### ISSUE TITLE
Characters in coordinate.toStringHDMS() should be configurable

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#1175]
At the moment, this is limited to NSEW, but this is specific to English, and should be configurable to suit other languages.

**Comment by ahocevar** [comment]
The function is well documented, and it is only used in two examples. For things like the mouseposition control, the output format can be configured with a function. If the function wasn't marked stable, I'd remove it. But I think it is unimportant enough to keep it as simple as it is, and continue to have it work like documented.
