### ISSUE TITLE
Re-render on vector change

### ISSUE THREAD

**Issue by crepererum** [openlayers/ol3#1831]
**Environment:**
 - ol3 version: HEAD
 - renderer: canvas
 - layer: vector, driven by a vector source
 - vector source: just a list of some features (also tested with only 1 feature)

**What my script does:**
  1. Update the feature vector by removing and adding a feature
  2. Fix: call `map.renderSync()`
  3. Start a pan animation to a new center using `ol.animation.pan` and `map.beforeRender`

```javascript
source.removeFeature(last);
last = new ol.Feature({
    geometry: new ol.geom.Point(nextCenter)
});
source.addFeature(map.olfeature);

map.renderSync(); // fix

pan = ol.animation.pan({
    duration: 1000,
    source: view.getCenter(),
    start: nextCenter
});
map.olmap.beforeRender(pan);
view.setCenter(nextCenter);
```

**Expected behavior without fix (step 2):**
Feature changes get immediately shown on the map and animation just plays.

**Actual behavior without the fix:**
Animation plays and *after* it has finished the feature changes are shown. So during the animation the old feature vector is displayed.

**Notes:**
The fix works well if the feature has a `ol.geom.Point` geometry but sometimes does not when using `ol.geom.Circle`.

**Comment by ahocevar** [comment]
Setting the `updateWhileAnimating` option of `ol.layer.Vector` to `true` should fix this issue.
