### ISSUE TITLE
issue with overlay positioning

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#1846]
This jsfiddle shows a label at the center of the map, however when you zoom in the label will move north of the road:

http://jsfiddle.net/mendietj/S6TPP/

Reported on the ML as:

https://groups.google.com/d/msg/ol3-dev/HeHMk9L2aSw/d4RGSulxCdgJ

**Comment by fredj** [comment]
`positioning: 'center-center'` fixes the issue, see http://jsfiddle.net/S6TPP/29/
