### ISSUE TITLE
"movable map" issue on firefox

### ISSUE THREAD

**Issue by legrostdg** [openlayers/ol3#1862]
On firefox 24, opening http://ol3js.org/en/master/examples/full-screen.html and pressing my keyboard down key I get this:
![gray-band](https://f.cloud.github.com/assets/372337/2422114/e4028de8-ab8a-11e3-8d1c-3cdea7ea9cad.png)
(notice the gray band under the map). It's like if I could move the map of maybe 5 pixels up in its containers.

Chrome does not seem to be affected by this bug. 

All the maps where the complete page has a height under 100% seem to be affected.

**Comment by fredj** [comment]
can't reproduce the issue with a recent version of firefox
