### ISSUE TITLE
ZoomToExtent and ZoomSlider overlap on each other

### ISSUE THREAD

**Issue by qianyanseu** [openlayers/ol3#2046]
The built in control.ZoomToExtent() and control.ZoomSlider() would overlap on each other when added to the same map.

I tried to add them in different sequences, but the issue continued. The latter added one would always appear on top of the former added one.

Can I put the zoom slider somewhere else by passing some parameters when creating it using the following code?
`map.addControl(new ol.control.ZoomSlider());`

![image](https://cloud.githubusercontent.com/assets/1569368/2899508/d01c4a1a-d5b7-11e3-885a-e6462a70aa00.png)

**Comment by zalf** [comment]
I would like to know that too!

**Comment by qianyanseu** [comment]
@zalf Finally someone replied, more than one year later...

My solution is stopping using `ZoomToExtent` control.

**Comment by marcjansen** [comment]
I should be doable with CSS. Have you tried that?

**Comment by zalf** [comment]
I like to try it with CSS, but I don't know how.

**Comment by qianyanseu** [comment]
It's been too long. No longer have the access to the codes. Can't recall the details.



—

**Comment by marcjansen** [comment]
You could try:

```css
.ol-zoomslider {
   top: 110px; /* or whatever you want */
}
```

See: http://jsfiddle.net/hk1nrekq/

**Comment by zalf** [comment]
Ok, that loks good. And, stupid question, do I have to put a reference in the html file to "ol-zoomslider"?

**Comment by zalf** [comment]
I just tried it, it works without further references! Thank you very much!
