### ISSUE TITLE
Building OL 3 since beta 5 on Windows

### ISSUE THREAD

**Issue by Dzermin** [openlayers/ol3#2100]
Having asked about building OL 3 Beta 5 (and newer), Tim suggested I should post here with some details auot my build set up. The original thread is: https://groups.google.com/forum/#!topic/ol3-dev/_xlHpp8Gm9o

 * Windows version - 
Win 7 SP1
 * Node version (run `node --version`) 
v0.10.28
 * OL3 version (run `git rev-parse HEAD` from a git clone) 
81523091f0a6222f07ba5c7139da79f8f64784cf

node tasks\generate-exports.js build\exports.js 
Yields the same error as just trying to build it, i.e.

C:\OL3buildstuff\ol3sourcecode>node tasks\generate-exports.js build\exports.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)

---

Prior to failing to build beta 5 I've been following the hints at this blog http://www.spatially-oriented.com/blog/2013/12/13/building-openlayers-3-on-windows/#comment-1397158447 which made it possible for me to build OL 3 on Windows.

Grateful for any help!

**Comment by GuillaumeSmaha** [comment]
Hi !

I just used the patch from probins/ol3@29a420c, and probins/ol3@90a8263 and it's work for rev b6adeea4f4cb31fbd0976ad1d91e70c1c66f39c7

**Comment by andreasrueedlinger** [comment]
Any chance of getting in the patches as a pull request?

**Comment by photostu** [comment]
In the end for me, it was easier setting up a Linux VM to build on. Just my .02 for others that run into this.

**Comment by soletan** [comment]
Ridiculous ... thank god we don't need to take care of 8.3 filename format as well! What is this issue about? Coding in the 1970s? What professional developer decided to have all filenames passed on command line? This is definitely about bad software design ...

The quick workaround on using flagfile didn't work for me as compiler.jar is obviously complaining about some unknown configuration option "--" listing all valid options (not including flag file) ... so two issues keeping that workaround from working here: 1) flag file isn't support 2) compiler.jar seems to have minor issue in parsing command line switches

My instant quick fix: not using OpenLayers.

**Comment by marcjansen** [comment]
Which PR is that exactly, that we didn't 'obey'? Does it still apply cleanly and is it confirmed that it wirks on all platforms?

We are mostly developing on non-windows machines, and therefore ai find it only natural, that we didn't scratch what didn't itch us.

I think no one would be against a solution tht works everywhere.

**Comment by probins** [comment]
https://github.com/openlayers/ol3/pull/2593

**Comment by marcjansen** [comment]
Thanks, @probins. I'll try to evaluate that and https://github.com/openlayers/closure-util/pull/63.

**Comment by guidoheckmann** [comment]
I tried all examples for creating custom OpenLayers builds on Windows 8.1 and none of them worked.
Error message is nearly the same in all cases:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENAMETOOLONG
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

In my opinion there should be a good solution for this problem after more than a year this issue is existing. Not?

**Comment by probins** [comment]
this should now work with the latest master with the new version of closureutil

**Comment by guidoheckmann** [comment]
I have it now!
For me it didn't work with the latest version. I tried "npm install openlayers --save". This installed a version "1.5.0" of closure-util.
Changing the config like explained in "https://github.com/openlayers/closure-util" and executing "closure-util update" changed nothing.
So I downloaded the latest zip file of closure-util from "https://github.com/openlayers/closure-util" and copied the files into directory "node_modules/openlayers/node_modules/closure-util" of my application. After that the build command succeeded.

**Comment by elemoine** [comment]
On Fri, Aug 28, 2015 at 11:52 AM, guidoheckmann
<notifications@github.com> wrote:
>
> I have it now!
> For me it didn't work with the latest version. I tried "npm install openlayers --save". This installed a version "1.5.0" of closure-util.
> Changing the config like explained in "https://github.com/openlayers/closure-util" and executing "closure-util update" changed nothing.
> So I downloaded the latest zip file of closure-util from "https://github.com/openlayers/closure-util" and copied the files into directory "node_modules/openlayers/node_modules/closure-util" of my application. After that the build command succeeded.


Try with the latest closure-util version: 1.6.1.
<https://www.npmjs.com/package/closure-util>



-- 
Eric Lemoine

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : +33 (0)4 58 48 20 34
Mail : eric.lemoine@camptocamp.com
http://www.camptocamp.com

**Comment by probins** [comment]
can this one be closed?

**Comment by ahocevar** [comment]
Outdated, closing.
