### ISSUE TITLE
Add pixel tolerance to hit detection

### ISSUE THREAD

**Issue by elemoine** [openlayers/ol3#2105]
The hit detection mechanism could work with a pixel tolerance. This would make it easier to select thin (1 pixel wide) lines on touch devices.

**Comment by colouredFunk** [comment]
Desperately need a solution to this as well. Feature icons/labels on a tablet devices are very hard to click.

**Comment by colouredFunk** [comment]
Has this been resolved in any of the updates

**Comment by giohappy** [comment]
Has anyone worked on this? It's a very important issue. In case we could fund it.

**Comment by tschaub** [comment]
Fixed by #5995.
