### ISSUE TITLE
ol.xml.parse crashes in IE9

### ISSUE THREAD

**Issue by jacmendt** [openlayers/ol3#2154]
It looks like the code from ol.xml does not work with IE9. After a bit debugging some problems arise from the method ol.xml.parse . The problem arises from property names, like "localName" which is in IE "baseName", "firstElementChild" --> "firstChild" and "nextElementSibling" --> "nextSibling". Also my IE version seems to have problems with the method ol.xml.getAttributeNS_ through the missing of the node.getAttributeNS method. Propably there are more snares. 
Kind regards, JM

**Comment by bartvde** [comment]
@jacmendt is this still the case with the latest version?
If so could you provide a test case?

**Comment by jacmendt** [comment]
@bartvde when i am back in office i will check this and give you known

**Comment by jacmendt** [comment]
@bartvde I tested it today with a recent build of ol3 and now i got with my test case no more problems in IE9. So this ticket could be closed. Thanks a lot.

**Comment by bartvde** [comment]
thanks for confirming @jacmendt
