### ISSUE TITLE
Allow popups to live outside the map div

### ISSUE THREAD

**Issue by nidico** [openlayers/ol3#2180]
This is a copy from [OL2 trac ticket #1727](http://trac.osgeo.org/openlayers/ticket/1727):

> In the case where users have a small map div, it would be nice if they could have their popups go beyond the restrictive limits of the map div... ie live outside the openlayers div itself.
>
> The complication of this is that it will be more difficult for the popup to move with the map as it is panned.
>
> To get a quick solution working, we can make the default behavior for these popups be to disappear when the map is panned (see [~~#1726~~](http://trac.osgeo.org/openlayers/ticket/1726))

The unsettled question is what to do with popups if the referred marker is moved out of the map entirely. This alone makes the whole feature questionable; however it would still be useful in certain cases (e.g. if the map viewport is constant). Alternatively, as proposed in the original ticket, the popup could just disappear if the map is panned or zoomed.

As I'm interested in this feature as a user (designers *always* design popups that way!), I'm curious to hear from developers side:

* Is this desired at all, taking into account the open question above; i.e. would you accept a pull request?
* What would be the rough sketch to implement this?

**Comment by fredj** [comment]
Removing `overflow: hidden` from the `.ol-viewport` works
