### ISSUE TITLE
ol.View#calculateExtent doesn't take rotation into account

### ISSUE THREAD

**Issue by elemoine** [openlayers/ol3#2195]
Currently the `ol.View#calculateExtent` [function](https://github.com/openlayers/ol3/blob/master/src/ol/view2d.js#L247-L256) does not take the view rotation into account. That function calculates the minimal geographic extent that covers the passed pixel box, so it sounds to me that it should take the view rotation into account.

**Comment by fredj** [comment]
Fixed with e7cd691362c3727df3eb0570e7120cc91edb56e3
