### ISSUE TITLE
DOM rendererer doesn't support layers with min and max resolution

### ISSUE THREAD

**Issue by cedricmoullet** [openlayers/ol3#2262]
The example http://ol3js.org/en/master/examples/min-max-resolution.html works well with canvas and webgl renderer. The dom renderer doesn't take in account the min and max resolutions set on the layer level.

**Comment by fredj** [comment]
fixed
http://openlayers.org/en/v3.13.1/examples/min-max-resolution.html?mode=raw&renderer=dom
