### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#2314]
https://github.com/openlayers/ol3/blob/master/src/ol/renderer/canvas/canvastilelayerrenderer.js#L253

On Chrome 35.

This seems to be a similar error to one reported recently for GMaps with Chrome https://code.google.com/p/chromium/issues/detail?id=373153

prepareFrame() is described in the source as a 'dangerous zone', so I shan't attempt to fix. :-) But as with comment 25 on the GMaps issue, the code looks dodgy to me. Both width and height are calculated via division, which seems to be creating a fraction, which is then passed to `new Array()`.

An example is at http://maps.peterrobins.co.uk/files/gb.html (and gb.js), using simple build which is a bit easier to follow. If you zoom all the way in and then back out again, you should see the problem. This server is an oddity, in that the tilegrid has differing tile sizes for different resolutions. I would guess that the problem is related to this - does the cache need clearing? Whatever the cause, ISTM the code should be changed so that the array is always created with an integer, not a float.

**Comment by bill-chadwick** [comment]
in ol.renderer.canvas.TileLayer.prototype.prepareFrame

patching 

    if (this.canvasSize_[0] < canvasWidth ||
        this.canvasSize_[1] < canvasHeight ||
        (this.canvasTooBig_ && (this.canvasSize_[0] > canvasWidth ||
        this.canvasSize_[1] > canvasHeight))) {
      // Canvas is too small, resize it. We never shrink the canvas, unless
      // we know that the current canvas size exceeds the maximum size

to

    if (this.canvasSize_[0] < canvasWidth ||
        this.canvasSize_[1] < canvasHeight ||
        this.canvasSize_[0] % tilePixelSize != 0 ||
        this.canvasSize_[1] % tilePixelSize != 0 ||
        (this.canvasTooBig_ && (this.canvasSize_[0] > canvasWidth ||
        this.canvasSize_[1] > canvasHeight))) {
      // Canvas is too small or not a multiple of tilePixelSize 
      // (tileSize changes by z), resize it. We never shrink the canvas, unless
      // we know that the current canvas size exceeds the maximum size

fixes the problem, by detecting that the existing canvas is not a multiple of the new tile size

**Comment by bill-chadwick** [comment]
This ties in with the comment at the start of the function

'Note also that the canvas always contains a whole number of tiles.'

**Comment by elemoine** [comment]
It looks like you spotted the bug! Good job! Do you plan to create a PR for that?

**Comment by bill-chadwick** [comment]
I am a bit of a newbie with the GitHub stuff so would rather someone else did it for now.

**Comment by elemoine** [comment]
Alright, you did your part I guess :-)

**Comment by bill-chadwick** [comment]
I have attempted a Pull Request for this. Hope I did it right - let me know if not.
