### ISSUE TITLE
complete modify example

### ISSUE THREAD

**Issue by barbalex** [openlayers/ol3#2384]
Hi core ol3 coders

Thanks for this great tool!

I have a hard time getting this working:

1. There is a vector layer in the map with own data
2. Users can select features, create new ones and modify existing ones
3. Whenever a new feature is created or an existing one modified, an event is triggered that can be used to update the data in the database or geojson-file

The hard part is getting the interactions for select, modify and draw to work together on the same source and get a "modified" event when modifying.

It seems to me that this is a very typical use case that many people will try to implement.

Please consider adding such an example.

**Comment by tschaub** [comment]
Pull requests for improved documentation or examples are always welcome.
