### ISSUE TITLE
Wrap builds with UMD for use in Browserify, Node, etc..., add documentation

### ISSUE THREAD

**Issue by wavded** [openlayers/ol3#2430]
This case stems from @tschaub comments in https://github.com/openlayers/ol3/issues/317#issuecomment-49826602 :

> I think it does make sense to open another ticket to always wrap builds in a way that only assigns to the global if module (et al.) is not defined. We can also include documentation on proper use of ol3 builds with Browserify.

Seems like a common [UMD wrapper](https://github.com/umdjs/umd) would support all the use cases.

One question I would add is, can an npm installable package be added?  Maybe a separate builds repo?

**Comment by fredj** [comment]
Fixed with #3039
