### ISSUE TITLE
Using OL3 with Sencha touch 2.3.1

### ISSUE THREAD

**Issue by ayushpurohit05** [openlayers/ol3#2507]
Hello Sir/Ma'am,

As we are using OL3 (v3.0.0-gamma.3) with sencha touch 2.3.1 in the sencha touch application.

1. We are facing issue when click on the OL3 map (implemented with sencha touch 2.3.1 app), which is throwing error in console every time:-
Uncaught TypeError: undefined is not a function ol.js:514
We tried to resolve this and recheck the code many times that whether we are missing something in the code or doing anything wrong but nothing was there.

After doing lot of rework I found that when we remove the script tag 

<script id="microloader" type="text/javascript" src=".sencha/app/microloader/development.js"></script>

from our index.html (means not loading sencha library files) it works well and not throwing the above error when clicking on the map, also fires "onclick" function of the OL3 map 

olMap.on('click', function(evt) {
    var feature = olMap.forEachFeatureAtPixel(evt.pixel, function(feature, layer) {
        return feature;
    });
    Ext.Msg.alert('Hey','Map click working');
    //do the stuff here
});

But unfortunately doesn't work when we again include the above script tag in the index.html

2. One more thing we tried with OL3 map and sencha touch as below:-

var vector = new ol.layer.Vector({
    source: vectorSource,
    style: new ol.style.Style({
        fill: new ol.style.Fill({color: 'rgba(0, 0, 255, 1)'}),
        stroke: new ol.style.Stroke({color: 'green', width: 10})
    })
});

With the above code we tried to display vector layer on the ol map and specify the stroke color as "green" and fill color as "blue" (color: 'rgba(0, 0, 255, 1)') for the vector layer.
The vector layer displays properly on the map with the stroke color "green" but the fill color not appearing on the layer.
Same thing as we explained in the point 1, we removed the script tag and the fill color property works but not when we include the script tag in the index.html

Attached is the screen shot of the stuff we do with OL3 map in the sencha touch 2.3.1 app with the console error when we click on the map.

![screenshot-from-2014-08-06-16 3a28 3a111](https://cloud.githubusercontent.com/assets/1401652/3854860/2c2f31d2-1edd-11e4-97fd-4381e6da125c.png)

It seems that OL3 is not working with Sencha or there is some conflict. Please let us know the solution so we can use both.

Thanks

**Comment by fredj** [comment]
(probably) fixed with #2501

If not, add a comment in this issue
