### ISSUE TITLE
WMTS fails when no projection extent

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#2623]
This is a regression introduced with https://github.com/openlayers/ol3/commit/caa0b568ade5f9277df3e2f06e488abbe7bea1e0

Used to use source.extent; now uses projection.extent, but most projections don't have an extent, so fails at https://github.com/openlayers/ol3/blob/master/src/ol/source/wmtssource.js#L171 'cannot read property of null'.

Source/layer extent here is what the server supports (in the capabilities); if this is defined on the layer, then the tileUrlFunction should be using that, not the projection (though that might be a good default if it's not null).

Workaround for the moment is to set the projection extent to the server extent before creating the layer/source.

**Comment by ahocevar** [comment]
This was fixed with #3639.
