### ISSUE TITLE
TileCache corruption and unhandled exception

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/ol3#2646]
I was playing around with lower ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK values because the default 2048 can become very big (multiple gigabytes) with many tiled layers.

With ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK set to a rather low value like 32 after a while zooming and panning no new tiles are loaded and cached tiles will dissapear gradually when zooming panning leaving a blank map. Some time after this behaviour I noticed errors in the console log and looking into them I find that usedCache can become undefined here:
https://github.com/openlayers/ol3/blob/master/src/ol/tilecache.js#L48 which will be logged as an console message similar to "Uncaught TypeError: Cannot use 'in' operator to search for '9' in undefined." in Chrome.

I've tried to reproduce directly in ol3 examples (Stamen and WMS tile) by pausing and setting ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK to 32 I get the same unwanted behaviour just after a short while panning and zooming but as of yet I haven't been able to reproduce the unhandled exception in those examples.

I've reproduced this error multiple times on Chrome 36 in Linux but have heard reports of the same in Chrome OS X and Internet Explorer on Windows.

I have not been able to reproduce anything with the default ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK but perhaps it's just a matter of time panning and zooming a heavy tiled map.

**Comment by illogicz** [comment]
Running into this exception as well. Seems to occurs when erratically zooming without giving tiles time to load. Not easy to reproduce however. Chrome 45.

**Comment by fredj** [comment]
fixed with #5051
