### ISSUE TITLE
command-line parameter for build.js to get debug version

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#2709]
If I have understood things correctly, I currently need to edit my build JSON and get rid of the compile section (or rename it) to get a debug output.

It would be more convenient to have a flag on the command-line instead of changing the JSON file.

**Comment by tschaub** [comment]
For now, you can do this to get a debug build:
```
node tasks/build.js config/ol-debug.json ol-debug.js
```

**Comment by bartvde** [comment]
Right but my ticket was more about a debug version of a custom build profile
