### ISSUE TITLE
Tile wrapping issue at 180th/Anti meridian in OL3

### ISSUE THREAD

**Issue by SpidermanInAK** [openlayers/ol3#2712]
OL no longer honors the "wrapDateLine" parameters of the WMS Tile requests. Attached image shows continuous polygonal data split at the meridian (red circles). (http://dnr.alaska.gov/mdfiles/img/canvas.png).

**Comment by kagyuu** [comment]
I have same problem. I want to upgrade our geospatial applications base OL2 to OL3.
But only the degrade that ol.layer.Tile of OL3 lacks wrapDateLine option disturb it.
Please fix it.

**Comment by SpidermanInAK** [comment]
Last I heard from Andreas was that this issue was likely to be worked on
during the code sprint in March/April of this year.

We are eager to get this resolved too as it is holding up our much
anticipated move to OL3.

**Comment by amosparovel** [comment]
It is a crucial Point, especially when dealing with New Zealand and Antactica

**Comment by icebreakerPNRA** [comment]
+1; I agree with SpidermanInAK: ee are eager to get this resolved in order to move to OL3.

**Comment by myspivey** [comment]
+1, working with a brand new install of ol3 and discovered this one. Could be a major setback having to downgrade to ol2.

**Comment by SpidermanInAK** [comment]
I asked Andreas Hocevar about this last year and he assured me that it would get worked on this spring. We even offered money. But neither this ticket or the similar one (#999) has been pulled into a milestone.  :(

With that said, since we are using GeoWebCache as a proxy for all our data, I figured out a workaround and we are moving ahead with OL 3 development.  We hope eventually they will fix this.

**Comment by ahocevar** [comment]
I have started working on this for `ol.source.TileWMS`.

Note that most WMS servers (e.g. GeoServer) already support wrapping the x-axis in ol3, because they accept coordinates outside the world bounds. I have created a JSFiddle that shows this: http://jsfiddle.net/jt1pc7jv/.
