### ISSUE TITLE
ol.overlay.Popup implementation

### ISSUE THREAD

**Issue by walkermatt** [openlayers/ol3#2778]
Hi,

A little while back I [posted to the OL3 Dev list](https://groups.google.com/d/msg/ol3-dev/gk68eWkuMVs/69d0_Bjv2TAJ) details of a [popup implementation] (https://github.com/walkermatt/ol3-popup) and there was some discussion about the possibility of it being incorporated into the core.

I've moved the popup into [a branch in my fork of ol3](https://github.com/walkermatt/ol3/tree/popup). It's largely based on the example provided by @tschaub but I've now made use of the Closure library, implemented panIntoView functionality, provided docs and updated the [popup example](https://github.com/walkermatt/ol3/blob/popup/examples/popup.js).

Before I go much further I though it would be worth asking about the likelihood of it being incorporated in the core and if that's a possibility some guidance around tests etc.

Thanks,

Matt.

/cc @elemoine

**Comment by fredj** [comment]
`autoPan` has been added to `ol.Overlay` in #3256
