### ISSUE TITLE
Fix failing ol.format.GPX tests (Chrome)

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#2783]
The tests

* ol.format.GPX
  * readFeatures
    * rte
      * can transform, read and write a rte
    * trk
      * can tranform, read and write a trk with a trkseg

Fail for me due to precission / rounding issues of the coordinates in the written GPX. This happens in  Chrome 33 Linux:

> Attribute value test failed for: rtept | expected '5' to equal '5.000000000000028'
> ...
> Attribute value test failed for: trkpt | expected '5' to equal '5.000000000000028'

We use our own `xmleql`-method for the assertion, so this may be harder to fix than one would first think...

**Comment by bartvde** [comment]
@marcjansen this was fixed right? Can we close it?

**Comment by marcjansen** [comment]
In the old chrome this can still be reproduced, in 41 the problem is gone.
