### ISSUE TITLE
Freehand Drawing with ol.interaction.Draw

### ISSUE THREAD

**Issue by shaunakv1** [openlayers/ol3#2826]
New Feature request:

I was trying out the ol.interaction.Draw feature in Openlayers 3 and couldn't find a way to do freehand drawing like in OpenLayers 2.  Is this possible currently in OpenLayers 3? If not is there a plan to add? 

Here's an example of what I am trying to do implemented in OpenLayers 2

http://www.codechewing.com/demo/openlayers/freehand-mode-with-openlayers-draw-line.html

I started this question on google group and looks like , this feature does not exist yet. Just wanted to put in a feature request here.

Issue on google group:

https://groups.google.com/forum/#!topic/ol3-dev/Hxri0Qx0gPU

**Comment by greggian** [comment]
+1 This was a very useful feature in OL2.

**Comment by 1Map** [comment]
Agree, OL3 is also lacking the ability to draw a hole in a polygon (donut). With OL2 this was possible by holding Alt key and drawing hole inside an existing polygon.

**Comment by ahocevar** [comment]
See #3616 for a pull request that implements freehand drawing.
