### ISSUE TITLE
Incorrect rendered Extent of ImageStatic

### ISSUE THREAD

**Issue by chird** [openlayers/ol3#2844]
If I add an ImageStatic to a Map, its rendered too wide (in horizontal direction). Its maxx (right extent) appears at the false position.

Example: http://jsfiddle.net/u7xyor0t/1/

The Image is intended to reach from 8° to 9° East. But its right border appears at about 9.5° E... (you can check this with the Mouse Position)

**Comment by bartvde** [comment]
working on a PR for this one now
