### ISSUE TITLE
Zoom box persists with DOM renderer

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#2873]
With #2690 (which looks very nice) we now magically get a drag-zoom box.  However, the zoom box persists after being rendered.  This can be reproduced by opening the [simple example with the DOM renderer](http://openlayers.org/en/master/examples/simple.html?renderer=dom) and shift-dragging to zoom in.

Since we now have a working zoom box with the Canvas renderer, a partially working one with the DOM renderer, and nothing with the WebGL renderer, I still think we'd be better off using a simple DOM element for the box.

My main arguments:
 * we could have it working consistently, everywhere, right now
 * nobody is going to guess how to restyle the box (see https://github.com/openlayers/ol3/issues/1583#issuecomment-34094420)
 * there is no reason to require that people bring in all of the vector rendering code to draw a box on the map

**Comment by ahocevar** [comment]
Fixed with #4278.
