### ISSUE TITLE
ol.proj.transform returns wrong coordinates

### ISSUE THREAD

**Issue by acidicX** [openlayers/ol3#2876]
Hi there,
I just followed the quickstart:
http://openlayers.org/en/v3.0.0/doc/quickstart.html
and changed the center coordinates to Berlin:

`center: ol.proj.transform([52.50, 13.37], 'EPSG:4326', 'EPSG:3857');`

But the map shows Africa/Middle East, which is clearly not Berlin. At least not on OSM or MapQuest. The function returns:

`Array [ 5844273.266646863, 1502035.739341348 ]`

Is the projection transform function broken or am I missing something? Center works correctly when using the right EPSG 3857 coordinates.

**Comment by bharathnav** [comment]
Hi I'm currently implemeting opelayers 3 but am unable to use ol.transform method . It say ol is not defined. I tried many ways but could not fix that. I'm new to this could someone help me on this please.

Thanks in advance,
Barry

**Comment by acidicX** [comment]
@bharathnav this means you have no openlayers instance. As this is clearly not a bug, please try posting it on StackOverflow to get help. https://stackoverflow.com/questions/tagged/openlayers-3

**Comment by ThomasG77** [comment]
It has always been (lng, lat). (lat, lng) is not the norm (your norm if you come From Leaflet or Google Maps :) )
In fact, not so simple >> https://macwright.org/lonlat/
For an explanation about the why (lng, lat) in OpenLayers, see also the [FAQ](http://openlayers.org/en/latest/doc/faq.html#why-is-the-order-of-a-coordinate-lon-lat-and-not-lat-lon-)
