### ISSUE TITLE
ol.DrawEvent not implemented by ol.interaction.Modify

### ISSUE THREAD

**Issue by awahab07** [openlayers/ol3#2946]
ol.DrawEvent is implemented by ol.interaction.Draw but ol.interaction.Modify is not implementing any event from ol.DrawEvent neither it has its own event type.

ol.interaction.Modify changes geometry of features and both features and geometry can be observed by listeners but it becomes crucial at certain points to hook up certain functionality when the ol.interaction selects, starts, ends and leaves the feature for modification.

It will be desired if ol.interaction.Modify maintains certain attributes in order to allow Undo / Redo functionality implementation compact.

**Comment by ttsiodras** [comment]
I know this is sacrilege, but since there was no response all this time... I hacked it: 

    ol.interaction.Modify.prototype.handlePointerUp = function(evt) {
      inModifyMode = false;
      var segmentData;
      for (var i = this.dragSegments_.length - 1; i >= 0; --i) {
        segmentData = this.dragSegments_[i][0];
        this.rBush_.update(ol.extent.boundingExtent(segmentData.segment),
            segmentData);
      }
      // ttsiod ugly patch here
      this.map_.npMap_.modified();
      // ttsiod ugly patch ends
      return false;
    };

When I create the map, I monkey-patch a reference back to my wrapper class:

    this.map = new ol.Map({
    ...
    });
    this.map.npMap_ = this;

...and I now have callbacks into my class's `modified()` callback, emulating the missing 'modifyend' event.

**Comment by awahab07** [comment]
I appreciate @ttsiodras's approach. But if you can't afford overriding ol.interaction.Modify.prototype.handlePointerUp, you can follow the approach implemented in http://erilem.net/ol3/drag-features/examples/drag-features.html

To mention specifically look how app.Drag.prototype.handleUpEvent is implemented to nullify a reference when drag is complete. I think this is the location that @barbalex needs.

**Comment by carueda** [comment]
:+1: for this request, in particular for ability to listen to a specific event triggered when a modification (vertex has been moved, vertex has been added, or vertex has been deleted) has finished.

**Comment by elemoine** [comment]
Closed with https://github.com/openlayers/ol3/pull/3461.
