### ISSUE TITLE
add custom CRS/SRS parameter to ImageWMS

### ISSUE THREAD

**Issue by relet** [openlayers/ol3#2966]
Occasionally, you may want to override the CRS/SRS code generated by the ImageWMS data source, for example when "similar enough" projections have different codes, and the projection code used in your view differs from the ones supported by the server. 

The same goes for probably all ol.source types which cannot be reprojected. 

    /* monkeypatch for ol.source.TileWMS.getRequestUrl_ to support custom CRS ***/
    ol.source.ImageWMS.prototype.getRequestUrl_orig = ol.source.ImageWMS.prototype.getRequestUrl_ ;
    ol.source.ImageWMS.prototype.getRequestUrl_ = function(extent, size, pixelRatio, projection,  params) {
      if (!!this.getProjection()) {
        projection = this.getProjection();
      }
      return this.getRequestUrl_orig(extent, size, pixelRatio, projection, params);
    };

**Comment by fredj** [comment]
fixed with #2985
