### ISSUE TITLE
set up a better export map example using canvas.toBlob instead of canvas.toDataURL

### ISSUE THREAD

**Issue by barbalex** [openlayers/ol3#2968]
The official export map example (http://openlayers.org/en/v3.0.0/examples/export-map.html) uses canvas.toDataURL to export. This is very unreliable as the browser crashes depending on size of the exported file. It was unusable for us.

I've managed to circumvent this by using canvas-toBlob (https://github.com/eligrey/canvas-toBlob.js) and FileSaver.js (https://github.com/eligrey/FileSaver.js).

See the example here: http://codepen.io/barbalex/pen/raagKq

I have successfully downloaded 8MB png-files using this method.

**Comment by richardjr** [comment]
Just to add further weight to this as I got here after implementing the ol3 example which causes chrome to crash pretty much all the time if your using multiple layers. @barbalex  example works flawlessly so maybe the ol3 example could be updated with both methods?

A native example then a link to his example using external libs.

**Comment by barbalex** [comment]
The libs are only there only used  to implement standard HTML5 methods in browsers that don't yet implement them. In a little while they will not be necessary any more

**Comment by probins** [comment]
Chrome/ium recently decided to implement toBlob https://code.google.com/p/chromium/issues/detail?id=67587#c101

**Comment by jonataswalker** [comment]
@barbalex may you update your codepen changing:

`http://ol3js.org/en/master/build/ol.js` to `//openlayers.org/en/master/build/ol.js`
and
`http://ol3js.org/en/master/css/ol.css` to `//openlayers.org/en/master/css/ol.css`

For some reason you have 404 for those urls.

**Comment by barbalex** [comment]
Yes, will do it next week. Am on vacation now. Thanks! Will also build examples without libraries and test them on different browsers

**Comment by barbalex** [comment]
I changed the ol3-links in http://codepen.io/barbalex/pen/raagKq so the example works again.

I understand @elemoine now: the example does not work with firefox in codepen.io. There seems to be an issue with Content Security Policy. It works in firefox in my web-app though.

Unfortunately this prevents me from testing the example without using https://rawgit.com/eligrey/canvas-toBlob.js/master/canvas-toBlob.js as firefox is the only browser I know that supports canvas.toBlob so far.

**Comment by barbalex** [comment]
The example works on firefox without https://github.com/eligrey/canvas-toBlob.js, using native canvas.toBlob, see here: https://jsfiddle.net/oj7451L5/15/

**Comment by barbalex** [comment]
looks like the file-writer API has been descontinued: http://www.w3.org/TR/file-writer-api

so my solution will always use the external lib https://github.com/eligrey/FileSaver.js

**Comment by barbalex** [comment]
I checked the other tutorials (not having known them before). As defined ("For a more in-depth overview of OpenLayers 3 core concepts, check out the tutorials."), they are more in depth and explain core concepts.

So to me as an "outsider" it would seem much more logical to find an example using FileSaver.js and canvas.toBlob in the examples.

Also, the code needed is fairly short and even with some explanations will not be longer than most examples - even shorter than the other export map example using canvas.toDataURL.

Personally I would add a link from each example to the other and explain the differences.

**Comment by barbalex** [comment]
I checked the contributing guide. Sorry: There's too much that's new to me and I work on windows so I won't try to add an example.

**Comment by Anupam-** [comment]
If there are more then 1 layer is open then  toDataURL() throw a security exception for map canvas. Is it possible to use your solution for this,but it seems toDataURL() uses toBlob() internally.

**Comment by richardjr** [comment]
Are you seeing the tainted canvas error?

If so then both methods will experience this problem. Its because you are
loading layers from different URLS EG cache1.domain.com & cache2.domain.com
and so far I have not come across a way around this even with full CORS
setup. You could proxy all your calls via a single URL but this isn't
really a good solution for improving tile request speeds.

If anyone has any ideas on solving this I'm happy to spend some time on it
and posting any solution back to the community.

**Comment by Anupam-** [comment]
No I am not getting tainted canvas error. error says : 'Error: The operation is insecure.' in Mozilla  and in IE11 its says 'SecurityError'

**Comment by richardjr** [comment]
Yeah that's the same issue, I think the error message in chrome is
different.

See this similar issue:
http://stackoverflow.com/questions/25753754/canvas-todataurl-security-error-the-operation-is-insecure

Basically as I understand it any data that ends up on the canvas from a
location outside your origin taints the canvas as insecure. In theory this
should be solved by having a correctly setup CORS policy on the end points
but so far I haven't been able to get that to work with the canvas despite
all the other CORS related functions working correctly.

**Comment by ca0v** [comment]
I think ol3 needs is a proxy setting.  It is not always possible to simply prefix an proxy to the layer endpoint.  For example,  [ol.source.ImageArcGISRest](https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/source/imagearcgisrestsource.js#L212), will find the "?" in the proxy and use "&" on the first argument.

Each layer with crossOrigin: 'anonymous' set (or maybe just proxy: true) would be proxied if a proxy is set.  The goal being that canvas.toDataURL should not fail due to CORS security.

**Comment by ca0v** [comment]
Well, this worked for my test cases so maybe it's not so bad:
```
    ol.source.Image.defaultImageLoadFunction = (image: {
        getImage: () => HTMLImageElement
    }, src: string) => {
        image.getImage().src = proxy + src;
    };
```
