### ISSUE TITLE
Text "rotateWithView" Request

### ISSUE THREAD

**Issue by gDelandro** [openlayers/ol3#3005]
Is it possible to add rotateWithView to the text style parameters?
Also a scaleWithView would be very useful for Text as well as Icons.

Currently trying to use vector data to label things like streets is not possible to do well.
I know you might say just use a WMS or OSM tiles but on my project that's not really an option.

**Comment by coastforge-tdo** [comment]
+1

**Comment by jgalrito-i9** [comment]
+1
