### ISSUE TITLE
Reduce size of release archive

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3078]
The release archive we generate is 19MB.  I think it would be nice to reduce the size of this.

Here's the uncompressed size from the v3.1.0 release:
```
$ du -d 1 -h .
200M	./apidoc
4.3M	./build
 26M	./closure-library
4.0K	./css
 36K	./doc
7.9M	./examples
2.2M	./ol
520K	./resources
241M	.
```

**Comment by fredj** [comment]
Can we close this issue now that we have `vX.Y.Z-dist.zip` release archive?

**Comment by bartvde** [comment]
Sure, let's close this.
