### ISSUE TITLE
renderer to dom, draw features and GeoJson example broken on mobile

### ISSUE THREAD

**Issue by ChouGary** [openlayers/ol3#3087]
i tested two mobile deivce 
samsung S3 (android 4.1.2) => devicePixelRatio 1.3
HTC ONE M7 (android 4.4.4) => devicePixelRatio 1.5

http://openlayers.org/en/v3.1.1/examples/draw-features.html?renderer=dom
![screenshot_2014-12-25-18-39-18](https://cloud.githubusercontent.com/assets/8294943/5553691/899b1228-8c65-11e4-9c48-d8b983d8e7cd.png)
![screenshot_2014-12-25-18-45-44](https://cloud.githubusercontent.com/assets/8294943/5553723/f1eaf2ca-8c66-11e4-9e6f-86263dd8bdcb.png)

fiddle.jshell.net/67rrb6ge/show/
![screenshot_2014-12-25-18-30-04](https://cloud.githubusercontent.com/assets/8294943/5553661/930c64ca-8c64-11e4-98db-84ec8501d140.png)

**Comment by ahocevar** [comment]
Thanks @ChouGary for reporting this. See #3117 for a fix.
