### ISSUE TITLE
cant Drag and Modify features in the same time

### ISSUE THREAD

**Issue by ChouGary** [openlayers/ol3#3093]
cant Drag features example+Modify features example
http://fiddle.jshell.net/65hkL1w6/
step1->select polygonFeature 
step2->drag polygonFeature 
step3->modify polygonFeature 
result->modify ponit still old pos
![ol3_issue](https://cloud.githubusercontent.com/assets/8294943/5585272/344ee97c-90e1-11e4-8abf-b9559e021088.png)

**Comment by ahocevar** [comment]
I'm inclined to say that this is an application problem. Make sure the Modify interaction is not active on a feature that you are modifying (e.g. dragging) otherwise.
