### ISSUE TITLE
Add ol.Map#forEachLayerAtPixel function

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#3097]
From [this comment](https://github.com/openlayers/ol3/pull/1536#issuecomment-32457960) by @elemoine:

we've also considered adding `ol.Map#forEachLayerAtPixel`. This function will execute the user-provided callback for each layer that has a color for that pixel. This can be used in conjunction with GetFeatureInfo. For example:

```js
map.forEachLayerAtPixel(pixel, {
  layerFilter: function(layer) {
    return layer.getSource() instanceof ol.source.ImageWMS;
  }
}, function(layer) {
  var url = layer.getSource().getGetFeatureInfoUrl(coordinate,
      {INFO_FORMAT: 'text/plain'});
  // trigger GFI request
});
```

**Comment by bartvde** [comment]
I guess the pixel will need to be buffered somehow, since otherwise this will be very sensitive to non-exact touches on touch devices?

**Comment by elemoine** [comment]
> I guess the pixel will need to be buffered somehow, since otherwise this will be very sensitive to non-exact touches on touch devices?

A problem we already have when hit-detecting features.
