### ISSUE TITLE
olx.layer.TileOptions renaming issue

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#3103]
When the application code is compiled along with ol3, the `useInterimTilesOnError` and `preload` options are renamed by the compiler:
```javascript
new ol.layer.Tile({
  useInterimTilesOnError: false,
  visible: false,
  source: ...
})
```
Is compiled to:
```javascript
new Tj({ji: !1,visible: !1,source: ...})
```

**Comment by fredj** [comment]
`olx.layer.VectorOptions#renderBuffer` is also renamed

**Comment by elemoine** [comment]
Which is fine, no?

**Comment by tschaub** [comment]
This is actually the goal of `olx.js`.  We want to allow renaming when compiling together, but respect option property names when compiling the stand-alone library.

**Comment by fredj** [comment]
You're right; I was confused by the fact that `opacity` or `style` were not renamed in the build.

**Comment by elemoine** [comment]
`style` is a property of HTML elements, and `opacity` is a property of syles, so the compiler includes externs declarations that prevent renaming.

**Comment by fredj** [comment]
Thanks for the explanation
