### ISSUE TITLE
Vector Layers not Drawing during animated panning or mouse-drag events

### ISSUE THREAD

**Issue by stephenmartindale** [openlayers/ol3#3113]
It appears that features on an ol.layer.Vector are not painted or drawn during panning animations or mouse-drag events (in OpenLayers v.3.1.1)

To see the problem, take a look at: http://jsfiddle.net/StephenM/489aveLr/6/
![image](https://cloud.githubusercontent.com/assets/6370145/5703177/ef1559b2-9a5a-11e4-9184-bdbac3ac9abf.png)

If you zoom in on the rectangle covering Antarctica and use the mouse to pan around, you will see that the rectangle is only painted after the mouse button is released and the pan-animation has completed, whichever happens last.

I have tested in Internet Explorer and both Chrome and Firefox and the behaviour is the same.

**Comment by ahocevar** [comment]
See #2385.

**Comment by stephenmartindale** [comment]
Thanks, ahocevar.

From reading that linked thread and other discussions, this seems to be an issue with the behaviour of the Canvas renderer. Is there some way to work around the problem by rolling back to the SVG renderer or another older renderer, at least until your pull-request is merged and released?

I can't find any way to change renderers in v.3.1.1.

**Comment by ahocevar** [comment]
My pull request needs to be updated to address comments and code changes that have been made since. In the meantime, you can use a FeatureOverlay instead of a vector layer. There is no SVG renderer in ol3, and the WebGL renderer does not render polygons yet.

**Comment by elemoine** [comment]
And the WebGL renderer behaves the same: the batch is not recreated while interacting or animating.

**Comment by elemoine** [comment]
@ahocevar do you think we can close this?
