### ISSUE TITLE
Also add ol.css to the dist directory

### ISSUE THREAD

**Issue by elemoine** [openlayers/ol3#3115]
It looks like the `publish.sh` script just adds `ol.js` and `ol-debug.js` to the `dist` directory included in the node package. Shouldn't we add `ol.css` (both the minified and non-minified versions) as well?

**Comment by tschaub** [comment]
The [unminified version](https://github.com/openlayers/ol3/blob/master/css/ol.css) is already included, right?

Building a minified version in the dist directory is ok by me (I've been importing the `css/ol.css` and bundling/minifying it with other stylesheets as part of a build step).

Before we get too much duplication in `build` and `dist`, I'd like to lay out a plan for distributing the source and built examples, script(s), and stylesheet.

**Comment by elemoine** [comment]
> The unminified version is already included, right?

It's just not in the `dist` directory, where I was expecting it. And if we do add the minified version to `dist` I will expect even more to find the unminified version in that directory as well.
