### ISSUE TITLE
Feature hits overlay

### ISSUE THREAD

**Issue by yoan-m** [openlayers/ol3#3120]
Hello,

I have an issue when you modify a feature and it hits an overlay on the map.
http://jsfiddle.net/cp7a9phx/1/

Thank you.

**Comment by elemoine** [comment]
Please provide a description of the issue you're seeing.

**Comment by yoan-m** [comment]
When the feature hits the overlay during dragging, the feature position is set at the top left of the map

**Comment by fredj** [comment]
This is probably related to #3121

**Comment by yoan-m** [comment]
I think it's because when the pointer is hover the overlay, coordinates are calculated from the pixels of the overlay and not from the map.
See ol.interaction.Modify.handleDragEvent_

**Comment by yoan-m** [comment]
It works, thank you.
