### ISSUE TITLE
How can I Show KML with checkboxes?

### ISSUE THREAD

**Issue by hunterston** [openlayers/ol3#3126]
hi,
i have a google map that shows kml polygons on it by clicking the apropriate checkbox.
I would prefer to have openstreetmap as the main map instead of google but cannot find a solution to this, I know how to show the osm map but do not know how to show the kml files in exactly the same way as the google map.
Google Map test
http://gmdesign.org.uk/maptest/1
OSM Map Test
http://gmdesign.org.uk/maptest/2
Can you suggest or fix it so the osm map shows the kml files on it in the same was as the google one does.
OSM has an toption to show kml but that is by a slide in sidebar at top right of screen but this is not what i am after, am after the checkbox style same as google map. The only thing osm website does not show how to do that so am asking if you know how.
the scripts are files are on the links above

If i understood how to do it i would not be asking

**Comment by pagameba** [comment]
Please ask questions on the [mailing list](https://groups.google.com/forum/#!forum/ol3-dev).
