### ISSUE TITLE
TileVector and possible memory usage issues

### ISSUE THREAD

**Issue by pgiraud** [openlayers/ol3#3134]
Currently when using a TileVector source, the data retrieved for each tile to be rendered is stored in the source and stays there until the application is reloaded or the source is destroyed.
There's currently no strategy implemented to remove the data from the source at any time. This may result in memory usage issues if the user keeps the browser page open and pans or zooms a lot.
There could be a mechanism similar to the one used for raster tiles that would manage the removal of data for tiles that are visible any more.

**Comment by fredj** [comment]
`ol.source.TileVector` are gone, closing
