### ISSUE TITLE
nl-BE.js and fr-BE.js

### ISSUE THREAD

**Issue by cptstarling** [openlayers/ol3#3138]
It occurs to me that there are issues with the Dutch and French language for Belgian websites. This is probably because the following libraries don't exist:

/lib/OpenLayers/Lang/nl-BE.js
/lib/OpenLayers/Lang/fr-BE.js

(Belgium is a country with two major language communities)

See: https://www.drupal.org/node/2407917

Any ideas how this can be solved?

**Comment by bartvde** [comment]
wrong issue tracker use https://github.com/openlayers/openlayers/issues instead

**Comment by cptstarling** [comment]
Ok, for anyone who'd land on this one: https://github.com/openlayers/openlayers/issues/1424
