### ISSUE TITLE
Toggle visibility of Overlay

### ISSUE THREAD

**Issue by dkastl** [openlayers/ol3#3141]
I tried to toggle the visibility of an overlay, but it seems that there is no such method for overlays, such as `getVisibility` or `setVisibility`.

I solved this by setting the `hidden` attribute of the overlay element, and I want to ask now, if it would be good idea to add `getVisibility` or `setVisibility` methods to `ol.Overlay` or if this could cause troubles?

**Comment by fredj** [comment]
You can hide an overlay by setting it's position to `undefined`: `overlay.setPosition(undefined)`

**Comment by dkastl** [comment]
OK. and if I want to show it again, then I need to remember the position coordinate, right?

**Comment by elemoine** [comment]
> OK. and if I want to show it again, then I need to remember the position coordinates, right?

Yes, indeed.

**Comment by ahocevar** [comment]
Since the overlay is rendered to a DOM element that you provide, you could also just set a `display:none` style on that DOM element.
