### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by icholy** [openlayers/ol3#3147]
Are there TypeScript definition files for ol3? If not, is anyone working on it?

**Comment by elemoine** [comment]
To both questions: not that I know.

**Comment by 3x0dv5** [comment]
https://github.com/3x0dv5/ol3-typescript-definitions

**Comment by ca0v** [comment]
Just a comment: I can't understand why this is not a highly requested feature.  It improves the development experience enough to justify the effort but the project linked above is neglected and unpopular.  It's a shame.

**Comment by icholy** [comment]
@ca0v someone is working on it https://github.com/jumpinjackie/jsdoc-typescript-plugin
