### ISSUE TITLE
Layer extent rendering issues when devicePixelRatio > 1

### ISSUE THREAD

**Issue by nielsmeijer** [openlayers/ol3#3148]
This issue seems to apply to clients with a devicePixelRatio > 1. On such devices, layers that have a limited extent (configured by setting the extent property) are rendered incorrectly. 

I added some screenshots from a client running Firefox 35.0 on Windows 8.1 (devicePixelRatio is 1.5)

![JSFiddle testcase](http://i.imgur.com/q3lij3W.png)
[JSFiddle testcase](http://jsfiddle.net/nielsm/kymq05mh/): The atlas-style layer should cover Europe entirely.

![Tiled WMS Example](http://i.imgur.com/5NPVoP8.png)
[WMTS HiDPI example](http://openlayers.org/en/v3.1.1/examples/wms-tiled.html)

![WMTS HiDPI example](http://i.imgur.com/M7nJgXC.png)
[WMTS HiDPI example](http://openlayers.org/en/v3.1.1/examples/wmts-hidpi.html)

This issue can be reproduced by visiting  [this JSFiddle](http://jsfiddle.net/kymq05mh/) on a device with a pixelDeviceRatio > 1. Zoom out one level, rendering will be off.

**Comment by elemoine** [comment]
Thanks for the report. I hope we can address this for v3.2.0.

**Comment by shaunakv1** [comment]
I am seeing the same issue. Sorry I started a ticket before I saw this one..   #3185

**Comment by fredj** [comment]
50c0bc6879d38f2a6da0057b919069d6ad3bfb12 is the first bad commit
