### ISSUE TITLE
proj.transform can't handle extents

### ISSUE THREAD

**Issue by vog** [openlayers/ol3#3151]
`proj.transform()` doesn't handle extents correctly. It only transforms the first two coorinates, not the last two. However, `proj.getTransform()` handles extents correctly.

For example, consider the following extent:

    var extent = [10, 10, 20, 20];

Then, `proj.transform()` leads to the wrong result:

    ol.proj.transform(extent, 'EPSG:4326', 'EPSG:3857')

Wrong output (last two coordinates not transformed):

    [1113194.9079327357, 1118889.9748579597, 20, 20]

But `proj.getTransform()` works correctly:

    ol.proj.getTransform('EPSG:4326', 'EPSG:3857')(extent)

Output:

    [1113194.9079327357, 1118889.9748579597, 2226389.8158654715, 2273030.926987689]

**Comment by bartvde** [comment]
You should be using http://openlayers.org/en/v3.1.1/apidoc/ol.proj.html#transformExtent instead

**Comment by elemoine** [comment]
Use `ol.proj.transformExtent` to transform extents.

**Comment by elemoine** [comment]
With two answers I think we can safely close this :-)

**Comment by vog** [comment]
Just one quesiton: What about proj.getTransform()? Should this be used or not? And why does it behave differently from proj.transform()?
