### ISSUE TITLE
goog.require('ol.ext.rbush') - is not provided

### ISSUE THREAD

**Issue by royepperson** [openlayers/ol3#3155]
I have built an application using OL3.1.1 which works fine using ol-debug.js. I am now to trying to minify my application and OL3 using the closurebuilder.py.  I am running it from an Ant build.xml.  depstree.py raise the following exception:

   [exec]   File "C:\Roy\websites\javascript_projects\web\closurelibrary\closure\bin\build\depstree.py", line 56, in __init__
     [exec]     raise NamespaceNotFoundError(require, source)
     [exec] depstree.NamespaceNotFoundError: Namespace "ol.ext.rbush" never provided. Required in PathSource C:\Roy\websites\javascript_projects\web\openlayers_v3.1.1\ol\ol\structs\rbush.js

I have done a search in the my openlayers_v3.1.1 directory and find no goog.provide() for ol.ext.rbush.

How does this need to be corrected?

**Comment by royepperson** [comment]
More detail.  My closurebuilder.py command (only the ol portion):
    [exec] 'C:\Roy\websites\javascript_projects\web\gpxElevation/../closure-library/closure/bin/build/closurebuilder.py'
     [exec] '--root=C:\Roy\websites\javascript_projects\web\gpxElevation/../closure-library/closure'
     [exec] '--root=C:\Roy\websites\javascript_projects\web\gpxElevation/../closure-library/third_party/closure'
     [exec] '--root=C:\Roy\websites\javascript_projects\web\gpxElevation/../openlayers_v3.1.1/ol/ol'

I did find in ol-debug.js the following:

goog.provide('ol.ext.rbush');
/** @typedef {function(*)} */
ol.ext.rbush;
(function() {
var exports = {};
var module = {exports: exports};

What needs to be added to the release so when using closurebuilder the aforementioned definition of rbush gets included in a closure compile?

**Comment by pfidalgomachado** [comment]
Hi,

You should pass the rbush.js directory as a root to closurebuilder. An example that works for me:

```
python ../../closure-library/closure/bin/build/closurebuilder.py ^
 --root=../../closure-library ^
 --root=../../ol3/src ^
 --root=../../ol3/build/ol.ext ^
  ...
```
at line 4, ./../ol3/build/ol.ext is the directory path where the rbush.js is in my project-

Hope this helps!

**Comment by royepperson** [comment]
Thanks for the feedback. I've been trying to do the build using the OL3.1.1 zip file and not a git uclone. So it looks like I'm missing some needed files.  Gotta figure out why I'm getting an SSL error when trying to clone from github

**Comment by elemoine** [comment]
Le 22 janv. 2015 05:03, "royepperson" <notifications@github.com> a écrit :
>
> Thanks for the feedback. I've been trying to do the build using the
OL3.1.1 zip file and not a git uclone. So it looks like I'm missing some
needed files. Gotta figure out why I'm getting an SSL error when trying to
clone from github

The build/ol.ext/rbush.js file is generated by the build tool. It sounds
like we've got something to fix on the ol3 build side.

**Comment by royepperson** [comment]
elemoine, OL3 is totally new to me so I'm learning....

I have been trying to do a closure-library minify of my app and OL3 using the  zip download of the OL3 release and not a git clone of the repository. Don't know if that is the problem.  Unfortunately I am getting a SSL chain error when try to clone github and the github support team has not gotten back to me.

In my current configuration I am getting a lot of type warnings for oli and olx missing definitions plus a bunch of errors for missing option definitions.

Additionally I have been building an Ant build.xml file to run the compile.

Are my problems coming using the release zip verses a git clone of the repository?

Roy

**Comment by ca0v** [comment]
Same thing with the latest 3.4.0 zip file; loaded ol3/build/ol-debug.js into the browser and ol.ext.rbush is an empty object (not a function) and so `this.rbush_ = ol.ext.rbush(opt_maxEntries);` results in **Uncaught TypeError: object is not a function**; I'm using the zip because building ol3 on windows looks like a nightmare.

**Comment by thostetler** [comment]
Adding to what @ca0v mentioned, I'm getting the same issue with AMD as well.  You can reproduce the error here: http://plnkr.co/edit/jju2QaWgR8iGGgyPxEqe?p=preview if this helps.

**Comment by elemoine** [comment]
> I'm using requirejs and it seems like if (typeof define === 'function' && define.amd) define('rbush', function() { return rbush; }); might be the culprit. Because this case is true the next case, else if (typeof module !== 'undefined') module.exports = rbush; doesn't execute, which might result in rbush not being defined as the intended object (a function).


You are right. That's where the problem is.


> 
> By including the require.js script after the ol-debug.js script this error went away. Does this mean there are compatibility issues with OL3 and AMD?

Yep, for `ol-debug.js`.

Actually, it works by change for `ol.js`. It works because the compiler renames `define.amd` to `define.xx`.

**Comment by dpacifico** [comment]
info ol Parsing dependencies
ERR! Unsatisfied dependency "ol.ext.rbush" in script: /var/www/html/webprograms/ol3/src/ol/structs/rbush.js
2015-04-14 10:51:40,687 build/ol.js: clean
2015-04-14 10:51:40,687 pake: build/ol.js: Command '['node', 'tasks/build.js', 'config/ol.json', 'build/ol.js']' returned non-zero exit status 1
does anybody know the fix?

**Comment by lamuertepeluda** [comment]
I wish you had a Gruntfile instead of the closure compiler. That would be much easier to handle. Anyway bypassing that damn line:

if (typeof define === 'function' && define.amd) define('rbush', function() { return rbush; });

in ol-debug.js makes it work again with require.js optimizer... Thank you guys!

**Comment by ahocevar** [comment]
See #3755 for a related issue when using OpenLayers with RequireJS.
