### ISSUE TITLE
ol.source.TileWMS always send EPSG:3857

### ISSUE THREAD

**Issue by bestpika** [openlayers/ol3#3160]
I write the following code
```javascript
var src = new ol.source.TileWMS({
    params: { LAYERS: '...', VERSION: '1.1.1', SRS: 'EPSG:4326' },
    projection: 'EPSG:4326',
    url: '...'
})
```
But it send `EPSG:3857`
![img](http://i.imgur.com/XigySid.png)
Then the server return
```xml
<ServiceExceptionReport version="1.1.1">
   <ServiceException code="InvalidSRS">
      The spatial reference system specified is not supported. (Found SRS=EPSG:3857)
   </ServiceException>
</ServiceExceptionReport>
```
But I do not want to change ol.View's `projection`.
How do I make it send `EPSG:4326` without change ol.View's `projection`?

**Comment by elemoine** [comment]
If your view projection is X then you need the WMS to support that X projection. ol3 does not reproject images.

**Comment by bestpika** [comment]
So all my layers have to use the same `projection`?
Or how I add the auto transform code?

**Comment by lrusev** [comment]
Solved this issue with custom ol.source.TileWMS.tileLoadFunction.

```javascript
EPSG4326TileLoadFunction = function (tile, src) {
  var bboxReg, matches, coords;

  //projection hack, layer not support EPSG:3857
  bboxReg = /BBOX=([^&]+)/g;
  matches = bboxReg.exec(src);
  coords = window.unescape(matches[1]).split(',').map(function (c) {
    return parseFloat(c);
  });

  coords = ol.proj.transformExtent(coords, 'EPSG:3857', 'EPSG:4326');
  src = src.replace(bboxReg, 'BBOX=' + window.escape(coords.join(',')));
  src = src.replace(/SRS=[^&]+/g, 'SRS=' + window.escape('EPSG:4326'));
  tile.getImage().src = src;
}
```

**Comment by zantonz2** [comment]
I encountered the same problem recently, looked in 'ol / source / tilewms'. On the 204 line typo ==
params [this.v13_? 'CRS': 'SRS'] = projection.getCode ();

in params, specify the CRS: 'EPSG: 4326'
