### ISSUE TITLE
ol.View.fitExtent() does not perfectly fit to canvas

### ISSUE THREAD

**Issue by m-schuetz** [openlayers/ol3#3166]
Seems like it uses the nearest integer rather than a fractional zoom value.
Is there any way to get it to zoom exactly to the canvas size?

**Comment by m-schuetz** [comment]
Looking at the code of the fitExtent() function, this seems to do the trick:

```
var view = map.getView();
var res = view.getResolutionForExtent(extent, map.getSize());
view.setResolution(res);
```

Basically, just omitting the constrainedResolution part in fitExtent().


Maybe it'd be a good idea to add a tag somewhere that let's users get this behaviour if they want?

**Comment by elemoine** [comment]
Agree that it'd be a useful option.

**Comment by mauriciopasquier** [comment]
This solved an issue I was having perfectly, but I couldn't find that option in the docs. Is it there?

**Comment by ahocevar** [comment]
The API has changed since. In v4+, you can simply sqy
```js
map.getView().fit(extent, { constrainResolution: false});
```
which is [documented](https://openlayers.org/en/latest/apidoc/ol.View.html#fit);

**Comment by mauriciopasquier** [comment]
Ohh, I did not understand that option. Thanks!
