### ISSUE TITLE
Calling addFeatures on a ol.source.Cluster does not recluster 

### ISSUE THREAD

**Issue by jnachtigall** [openlayers/ol3#3173]
Whenever I add features to a cluster its `cluster_` should be called automatically. Currently, there is only this in ol.source.Cluster
`
  this.source_.on(goog.events.EventType.CHANGE,
      ol.source.Cluster.prototype.onSourceChange_, this);
`

`cluster_()` is not called when I change, remove or add features.

I'd expect a vector layer to automatically to update whenever I add features, for ol.source.Cluster the features are just added as individual single features not as clustered features.

**Comment by jnachtigall** [comment]
`addFeatures()`, `clear()` or `removeFeature()` seems to be broken for ol.source.Cluster. The features are added or removed but no reclustering happens, there are only single features then.

I even tried
`
src.clear();
src.addFeatures(fs);
src.cluster_();
src.changed();
`
or
`
src.onSourceChange_();
`
but with no success. 

I tried with `src` being `ol.source.Cluster` or even `src` being the `source` object passed as an option to the constructor of `ol.source.Cluster`

I ended up with removing and adding the whole cluster layer with a freshly created cluster source whenever I needed to add/remove features.

**Comment by malaretv** [comment]
@jnachtigall I performed a quick test [here](http://bl.ocks.org/malaretv/14c61b0e73fa529ce397) and the `addFeature`, `removeFeature`, and `clear` all seem to trigger an update to the clustering as expected.

**Comment by jnachtigall** [comment]
@malaretv Thanks for the working example. Playing with your code I really cannot reproduce it within your minimally working example :-/ Unfortunately, I had this in a rather large project where reclustering did not work. Closing for now, assuming that it was probably some other thing...

**Comment by vedro-compota** [comment]
@jnachtigall I see same problem in ol 4.6, this code won't work:
```javascript
    var source = new ol.source.Vector({});
    var layer = new ol.layer.Vector({
        source: source,
        style: function(feature, resolution) {
            var size = feature.get('features').length;
            var style = styleCache[size];
            if (!style) {
              style = [new ol.style.Style({
                image: new ol.style.Circle({
                  radius: 10,
                  stroke: new ol.style.Stroke({
                    color: '#fff'
                  }),
                  fill: new ol.style.Fill({
                    color: '#3399CC'
                  })
                }),
                text: new ol.style.Text({
                  text: size.toString(),
                  fill: new ol.style.Fill({
                    color: '#fff'
                  })
                })
              })];
              styleCache[size] = style;
            }
            return style;
          }
    });

    map.addLayer(layer);
```

**Comment by vedro-compota** [comment]
In `v5.3` this problem also exists.
