### ISSUE TITLE
Failing example in development mode

### ISSUE THREAD

**Issue by htulipe** [openlayers/ol3#3181]
This example does not work (only in dev mode):

http://openlayers.org/en/v3.1.1/examples/box-selection.html?mode=raw

This is due to the following error

    Uncaught TypeError: Cannot read property 'rbush' of undefined

Which seems to be due to that script loading error

    http://openlayers.org/en/v3.1.1/ol.ext/rbush.js

**Comment by bartvde** [comment]
all hosted examples are broken in debug mode, I think there is a ticket already for this

**Comment by bartvde** [comment]
or maybe there is not yet a ticket but it's been discussed before IIRC

**Comment by bartvde** [comment]
The ticket I was talking about is #3034 but it is fixed

**Comment by htulipe** [comment]
For what I can gather, only vector related example are broken which is consistent with the rbush loading issue.

**Comment by bartvde** [comment]
ah that is very likely, I only noticed the examples I checked today were also broken, but indeed those were all vector related

**Comment by elemoine** [comment]
Looking at that now…

**Comment by fredj** [comment]
It's probably a missing entry in https://github.com/openlayers/openlayers.github.io/blob/build/gruntfile.js#L55

**Comment by elemoine** [comment]
Yes, I'm fixing it…

**Comment by fredj** [comment]
cool, thanks

**Comment by elemoine** [comment]
See https://github.com/openlayers/openlayers.github.io/pull/40.

**Comment by elemoine** [comment]
Fixed. See http://openlayers.org/en/master/examples/box-selection.html?mode=raw.

**Comment by htulipe** [comment]
Cool, thanks.
