### ISSUE TITLE
Can not switch between development and production mode in the examples

### ISSUE THREAD

**Issue by htulipe** [openlayers/ol3#3184]
Way to reproduce:

- Go to http://openlayers.org/en/v3.1.1/examples
- Type `simpl` in the search form and hit the Enter key
- Click the `Simple Example` link
- Try to switch to development mode

This does not occur when Enter key is not hit. the problem comes from the search criteria being added has a query param. Please see two possible fix in PR #3183 and PR #3182

**Comment by elemoine** [comment]
Thanks for researching this. What patch do you think we should apply?

**Comment by htulipe** [comment]
Maybe both. #3183 adresses a clear bug IMHO. For #3182, I don't see a reason why query param should propagate to example page.

That being said, it was a delibarate addition made a while back by a commit of @twpayne (7f63e3b8e7fab74f6917ee3efdb9ff9571f6ae3e), there surely was a reason then.Question is, is it still the case?

**Comment by htulipe** [comment]
For the record, #3183 has been kept while #3182 has not. I am closing this issue.
