### ISSUE TITLE
Viewport is clipping WMS Layers weirdly. Happening on Production Examples

### ISSUE THREAD

**Issue by shaunakv1** [openlayers/ol3#3185]
Please check these examples.  Try to zoom and pan the map, see how WMS layer goes in the top left corner and is cropped by viewport? This is happening in my code when setting extents on WMS layers. This does not happen if I remove extents.. 

http://openlayers.org/en/v3.1.1/examples/wms-tiled.html?q=wms

http://openlayers.org/en/v3.1.1/examples/wms-image.html?q=wms

**Comment by elemoine** [comment]
Closed with https://github.com/openlayers/ol3/pull/3186.

**Comment by shaunakv1** [comment]
Yes that fixed it.. thanks for quick fix @fredj
