### ISSUE TITLE
ol.Object property fires change when new and old value are the same

### ISSUE THREAD

**Issue by Threxxy** [openlayers/ol3#3188]
Hi guys, fantastic work on OL3.

It seems a property of ol.Object will fire a change event even if the value hasn't changed.  Fiddle [here](http://jsfiddle.net/1kjeLo8k/2/) and basic example below:

```javascript
//Create observable kitten object with cuteness of 90
var kitten = new ol.Object({cuteness: 90});

//log the old and new value when cuteness is changed
kitten.on(
    'change:cuteness',
    function(evt) {
        console.log(evt.oldValue + ' set to ' + evt.target.get('cuteness'));
    }
);

//test
kitten.set('cuteness', 45); //console: 90 set to 45
kitten.set('cuteness', 45); //console: 45 set to 45
kitten.set('cuteness', 45); //console: 45 set to 45
```

**Comment by elemoine** [comment]
Yes indeed. The app developer is responsible for checking if the value has changed, if needed.

**Comment by Threxxy** [comment]
Ah okay, I was used to Knockout's observable style where the subscribers are only notified if there is a different value. I'll just use preventDefault(), thanks!

**Comment by elemoine** [comment]
> I'll just use preventDefault(), thanks!

I fail to understand the relationship to `preventDefault()`.

**Comment by Threxxy** [comment]
Oh, my mistake, I was confused about the mechanism by which subscribers are notified about mutation to an observable -- I see it has no effect and the event can't even be cancelled anyway.
