### ISSUE TITLE
ArcGisCache Layer Missing In OL3 (was present in OL2)

### ISSUE THREAD

**Issue by thenadz** [openlayers/ol3#3189]
Was [ArcGisCache](https://github.com/openlayers/openlayers/blob/master/lib/OpenLayers/Layer/ArcGISCache.js) intentionally left out of OL3? Is there a way to achieve the same hex row/column numbers from some other layer type?

**Comment by ThomasG77** [comment]
I think it's because it was not a fundamental component compared to others. You should consider contributing or funding this feature.
Anyways, questions should not be done via Github. See the [following rules](https://groups.google.com/d/topic/ol3-dev/WzJ8ewR8HGI/discussion)

**Comment by thenadz** [comment]
Sorry, you're correct that this issue is borderline. I posted as an issue because it seemed like a regression, but the wording is definitely a question.

I unfortunately cannot justify developing/funding development for this enhancement. I'll probably end up just changing the file structure to match another supported format.
