### ISSUE TITLE
popup feature?

### ISSUE THREAD

**Issue by liaicheng** [openlayers/ol3#3191]
hi,guys!  i m fresh man to use ol3, i find a lot about how to use popup feature on the Internet,,but no right answer for the ol3(they are all for ol2). who can tell me which parts can solve my problem. example is better lol.

**Comment by bartvde** [comment]
don't ask questions on github issues please, use the mailing list or a forum

Also you might need to specify more info in your e-mail / forum post.

https://groups.google.com/d/msg/ol3-dev/WzJ8ewR8HGI/09726Th0RE0J
