### ISSUE TITLE
panorama images?

### ISSUE THREAD

**Issue by andreaplanet** [openlayers/ol3#3194]
Is openlayers suitable to show panorama images, high resolution images (converted in multilayer tiled images) without any projection/geographical coordinates?
Example: http://www.gigapan.com/

**Comment by bartvde** [comment]
please don't ask questions in github issues
Use the mailing list or a forum: https://groups.google.com/d/msg/ol3-dev/WzJ8ewR8HGI/09726Th0RE0J
