### ISSUE TITLE
Zoom box behavior

### ISSUE THREAD

**Issue by ischas** [openlayers/ol3#3207]
Hello there,

I'd suggest to change the behavior of the zoom box, which actually isn't working in the same way as known of OL2 (e.g. http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/pan-zoom-panels.html ) or standard GIS tools like QGIS.
* The surrounded area should be fully visible after the zoom.
* The surrounded area should be places in the middle of the map.

I tested the behavior with the following example: http://openlayers.org/en/master/examples/d3.html .

I started with the following view:
![drag1](https://cloud.githubusercontent.com/assets/8558126/6044979/1edbb26a-ac97-11e4-8cc5-51da89098f4b.png)

Now I dragged a box (with a buffer of a couple of pixels) around Wyoming and got the following view:
![drag2](https://cloud.githubusercontent.com/assets/8558126/6045003/475b836e-ac97-11e4-9348-59733e10548a.png)

You see that Wyoming isn't fully displayed and it is not in the center of the map. I expected the map to look something like that:
![drag3](https://cloud.githubusercontent.com/assets/8558126/6045045/77787c46-ac97-11e4-87ec-113072168e6d.png)

Best regards!

**Comment by elemoine** [comment]
Indeed, in ol3, the center of the zoom box is the "anchor", that is the geographical position that doesn't move in the map viewport. What do people think about this? Both ol2 and Leaflet recenter to the map to the center of the zoom box…

**Comment by bartvde** [comment]
I personally prefer the ol2 / leaflet approach

**Comment by elemoine** [comment]
Anyone up for a patch? That should not be too hard.

**Comment by ischas** [comment]
This has been fixed somewhen in time. It can be closed.
