### ISSUE TITLE
Hectic movement of icons while hovering

### ISSUE THREAD

**Issue by simonseyock** [openlayers/ol3#3218]
I encountered a problem with the new release (3.2.0 that is). When icons are are close to each other and the map has a select interaction with condition: mouseMove this problem occurs. While moving the mouse over the icons the selected icon erratically changes. 
I would expect the selected icon to be the one laying directly under the mouse (like in version 3.1.1) or to be the icon of the feature which is nearest to the pointer.
I made a fiddle to demonstrate the issue:
http://jsfiddle.net/simon_seyock/45e1ddu1/1/

Greets and thanks,
Simon

**Comment by tschaub** [comment]
Thanks for the report and the good example.  I agree this is unexpected behavior.  Here's a fiddle with 3.1.1 for comparison: http://jsfiddle.net/45e1ddu1/2/

I haven't dug yet to find the responsible change.

**Comment by fredj** [comment]
`git bisect`: 162c47eb3e0f6ea1bab192fb14b8f0c4cea7f5e0 is the first bad commit
