### ISSUE TITLE
SVG Icon in a Vector Layer causes IndexSizeError in IE11

### ISSUE THREAD

**Issue by jnpritchard** [openlayers/ol3#3220]
`var layer = new ol.layer.Vector({`
...
`style: new ol.style.Style({`
`                    image: new ol.style.Icon({`
`                        src: 'images/myicon.svg'`
`                    })`
`                })`
`            });`

Adding an icon as a style attribute to a Vector layer results in errors at the case ol.render.canvas.Instruction.DRAW_IMAGE: in ol.render.canvas.Replay.prototype.replay_

Found in IE11, it appears that the width and height of the image are zero, which causes the error to occur.

**Comment by DanielSundberg** [comment]
I've got this as well. 

The only way for me to get rid of this error was to use a PNG image instead.

**Comment by fredj** [comment]
See https://connect.microsoft.com/IE/feedbackdetail/view/925655/svg-image-has-0x0-size-in-ie11

**Comment by DanielSundberg** [comment]
@fredj, doesn't help us since we have to support IE11.

**Comment by ahocevar** [comment]
Can't you just set the `imgSize` of your SVG icon? Like
```js
new ol.style.Style({
  image: new ol.style.Icon({
    src: 'images/myicon.svg',
    imgSize: [24, 24]
  })
})
```

**Comment by DanielSundberg** [comment]
For some reason that did not work for me.

**Comment by ahocevar** [comment]
Sorry, my snippet above is invalid. We currently assert that `imgSize` is not set when `src` is set.

**Comment by ahocevar** [comment]
Fixed with #5036.

**Comment by tomchadwin** [comment]
I'm still getting this issue. Is #5036 in 3.16.0?

**Comment by ahocevar** [comment]
Yes it is @tomchadwin. Can you provide a JSFiddle that shows the error with the latest release?

**Comment by tomchadwin** [comment]
I'll try. It occurs in output automatically generated by qgis2web, so I'll have to see what happens as I strip the output down to functional minimum. Thanks.

**Comment by tomchadwin** [comment]
Perhaps my error (from inherited code). So `imgSize` is required for IE11 SVGs, *even if they use `src`, and not `img*`?

**Comment by ahocevar** [comment]
We are aware of the fact that the `size` property is very misleading. It is mostly for image sprites, if you only want to use a subset of the image. If you want to resize client-side, you'll need to configure `scale`. So if you want half the size, configure `scale: 0.5`.

And yes, for IE11, you need to set `imgSize` even when you configure `src` instead of `img`.

**Comment by tomchadwin** [comment]
Ahh, OK. Makes sense. I'll have to do some maths to get from my required client-side size in pixels to the scale. Thanks for all the clarification.

**Comment by tomchadwin** [comment]
All working now - thanks for all the help.
