### ISSUE TITLE
Error when writing polygons to GPX format

### ISSUE THREAD

**Issue by jalik** [openlayers/ol3#3229]
*Version: OpenLayers 3.1.1*

When serializing polygons using **ol.format.GPX.writeFeatures()**, I get the following error :

```TypeError: serializersNS[node.namespaceURI][node.localName] is undefined ol.js:83601```

Which refers to the code below :

```js
ol.xml.serialize = function(
    serializersNS, nodeFactory, values, objectStack, opt_keys, opt_this) {
  var length = (goog.isDef(opt_keys) ? opt_keys : values).length;
  var value, node;
  for (var i = 0; i < length; ++i) {
    value = values[i];
    if (goog.isDef(value)) {
      node = nodeFactory.call(opt_this, value, objectStack,
          goog.isDef(opt_keys) ? opt_keys[i] : undefined);
      if (goog.isDef(node)) {
        serializersNS[node.namespaceURI][node.localName]
            .call(opt_this, node, value, objectStack);
      }
    }
  }
};
```

And below the values from the line execution :

```js
serializersNS = Object { "null": Object, "http://www.topografix.com/GPX/1/0": Object, "http://www.topografix.com/GPX/1/1": Object }
node.namespaceURI = "http://www.topografix.com/GPX/1/1"
node.localName = undefined
```

So the **node.localName** initialization is missing somewhere... should be easy to fix, no ?

**Comment by bartvde** [comment]
GPX does not support polygons

http://www.globalmapperforum.com/forums/suggestion-box/1761-support-polygon-gpx-export.html

**Comment by jalik** [comment]
Thanks for your quick reply, I am sorry, I didn't know...

So what do you propose ?
- should it stay like this, throwing a meaningless error leaving the newbie thinking its a bug
- or maybe we can ignore polygons to avoid errors
- or display a more explicit error message (eg: polygons not supported)
- or anything else...

**Comment by bartvde** [comment]
Those are good questions. At the very least we should handle this more gracefully I agree.

**Comment by jalik** [comment]
Maybe the safer option would be to just display a custom error, because ignoring polygons could become a bug if GPX adds polygon support later.

**Comment by bartvde** [comment]
yeah we normally use assertions that will show up in debug mode, would that work for you?

**Comment by jalik** [comment]
Yes of course, it's better than the current behaviour.

**Comment by elemoine** [comment]
Fixed witth https://github.com/openlayers/ol3/pull/4361.
