### ISSUE TITLE
Disable pinch- zoom and dragging when map covers the whole viewport

### ISSUE THREAD

**Issue by sirtet** [openlayers/ol3#3242]
Not sure if this is doable at all (google maps suffer from it too), but here's the problem:

On touch devices it can happen that the user zooms a page with a map in a way so the map covers the full viewport. If pinch-zoom and drag is active for the map, there will be no way to zomm/scroll back to other parts of the page.

So the map should be able to detect such a state and offer a solution, maybe the suggested disabling of the touch events, maybe the addition of a button similar to the full-screen toggle, which would zoom out the page?

**Comment by elemoine** [comment]
I don't think ol3 should be responsible for detecting that state and disabling the touch interactions. There are, for example, apps where the map always covers the full viewport. What we could provide though is a way to enable/disable the call to`preventDefault`. In this way, if you can detect when the map covers the viewport, you will able to disable the call and have the page scroll on pointermove.
