### ISSUE TITLE
Inquiry on Other possibility with OpenLayer

### ISSUE THREAD

**Issue by tonysai** [openlayers/ol3#3249]
Aside from using maps with OpenLayer, would it be possible to use it with other javascript library that creates org charts?  For example, http://gojs.net/latest/samples/orgChartExtras.html.

We are hitting a wall now with displaying thousands of notes it is taking too much time.  Would OpenLayer be a solution?  Any advice is appreciated.

**Comment by bartvde** [comment]
Please use the mailing list of an online forum instead of github issues for inquiries

https://groups.google.com/d/msg/ol3-dev/WzJ8ewR8HGI/09726Th0RE0J
