### ISSUE TITLE
Draw Interaction unit tests use incorrect pointer event

### ISSUE THREAD

**Issue by Morgul** [openlayers/ol3#3251]
While writing the tests for #3250, I used the `Draw` interaction tests as a template. However, when attempting to simulate a drag like [here](https://github.com/openlayers/ol3/blob/master/test/spec/ol/interaction/drawinteraction.test.js#L119-L126), I noticed that my drag event handler was never actually firing. Doing a little debugging, it quickly became clear that instead of firing `pointermove` events, the test should be firing `pointerdrag` events. Because the test is checking to make sure that something _didn't_ happen, it still passes, but it's not really testing what it claims to be testing.

I decided to file this as a bug to make sure I wasn't missing something, and ensure I understood the intent of the tests correctly.

**Comment by elemoine** [comment]
I just looked at the draw interaction code again and, as I understand it, the draw interaction does not rely on `pointerdrag` at all. So it makes sense that the tests do not emulate `pointerdrag` events.

**Comment by Morgul** [comment]
Hmm, it may just be a confusion because the unit tests _claim_ to be simulating a drag, but in actuality are not. Or, rather, they're simulating a drag, but not a drag event?

Well, if it's a non issue, I'm happy having this closed.
