### ISSUE TITLE
Add button type="button" for FullScreen control

### ISSUE THREAD

**Issue by ssaarela** [openlayers/ol3#3255]
As with #2015 a button without type is by default a submit button and triggers full screen mode when a) fullscreen button happens to be first submit button and b) enter is pressed in some other field in same form. All control buttons should have type='button' attribute.

**Comment by elemoine** [comment]
@ssaarela would you create a PR for that?

**Comment by fredj** [comment]
The fullscreen button type is already `button`: https://github.com/openlayers/ol3/blob/master/src/ol/control/fullscreencontrol.js#L62

**Comment by elemoine** [comment]
Good call @fredj :-)

**Comment by elemoine** [comment]
I'm closing this. @ssaarela please reopen if we misunderstood your query.

**Comment by ssaarela** [comment]
You got it right. Seems I need to update the ol3 dependency... my bad.
