### ISSUE TITLE
Possibility to restrict the type of features you can select

### ISSUE THREAD

**Issue by acanimal** [openlayers/ol3#3257]
`ol.interaction.Select` select any type of features from a given layer/s.
It would be nice to limit the type of geometries we can select, for example, in a layer with points and lines it would be helpful to limit the `ol.interaction.Select`to only select features using a point geometry.

**Comment by acanimal** [comment]
I'm looking at other interactions. In the same way `ol.interactino.Draw` allows to specify/restrict the kind of geometry to draw, it would be helpful to specify the kind of feature to select or modify. So I'm thinking to also add to to `ol.interaction.Modify` too.

Has it sense ?? @bartvde @tschaub @elemoine @fredj

**Comment by adube** [comment]
For the record, I could be interested in such a feature.

**Comment by acanimal** [comment]
I just modified `ol.interaction.Select` and making some test. For the moment it seems it is a bit complex than the draw interaction, where we can select one type of geometry.
With select interaction we could need to specify an array of types allowed to be selected.
Testing using the GeoJSON countries I found if I restrict to select polygons, some countries (like USA) which is a MultiPolygon is not selected. So I'm trying to specify an array of types.

**Comment by acanimal** [comment]
ok, I'm almost ready to make a PR but I don't know where I must document the new `type` property in the `ol.interaction.Select` to appear in the API doc. Any help?

**Comment by tsauerwein** [comment]
> Any help?

See my comment: https://github.com/acanimal/ol3/commit/38ac08d4e92581ad59ee2194e6c9896185c81dea#commitcomment-9836892

**Comment by fperucic** [comment]
I wholud seem nicer to have a preSelect callback. For example, if `preSelectCallback` is defined on `ol.interaction.Select`, a callback whoud receive the feature and thia feature whouldn't be added to 'ol.interaction.Select.featureOverlay_.getFeatures()' if `preSelectCallback` returns `false`
You have more flexibility when using such a calback.

**Comment by acanimal** [comment]
For the moment this PR #3258  allows to specify a `type` property with an array of allowed geometries.
Maybe this parameter could also accept a function called each time a feature is going to be selected and determine if the feature is allowed to be selected or not, similar to:

    new ol.interaction.Select({
        type: function(feature) {
            // return true if feature must be selected depending on the feature's geometry or properties
        }
    }

**Comment by tschaub** [comment]
I agree this should be made more general.  And I think the option should be spelled `filter`.  And it would be `function(ol.Feature):boolean`.

**Comment by acanimal** [comment]
working on...

**Comment by acanimal** [comment]
Please take a look to the comment so if you agree I send the PR.

I have created a `filter` property with the signature `ol.interaction.SelectFilterFunction`, defined too in the `ol.interaction.Select` file as:

    /**
     * A function that takes an {@link ol.Feature}. The function should return true
     * if the feature must be selected or false otherwise.
     * @typedef {function(ol.Feature): boolean}
     * @api
     */
    ol.interaction.SelectFilterFunction;

For the moment I don't add any getter/setter method. 
I have created a sample too where we can see the `filter` in action as:

    var selectInteraction = new ol.interaction.Select({
      filter: function(feature) {
        if(types===null) {
          return true;
        } else {
          return goog.array.contains(types, feature.getGeometry().getType());
        }
      }
    });

I'm thinking to modify the `ol.interaction.SelectFilterFunction` signature so it receives three parameters: the feature, the layer and the map event (or at least the pixel clicked). I saw a comment in the ol3-dev group of someone requesting a way to know the clicked pixel of the select interactions.

Opinions ???

**Comment by elemoine** [comment]
I think https://github.com/openlayers/ol3/pull/3018 should also be considered, as it is somewhat related. If we make the interaction emit specific events we may want to introduce `before` type events allowing listeners to cancel the corresponding action. I am just wondering…

**Comment by acanimal** [comment]
I'm not sure. In beta version of OL3 there were the `before` events but, if I'm not wrong, there were more oriented to decide if a property must be changed.

Here there is no property to be changed. This issue is simply to decide if a feature must be selected or not and the #3018 is to trigger `select` events.

Any ideas @bjornharrtell ?

**Comment by bjornharrtell** [comment]
I like the idea of a cancelable `beforechange` event rather than introducing the more specific filter API. Documentation and/or an example should make it clear how to use `beforechange` to get the same effect as the suggested filter. On second thought I think the event type names should be `beforeselect` and `select`.

**Comment by bjornharrtell** [comment]
I've made the rename in #3018 which is ready for review: Eventual `beforeselect` implementation should be a separate PR.

**Comment by acanimal** [comment]
ok, I will change then my implementation to use before listeners.

**Comment by acanimal** [comment]
Look at this https://github.com/openlayers/ol3/pull/2865#issuecomment-60323004
Everybody loves to kill the old `beforepropertychange` which is similar the `before` type events we are talking.

Personally I prefer start with a simple solution that satisfies a currently need, that is, limit the kind of geometries we can select, and make it complex when needed.

**Comment by bjornharrtell** [comment]
I'm not sure the desire to remove `beforepropertychange` applies to the suggested `beforeselect` event. I think `beforeselect` is as simple or even simplier to understand and use than a specific filter API.

If `beforeselect` event is implemented similar to `select` in #3018 it could/should allow for the selected collection to be modified using standard JavaScript array filtering (or goog.array.filter not sure what is prefered in ol3) which would provide the same functionality as proposed by the filter API.

I think this can be compared to how styling features in OL2 and OL3 was changed. In OL2 there is a specific API to define rules and filters for styles. In OL3 the same functionality is simply provided by allowing a style to be a function conforming to ol.style.StyleFunction.

**Comment by acanimal** [comment]
I have made an initial PR (see #3277) based on a `filter` property, which accepts a function invoked for each feature and that determines if a feature must be selected or not.

I continue thinking on the `beforeselect` event and I'm not sure to agree it is the right solution. For me the `select` event has sense because it notifies when new features are selected and there can be many listeners interested to be notified on this event.

On the other hand and, at the risk to seem stubborn :) (thats me),  I think there must be only one function responsible to determine if a feature must be selected or not, that is, using the proposed `filter` property.

Use the `beforeselect` event means there can be many listeners deciding if a feature must be selected or not, and I think that can produce confusing situation, where a listener want to allow select points and another listener doesn't.

What do yo think?

**Comment by elemoine** [comment]
> What do yo think?

That I am also unsure/undecided on the whole thing.

**Comment by ahocevar** [comment]
I like the idea of a filter function better than a beforeselect event. But this is just personal preference, nothing that I could back with arguments.

**Comment by sweco-sebhar** [comment]
I'm not strongly against the filter function idea and it relates well to the layers option. However I still think a `beforeselect` event could be useful as a way to abort or otherwise alter selections and could possibly used to the same effect as the filter and layers options. Perhaps there is no reason to not have both these things.

**Comment by acanimal** [comment]
See also conversation on #3018

**Comment by fredj** [comment]
Fixed with #3402
