### ISSUE TITLE
Access styles for features imported via ol.format.KML

### ISSUE THREAD

**Issue by stewberticus** [openlayers/ol3#3262]
As of now the developer has almost no control over the rendering of features imported from a KML source. There is no access to the styleUrl that the format is reading from, and no way to access the style of the features once they have been set. getStyle() returns the style function, but there is no way of actually telling what color the feature is, for example. This data is known at some point because the features render the correct style I just think the developer should have access to that style to makes chance per his or her specific application.

**Comment by ahocevar** [comment]
You can execute the style function with a render resolution as argument:
```
feature.getStyleFunction()(map.getView().getResolution());
```
The above will return the style that is used to render that feature.

I'm closing this. Please reopen if you still feel that something needs to be fixed/improved on the library side.

**Comment by stewberticus** [comment]
Yes, that will return the function not any sort of style itself that can be
manipulated

**Comment by ahocevar** [comment]
Maybe my code snippet was not clear enough:
```js
var style = feature.getStyleFunction()(map.getView().getResolution());
// style now holds the feature's style for the current resolution
// manipulate or recreate the style here
feature.setStyle(style);
// the new/manipulated style is now set on the feature
```

**Comment by stewberticus** [comment]
OK I've tried this and had issues. I'll post a JS fiddle of my exact issue.
It has to do with the drag and drop file manipulation interface, so it may
be my timing of when I'm trying to access this information is wrong.

**Comment by stewberticus** [comment]
There is an issue with the pointer to the "this" keyword in the returned
style function, using your code posted above somehow "this" gets set to the
global window object instead of the feature. I do not feel like this is the
desired behavior.

**Comment by ahocevar** [comment]
You're absolutely right. The style function needs to be called in the scope of the feature:

feature.getStyleFunction().call(feature, map.getView().getResolution());

**Comment by stewberticus** [comment]
thank you!
