### ISSUE TITLE
SVG in ol.style.Icon

### ISSUE THREAD

**Issue by Arul4rmBCT** [openlayers/ol3#3269]
Hi,
Im trying to use SVG image while creating marker, but getting 'NS_ERROR_NOT_AVAILABLE: ' error.

Source::

var mapVectorSource = new ol.source.Vector({
		    features: []
		});
		var mapVectorLayer = new ol.layer.Vector({
		    source: mapVectorSource
		});

function createMarker(location, style){
		    var iconFeature = new ol.Feature({
		        geometry: new ol.geom.Point(location)
		    });		    
		    iconFeature.setStyle(style);		    
		    return iconFeature;
		}

var marker = createMarker(ol.proj.transform(degrees, 'EPSG:4326', 'EPSG:3857'), 
						new ol.style.Style({
					    	image: new ol.style.Icon(({
						        anchor: [0.5, 1],
						        anchorXUnits: 'fraction',
						        anchorYUnits: 'fraction',
						        src: 'assets/data/cat30.svg'						        						
					    	}))
					    })
					);		
mapVectorSource.addFeature(marker);

map=new ol.Map({
			target:'map',
			layers: [osmLayer,mapVectorLayer],
			view: view
		});

Any one please help on how to use svg in marker.

Thanks..

**Comment by elemoine** [comment]
Please don't use GitHub for questions.
