### ISSUE TITLE
requirejs optimization issue with ol3

### ISSUE THREAD

**Issue by mylen** [openlayers/ol3#3274]
Hi,

I've been trying to bundle ol3 with my app using requirejs optimizer.
I ran into a runtime error :

>Mismatched anonymous define() modules ...

After some research, I found that in my ol.js file, the rbush dependency was defined without name:

    // export as AMD/CommonJS module or global variable 
    if (typeof define === 'function' && define.amd) define(function() { return rbush; }); 

Or that generate an issue in requireJS:

>If you use the loader plugins or anonymous modules (modules that call define() with no string ID) but do not use the RequireJS optimizer to combine files together, this error can occur. 

I modified the source likewise in order to avoid that error:

    // export as AMD/CommonJS module or global variable 
     if (typeof define === 'function' && define.amd) define("rbush", function() { return rbush; }); 

I gave a look in the code repository, but cannot find where to modify the code. I hope someone more skilled in ol3 will propose a PR

**Comment by fredj** [comment]
Thanks for the report, you should probably open an issue directly to rbush: https://github.com/mourner/rbush

**Comment by mylen** [comment]
Ok, thank you for the advice:

https://github.com/mourner/rbush/pull/29
