### ISSUE TITLE
TypeError: wgs84Sphere.midpoint is not a function

### ISSUE THREAD

**Issue by yanakey** [openlayers/ol3#3282]
For some reason, default build doesn't include ol.Sphere methods. I tried to make a custom build, listing explicitly all the methods, but they are not exported anyway. Can anybody tell, please, if there any option I should set?

**Comment by fredj** [comment]
Only `ol.Sphere#geodesicArea` and `ol.Sphere#haversineDistance` are exported.

We could export `ol.Sphere#midpoint` as well.

**Comment by yanakey** [comment]
ol.Sphere.haversineDistance is not a function too (using official v3.2.1 release builds). 
I've tried to build my own with 

	"exports": [
		...,
	
		"ol.Sphere", 
		"ol.Sphere#*",
	
		...
	}

or 

	"exports": [
		...,
	
		"ol.Sphere#cosineDistance",
		"ol.Sphere#geodesicArea",
		"ol.Sphere#crossTrackDistance",
		"ol.Sphere#equirectangularDistance",
		"ol.Sphere#finalBearing",
		"ol.Sphere#haversineDistance",
		"ol.Sphere#interpolate",
		"ol.Sphere#initialBearing",
		"ol.Sphere#maximumLatitude",
		"ol.Sphere#midpoint",
		"ol.Sphere#offset",

		...
	}

Nothing helps, they are not exported.

**Comment by bartvde** [comment]
you'll need to add ```@api``` annotation in the source code doc blocks as well

**Comment by yanakey** [comment]
@bartvde, thank You very much, now they are exported (-:
Issue can be closed.
