### ISSUE TITLE
Firefox, dom renderer and NS_ERROR_NOT_AVAILABLE 

### ISSUE THREAD

**Issue by pavel-stastny** [openlayers/ol3#3283]
Hello,

In some cases I am getting error NS_ERROR_NOT_AVAILABLE while zooming. 

To reproduce the issue: 

1) Open link http://jsfiddle.net/axoxhcrm/ (firefox browser)
2) Click the plus button
3) Click the minus button

Thanks 

-pavel

**Comment by bartvde** [comment]
DOM renderer got removed with https://github.com/openlayers/ol3/pull/5815 so closing
