### ISSUE TITLE
In case of missing Geometry information in GEOJSON format, we have an exception undefined

### ISSUE THREAD

**Issue by srouaix** [openlayers/ol3#3286]
The source with the problem
ol.format.GeoJSON.readGeometry_ = function(object, opt_options) {
  if (goog.isNull(object)) {
    return null;
  }
  var geometryReader = ol.format.GeoJSON.GEOMETRY_READERS_[object.type];
  goog.asserts.assert(goog.isDef(geometryReader));
  return /** @type {ol.geom.Geometry} */ (
      ol.format.Feature.transformWithOptions(
          geometryReader(object), false, opt_options));
};

The solution is to add another test ->  typeof object == 'undefined'.

Version 3.2.1

**Comment by bartvde** [comment]
Your GeoJSON is invalid, see: http://geojson.org/geojson-spec.html

A feature object must have a member with the name "geometry". The value of the geometry member is a geometry object as defined above or a JSON null value.
