### ISSUE TITLE
ol.source.ImageStatic custom width and height for image

### ISSUE THREAD

**Issue by idevin** [openlayers/ol3#3289]
Hi, guys! for eg, i use image with width and height = 100 for ol.source.ImageStatic, but when i resize its dimensions (like 20, 300) it does not resize at all

**Comment by elemoine** [comment]
Please use the mailing list for questions.

**Comment by idevin** [comment]
Here is discussion https://groups.google.com/d/msg/ol3-dev/mE-q58s9F9k/ucc0129Y1TwJ

Is it a duplicated issue ?
