### ISSUE TITLE
Scale Line Control - accuracy of width

### ISSUE THREAD

**Issue by bill-chadwick** [openlayers/ol3#3291]
Another small thing ...

The accuracy of the width of the scale line control is being affected by the CSS padding.
replacing

.ol-scale-line-inner{border:1px solid #eee;border-top:none;color:#eee;font-size:10px;text-align:center;margin:1px;padding:0 2px}

with

.ol-scale-line-inner{border:1px solid #eee;border-top:none;color:#eee;font-size:10px;text-align:center;margin:1px;padding:0 0}

Makes the scale line more accurate (by 4px when referenced to a 1km Ordnance Survey Grid on a Bing map)

To show this, I used the area around Swanage (2 degrees West, 50.6 degrees North) where the 1km grid on the OS map is horizontal on Web Mercator.

This link http://www.bdcc.co.uk/ol3/examples/bing-maps.html has the tweaked CSS as above, and starts at the Swanage area.

**Comment by fredj** [comment]
Good catch !
