### ISSUE TITLE
OL3 and https

### ISSUE THREAD

**Issue by aresys** [openlayers/ol3#3299]
Hi everybody,
I'm new to OL3 and web development (I'm coming from C/C++) and now I'm in a little trouble.
I desire to use OL3 into a private network, but the maps I'm using aren't loaded from inside the (private) network.
Is there a manner to decleare something like "https" loading, when I define a new ol.layer.Tile object? Or another way to impose an SSL connection to map servers?

Thanks very much!
Emanuele

**Comment by bartvde** [comment]
Please use the mailing list or a forum for questions
