### ISSUE TITLE
OL3 and X3DOM

### ISSUE THREAD

**Issue by clement-igonet** [openlayers/ol3#3302]
Hi,

   I've already coded a tool to render 3D object relying on OSM data (Demo here: http://web/osm2x3d.net )

   Then, I'm currently developing a solution to display OSM tiles in an x3dom 3D graph scene, relying on an OSM tile queue manager. So I've just realized it could be done with something like an "ol.render.x3dom" implementation of the ol.render model.

   Is there somebody interested in working with me on this feature?

**Comment by elemoine** [comment]
Sounds like a nice project!

Could you please use the mailing list for such questions?
