### ISSUE TITLE
Tissot indicatrix error in description

### ISSUE THREAD

**Issue by Apophis3000** [openlayers/ol3#3314]
The text on http://openlayers.org/en/v3.3.0/examples/tissot.html is wrong. It says:

Example of Tissot indicatrix maps. The map on the left is an EPSG:4326 map. The one on the **left** is EPSG:3857.

Should be:

Example of Tissot indicatrix maps. The map on the left is an EPSG:4326 map. The one on the **right** is EPSG:3857.

**Comment by fredj** [comment]
good catch!
