### ISSUE TITLE
map.getPixelFromCoordinate function not works in IE9

### ISSUE THREAD

**Issue by dboz** [openlayers/ol3#3318]
Hi,
when try to get pixels from coordinates using IE9 a null value is returned.
The same function works well with other versions.

**Comment by elemoine** [comment]
Could you please provide a jsfiddle demonstrating the problem?

**Comment by ahocevar** [comment]
Maybe the map has not been rendered yet when you call getPixelFromCoordinate?

**Comment by fredj** [comment]
Closing due to lack of response.
