### ISSUE TITLE
Select features example Uncaught TypeError

### ISSUE THREAD

**Issue by steveoh444** [openlayers/ol3#3319]
Hallo 

I think there is a Problem with the Example "Select features example" 
http://openlayers.org/en/v3.3.0/examples/select-features.html

 $('#status').html('&nbsp;' + e.target.getFeatures().getLength() +
          ' selected features (last operation selected ' + e.selected.length +
          ' and deselected ' + e.deselected.length + ' features)');
    });

gives me a Uncaught TypeError: Cannot read property 'length' of undefined
on

&lt;span id=&quot;status&quot;&gt;&amp;nbsp;0 selected features&lt;/span&gt;

**Comment by GuillaumeSmaha** [comment]
This error only occur with the minimized version. d8150c515544f1f573949971714c72fc5fa7ea7b on the master fixes that.

**Comment by fredj** [comment]
fixed on master: http://openlayers.org/en/master/examples/select-features.html
