### ISSUE TITLE
Get examples working locally

### ISSUE THREAD

**Issue by gdini** [openlayers/ol3#3340]
Hi everyone,
I was trying to get started with OL3. I cloned the repository on my Windows7 machine, but so far I can't get the examples working.
Opening the build.py always returns an error. Even configuring my own localhost (i.e. Cesium or node.js) is not working.
Could please someone pass me some instruction to get started with the examples? For instance, which dependancies do I need, any configuration that is not included in the repository, etc.?

Thanks in advance.
Best regards

**Comment by elemoine** [comment]
To use OpenLayers 3 in an application you just need the `ol.js` and `ol.css` files that are included in the release archive.

Why do you want to clone the ol3 repository? Do you have specific reasons for doing so? FYI, the ol3 build process doesn't currently work on Windows, so it's no surprise that you're having problems.

In the future please use the mailing list for such questions.
