### ISSUE TITLE
How to use OpenLayers 3 with Proj4js

### ISSUE THREAD

**Issue by haktanaydin** [openlayers/ol3#3348]
I'm working on a map viewer project and used openlayers 2 before this. Now I have to use OpenLayers 3 and map viewer app should support many different projections because I have wms and wfs layers from different sources and projections. I've found examples that use openlayers2 and proj4js. But I couldn't find explicit example for using ol3 and proj4js. What is your suggestion?

**Comment by elemoine** [comment]
See https://github.com/openlayers/ol3/blob/master/examples/wms-image-custom-proj.js and its html counterpart.
