### ISSUE TITLE
 object is not a function at new ol.structs.RBush in ol-debug build

### ISSUE THREAD

**Issue by theoutlander** [openlayers/ol3#3349]
Error, 3/13/2015, 5:30:17 PM, TypeError: object is not a function at new ol.structs.RBush (/app/map/bower_components/openlayers3/build/ol-debug.js?v=1426292962889:63920)

This is where that problem is:

// export as AMD/CommonJS module or global variable
**if (typeof define === 'function' && define.amd) define(function() { return rbush; });**
else if (typeof module !== 'undefined') module.exports = rbush;
else if (typeof self !== 'undefined') self.rbush = rbush;
else window.rbush = rbush;

})();
**ol.ext.rbush = module.exports;**
})();

The issue is caused because I'm using requirejs which creates window.define.amd. Hence, module.exports is still an empty object as it is not set to rbush.

I'm not sure why this works in release mode....can't figure out what the minified variables mean.

One solution is to set "module.exports = rbush", but I'm not sure how open layers handles these scenarios when using 3rd party libraries. However, I can at least modify the debug file and use it to debug.

Email thread: https://groups.google.com/forum/#!topic/ol3-dev/y0ri7LPrD78

**Comment by ca0v** [comment]
+1

**Comment by fredj** [comment]
See #3274

Please try with v3.4.0

**Comment by jirihelmich** [comment]
Still having this issue with both 3.4.0 and 3.5.0.
