### ISSUE TITLE
When does map.change:layerGroup fire?

### ISSUE THREAD

**Issue by Zodiase** [openlayers/ol3#3351]
I'm using ol-3.3.0 and I have a code that looks like this:

    map.on('change:layerGroup', function () {
        console.log('change:layerGroup',arguments);
    });
    map.getLayerGroup().on('change', function () {
        console.log('change',arguments);
    });
    map.addLayer(anotherLayer); // Fires change event twice.
    map.setLayerGroup(anotherLayerGroup); // Never fires change:layerGroup.

Am I understanding the change:layerGroup event wrong here? When does it fire? How should I detect change map layer group events?

Thanks!

**Comment by elemoine** [comment]
I think it's a bug. For now you can use `'change:layergroup'` as the event type name. 

Up for an easy patch/PR?

**Comment by marcjansen** [comment]
Is this still an unfixed bug, @elemoine or @Zodiase? I am not able to test right now.

**Comment by Zodiase** [comment]
@marcjansen I'm not sure. I probably shouldn't have closed this. Sorry for the confusion.

**Comment by marcjansen** [comment]
No need to be sorry. At least the (maybe) issue came up again. We'll try to have another look for sure.

**Comment by fredj** [comment]
The problem was that the event name is `layergroup` not `layerGroup` (see https://github.com/openlayers/ol3/blob/v3.15.1/src/ol/map.js#L104).

tested with:
```js
map.on('change:layergroup', function () {
  console.log('change:layergroup',arguments);
});

map.getLayerGroup().on('change', function () {
  console.log('change',arguments);
});

var layer = new ol.layer.Tile({
  source: new ol.source.OSM()
});
var group = new ol.layer.Group();

map.addLayer(layer);
map.setLayerGroup(group);
```
