### ISSUE TITLE
Small feature request: access overlay used by ol.interaction.Draw

### ISSUE THREAD

**Issue by yanakey** [openlayers/ol3#3353]
Seems like there is no way to access overlay from interaction, so there is no way to update overlay style?..

**Comment by fredj** [comment]
Are you referring to the overlay of the OverviewMap control?

**Comment by yanakey** [comment]
No, I mean ol.interaction.Draw (corrected title). 

For example, in my app interaction is created with some default styles and user can change color or stroke width. But I can't update draw styles, because I can't access interaction overlay.

Just for testing tried with the name of overlay in compressed ol: 
this.drawInteraction['N'].setStyle (this.getDrawStyle ());

**Comment by tsauerwein** [comment]
`ol.interaction.Draw` takes a `style` argument in the options, see http://openlayers.org/en/master/apidoc/ol.interaction.Draw.html?unstable=true

Is that what you are looking for?

**Comment by yanakey** [comment]
@tsauerwein , not quite. Using style argument in the option I set default styles. And I have controls, allowing to change default styles. Fill/stroke color, for example. But after interaction is instantiated I can't update overlay style, because there is no method like `getOverlay()` to do `interaction.getOverlay().setStyle(updatedStyle)`

**Comment by tsauerwein** [comment]
The style that you set in in the constructor can be a function, which could return your updated style.

Something like:

    var interaction = new ol.interaction.Draw({
      // ...
      style: function(feature, resolution) {
        // ...
        return [updatedStyle];
      }
    });

See [ol.style.StyleFunction](http://openlayers.org/en/master/apidoc/ol.style.html?unstable=true#StyleFunction).

**Comment by yanakey** [comment]
Oh, really, I absolutely forgot it can be a function... Thank You! (-:
