### ISSUE TITLE
OpenLayers.ProxyHost In OpenLayers 3?

### ISSUE THREAD

**Issue by conorw** [openlayers/ol3#3367]
Hi,

Is there a corresponding OpenLayers.ProxyHost setting in the new OL3 library?

Many thanks,

Conor

**Comment by adube** [comment]
Please, use StackOverflow [1] for for user questions.  If you want to participate in discussions related to the development of ol3, you can use the "ol3-dev" [2] mailing list.

[1] http://stackoverflow.com/questions/tagged/openlayers-3
[2] https://groups.google.com/forum/#!forum/ol3-dev

**Comment by elemoine** [comment]
> Is there a corresponding OpenLayers.ProxyHost setting in the new OL3 library?

No there isn't anything like this for now.
