### ISSUE TITLE
How to remove Countries Borders from a Google map integrated in opnelayers?

### ISSUE THREAD

**Issue by ouadie1983** [openlayers/ol3#3368]
How can I hide the borders between countries on Google map. integrated in openlayers . i mean where to added this code 

	var mapStyles = [{featureType: "administrative.country",stylers: [{ visibility: "off" }]}];

or 

{
    featureType: "administrative.country",
    elementType: "geometry.stroke",
    stylers: [
        { visibility: "off" }
    ]
  }

i think i need edit this file but where and how to added this 
http://212.14.46.18:8080/scripts/tracking/oltracking-map.js

Please help 
Thanks

**Comment by tsauerwein** [comment]
It looks like you are using OpenLayers 2, this is OpenLayers 3. Please ask your question on the ol2 [mailing list](http://trac.osgeo.org/openlayers/wiki/MailingLists) or on [StackOverflow](http://stackoverflow.com/questions/tagged/openlayers).
