### ISSUE TITLE
Value of height is wrong when Height  of map is changing 100%.

### ISSUE THREAD

**Issue by mfdev1** [openlayers/ol3#3373]
Height of map is 100% in example.
The next, value of Height is wrong  when window is resizing.

Isn't there any way of viewing to match the size of the window?

![2015-03-20 20 37 13](https://cloud.githubusercontent.com/assets/11344789/6750762/31d62cc0-cf41-11e4-90e4-ffd128cde3bb.png)

![2015-03-20 20 37 36](https://cloud.githubusercontent.com/assets/11344789/6750765/352626be-cf41-11e4-9742-20d39fd2de5b.png)

![2015-03-20 20 38 47](https://cloud.githubusercontent.com/assets/11344789/6750767/38e88972-cf41-11e4-8d30-2994334e6ca7.png)

**Comment by ChouGary** [comment]
map.updateSize();

**Comment by ahocevar** [comment]
If you want your map div to cover the whole viewport, you have to make sure that the height of html and body is also 100%.

**Comment by Mandelag** [comment]
@ahocevar Is it normal to style the html tag like this? 
```
<html style="height:100%"> 
</html>
```
If I write `<div id="map" style="width:100%;height:100%"></div>` without styling the `<html>` & `<body>` height by 100% first and then click-and-keep-dragging the browser window's corner, the map height will increase indefinitely.

**Comment by ahocevar** [comment]
Yes, that's expected. 100% only works if the container has a size. HTML and BODY don't have one unless you set one.
