### ISSUE TITLE
Tile Vector Grid Lines Appear on Tile Edges

### ISSUE THREAD

**Issue by mechdrew** [openlayers/ol3#3375]
Lines will appear at the edges of tiles in TileVector sources for no apparent reason. Some are more visible than others, but there seems to be a problem with how the tiles are fit together. I have tested in Firefox, IE, and Chrome on Windows and Firefox on Ubuntu and all exhibit the same problem.

Here is a screenshot from the [tile vector example](http://openlayers.org/en/v3.3.0/examples/tile-vector.html?q=vector+tile), you can see thin white lines in the water (although there are no problems when zoomed in on the land it appears):
![image](https://cloud.githubusercontent.com/assets/5085577/6761417/7c4859b4-cf18-11e4-81b7-1b21b46c27ed.png)

And one from the application I am working on, the land polygons have a black stroke for the boundaries that I assume is being used for the color of the grid lines:

![image](https://cloud.githubusercontent.com/assets/5085577/6761412/6d45ba56-cf18-11e4-805b-ee51b2981f6a.png)

**Comment by elemoine** [comment]
The issue with "stroked polygons" is known. I plan to work on this during the coming code sprint.

**Comment by sbowler** [comment]
Do you mean v3.5.0? Does that mean you already have an idea what the solution is? Is there any easy work around in the mean time?

**Comment by elemoine** [comment]
> Do you mean v3.5.0?

Probably not.

> Does that mean you already have an idea what the solution is?

I want to try out some approach, based on Canvas clipping.

> Is there any easy work around in the mean time?

Not that I know.

**Comment by sbowler** [comment]
Thank you for the information. It is disappointing this isn't likely to make it in v3.5.0. I've attempted to look through the code, but am having a difficult time tracking this down. Can you point me in the right direction of where changes would need to be made? I would really appreciate it.

**Comment by sbowler** [comment]
I wanted to try to clarify what is happening. We noticed that the library we are using to generate the tiles is clipping the polygons where they go outside of the tile, which creates the false line on the edge of the tiles. This seems fundamentally needed in order to try to tile vector data.

Is this what you are confirming is the issue? Are you proposing some method to not draw strokes for those erroneous lines or are we talking about different issues?

**Comment by elemoine** [comment]
We're talking about the same issue. Our plan is to rely on buffered tiles and clipping at rendering time.

Out of curiosity, what tool/library do you use for the creation of the vector tiles?

**Comment by sbowler** [comment]
I used a slightly modified version of https://github.com/mapbox/geojson-vt running with Node.js to tile the data. I modified the library to convert the points back into the same lat lon projection as the original data and modified the returned tile to be in valid GeoJSON format. Aside from this issue and a fair bit of memory usage it seems to work quite well.

**Comment by elemoine** [comment]
I also used a geojson-vt-based node script. My script generates GeoJSON tiles with coordinates in Web Mercator.

**Comment by ahocevar** [comment]
@elemoine, has there been any progress on canvas clipping?

**Comment by elemoine** [comment]
No, unfortunately, we haven't had time to continue working on this.

**Comment by ahocevar** [comment]
@elemoine Can you please outline briefly what you had in mind (canvas clipping)? I'm wondering if you wanted to create one replay per tile, render each replay to its own canvas, clip the canvas, and compose it onto the layer canvas - or if you had something else in mind.

The reason why I'm asking is because I may be able to get time to work on this.

**Comment by elemoine** [comment]
My plan was to create a specific renderer for tile vector layers. That renderer would know about tiles and would use canvas clipping when rendering features of a tile. This assumes buffered tiles obviously. I did not go further than that.

**Comment by ahocevar** [comment]
Ok cool, thanks. Then we are on the same page. If I get time to work on this, I'll create an RFC before I implement anything.

**Comment by elemoine** [comment]
> Ok cool, thanks. Then we are on the same page. If I get time to work on this, I'll create an RFC before I implement anything.

Nice.

**Comment by sbowler** [comment]
We've had to duplicate our data to get around this issue. If you have time to fix it, that would be much appreciated!

**Comment by tsauerwein** [comment]
Clipping was implemented with https://github.com/openlayers/ol3/pull/4219
