### ISSUE TITLE
Support blend modes for layer styles

### ISSUE THREAD

**Issue by tremby** [openlayers/ol3#3379]
It would be very useful to specify a [blend mode](http://dev.w3.org/fxtf/compositing-1/#blendingseparable) along with a vector style's fill or stroke, or for a layer's tiles.

This would make it possible, for instance, to avoid obscuring labels on the underlying tiles when putting a brightly coloured vector overlay on top. For example if the background is white with dark labels, a vector overlay of any colour, full opacity and "multiply" blend mode will give the colour on any white areas but the labels will still be visible.

At present the normal blend mode is used, which mixes colours, so in the above example to keep labels visible we need to use a semi-transparent overlay. In this case we don't get the full brightness of the overlay and additionally the label below is washed out to some extent.

Any possibility of including this feature in future?

**Comment by ahocevar** [comment]
This sounds like a good idea indeed.

**Comment by lun471k** [comment]
This feature would be quite useful for the applications I develop using OL3 too.

**Comment by kalessine** [comment]
Hi! could I request a bitwise OR blend... I would like to make a map with 3 vector layers, with each layer having a single channel (either red, green or blue) the final composite is dark at value of zero for all 3 vectors, white at max value, and coloured for all other in-between values..the desired effect is not achievable using alpha blending at the moment... if anyone has any hints how to do this with ol3 at the moment please message me =D
Thanks   
James

**Comment by tremby** [comment]
That'd be possible with this feature, using the 'add' blend mode.

**Comment by tremby** [comment]
I'd be willing to put a bounty on this feature. Is there a mechanism to do that?

**Comment by ahocevar** [comment]
We currently do not have a mechanism to put bounties on a feature.

**Comment by elmuSSo** [comment]
I would also like to support this feature request. I think blend modes (especially MULTIPLY) should be added to every map application software by default. I can't imagine merging two layers without blending modes. I was also lobbying for that feature in Locus and now I will lobby for it in MapProxy. It is a must-have feature.

**Comment by lun471k** [comment]
I've been able to ahieve what I wanted (using multiply) by binding a custom function when a new layer/features is added to the map and edit the `globalCompositeOperation` property of the canvas' context. But it must be called each and every time I add an element. 

I still think this should be managed by OL3 itself.

**Comment by tremby** [comment]
Does this work in all cases? What if it's for example on a vector layer showing some polygons? What if the user then zooms in and out? What if the user pans the features way off screen and then pans them back in? I don't know the OL internals and would worry that it'd at some point remove and add the features and so the blend mode would disappear at some point.

**Comment by elmuSSo** [comment]
lun471k: can you share the code somewhere, please?

**Comment by lun471k** [comment]
First of all, I'm declaring the blend mode when creating my map element:

    var myMap = new ol.Map({ /* all your map stuff */ 
        beforeRender: function(var_args) {
            var canvas = document.getElementsByTagName('canvas')[0];
            var context = canvas.getContext("2d");

            //Now set the blending mode
            context.globalCompositeOperation = "multiply";
        }
    });

Then, I created a function to make sure the blend mode stays as I wanted, otherwise it would randomly change to default after several user interaction with the map.

    function refreshCanvasCompositeMode() {
        var canvas = document.getElementsByTagName('canvas')[0];
        var context = canvas.getContext("2d");

        if (context.globalCompositeOperation !== "multiply")
            context.globalCompositeOperation = "multiply";
        if (typeof myMap === "object") 
            myMap.render();
    }

I call this function every 100ms once the map is fully loaded (custom map with a background image and several dozen of polygon/linestring vector layers): `setInterval(refreshCanvasCompositeMode(), 100);`

I also force the blend mode right before I add an element to the map:

    var canvas = document.getElementsByTagName('canvas')[0];
    var context = canvas.getContext("2d");

    context.globalCompositeOperation = "multiply";

This is crappy code, but it works. You can see a [working example here](http://lachance.qc.ca/projets/quartier-menestrel/?beta=1) (warning: we're working on it, so it might not always be available and is a dummy URL).

**Comment by elmuSSo** [comment]
Thanks! I will look into that. Will it be also applicable for multiplying two (or more) tile-based layers?

**Comment by tremby** [comment]
I don't think this approach will work for me since I need to apply the blend mode only to a vector layer. And I don't think I can get away with something as hacky like this in production. Still, I'll have a play with it.

**Comment by tremby** [comment]
@ahocevar if you won't accept a bounty, maybe I'll try to implement this myself. Can you provide any guidance? I don't know the OL codebase at all. Which files and areas of code should I look at, and is there anything I need to be careful of?

**Comment by ahocevar** [comment]
@tremby I think you can easily implement this on the application level, using the precompose hooks of `ol.Map`, e.g.:

    map.on('precompose', function(evt) {
      evt.context.globalCompositeOperation = "xor";
    });

No need for any hacks.

**Comment by tremby** [comment]
It's no good in my case to have a particular blend mode active for all operations on the map. I need all layers to be the default blend mode except my vector overlay. Are there such hooks for before and after anything in a particular layer is rendered, to switch the blend mode to multiply and then switch it back when done?

**Comment by ahocevar** [comment]
The same hook is available on the layer level, e.g.
```js
vectorLayer.on('precompose', function(evt) {
  evt.context.save();
  evt.context.globalCompositeOperation = "xor";
});
vectorLayer.on('postcompose', function(evt) {
  evt.context.restore();
});
```

**Comment by marcjansen** [comment]
This calls for an example, right? I may have time for such an example tomorrow.

**Comment by tremby** [comment]
@ahocevar What about for a `FeatureOverlay`? I'm told that `featureOverlay.on` is not a function.

**Comment by ahocevar** [comment]
FeatureOverlay is something we may get rid of soon.

**Comment by tremby** [comment]
Okay. That alone makes this not a suitable solution right now, since I'm using FeatureOverlay to highlight selected rooms, and I don't have time to rewrite it to do it another way.

But that aside, I've been playing with this and I'm having only limited success. I can see that the two handers are being called, and the blend mode is being changed and changed back to the values I expect. However, the blend mode is not being applied to the vector shapes. It *is*, on the other hand, being applied to points (which I'm styling as icons) on the very same layer. Why might this be?

I actually need it to be the other way around; I need the icons to be "source-over" (the normal blend mode) and the shapes to be multiplied. I guess I'd need to split them into separate vector layers? Or are there some other events I can listen for, before and after individual features are rendered?

If I remove the postcompose callback (so the multiply mode stays) the vector shapes are multiplied. But I can't have various other layers and features multiplied, so this won't work.

**Comment by fredj** [comment]
fixed with #3696

**Comment by tremby** [comment]
I disagree. Have the concerns I raised in my various comments here been addressed? It doesn't look like it to me, since all #3696 does is add an example.

**Comment by ahocevar** [comment]
@tremby That example shows how you can easily set a blend mode using OpenLayers' flexible compose event system. I agree with @fredj that this is fixed.

**Comment by tremby** [comment]
If I understand it correctly, I can now set a blend mode for one specific layer, but not separately for individual features within a given layer. Is that correct?

I'm on a totally different project now and can't practically test. But I'll likely be looking for this feature again in the very near future. I guess I can raise any issues which come up when it comes to it.
