### ISSUE TITLE
Fullscreen-button class

### ISSUE THREAD

**Issue by coastforge-tdo** [openlayers/ol3#3390]
Hi there.

First of all: Thanks for the great work :) 

I noticed after updating from Version 3.0.0 to Version 3.3.0 (yes, I skipped a few ^^) that the fullscreen-button class is always "ol-full-screen-false", even with the fullscreen beeing activated. In 3.0.0 the class changed to "ol-full-screen-true".

**Comment by fredj** [comment]
(see 7679069520839d038ea048fb2e9eae1bcfa65857), `-false` should be removed. ping @tsauerwein

**Comment by coastforge-tdo** [comment]
Thanks for the quick answer.
Would it be possible to have both possibilities? Because without the class-change it is not really possible to style the button states differently with CSS.
I am asking because I want to use css-themes in a project, allowing the user to change the button-icons, with just loading a different css-file.

**Comment by tsauerwein** [comment]
Yes, this is a bug, thanks for reporting. I will restore the original behavior.

**Comment by coastforge-tdo** [comment]
Thank you :-)
