### ISSUE TITLE
Can not set zoom level and immediately get pixel position

### ISSUE THREAD

**Issue by helgiborg** [openlayers/ol3#3400]
This will give wrong results:

view.setZoom(level);
var pixel = map.getPixelFromCoordinate(myCoordinates);

However if you'll change the zoom level and then call map.getPixelFromCoordinate(myCoordinates) after a litle while, it will give the correct results.

Perhaps there is another way to get the pixels using the view (which obviously is more logical) but I haven't found it.

I'm using:
  source = new ol.source.WMTS
  tileLayer = new ol.layer.Tile

**Comment by elemoine** [comment]
When the view is changed (using `view.setZoom` or something else) a re-render is scheduled. But the rendering will occur at a later time, in an animation frame. If you want to force a rendering in the current execution "thread" you can use `map.renderSync()`. So try to do `map.renderSync()` between the  call to `setZoom` and the call to `getPixelFromCoordinate`.

**Comment by helgiborg** [comment]
Works correctly. Thanks.
