### ISSUE TITLE
Deleting an ol.Object property

### ISSUE THREAD

**Issue by gberaudo** [openlayers/ol3#3404]
Currently there is no method for deleting a property from an `ol.Object`.
It would be useful when serializing a feature to GeoJSON since `ol.Feature` properties appear in the serialized string, even when they are `undefined`.

**Comment by elemoine** [comment]
`ol.Object#unset` maybe?

**Comment by tschaub** [comment]
> `ol.Object#unset`

+1

**Comment by probins** [comment]
looks like this one wasn't closed automatically - because #3410 says 'closes:' rather than 'closes'?
