### ISSUE TITLE
ImageWMS WebGL bug on Retina displays (Macbook Pro)

### ISSUE THREAD

**Issue by Xyrus2000** [openlayers/ol3#3405]
When using the WebGL renderer and with ImageWMS on retina displays (specifically the Macbook Pro), the requested image dimensions are incorrect (too large). This causes the layer imagery to appear small and "floating" above a tiled basemap.

The issue seems to affect all single image based sources (ImageWMS, ImageVector, etc.).

The jsfiddle included here runs perfectly fine on a non-retina laptop and external monitor, but demonstrates the problem on a MacBook Pro retina display.

<link>http://jsfiddle.net/j2cP4/95</link>

**Comment by hoodlumbubo** [comment]
I can confirm this problem:
![screen shot 2015-03-27 at 6 03 42 pm](https://cloud.githubusercontent.com/assets/5143876/6862832/e7c6ae8c-d4ab-11e4-9ac7-4328d434e37c.png)
However I believe it is the content is too small.

**Comment by elemoine** [comment]
Thanks for the report. I hope to be able to look into it.
