### ISSUE TITLE
Running OpenLayers in a UIWebView with an aspect ratio less than a device-dependent value causes extreme slowdown

### ISSUE THREAD

**Issue by tripleplay369** [openlayers/ol3#3408]
Running OpenLayers in a UIWebView with an aspect ratio less than a device-dependent value causes extreme slowdown in the canvas rendering.

## To reproduce:
1. Create a new iOS project from the "Single View Application" template.
2. Paste the following code into the ViewController:

  ```
  - (void)viewDidLoad {
      [super viewDidLoad];
      // Do any additional setup after loading the view, typically from a nib.
    
      UIWebView * webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, 414, 682)];
      [self.view addSubview:webView];
        
      [webView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"http://openlayers.org/en/v3.3.0/examples/mobile-full-screen.html"]]];
  }
  ```

4. Run the app on an iPhone 6+ (see below for frame sizes that reproduce on other devices). The map should pan smoothly when touch panning.
3. Change the line
  ```
  UIWebView * webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, 414, 682)];
  ```
  to
  ```
  UIWebView * webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, 414, 683)];
  ```
5. Run the app on an iPhone 6+. The map is extremely unresponsive.

## Findings

The slowdown seems to happen when the aspect ratio (width of the UIWebView / height of the UIWebView) drops below a certain device specific threshold.

* iPhone 6+ happens at aspect ratios less than .607.  Example frames: `CGRectMake(0, 0, 414, 682)` -> `CGRectMake(0, 0, 414, 683)`
* iPhone 6 happens at aspect ratios less than .366.  Example frames: `CGRectMake(0, 0, 200, 546)` -> `CGRectMake(0, 0, 200, 547)`
* iPad Air happens at aspect ratios less than 0.751.  Example frames: `CGRectMake(0, 0, 500, 666)` -> `CGRectMake(0, 0, 500, 667)`

After profiling Mobile Safari, the calls that slow down are the canvas calls `drawImage` and `clearRect`.  At a "good" aspect ratio on the iPhone 6, these calls take <1ms and <1ms respectively.  At a "bad" aspect ratio they take ~20ms and ~4ms respectively.

Good:
![image](https://cloud.githubusercontent.com/assets/1642685/6870887/52d549cc-d475-11e4-984d-60a36892fb6b.png)

Bad:
![image](https://cloud.githubusercontent.com/assets/1642685/6870882/432a9572-d475-11e4-86c7-f33a3b46621a.png)

This is a weird one.

**Comment by mlegenhausen** [comment]
The same problem occurs on Cordova powered apps. The canvas stuff is extremely slow. Even drawing a simple icon Vector line makes the ol3 engine unusable.

I am currently looking for alternatives. Have you tried `WKWebView` or [corsswalk for ios](https://github.com/crosswalk-project/crosswalk-ios)?

**Comment by GerardPerche** [comment]
It seems I'm facing the same issue, in a native app (inside a UIwebview or WKWebview)...,even with a "perfect" aspect ratio. 
I've made a lot of tests, as soon as the map occupies the majority of the screen, the redraw becomes very slow. (it's perfectly smooth if the map occupies 1/4 of the screen, nevertheless)
I've also tried to use the "webgl" and "dom" renderers, which are much quicker for rendering, but they only work if the map has no vector data to render.
Maybe I'm doing something wrong?
Any idea for a workaround ?

**Comment by mlegenhausen** [comment]
I am currently limiting the pixelRatio to 2. Example:

```js
const map = new ol.Map({
  pixelRatio: Math.min($window.devicePixelRatio, 2),
  ...
});
```

This works very well and we have already apps in production with this configuration.

**Comment by GerardPerche** [comment]
and you maps are fullscreen?

**Comment by mlegenhausen** [comment]
Yes using the canvas renderer.

**Comment by GerardPerche** [comment]
OK thanks. I've just added the pixelRatio line, but panning/zooming is still very laggy :-(

**Comment by mlegenhausen** [comment]
Which Cordova Version and ol3 version are you using?

**Comment by GerardPerche** [comment]
ol: v3.13.1
No cordova: I'm in a native app, the page is rendered inside an embedded browser (either an UIwebview or WKwebview instance)

**Comment by mlegenhausen** [comment]
From our experience WkWebView will bring you the most in performance. Does it run smoother with pixelRatio of 1? Which Device are using?

**Comment by GerardPerche** [comment]
(device: iPhone 6 and iPad air 2)
Yes it's much quicker with pixelRatio of 1. Not perfectly fluid though..

**Comment by ahocevar** [comment]
Just a quick note: you can use the dom renderer - it works with vector data and creates a canvas for vector layers.

**Comment by GerardPerche** [comment]
With the dom renderer and pixelratio at 1, it's now PERFECTLY fluid. Guys: many thanks to you !I owe you a beer (each) :-)
