### ISSUE TITLE
Selected feature has weird shape when partially moved off screen

### ISSUE THREAD

**Issue by doronhorwitz** [openlayers/ol3#3412]
This is an issue in the newly release v3.4.0.
Take a look here: http://jsfiddle.net/doronhorwitz/022nnszd/
Select the bottom square. Now move the map downwards so that the bottom square starts moving off the bottom of the screen. It will turn into a triangle
![1](https://cloud.githubusercontent.com/assets/687727/6885130/7db416ea-d61a-11e4-9528-db9ffcb51fed.png)
![2](https://cloud.githubusercontent.com/assets/687727/6885131/7f1e3c72-d61a-11e4-8deb-edfda87c1738.png)

**Comment by ahocevar** [comment]
Your polygons are not closed. A polygon's last coordinate must equal the first coordinate. See my [updated JSFiddle](http://jsfiddle.net/022nnszd/1/) for correctly defined polygons.

**Comment by doronhorwitz** [comment]
Thanks for the correction, but still the behaviour isn't consistent.
This problem doesn't exist in v3.3.0. Also the square is drawn fully when it is not selected but offscreen. Surely this might be an indicator of a different problem?

**Comment by ahocevar** [comment]
Which inconsistencies are you experiencing with my updated JSFiddle? What do you mean by "Also the square is drawn fully when it is not selected but offscreen."?

**Comment by doronhorwitz** [comment]
If you go back to my original (incorrect) code in which the polygons are not closed, the polygon is still drawn as a square when it is unselected and partially off the screen.
Then if it is selected when it is partially off the screen it is drawn as a triangle. That's what I mean by inconsistent.
In v3.3.0 this does not happen. But the fact that it happens in v3.4.0 might be a sign of some other problem?

**Comment by ahocevar** [comment]
Not at all. The reason why you see the polygon clipped in your snippet only when selected is because for vector overlays, the data is clipped to the visible extent and updated with every frame. Vector layers have a buffer so the clip extent is bigger than the visible extent. So to me everything in both JSFiddles is expected behavior.

**Comment by doronhorwitz** [comment]
Thanks. That explains that

**Comment by ahocevar** [comment]
For what it's worth, the behaviour is the same with v3.3.0 when polygons are not closed. See http://jsfiddle.net/022nnszd/2/.
