### ISSUE TITLE
No examples of using goog.ui.Menu or other closure functionality within an OL application?

### ISSUE THREAD

**Issue by ca0v** [openlayers/ol3#3421]
I am having a difficult time figuring out how to use goog.ui.Menu when using ol-debug.js.  The ol file destroys the global goog instance and subsequent goog.require('goog.ui.Menu') calls fail to locate the component.  I would like to see an example which makes use of some/any goog.ui component.

**Comment by ahocevar** [comment]
@fredj Can't we point @ca0v to a resource that explains this? I'm pretty sure swisstopo has one somewhere.
