### ISSUE TITLE
MS Surface 1st gen IE11 full screen mode - empty screen when try to zoom

### ISSUE THREAD

**Issue by vdavyskiba** [openlayers/ol3#3430]
Device: MS Surface 1st gen IE11 in full screen mode
Steps:
1. open http://dev.openlayers.org/examples/fullScreen.html in full screen mode
2. Try to zoom, double tap
Actual Result: Empty screen for all actions - double tap, zoom out/in or swipe the screen 
Expected: Can zoom in/out, swipe the map properly, double tap to zoom
OpenLayers 3 Debug file. Version: v3.4.0 line 60865:
context.drawImage(image, 0, 0, +image.width, +image.height,
          Math.round(dx), Math.round(dy), Math.round(dw), Math.round(dh));
throws IndexSizeError Exception

After I deleted "if" statement of the expression, all functionality became working correct.
Before:(throws exception):
if (frameState.viewState.rotation === 0) {
      var dx = goog.vec.Mat4.getElement(imageTransform, 0, 3);
      var dy = goog.vec.Mat4.getElement(imageTransform, 1, 3);
      var dw = image.width * goog.vec.Mat4.getElement(imageTransform, 0, 0);
      var dh = image.height * goog.vec.Mat4.getElement(imageTransform, 1, 1);
      context.drawImage(image, 0, 0, +image.width, +image.height,
          Math.round(dx), Math.round(dy), Math.round(dw), Math.round(dh));
    } else {
      context.setTransform(
          goog.vec.Mat4.getElement(imageTransform, 0, 0),
          goog.vec.Mat4.getElement(imageTransform, 1, 0),
          goog.vec.Mat4.getElement(imageTransform, 0, 1),
          goog.vec.Mat4.getElement(imageTransform, 1, 1),
          goog.vec.Mat4.getElement(imageTransform, 0, 3),
          goog.vec.Mat4.getElement(imageTransform, 1, 3));
      context.drawImage(image, 0, 0);
      context.setTransform(1, 0, 0, 1, 0, 0);
    }

After("if" statement deleted ):
context.setTransform(
          goog.vec.Mat4.getElement(imageTransform, 0, 0),
          goog.vec.Mat4.getElement(imageTransform, 1, 0),
          goog.vec.Mat4.getElement(imageTransform, 0, 1),
          goog.vec.Mat4.getElement(imageTransform, 1, 1),
          goog.vec.Mat4.getElement(imageTransform, 0, 3),
          goog.vec.Mat4.getElement(imageTransform, 1, 3));
      context.drawImage(image, 0, 0);
      context.setTransform(1, 0, 0, 1, 0, 0);

**Comment by fredj** [comment]
do you mean http://openlayers.org/en/master/examples/full-screen.html ?

**Comment by vdavyskiba** [comment]
Yes. Updated: add device description in report body(MS Surface 1st gen)

**Comment by vdavyskiba** [comment]
closed: not reproducible on OpenLayers v3.7.0
