### ISSUE TITLE
Test ol.format.KML#readNetworkLinks fails on Firefox

### ISSUE THREAD

**Issue by tsauerwein** [openlayers/ol3#3439]
Test: "returns an array of network links"

    expected 'http://localhost:3000/test/bar/bar.kml' to equal 'bar/bar.kml'

**Comment by bartvde** [comment]
right I noticed the same recently: https://github.com/openlayers/ol3/pull/3171#issuecomment-86548794

**Comment by bartvde** [comment]
This is because node.baseURI seems to use window.location.href on Firefox
