### ISSUE TITLE
updateWhileAnimating doesn't cause style functions to re-run

### ISSUE THREAD

**Issue by tremby** [openlayers/ol3#3442]
I have a vector layer which has two styles: one fills the building described in the layer source, and the other draws a polygon pointing from an element on the HTML page (like a control, fixed position with respect to the map canvas) to the building on the map. This is done with the `geometry` option to the style and a style function.

When panning the map (and otherwise animating) the style function isn't reevaluating and so the arrow doesn't point from the HTML element until the animation stops.

I found the `updateWhileAnimating` feature https://github.com/openlayers/ol3/pull/2385 but this isn't helping. Is this a bug, or is there some other workaround I can use to force the style function to reevaluate?

**Comment by tremby** [comment]
I may have made a mistake here. The style function *is* updating in some cases (for instance if I pan and let go so it keeps panning with inertia) but it is not updating while the mouse is still being held down and panning.

**Comment by elemoine** [comment]
> I may have made a mistake here. The style function is updating in some cases (for instance if I pan and let go so it keeps panning with inertia, and the style function is reevaluating) but it is not updating while the mouse is still being held down and panning.

Indeed. That's expected behavior. We could introduce `updateWhileInteracting` as well.

**Comment by tremby** [comment]
That would be extremely helpful. This visual effect doesn't really work otherwise. (But it looks really, really nice while it skids on inertia!)

Any chance that could be squeezed in before the next release, or is it a lot of work?

**Comment by elemoine** [comment]
See https://github.com/openlayers/ol3/pull/3446.

**Comment by tremby** [comment]
Thanks!

**Comment by tremby** [comment]
Related, is there a way to tell the map to reevaluate styles? I want to do this on window resize.

Since my vector style depends on objects outside the map as well as inside the map, when resizing the map things get out of alignment. (Interestingly, the styles update automatically when making the window narrower but not when making it wider.)

**Comment by tremby** [comment]
Here's the effect, if you're interested! http://jsfiddle.net/6QaHA/185/
