### ISSUE TITLE
Allow builds with manage_closure_dependencies

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3452]
We can't currently use `manage_closure_dependencies` reliably because the `olx.js` externs use types that are defined throughout the source - if a build doesn't depend on one of the sources that provides a type used in `olx.js`, the compiler complains about the unrecognized type.

Without `manage_closure_dependencies`, the compiler includes code that is not used by the exports (see #3447).

**Comment by tschaub** [comment]
As mentioned elsewhere, here are two build configs that demonstrate the benefit of setting `"manage_closure_dependencies": true`: https://gist.github.com/tschaub/5e26e51ece8bc13167b5

I still need to put together a build config that demonstrates a failure.

**Comment by elemoine** [comment]
Good [comment](https://github.com/openlayers/ol3/pull/3551#issuecomment-94286985) in #3551 @tschaub. I've come to the same conclusion as you. `manage-closure-dependencies` means exclude files that are not required but (still) include files that don't `goog.provide` any namespace (+ their dependencies) .

**Comment by tschaub** [comment]
So if we had our `@typedef`s in dedicated files with no `goog.provide`, we could send the whole library to the compiler with `"manage_closure_dependencies": true`, and everything would work.

**Comment by elemoine** [comment]
> So if we had our @typedefs in dedicated files with no goog.provide, we could send the whole library to the compiler with "manage_closure_dependencies": true, and everything would work.

It sounds like so to me too. The `@typedef` file could include `goog.provide`'s if we wanted too, but that would not be mandatory.

This would also mean two files for constructor options: an" externs" file and a "typedef" file. I personally think it's acceptable.

**Comment by tschaub** [comment]
> The @typedef file could include goog.provide's if we wanted too, but that would not be mandatory.

Not sure I follow.  If it has a `goog.provide` it won't be included in the build unless explicitly required.  I still need to reproduce it, but this is the issue I was seeing with `olx.js` (types not understood because they were not required by anything in the build profile).

**Comment by elemoine** [comment]
> So if we had our @typedefs in dedicated files with no goog.provide, we could send the whole library to the compiler with "manage_closure_dependencies": true, and everything would work.

But it's not only about `@typedef`'s, no? Think about `olx.MapOptions.prototype.view` whose type is `ol.View`.

(I hope I understand you correctly. Sorry if I don't.)

**Comment by ahocevar** [comment]
If I remember correctly, the reason why `goog.require` `@typedef`s is that we used to have a python script (a long time ago!) to verify dependencies, which simply looked at the used symbols instead of understanding the code.

**Comment by elemoine** [comment]
So we need two things: 1) use `manage-closure-dependencies: true` (because of #3447), and 2) somehow have `goog.require`'s for the types/symbols used in `olx.js`.

So one possible option is to have the `@typedef`'s currently in the `olx.js` externs file in a separate file. That file would include `goog.require`'s for the types used in the `@typedef`'s (see 2) above).

So this would mean two files for the constructor options: an "externs" file and a "typedef" file. The "typedef" file could possibly be automatically generated from the "externs" file.

For example, we'd have this in the "externs" file:

```js
/**
 * Start Tracking. Default is `false`.
 * @type {boolean|undefined}
 * @api stable
 */
olx.GeolocationOptions.prototype.tracking;


/**
 * Tracking options. See
 * {@link http://www.w3.org/TR/geolocation-API/#position_options_interface}.
 * @type {GeolocationPositionOptions|undefined}
 * @api stable
 */
olx.GeolocationOptions.prototype.trackingOptions;


/**
 * The projection the position is reported in.
 * @type {ol.proj.ProjectionLike}
 * @api stable
 */
olx.GeolocationOptions.prototype.projection;

```

and this in the "typedef" file:

```js
goog.require('ol.proj.ProjectionLike');


/**
 * @typedef {{tracking: (boolean|undefined),
 *     trackingOptions: (GeolocationPositionOptions|undefined),
 *     projection: ol.proj.ProjectionLike}}
 * @api
 */
olx.GeolocationOptions;
```

With the "typedef" file including `goog.require`'s we know the compiler will use the dependency files (`proj.js` in the above example) for the compilation.

The problem with this approach is that we have constructor options in two different files, but the "typedef" could be generated automatically.

**Comment by elemoine** [comment]
In case people are interested I've written an ugly script that split `olx.js` into two files: an "externs" file and a "typedef" file. The script and the resulting files are available in my [split-externs branch](https://github.com/openlayers/ol3/compare/master...elemoine:split-externs).

**Comment by fredj** [comment]
`manage_closure_dependencies` is now used.
I assuming this issue is fixed
