### ISSUE TITLE
Create an official tutorial for custom builds

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#3459]
We'll soon have a tutorial for compiling application code and ol3-code, but I think basic tutorial on creating custom builds should be added as well.

We could use this a s starting point: http://boundlessgeo.com/2014/10/openlayers-custom-builds-revisited/

/cc @bartvde

**Comment by elemoine** [comment]
Yes.

In my opinion we need three tutorials:

* Create custom builds.
* Create a Browserify-based OpenLayers 3 application. This tutorial could include a link to the "Create custom builds" tutorial if the user doesn't want to use the full build.
* Create a Closure-based OpenLayers 3 application. This is https://github.com/openlayers/ol3/pull/3441.

**Comment by probins** [comment]
my tutorial has been languishing in the queue since August https://github.com/openlayers/ol3/pull/2489

**Comment by elemoine** [comment]
> my tutorial has been languishing in the queue since August #2489

Yes. I think we should add your "doc/tutorials/buildExamples.md" tutorial, which I'd just rename "custom-builds.md".

**Comment by marcjansen** [comment]
:+1:

**Comment by elemoine** [comment]
I'll do it.
