### ISSUE TITLE
zoomed browser causes loss of map resolution

### ISSUE THREAD

**Issue by pwrelkin** [openlayers/ol3#3471]
I am encountering a problem when an OpenLayers canvas is loaded into a browser webpage that is initially zoomed out. If the webpage is subsequently zoomed in, the OpenLayers canvas resizes proportional to the initial zoom. This causes the map to appear very blurry and pixelated. This is not specific to my code since it occurs with all of the examples on the OpenLayers website.

For example, if the initial webpage zoom is 25% and OpenLayers is loaded into a container that is 500px by 500px, the container size at that zoom is 2000px by 2000px. However, the canvas remains 500px by 500px instead of stretching to 2000px by 2000px. If the zoom then is brought to 100%, the container size is 500px by 500px, and the canvas shrinks to 125px by 125px with the resulting loss of resolution and occurrence of pixelation.

**Comment by ahocevar** [comment]
This behaviour is specific to some browsers (I've only seen it in Chrome so far). It is because when you load the page when the browser zoom is different than 100%, a different device pixel ratio will be reported. You can avoid this issue by configuring your map with

    pixelRatio: 1
