### ISSUE TITLE
Use Jsonix for XML<->JSON converting

### ISSUE THREAD

**Issue by ximex** [openlayers/ol3#3477]
https://www.youtube.com/watch?v=6Wtc08_uNeI (german)
https://github.com/highsource/jsonix

**Comment by elemoine** [comment]
Thanks for the links.

**Comment by ximex** [comment]
I hope this will help. There are already schemas for some OGC standards:
https://github.com/highsource/ogc-schemas

This should make the parsing much easier.

I already use jsonix in a own project. (https://github.com/ximex/ris-bka) It works fine but doesn't have all types/tags/methods they are needed in my project implemented. but it's getting better ;-)

**Comment by bartvde** [comment]
I agree we should try and use JSONIX for all formats that don't involve feature parsing. The last type of parsers is too much tied to the ol3 feature and geometry model etc.

I have already used it in other projects as well and like it a lot. For some types we would need some adapter code, for instance when a Web Map Context document would be translated to JSON by JSONIX, we would still need to write the conversion code to create the layer objects and put them in an ```ol.Map``` object.
