### ISSUE TITLE
The layout of the center example is broken

### ISSUE THREAD

**Issue by elemoine** [openlayers/ol3#3480]
The layout of the center example is broken on master when using the development server (http://localhost:3000/examples/center.html). See the image below. It seems correct when hosted on github.io though.

![ol3-center-example](https://cloud.githubusercontent.com/assets/76594/6988250/c2b089a2-da4f-11e4-8582-8b3f89533f5b.png)

**Comment by bartvde** [comment]
@elemoine I am seeing the same thing on all releases as well?

http://openlayers.org/en/v3.0.0/examples/center.html

**Comment by bartvde** [comment]
okay so the issue is actually that the css files are missing on the master website, they are not copied over
