### ISSUE TITLE
Add a one sentence summary for all exportable symbols.

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3497]
We should have a one sentence (plain text) summary of all our exportable symbols (everything with an `@api` annotation).

The first batch of this work is handled in #3488.  Here's what remains:

 - [x] `ol.Sphere.*` (all `@api`-symbols are documented already)
 - [x] `ol.source.*` (#3580)
 - [ ] `ol.render.*`
 - [x] `ol.proj.*` (#3583)
 - [x] `ol.layer.*` (#3583)
 - [x] `ol.interaction.*` (#3613)
 - [x] `ol.geom.*` (#3619)
 - [ ] `ol.format.*` (#3624)
 - [ ] `ol.events.*` (#3624)
 - [x] `ol.dom.*` (nothing to document)
 - [ ] `ol.control.*` (#3624)
 - [x] `ol.color.*` (all `@api`-symbols are documented already)
 - [ ] `ol.MapBrowserPointerEvent.*` (#3624)
 - [x] `ol.renderer.*`  (all `@api`-symbols are documented already)

**Comment by marcjansen** [comment]
This can be closed now.
