### ISSUE TITLE
Ensure that testcoverage is gathered for all sourcefiles

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#3514]
In the aftermath of #3470 we found out, that the following sourcefiles are not included in the most recent coverages. This is most probably due to the fact that they are not loaded (e.g. required) during running of our testsuite.

This might mean we do not have any tests at all for the following 33 files:

* `src/ol/tilegrid/zoomifytilegrid.js`
* `src/ol/source/zoomifysource.js`
* `src/ol/source/topojsonsource.js`
* `src/ol/source/tilevectorsource.js`
* `src/ol/source/tileutfgridsource.js`
* `src/ol/source/tilejsonsource.js`
* `src/ol/source/tiledebugsource.js`
* `src/ol/source/staticvectorsource.js`
* `src/ol/source/stamensource.js`
* `src/ol/source/osmxmlsource.js`
* `src/ol/source/mapquestsource.js`
* `src/ol/source/kmlsource.js`
* `src/ol/source/imagemapguidesource.js`
* `src/ol/source/igcsource.js`
* `src/ol/source/gpxsource.js`
* `src/ol/source/geojsonsource.js`
* `src/ol/source/bingmapssource.js`
* `src/ol/overlay.js`
* `src/ol/layer/heatmaplayer.js`
* `src/ol/interaction/snapinteraction.js`
* `src/ol/interaction/dragrotateandzoominteraction.js`
* `src/ol/interaction/draganddropinteraction.js`
* `src/ol/imageurlfunction.js`
* `src/ol/geolocation.js`
* `src/ol/format/binaryfeatureformat.js`
* `src/ol/dom/input.js`
* `src/ol/deviceorientation.js`
* `src/ol/control/zoomtoextentcontrol.js`
* `src/ol/control/scalelinecontrol.js`
* `src/ol/control/overviewmapcontrol.js`
* `src/ol/control/mousepositioncontrol.js`
* `src/ol/control/fullscreencontrol.js`
* `src/ol/binary.js`

We could either

1. unconditionally load all `*.js`-files in `src`,
2. or we could add super basic tests for the files listed above

I think I'd go for 2, even though e.g. some of the sources will probably be gone soon.

**Comment by elemoine** [comment]
I hope we can merge the "new vector API" branch first, as it does not make sense to add tests for files we know they will go away.

**Comment by marcjansen** [comment]
Agreed, I'm working on providing basic tests, and I'll leave sources out for now.

**Comment by marcjansen** [comment]
See #3517 (WIP)

**Comment by bartvde** [comment]
I agree on option 2. and merging vector rework first.

**Comment by tsauerwein** [comment]
It's great that you are adding all these tests, but I think we should also make sure that all source files are included in the coverage. Otherwise we always risk to forget newly added files.

**Comment by bartvde** [comment]
@tsauerwein so you suggest using a different loader for the instrumented tests?

**Comment by tsauerwein** [comment]
@bartvde Yep. See #3518

**Comment by bartvde** [comment]
I agree that makes sense as well
