### ISSUE TITLE
The readFeatures (et al.) methods of feature formats should accept a string

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3515]
Currently, we say that `ol.format.Feature#readFeatures` accepts `ArrayBuffer|Document|Node|Object|string`.  In practice though, it only works with one type, not any of the listed types.  This is particularly misleading, especially with the missing documentation for the type accepted (see for example the [`ol.format.GeoJSON#readFeatures` documentation](http://openlayers.org/en/master/apidoc/ol.format.GeoJSON.html#readFeatures) which says anything is accepted and doesn't give more detail - in fact, only an `Object` works).

As with the `writeFeatures` methods (which consistently return a string, see #2102), I think `readFeatures` should consistently accept a string.  The same should be true for `readFeature` and `readGeometry`.

Since we can't make all of these methods accept all types (e.g. it doesn't make sense for `ol.format.GeoJSON#readFeatures` to accept `ArrayBuffer|Document|Node`), I think it would have been best to make them accept only `string`.  We could be strictly backwards compatible by adding support for `string` now and still accepting whatever else they currently do.

**Comment by elemoine** [comment]
> We could be strictly backwards compatible by adding support for string now and still accepting whatever else they currently do.

They do accept a string currently right? So you're suggestion would be to use `string|Object` for JSON and `string|Node|Document` for XML?

**Comment by tschaub** [comment]
Whoa.  I can't say what went wrong there.  Ignore this.

**Comment by elemoine** [comment]
What? Did you miss that the readFeatures methods do accept strings currently? But still, having Node and Document in the signature of ol.format.GeoJSON#readFeatures doesn't make sense to me.

**Comment by tschaub** [comment]
Yeah, I temporarily misread some code and assumed `string` didn't work.

I agree the extra types don't make sense.  I'll repurpose this ticket for moving `readFeatures` up to `ol.format.JSONFeature` and `ol.format.XMLFeature` with more limited types.

I think this means we either use type casts or call more specific methods in `ol.featureloader.loadFeaturesXhr`.  But we could see how that works out.
