### ISSUE TITLE
bindInputs code broke between 3.3.0 and 3.4.0

### ISSUE THREAD

**Issue by gnatwilson** [openlayers/ol3#3525]
I'm really enjoying OL3, the user experience is very good and it's easy to add new layers and tools to the interface.

With 3.4.0, code I borrowed from your layer-group.js has broken.  The map interface breaks with an error that an ol.dom.Input is undefined at the following lines:

function bindInputs(layerid, layer) {
  new ol.dom.Input($(layerid + ' .visible')[0])
      .bindTo('checked', layer, 'visible');
}

map.getLayers().forEach(function(layer, i) {
  bindInputs('#layer' + i, layer);
});

I reverted to using 3.3.0 and the all is fine.  Any help is appreciated.

**Comment by bartvde** [comment]
This functionality will be completely removed with 3.5.0 anyway see: https://github.com/openlayers/ol3/pull/3472 for the detailed discussion

**Comment by bartvde** [comment]
The most relevant part for you to read is in here, it suggests different ways to do this at the application level: https://github.com/openlayers/ol3/blob/c3d5a2e9c49cbe7c08c8379e9a8cb1c0b9b4a475/changelog/upgrade-notes.md

**Comment by gnatwilson** [comment]
My code was referring to the master (http://openlayers.org/en/master/build/ol.js) and not 3.4.0, is it removed from the master already?  I guess I'll need to do a bit more research on how to associate a checkbox with turning a layer on and off without the bindTo method.  Thanks for responding so quickly.

**Comment by bartvde** [comment]
yes it is removed from master

**Comment by gnatwilson** [comment]
Thanks for the link.
