### ISSUE TITLE
ol.source.GeoJSON is not a constructor

### ISSUE THREAD

**Issue by tremby** [openlayers/ol3#3526]
I'm getting this error since about b5a0ca0 (5a7d1f3 is fine) when trying to make a new `ol.source.GeoJSON` object.

**Comment by tschaub** [comment]
See #3481.  Quoting from the `upgrade-notes.md` in [the commit](https://github.com/openlayers/ol3/commit/b5a0ca0589f9afafa98691cf933de6706ff13ce4) that you link to above:

... if you used `ol.source.GeoJSON` as follows:

```js
var source = new ol.source.GeoJSON({
  url: 'features.json',
  projection: 'EPSG:3857'
});
```

you will need to change your code to:

```js
var source = new ol.source.Vector({
  url: 'features.json',
  format: new ol.format.GeoJSON()
});
```

In case it isn't clear, we allow access to some "experimental" features in releases, but these are subject to change or removal.  You'll find the experimental label in the docs for [`ol.source.GeoJSON`](http://openlayers.org/en/v3.4.0/apidoc/ol.source.GeoJSON.html?unstable=true).

**Comment by tremby** [comment]
Thanks very much. Apologies; I should have looked more carefully at the commit I bisected to!
