### ISSUE TITLE
./build.py check should run over the examples_src directory instead?

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#3529]
Currently it will report errors in the examples dir, but I think it makes more sense to run over the examples_src directory instead so that people don't get confused where they need to change the files?

**Comment by bartvde** [comment]
otherwise after fixing the issues you need to manually run ```node tasks/parse-examples.js``` again before running ```./build.py check``` again

**Comment by elemoine** [comment]
https://github.com/openlayers/ol3/pull/3524, which I decided to close, is related.

**Comment by tschaub** [comment]
I've handled this in #3542 as part of other `build.py` changes.
