### ISSUE TITLE
Documentation for ol.View.fitGeometry

### ISSUE THREAD

**Issue by stephan-rayner** [openlayers/ol3#3534]
I am attempting to do something similar to this example of yours... http://openlayers.org/en/v3.3.0/examples/center.html?q=advanced+view
but I cannot for the life of me find any documentation on ol.View.fitGeometry. Is this in the pipeline?

**Comment by bartvde** [comment]
http://openlayers.org/en/v3.4.0/apidoc/ol.View.html?unstable=true#fitGeometry

Make sure to uncheck the stable only checkbox in the top right. Next release will have this unchecked by default.

**Comment by stephan-rayner** [comment]
That was what it was. Thanks for the suggestion. Sorry for the delay in getting this response back to you.
