### ISSUE TITLE
ol.proj.transform unhandled exception

### ISSUE THREAD

**Issue by mrmegabytes** [openlayers/ol3#3535]
it appears there is an error when converting geographics to MGA/UTM coords

ol.proj.transform([151.60856227969708, -32.89173695452235], 'EPSG:4326', 'EPSG:32756');
ol.proj.transform([369853.293895506, 6359901.25733753], 'EPSG:28356', 'EPSG:900913')
ol.proj.transform([369853.293895506, 6359901.25733753], 'EPSG:32756', 'EPSG:900913')

Crashing is:
Uncaught TypeError: Cannot read property 'getCode' of undefined.
ol-debug.js: 19280  version 3.4

**Comment by bartvde** [comment]
Please report issues with ol-debug.js see: http://openlayers.org/ol3-workshop/basics/resources.html#reporting-issues

**Comment by mrmegabytes** [comment]
sorry bartvde, a noob mistake, I forgot I was using the non debug version.  I've now rerun it using the debug libraries.

**Comment by ahocevar** [comment]
Looks like transforms between projections you use are not defined. The easiest way to get them defined is to load the Proj4js library and the CRS definitions for EPSG:28356 and EPSG:32756, which you can get e.g. from http://epsg.io/.

**Comment by mrmegabytes** [comment]
This not the case.  My work around was to incorporate the OpenLayers v2.x library which needed the Proj4js library, as well asn conversion string.
Below are the relevant chunks of code.

<script type="text/javascript"  src="http://cdnjs.cloudflare.com/ajax/libs/proj4js/1.1.0/proj4js-compressed.js"></script>

Proj4js.defs["EPSG:27700"] = "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs";
Proj4js.defs["EPSG:4326"] = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs";
Proj4js.defs["EPSG:900913"] = "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs";
Proj4js.defs["EPSG:28356"] = "+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs ";

var wgs82 = new OpenLayers.Projection("EPSG:4326");
var mga56 = new OpenLayers.Projection("EPSG:28356");

var center = ol.extent.getCenter(extent);
var point = new OpenLayers.LonLat(center[0], center[1]).transform(mga56, new OpenLayers.Projection("EPSG:900913"));
view.setCenter([point.lon, point.lat]);

**Comment by ahocevar** [comment]
You need to use proj4js 2.x with OpenLayers 3, not 1.x.

**Comment by mrmegabytes** [comment]
thanks guy.  i'll look into it.
