### ISSUE TITLE
problem passing from ver 3.3 to 3.4

### ISSUE THREAD

**Issue by ruggix59** [openlayers/ol3#3541]
Today have upgrade my project to ol ver 3.4.0. from 3.3.0. I have a layer with source XYZ with local folders and tiles files.
when i load the layer nothing tile is loaded the browser return:
"Failed to load resource: the server responded with a status of 404 (Not Found)"
for all tile.
go back to version 3.3.0 all returns to work with no code changed.
I noticed
z is correct (no changes)
folder for X parameter non found
tile exist but in another folder.

many thanks for your work

Ruggero La Mantia
(sorry for my english)

**Comment by elemoine** [comment]
We need more information to understand what's going on here. Are you able to come up with a simple test case?

**Comment by ruggix59** [comment]
these are my tiles folders
![image](https://cloud.githubusercontent.com/assets/11911405/7106507/55592eae-e143-11e4-9f84-47f490a38db6.png)


////  **********************this is my initial page 
   <script type="text/javascript">

        // variabili pubbliche
        var NomeUtente = "";
        var Password = "";
        var LayerAttivo = -1;
        var Selezione = null;
        var Segnalazioni = null;
        var InfoBox = null;
        var map = null;
        var scale = { '1:1.000': 1000, '1:2.000': 2000, '1:5.000': 5000, '1:10.000': 10000, '1:20.000': 20000, '1:50.000': 50000 };
        var center = [1506822.131176868, 4569674.295535927];
        var Sicilia = [700958.913598113, 4151993.4180475543, 2266389.2528785225, 5038662.946155598];
        var TerritorioBaucina = [1502352.131176868, 4564406.295535927, 1511292.131176868, 4574942.295535927];
        var MaxExtend = TerritorioBaucina;
        var UTMzone33N = null;
        var CurrentBaselayer = null;
        var svrpath = "@(serverPath)";
        //if (svrpath.substr(svrpath.length-1) != "/") svrpath = svrpath + "/";

        var infopop = new ol.Overlay({ element: $("#infopop") });
        var marker = new ol.Overlay({ element: $("#marker"), positioning: 'bottom-left' });
        var infosign = new ol.Overlay({ element: $("#infosign") });


        $(document).ready(function () {

            //ol.ProxyHost= "Proxy.ashx?url=";

            // Disattiva il bottone di Destra
            //document.oncontextmenu = function () { return false; };

            //Google Maps, OpenStreetMap
            var PseudoMercator = new ol.proj.Projection({
                code: 'EPSG:3857',
                extent: [-20026376.39, -20048966.10, 20026376.39, 20048966.10],
                units: 'm'
            });

            //var UTMzone33N = new ol.proj.Projection({
            //    code: 'EPSG:32633',
            //    // The extent is used to determine zoom level 0. Recommended values for a
            //    // projection's validity extent can be found at http://epsg.io/.
            //    extent: [166021.44, 0.00, 534994.66, 9329005.18],
            //    units: 'm'
            //});
            //ol.proj.addProjection(UTMzone33N);

            proj4.defs("EPSG:32633", "+proj=utm +zone=33 +datum=WGS84 +units=m +no_defs");
            UTMzone33N = ol.proj.get('EPSG:32633');
            UTMzone33N.setExtent([166021.44, 0.00, 534994.66, 9329005.18]);


            map = new ol.Map({
                target: 'map',
                renderer: 'canvas',
                controls: [], // rimuove tutti i controlli di default !!
                view: new ol.View({
                    projection: 'EPSG:3857', //UTMzone33N //EPSG:4326
                    //extent: MaxExtend,
                    //maxResolution: 12, // massima estensione
                    //minResolution: 0.375 // massimo Livello di zoom
                })
            });

            // aggiunge gli overaly alla mappa
            map.addOverlay(infopop);
            map.addOverlay(marker);
            map.addOverlay(infosign);


            // Converte le scale metriche in risoluzioni di OL
            var resolutions = setViewResolutions(map, scale);
            // Legge la massima risoluzione
            var maxResolution = resolutions[resolutions.length - 1];
            // Setta la massima risoluzione in OL
            map.getView().setResolution(maxResolution);


            // configura il Combo delle scale alla risoluzione più prossima
            var scala = getCurrentScaleFromResolution(map, maxResolution);
            setScaleSelect(map, scala);

            //imposta il centro della View. non è necessario se si imposta L'estensione
            map.getView().setCenter(center);
            map.getView().setZoom(12);

            AddCduControl();
            AddNavControls();
            mapSetControls();

            var corsproxy = ""
            //var corsproxy = "http://www.corsproxy.com/"


            //bingAero = AddBingLayer("Bing - foto", false, 'Aerial');
            //bingTerrain = AddBingLayer("Bing - foto labels", false, 'AerialWithLabels');

            //var raster = AddRasterLayer();
            //AtlanteDeagostini = AddWmsLayer("Atlante De Agostini", "http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/de_agostini.map&", "DEAGOSTINI", false, 'EPSG:3857', true);
            //Ortofoto_1988_1989 = AddWmsLayer("Ortofoto 1988-1989", "http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/ortofoto_bn_88.map&", "OI.ORTOIMMAGINI.1988.", false, UTMzone33N.getCode(), true);
            var tmsOrtho = AddTMSLayer("Immagine Territorio", true, svrpath + "public/map/", "1", true);
            //ortofoto = AddWmsLayer("SITR ortofoto 2007-2008", corsproxy + "http://map.sitr.regione.sicilia.it/ArcGIS/services/WGS84_F33/Ortofoto_ATA20072008_f33/MapServer/WMSServer", "0", false, UTMzone33N.getCode(), true);
            //ocm = AddOcmLayer("Open Cycle Map", false);
            //osm = AddOsmLayer("Open Street Map", false);

            //var tmsEdificato = AddTMSLayer("CTR Edificato", true, svrpath + "public/edificato/", "1", false);
            // ***** Senza Il proxy non si hanno autorizzazioni per copiare l'immagine sul CDU *****
            //var ctrEdificato = AddWmsLayer("SITR CTR Edificato", corsproxy+"http://map.sitr.regione.sicilia.it/ArcGIS/services/WGS84_F33/CTR_10000_f33/MapServer/WMSServer", "24", true, UTMzone33N.getCode(), false);
            //var limitiAmministrativi = AddWmsLayer("SITR Limiti Amministrativi", corsproxy+"http://map.sitr.regione.sicilia.it/ArcGIS/services/WGS84_F33/CTR_LimitiAmministrativi_f33/MapServer/WMSServer", "0", true, UTMzone33N.getCode(), false);

            //v4 = AddOsmVector("Osm Vectors", false); // Da verificare!!!!
            //v1 = AddLayerFromdb("Foglio 15 Particelle", '@Url.Action("Vectors", "Maps")', "q1", UTMzone33N.getCode());
            //v3 = AddLayerFromdb("Zone PRG", '@Url.Action("Vectors", "Maps")', "q10", UTMzone33N.getCode());
            //v2 = AddLayerFromdb("Vincoli Territorio", '@Url.Action("Vectors", "Maps")', "q12", UTMzone33N.getCode());
            v4 = AddLayerFromdb("Confini", '@Url.Action("Vectors", "Maps")', "q14", UTMzone33N.getCode());
            //v5 = AddLayerFromdb("Segnalazioni", '@Url.Action("Vectors", "Maps")', "q16", UTMzone33N.getCode());


            // ************ Da inserire dopo aver caricato tutti i layers sulla mappa *************
            AggiornaLegenda($("#LegendaBody"));

            //ZoomToExtend(MaxExtend);


            

            addGeolocation();


            //**************** Eventi ****************


            //map.on('postcompose', function (event) {

            //    var context = event.context.canvas.getContext('2d');
            //    var features = v2.getFeatures();
            //    var imageObj = new Image();
            //    imageObj.onload = function () {
            //        var pattern = context.createPattern(imageObj, 'repeat');
            //        //event.context.rect(50, 50, 50, 50);

            //        features[0].fillStyle = pattern;

            //        //event.context.fillStyle = pattern;
            //        event.context.fill();
            //    };
            //    imageObj.src = "img/corosoft_small.png";

            //    //var features = v2.getFeatures();
            //    //for (var i = 0, ii = features.length; i < ii; i++) {
            //    //    var feature = features[i];

            //    //}
            //    //map.render();
            //});


            $(document).mousemove(function (e) {
                hidemenu(10000);
            });


            $("#ScaleSelect").change(function () {
                var valueSelected = this.value;
                var resolution = setResolution(map, valueSelected);
                map.getView().setResolution(resolution);
            });

            map.getView().on('change:center', function () {
                DisplayInfoMap();
            });

            map.getView().on('change:resolution', function () {
                var ScalaCorrente = getCurrentScaleFromResolution(map, map.getView().getResolution());
                setScaleSelect(map, closest(ScalaCorrente, scale));
                DisplayInfoMap();
            });

            // tasto ESC
            $(document).keydown(function (e) {
                if (e.which == 27) {
                    infosign.setPosition(undefined);
                    infopop.setPosition(undefined);
                    marker.setPosition(undefined);
                    if (Selezione) Selezione.getFeatures().clear();
                    $("#FormInfoProf").hide();
                }
            });

            // Click Mappa!!!!
            map.on('singleclick', function (e) {
                if (e.originalEvent.button == 0) {
                    if (InfoBox == true) { InfoClickButton(e) } else { infopop.setPosition(undefined) };
                    if (Segnalazioni == true) { SegnalazioneMapClick(e) } else { infosign.setPosition(undefined) };
                }
            });

            //map.on('contextmenu', function (event) {
            //    var coordinate1 = event.coordinate;
            //});


            // Click Bottone di destra sulla Mappa!!!!
            //$("#map").mouseup(function (e) {
            //    if (e.button == 2 || e.ctrlKey) {
            //
            //    }
            //});

            $('#ActiveLayer').on('change', function (e) {
                infosign.setPosition(undefined);
                infopop.setPosition(undefined);
                marker.setPosition(undefined);
                Selezione.getFeatures().clear();
            });

            $("#FormInfoProf").find('.panel-heading .close').on('click', function (e) {
                marker.setPosition(undefined);
            });



            $(window).resize(function () {
                menuadjust();
            })

            $("#freccia_left").on("click", function (e) {
                scroll = $(".ScrollingDiv").scrollLeft();
                $(".ScrollingDiv").scrollLeft(scroll - 50);
            });

            $("#freccia_right").on("click", function (e) {
                scroll = $(".ScrollingDiv").scrollLeft();
                $(".ScrollingDiv").scrollLeft(scroll + 50);
            });

            // **************** FINE Eventi ****************
        });


        $(window).load(function () {
            menuadjust();
            //var html = "Benvenuti!</br>Il sito che vi ospita è in corso di sviluppo.</br>";
            //html += "Questa é una versione dimostrativa!</br>";
            //FacileAlertOpen(html, "info")

            DisplayInfoMap();
        })


    </script>

//**************************************
// ***********this is my tiles funtion
function AddTMSLayer(nome) {
   var layer = new ol.layer.Tile({
        source: new ol.source.XYZ({
            projection: 'EPSG:3857',
//          url: Path + "{z}/{x}/{-y}.png", // even with this behaves in a different way 
            tileUrlFunction: tileUrlFunction
        })
    });
    map.addLayer(layer);
    return layer;
}

var tileUrlFunction = function (coordinate) {
    var z = coordinate[0];
    var x = coordinate[1];
    var y = (1 << z) - coordinate[2] - 1;
    var url = 'public/map/' + z + '/' + x + '/' + y + '.png';
   console.log(url);
    return url;
}

//***************************************

this is browser log with 3.3
same tile are out of map and are actually "not found"

AddTileLayers.js:134 public/map/12/2199/2514.png
AddTileLayers.js:134 public/map/12/2199/2515.png
AddTileLayers.js:134 public/map/12/2200/2514.png
AddTileLayers.js:134 public/map/12/2200/2515.png
AddTileLayers.js:134 public/map/12/2201/2514.png
AddTileLayers.js:134 public/map/12/2201/2515.png
AddTileLayers.js:134 public/map/12/2202/2514.png
AddTileLayers.js:134 public/map/12/2202/2515.png
AddTileLayers.js:134 public/map/12/2203/2514.png
AddTileLayers.js:134 public/map/12/2203/2515.png
AddTileLayers.js:134 public/map/12/2204/2514.png
AddTileLayers.js:134 public/map/12/2204/2515.png
2515.png:1 GET http://localhost:50366/public/map/12/2203/2515.png 404 (Not Found)
2515.png:1 GET http://localhost:50366/public/map/12/2200/2515.png 404 (Not Found)
2514.png:1 GET http://localhost:50366/public/map/12/2200/2514.png 404 (Not Found)
2514.png:1 GET http://localhost:50366/public/map/12/2203/2514.png 404 (Not Found)
2515.png:1 GET http://localhost:50366/public/map/12/2199/2515.png 404 (Not Found)
2515.png:1 GET http://localhost:50366/public/map/12/2204/2515.png 404 (Not Found)
2514.png:1 GET http://localhost:50366/public/map/12/2199/2514.png 404 (Not Found)
2514.png:1 GET http://localhost:50366/public/map/12/2204/2514.png 404 (Not Found)

this is the result. the image is centered properly
![image](https://cloud.githubusercontent.com/assets/11911405/7106479/57742dfc-e142-11e4-96e1-f5285b5356cd.png)



this is browser log with 3.4
AddTileLayers.js:134 public/map/12/2197/2513.png
AddTileLayers.js:134 public/map/12/2197/2514.png
AddTileLayers.js:134 public/map/12/2197/2515.png
AddTileLayers.js:134 public/map/12/2198/2513.png
AddTileLayers.js:134 public/map/12/2198/2514.png
AddTileLayers.js:134 public/map/12/2198/2515.png
AddTileLayers.js:134 public/map/12/2199/2513.png
AddTileLayers.js:134 public/map/12/2199/2514.png
AddTileLayers.js:134 public/map/12/2199/2515.png
AddTileLayers.js:134 public/map/12/2200/2513.png
AddTileLayers.js:134 public/map/12/2200/2514.png
AddTileLayers.js:134 public/map/12/2200/2515.png
AddTileLayers.js:134 public/map/12/2201/2513.png
AddTileLayers.js:134 public/map/12/2201/2514.png
AddTileLayers.js:134 public/map/12/2201/2515.png
AddTileLayers.js:134 public/map/12/2202/2513.png
AddTileLayers.js:134 public/map/12/2202/2514.png
AddTileLayers.js:134 public/map/12/2202/2515.png
2514.png:1 GET http://localhost:50366/public/map/12/2199/2514.png 404 (Not Found)
2514.png:1 GET http://localhost:50366/public/map/12/2198/2514.png 404 (Not Found)
:50366/public/map/12/2199/2515.png:1 GET http://localhost:50366/public/map/12/2199/2515.png 404 (Not Found)
2515.png:1 GET http://localhost:50366/public/map/12/2200/2515.png 404 (Not Found)
2513.png:1 GET http://localhost:50366/public/map/12/2199/2513.png 404 (Not Found)
2514.png:1 GET http://localhost:50366/public/map/12/2200/2514.png 404 (Not Found)
2515.png:1 GET http://localhost:50366/public/map/12/2198/2515.png 404 (Not Found)
2513.png:1 GET http://localhost:50366/public/map/12/2198/2513.png 404 (Not Found)
2514.png:1 GET http://localhost:50366/public/map/12/2197/2514.png 404 (Not Found)
2513.png:1 GET http://localhost:50366/public/map/12/2200/2513.png 404 (Not Found)
2515.png:1 GET http://localhost:50366/public/map/12/2197/2515.png 404 (Not Found)
2513.png:1 GET http://localhost:50366/public/map/12/2202/2513.png 404 (Not Found)
2513.png:1 GET http://localhost:50366/public/map/12/2197/2513.png 404 (Not Found)
2513.png:1 GET http://localhost:50366/public/map/12/2201/2513.png 404 (Not Found)

this is the result. the image is shifted to the right
![image](https://cloud.githubusercontent.com/assets/11911405/7106470/1922d846-e142-11e4-8734-eb4de261a628.png)
