### ISSUE TITLE
Rename examples_src to examples

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3547]
I'd like it if the built examples could go in `build/examples`.  This would make it easier to search for things in our sources (if you exclude `build` when searching) and people would be less prone to accidentally editing the built examples.

The slight downside of this is that after `npm start` you browse to `http://localhost:3000/build/examples/` to view the examples (instead of `http://localhost:3000/examples/`).  An alternative would be to rework things in a bigger way and run the development server with a different root, but I'm trying to make incremental improvements.

Any other opinions?

**Comment by ahocevar** [comment]
I'd be in favour of such a change, and I have no strong opinion on whether to change the development server root or to browse to `http://localhost:3000/build/examples/` to run the examples.

**Comment by bartvde** [comment]
I would be supportive of this change, and wouldn't mind browsing to build/examples

**Comment by fredj** [comment]
+1 to move the examples to build

**Comment by gberaudo** [comment]
+1

**Comment by elemoine** [comment]
+1, I don't like having both `examples` and `examples_src` at the root of the repo. It's confusing. `build/examples` sounds good to me.

**Comment by tschaub** [comment]
Ok, I've started on this (and some other cleanup of `build.py` related to examples) in my [`built-examples` branch](https://github.com/openlayers/ol3/compare/openlayers:master...tschaub:built-examples).

**Comment by elemoine** [comment]
You finally decided against using `build/examples` as the destination directory?

**Comment by tschaub** [comment]
> You finally decided against using build/examples as the destination directory?

No, I just had a temporary commit in place to start untangling all the resources that the examples depend on.  The change is fairly involved, see #3558.
