### ISSUE TITLE
Rotation of RegularShape symbol is different between canvas and WebGL

### ISSUE THREAD

**Issue by tsauerwein** [openlayers/ol3#3563]
The rotation of RegularShape symbols is not the same for the canvas renderer and the WebGL renderer.

Test-case:
https://github.com/openlayers/ol3/blob/c0a23dc8185558cb0bec4fd70ba9a029481236ec/test_rendering/spec/ol/style/regularshape.test.js

Canvas
![regularshape-canvas](https://cloud.githubusercontent.com/assets/266474/7158710/011b8184-e37d-11e4-9155-8ad463addd87.png)
WebGL
![regularshape-webgl](https://cloud.githubusercontent.com/assets/266474/7158711/03601d7e-e37d-11e4-959e-3fd105388729.png)

**Comment by gberaudo** [comment]
I am wondering why the WEBGL version is so blurred.

**Comment by tschaub** [comment]
> I am wondering why the WEBGL version is so blurred.

Missing ["snap to pixel" handling](https://github.com/openlayers/ol3/blob/31cebc7c8a210520073bda92af9823e86bdf399a/src/ol/render/canvas/canvasreplay.js#L859).

**Comment by tsauerwein** [comment]
I think this is related to that we are using `gl.LINEAR` for `gl.TEXTURE_MAG_FILTER` and `gl.TEXTURE_MIN_FILTER` (see [ol.webgl.Context.createTexture](https://github.com/openlayers/ol3/blob/e2b37a74a592a98d80761fe52969f031a387a611/src/ol/webgl/context.js#L367-368)). If I remember correctly `gl.NEAREST` made icons look blurry.

**Comment by fredj** [comment]
fixed with #6169
