### ISSUE TITLE
Earthquake heatmap example broken

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3564]
Perhaps `extractStyles: false` is [no longer working](http://openlayers.org/en/master/examples/heatmap-earthquakes.html).

![image](https://cloud.githubusercontent.com/assets/41094/7162050/ac63a59a-e34f-11e4-983d-e423eec06b5c.png)

**Comment by elemoine** [comment]
Yes, `ol.source.Vector` does not have an `extractStyles` option. Thanks for reporting that bug. I'll have a look.

**Comment by fredj** [comment]
I'm also looking at it, a patch is ready
