### ISSUE TITLE
Stop using gjslint.py

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3567]
I'd like to move on from using `gjslint.py`.  [ESlint](http://eslint.org/) is a far more configurable and capable tool.  I'm going to start by replacing our use of JSHint with ESLint and then see if I can convince others that `gjslint.py` can be removed.

**Comment by elemoine** [comment]
gjslint catches Closure-related things, such as a missing `@private` annotation for an underbar suffixed members. Do you think we just don't need a linter that catches Closure-related errors? Or do you think we can use ESLint plug-ins (if possible?) for Closure? Just asking...

**Comment by probins** [comment]
Closure compiler's linter has just been separated out into its own jar. https://github.com/google/closure-compiler/commit/4782e1a9ea95bd25ae0dc10775be4f7f660fba7a Not sure how far this can be used as a substitute for gjslinter, though the comment that they'll be using it on the Closure lib itself sounds promising.

**Comment by tschaub** [comment]
My editor is not configured to use `gjslint.py`, so I don't find out about it until `make check`, at which time I'd rather just let the Compiler catch any Compiler-specific issues.

I prefer the ESLint rules (and their configuration options) to what is enforced by `gjslint.py`, so I don't see a need for it in terms of coding conventions.  Rules are pretty straightforward to implement, so if we really feel there are things we want enforced, and there isn't a rule already, we could create one (and make it available to others who might share the same conventions).

The [`valid-jsdoc` rule](http://eslint.org/docs/rules/valid-jsdoc.html) provides some light documentation checking - which I think is sufficient for our needs.  We have very real problems with our documentation that are not being caught by `gjslint.py`, so I don't think our documentation quality would go down by getting rid of it.

In addition, I think ESLint brings a lot of rules that do catch real coding mistakes.  I can't think of a single example where `gjslint.py` has caught a real mistake, and it has not been uncommon for me to have ESLint correct errors before I even save a change.

> gjslint catches Closure-related things, such as a missing @private annotation for an underbar suffixed member

This is an interesting point.  If we were to ditch this convention of using underscore suffixed names for private members, we would not satisfy `gjslint.py`, but we could instead conform with the majority of the JavaScript development community - where underscore *prefixed* names are private.

**Comment by bartvde** [comment]
I've also been using ESLint on a few projects and very happy with it

**Comment by marcjansen** [comment]
We're also using it and have had good experience so far, especially the integration into editors is easy.

**Comment by ahocevar** [comment]
I'm also a happy ESLint user, and it is integrated in Atom almost out of the box. Personally, I'm +1 for ditching gjslint.py.

The `@private` and `@opt_` annotation checks are the only ones we'd be missing I guess, which I consider quite minor.

**Comment by elemoine** [comment]
No doubt that `ESLint` is a good tool. And I totally trust you that it'll catch more errors than `gjslint`. But what I'd like to understand is why ditching `gjslint` instead of using **both** `ESLint` and `gjslint`. Some of the things that `gjslint` enforces for us and that I think are relevant for the project:

- Members suffixed with a `_` have a `@private` marker (and corollary)
- Optional parameters are prefixed with `opt_` (and corollary)
- Function parameters have associated docs (`@param`) (and corollary)
- Functions that return a value have associated docs (`@return`) (and corollary)
- `goog.provide`'s and `goog.require`'s are alphabetized
- Annotations (e.g. `@param`) are correctly formed
- Two blank lines between top-level blocks
- Three blank lines before constructors/interfaces

Don't you agree that these are relevant? So why not use both `gjslint` and `ESLint` (just as we use both `JSHint` and `gjslint` today)?

**Comment by tschaub** [comment]
> Members suffixed with a _ have a @private marker (and corollary)

If we switched to using `_` *prefixed* names, we'd match expectations of developers working on other JavaScript projects.  I'm not suggesting we have to do this, but `gjslint` enforces a convention that is not common in this case.

> Optional parameters are prefixed with opt_ (and corollary)

We do some extra work when building our documentation to get rid of this `opt_` prefix.  I think both the docs and code could be more readable without this prefix (and we could include explicit documentation where arguments are optional).  But I'm not opposed to maintaining this convention if others like it.

> Function parameters have associated docs (@param) (and corollary)

I think we can get what we need out of the [JSDoc plugin](https://www.npmjs.com/package/eslint-plugin-jsdoc) for ESLint.  Where features are missing, we can create a custom rule or contribute to this plugin.

> Functions that return a value have associated docs (@return) (and corollary)

See above.

> goog.provide's and goog.require's are alphabetized

I look forward to a time when we don't have `goog.provide` and `goog.require`.  I'm not sure how much value this brings, but we could create a rule about alphabetized `goog` calls in the meantime.

> Annotations (e.g. @param) are correctly formed

See above.

> Two blank lines between top-level blocks

My preference would be to [disallow multiple empty lines](http://eslint.org/docs/rules/no-multiple-empty-lines) altogether.

> Three blank lines before constructors/interfaces

See above.  I think the distinction between top level blocks, constructors, and interfaces is arbitrary.  I think it is easier to adopt to a more consistent "no multiple empty lines" rule.

**Comment by bartvde** [comment]
well said @tschaub

**Comment by ahocevar** [comment]
I also agree with @tschaub's assessment.

**Comment by fredj** [comment]
And we should consider activating the `lintChecks` compiler option

**Comment by gberaudo** [comment]
Are you considering a transition period with both linters?

**Comment by ahocevar** [comment]
@gberaudo What would be the benefit of a transition period in your opinion?

**Comment by gberaudo** [comment]
@ahocevar, it would ensure no error gets through `ESLint` undetected.
If such error is detected by `gjslint`, then we have the opportunity to update `ESLint` configuration.

**Comment by ahocevar** [comment]
@gberaudo As @tschaub pointed out, we're not relying on gjslint to prevent errors, but to enforce a certain code and documentation style. Errors (e.g. missing function params, returns etc.) are detected by the compiler anyway. So there should be no need to keep gjslint around once ESLint is in place.

**Comment by gberaudo** [comment]
@ahocevar, I tried removing a parameter definition and it was only detected by `gjslint`:
```diff
diff --git a/src/ol/map.js b/src/ol/map.js
index 91f02c0..faeb06f 100644
--- a/src/ol/map.js
+++ b/src/ol/map.js
@@ -571,7 +571,6 @@ ol.Map.prototype.beforeRender = function(var_args) {
 
 
 /**
- * @param {ol.PreRenderFunction} preRenderFunction Pre-render function.
  * @return {boolean} Whether the preRenderFunction has been found and removed.
  */
 ol.Map.prototype.removePreRenderFunction = function(preRenderFunction) {
```

**Comment by ahocevar** [comment]
Ok @gberaudo, but we get these checks from eslint anyway: http://eslint.org/docs/rules/valid-jsdoc.html.
