### ISSUE TITLE
OSM XML example broken

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3577]
I'm not seeing any vector data rendered on this example: http://openlayers.org/en/master/examples/vector-osm.html

It looks like there are frequent `504`s from [the server](http://overpass-api.de/api/xapi?map?bbox=6.635742187499986,46.781254534638606,6.638488769531236,46.78313532151748).  Not sure how common these are.  I came across the issue when running our `check-examples` target with debug logging from Phantom.  Then confirmed that data doesn't load reliably in my browser either.

**Comment by elemoine** [comment]
I don't see any problem right now. But if the server is not reliable, I personally don't have any problem removing that example.

**Comment by tschaub** [comment]
Just tried again from work.  Here is typical console output for me (`504`s and `429`s).

![image](https://cloud.githubusercontent.com/assets/41094/7208239/914b48a4-e4fc-11e4-8aa5-7d8a20692fcd.png)

I haven't profiled to know if it is waiting, parsing, or rendering that takes so long, but even when features do render, I think the example looks pretty bad (I'd blame it on the library if I didn't know better).

**Comment by fredj** [comment]
see #5988

 http://overpass-api.de/ is no longer available.

**Comment by mmd-osm** [comment]
That's not quite correct, only xapi?map is currently disabled to due abusive usage. But you can easily switch to Overpass QL.
