### ISSUE TITLE
ol.extent.intersectsSegment sometimes wrong

### ISSUE THREAD

**Issue by rattai** [openlayers/ol3#3585]
ol.extent.intersectsSegment([1, 1, 2, 4], [4, 5], [-1, 0])
returns false when it should be true.

This example fails the bottom-intersection test and is never allowed to reach the left-intersection test, which it would pass.

**Comment by marcjansen** [comment]
Thanks. Any chance you can turn this into a failing test? This way it'd be easier to validate the issue and create a fix.

**Comment by tschaub** [comment]
This is indeed a valid issue.  Pull request coming.
