### ISSUE TITLE
Broken/missing links in docs for source.Vector

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#3588]
http://openlayers.org/en/master/apidoc/ol.source.Vector.html - constructor options

* ol.FeatureLoader and ol.LoadingStrategy should link to typedef
* ol.featureloader.xhr is linked from url, but doesn't exist

Also, the docs for `loader` are surely wrong; 'src' should read 'url', no?
And what's 'url' at the end of format supposed to mean? Delete this?
And, under strategy, 'features at loaded' should presumably read 'features are loaded'

I can create a PR for this if someone can remind me what has to be added where so the links work ;-)

**Comment by fredj** [comment]
> ol.featureloader.xhr is linked from url, but doesn't exist

A `featureloader.jsdoc` file is probably missing.

**Comment by elemoine** [comment]
PR welcome then. Thanks @probins!

**Comment by fredj** [comment]
@probins I've updated the API doc from master and the "ol.FeatureLoader and ol.LoadingStrategy should link to typedef" issue is now fixed

**Comment by probins** [comment]
> A featureloader.jsdoc file is probably missing.

#3595

**Comment by probins** [comment]
fixed with #3599
