### ISSUE TITLE
Autopan with bootstrap popover

### ISSUE THREAD

**Issue by Federico-G** [openlayers/ol3#3606]
In this example:
http://openlayers.org/en/v3.4.0/examples/popup.html
A self-made popup is used to show information. It's in a overlay with autoPan: true;

I really like this new feature so I want to add it to my proyect. I'm using bootstrap popover in the same way as here:
http://openlayers.org/en/v3.4.0/examples/overlay.html

The problem is that the overlay size is 0 and it's in the bottom of the overlay.
Here is an example:
http://jsbin.com/cihufubuhu/

If you click close to the top border of the map, it would shift but only to the bottom part of the popover (the popover appears with a gap intentionally)

**Comment by tsauerwein** [comment]
I wasn't able to get the Popover popups to work with `autopan`. If it's just the Popover styling that you are after, you could only use the Popover CSS classes, like in this example: http://jsfiddle.net/0wrannj5/3/

**Comment by Federico-G** [comment]
@tsauerwein Thanks for the answer. I follow your advice and your code and I improve it, so it can receive dinamic content, and fix some classes and css.

Hope it helps anyone with the same problem

http://jsbin.com/royikevuno/1/

http://jsbin.com/royikevuno/1/edit?html,css,js,output
