### ISSUE TITLE
Create a download page with links and instructions

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3615]
The GitHub [releases page](https://github.com/openlayers/ol3/releases) is not a good place to send people looking to download.  It is not clear which of the archives to download, and the release notes make the links harder to find.  Instead, we should have a dedicated download page that includes the following:

 * link to a minimal distribution with JS and CSS builds
 * link to an archive that includes API docs, examples, and builds
 * link to the release notes
 * link to instructions on creating custom builds

**Comment by ahocevar** [comment]
Didn't @klokan do some work on this already?

**Comment by tschaub** [comment]
Minimal version added in https://github.com/openlayers/openlayers.github.io/commit/bc3aac7d5c038e1e37ddb1a702bcd79f293a557a.  Can be improved there (should be an openlayers/openlayers.github.io issue instead of an ol3 one).
