### ISSUE TITLE
ol.js missing methods that are in src and ol-debug.js (3.4.0)

### ISSUE THREAD

**Issue by umphy** [openlayers/ol3#3620]
Hi, I'm currently using version 3.4.0 via cdnjs (https://cdnjs.com/libraries/ol3).

I noticed that for ```ol.geom.Circle``` (https://github.com/openlayers/ol3/blob/v3.4.0/src/ol/geom/circle.js), there is a method called ```containsXY ```. However, this method is missing from the ol.js (and ol.min.js), but is in ol-debug.js.

**Comment by marcjansen** [comment]
That method probably isn't marked 'stable' and therefore being renamed by the closure compiler.

Please reopen if it is stable and missing.

**Comment by tschaub** [comment]
What @marcjansen said except the renaming is about the symbols being exportable, not necessarily stable.

When we create a full build of the library, the compiler minifies the size by renaming things that we haven't marked as part of the public API.  If you're looking at the source, you can see the `@api` annotation on properties and methods that will become part of the public API (accessible from a build of the library).  We call these "exportable" symbols.  There are two classes of exportable symbol: stable and experimental.  Names marked with `@api stable` are part of the stable API - these are things that we promise won't change between major versions.  Names that are just marked with `@api` (and no word after it) are experimental.  Basically, if you use them, you accept the responsibility of doing some work when you upgrade to a new release.

If you look at the [API docs](http://openlayers.org/en/master/apidoc), you can see what is included in the API (both stable and experimental).

**Comment by umphy** [comment]
Thank you both for your explanations. Much appreciated.
