### ISSUE TITLE
make install doesn't work after clearing node_modules

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#3642]
```
Barts-MacBook-Air:ol3_bartvde bartvandeneijnden$ rm -rf node_modules/
Barts-MacBook-Air:ol3_bartvde bartvandeneijnden$ make install
make: Nothing to be done for `install'.
```

Running npm install does work in this case.

**Comment by elemoine** [comment]
Yes, that's expected. Either run `npm install` or do `rm build/timestamps/node-modules-timestamp` before running `make install` again. I could try to improve this.

**Comment by fredj** [comment]
@bartvde can we close this issue?

**Comment by bartvde** [comment]
Sure.
