### ISSUE TITLE
`tasks/test-coverage.js` wrongly detects the outputfilename to store instrumented sources

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#3643]
`tasks/test-coverage.js` has: 

```javascript
var outfile = file.replace(/\/src\//, '/src-instrumented/');
```

which is from https://github.com/openlayers/ol3/blob/master/tasks/test-coverage.js#L142 

We noticed this actually leads to errors in #3640#issuecomment-97367282

**Comment by elemoine** [comment]
Working on a fix…
