### ISSUE TITLE
Building on Windows with Make and Cygwin

### ISSUE THREAD

**Issue by bill-chadwick** [openlayers/ol3#3648]
Now that the build system is updated to use Make, a Make is needed for building on Windows. The best way to do this looks to be to install Cygwin. When installing Cygwin be sure to include the  Developer Tools. The install will take quite a while. There are 32 and 64 bit installers here https://www.cygwin.com/

After Installing CygWin, modify the 'Cygwin Terminal' desktop shortcut to 'Run As Administrator', otherwise file permission errors will occur when building ol3. All building must be done from the Cygwin Terminal.

The tasks\generate-info.js script needs updating for windows following the changes posted a while ago here. https://github.com/openlayers/ol3/pull/2813/files#diff-47e08054189bdf70c82633c1a2479eca

It would be good if CONTRIBUTING.md could have some Windows tips added and tasks\generate-info.js be updated. I guess I could do a PR for that when all is working though I will need some more help to get there.

With the generate-info.js patch applied, most Make targets look to be working reliably (see below). The only major problem target is host-examples. If anyone can help with that , please chip in !

**CHECK-DEPS**

_$ make check-deps
Program git OK
Program node OK
Program python OK
Program java OK_

**CLEAN**

_$ Make clean
rm -f build/timestamps/gjslint-timestamp
rm -f build/timestamps/jshint-timestamp
rm -f build/timestamps/check-*-timestamp
rm -f build/ol.css
rm -f build/ol.js
rm -f build/ol.js.map
rm -f build/ol-debug.js
rm -f build/test_requires.js
rm -f build/test_rendering_requires.js
rm -rf build/examples
rm -rf build/compiled-examples
rm -rf build/hosted/projection_

**BUILD**

_$ make build
node tasks/build.js config/ol.json build/ol.js
info ol Parsing dependencies
info ol Compiling 355 sources
ERR! compile Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
ERR! compile
uncompressed: 471295 bytes
  compressed: 140224 bytes
node tasks/build.js config/ol-debug.json build/ol-debug.js
info ol Parsing dependencies
info ol No compile options found.  Concatenating 355 sources
uncompressed: 3802301 bytes
  compressed: 702140 bytes_

The TieredCompilation report does not seem to be important.

**LINT**

_$ make lint
Running gjslint...
327 files checked, no errors found.
Running jshint...
2015-04-29 20:35:21,373 check-requires: test/spec/ol/interaction/modifyinteraction.test.js:84 missing goog.require('ol.geom.Point')
2015-04-29 20:35:21,606 check-requires: 0 unused goog.requires, 1 missing goog.requires_

**TEST**

This looks to work well with the proper green ticks being displayed.

_$ make test
node tasks/test.js
  ol.collection
    create an empty collection
      ✓ creates an empty collection
    create a collection from an array
......
  1606 passing (13s)_

**CHECK**

_$ make check
Running gjslint...
..........
..........
  1606 passing (13s)_

**HOST-EXAMPLES**

This looks to have some issues, which I have yet to fathom out. If anyone can help, please chip in.
This target is fairly vital for checking that the Examples and Library actually work ! 

First attempt

_$ make host-examples
node tasks/build.js config/ol-debug.json build/ol-debug.js
info ol Parsing dependencies
info ol No compile options found.  Concatenating 355 sources
uncompressed: 3802301 bytes
  compressed: 702140 bytes
Running cleancss..._

_Error: EINVAL, invalid argument
    at new Socket (net.js:157:18)
    at process.stdin (node.js:687:19)
    at Object.<anonymous> (C:\ol3\ol3\node_modules\clean-css\bin\cleancss:54:52)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
Makefile:284: recipe for target 'build/ol.css' failed
make: *** [build/ol.css] Error 8_

Second attempt

_$ make host-examples
cp: cannot stat ‘C:ol3ol3node_modulesclosure-util.depslibraryb0b32b6477e735055b8f53284d5cf6a4af1b29da/*’: No such file or directory
Makefile:159: recipe for target 'host-libraries' failed
make: *** [host-libraries] Error 1_

**CI**

_$ make ci
node tasks/test.js
...
node tasks/test-rendering.js
Gecko: 35.0.1_

A couple of small browser windows appear, one with a SlimerJS logo and the other blank with a title of 'webpage'. I am not really sure what is meant to happen at this point.

_Script Error: [JavaScript Error: "ReferenceError: goog is not defined" {file: "http://127.0.0.1:3001/test_rendering/index.html" line: 45}]
       Stack:
         -> http://127.0.0.1:3001/test_rendering/index.html: 45_

_Error getting the exit status of SlimerJS
Makefile:143: recipe for target 'test-rendering' failed
make: *** [test-rendering] Error 1_

**SERVE**

This works a bit after a 'clean' and two attempts, but only an empty examples index page shows.

_$ make serve
node tasks/serve.js
info serve Building examples.
ERR!Makefile:130: recipe for target 'serve' failed
make: *** [serve] Error 1_

_$ make serve
node tasks/serve.js
info serve Building examples.
info serve Parsing dependencies.
info serve Listening on http://localhost:3000/ (Ctrl+C to stop)_

**Comment by probins** [comment]
Specifying Tiered Compilation was a temporary thing in Java 7; it is used by default in Java 8. Assuming everyone is now using Java 8, it should probably be removed. IIRC this is defined in closure-util

**Comment by bill-chadwick** [comment]
Hi Peter.
Do you know anything about the cleancss failure?

**Comment by kalbermattenm** [comment]
I did give a try, but I can't get `make build` work correctly.

I first get an error because of `cleancss`, @bill-chadwick seems to have the same error...

Then, if I re-run `make build`, then I get an error because of node.

Simply running node in Cygwin, throws an error (see hereunder).

@bill-chadwick, how does that react on your side ?

```shell
$ make clean
rm -f build/timestamps/gjslint-timestamp
rm -f build/timestamps/jshint-timestamp
rm -f build/timestamps/check-*-timestamp
rm -f build/ol.css
rm -f build/ol.js
rm -f build/ol.js.map
rm -f build/ol-debug.js
rm -f build/test_requires.js
rm -f build/test_rendering_requires.js
rm -rf build/examples
rm -rf build/compiled-examples
rm -rf build/hosted/master

$ make lint
Running gjslint...
477 files checked, no errors found.
Running jshint...

$ make build
Running cleancss...

Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at Object.<anonymous> (C:\git_projects\ol3\node_modules\clean-css\bin\cleancss:54:52)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Makefile:284 : la recette pour la cible « build/ol.css » a échouée
make: *** [build/ol.css] Erreur 8

$ make build
node tasks/build.js config/ol.js
on build/ol.js
ERR!Makefile:290 : la recette pour la cible « build/ol.js » a échouée
make: *** [build/ol.js] Erreur 1

$ node

net.js:156
    this._handle.open(options.fd);
                 ^
Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at startup (node.js:145:16)
    at node.js:906:3
```

**Comment by probins** [comment]
I'd suggest running the underlying cmds without make, though I'm afraid Node's error msgs are often not very helpful :-(

**Comment by kalbermattenm** [comment]
Yes, that would be a solution... But it looks like @bill-chadwick was able to make node work inside the Cygwin terminal...

I was interested in knowing how he managed that...

**Comment by ponceta** [comment]
http://stackoverflow.com/questions/10043177/node-js-cygwin-not-supported

This seems very hacky to me :) (not tested yet)

**Comment by kalbermattenm** [comment]
OK... I found why node was not working... Actually, if you use the nodejs msi installer, I should not install node in the default proposed directory (`C:\Program Files\nodejs\`), but install it in a space free directory (something like `C:\nodejs\`), then it works quite good through the Cygwin bash... (should have seen that earlier... sorry for all the noise...)

After that, I did the same tests as @bill-chadwick, having pretty much the same results... See stack hereunder.

Running `make serve` the second time makes the `http://localhost:3000/build/examples` accessible, but all examples have the ol3 gray background and Firebug contains the following error (for all needed js files, I guess...):
```
http://localhost:3000/build/examples/loader.jsC:%5Cgit_projects%5Col3%5Cnode_modules%5Cclosure-util%5C.deps%5Clibrary%5Cb0b32b6477e735055b8f53284d5cf6a4af1b29da%5Cclosure%5Cgoog%5Chtml%5Cuncheckedconversions.js
```
Stack:
```shell
$ make build
node tasks/build.js config/ol.json build/ol.js
info ol Parsing dependencies
info ol Compiling 355 sources
uncompressed: 470678 bytes
  compressed: 139888 bytes
node tasks/build.js config/ol-debug.json build/ol-debug.js
info ol Parsing dependencies
info ol No compile options found.  Concatenating 355 sources
uncompressed: 3797230 bytes
  compressed: 700599 bytes


$ make test
node tasks/test.js

  ol.collection
    create an empty collection
      ? creates an empty collection
....
  1597 passing (8s)

$ make host-examples
cp: impossible d'évaluer « C:git_projectsol3node_modulesclosure-util.depslibraryb0b32b6477e735055b8f53284d5cf6a4af1b29da/* »: No such file or directory
Makefile:159 : la recette pour la cible « host-libraries » a échouée
make: *** [host-libraries] Erreur 1

$ make ci
node tasks/test-rendering.js
Gecko: 35.0.1

Script Error: [JavaScript Error: "ReferenceError: goog is not defined" {file: "http://127.0.0.1:3001/test_rendering/index.html" line: 45}]
       Stack:
         -> http://127.0.0.1:3001/test_rendering/index.html: 45

$ make serve
node tasks/serve.js
info serve Building examples.
ERR! serve Building examples failed.
ERR! serve Failed to write the file at: C:\git_projects\ol3\build\examples\accessible.css
ERR! serve
ERR! serve EPERM, mkdir 'C:\git_projects\ol3\build\examples'
ERR! serve Use "verbose" logging to see the full stack trace.
Makefile:130 : la recette pour la cible « serve » a échouée
make: *** [serve] Erreur 1

$ make serve
node tasks/serve.js
info serve Building examples.
info serve Parsing dependencies.
info serve Listening on http://localhost:3000/ (Ctrl+C to stop)
```

**Comment by bill-chadwick** [comment]
Its just host-examples that is not working. 
Even with the build folder under Cygwin Home, I still get

$ make host-examples
node tasks/build.js config/ol.json build/ol.js
info ol Parsing dependencies
info ol Compiling 355 sources
ERR! compile Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
ERR! compile
uncompressed: 471295 bytes
  compressed: 140224 bytes
node tasks/build.js config/ol-debug.json build/ol-debug.js
info ol Parsing dependencies
info ol No compile options found.  Concatenating 355 sources
uncompressed: 3802301 bytes
  compressed: 702140 bytes
Running cleancss...
cp: cannot stat ‘C:cygwinhomeUserol3node_modulesclosure-util.depslibraryb0b32b6477e735055b8f53284d5cf6a4af1b29da/*’: No such file or directory
Makefile:159: recipe for target 'host-libraries' failed
make: *** [host-libraries] Error 1

just like kalbermattenm .

It looks like there are \ characters missing from the copy path when running cleancss.

If any Cygwin and/or Node experts out there could help, it would be much appreciated.

**Comment by bill-chadwick** [comment]
The issue looks to be todo with the final /build/ol-deps.js step

**Comment by elemoine** [comment]
It sets the CLOSURE_LIB var to the file system path including the Closure Library. That path is obtained by running a node command that gets the path by calling getLibraryPath provided by the closure-util node package.

**Comment by bill-chadwick** [comment]
Thans Eric,
That process looks to be failing on Windows - returning a path missing its
slashes. Do you know why that might be?

**Comment by probins** [comment]
see https://github.com/openlayers/closure-util/blob/master/lib/util.js. From the fact that the normal build works correctly, something specific to the hosted examples must be setting up incorrect paths. What do you get if you run that node cmd directly?
`node -e 'process.stdout.write(require("closure-util").getLibraryPath())`

I think the cleancss msg is misleading. I don't think this has anything to do with cleancss

**Comment by bill-chadwick** [comment]
running that outside of Make looks to work but I suspect produces the wrong kind of slashes

$ node -e 'process.stdout.write(require("closure-util").getLibraryPath())'
C:\cygwin\home\User\ol3\node_modules\closure-util\.deps\library\b0b32b6477e735055b8f53284d5cf6a4af1b29da

**Comment by bill-chadwick** [comment]
changing getLibraryPath in util.js (as below) seems to fix things

/**
 * Get the file system path to the Closure Library.
 * @return {string} Path.
 */
exports.getLibraryPath = function() {
  return getDependency('library', config.get('library_url')).replace(/\\/g,"/");
};

**Comment by bill-chadwick** [comment]
I expect getCompilerPath needs the same treatment. I trust those two changes would be safe for Linux building.

**Comment by bill-chadwick** [comment]
make apidoc is working on windows.

**Comment by bill-chadwick** [comment]
make serve is good for Chrome and Internet Explorer but not Firefox (issues with build serve and Firefox have been reported in the past)

**Comment by bill-chadwick** [comment]
To avoid changing closure-utils getLibraryPath, for building under Cygwin, we can modify the makefile as below 

*ifeq (CYGWIN,$(findstring CYGWIN,$(OS)))
  CLOSURE_LIB = $(shell cygpath -u $(shell node -e 'process.stdout.write(require("closure-util").getLibraryPath())'))
else
  CLOSURE_LIB = $(shell node -e 'process.stdout.write(require("closure-util").getLibraryPath())')
endif*

This converts the windows path (with backslashes) from getLibraryPath to a Cygwin path, only when running make under Cygwin.

**Comment by elemoine** [comment]
We talked about building ol3 on Windows today at the dev meeting. We think that we should first focus on making the most important targets work. For example a PR that makes `make build` and `make check` work would be fantastic! As an ol3 developer you need to be able to run `make check` locally, for the rest you can rely on Travis.

**Comment by bill-chadwick** [comment]
Eric,

I would have thought folk really need to be able to run the examples
locally before committing so adding either or both of 'make serve' or 'make
host-examples' to your list seems sensible to me. Do you agree ?

For just 'make build' and 'make check' to work on Cygwin, only the patches
to tasks\generate-info.js are needed + of course some words in contributing
about using Cygwin on Windows.

I have a stalled PR on my fork's master (about geodesic flat geom). I plan
to delete that PR (for now) and then bring my master up to date.

I still hope to contribute an updated graticule sometime soon.

Bill

**Comment by elemoine** [comment]
> I would have thought folk really need to be able to run the examples locally before committing so adding either or both of 'make serve' or 'make host-examples' to your list seems sensible to me. Do you agree ?

`make serve` (or just `npm start`) definitely needs to work as well, as you can basically not work on examples without it.

**Comment by bill-chadwick** [comment]
Is there some reason why the makefile has

*CLOSURE_LIB = $(shell node -e 'process.stdout.write(require("closure-util").getLibraryPath())')*

rather than

*CLOSURE_LIB := $(shell node -e 'process.stdout.write(require("closure-util").getLibraryPath())')*

?
I would have thought the path only needed evaluating once.

**Comment by elemoine** [comment]
The `closure-util` package is not installed when you execute `make` the first time.

**Comment by bill-chadwick** [comment]
I have put up a branch at https://github.com/bill-chadwick/ol3/tree/windows that attempts to fix things and provide brief instructions, for building on Windows with Cygwin. If someone else could try out a Windows build from there, that would be great. 

I have not got to the bottom of why *make serve* fails first time around (with a permissions problem) but works subsequently. The test-rendering of *make ci* do not work.

**Comment by kalbermattenm** [comment]
@bill-chadwick, thanks a lot for creating a branch for that !

I just gave it a try and I have pretty much the same results as you get:

```
$ make ci

node tasks/test.js

  ol.collection
    create an empty collection
...
  1614 passing (9s)

node tasks/test-rendering.js
Gecko: 35.0.1

Script Error: [JavaScript Error: "ReferenceError: goog is not defined" {file: "http://127.0.0.1:3001/test_rendering/index.html" line: 45}]
       Stack:
         -> http://127.0.0.1:3001/test_rendering/index.html: 45
```
For `make serve`, the first time you run it:
```
$ make serve
node tasks/serve.js
info serve Building examples.
ERR! serve Building examples failed.
ERR! serve Failed to write the file at: C:\git_projects\ol3\build\examples\accessible.css
ERR! serve
ERR! serve EPERM, mkdir 'C:\git_projects\ol3\build\examples'
ERR! serve Use "verbose" logging to see the full stack trace.
Makefile:134 : la recette pour la cible « serve » a échouée
make: *** [serve] Erreur 1
```
It seems to work the second time you run it...

I still have issues running the examples. The server run, but if you go to any example in a browser, then there are quite a lot of errors... I do not really get where or what to search for to resolve this error:

![presse-papiers-1](https://cloud.githubusercontent.com/assets/1681332/7560547/882e2676-f7c4-11e4-9bd4-e5117564f756.png)

**Comment by bill-chadwick** [comment]
Did you try Chrome or IE for the examples ?

**Comment by bartvde** [comment]
that last issue is Firefox only

**Comment by kalbermattenm** [comment]
OK... Works great on Chrome (and IE...) ! 

Sorry, I did not know that there was an issue with Firefox on Windows...

**Comment by bill-chadwick** [comment]
You are seeing the same first time fault with make serve as I do.

**Comment by bill-chadwick** [comment]
It may be the C: in the script paths that Firefox objects to.

**Comment by bill-chadwick** [comment]
I would have thought it would be good for the make targets to work from a downloaded repo zip.
Currently, on Windows I get

fatal: Not a git repository (or any parent up to mount point /cygdrive/c)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

at the start of most (?all) of the targets (*build*, *test*, *check* and *serve* at least) even though many of them go on work.

Also, on Windows, paths have to be kept short to avoid ENAMETOOLONG errors.

BTW the issue with the first time fail of *make serve* has gone away now that Cygwin's use of ACLs is disabled.

**Comment by elemoine** [comment]
Thanks @bill-chadwick and @kalbermattenm! @bill-chadwick, could you please create a PR with your branch? I think it looks good.

**Comment by bill-chadwick** [comment]
PR created.

**Comment by probins** [comment]
can this one be closed?

**Comment by ahocevar** [comment]
Outdated, closing.
