### ISSUE TITLE
Can we add ol.source.VfrMap?

### ISSUE THREAD

**Issue by xianyunjushi** [openlayers/ol3#3650]
Currently, ol.source.XYZ has 3 subclasses:
    ol.source.MapQuest
    ol.source.OSM
    ol.source.Stamen

Can we add one more, in order to easily add vfrmap.com tiles?
ol.source.VfrMap

The url to vfrmap.com tiles is:
http://vfrmap.com/20140918/tiles/vfrc/{z}/{y}/{x}.jpg

So, it's a special case of ol.source.XYZ, isn't it? So far I don't know how to add vfrmap.com tiles into OpenLayers 3.

Thanks!

**Comment by bartvde** [comment]
Please don't ask questions through github issues.
