### ISSUE TITLE
Show KML layer with draw features and a export-to-png button

### ISSUE THREAD

**Issue by ogirdorsevla** [openlayers/ol3#3652]
Hello there!
I have a script, that can show kml layers and draw features... but the export-to-png button isn't working.

here's a link to the website where the script is running
http://www.jourdan.org.br/geojourdan-teste/

and here's the script.
Can anyone help me with this? I'm almost a week trying to solve this. Thanks!

<!DOCTYPE html>

<html>
    <head><title>OpenLayers KML Example</title>
        <style>
            #map {
                height: 400px;
                width: 1000px;
            }
            .ol-attribution a {
                color: black;
            }            
        </style>
        <script src="http://www.openlayers.org/api/OpenLayers.js"></script>
        <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.4.0/ol.css" type="text/css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.4.0/ol.js"></script>
    </head>
    <body>
        <br>      
        <div id="mydiv">
            <div class="container-fluid">

                <div class="row-fluid">
                    <div class="span12">
                        <div id="map" class="map"></div>
                        <div id="no-download" class="alert alert-error" style="display: none">
                            This example requires a browser that supports the
                            <a href="http://caniuse.com/#feat=download">link download</a> attribute.
                        </div>
                        <a id="export-png" class="btn" download="map.png"><i class="icon-download"></i> Export PNG</a>
                    </div>
                </div>

            </div>
            <form name="camadas">
                <input type="checkbox" class="camadas" name="vilanova" id="vilanova" onChange="bairros(this, 'vilanova')"/> Vila Nova            
            </form>            
            <div style="font-weight: bold">Camada de Edição</div>
            <select id="mapMode" name="mapMode" size="1" onchange="changeMapMode(this.value);">
                <option value="none" selected>Navegar pelo Mapa</option>
                <option value="polygon">Criar Polígonos</option>
                <option value="point">Criar Pontos</option>
                <option value="modify">Modificar Pontos/Poligonos ja criados</option>
                
                
                
                <option value="select">Selecionar Objetos</option>
            </select>
            <input type="button" value="download" id="export-png" onClick="convertasbinaryimage()"/>     
        </div>    
        <script>

            map = new OpenLayers.Map("map"); 
            map.addLayer(new OpenLayers.Layer.OSM());
            

            var lonLat = new OpenLayers.LonLat(-5462834.47, -3058929.70)
                    .transform(
//                            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
                            map.getProjectionObject() // to Spherical Mercator Projection
                            );
            var zoom = 2;
            map.setCenter(lonLat, zoom);

            drawingLayer = new OpenLayers.Layer.Vector("Drawing layer");
            drawingLayer.events.on({
                'featureselected': function (feature) {
                    updateFeatureTable(this.selectedFeatures);
                },
                'featureunselected': function (feature) {
                    updateFeatureTable(this.selectedFeatures);
                }
            });
            map.addLayer(drawingLayer);

            drawingControls = {
                polygon: new OpenLayers.Control.DrawFeature(drawingLayer, OpenLayers.Handler.Polygon, {
                    eventListeners: {
                        "featureadded": controlFeatureHandler
                    }
                }),
                point: new OpenLayers.Control.DrawFeature(drawingLayer, OpenLayers.Handler.Point),
                modify: new OpenLayers.Control.ModifyFeature(drawingLayer, OpenLayers.Handler.dragComplete),
                select: new OpenLayers.Control.SelectFeature(
                        drawingLayer,
                        {
                            clickout: false, toggle: false,
                            multiple: false, hover: false,
                            toggleKey: "ctrlKey", // ctrl key removes from selection
                            multipleKey: "shiftKey", // shift key adds to selection
                            box: true
                        }
                )
            };

            for (var key in drawingControls) {
                map.addControl(drawingControls[key]);
            }

            var highlightCtrl = new OpenLayers.Control.SelectFeature(drawingLayer, {
                hover: true,
                highlightOnly: true,
                renderIntent: "temporary",
                eventListeners: {
                    //beforefeaturehighlighted: report,
                    featurehighlighted: report,
                    featureunhighlighted: unReport
                }
            });
            map.addControl(highlightCtrl);
            highlightCtrl.activate();

            function report(e) {
                //OpenLayers.Console.log(e.type, e.feature.id);
                document.getElementById('highlighted').innerHTML = e.feature.id;
            }
            ;
            function unReport(e) {
                //OpenLayers.Console.log(e.type, e.feature.id);
                document.getElementById('highlighted').innerHTML = "";
            }
            ;

            function changeMapMode(value) {
                for (var key in drawingControls) {
                    var control = drawingControls[key];
                    if (value == key) {
                        control.activate();
                    } else {
                        control.deactivate();
                    }
                }
            }

            function controlFeatureHandler(event) {
            }

            function updateFeatureTable(featureList) {
                var wkt = new OpenLayers.Format.WKT();
                var table = "<table border='1'>";
                for (var key in featureList) {
                    table += "<tr><td>";
                    table += featureList[key].id;
                    table += "</td><td>";
                    table += wkt.write(featureList[key]);
                    table += "</td></tr>";
                }
                table += "</table>";
                document.getElementById('featureTable').innerHTML = table;
            }

            //Declaração de Camadas KML
            var vilanova = new OpenLayers.Layer.Vector("KML", {
                strategies: [new OpenLayers.Strategy.Fixed()],
                protocol: new OpenLayers.Protocol.HTTP({
                    url: "../wp-content/uploads/2015/01/VILA-NOVA.kml",
                    format: new OpenLayers.Format.KML({
                        extractStyles: true,
                        extractAttributes: true,
                        maxDepth: 2,
                        setVisibility: true
                    })
                })
            });

//Centro do mapa e zoom

            var lonLat = new OpenLayers.LonLat(-5462834.47, -3058929.70)
                    .transform(
//                            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
                            map.getProjectionObject() // to Spherical Mercator Projection
                            );
            var zoom = 2;
            map.setCenter(lonLat, zoom);
            //Add a selector control to the kmllayer with popup functions
            var controls = {
                selector: new OpenLayers.Control.SelectFeature(kmllayer, {onSelect: createPopup, onUnselect: destroyPopup})
            };
            function createPopup(feature) {
                feature.popup = new OpenLayers.Popup.FramedCloud("pop",
                        feature.geometry.getBounds().getCenterLonLat(),
                        null,
                        '<div class="markerContent">' + feature.attributes.description + '</div>',
                        null,
                        true,
                        function () {
                            controls['selector'].unselectAll();
                        }
                );
                //feature.popup.closeOnMove = true;
                map.addPopup(feature.popup);
            }

            function destroyPopup(feature) {
                feature.popup.destroy();
                feature.popup = null;
            }

            map.addControl(controls['selector']);
            controls['selector'].activate();

            function bairros(i, layername) {
                if (i.checked === true) {
                    map.addLayer(eval(layername));
                }
                else {
                    map.removeLayer(eval(layername));
                }
            }

            //Add the vector layer
            var polygonLayer = new OpenLayers.Layer.Vector("My Polygon");
            //Add the layer to map
            map.addLayer(polygonLayer);

            //Drawing controls
            drawControls = {
                polygon: new OpenLayers.Control.DrawFeature(polygonLayer, OpenLayers.Handler.Polygon)
            };
            //Add the drawing control to polygon
            map.addControl(drawControls.polygon);

            //Activate the drawing control
            drawControls.polygon.activate();

            //You can add the select control to the polygons
            //This is not a necessary step
            var options = {
                hover: false
            };
            var select = new OpenLayers.Control.SelectFeature(polygonLayer, options);
            select.onSelect = function (e) {
                var mapProjv = map.getProjectionObject();
                var epsg4326v = new OpenLayers.Projection("EPSG:4326");
                var verticesNative = e.geometry.getVertices();
                var verticesLatLon = [];
                var verticesStr = "";
                for (var x in verticesNative) {
                    verticesLatLon.push(verticesNative[x].clone().transform(mapProjv, epsg4326v));
                    verticesStr += verticesLatLon[x].toShortString() + ";";
                }
                document.getElementById("verticesStr").innerHTML = "Area Vertices: " + verticesStr;
            }
            //Add the select control to the map
            map.addControl(select);
            //Activate the select control
            select.activate();

            var exportPNGElement = document.getElementById('export-png');

            if ('download' in exportPNGElement) {
                exportPNGElement.addEventListener('click', function (e) {
                    map.once('postcompose', function (event) {
                        var canvas = event.context.canvas;
                        exportPNGElement.href = canvas.toDataURL('image/png');
                    });
                    map.renderSync();
                }, false);
            } else {
                var info = document.getElementById('no-download');
                /**
                 * display error message
                 */
                info.style.display = '';
            }

        </script>
    </body>
</html>

**Comment by tsauerwein** [comment]
It seems like you are mixing up OpenLayers 2 and OpenLayers 3. They are not compatible.

Also in the future, please ask questions on StackOverflow with the tag [openlayers](http://stackoverflow.com/questions/tagged/openlayers) (for OpenLayers 2) or [openlayers-3](http://stackoverflow.com/questions/tagged/openlayers-3) (for OpenLayers 3.)
