### ISSUE TITLE
TextStyle hit detection getting cut off

### ISSUE THREAD

**Issue by greggian** [openlayers/ol3#3657]
My application supports adding labels/annotations on the map. To support this, I use a point feature with a text style applied.

When adding a text style with a long text attribute, hit detection does not work for the entire length of text. Beyond a certain length (~100px?) from the center point, hit detection fails for the remainder of the text. I would expect hit detection to work for the entire label.

I created this jsfiddle to demonstrate the issue: http://jsfiddle.net/629to5rd/33/
In the example, I use the text "A long long long long long label to test very long label selection". In my testing, hovering on the middle of the text ("long long label to test very long") I get a hover cursor as expected. If i hover over the beginning ("A long long long") or the end ("label selection") of the text label then I get no hover cursor, which I believe is a bug. I have also added a selection interaction and its hit detection seems to behave the same.

Thanks!

**Comment by tsauerwein** [comment]
[ol.layer.Vector](http://openlayers.org/en/master/apidoc/ol.layer.Vector.html) takes a `renderBuffer` option which by default is 100px. If you have very long labels or very large icons, you can increase this value to make the rendering and hit detection work properly.

See http://jsfiddle.net/629to5rd/35/

**Comment by greggian** [comment]
@tsauerwein Thanks for the clarification. This also explains why hit detection worked when the item was selected (FeatureOverlays have no renderBuffer).

From the description of RenderBuffer ("The buffer around the viewport extent used by the renderer when getting features from the vector source"), I didn't expect that it would effect hit detection of items within the viewport.

**Comment by tsauerwein** [comment]
@greggian Would the following description be clearer?

> The buffer around the viewport extent used by the renderer when getting features from the vector source for the rendering or hit-detection. Recommended value: the size of the largest symbol, line width or label. Default is 100 pixels.

**Comment by greggian** [comment]
@tsauerwein Yeah, I think calling out hit detection is helpful. I was also curious about 'buffer around the viewport extent'. Maybe my terminology is off, but that made me think that the buffer area is larger than the viewport. Thanks!
