### ISSUE TITLE
First feature of source is lost

### ISSUE THREAD

**Issue by Polzme** [openlayers/ol3#3670]
Hello,

If you draw some feature on this page: http://dev.through-my-eyes.be/openlayers_examples/openlayers_geofield_map_geofield

You'll quickly notice that the features are converted in the format you want in the textarea under it.
Except that the first feature is not there, it works when you draw two features.

This example was working perfectly with 3.4.0, is this a bug or I'm doing something wrong ?

The JS file handling this is here: http://cgit.drupalcode.org/openlayers/tree/modules/openlayers_geofield/src/Openlayers/Component/Geofield/js/geofield.js?h=7.x-3.x

Thanks!

**Comment by Polzme** [comment]
I just noticed:

> Change to ol.interaction.Draw
> When finishing a draw, the drawend event is now dispatched before the feature is inserted to either the source or the collection. This change allows application code to finish setting up the feature

Any clue on how to change my code according to your changes ?

**Comment by Polzme** [comment]
Another example on Codepen, not working anymore: http://codepen.io/barbalex/pen/fBpyb

**Comment by elemoine** [comment]
Couldn't you call `saveData` from an `addfeature` listener on the source instead of the `drawend` listener on the draw interaction?

```js
vector_layer.getSource().on('addfeature', saveData);
```

**Comment by Polzme** [comment]
Thanks, fixed !

http://cgit.drupalcode.org/openlayers/commit/?h=7.x-3.x&id=8a03effb83611b05ff1fc145c23f36b26f36cf64

**Comment by Polzme** [comment]
By the way, when do you start Drupal ?

**Comment by elemoine** [comment]
Start Drupal?

**Comment by ahocevar** [comment]
https://groups.drupal.org/node/440733

**Comment by Polzme** [comment]
@ahocevar I wrote that page ! :)

@elemoine I you want to start contributing to the Openlayers module for Drupal... that would be great!

**Comment by elemoine** [comment]
I am not a Drupal user...

**Comment by Polzme** [comment]
Soon :)

 -*φol d.*-
