### ISSUE TITLE
Missing ol.geom.GeometryType from 3.5.0 build

### ISSUE THREAD

**Issue by umphy** [openlayers/ol3#3671]
Hi,

I have limited understanding in how Ol3 is built, so I apologise if it's just my misunderstanding.

I am trying v3.5 from cdnjs. I tried to reference the constant `ol.geom.GeometryType.POLYGON`, but `ol.geom.GeometryType` is undefined. In the source code ([src/ol/geom/geometry.js] (https://github.com/openlayers/ol3/blob/v3.5.0/src/ol/geom/geometry.js)), it's marked as `@api stable` with a `goog.provide('ol.geom.GeometryType')`.

Am I missing something or is it a build bug?

Thanks for you efforts by the way for this great library.

**Comment by bartvde** [comment]
You cannot use the enums but you should be using the string values instead so "Polygon".
Also please ask this type of question on stackoverflow the next time using the openlayers-3 tag, github issues are for when you've verified things are really an issue in the library.

**Comment by umphy** [comment]
OK thanks for that. I was confused since I was using it fine in 3.4.0, but it stopped working in 3.5.0. Just saying.

I thought it was a good idea to expose the enums so that even if you change the value internally it wouldn't affect the users.

**Comment by bartvde** [comment]
I don't think enums ever worked, were you using the debug build?

**Comment by umphy** [comment]
Yes you're absolutely right. I just tried the unminified debug build and it
works. But I think there is a problem with the minified debug build, which
was the one I was using for 3.4.0. I just tested using a blank html file
loading the debug.min build, and I got the following error from Firefox:

SyntaxError: expected expression, got '<' ol-debug.min.js:1:0

**Comment by bartvde** [comment]
If you're using the CDN you should either use:

(1) minified, production use
https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol.js

(2) debug
https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol-debug.js

**Comment by marcjansen** [comment]
That syntax error sounds like a 404?

**Comment by bartvde** [comment]
See: https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol-debug.min.js

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>
```

**Comment by giohappy** [comment]
Why shouldn't the enums be used? They're a foundation for managing APIs constants. What happens if "LineString" will ever be changed to "Linestring".
Anyway, if they're not meant to be used they should be removed from the [API docs](http://openlayers.org/en/v3.14.2/apidoc/ol.geom.html#.GeometryType)
