### ISSUE TITLE
Name, tags and description of verbatim examples don't show up on example-index

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#3674]
![undefined-examples](https://cloud.githubusercontent.com/assets/227934/7535182/ab9df0bc-f582-11e4-9aad-b4affc215d07.png)

I noticed this for the following examples:

* `geolocation-orientation.html`
* `mobile-full-screen.html`

There may be more and I am not 100% sure that the reason is the `example-verbatim`-template, but it seems likely.

**Comment by tschaub** [comment]
These examples are missing `title`, `shortdesc`, and `tags` metadata.  See #3677 for a fix.
