### ISSUE TITLE
kml icon size is huge

### ISSUE THREAD

**Issue by tamarmot** [openlayers/ol3#3680]
When reading a standard kml file with pushpins and labels, both are huge; the pushpin is always getting rendered at full scale and does not change size with map zoom.

**Comment by tschaub** [comment]
@tamarmot can you provide a link to the KML or a JSFiddle that demonstrates the problem?

**Comment by tamarmot** [comment]
A sample kml file is here:
https://www.dropbox.com/s/s65zrvegi2n6vte/2014_PLRP_Pin_Drops.kml?dl=0

**Comment by tamarmot** [comment]
I created a fiddle that has my same javascript code but for some reason the kml is not yet rendering at all ...https://jsfiddle.net/tamarmot/5kcpz76f/

**Comment by tamarmot** [comment]
ah I see I had 2 problems, one is that ol 3.5 changed the spec for how to load kml (done) and my next problem is a CORS problem for jsfiddle.  Working on that.

**Comment by tamarmot** [comment]
I've been doing some more testing in this area and I notice the following:
In ol.format.KML.prototype.readPlacemark_, the properties are read and applied to the feature, so I can do feature.get('name') and it gives the name that was in the placemark; this name is not rendered.  I would think that it should have been rendered in text on the style.

**Comment by JrFolk** [comment]
I'm having the same issue.  The same kml renders fine for OpenLayers2, and Google Earth, but in ol3 the icons take up have of the viewport.

**Comment by tamarmot** [comment]
Nothing so far.  I'm working on this now, and found where I can scale the icon size.  I will fork the code, make that fix (and others to include labels) and submit a pull request.

**Comment by ahocevar** [comment]
Fixed with #4302.
