### ISSUE TITLE
Adding tile layer after vector layer obscures vectors

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#3681]
Because addLayer does a simple push to the array/collection, the tiles from a tile layer will be laid on top of the vectors, making it look like they have disappeared. The only way around this that I can think of is not to use addLayer, but when adding tile layers always use insertAt before the first vector layer. Not sure how often this occurs, and whether it's worth having a convenience method for doing this. Would putting tile and vector layers in separate groups ensure that tiles are always 'underneath' vector layers regardless of which order they are added?

**Comment by tschaub** [comment]
In my opinion, all layers should be treated equally.  If you had opened an issue saying "adding a layer to my map covers existing layers" we would have closed it as an invalid issue.

**Comment by probins** [comment]
some tile layers, like WMS, can be transparent. But if you want to display, say, OSM and vectors, you have to have vectors on top of OSM, not the other way round. So, effectively, layers aren't equal, though I get your point that the library maybe shouldn't have an opinion on the 'correct' sequence. Perhaps all that's needed is some documentation or an example showing the best way to force a particular sequence.

**Comment by marcjansen** [comment]
Layers are equal. OSM could e.g. be transparently laid on top of vectors. I agree with Tim here.

I'll close this now. Please reopen if you disagree.

**Comment by probins** [comment]
the issue doesn't have to be reopened, but I'm still looking for a solution. Pushing a new layer into the middle of the layers array doesn't seem to work, so presumably layers are rendered in the order they are added, not the order in the layers array. If so, then the only way I can think of to resolve this is to remove the vector layers, add the new tile layer, and then add the vector layers back to the top.

**Comment by bartvde** [comment]
@probins are you using the array or the collection?

**Comment by probins** [comment]
quite right. I was using the array. insertAt on the collection does work. End of subject, though this should probably be documented somewhere (not sure where)

**Comment by bartvde** [comment]
@probins currently getArray has a warning in the API docs are you saying this is not clear from the sentence? "Get a reference to the underlying Array object. Warning: if the array is mutated, no events will be dispatched by the collection, and the collection's "length" property won't be in sync with the actual length of the array."

**Comment by probins** [comment]
no, I was meaning what I was trying to do, namely adding a layer, but not at the top of the stack. map.addLayer does say 'to the top', so perhaps add a note that you can use the Collection methods to add a layer elsewhere in the stack

**Comment by bartvde** [comment]
Good suggestion.

**Comment by bartvde** [comment]
@probins I've implemented your suggestion in #3682

**Comment by probins** [comment]
Yes, thanks. I was going to do this myself, but you beat me to it :-)

I've been looking at layer groups too, and the docs there could be improved as well. It isn't clear from the Map docs what the layerGroup in get/setLayerGroup is and what the relationship between getLayers and getLayerGroup is. I'm currently experimenting with groups with the same aim, to have all layers in one group rendered before or after another, and can create a PR if you like once I've worked out how it all fits together.

**Comment by bartvde** [comment]
sure PR for doc improvements are always welcome! TIA

**Comment by marcjansen** [comment]
+1 for better docs!

**Comment by probins** [comment]
for anyone looking at this issue in the future, layerGroups provide an easy way of doing what I was wanting. I've put all my tile layers in one group and all the vectors in a 2nd group; then any tile layer added later will automatically be rendered underneath the vectors.
