### ISSUE TITLE
ol.format.WKT doesn't recognize scientific number notation

### ISSUE THREAD

**Issue by damir-sirola** [openlayers/ol3#3686]
I'm having a problem where default C# / SQL Server implementation of geography to WKT methods return small numbers in scientific number format with character E in them. I get the following error
Uncaught Error: Unexpected `E` at position 123 in `MULTIPOLYGON(((-5.7156469384940491 50.082709053271955, -5.7059626929961649 ... **9.1993293867552632E-05** 53.535345770529375, ...))).
The most popular 3rd party library for spatial data in C# creates WKT in same format.

**Comment by marcjansen** [comment]
Hey @damir-sirola, I hope #3699 fixes that issue for you.
