### ISSUE TITLE
ol.webgl.getContext: attributes renamed by the compiler

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#3687]
The attributes passed to `getContext` are renamed by the compiler: the type is [Object](https://github.com/openlayers/ol3/blob/master/src/ol/webgl/webgl.js#L29) and the keys [are](https://github.com/openlayers/ol3/blob/master/src/ol/has.js#L127-L129) [not](https://github.com/openlayers/ol3/blob/master/src/ol/renderer/webgl/webglmaprenderer.js#L98-L104) quoted

**Comment by fredj** [comment]
correction: only `failIfMajorPerformanceCaveat` is renamed by the compiler: this key is not present in the webgl externs (added with https://github.com/google/closure-compiler/commit/4a5d5a6d594ae46772405dd709c0993b7eb0cfc9)

**Comment by elemoine** [comment]
So, should we add it to our [closure-compiler.js](https://github.com/openlayers/ol3/blob/master/externs/closure-compiler.js) externs file for now?

**Comment by fredj** [comment]
Yes, and remove it when we upgrade the closure-compiler.
