### ISSUE TITLE
Custom polygon symbolizer

### ISSUE THREAD

**Issue by doronhorwitz** [openlayers/ol3#3698]
I asked this question on stackoverflow: ["Openlayers 3 custom polygon symbolizer"](http://stackoverflow.com/questions/30165011/openlayers-3-custom-polygon-symbolizer).

Would it be possible and relevant to implement an ol.style.Polygon symbolizer that would allow symbolizers to be arbitrary polygons (beyond the circles and and regular shapes already provided)?

**Comment by elemoine** [comment]
+1

We could introduce an `ol.style.Shape` base class that app developers would directly instantiate for creating custom symbols.

**Comment by jgalrito-i9** [comment]
+1

**Comment by vaceslav** [comment]
+1 
What way should I use NOW to draw rectangle (not a square) symbols for a feature?

**Comment by tsauerwein** [comment]
You could use a style function which returns a style with the geometry attribute set to a rectangle geometry:
```
style: function (feature, resolution) {
  // calculate the rectangle using the feature geometry
  // and the current resolution
  var rectangleGeom = ...;
  return new ol.style.Style({
    geometry: rectangleGeom,
    ...
  });
}
```

See also:
http://openlayers.org/en/master/apidoc/ol.style.Style.html
http://openlayers.org/en/master/examples/polygon-styles.html

**Comment by ahocevar** [comment]
You can also use the technique shown in http://openlayers.org/en/latest/examples/earthquake-custom-symbol.html.
