### ISSUE TITLE
How about a multiLineString.appendLineStrings([linestrings]) method?

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#3700]
How about a multiLineString.appendLineStrings([linestrings]) method?

This could perhaps turn into a PR.

**Comment by jonataswalker** [comment]
I was [informed](http://stackoverflow.com/a/30306656/4640499) that there's a [ol.geom.MultiLineString#setLineStrings](https://github.com/openlayers/ol3/commit/0bf34a52ff05cf545c2e32888798d9139c580708).

This is not in the docs. Is there a reason? Is it exported?

**Comment by bartvde** [comment]
It's not part of the API currently.

**Comment by jonataswalker** [comment]
So how about a multiLineString.appendLineStrings([linestrings]) method?

It could also accept an empty array and solve [this question](http://stackoverflow.com/a/30306656/4640499)

**Comment by jonataswalker** [comment]
Never mind, multiLineString.setCoordinates([]) do the job.
