### ISSUE TITLE
Draw / Edit polygon over 180° or -180°

### ISSUE THREAD

**Issue by jcarbou** [openlayers/ol3#3704]
Drawing polygon over 180° or -180° (Example http://openlayers.org/en/v3.5.0/examples/draw-and-modify-features.html?q=draw&mode=raw), the polygon disapear when the mouse move outside [-180°,180°].
This is not exactly a disappearance because the polygon is translated (+360 ° or -360 °). The result is the same for high zoom levels where we can not observe these translations.

**Comment by jcarbou** [comment]
I identify the piece of code that generates this behavior (If I comment the code, see below, the behavior is correct, like previously in version ol3.4.0). However this code is usefull for other use case... I think...

```javascript
/**
 * @param {ol.render.EventType} type Event type.
 * @param {olx.FrameState} frameState Frame state.
 * @private
 */
ol.renderer.canvas.Map.prototype.dispatchComposeEvent_ =
    function(type, frameState) {
  var map = this.getMap();
  var context = this.context_;
  if (map.hasListener(type)) {
    var extent = frameState.extent;
    var pixelRatio = frameState.pixelRatio;
    var viewState = frameState.viewState;
    var projection = viewState.projection;
    var resolution = viewState.resolution;
    var rotation = viewState.rotation;

    var offsetX = 0;
    /*if (projection.canWrapX()) {
      var projectionExtent = projection.getExtent();
      var worldWidth = ol.extent.getWidth(projectionExtent);
      var x = frameState.focus[0];
      if (x < projectionExtent[0] || x > projectionExtent[2]) {
        var worldsAway = Math.ceil((projectionExtent[0] - x) / worldWidth);
        offsetX = worldWidth * worldsAway;
        extent = [
          extent[0] + offsetX, extent[1],
          extent[2] + offsetX, extent[3]
        ];
      }
    }*/

var transform = this.getTransform(frameState, offsetX);

    var tolerance = ol.renderer.vector.getTolerance(resolution, pixelRatio);
    var replayGroup = new ol.render.canvas.ReplayGroup(
        tolerance, extent, resolution);
```
The extent of the replayGroup is used to compute bufferedMaxExtent_ of ol.render.canvas.Replay. This bufferedMaxExtent_ is used to contrain coordinate of geometry (ol.render.canvas.Replay.prototype.appendFlatCoordinates ).

A solution should be :
- Add 2 extents attributes in replayGroup   (wrapExtent -new extent of ol3.5.0- and frameStateExtent - old extent of ol3.4.0-) setted by the constructor
- The maxExtent attribute of replayGroup   is set by defaut with wrapExtent  (ol3.5.0 behavior)
- Use the old extent for FeatureOvelay rendering (FeatureOverlay is used by drawinteraction to draw geometry). To do that, set the replayGroup "maxExtent" attribute before calling rendering in FeatureOverlay  (and unset after)
 
```javascript
ol.FeatureOverlay.prototype.handleMapPostCompose_ = function(event) {
  if (goog.isNull(this.features_)) {
    return;
  }
  var styleFunction = this.styleFunction_;
  if (!goog.isDef(styleFunction)) {
    styleFunction = ol.style.defaultStyleFunction;
  }
  var replayGroup = /** @type {ol.render.IReplayGroup} */
      (event.replayGroup);
  goog.asserts.assert(goog.isDef(replayGroup),
      'replayGroup should be defined');
  var frameState = event.frameState;
  var pixelRatio = frameState.pixelRatio;
  var resolution = frameState.viewState.resolution;
  var squaredTolerance = ol.renderer.vector.getSquaredTolerance(resolution,
      pixelRatio);
  var i, ii, styles, featureStyleFunction;
  this.features_.forEach(function(feature) {
    featureStyleFunction = feature.getStyleFunction();
    styles = goog.isDef(featureStyleFunction) ?
        featureStyleFunction.call(feature, resolution) :
        styleFunction(feature, resolution);

    if (!goog.isDefAndNotNull(styles)) {
      return;
    }

 // Set frameState extent
replayGroup.maxExtent=replayGroup.frameStateExtent;

    ii = styles.length;
    for (i = 0; i < ii; ++i) {
      ol.renderer.vector.renderFeature(replayGroup, feature, styles[i],
          squaredTolerance, this.handleImageChange_, this);
    }

// UnSet frameState extent
replayGroup.maxExtent=replayGroup.wrapExtent;
  }, this);
};
```

**Comment by ahocevar** [comment]
For editing features across the date line, you simply need to set `wrapX` to `false` on your vector layer.

**Comment by jcarbou** [comment]
Hi ahocevar,

I don't understand your comment. The draw interaction use FeatureOverlay, not VectorLayer (see http://openlayers.org/en/v3.5.0/examples/draw-and-modify-features.html). And I can't set wrapX option to false on FeatureOverlay.

**Comment by ahocevar** [comment]
Then maybe is misunderstood your code snippet @jcarbou. Can you create a pull request?

**Comment by jcarbou** [comment]
Yes I can but I think is a issue because I can draw a polygon over 180° with  version 3.4.0. You can reproduce this issue using http://openlayers.org/en/v3.5.0/examples/draw-and-modify-features.html. I'am a beginner on ol3 but I don't understand the utility of the modification of `extent` in `ol.renderer.canvas.Map.prototype.dispatchComposeEvent_` before `ReplayGroup' instanciation. This extent is only used by FeatureOvelay and FeatureOverlay need FrameStateExtent. No ?

**Comment by jcarbou** [comment]
I prepare a pull request (I will add  a wrapX option to FeatureOvelay). You can choose between accepting this request or comment the code that modifies the extent in ol.renderer.canvas.Map.prototype.dispatchComposeEvent_ .

Thank you for your answers and for the quality of OL3 !
