### ISSUE TITLE
Can't delete end vertex of linestring

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#3708]
There are several outstanding issues for interaction.Modify, but afaics this one hasn't been raised. Looks like ol.interaction.Modify.prototype.removeVertex_ isn't allowing for this possibility, as one of left/right will be undefined in this case. So you can only delete a vertex within the linestring, not one of the end vertices.

**Comment by sweco-sebhar** [comment]
This will probably bite me some day. A good start would be to introduce tests for interaction.Modify. I have done some initial cases done in #3635 but it has not been cleared to merge yet.

**Comment by rmichaelis** [comment]
Furthermore, in the private function `ol.interaction.Modify.prototype.removeVertex_`, the function contract is not respected [because the return value is always true](https://github.com/openlayers/ol3/blob/master/src/ol/interaction/modifyinteraction.js#L974).

**Comment by marcjansen** [comment]
Can you come up with a PR?
