### ISSUE TITLE
stopping animations

### ISSUE THREAD

**Issue by MajedDH** [openlayers/ol3#3714]
Is there a way to stop `ol.animation` static methods in the middle of an animation?

if there isn't, can i implement stopping an animation in  `ol.PreRenderFunction` ?

**Comment by jonataswalker** [comment]
The recomendation is to make usage questions [here](http://stackoverflow.com/questions/tagged/openlayers-3).

**Comment by fredj** [comment]
`ol.animation` are now deprecated (see #6079); `view.animate` must be used instead.
All animations are cancelled when the user interacts with the map or when anything calls `view.setCenter()`, `view.setResolution()`, or `view.setRotation()`.

**Comment by jose-gomez-ml** [comment]
view.cancelAnimations();
