### ISSUE TITLE
Firefox, OL 3.5.0: "TypeError: invalid Array.prototype.sort argument" when using renderOrder

### ISSUE THREAD

**Issue by CaitW** [openlayers/ol3#3715]
Call stack:

![screen shot 2015-05-20 at 11 30 13 am](https://cloud.githubusercontent.com/assets/8647176/7732249/a3330bdc-fee3-11e4-9a1e-eba165d8c7ad.png)

When using renderOrder like:

```
new ol.layer.Vector({
	source: new ol.source.Vector(),
	visible: true,
	renderOrder: 2
})
```

**Comment by tsauerwein** [comment]
`renderOrder` accepts a function to compare two features when sorting the features before the rendering (see in the [API docs](http://openlayers.org/en/master/apidoc/ol.layer.Vector.html)). So giving a number will not work.

I have to admit that the error message is not quite expressive though.

**Comment by tsauerwein** [comment]
See #3718
