### ISSUE TITLE
GeoJSON format do not emit empty properties property

### ISSUE THREAD

**Issue by s093294** [openlayers/ol3#3719]
According to spec, and due to a few errors in other gis systems, the output of the GeoJSON format when writing geojson do not have empty properties property.

"properties": {},

**Comment by bartvde** [comment]
We write out properties: null in such case (https://github.com/openlayers/ol3/blob/master/src/ol/format/geojsonformat.js#L545:L551) which is in line with the spec?

A feature object must have a member with the name "properties". The value of the properties member is an object (any JSON object or a JSON null value).

http://geojson.org/geojson-spec.html

**Comment by tschaub** [comment]
Yes, `properties: null` is in line with [the spec](http://geojson.org/geojson-spec.html#feature-objects).

@s093294 - where is `null` causing issues?  It would be good to open a ticket where this is a problem.

**Comment by fredj** [comment]
`properties: null` since v3.4.0 (see https://github.com/openlayers/ol3/pull/3346)

**Comment by s093294** [comment]
Sorry about the issue creation then, my deployment that caused issues was from a build just prior to 3.4. This would explain it.
