### ISSUE TITLE
OverviewMap getting the overview map not the main map 

### ISSUE THREAD

**Issue by bogdanvaduva** [openlayers/ol3#3723]
Is there a way of getting the overview map and not the main map?
Right now the getMap() method is giving the main map. May be there is a way of getting the ovmap_ and i don't know it.
Thanks in advance.

**Comment by adube** [comment]
There's currently no way to get the overview map.  A `getOverviewMap` getter method would be nice, indeed.  If you want to work on a PR, I'd be glad to review it.

**Comment by bogdanvaduva** [comment]
I've asked the question about overviewmap because I wanted to have an overview map with drag box and getting the overview map seems to be a better solution that the one I have right now.
I've forked the current master and added a custom overviewmap with drag (without adding getOverviewMap getter method). I'll try to add this method in my repository. If you want to comment on this have a look at my repository's examples:: https://github.com/bogdanvaduva/ol3/tree/master/examples

**Comment by adube** [comment]
Do you have a live example showingthe overviewmap with drag ?  That seems like a nice addition.

**Comment by bogdanvaduva** [comment]
Here is a working example of overview map with drag box. 

http://ol3.qtibia.ro/overviewmap-custom-drag.html

**Comment by bogdanvaduva** [comment]
I've added overview with drag in my repository's examples and put them online.
http://ol3.qtibia.ro/build/examples/overviewmap-custom-drag.html

**Comment by adube** [comment]
Thanks for sharing this.  I see that you used jQuery UI for the 'draggable'.  That's smart.  I thought that you had modified the control itself to support this natively, but the way you did it is fine.

You can create a PR for the addition of the `getOverviewMap` method only.  The rest should stay in an example.  I'd like to hear from a core dev of ol3 about adding this example to the core library.  I'd say 'no', but it would still be nice to see this in action from somewhere, like in a blog post such as for the GoogleMaps example with ol3: http://bl.ocks.org/elemoine/e82c7dd4b1d0ef45a9a4 (the example is no longer working, but you get the idea).

Again, thanks for sharing !
