### ISSUE TITLE
Create "getCentroid" for all geometry types

### ISSUE THREAD

**Issue by riverstream** [openlayers/ol3#3731]
Create "getCentroid" for all geometry types just as in OL2 available for public use.

**Comment by bill-chadwick** [comment]
Take care with getting a meaningful answer out of a cartesian (x,y) calculation method when the coordinate system does not have equal x,y weights,

With EPSG:4326 coordinates (lat/lon)  x,y coordinate weights are not of equal value other than on the equator.

With EPSG:3857 coordinates (web mercator), coordinate weights change with latitude. You should get a reasonably accurate centroid for polygons with a few kms of extent but for polygons of 100kms in extent the result (from a simple cartesian calulation) will be wrong.

A cartesian calculation method will work well for non global coordinate systems such as UTM or UK grid coordinates (Transverse Mercator).

**Comment by bill-chadwick** [comment]
See the discussion on getLength here

https://github.com/openlayers/ol3/issues/3533

and

here

https://github.com/openlayers/ol3/pull/3609

I suspect that a get centroid method should only really be added to ol.Sphere along the lines of ol.Sphere.prototype.geodesicArea

**Comment by riverstream** [comment]
I actually need it for ol.geom.Polygon, ol.geom.Circle and ol.geom.LineString.  Do not need it for ol.Sphere.

**Comment by bill-chadwick** [comment]
You have misunderstood me, perhaps I did not make myself clear. 

To get an accurate centroid you need to convert the geometry coordinates to 4326 lat/lng and then use a computation of centroid that works for a polygon on a sphere. Sadly the referenced article on the getGeodesicArea method only includes calculations for area and point-in-polygon, not centroid. ol.Sphere is the place where this kind of computation would belong. 

Whilst you can reuse the OL2 code for centroid computation (which I assume is cartesian x,y), it might be an idea to state that it will only give good results for EPSG:3857 polygons with extent less than a few tens of km. It will give bad results for polygons with extents of 100s of kms. The centroid of a circle is of course its centre. OL3 geometry uses a square to represent a circle so its centroid is trivial.

**Comment by riverstream** [comment]
Thank you for the explanation.  My use was definitely not kms.  I was going to use it for areas of 10-20 square meters.

**Comment by bill-chadwick** [comment]
Be very careful if you are also computing area. 

The ol.geometry area methods will not give an answer in square meters if you have EPSG:3857 coordinates. Rather, you should convert the coordinates of the geometry to EPSG:4326 and then use ol.Sphere.geodesicArea. 

With EPSG:3857, scale varies according to the cosine of the latitude. For small area geometries, I think you should be able adjust the return from the geometry class area methods by multiplying them with the square of the cosine of the latitude of the geometry's centroid.

**Comment by riverstream** [comment]
So far no issues calculating areas of 10-20 square meters.  Regarding the current issue: "Create "getCentroid" for all geometry types just as in OL2 available for public use."  Could this be added to a future version of OpenLayers 3.x?

**Comment by bill-chadwick** [comment]
whereabouts in the world are you calculating areas? Do you have a known area on the ground to check the calculated result against?

**Comment by tsauerwein** [comment]
@riverstream For now, as a work-around you can use [Turf](http://turfjs.org/static/docs/module-turf_centroid.html) to calculate the centroid:

    var polygon = new ol.Feature(new ol.geom.Polygon(...));
    var format = new ol.format.GeoJSON();
    var features = format.readFeatures(
        turf.centroid(format.writeFeatureObject(polygon)));
    var centroid = features[1];

Or also [JSTS](http://bjornharrtell.github.io/jsts/doc/api/symbols/jsts.geom.Geometry.html#getCentroid) (here is an [example](http://stackoverflow.com/a/29985781/119937)).

What do you need the centroid for? If you just want to display a label at the centroid, you probably can ignore the issues that @bill-chadwick is mentioning. Then it even would be better to use [pointOnSurface](http://turfjs.org/static/docs/module-turf_point-on-surface.html).

**Comment by bill-chadwick** [comment]
Good point about labelling using a centroid. I guess whats important is
that any documentation for a new method makes it clear that the centroid
wont necessarily be geographically accurate.

**Comment by riverstream** [comment]
Bill, thank you. Correct I would like to focus this open issue on "getCentroid" for all geometry types and not go off topic.  Tsauerwein, thank you I will look into Turf.  And correct, I will be using "getCentroid" for is displaying a label or centering the view.   It does not have to be 100% accurate.  In the long run, it would be correct to integrate this into OpenLayers instead of having to use Turf.  Same as it was in OL2.

**Comment by riverstream** [comment]
Hi, just wondering if there are any updates on this and if "getCentroid" for all geometry types will be integrated into OpenLayers 3.  Thanks.

**Comment by ahocevar** [comment]
@riverstream We have [`getInteriorPoint()`](http://openlayers.org/en/v3.13.1/apidoc/ol.geom.Polygon.html#getInteriorPoint) for polygons and multi points, which is usually better for labeling than the centroid, which can be outside a polygon.

**Comment by riverstream** [comment]
Awesome thanks.

**Comment by ahocevar** [comment]
Can we close this issue then?

**Comment by riverstream** [comment]
Yes thank you.  Quick question, I was reading something, what would be the difference of using getInteriorPoint() as opposed to doing this:

var geometry = feature.getGeometry();
var featureExtent = geometry.getExtent();
var featureCenter = ol.extent.getCenter(featureExtent);

Thanks

**Comment by ahocevar** [comment]
The center of the extent may also lie outside the polygon. What OpenLayers does to calculate the interior point is take the extent, horizontally cuts it in two equally sized rectangles, finds the longest intersection of the geometry with the cut line, and returns the center of that intersection.

**Comment by riverstream** [comment]
Thank you for the great work and great answer.
