### ISSUE TITLE
Add pixel/coordinate to ol.SelectEvent

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#3737]
If pixel and/or coordinate were available in SelectEvent, the code for creating popups/overlays for features such as in the vector-layer example could simply use the select interaction instead of creating its own FeatureOverlay. It looks pretty straightforward to change SelectEvent to pass these vars on from the MapBrowserEvent and I was in the middle of creating a PR when it struck me it might be better/simpler to change `ol.SelectEvent` so it inherits from `ol.MapBrowserEvent` instead of `goog.events.event`. Would there be any problems/issues with doing this?

**Comment by bjornharrtell** [comment]
PR #3454 might be relevant.

**Comment by probins** [comment]
thanks @bjornharrtell I managed to miss that one, which is also on my list. What do you think about adding pixel in that PR? Or would it be better in a separate one?

**Comment by bjornharrtell** [comment]
Perhaps it's better to make it a separate one and I'd like to see the tests in #3453 in first.

**Comment by bjornharrtell** [comment]
Was just hit by goog.events.event not being enough, will make a PR to change base to ol.MapBrowserEvent.

**Comment by bjornharrtell** [comment]
@probins #3757 ready for review.

**Comment by probins** [comment]
thanks for tackling this - we're obviously trying to do similar things in our apps :-)

**Comment by ahocevar** [comment]
Fixed with #3757.
