### ISSUE TITLE
different Y-offset with new ol.tilegrid.createXYZ instead of ol.tilegrid.XYZ

### ISSUE THREAD

**Issue by plepe** [openlayers/ol3#3744]
I'm just testing the current development version, and I noticed that the XYZ tilegrid has changed -> it has been replaced by createXYZ, but that is not the problem. The problem is, that the Y-offset of the requested tiles is different.

I'm using an ol.source.TileVector with ol.tilegrid.XYZ(). I replaced the ol.tilegrid.XYZ by ol.tilegrid.createXYZ, e.g.:

```js
var source = new ol.source.TileVector({
  url: "something/{z}/{x}/{y}.json",
  tileGrid: new ol.tilegrid.createXYZ()
});
```

Now, the Y coordinate of the requested tiles is totally wrong, before it was e.g. 11361, now it is 21406. X and Z are correct.

**Comment by ahocevar** [comment]
What code did you have before? Note that both the old XYZ tilegrid and the new createXYZ function assume that your data projection is EPSG:3857 with the full world extent as projection extent.

**Comment by ahocevar** [comment]
Oh, also note that iy

**Comment by plepe** [comment]
EPSG:3857 it is and full world extent. I also removed the `new`, it didn't change anything. I'll try to create a test file tomorrow ...

**Comment by plepe** [comment]
I created a file which can both handle ol.tilegrid.XYZ() and ol.tilegrid.createXYZ():
https://gist.github.com/plepe/de0db5e5461b99ca0351

It does not really download anything, as I used a relative URL.

When I watch Firebug, it will request ...
* with ol3 v3.5.0, tiles in the range 12/2232/1420.json to 12/2235/1422.json
* with ol3 master, tiles in the range 12/2232/2673.json to 12/2235/2675.json

**Comment by ahocevar** [comment]
Thanks for the test case. This is a regression indeed. I'll provide a fix later today. Stay tuned.

**Comment by ahocevar** [comment]
@piepe, can you please have a look at #3747. That pull request should fix the issue.

**Comment by plepe** [comment]
Yes, that pull request works. Thanks!

I also tried tilesize 1024.
