### ISSUE TITLE
new ol.source.Vector() - JS error

### ISSUE THREAD

**Issue by kulmegil** [openlayers/ol3#3755]
cannot create ol.source.Vector because always getting an error
> TypeError: ol.ext.rbush is not a function

This happens for me when OL is loaded through requireJs
v3.5.0

**Comment by juristr** [comment]
same here. Is there any solution for this?

**Comment by ahocevar** [comment]
Duplicate of #3155.

**Comment by ahocevar** [comment]
@juristr @kulmegil Please try #3910, it should fix the issue.

**Comment by ahocevar** [comment]
Duplicate of #3155.
