### ISSUE TITLE
OpenLayers 3.6.0 jsfiddle and copy examples codes are not working

### ISSUE THREAD

**Issue by cholmes** [openlayers/ol3#3768]
Just got confused by this for a bit. Root reason seems to be that they give links to https://cdnjs.cloudflare.com/ajax/libs/ol3/3.6.0/ol.js and https://cdnjs.cloudflare.com/ajax/libs/ol3/3.6.0/ol.css But cloudflare doesn't have 3.6.0 (yet?). The 3.5.0 examples work fine.

**Comment by ahocevar** [comment]
Unfortunately we cannot trigger a cdnjs build, and it takes up to 24 hours for the new version to be available on cdnjs. This is why I did not announce the release on Twitter yet.

I think next time we'll wait with updating the website until the new version is available on cdnjs.

**Comment by tschaub** [comment]
An alternative would be to just use the openlayers.org hosted builds.
```
$ curl -w @curl-format.txt -o /dev/null -s http://openlayers.org/en/v3.5.0/build/ol.js
    time_namelookup:  2.537
       time_connect:  2.542
    time_appconnect:  0.000
   time_pretransfer:  2.542
      time_redirect:  0.000
 time_starttransfer:  9.049
                    ----------
         time_total:  9.049
```

Compare to the cloudflare time:
```
$ curl -w @curl-format.txt -o /dev/null -s https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol.js
    time_namelookup:  2.541
       time_connect:  4.569
    time_appconnect:  7.986
   time_pretransfer:  7.986
      time_redirect:  0.000
 time_starttransfer:  10.240
                    ----------
         time_total:  11.308
```
(These with `curl-format.txt` from [this post](https://josephscott.org/archives/2011/10/timing-details-with-curl/).)

(And you can now see why I don't work from home.)

**Comment by probins** [comment]
this is now working. I'd agree with @ahocevar that it would be better to hold off updating the website until the new cdnjs version is available.

**Comment by bartvde** [comment]
if so, we should add this to the release procedure

**Comment by probins** [comment]
I noticed that this new procedure was followed with 3.7. I think this issue can be closed

**Comment by bartvde** [comment]
Agreed. I just added a note to the release procedure.
