### ISSUE TITLE
ImageLayer with TileVector Source,.

### ISSUE THREAD

**Issue by javieramor** [openlayers/ol3#3773]
Hi, I'm trying to achieve a ImageLayer that have a TileVector Source, ( the tile vector have a thousands of geometries, and I need to improve the map performance).

The code looks like it:

 var construcciones = new ol.layer.Vector({
            source: new ol.source.TileVector({
                format: new ol.format.GeoJSON(),
                projection: 'EPSG:4326',
                tileGrid: new ol.tilegrid.XYZ({
                    maxZoom: 19,
                    
                }),
                url: 'Manejadores/Layers.ashx?fn=vectorTile&id=898&x={x}&y={y}&z={z}'
            })
            
        });

        var construccionesImage = new ol.layer.Image({
            source: new ol.source.ImageVector({
                source: construcciones
            })
        });

        var map = new ol.Map({
            target: 'map',
            layers: [
              new ol.layer.Tile({
                  source: new ol.source.MapQuest({ layer: 'osm' })
              }),
              construccionesImage
             
            ],
            
            view: new ol.View({
                center: ol.proj.transform([-0.86492, 38.63390], 'EPSG:4326', 'EPSG:3857'),
                zoom: 19
            })
        });

The result is a blank map :(

The "construcciones" layer works, however construccionesImage fails.
I need to know if really is posssible to do it.   Thanks in advance.

**Comment by alvinlindstam** [comment]
The ImageVector layer takes a Vector source as "source", not a Vector layer. 

http://openlayers.org/en/v3.5.0/apidoc/ol.source.ImageVector.html
