### ISSUE TITLE
Heavy RAM usage with ol3, generating swapping

### ISSUE THREAD

**Issue by costales** [openlayers/ol3#3778]
Hi!
I made an application with openlayers for Ubuntu Phone and I'm having a big issue with a swapping. I was looking the problem and I think it could be openlayers.

I can reproduce it into the browser desktop too. Please, watch this video:
https://youtu.be/B-v0k5FMxEM

If I refresh [your official page](http://openlayers.org/en/v3.5.0/examples/accessible.html) each 3", appears that openlayers is not releasing the cache (?).

I tried the same test with [Leaflet basic map](http://leafletjs.com/examples/quick-start-example.html) and it works fine.

Environment:
* Ubuntu 14.04 MATE updated
* Firefox 38.0 or Chromium 41.0.2272.76

One question too: Could I disable the map cache for test this?

Thanks in advance!

PS: I just tried all the ol3 releases and it's happening in all of them.

**Comment by fredj** [comment]
The cache size can now be configured, see #4805, .
