### ISSUE TITLE
Exporting method for midpoint of a linestring

### ISSUE THREAD

**Issue by simon1389** [openlayers/ol3#3779]
A method which returns a certain point of a linestring would be useful in many cases. There is already a function called "getFlatMidpoint" which returns the midpoint of the linestring.
I think this function should be exported and in addition it should provide a fraction as parameter in order to get any point on the linestring. For the midpoint i would call this method with "0.5" as argument.

**Comment by jonataswalker** [comment]
Certainly it would be an useful resource.

**Comment by matjos** [comment]
+1
