### ISSUE TITLE
function fn() / TypeError: d is undefined  | api bug

### ISSUE THREAD

**Issue by CJankowski** [openlayers/ol3#3788]
**Version:** ol.js / v3.5.0
**Error message:**
TypeError: d is undefined
http://openlayers.org/en/v3.5.0/build/ol.js
Line 305
.. function fn(a,c,d,e,f,g){ …

**Solution for ol.js  3.5.0:**
```javascript
function fn(a,c,d,e,f,g){
var h=!1,k,n;
/** Solution -start**/	 if(d==undefined){return}else{k=d.f}	/** Solution -end **/
/** k=d.f; **/
null!==k&&(n=k.gd(),2==n||3==n?k.xf(f,g):(0==n&&k.load(),k.$e(f,g),h=!0));f=(0,d.d)(c);null!=f&&(e=f.Ve(e),(0,gn[e.M()])(a,e,d,c));
return h
}
```

**Explain:**
I write a campus map with many different functions and use ol3 and jquery. For a better use case i generate new classes. One of it call ol.layer.Vector. < ol.layer.Vector.call(this,c); >
In this new class i add functions and dont touch the base of the Vector class. But i get the error message for one layer after a click event. The result is all features from all vector layers have no style and i get the error message.
 I think the problems get from the styles, or any undefined coordinates. But i cant find the error. I am happy for every help, or tips. ( the vector layer is testing in other maps and work fine/ the base data is a geojson file )
For find the error i add in ol.js 3.5.0 the solution. After it all works without errors. Maybe one feature isnt display?
I use ol.js for debug because its faster for me then ol-debug.js.

**Comment by marcjansen** [comment]
To get to the root of you issue, the debug build is way better suited. Please report if the error remains when using ol-debug.js.

Also we'd probably need some code to find out if you have fiund a bug or are using stuff in an unintended way.

**Comment by CJankowski** [comment]
I use ol-debug.js now and after a long long way i found at the end a wrong return for this case and solved it.
ol-debug.js->Error: AssertionError: Assertion failed: obj should be an ol.style.Style.

The issus is solved. Thanks afi to encourage me to use ol-debug. :+1:

**Comment by marcjansen** [comment]
When everything works again, you should switch back to the production build, of course.
