### ISSUE TITLE
Minified Versions of OL3 always have different variables

### ISSUE THREAD

**Issue by dtamm** [openlayers/ol3#3789]
When using the minified version of OL3 and switching from (e.q.) version 3.4 to 3.6 the variables of features deffer between the version which makes an quick update impossible.

Example:

```
console.log(feature.n.someSelfmadeInformation); //Works in 3.4 but doenst work in 3.6
console.log(feature.q.someSelfmadeInformation); //Works in 3.6
```

is there any solution for this, rather than using the debug version of OL?

**Comment by bartvde** [comment]
you should not be using the minified property names at all. You can only use exported properties and functions that are not renamed.

**Comment by bartvde** [comment]
If there are things not part of the API that you need, you can ask for additional API / exports with a github issue. Please motivate why you need it to be available in your application.

Otherwise the only "solution" is to create your own version of the library which adds @api tags for the things you need.

Can you explain what n and q is in the above example?

**Comment by dtamm** [comment]
I add features to an array with some more information i need on my map (e.g. to display a label under the icon):

```
var iconFeature = new ol.Feature({
    geometry: new ol.geom.Point(toMercator(data.items[i].rzlongitude, data.items[i].rzlatitude)),
    calculatedCount: data.items[i].calculatedCount,
    count: data.items[i].count,
    countForHeatmap: data.items[i].count,
    stopName: data.items[i].stopName,
    additionalData: data.items[i].additionalData
});
pointArray.push(iconFeature);
```

All these information are available in the ol.layer.Vector like this:

```
var clusters = new ol.layer.Vector({
    minResolution: 15,
    name: "cluster",
    source: clusterSource,
    style: function(features, resolution) {
        var featuresInArea = features.get("features");
        for(feature in featuresInArea) {
            console.log("Stop Name of this feature ", feature.n.stopName); //as set in the code-example above!
        }
    }
});
```

In Version 3.4 the property of the feature is "n", in version 3.6 it is "q".

**Comment by bartvde** [comment]
Try ```feature.getProperties().additionalData``` instead

**Comment by ahocevar** [comment]
Or simply `feature.get('stopName')`.

**Comment by bartvde** [comment]
Right even simpler, thanks @ahocevar

**Comment by dtamm** [comment]
Okay, maybe i was too lazy to read the documentation till now! Will change my code and give feedback later!

**Comment by dtamm** [comment]
This did really help, thanks!
