### ISSUE TITLE
Tile grid extent settings causes creating lot of useless requests

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#3798]
In my 'app' http://drifted.in/other/ol/tiles_36_extent.html there is the 'extent' specified on vector tile grid to prevent loading vector tiles outside a valid area. But this settings causes creating thousands of requests. Like all my vector data for all tiles in all zoom levels are required.

While the script in Firefox can be interrupted, Chrome consumes almost all PC memory and must be killed.

**Comment by ahocevar** [comment]
Thanks @jan-tosovsky-cz for reporting this issue. `ol.source.TileVector` currently does not respect extent restrictions from the tile grid indeed. Please try #3801, it should fix your issue.
