### ISSUE TITLE
MULTIPLE CHECKBOXES DOES NOT RUN!!!!

### ISSUE THREAD

**Issue by nickhatz** [openlayers/ol3#3807]
MULTIPLE CHECKBOXES DOES NOT RUN!!!!

for (var i = 0; i<5; i++){
var checkbox = document.querySelector('#mycheckbox' + i);
           
            
            layers[i].on('change:visible', function() {
                var visible = this.getVisible();
                if (visible !== checkbox.checked) {
                    checkbox.checked = true;
                }
            });
            //checkbox.checked = layers[i].getVisible();
            
            checkbox.addEventListener('change', function() {
                var checked = this.checked;
                if (checked !== layers[i].getVisible()) {
                    layers[i].setVisible(checked);
                }
            });
            
        }

ALSO IF YOU INITIALIZE THE LAYER WITH visible=false does getVisible is not recongoized

**Comment by pconnell99** [comment]
Could you jsfiddle this https://jsfiddle.net/? Just a quick once over but is this a closure issue?

**Comment by nickhatz** [comment]
check this out:

https://jsfiddle.net/k9qe51f3/8/


--Nikos

**Comment by nickhatz** [comment]
https://jsfiddle.net/k9qe51f3/9/

I caught a mistake

**Comment by pconnell99** [comment]
I'm positive this is a closure issue - if you output 'i' you get '2' - which doesn't exist in the array [0,1].

**Comment by nickhatz** [comment]
excuse me???

**Comment by pconnell99** [comment]
I don't think this is an Openlayers issue, I think it's a fault with the way you are wiring up the event listeners.  I'm no expert (and I don't work on the library) but that's how it looks to me.

**Comment by nickhatz** [comment]
And how it suppose to be??

Same code works using the dom input and bind in version 3.4.0 version

**Comment by ahocevar** [comment]
As @pconnell99 said, the way that @nickhatz defined the event listeners is the problem. I took the liberty to update the jsfiddle with a working option: https://jsfiddle.net/k9qe51f3/10/.

**Comment by nickhatz** [comment]
Thanks for your correction.. but I see you actually added the checked option
into the html code for checkbox0. Using bind you did not need to do that.

--Nikos

**Comment by ahocevar** [comment]
With one additional js code line, you get that as well. See https://jsfiddle.net/k9qe51f3/11/.

**Comment by nickhatz** [comment]
Yes this line made it work perfectly.. I would suggest you to upload this
as example to the openlayers examples

Best,
--Nikos
