### ISSUE TITLE
Graticule not displaying properly on wrapped map

### ISSUE THREAD

**Issue by Jebjum** [openlayers/ol3#3813]
The graticule is only displayed on the first/centered version of a wrapped map:

http://jsfiddle.net/g3jq71op/1/

**Comment by jonataswalker** [comment]
Your fiddle shows nothing. You're requesting `http (ol.js)` over `https`.

**Comment by Jebjum** [comment]
Is that working now?

**Comment by Jebjum** [comment]
The fiddle just adds a graticule to a map. Nothing special.

var map = new ol.Map({
  target: 'map',
  layers: [
    new ol.layer.Tile({
      source: new ol.source.MapQuest({layer: 'osm'})
    })
  ],
  view: new ol.View({
    center: ol.proj.transform(
        [-110, 45], 'EPSG:4326', 'EPSG:3857'),
    zoom: 3
  })
});

var graticule = new ol.Graticule({map: map});

**Comment by jonataswalker** [comment]
I guess that is just what is expected. Just like the [official example](http://openlayers.org/en/v3.6.0/examples/graticule.html).

**Comment by Jebjum** [comment]
I'm wondering how difficult this would be to implement.

**Comment by Jebjum** [comment]
There is actually a bug with the official example. 

If you click on one of the wrapped maps then the graticule switches to that map, however it does not display properly at any zoom level except for the 0 or perhaps 1. Any other zoom level and it will either fail to display the meridians, the parallels, or both, depending on how far you have panned away from the center map, and how far you have zoomed in.

I think it's fine for the graticule to only display over the last wrapped map that was clicked, however it is currently in a broken state.

**Comment by Jebjum** [comment]
I was able to get the correct behavior by modifying ol.Graticule.prototype.addMeridian and ol.Graticule.prototype.addParallel to have them not check if the current extent intersects the latitude or longitude (in other words I commented out the if check surrounded the line that adds the meridians and parallels to their repsective arrays). 

This might have performance implications by drawing lines that are  unseen.

I am guessing the proper fix is to either modify ol.extent.intersects to handle a wrapped extent, or to pass the wrapped extent.

**Comment by Jebjum** [comment]
I have what I think is the proper fix:

In on.Graticule.prototype.handlePostCompose_, on the third line of the function, change:

"var extent = frameState.extent;"

to

"var extent = vectorContext.extent_;"

The graticule will then draw properly on the last map that you clicked on.

**Comment by Jebjum** [comment]
Created pull request:

https://github.com/openlayers/ol3/pull/3858

**Comment by fredj** [comment]
Fixed with #3858

**Comment by NickMackz** [comment]
I wouldn't say this was fixed by that pull request. It improved the display of the graticule when wrapping is enabled, but the graticule is still only displayed on the first/centred version of a wrapped map.

**Comment by ahocevar** [comment]
You are right. We have an open issue for that, and are accepting pull requests: #4308.
