### ISSUE TITLE
Trackpad pinch zoom on a desktop

### ISSUE THREAD

**Issue by klokan** [openlayers/ol3#3817]
The Chrome web browser sends special events on a desktop computer for the pinch zooming with two fingers on a trackpad.
Google Maps web application (http://maps.google.com) allows to zoom-in and out with a trackpad with pinch gestures (tested on a Mac, but should be true also on Windows and ChromeOS).

Here is a demo code (try trackpad gestures on the blue rectangle on the right):
http://jsbin.com/qiyaseza/8/edit?html,js,output

The technical details:
https://code.google.com/p/chromium/issues/detail?id=289887

Implementation of this may also help on some of the large touch screens connected to desktop computer. Similar user report in OL3 was under #3054 - marked as not possible (in that time).

**Comment by bartvde** [comment]
@klokan this already works for me in Chrome on OSX (for instance on http://openlayers.org/en/v3.6.0/examples/bing-maps.html), it does not work for you?

**Comment by bartvde** [comment]
Ah okay my older Safari ticket, now I remember

**Comment by klokan** [comment]
You are right - it works now in Chrome out of the box.
I had this task for a few month in drawer - and it seems the latest Chrome implemented emulation of standard zoom events for the pinch gestures on trackpad directly.

I am sorry for the confusion. Closing.

**Comment by klokan** [comment]
BTW Safari still does not work - but the demo above would not help - as it is probably for Chrome only.
