### ISSUE TITLE
GML reader should handle CDATA nodes

### ISSUE THREAD

**Issue by rattai** [openlayers/ol3#3827]
https://github.com/openlayers/ol3/blob/v3.6.0/src/ol/format/gml/gmlbaseformat.js#L209
Should also catch `n.firstChild.nodeType === 4` for CDATA text nodes.

Not sure if this relates to #2977, as I don't understand what that issue is about.

**Comment by bartvde** [comment]
Are you up for submitting a pull request with a test case? TIA.

**Comment by fredj** [comment]
fixed with #3863
