### ISSUE TITLE
Version 3.6.0,  ol.layer.Vector, GeoJSON format,  wrong result with projection EPSG:3031

### ISSUE THREAD

**Issue by icebreakerPNRA** [openlayers/ol3#3831]
This is my code using openlayers 3.4.0

`<script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.4.0/ol.js"></script>`
`<script src="http://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js"></script>`

`var EPSG ='EPSG:3031'; // EPSG:3031 - WGS 84 / Antarctic Polar Stereographic`

`proj4.defs([['EPSG:3031','+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0` `+ellps=WGS84 +datum=WGS84 +units=m +no_defs']]);`

`var projection = ol.proj.get(EPSG);`
`var extent = ol.proj.transformExtent([-180, -45, 180, -90], 'EPSG:4326', projection); `
`var center = ol.proj.transform([180,-60], 'EPSG:4326', projection);`
`projection.setExtent(extent);`

`var iceEdgeWMS = new ol.layer.Image({ ` 
`	source: new ol.source.ImageWMS({`
`    	url: 'http://geos.polarview.aq/geoserver/wms',`
`    	params: {'LAYERS': 'polarview:iceedgeS15', 'SRS': 'EPSG:3031'},`
`    	serverType: 'geoserver'`
`    	})`
`  });`
  

`var graticule_style = new ol.style.Style({`
`	fill : new ol.style.Fill({`
`		color : '#BBBBBB'`
`	}),`
`	stroke : new ol.style.Stroke({`
`		color : '#BBBBBB',`
`		width : 0.5`
`	})`
`});`

`var WFS_json_graticuleWide = 	'http://sysnav.bologna.enea.it/geoserver/'+`
`'UTIL/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=UTIL:graticule_wide'+`
								`'&maxFeatures=100000&srsName='+EPSG+'&outputFormat=application/json';`

`var graticuleWide = new ol.layer.Vector({`
`		source: new ol.source.GeoJSON({url: WFS_json_graticuleWide}),`
`		style:  graticule_style`
` }); `		

`var map = new ol.Map({`
`  controls: ol.control.defaults().extend([`
`    new ol.control.ScaleLine()`
`  ]),`
`  layers: [iceEdgeWMS, graticuleWide],`
`  target: 'map',`
`  view: new ol.View({`
`    projection: projection,`
`    center: center,`
`    rotation: (Math.PI),`
`    zoom: 1`
`  })`
`});`

and this the result

![screenshot_340](https://cloud.githubusercontent.com/assets/11041983/8272761/58462132-1850-11e5-850c-2357e5deefaf.png)

For using openlayers I changed  these code lines:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.6.0/ol.js"></script>`

and

`var graticuleWide = new ol.layer.Vector({`
`		source: new ol.source.Vector({url: WFS_json_graticuleWide, format: new` `ol.format.GeoJSON()}),`
`		style:  graticule_style`
` }); `

and this is the wrong result

![screenshot_360](https://cloud.githubusercontent.com/assets/11041983/8273353/1db35b6a-186a-11e5-949d-aa3f9b27db73.png)

but including again the ol.js after projection definition:

...
`projection.setExtent(extent);`
`</script>`

`<script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.6.0/ol.js"></script> `

`<script>`
`var iceEdgeWMS = new ol.layer.Image({ ` 
`	source: new ol.source.ImageWMS({`
`    	url: 'http://geos.polarview.aq/geoserver/wms',`
`    	params: {'LAYERS': 'polarview:iceedgeS15', 'SRS': 'EPSG:3031'},`
`    	serverType: 'geoserver'`
`    	})`
`  });`
....

the result is correct like using ol 3.4.0

Any idea

**Comment by sweco-sealvi** [comment]
Your working example (ol 3.4.0): http://jsfiddle.net/3yLcg1ax/1/

Your non-working example (ol 3.6.0): http://jsfiddle.net/3yLcg1ax/2/

Your example with simple fix (ol 3.6.0): http://jsfiddle.net/3yLcg1ax/3/

Basically: You define the proj4 definition for "EPSG:3031", but your data is returned with "urn:ogc:def:crs:EPSG::3031". Adding it as an alias in proj4 fixes your issue.

I don't know if this is an intended change or not, or why ol 3.4.0 recognised the alias without explicit declaration.

**Comment by icebreakerPNRA** [comment]
Great ! Thank you so much.
