### ISSUE TITLE
 ol.format.GeoJSON.writeFeatureObject adds a Style property which prevent JSON export

### ISSUE THREAD

**Issue by Jenselme** [openlayers/ol3#3832]
`ol.format.GeoJSON.writeFeatureObject` sometimes adds a Style property when trying to get it as a GEOJson object which prevents the export of the features to JSON because of cyclic references. The problem occurs when I import a KML file in the map. If I try to use `writeFeature`, I get a stackoverflow error instead.

Here is the code I use.
```javascript
var source = layer.getSource();
var features = source.getFeatures();
var geojsonFormat = new ol.format.GeoJSON();

for (var i = 0, ii = features.length; i < ii; ++i) {
    var feature = features[i];
    var geojsonFeature = geojsonFormat.writeFeatureObject(feature);

    // Remove style property to avoid problem when converting to JSON
    if (geojsonFeature.hasOwnProperty('properties') &&
            geojsonFeature.properties &&
            geojsonFeature.properties.hasOwnProperty('Style')) {
      delete geojsonFeature.properties.Style;
    }
}
```

I think it shouldn't behave this way and always allow the export to JSON. This is the behavior I expect after reading the documentation.

Tested with OpenLayers 3.6.0

Problem originally submitted to https://github.com/camptocamp/ngeo/pull/239

**Comment by elemoine** [comment]
Could you please copy&paste the exact error you get when serializing to JSON/GeoJSON?

**Comment by Jenselme** [comment]
Here it is:

```
"Error: cyclic object value
toJson@http://geoportal.disney.interne/lib/angular.js:1036:10
$HttpProvider/this.defaults.transformRequest<@http://geoportal.disney.interne/lib/angular.js:8626:56
transformData/<@http://geoportal.disney.interne/lib/angular.js:8574:12
forEach@http://geoportal.disney.interne/lib/angular.js:322:11
transformData@http://geoportal.disney.interne/lib/angular.js:8573:3
$http/serverRequest@http://geoportal.disney.interne/lib/angular.js:9239:23
processQueue@http://geoportal.disney.interne/lib/angular.js:13075:27
scheduleProcessQueue/<@http://geoportal.disney.interne/lib/angular.js:13091:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://geoportal.disney.interne/lib/angular.js:14291:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://geoportal.disney.interne/lib/angular.js:14107:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://geoportal.disney.interne/lib/angular.js:14395:13
ngEventHandler/<@http://geoportal.disney.interne/lib/angular.js:22827:17
jQuery.event.dispatch@http://geoportal.disney.interne/lib/jquery-2.0.3.js:4675:15
jQuery.event.add/elemData.handle@http://geoportal.disney.interne/lib/jquery-2.0.3.js:4360:6
"
```

Note: my frontend is adapted from https://github.com/geoadmin/mf-geoadmin3

**Comment by elemoine** [comment]
@Jenselme, are you able to test if my [kmlformat](https://github.com/openlayers/ol3/compare/master...elemoine:kmlformat) branch fixes the problem?

**Comment by Jenselme** [comment]
@elemoine Just tested. It fixes the problem.

**Comment by elemoine** [comment]
Thanks for testing. I'll try to turn this into a PR.

**Comment by Jenselme** [comment]
Did you create the PR? I am not able to find it.

**Comment by elemoine** [comment]
No, I did not. Are you able to do it (and add tests)? Thanks.

**Comment by probins** [comment]
what happens with GeoJSON features which have a style property?

**Comment by ahocevar** [comment]
@probins The style property cannot be serialized, because its value is a complex object.

Another (simpler) solution to this problem would be to simply check `goog.isNumber(property) || goog.isString(property)` before serializing.

**Comment by probins** [comment]
but a GeoJSON feature may have a style property that has nothing to do with OL3 style: `"style":"modern"` for example. I think the number/string check is the better solution.

**Comment by ahocevar** [comment]
@Jenselme, can you please test if #3903 also fixes your problem?
