### ISSUE TITLE
Overviewmap projection

### ISSUE THREAD

**Issue by htulipe** [openlayers/ol3#3836]
The overviewmap's View projection is always EPSG:3857. This causes issues when the displayed layer is not in such projection (4326 for instance).

For instance, when dezooming to min zoom (0), we get something like the following:

![overviewmap](https://cloud.githubusercontent.com/assets/1255457/8284304/8b03408a-18fc-11e5-90b9-5bca67a37b1c.jpg)

**Comment by adube** [comment]
See #3007 and #3647.

**Comment by htulipe** [comment]
Ok my bad.

Hadrien Tulipe

2015-06-22 17:25 GMT+02:00 Alexandre Dubé <notifications@github.com>:

**Comment by adube** [comment]
You can close this issue.
