### ISSUE TITLE
LayerGroup visibility change

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#3837]
When the visibility of a layer group changes, it switches off its sub layers, but no events are emitted on the sub layers. This seems wrong to me?
Or maybe this was by design somehow?

**Comment by marcjansen** [comment]
The sublayers state doesn't change, does it?

**Comment by bartvde** [comment]
very true @marcjansen 
okay, probably makes sense to handle this at the application level then ;-)

**Comment by bartvde** [comment]
@marcjansen how did you handle this in the GeoExt 3 layer tree?

For instance you cannot have 1 sublayer visible and another one invisible, without having the layer group itself checked. This seems different from how other systems work? I thought in Ext the parent is only visible if all children are visible?

**Comment by marcjansen** [comment]
We're not really dealing with this properly right now. PR welcome :-)
