### ISSUE TITLE
style issue with selection and modify interaction on different vector layers

### ISSUE THREAD

**Issue by ubahnverleih** [openlayers/ol3#3838]
I have problems with select interactions and modify interactions on different layers. My select interaction is limited to one layer. The features of my modify interaction are on another layer - but sometimes i get the selection style of the select interaction on the this layer.

I have created a jsfiddle where you can reproduce this behavior: http://jsfiddle.net/s9womb3b/14/
there are two layers:
* select: with no features, but select interaction
* vectorLayer: with one feature which is used in the modify interaction.

The modify interaction has a custom style and `deleteCondition` set to `ol.events.condition.never` (maybe the deleteCondition is part of the problem, or other conditions just hide the problem)

To reproduce the behavior click on the middle of a line segment. Then the blue bubble of the selectionlayer style appears and on mouse move on the linestring it moves unit mouse leaves the linestring. On leaving the line stops there and the black circle of the modify style appears as it should but the blue circle also doesn't disappears. 

you can also [comment in](http://jsfiddle.net/s9womb3b/13/) the style on the select interaction, so you can see that the wrong style comes from the select interaction. (but the behavior is a bit differnt)

I can reproduce this in different browsers.

**Comment by jonataswalker** [comment]
If you add a filter on your select interaction your issue is solved, although this behavior is not expected.

```javascript

var select = new ol.interaction.Select({
    filter: function(feature, layer){
        if(feature.getGeometry() instanceof ol.geom.Point)
            return false;
    }
});

```

**Comment by ahocevar** [comment]
I don't know what causes the problem, but it does not happen with current master any more. See http://jsfiddle.net/s9womb3b/16/. So I consider this fixed.
