### ISSUE TITLE
ol.source.MapQuest logo not found

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#3839]
The [mapquest logo url](https://github.com/openlayers/ol3/blob/master/src/ol/source/mapquestsource.js#L41) is not present anymore.

**Comment by bartvde** [comment]
Right I noticed the same and have asked them on Twitter: https://twitter.com/6artvde/status/613256118287114240

**Comment by bartvde** [comment]
Has been fixed by MapQuest.
