### ISSUE TITLE
Unable to snap only on vertices or edges.

### ISSUE THREAD

**Issue by dufop** [openlayers/ol3#3850]
In OL2 there was options to activate the snapping only on vertices or edges and it would be great to have those options in OL3:
vertex {Boolean} Snap to vertices in target layer. Default is true.
edge {Boolean} Snap to edges in target layer. Default is true.

**Comment by AndreasTheMonkey** [comment]
I Agree!  Please add this feature.

**Comment by ahocevar** [comment]
Pull request anyone?

**Comment by fredj** [comment]
#5081
