### ISSUE TITLE
assert errors on layers with empty features array.

### ISSUE THREAD

**Issue by Rascaile** [openlayers/ol3#3862]
Today I upgraded from openlayers version 3.5 to 3.6, and it suddenly started throwing the following error:

    Uncaught AssertionError: Failure: unexpected layer configuration

It seems to be thrown right after I add a Vector layer with an empty source array to the map.
The trace from the error does not go all the way back to `addLayer()` so I assume it gets thrown when openlayers tries to render the map into the canvas (but it's only thrown once after adding such a layer) for the first time.

It's also thrown when I try to call `map.forEachFeatureAtPixel` with these vector layers on the map.

The errors disappear when I create a check to only add a layer if its source contains at least some elements, but this is not an elegant permanent solution as these points are defined by the users of our system (users can create custom points on our maps and save them). So to make this work I'd need to remove and add the layer whenever the first point is added or the last is deleted (granted, not a big issue, but still!). It's also not logical a layer like this -needs- to have features, if there are 0 features, there's no need to render them, so why throw an error? (that's my logic at least).

I couldn't find anything relevant in the changelog, at least not at first glance without digging into each separate issue, so this might be a side effect of some other changes.

I'll update with relevant information as I find it.

Thanks for your time.
Rascaile

**Comment by ahocevar** [comment]
The assertion you got is indeed thrown by the renderer, when looking for a suitable layer renderer. It does not get thrown when you create a layer without a source.

It will be best if you can create a JSFiddle that shows the issue.

**Comment by Rascaile** [comment]
So, I was apparently using some odd build of ol3.6 that sneaked its way into our folders, which had ENABLE_VECTOR=false in its configuration file (we are trying to move away from vectors in favor of overlays). Go figure. 

Lots of effort for nothing here, I was simply trying to add vector layers to a build that didn't support it. "looking for a suitable layer renderer" should've rang a bell quicker!

Thanks for the quick response, and keep up the good work with this library!
