### ISSUE TITLE
Overlaying map with different colors to each state/countries

### ISSUE THREAD

**Issue by rdsivaa** [openlayers/ol3#3866]
Hi Team, 
            I am new to open layers development. I have requirement to draw different colors on the US states based on the US state co-ordinates. I managed to draw the borders on the US map. But unable to set different colors to each states. Is there any option to set different colors to each states or countries. I want to populate the color like attached snapshot. If i get any quick help with solution would be great helpfull to continue the research. 
I would really appreciate your speedy response. 

![us_states_with_different_colors](https://cloud.githubusercontent.com/assets/13153917/8481998/43c1d71a-20ac-11e5-8de7-d6d6ff57ef4c.JPG)

**Comment by tsauerwein** [comment]
Please ask usage questions on [StackOverflow](http://stackoverflow.com/questions/tagged/openlayers-3). Regarding your question I would recommend you to take a look at the documentation (e.g. [Understanding Style](http://openlayers.org/ol3-workshop/vector-style/style-intro.html) or [ol.Style](http://openlayers.org/en/master/apidoc/ol.style.html)).
