### ISSUE TITLE
`@fires` for ol.Feature not correct

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#3868]
http://openlayers.org/en/master/apidoc/ol.Feature.html is not showing the change event correctly. Looks like the `@fires` should give the event type, which isn't the case with ol.Feature. I assume the intention here is to list what triggers a change. This needs changing but I'm not sure what to :-)

**Comment by probins** [comment]
I think what needs to change here is:
* `@fires` line should be removed from https://github.com/openlayers/ol3/blob/master/src/ol/feature.js#L53
* if it's the case that 'id' and 'style' changes should trigger events, then `@observable` should be added to `getId`, `setId`, `getStyle`, `setStyle` (`getGeometry` and `setGeometry` are already observable)

If someone could confirm this is how this should be, I'll create a PR.

**Comment by ahocevar** [comment]
Yes, that's correct. See https://github.com/openlayers/ol3/tree/master/config/jsdoc/api#events for the documentation on how to annotate events. Please go ahead with the changes as you suggested above.
