### ISSUE TITLE
select feature v 3.7.0 problem, render webgl.

### ISSUE THREAD

**Issue by manuelBermejo** [openlayers/ol3#3885]
When I select a feature, using the interaction select, and using the render webgl ( I use webgl because I have a big amount of data), the style of the selection is not functionally, the feature is selected but it's transparent, with the default style I have the same problem.

This happens only in the version 3.7.0, with the 3.6.0. I have no problem.

**Comment by manuelBermejo** [comment]
I don't use filter, just :
 var select = new ol.interaction.Select({
    layer: drawLayer,
    style: style1 
});

**Comment by ahocevar** [comment]
In this case #3883 should indeed fix this issue, because specifying a layer in the select interaction's config object creates a filter internally.

**Comment by ahocevar** [comment]
There is a second issue with unmanaged layers and the WebGL renderer. See #3896 for a fix.
