### ISSUE TITLE
How to throttle/limit ol.Feature change event? Does 'dragend' exist?

### ISSUE THREAD

**Issue by thinkpadder1** [openlayers/ol3#3887]
Google maps has three major change events for shapes (polylines, etc):

1. **drag:** This event is repeatedly fired while the user drags the shape.
2. **dragend:** This event is fired when the user stops dragging the shape.
3. **dragstart:** This event is fired when the user starts dragging the shape.

Openlayers has only one change event: 'change'. And it fires like 'drag', repeatedly. The problem for me is that I do a lot of intensive stuff when the 'change' event fires. However, only the last 'change' event matters to me. Is there any way to suppress all the the 'change' events except the last one similar to 'dragend' so I can increase performance?

Thank you.

**Comment by alvinlindstam** [comment]
Such events belongs to the interactions in ol3. Have a look at http://openlayers.org/en/v3.7.0/apidoc/ol.ModifyEvent.html

**Comment by thinkpadder1** [comment]
Looks like this was just added last week. Thank you for pointing me to the correct docs (I was looking at 3.6.0).
