### ISSUE TITLE
Tile queues don't play well together

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3889]
If you have two tile queues that load tiles for a single source, one may stop loading tiles.  This can occur when you have two maps (each has its own tile queue) that render data from the same source.

When a consumer requests that the queue loads more tiles (e.g. the [map calls `queue.loadMoreTiles()`](https://github.com/openlayers/ol3/blob/a62bbd66505255229e1d12ff1f004a34ac32a247/src/ol/map.js#L1012)), the tile queue registers a tile change listener and [calls `tile.load()`](https://github.com/openlayers/ol3/blob/a62bbd66505255229e1d12ff1f004a34ac32a247/src/ol/tilequeue.js#L91-L101).  The `tile.load()` function is [a no-op if the tile is not idle](https://github.com/openlayers/ol3/blob/a62bbd66505255229e1d12ff1f004a34ac32a247/src/ol/imagetile.js#L148-L160), so the queue's [tile change handler](https://github.com/openlayers/ol3/blob/a62bbd66505255229e1d12ff1f004a34ac32a247/src/ol/tilequeue.js#L74-L84) never gets called, the queue's `tilesLoading_` count never gets decremented, and the queue will stop loading tiles when this count surpasses the max.  If the now-unresponsive tile queue is responsible for loading tiles for additional sources (more tile layers on the second map), these will never load either.

We should be able to write tests to demonstrate the problem, but it should happen when you have two maps that render data from the same source.  Both consumers (maps) queue up the same tiles, one queue calls `tile.load()` first, and its change handler will get called.  The second calls `tile.load()`, its change handler never gets called, and the queue becomes unresponsive to future `queue.loadMoreTiles()` calls when the load count exceeds the max loading threshold.

Two possible solutions:

 * Only register for change and call `tile.load()` if a tile is idle in [`queue.loadMoreTiles()`](https://github.com/openlayers/ol3/blob/a62bbd66505255229e1d12ff1f004a34ac32a247/src/ol/tilequeue.js#L91-L101), and only increment `tilesLoading_` by the number of `tile.load()` calls.
 * Make `tile.load()` always call `tile.changed()` (even if the tile is not idle).

I think the first is a more sensible solution.

Kudos to @aisaacs for debugging this and getting to the bottom of the problem.  If anybody has any feedback on the proposed solutions (or another), please weigh in.

**Comment by tschaub** [comment]
Here's the failing test: https://github.com/planetlabs/ol3/commit/a705c6fe11e4683e2f6066ef3d53ed31264a2fc7

**Comment by elemoine** [comment]
Well spotted @aisaacs and @tschaub! And good description of problem.

So we currently assume that tiles in the queue cannot be in another state than IDLE. And this is a wrong assumption, as the same tile may be inserted into multiple queues.

So, yes, the `loadMoreTiles` function should just dequeue and "skip" non-IDLE tiles.

If we wanted to go fancy (we probably don't) we could provide a way to share a single tile queue across multiple maps.

**Comment by elemoine** [comment]
Another option maybe would be to modify `ol.Map#getTilePriority` to return `DROP` if the tile is not IDLE. In this way we ensure that we don't enqueue non-IDLE tile.

**Comment by tschaub** [comment]
Tiles are queued idle.  Then later, load is called.  When enqueuing, you don't know who is going to call load.

**Comment by tschaub** [comment]
> Another option maybe would be to modify ol.Map#getTilePriority to return DROP if the tile is not IDLE.

This would be a map-specific fix that wouldn't solve our use (where the map is not the tile consumer).

**Comment by elemoine** [comment]
> This would be a map-specific fix that wouldn't solve our use (where the map is not the tile consumer).

Right. The priority function is run at enqueue time so that option would indeed not work.

**Comment by elemoine** [comment]
> The fix is pretty simple. Just waiting for @aisaacs to make it since it was his find.

Looks good to me.
