### ISSUE TITLE
TileLoadError did not fires when tile does not exist

### ISSUE THREAD

**Issue by shareit** [openlayers/ol3#3890]
I have a Zoomify server that creates the tiles from a big image (max 4gb) and uploads the tiles in an accessible place for the web application. Tiles are uploaded in chunks of zoom levels, so when I load the page only few levels of tiles are uploaded.
The problem is that if the user try to zoom in the map, the request for getting the tiles is failing but the 'tilelioaderror' event from the Zoomify source is not triggered. 
My idea is to use this event to retry loading the missing tiles later every 2 seconds.

If I am missing anything or there is another way to achieve this functionality please let me know.

Thanks,

**Comment by fredj** [comment]
The `tileloaderror` event is correctly dispatched for the `ol.source.Zoomify` source.
Tested with the [zoomify example](http://openlayers.org/en/v3.14.1/examples/zoomify.html)
```js
source.on('tileloaderror', function(event) {console.log('tileloaderror');})
source.setUrl('invalid');
```
