### ISSUE TITLE
Frozen window when add WMTS Layer with EPSG:4326

### ISSUE THREAD

**Issue by lehmannwebdev** [openlayers/ol3#3891]
I need to add WMTS source in my project. 

When I try to add layer to map and use  layer source 'EPSG:4326' then the browser window tab crashes.
I know that 'EPSG:4326' don't exist for that layer source, but 'EPSG:25834' (don't exist too) don't suspend browser tab.

You can recreate: http://jsfiddle.net/hx9f3ozL/2/

**Comment by ahocevar** [comment]
You need to set the view projection to EPSG:4326 as well, and you cannot use your layer with an OSM base layer. See http://jsfiddle.net/hx9f3ozL/3/ for an updated fiddle.
