### ISSUE TITLE
Get map viewer bounding box in pixels

### ISSUE THREAD

**Issue by shareit** [openlayers/ol3#3901]
I have a Zoomify source layer and I need to retrieve the bounding box size of the view depending on the zoom level and view center. My map is rendered as a canvas with 100% width and it is positioned at 0,0. I need to retrieve the bounding box of the view (the visible tiles). Please advice!

If needed, I'm using OpenLayers 3.6.

This is not an issue but a support item. I ask the same question on http://stackoverflow.com/questions/tagged/openlayers-3 but nobody responds.

**Comment by ahocevar** [comment]
Please rephrase your question on stackoverflow. When nobody answers, it is usually a sign of a question that is not clear to or understood by the audience.
