### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getWrapX' of null

### ISSUE THREAD

**Issue by printmypic** [openlayers/ol3#3902]
Look like from 3.6 to 3.7 there is some error related to the getWrapX

console logs:

ol.renderer.Map.forEachFeatureAtCoordinate	@	ol-debug.js?r=20150706:51866
ol.Map.forEachFeatureAtPixel	@	ol-debug.js?r=20150706:82599
(anonymous function)	@	openlayers.3-polygon.js:523
goog.events.EventTarget.fireListeners	@	ol-debug.js?r=20150706:12811
goog.events.EventTarget.dispatchEventInternal_	@	ol-debug.js?r=20150706:12908
goog.events.EventTarget.dispatchEvent	@	ol-debug.js?r=20150706:12723
ol.Map.handleMapBrowserEvent	@	ol-debug.js?r=20150706:82954
goog.events.EventTarget.fireListeners	@	ol-debug.js?r=20150706:12811
goog.events.EventTarget.dispatchEventInternal_	@	ol-debug.js?r=20150706:12908
goog.events.EventTarget.dispatchEvent	@	ol-debug.js?r=20150706:12723
ol.MapBrowserEventHandler.emulateClick_	@	ol-debug.js?r=20150706:49194
ol.MapBrowserEventHandler.handlePointerUp_	@	ol-debug.js?r=20150706:49251
goog.events.EventTarget.fireListeners	@	ol-debug.js?r=20150706:12811
goog.events.EventTarget.dispatchEventInternal_	@	ol-debug.js?r=20150706:12908
goog.events.EventTarget.dispatchEvent	@	ol-debug.js?r=20150706:12723
ol.pointer.PointerEventHandler.fireEvent	@	ol-debug.js?r=20150706:48830
ol.pointer.PointerEventHandler.up	@	ol-debug.js?r=20150706:48688
ol.pointer.MouseSource.mouseup	@	ol-debug.js?r=20150706:47588
ol.pointer.PointerEventHandler.eventHandler_	@	ol-debug.js?r=20150706:48599
goog.events.fireListener	@	ol-debug.js?r=20150706:12270
goog.events.handleBrowserEvent_	@	ol-debug.js?r=20150706:12394
(anonymous function)	@	ol-debug.js?r=20150706:11819

**Comment by pgiraud** [comment]
I'm reopening this issue since I face the same problem.
It looks like `ol.Map::forEachFeatureAtCoordinate` fails when there's a layer with no source. I will create an example to show this.

**Comment by pgiraud** [comment]
In https://github.com/openlayers/ol3/commit/8a902f638ea400c2b8e2dfc50225034b6b388fdc I added a test showing the issue.
