### ISSUE TITLE
Error on ol.Vector.source.clear()

### ISSUE THREAD

**Issue by Burstaholic** [openlayers/ol3#3904]
When you create a vector source with `useSpatialIndex: false`, calling `clear()` on it produces this error:

`Uncaught AssertionError: Assertion failed: featureChangeKeys is an empty object now`

Example Fiddle: https://jsfiddle.net/Burstaholic/dzyzw6t4/ (modified from the example in #3812 )

Workaround: calling `clear(true)` succeeds, but this may not be desirable in all cases.

**Comment by ahocevar** [comment]
@Burstaholic Can you please test if #3906 fixes your issue?

**Comment by Burstaholic** [comment]
@ahocevar That does indeed fix it for me :tada:
