### ISSUE TITLE
Map leaves bands when browser zoom is not 100%

### ISSUE THREAD

**Issue by 1Map** [openlayers/ol3#3909]
Hi,

When my Chrome Browser (also in Firefox) is zoomed in (110% - By pressing Ctrl and Plus), I get bands on my map.  With zoom at 100% everything is ok.

How to replicate:

1) Press Ctrl and Plus in Chrome (Zoom to 110%)
2) Refresh the page (F5)
3) Result as follow (In Chrome):

![image](https://cloud.githubusercontent.com/assets/1152458/8724101/104b7862-2bd0-11e5-9b1c-4f600978634a.png)

Result should be as (which only works if the Browser is 100% Zoom Scale):

![image](https://cloud.githubusercontent.com/assets/1152458/8724759/99fb8b24-2bd0-11e5-85ff-af1c335d17e2.png)

The layer is:

new ol.layer.Tile({......

and the source is:

source: new ol.source.TileWMS({......

Also note that this layer draws from GWC (Geowebcache) in GeoServer and is a cached layer.

**Comment by ahocevar** [comment]
This is because OpenLayers requests tiles from WMS sources with the pixel ratio of the map if `serverType` is configured for the source. GWC cannot deliver tiles with a pixel ratio other than 1. So you'll have to configure your source like this:
```js
source: new ol.source.TileWMS({
  hidpi: false
  // ...
})
```

**Comment by 1Map** [comment]
Thanks for the quick reply.  Fixed and is working now.
