### ISSUE TITLE
fromLonLat not working to setCenter

### ISSUE THREAD

**Issue by spifftek70** [openlayers/ol3#3911]
I'm trying to set the center (setCenter) of the map from a JSON coordinate that comes in form Genomes using ui.autocomplete. I'm using the openlayers default proj of EPSG:3857, so to get the coordinates to plot, I'm using fromLongLat like so:

    $(function () {
            function log(message) {
                $("<div/>").text(message).prependTo("#log");
                $("#log").scrollTop(0);
            }
            $("#city").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON?username=XXXXX",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            style: "full",
                            maxRows: 12,
                            name_startsWith: request.term
                        },
                        beforeSend: function () {
                            $('.input-group-addon').html("<i class='fa fa-spinner'></i>");
                        },
                        success: function (data) {
                            response($.map(data.geonames, function (item) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryCode,
                                    value: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryCode,
                                    lat: item.lat,
                                    lng: item.lng
                                };
                            }));
                            $('.input-group-addon').html("<i class='fa fa-search'></i>");
                        }
                    });
                },
                minLength: 2,
                open: function () {
                    $(this).removeClass("ui-corner-all").addClass("ui-corner-top");
                    $(".input-group").css("z-index", 1000);
                    $(".ui-autocomplete").css("z-index", 1000);

                },
                close: function () {
                    $(this).removeClass("ui-corner-top").addClass("ui-corner-all");
                },
                select: function (event, ui) {
                    log(ui.item ?
                            "Selected: " + ui.item.label :
                            "Nothing selected, input was " + this.value);
                    var lat = ui.item.lat;
                    var lng = ui.item.lng;
                    locationB = [-95.36327, 29.76328];
                    var locationS = [lng, lat];
                    console.log('locationS = ' + locationS);
                    console.log('locationB = ' + locationB);
                    console.log('view map center = ' + taco);
                    var booH = ol.proj.fromLonLat(locationS);
                    console.log('tacoRepo = ' + booH);
                    var a = map.getView();
                    a.setCenter(booH);
                    a.setZoom(6);

                    var vectorlayer3 = new ol.layer.Vector({
                        source: vectorSource3
                    });

                    var marker = new ol.Feature({
                        geometry: new ol.geom.Point(location)
                    });
                    var vectorSource3 = new ol.source.Vector({
                        features: [marker]
                    });
                    vectorSource3.addFeature(marker);
                    map.addLayer(vectorlayer3);

                    var iconStyle = new ol.style.Style({
                        image: new ol.style.Icon({
                            anchor: [0.5, 46],
                            opacity: 0.75,
                            scale: 0.10,
                            anchorXUnits: 'fraction',
                            anchorYUnits: 'pixels',
                            src: "../images/flag.png"
                        })
                    });
                    marker.setStyle(iconStyle);
                }
            });
        });
The problem is that it's not reprojecting the coordinates properly. It keeps messing up the latitude.

it takes [-95.36327, 29.76328] and makes it [-10615790.656781463,-8452628.599925281] (which is -95.36327, -60.2367112)

here's the console.log readouts:

     locationS = -95.36327,29.76328
     locationB = -95.36327,29.76328
     view map center = -10615790.656781463,3473157.841633498
     tacoRepo = -10615790.656781463,-8452628.599925281

Why is it messing up the latitude??

**Comment by tsauerwein** [comment]
Make sure that your coordinates are numbers, and not strings.

    ol.proj.fromLonLat( [-95.36327, 29.76328])
    > [-10615790.656781463, 3473157.841633498]
    ol.proj.fromLonLat( ["-95.36327", "29.76328"])
    > [-10615790.656781463, -8452628.599925281]
