### ISSUE TITLE
ol.interaction.Modify needs to have 'multi' option in constructor like the Select interaction

### ISSUE THREAD

**Issue by AndreasTheMonkey** [openlayers/ol3#3914]
Modify interaction currently doesn't play well with overlapping features. The Select interaction has 'multi' option that allows selecting only 1 of overlapping features, but it is impossible to drag only one feature with Modify interaction if overlapping exists. Please add the same 'multi' option/capability to Modify interaction as in ol.interaction.Select.

**Comment by ahocevar** [comment]
If you set the features collection of ol.interaction.Modify to the one of an ol.interaction.Select, you can achieve the desired behavior:
```js
var select = new ol.interaction.Select({
  //...
});
var modify = new ol.interaction.Modify({
  features: select.getFeatures()
});

**Comment by AndreasTheMonkey** [comment]
Thank you. I tried the solution and it mostly works for my case. Seems like with this work-around the user has to first select the feature by clicking and only then drag the feature. If only Modify interaction is set, then user can immediately drag the feature without first selecting it by click, which is the behavior I'm looking for.

Is there a way to use your work-around such that the user could immediately start dragging without first having to select a feature?
