### ISSUE TITLE
Map gets disappear

### ISSUE THREAD

**Issue by vsdubey1309** [openlayers/ol3#3916]
I am using ol.Map to render the map in my application as:

var map = new ol.Map({
        controls: ol.control.defaults().extend([
            new ol.control.ScaleLine({
                //units: 'degrees'
            }), 
            new ol.control.MousePosition({
                coordinateFormat: ol.coordinate.createStringXY(4),
                className:'ol-mouse-position-custom'
            })
        ]),
        layers: layers,
        target: 'mapDivId',
        view: view
    });

    var zoomslider = new ol.control.ZoomSlider();
    map.addControl(zoomslider);

On some event, I want to zoom the map to some zoom level and set the center at some point. To do that I am using the code below:

var longitude = jsonResponse.longitude;
                var latitude = jsonResponse.latitude;
                var chainageLength = jsonResponse.chainageLength;

                if (longitude !== undefined && latitude !== undefined) {
                    if (chainageLength < 1000) {
                        map.getView().setZoom(16);
                    } else if (chainageLength >= 1000 && chainageLength < 2000) {
                        map.getView().setZoom(15);
                    } else if (chainageLength >= 2000 && chainageLength < 3500) {
                        map.getView().setZoom(14);
                    } else if (chainageLength >= 3500 && chainageLength < 6000) {
                        map.getView().setZoom(13);
                    } else if (chainageLength >= 6000) {
                        map.getView().setZoom(12);
                    }
                    var coord = [longitude, latitude];
                    map.getView().setCenter(coord);
                }

After executing this code, I map gets zoomed with the center point specified. However, when I want to Pan the map after this code gets executed, map gets disappeared.

Am I doing something wrong? Please help.

**Comment by oterral** [comment]
Provide a jsfiddle if you want faster answer or ask on [stackoverflow](http://stackoverflow.com/questions/tagged/openlayers-3)

First of all verify your `coord` variable contains value in meters (EPSG:3857) and not in degrees

**Comment by bartvde** [comment]
Lack of feedback so closing.
