### ISSUE TITLE
TMS with XYZ source

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#3923]
I have a tile source with a standard z/x/y url pattern, but with bottom-left 0/0, i.e. like TMS. This loads fine using a simple TileImage:
```
      source: new ol.source.TileImage({
        projection: 'EPSG:3035',
        tileGrid: new ol.tilegrid.TileGrid({
          extent: [2409891.715, 1328424.080, 6143417.136, 5330401.505],
          tileSize: [200, 200],
          origin: [2409891.715, 1328424.080],
          resolutions: [4000, 3000, 2000, 1000]
        }),
        tileUrlFunction: function(coordinate) {
          return 'http://map-loader.appspot.com/srtm3035/'+coordinate[0]+
              '/'+ coordinate[1] +'/'+ coordinate[2] +'.png';
        }
      })
```
The current docs for XYZ state "Layer source for tile data with URLs in a set XYZ format", which this is, so it ought to work with XYZ too, using the url pattern instead of tileUrlFunction. But it doesn't, whether using y or -y (I suspect the bitwise operator in createFromTemplate is causing the problem here). This is not necessarily a problem, as I can always use TileImage, but if XYZ can't handle some zxy sources, this should be documented.

I also think that the rather confusing area of tile origins needs to be better documented in the api docs, for example, that XYZ and WMTS grids are by default top-left, and that you use `-y` with XYZ for a bottom-left origin.

**Comment by ahocevar** [comment]
`-y - 1` should work. Also note that you don't need a `tileUrlFunction`. Just use the `{-y}` placeholder in the `url`.

**Comment by ahocevar** [comment]
Also you should leave out the origin from the tile grid configuration, or use the top left corner instead of the bottom left one.

**Comment by probins** [comment]
but how would `-y-1` be defined in the template? AFAICS there's only a regex for `y` and `-y`. The xyz-esri-4326-512 example uses both a template and a tileurlfunction, which seems over-complicated - easier to use TileImage directly, I would have thought

**Comment by ahocevar** [comment]
Yes, and {-y} in the template causes the -y-1 calculation. The ESRI example uses a tile Url function because there is a z offset.

**Comment by probins** [comment]
none of these work. Here a fiddle:
* http://jsfiddle.net/kk9af54m/ - origin set to top left, tries to fetch -ive y
* http://jsfiddle.net/kk9af54m/2/ - origin not set: same as /
* http://jsfiddle.net/kk9af54m/1/ - origin set to bottom left: better, but the bottom row of tiles, such as http://map-loader.appspot.com/srtm3035/0/0/0.png, aren't fetched
* http://jsfiddle.net/kk9af54m/3/ is how it should look, using TileImage/tileUrlFunction

**Comment by ahocevar** [comment]
You're right. I just looked at the code and saw that {-y} only works with a standard XYZ tile grid. Any suggestions for documentation improvements?

**Comment by probins** [comment]
if you like, we could add this source to the examples as an example of TMS. It was originally a tilecache layer, but I squashed the directories and renamed the files to make it a TMS pattern. I would just change the url to https as appspot now supports http/2 which should speed up loading of tiles

**Comment by ahocevar** [comment]
That would be a great addition to the examples collection. Thanks in advance!

**Comment by ahocevar** [comment]
Fixer with #3929.
