### ISSUE TITLE
Layer rendering fails on ImageWMS when ratio < 1

### ISSUE THREAD

**Issue by alvinlindstam** [openlayers/ol3#3926]
I don't know if setting a ratio less than one should be supported or why one would want it, but someone has problems when doing it: http://stackoverflow.com/questions/31611854/openlayers3-not-displaying-image

Example: http://jsfiddle.net/zL9jhgqf/ (set ratio to 1 or above, and it works).

Perhaps we should make it work, set some caps on the ratio (min/max) and/or document what's supported?

**Comment by ahocevar** [comment]
Using a ratio less than 1 does not make much sense. @alvinlindstam, would you mind creating a pull request with a documentation improvement?
