### ISSUE TITLE
Make ol.interaction.Modify listen to geometry change events

### ISSUE THREAD

**Issue by alvinlindstam** [openlayers/ol3#3927]
Currently, the Modify interactions does not listen to change events on it's geometries. Altering the geometry after it's loaded by the Modify interaction will make the geometry out of sync with the interactions segment cache.

Is there a reason not to listen to the geometries? The primary source of changes to the geometries will be the interaction itself, so we would need to ignore those or unlisten during the modification.

Is adding a reloadFeature method to the interaction a better option, so that application devs that manually change the features are also responsible for triggering the reloads?

Related example: http://jsfiddle.net/rbha7f83/1/ (I used an intermediate ol.Collection in order to force the Modify interaction to reload the geometry after setting it's coordinates).

**Comment by probins** [comment]
what's your use case here? ISTM this is an unusual situation, and the main 'reason not to listen to the geometries' is that it's unnecessary overhead for the usual situation where the user is the only 'source of changes'.

**Comment by elemoine** [comment]
I've come across the same issue when attempting to use a `Translate` interaction (https://github.com/openlayers/ol3/pull/4008) and a `Modify` interaction together.

**Comment by alvinlindstam** [comment]
The use case that prompted my post was testing to implement undo-functionality with the modify interaction (keeping track of the changes externally, and resetting the geometry to a previous state if requested by the user). It worked fine, but I had to remove and re-add the feature from the interaction for it to work properly. But when combined with a select interaction, that's difficult since you might not want to unselect a feature just to change it's geometry.

**Comment by elemoine** [comment]
@alvinlindstam, I am currently trying to modify the Modify interaction to make it listen to changes from the candidate features.

**Comment by elemoine** [comment]
This is my branch: https://github.com/openlayers/ol3/compare/openlayers:master...elemoine:update-segment-data. Would be good to know if that branch works for you.
