### ISSUE TITLE
ol.interaction.Modify not deleting edge vertices

### ISSUE THREAD

**Issue by Turbo87** [openlayers/ol3#3936]
`ol.interaction.Modify` is able to delete vertices from e.g. LineStrings, but it doesn't seem to be able to delete the "edge" vertices.

If I create a LineString `A -> B -> C` I am able to delete `B` but not `A` or `C`.

**Comment by probins** [comment]
see #3708

**Comment by Turbo87** [comment]
you're right. closing this one in favor of #3708
