### ISSUE TITLE
Issues with LineStrings crossing the antimeridian

### ISSUE THREAD

**Issue by sfischergit** [openlayers/ol3#3937]
When rendering a linestring that crosses the antimeridian OL3 will actually wrap the linestring all the way around the globe rather than have the linestring cross the antimeridian itself. I took a screen capture of this and put it here: http://i.imgur.com/5uvwdQT.jpg

**Comment by ahocevar** [comment]
Not a bug. How would OpenLayers know that you don't want your line rendered all the way around the globe? The common way to express features that cross the 180° meridian is to use coordinates that go beyond 180°, e.g. a line from 179° to 181°.

**Comment by sfischergit** [comment]
I see this as an issue because that's not how navigational coordinate systems work. When someone crosses the antimeridian the coordinates adjust back to zero and their reported locations would do the same.

If a point is added to the globe at 1°, 1° and it is repeated across the projection it would seem logical that linestrings would be handled in a similar manner, and indeed they are, except where it comes to a linestring crossing the antimeridian. The way around this that I see is calculating where a linestring crosses the antimeridian and breaking the linestring at that point and separating the rest into a separate linestring, which is an option programatically. The other option would be for OL to recognize where the antimeridian is crossed and change the coordinates to fit the projection at that time.

Since this is not a bug I will use the approach of simply splitting the linestring at the antimeridian, but I thought I would report it because I found the behavior confusing and did not know if it was working as intended.

Much appreciation to your reply.

**Comment by artursmirnov** [comment]
I would agree with @sfischergit. The current behaviour is confusing. And furthermore, because of this the app have to recalculate coordinates both ways all the time. And all the events have to take care of that approach. I would say it's a bug.

**Comment by ahocevar** [comment]
@sfischergit In a cartesian coordinate system, which is what OpenLayers (and every popular GIS software) uses, coordinates do not automagically change as you move along an axis. So I can only repeat that the current behaviour in OpenLayers is intended. As a counter-example let's say we have someone who wants to draw a line from 179 to -179 degrees, going all the way around the globe. That someone would be surprised if the line only went 2 degrees across the antimeridian.

**Comment by sfischergit** [comment]
@ahocevar I understand how the underlying coordinate system works, my initial frustration was with the difficulty of dealing with situations in which items wrap around the globe and have altered my implementation. It's even more complicated when dealing with Polygons.

However, perhaps a suggestion to ease future individuals struggles with this is to implement a flag in the LineString class that would have the LineString instead seek the shortest path by distance between the two points plotted, adjusting to the coordinate system as necessary. Your argument is an accurate and legitimate portrayal of one use case, but your argument does not necessarily negate the validity of that use case. I realize though, that implementing this in the coordinate system that exists in the GIS system is actually much more difficult than it seems, which is why I was satisfied when you declared it to not be a bug, but to be working as intended. Sometimes people who are implementing library need to be flexible with their approach.

**Comment by kneczaj** [comment]
@ahocevar a solution to your case it to have a directed line strings - the ones where the order of points is stated. I guess this is already there because you keep data in an array, and an array is ordered.

My proposition for your case is:
[[0, -179], [0, 179]] is the line going around the globe
[[0, 179], [0, -179]] is this 2 degrees line which you mention

I guess all guys already use it this way, but they need to put additional points inside the second case of 2 deg long line.

I wouldn't also say that the map uses cartesian coordinate system. The map uses spherical coordinate system of the globe, and cartesian system is just its projection on a flat surface :).
