### ISSUE TITLE
ol.source.TileJSON should include a opt_errorCallback argument

### ISSUE THREAD

**Issue by matiascelasco** [openlayers/ol3#3938]
When creaiting a new ol.source.TileJSON object, it may happen that the requests fails and I would like to detect this situation in order to inform the user properly. I checked the code of the constructor and I noticed the following.

    ol.source.TileJSON = function(options) {

      goog.base(this, {
        crossOrigin: options.crossOrigin,
        projection: ol.proj.get('EPSG:3857'),
        state: ol.source.State.LOADING,
        tileLoadFunction: options.tileLoadFunction
      });

      var request = new goog.net.Jsonp(options.url);
      request.send(undefined, goog.bind(this.handleTileJSONResponse, this));

    };
    goog.inherits(ol.source.TileJSON, ol.source.TileImage);

When the send method of the goog.net.Jsonp instance request is called, nothing is passed as the third parameter, which is named opt_errorCallback. It would be great to me to have a opt_errorCallback as one of the possible options for ol.source.TileJSON. The resulting code would be something like this:

    ol.source.TileJSON = function(options) {

      ...

      var request = new goog.net.Jsonp(options.url);
      request.send(undefined, 
                            goog.bind(this.handleTileJSONResponse, this),
                            options.opt_errorCallback);

    };
    goog.inherits(ol.source.TileJSON, ol.source.TileImage);

**Comment by ahocevar** [comment]
You can listen to the change event of the source. Then, when the state returned by getState() is 'error', you know that something went wrong. Does that work for you?

**Comment by matiascelasco** [comment]
No. When this error occurs the state doesn't change and remains as 'loading'. Maybe the problem is that the problem I want to detect is net::ERR_INSECURE_RESPONSE.

However if I pass a callback as a third argument to request.send, like here:

    request.send(undefined, goog.bind(this.handleTileJSONResponse, this), function(a, b, c){
        console.log("something wrong happened");
      });

'something wrong happened' gets logged into the console in the moment net::ERR_INSECURE_RESPONSE occurs

**Comment by ahocevar** [comment]
So the bug is that no error state is set when this happens. Would you be able to create a pull request? Should be as easy as replacing `console.log("something wrong happened");` with `this.setState(ol.source.State.ERROR);` in your snippet above.

**Comment by matiascelasco** [comment]
Great! Thank you very much! Sorry for not being able to fix it and create a pull request myself
