### ISSUE TITLE
Compiling custom controls with Google Closure

### ISSUE THREAD

**Issue by drupol** [openlayers/ol3#3943]
Hello,

I learned how to write [custom controls](https://github.com/drupol/openlayers/blob/openlayers-geofield-new-control/modules/openlayers_geofield/src/Plugin/Control/Geofield/js/geofieldControl.js) last week by reading the code of the different control available on the ol3 repository. The target of these controls are for the Drupal module of Openlayers.

You can find the code in my repository [PR #17](https://github.com/drupol/openlayers/pull/17).

I was quite surprised to notice that my controls were not working when I'm not using the debug version of the library. ([Source of the control](https://github.com/drupol/openlayers/blob/openlayers-geofield-new-control/modules/openlayers_geofield/src/Plugin/Control/Geofield/js/geofieldControl.js))
As I'm not very at ease with JS and Closure, I asked Google and learned that I had to compile the code.

I followed the tutorial to setup Closure and tried to compile my control:

```
pol@x230 ~/closure-compiler $ java -jar compiler.jar --js geofieldControl.js --js /home/pol/git/drupal7/sites/all/libraries/openlayers3/ol/ol/control/control.js --js '/home/pol/git/drupal7/sites/all/libraries/openlayers3/closure-library/closure/goog/**.js' --manage_closure_dependencies true
/home/pol/git/drupal7/sites/all/libraries/openlayers3/closure-library/closure/goog/net/xpc/crosspagechannel.js:25: ERROR - required "goog.async.Deferred" namespace never provided
goog.require('goog.async.Deferred');
^

/home/pol/git/drupal7/sites/all/libraries/openlayers3/closure-library/closure/goog/net/xpc/directtransport.js:25: ERROR - required "goog.async.Deferred" namespace never provided
goog.require('goog.async.Deferred');
^

/home/pol/git/drupal7/sites/all/libraries/openlayers3/closure-library/closure/goog/net/xpc/nativemessagingtransport.js:26: ERROR - required "goog.async.Deferred" namespace never provided
goog.require('goog.async.Deferred');
```

This was not working so I tried:

```
java -jar compiler.jar --js geofieldControl.js --js /home/pol/git/drupal7/sites/all/libraries/openlayers3/ol/ol/control/control.js --js '/home/pol/git/drupal7/sites/all/libraries/openlayers3/closure-library/closure/goog/**.js' --js '/home/pol/git/drupal7/sites/all/libraries/openlayers3/closure-library/third_party/**.js'  --manage_closure_dependencies true
```

This seems to be working but the output is huge. I suppose that I'm including too much file ? How to only include the files I need and their dependencies ?

My questions are:

* How to ease the development of custom controls/interactions using Google Closure for newcomers ?
* Should I "convert" the controls to regular JS ? I did it [here](https://github.com/drupol/openlayers/commit/54d53458a128dd97c05257bc2c333a2d4a857804) but I would prefer to use Google Closure for the other one, much bigger.

**Comment by probins** [comment]
why do you want to use the Closure library? This is indeed very large, and makes little sense if all you're doing is creating something small like a control. The api docs http://openlayers.org/en/master/apidoc/ol.control.Control.html give an example of creating a custom control. As this says, the only real advantage of using an ol.control is handling event propagation (plus it keeps the divs all in one place).

**Comment by drupol** [comment]
Ok, I will use regular JS then. Indeed the event management is great and some stuff like:

```
  goog.array.forEach(goog.dom.getChildren(goog.dom.getElementByClass('draw', this.element)), function(e, i, a) {
    if (e != event.target) {
      goog.dom.classlist.remove(e, 'enable');
    }
  });
  goog.dom.classlist.toggle(event.target, 'enable');
```

Are really handy. I have to find how to write those things using regular JS.

**Comment by drupol** [comment]
I figured out to convert most of the code but there's still something I'm unable to do.

In the control I was using:

```
options.set('options', options);
```

And in another script I was using:

```
instance_of_the_custom_control.on('change:options', function() {

});
```

How to convert that in regular JS ?

**Comment by probins** [comment]
not sure I understand. What is `options`? If it's an `ol.Object`, you can set any property on it and a change event will be triggered. If not, you can't.

I think this sort of discussion belongs on Stackoverflow, not in Github issues.

**Comment by drupol** [comment]
Ok, let's close this.

**Comment by jonataswalker** [comment]
I've written a small extension ([Geocoder Control](https://github.com/jonataswalker/ol3-geocoder)) and you can see if it helps. It's plain javascript.
