### ISSUE TITLE
Popups always appear in originating worldview when data wraps dateline

### ISSUE THREAD

**Issue by gwacker** [openlayers/ol3#3944]
http://openlayers.org/en/v3.7.0/examples/icon.html

Zoom out and click on an icon that has wrapped the dateline (not the original). The popup always centers over the original feature. Is that an issue with the library or is there a better way to write that code?

I'm sure the introduction of canvas and WebGL rendering has upped the complexity for determining feature interaction and clicks events, but unfortunately that complexity is very visible in the code (see icon example above) to implement a common task of creating a hover and click event for a feature in version 3 over version 2. Is there any plan to roll that into a higher level function to make popup creation easier moving forward?

**Comment by ahocevar** [comment]
See #3945. Showing the popup where the user clicks actually simplifies the example. But there are no plans to make popups part of the library.

**Comment by gwacker** [comment]
So, what about the issue where clicking an object that has wrapped initializes a popup over the object's original location (not the wrapped location that was clicked)?

http://i.imgur.com/gobkXRe.png

It gets particularly confusing when you navigate to a wrapped part of the world, zoomed in to where the original point(s) are out of view, thus causing the popup to be out of view.
