### ISSUE TITLE
forEachFeatureInExtent doesn't list matching features

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#3948]
Please navigate to the simplified test case http://drifted.in/other/ol/extent/vector_tiles_extent.html
There is a vector tile containing a feature which extent is smaller than a view extent. Both extents are logged in the console (rounded here):

`viewExtent: 1360000, 6400000,1750000,6600000`
`features[0].getGeometry().getExtent(): 1550000,6450000,1570000,6570000`

If the given feature is in the extent, it should be logged once again using this code (BUT isn't):
```javascript
source.forEachFeatureInExtent(viewExtent, function (feature) {
    console.log("id: " + feature.getId());
});
```

I am not sure if this method is supposed to do what I expect (to return the list of features inside the given extent), as there is the word 'intersects' in the method description, which slightly confuses me - http://openlayers.org/en/v3.7.0/apidoc/ol.source.Vector.html

> Iterate through all features whose bounding box intersects the provided extent (note that the feature's geometry may not intersect the extent), calling the callback with each feature. If the callback returns a "truthy" value, iteration will stop and the function will return the same value.

**Comment by jonataswalker** [comment]
Maybe this not merged PR (https://github.com/openlayers/ol3/pull/3761) is related.

**Comment by jan-tosovsky-cz** [comment]
Btw, I found the following workaround...
```javascript
var features = vectorLayer.getSource().getFeatures();

for (var i in features) {
   var feature = features[i];
   if (ol.extent.containsExtent(viewExtent, feature.getGeometry().getExtent())) {                        
      console.log("id: " + feature.getId());
   }
}
```

**Comment by alvinlindstam** [comment]
Taking a look at the source of the TileVector source, it appears that the following api methods are not even implemented (defined as goog.abstractMethod):

* addFeature(feature)
* addFeatures(features)
* forEachFeature(callback, opt_this)
* forEachFeatureInExtent(extent, callback, opt_this)
* getClosestFeatureToCoordinate(coordinate)
* getExtent()
* getFeaturesInExtent(extent)
* removeFeature(feature)

On top of this, the following inherited api methods will probably not work:

* forEachFeatureIntersectingExtent(extent, callback, opt_this) - uses forEachFeatureInExtent
* getFeatureById(id) - uses idIndex_, which is not used by the TileVector source
* getFeaturesAtCoordinate(coordinate) - uses forEachFeatureInExtent

**Comment by jan-tosovsky-cz** [comment]
alvinlindstam, thanks for the analysis. Is there any plan to implement those missing methods?

**Comment by ahocevar** [comment]
Note that ol.source.TileVector is likely to go away in favour of ol.source.VectorTile. See #4219. Resolution bound vector features are not meant for geospatial analysis, but for rendering. Having said that, I'm not sure how much of the suggestions here really make sense.

**Comment by jan-tosovsky-cz** [comment]
ahocevar, thanks for update! After reading the commit summary of the linked issue I am just worried some handy features are dropped in the name of speed optimization...
My vector tiles contains features which needs to be reiterated as new tiles enter/leave the vieport. During this iteration specific values are calculated and used outside the map application, see the code in my comment from 3 Aug. Is something like this still possible?

**Comment by ahocevar** [comment]
@jan-tosovsky-cz It would be interesting to know more about your use case. ol.source.VectorTile organises features in tiles and a tile grid.This might work even better for you.

**Comment by jan-tosovsky-cz** [comment]
@ahocevar it is kind of statistics over the selected area (extent). Imagine e.g. determining the min/max value of tiled vector isosurfaces (polygons). These values need to be updated together with updates (size changes) of the given area (which doesn't necessarily equals to the tile area). My current approach is to iterate all polygons (features) in the layer source, checking if they are in the extent and if so, retrieve the layer id. That 'id' curently represents the desired 'variable', which is then used for determining min/max values.

**Comment by ahocevar** [comment]
@jan-tosovsky-cz I'm failing to understand why this is resolution dependant. A plain ol.source.Vector would be better suited for such a use case IMHO.

**Comment by jan-tosovsky-cz** [comment]
@ahocevar I understand your point. Isosurfaces for each level in my case have a different 'step'. The higher resolution the higher level of detail. If the original value is e.g. 615, the 'max' level is:
| Step | Max  |
| ----:| ---: |
| 1000 | 1000 |
|  500 | 1000 |
|  100 |  700 |
|   50 |  650 |
|   10 |  620 |

These data covers quite large area so it would be inefficient to load all the features in the highest level of detail into the Vector source.

For me, any iteration of all the tile features (polygons) which are even partially shown within the extent is sufficient :-)

**Comment by jan-tosovsky-cz** [comment]
As TileVector was removed from API, this issue can be closed.

**Comment by raulromano** [comment]
Hi, Everyone.
I still have the same problem. Through the API methods, provided in the documentation, I can't identify which coordinates (latitude and longitude) are selected in the dragbox.
Can someone help me?
