### ISSUE TITLE
Option to specify precision of coordinate values on format write

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#3953]
A common floating-point arithmetic issue, when reading in 4326 coordinates to a projected view and then writing them back out in 4326:

value in: 45.460979
value out: 45.46097900000001

or

value in: 45.453625
value out: 45.45362499999999

On large geometries, this significantly increases the size of the output for no added value. How to improve this? Have a 'round to decimal places' option for transforms? In this case, for example, specify 6 places on output/write.

**Comment by tschaub** [comment]
I think you mean that you would like to specify a precision when serializing geometries.  This would be an option to the write methods of a format.  This isn't strictly about transform methods.

**Comment by probins** [comment]
yes, I've changed the issue title, as I've just come across a related issue when drawing. Drawing on OSM, for example, coordinate stored as [66041.59243839228, 5230127.223384898], which is a ridiculous level of precision for metre projections, but probably doesn't matter internally. Gets output in 4326 as [0.59326171875, 42.45994035221656], which is also spuriously precise, and in this case does matter as it bloats the size of the file unnecessarily. 6 decimal places should be ample for most apps.

**Comment by probins** [comment]
Another example: incoming and outgoing geometries and view in 4326. Move a coordinate; new position is [11.120000000000001, 44.77]; presumably this is coming from the pixel->coordinate calculation and has nothing to do with transform.

If the incoming and outgoing geometries and the view are in the same projection, there is no transform and unmodified geometries are output as input. If not, then even if the only change is to an attribute the outgoing coordinates will not be the same as the input. IIRC OL2 had an option to store the incoming data, so if the only edit is to attributes, you could output unchanged geometries from there. To do this in OL3, you would have to fetch and store the file in the app.

Looking around the web for a solution, `parseFloat(45.45362499999999.toPrecision(8))` or `parseFloat(11.120000000001.toPrecision(8))` seems to do the trick. '8' is the maximum precision wanted, and `parseFloat` removes trailing zeroes.

**Comment by probins** [comment]
where would be the best place to add this? After looking at the code, I'm thinking that it would be best to include this in `ol.format.Feature.transformWithOptions`: if the precision option is set, `parseFloat` on each transformed coordinate before returning the geometry.

**Comment by probins** [comment]
I've just noticed there's a similar issue with other output fields. KML has a scale output, and this can be output for example as '0.6400000000000001'. Not sure what others there might be; anything stored as a float, I suppose.

**Comment by ahocevar** [comment]
`ol.format.Feature#writeGeometry()` would be the best place to make such a change. Especially if you don't just want to cover transformed, but also drawn geometries.

**Comment by probins** [comment]
but if you're just writing a geometry (as you can with GeoJSON), `ol.format.Feature#writeGeometry()` isn't used, is it? All the formats call `ol.format.Feature#transformWithOptions()`, and the coords need truncating after being transformed but before being output, so I was thinking that instead of returning directly the transform would write to an interim var, then truncate and return that.

An extra complication is that the loop to update the coordinates will differ for each geometry type as they have different array depths.

**Comment by ahocevar** [comment]
> All the formats call ol.format.Feature#transformWithOptions(), and the coords need truncating after being transformed but before being output

Valid point. Maybe the function should be renamed then.

> An extra complication is that the loop to update the coordinates will differ for each geometry type as they have different array depths.

You can use truncate all values in the `flatCoordinates_` array.

**Comment by probins** [comment]
WIP at https://github.com/openlayers/ol3/compare/master...probins:decimals. This is not ready for a PR yet; I've done some preliminary tests with my own software but I don't use multi-geometries or GeometryCollections. It does however compile (Travis approves), and something along these lines is what I'm thinking of. It would be good to have some feedback.

An alternative to renaming the function would be to put this new logic in its own function and have `transformWithOptions()` call it.

I think some tests need adding, but am not sure what. It would be a lot of work to test the new option with each geometry type in every format that writes. Add some for GeoJSON and one of the XML formats, and assume the rest work the same? I notice that the last test in `geojsonformat.test.js` does a 'roughlyequal' test, presumably because of float arithmetic issues. With this new option set, the output should be exactly equal, and that would be an obvious test to add.
