### ISSUE TITLE
ol.source.ImageWMS gets stuck loading image for certain extents

### ISSUE THREAD

**Issue by rattai** [openlayers/ol3#3963]
The `getImage` function checks if the source already has an image to respond with.  This includes an extent comparison.
https://github.com/openlayers/ol3/blob/f5cd9a3ebac748d248e04b30688db447435d23ab/src/ol/source/imagewmssource.js#L206

However, this extent comparison incorrectly compares the image.getExtent() with the raw extent requested.  Instead it should compare the image.getExtent() with an "image extent" computed from the raw extent.  "Image extents" are adjusted to allow for integer pixel heights/widths.

For certain extents, the extent comparison will never pass and renderring of the ImageWMS will end up in an infinite loop....repeatedly creating new ol.Image instances that never finish loading.

**Comment by ahocevar** [comment]
Should be fixed with #3933. @rattai, can you please verify?

**Comment by ahocevar** [comment]
To improve the pull request, you could also cache the image extent, e.g. as `imageExtent_` member, instead of calculating it with every getImage call.
