### ISSUE TITLE
Support for icon fonts (like FontAwseome) in ol.style.Icon

### ISSUE THREAD

**Issue by mfilotto** [openlayers/ol3#3965]
Hi,
Would be nice if ol.style.Icon was icon fonts friendly.
Thanks

**Comment by gbassiere** [comment]
Have you tried [ol.style.Text](http://openlayers.org/en/v3.7.0/apidoc/ol.style.Text.html)?
Have a look at this [example on SO](http://stackoverflow.com/questions/27809479/use-semantic-ui-or-font-awesome-icons-as-markers-in-openlayers3).

**Comment by mfilotto** [comment]
Yes we already use this, but it's not as felxible as pointing to the class font.

**Comment by mfilotto** [comment]
@gbassiere thanks for your answer
