### ISSUE TITLE
ol.Feature.setGeometryName

### ISSUE THREAD

**Issue by FreeGIS** [openlayers/ol3#3966]
I have  a Feature which default geometry name is 'geometry',when i used 'drawfeature.setGeometryName('geom')',the values_ still  keep 'geometry'. i think it is  a bug because when i used 'var pFeature=new ol.Feature({...}),pFeature.setGeometryName('geom');pFeature.setGeometry(pgeom)' is right.The values_   has a property which name is 'geom'.

so,i find use setGeometryName can not change the property of geometry in values_ ,but  new a feature can change

**Comment by ahocevar** [comment]
ol.interaction.Draw has a geometryName property, which you should set to 'geom'.

The behavior you are seeing is not a bug. setGeometryName on a feature only sets a pointer to the property that holds the main geometry, it does not change property names.
