### ISSUE TITLE
Unable to get value of the property 'call' in IE 9.0.8112

### ISSUE THREAD

**Issue by gsommerw** [openlayers/ol3#3967]
In an application using OpenLayers 3.7.0, I get the following error, only when using IE 9:

Unable to get value of the property 'call': object is null or undefined
ol.js, line 231 character 782

After this I get 'ol' is undefined, so it seems, that this happens while loading ol.js.
This does not happen, when using ol-debug.js!

**Comment by elemoine** [comment]
More context is required. Do you have a test case/example demonstrating the problem?

**Comment by gsommerw** [comment]
I created the following JSFiddle:

https://jsfiddle.net/uz899z5j/9/

**Comment by ahocevar** [comment]
Try to add a `<!DOCTYPE html>` header to your HTML page.

**Comment by gsommerw** [comment]
There is already <!DOCTYPE html> in my original code. But I added it to http://www.basemap.at/applicationt/ol3test.html too

**Comment by gsommerw** [comment]
This is strange, as yesterday I had another problem, before the capabilities were accessed, which can not be reproduced anymore with http://www.basemap.at/applicationt/ol3test.html:

Unable to get value of the property 'call': object is null or undefined
ol.js, line 231 character 782

and

'ol' is undefined

in the statement 

var gg = ol.proj.get('EPSG:4326');

This only happened in ol.js, but not in ol-debug.js.I can still reproduce it, if I run ol3test.html locally, hosted on IIS, but it depends, how I write the base URL (localhost:8080 works, server.magwien.gv.at:8080 cannot access the capabilities (the same as with the public URL) and server:8080 still reproduces the error above.

But as I can not show You using a public URL, please close the issue.

I changed the base URL of Capabilties to the same domain and it works now, at least in production.

**Comment by gsommerw** [comment]
But if IE 9 does not support CORS headers at all, why do I get the map tiles?

**Comment by bartvde** [comment]
images can be loaded from different domains, there is no same origin policy for mg.src

**Comment by gsommerw** [comment]
OK, thank You.
