### ISSUE TITLE
Options created with ol.source.WMTS.optionsFromCapabilities ignore attributions setting

### ISSUE THREAD

**Issue by gsommerw** [openlayers/ol3#3976]
When I try to set attributions like this, the setting is ignored:
    
    var bmapOptions = ol.source.WMTS.optionsFromCapabilities(
        capabilities,
        {
            layer: 'geolandbasemap',
            requestEncoding: 'REST',
            attributions: [
                new ol.Attribution({
                    html: 'Tiles &copy; <a href="//www.basemap.at/">' +
                        'basemap.at</a> (STANDARD).'
                })
            ]
        });

I have to do it this way:

    var bmapOptions = ol.source.WMTS.optionsFromCapabilities(
        capabilities,
        {
            layer: 'geolandbasemap',
            requestEncoding: 'REST'
        });

    bmapOptions.attributions = [
        new ol.Attribution({
            html: 'Tiles &copy; <a href="//www.basemap.at/">' +
                'basemap.at</a> (STANDARD).'
        })
    ];

You can reproduce this with http://www.basemap.at/applicationt/ol3test.html

**Comment by ahocevar** [comment]
Not a bug. `attributions` is not a valid option in the `config` object for `ol.source.WMTS.optionsFromCapabilities()`. However, `ol.source.WMTS.optionsFromCapabilities()` has room for improvements. This is already ticketed, see #3874.
