### ISSUE TITLE
ol.Object no longer expose dispatchEvent() method in release version since v3.8.X

### ISSUE THREAD

**Issue by kulmegil** [openlayers/ol3#3994]
ol.Object no longer exposes dispatchEvent() - something I relied until 3.7.0 even though it was undocumented. This makes extending ol.* classes even harder then it already was - without closure compiling app along with library.

ps It would be nice if ol.interaction.Interaction could expose it's getMap() method as well.

**Comment by marlowp** [comment]
+1 It seems strange to restrict the ability for classes that extend the ol.Object class from dispatching their own events. At present the workaround seems to be to register a property on the object and watch for changes on that. This doesn't feel right though and essentially means you are creating properties on the object just to fire events.

**Comment by elemoine** [comment]
Have you been able to determine the PR/commit that removed the exposition of the `dispatchEvent` function? I am not fully sure but I don't think OpenLayers has ever exposed that function.

**Comment by bartvde** [comment]
I have heard similar reports from @volaya that with 3.8 dispatchEvent('change') did not work anymore for him. I pointed out it's not in our API docs, also not for earlier releases. But somehow it worked before apparently.

**Comment by elemoine** [comment]
So it's probably related to the Closure Compiler. I guess that, with previous versions of the compiler, `dispatchEvent` was not renamed by the compiler. So that function was exposed "by chance".

**Comment by elemoine** [comment]
`object.changed()` can be used to dispatch a "change" event, but I don't know if that address people's use-cases…

**Comment by bartvde** [comment]
Right that's also what @volaya used for his case. I agree with the chance option.

**Comment by elemoine** [comment]
@kulmegil, @marlowp, would `changed()` work for you? Or do you need to dispatch events with specific names (e.g. `dispatchEvent('myevent')`)?

**Comment by jonataswalker** [comment]
In the case @marlowp raised (http://gis.stackexchange.com/q/159419/50718), it's an extended `ol.control.Control` so events can be managed with something like:

```javascript
var Geocoder = function(opt_options){
    'use strict';
    //....
    ol.control.Control.call(this, {
        element: container
    });
    //set event to be captured with 'change:geocoder'
    this.set('geocoder', '');
};

ol.inherits(Geocoder, ol.control.Control);

Geocoder.prototype.makeSomething = function(){
    //dispatchEvent
    this.set('geocoder', Math.random());
};
```
Listen on app:
```javascript
var geocoder = new Geocoder();
map.addControl(geocoder);

geocoder.on('change:geocoder', function(evt){
    //...
});
```

**Comment by marlowp** [comment]
@jonataswalker is correct, that is how I'm now firing events in my application at present. However the added overhead with this method is that I have to create a property on the object to fire/listen to events on. Whereas the ability to trigger an event using dispatchEvent(<event_name>) seems to me to be a cleaner approach.

It also means when creating our own custom controls that extend OL controls we can manage events in the same way as the OL controls do.

**Comment by marlowp** [comment]
@elemoine in my case I'd like to be able to dispatch events with specific names. This seems like the cleanest approach to me... however I stand ready to be corrected if it is not.

**Comment by kulmegil** [comment]
@elemoine 
late reply, but I'm finally on my vacation and away from the code and stuff.

I rely a lot on custom events and event data as well (coordinates, affected feature, ect) so this won't do for me.

**Comment by Chris-Dixon** [comment]
I also rely on custom events and event data so I need dispatchEvent to be available. It is a public method on goog.events.EventTarget that ol.Object inhertis from, so I would have expected it to be available.
