### ISSUE TITLE
Inclusion of Apache 2.0 prevents use with GPLv2 code

### ISSUE THREAD

**Issue by mstenta** [openlayers/ol3#3996]
Openlayers itself is licensed under 2-clause BSD, which is fully compatible with the GPLv2 license. However, the repository includes a few pieces of code licensed under Apache 2.0, which is NOT compatible with GPLv2 (it is compatible with v3 however).

Over on drupal.org, we are currently struggling with this fact, because all software hosted on drupal.org must be packaged as GPLv2 (this is an issue in itself, and there is work being done to change this, but very slowly).  Here is the issue for cross-reference: https://www.drupal.org/node/1442460

Would you consider removing the code that is Apache 2.0 licensed, to make Openlayers available for use with the GPLv2?

I ran a grep of the repo, and it seems there there are only 3 places that reference Apache2 (but really only 2):

* Prettify.js (in config/jsdoc/api/template/static/scripts/prettify)
* externs/jquery-1.9.js (something to do with Closure?)
* Bootstrap js and css (but this is actually outdated - Bootstrap uses MIT now)

It's worth noting that the Bootstrap library went through a similar transition - but in their case they changed their entire license from Apache 2 to MIT (https://github.com/twbs/bootstrap/issues/2054).  That was a much bigger project, of course, because it was their entire codebase. In the case of Openlayers, it's just those two mentioned places.

Is this possible?  I don't know what Prettify is being used for, nor extern/jquery-1.9.js.  Can someone educate me?  I will be happy to help with a pull request if this is doable.

**Comment by ahocevar** [comment]
OpenLayers is not licensed under the MIT license, but under a 2-clause BSD license.

Neither Prettify.js, nor JQuery or Bootstrap are included in the code. Prettify.js is used for the API doc generation (and part of JSDoc), JQuery and Bootstrap are used in the examples and the web site only.

**Comment by mstenta** [comment]
Oh sorry, I knew it was 2-clause BSD, not sure why my brain got stuck on MIT - maybe from Bootstrap. I will update the main description.

The problem we're running into on drupal.org is that our packaging system downloads the entire Git repository of the library, which includes the incompatible licenses. So simply having them in the repository is a deal breaker.

In the Openlayers Drupal module (http://drupal.org/project/openlayers), we are working on a workaround that loads the ol.js from a CDN instead. But I figured I would start a thread about the Apache 2 licensed code to see if it was worth removing them.

**Comment by ahocevar** [comment]
Why don't you simply download/package the official distribution archive, e.g. https://github.com/openlayers/ol3/releases/download/v3.8.2/v3.8.2-dist.zip ?

**Comment by mstenta** [comment]
Ah that would work! I didn't know that was an option! Thanks! I updated the issue on drupal.org accordingly: https://www.drupal.org/node/1442460#comment-10272559

Thanks again, I'll close this issue.
