### ISSUE TITLE
Shift + Click + MouseMove

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [openlayers/ol3#3997]
When rotation is enabled Shift + Click + MouseMove will rotate the image. The problem is that this combination is already used to define a zoom in extent when rotation is not enabled. 

I have multiple OL instances on my site, some with rotation, others without. It might be confusing for the users if the same gesture produce different results or if the zooming gesture is obstructed by the rotate one.

I have two questions:
1. would it be possible to modify the default gesture for one of those two operations (zoom in or rotate)? For instance using Ctrl + Click + MouseMove (if possible) to rotate.
2. is there a way with the current API to customise the gesture to rotate so I can offer users something else than Shit + Click + MouseMove for rotation?

Thanks

**Comment by ahocevar** [comment]
Yes, there is an API. You can configure the `condition` for all interactions. See e.g. http://openlayers.org/en/v3.8.2/apidoc/ol.interaction.DragRotate.html.
