### ISSUE TITLE
404 for marker icons

### ISSUE THREAD

**Issue by entrepreneurj** [openlayers/ol3#4004]
I've been trying to use markers on an embedded version of OpenLayers on my website, however the images for the markers I've tried (http://www.openlayers.org/dev/img/marker.png, http://openlayers.org/dev/img/marker-gold.png) return a 404. Have the marker images been moved?

**Comment by ahocevar** [comment]
When we created the website for OpenLayers 3, we changed the website structure. The new url is http://dev.openlayers.org/img/marker.png. However, you should not be relying on such deep links. It is better to host your own instead.
