### ISSUE TITLE
TileWMS and vector layer are not aligned properly

### ISSUE THREAD

**Issue by lavoiej** [openlayers/ol3#4005]
I am trying to upgrade ol3 from version 3.6.0 to 3.7.0, but without changing any code, my wms layer and my vector layer are not aligned properly (see pictures). 

Good alignment: 
![good](https://cloud.githubusercontent.com/assets/1693044/9293696/9f741770-4402-11e5-86b7-760ae3a4008d.jpg)

Bad alignment:
![bad](https://cloud.githubusercontent.com/assets/1693044/9293693/91abc8d6-4402-11e5-916d-3363064ee9e1.jpg)

When I am at max zoom, everything is fine, but when I start to zoom out, the wms and vector layer start to misalign. The more I zoom out, the worse it gets.

If I remove TILED=true to my WMS layer, everything is fine.

Any ideas on what's happening ?

* This only happens in version above 3.6.0

**Comment by ahocevar** [comment]
Can you share your code, e.g. using a [JSFiddle](http://jsfiddle.net)?

**Comment by marcjansen** [comment]
Guessing, but look at the headers of an image when you request them with tiled:true. And then compare the requested bou ds with thise from the header. A fiddle would nonetheless be helpful.

**Comment by lavoiej** [comment]
I found the problem while doing the JSFiddle...

The problem was that I was using a different extent from epsg.io for my projection.

I don't know if it should still be considered as a bug, because it was working in version 3.6.0.
I can share a JSFiddle later if you guys still want to investigate the issue.

**Comment by ahocevar** [comment]
Tile grid definitions based on extents were seriously broken before 3.7.0, so I guess what you're observing is the result of a bugfix, not a bug. But feel free to share the Fiddle if you want us to take a look.

**Comment by lavoiej** [comment]
Thank you for the quick answer! I guess you can close the issue.
