### ISSUE TITLE
Area calculation not proper while drawing a polygon intersecting it's own shape

### ISSUE THREAD

**Issue by aashirwadgupta** [openlayers/ol3#4009]
I was trying to draw and measure area of a polygon using openlayer3, It gave correct values for proper figures in which line continuation didn't intersect. 
But when I draw a figure in which line continuation did intersect the area was coming as subtraction of the two areas. 
Please find the images for more clarity
Image 1 - Here the figure has been drawn in a continuation pattern
![error in area for intersection figure](https://cloud.githubusercontent.com/assets/12935036/9329798/fcd95956-45f7-11e5-8412-978698437f1c.JPG)
Image 2 - A simple triangle is drawn which has more area then the previous figure as mentioned in image 1
![proper area for regular figure](https://cloud.githubusercontent.com/assets/12935036/9329808/242081d8-45f8-11e5-8364-21aa7461ff6d.JPG)

**Comment by bartvde** [comment]
Wrong issue tracker should be https://github.com/openlayers/openlayers instead

**Comment by aashirwadgupta** [comment]
Thanks for the proper link. :)
