### ISSUE TITLE
Area calculation not proper while drawing a polygon intersecting it's own shape

### ISSUE THREAD

**Issue by aashirwadgupta** [openlayers/ol3#4010]
I was trying to draw and measure area of a polygon using Openlayers v3.7.0, It gave correct values for proper figures in which line continuation didn't intersect. 
But when I draw a figure in which line continuation did intersect the total area was coming as subtraction of the two figures which forms as a result of line intersection. 
Please refer the image below for more details.
![open layer 3 polygon areas issue](https://cloud.githubusercontent.com/assets/12935036/9330208/145eb8f2-45fb-11e5-8999-0c08d53d6ffd.JPG)

**Comment by ahocevar** [comment]
Although OpenLayers does not enforce topology rules, a topology rule for proper area calculation of polygons is that none of the polygon's ring segments do not intersect.

**Comment by aashirwadgupta** [comment]
Thanks Andreas Hocevar for the info.
