### ISSUE TITLE
Will OL 4 change OL 3 api?

### ISSUE THREAD

**Issue by robertobsc** [openlayers/ol3#4020]
Hi guys, sorry to open a ticket here, but i wasnt sure where i should do it. 

I am developing a big software using OpenLayers 2.13.1. I am estimating the cost of migrating it to 3.8.2 version, but it seems that version 4 is right around the corner, and i am concerned if it will change all the api again.

Can you guys tell me about it?

Thanks very much.

**Comment by bartvde** [comment]
Version 4 is not around the corner, hasn't even been discussed.

**Comment by robertobsc** [comment]
Hi @bartvde !!

I said that because of the version 3.**8**, sorry about that. But do you have any prevision about changing the api? Like I said, it will be a huge cost for us and my concern is to have a double effort.

**Comment by bartvde** [comment]
For 3.X we have the policy that we can change the non stable (experimental) parts of the API. Anything marked as stable we cannot change.
I'd say it's pretty safe to upgrade now from 2 to 3.

**Comment by robertobsc** [comment]
Many thanks to your awnser. Closing the issue.
