### ISSUE TITLE
ol2 to ol3 with google maps

### ISSUE THREAD

**Issue by robertobsc** [openlayers/ol3#4021]
Again, sorry if i am asking here, but is the place that i thought is correct. If I am wrong please put me in the right direction.
I know a lot have been spoke about google maps and ol3 compability. But i have a little different question to ask about it.

The problem is that our system is in production and already has integration between ol**2** and google maps. I was just starting migrating to ol3 and it seemed (by looking at forums) that it has more compatibility problems with gmaps than ol2 had, but i saw that is still possible.

The requirement for my system is to support gmap and other base layers, so i cant use google maps api.

So my question is: can i migrate to ol3 with google maps? Or will i have so many problems that it is not worth it? It is better to stay at ol2?

Thanks!

**Comment by bartvde** [comment]
This has been discussed many times please search the archives of the ol3-dev google group
