### ISSUE TITLE
setStyle not rerendering styled features

### ISSUE THREAD

**Issue by hansonwj** [openlayers/ol3#4052]
In the scenario below, the style function tests whether an unique value, representing the feature, is in an associated table, and should remove the feature from the map if it is not present (i.e. has been filtered out by the search). This needs to occur every time a different filter is applied.

What is currently happening is that once the feature has been drawn, the style of that feature cannot be changed/nullified. 

The style of features that have not yet been rendered (i.e. were outside the map window when the filter was applied) are affected by the filter, but once they are rendered then they too are unaffected by further filters. On the other hand, features that have been set to null before they were rendered will appear when the filter is removed.

I have attempted to manually refresh the layer by calling wayleavesLayer.changed(), but this has no effect.

    table.on('draw.dt search.dt stateLoaded.dt', function (){

        wayleavesLayer.setStyle(styleFunction);

        function styleFunction(feature, resolution) {
           feature.setStyle(null);
           var ruleStyle = [new ol.style.Style({
             image: new ol.style.Circle({
               radius: 10,
               fill: null,
               stroke: new ol.style.Stroke({color: 'red', width: 3})
             })
           })];

          var data = table.columns(0, {search:'applied'}).data();
      
          if ($.inArray(feature.get('DocumentID'), data[0]) > -1){
            feature.setStyle(ruleStyle);
          } else {
            feature.setStyle(null)
          }
        };

    });

**Comment by tsauerwein** [comment]
The style function should return an array of styles, see [ol.style.StyleFunction](http://openlayers.org/en/master/apidoc/ol.style.html#.StyleFunction).

**Comment by hansonwj** [comment]
Thanks, solved.

            function styleFunction(feature, resolution) {
              console.log($.inArray(feature.get('DocumentID'), data) > -1)
              if ($.inArray(feature.get('DocumentID'), data) > -1) {
                return ruleStyle;
              } else {
                return null;
              }
            }
