### ISSUE TITLE
Issues handling unmanaged ol.layer.Layer

### ISSUE THREAD

**Issue by gberaudo** [openlayers/ol3#4053]
Unmanaged layers answer an important use case (having one or some layers on top of the others)
but their big drawbacks is that they are not discoverable and listenable.

In OL3-Cesium, a map is setup and then its layers discovered by a call to `map.getLayers()`.
Afterwards, addition and removal of layers is watched and triggers listeners.

This is not possible in the case of unmanaged layers since they are not part of the `ol.Map`
but hidden to the outside and only watching for the map precompose event.

I see several ways to fix or workaround the issue:
1- Modify `ol.Map` to export an ol.Collection object containing the `unmanaged` layers;
2- Add a `z-index` mechanism to layers in addition to current unmanaged mechanism;
3- Add a `z-index` mechanism to layers instead of the current unmanaged mechanism;
4- Push the workaround responsability to the user.

1- Modify `ol.Map` to export an ol.Collection object containing the `unmanaged` layers;
The most simple:
In `ol.layer.Layer#setMap()`, we add/remove the layer to some new `ol.Map#unmanagedLayers` object.
This object can be discovered easily and watched.

2- Add a `z-index` mechanism to layers in addition to current unmanaged mechanism;
We allow the user to set a `z-index` property in the layer which we will use in the renderer
to determine the rendering order. In this case, the user will use `normal` layers which will
show up in `ol.Map#getLayers()`. The rendering order will depend both on the optional z-index value and the
actual sequence of the layers. For example [a, b1, c, d1] will be rendered as [a, c, b1, d1].

3- Add a `z-index` mechanism to layers instead of the current unmanaged mechanism;
This is the same as 2 but also removes unmanaged layers since their use case
would be handled with z-index.

4- Push the workaround responsability to the user.
This is the worst solution, where each user has to find out, understand and implement
a complex workaround.

What do you think about this issue and proposed solutions?
Am I missing something and do you see other ways?

**Comment by ahocevar** [comment]
Unmanaged layers are the successor of feature overlays, which were also hidden from applications unless created by the application itself. ol3-cesium did not support feature overlays.

Sounds to me like we only need to improve documentation to make it clear to users what unmanaged layers are for.

**Comment by gberaudo** [comment]
@ahocevar, supporting layers on top is a real use case and an expectation from our users.
They want support both at the application level and also indirectly through the use in OL3 itself.

What is the value of OL3 interactions if they only work in 2D?
With that in mind, I think only the first three solutions are practical.

Other feedback?

**Comment by elemoine** [comment]
@gberaudo, I think I like option 2. With that option, contrary to option 3, we still provide a way to silently add and remove layers (using `setMap`).  Option 2 sounds simple enough, while offering flexibility to users.

**Comment by gberaudo** [comment]
Closing after the merge of #4069.
