### ISSUE TITLE
error in ol.source.WMTS.optionsFromCapabilities

### ISSUE THREAD

**Issue by spind42** [openlayers/ol3#4056]
ol.source.WMTS.optionsFromCapabilities cannot read the description from http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml

it runs into an assert:   goog.asserts.assert(urls.length > 0, 'At least one URL found');

Looks like the code is trying to use WMTSRequestEncoding.KVP but the WMTSCapabilities.xml says it is WMTSRequestEncoding.REST

so is the provided WMTSCapabilities.xml illegal or is there a parser error in the code?

**Comment by bartvde** [comment]
Are you specifying ```requestEncoding: "REST"``` in the source config?

**Comment by spind42** [comment]
nope i added an ugly workaround to the ol code. I modifed the optionsFromCapabilities function in a very ugly way, so it can also parse the urls from the provided xml. But adding requestEncoding: "REST" to the source config looks like the better way.
