### ISSUE TITLE
Add 'rightclick' event on map.

### ISSUE THREAD

**Issue by anzhihun** [openlayers/ol3#4057]
Use case: The user wants to modify/delete/save the areas through a menu, which is popuped by right click on the area.   
I have found all examples and APIs for this. But I doesn't found some solution. Finally, I find that the map doesn't emit 'rightclick' event after I look into the source code, 
I hope that the map will support 'rightclick' event, or provide other solutions about this use case. Thanks!

**Comment by jonataswalker** [comment]
Fork (https://github.com/jonataswalker/ol3-contextmenu) and adapt to your needs.

**Comment by anzhihun** [comment]
Thank you very much!
