### ISSUE TITLE
Using getSimplifiedGeometry() in project

### ISSUE THREAD

**Issue by patrickbr** [openlayers/ol3#4058]
Hi there,

we are using the undocumented function 'getSimplifiedGeometry()' in a project to simplify a LineString using Douglas-Peucker. This works perfectly fine as long as we are using the pre-build version of OL3. However, we would like to use our own custom build OL3. We digged through build/info.json but couldn't find any export that would provide as with getSimplifiedGeometry().

A related, more general question: what is usually the best practice for finding out the export strings for certain functions? For now, we just grep build/info.json for something that looks promising and test it.

Thanks,
patrick

**Comment by bartvde** [comment]
Right you would need to maintain a fork of openlayers and add the ```@api``` annotation as well.

Let's just consider this a request for exporting ```getSimplifiedGeometry``` as an experimental API option in ol3 master branch. I have no objections.

Anybody else object to this?

**Comment by fredj** [comment]
+1 to export `getSimplifiedGeometry`

**Comment by bartvde** [comment]
@patrickbr are you able to create a PR?

**Comment by bill-chadwick** [comment]
+1 to export but as ever I suggest that the docs have an explanation that the simplification assumes that the coordinates have equal weight in the x and y direction so with 4326 and 3857  coords at high/low latitudes the simplification will be compromised. Some thought is required to select a squared tolerance in degrees at extreme latitudes, probably best just to use a latitude squared tolerance I think.

**Comment by tschaub** [comment]
> Some thought is required to select a squared tolerance in degrees at extreme latitudes, probably best just to use a latitude squared tolerance I think.

The purpose of this method is to simplify geometries for rendering.  Your suggestions are not relevant for our use case - the geometries are in the view CRS.
