### ISSUE TITLE
geolocation error chrome and ff

### ISSUE THREAD

**Issue by lehmannwebdev** [openlayers/ol3#4065]
Geolocation does not work.

http://openlayers.org/en/v3.8.2/examples/geolocation-orientation.html - return alert geolocation error on Google chrome (v. 44.0.2403.157 m) and FF (v. 40.0.3) [Windows 7]. 

Error does not exists on IE and Opera.

**Comment by fredj** [comment]
Error on chrome:

getCurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details
