### ISSUE TITLE
problem initialising google maps MapTypeId.ROADMAP and MapTypeId.TERRAIN 

### ISSUE THREAD

**Issue by arthurnl** [openlayers/ol3#4066]
Since  today, 1-9-2015,using OL2, the  OpenLayers.Layer.Google() does not work properly any more.
You can still use MapTypeId.HYBRID,or MapTypeId.TERRAIN.

Once you passed that, the MapTypeId.ROADMAP can be used again with the LayerSwitcher.

maybe the same problem in OL3?

**Comment by tsauerwein** [comment]
That's not a problem since OpenLayers 3 does not support Google Maps tiles.

**Comment by arthurnl** [comment]
Understood. No support for OL2. As we ned to continue with google maps, we need to find another framework. Pity.

**Comment by bartvde** [comment]
You can always open an issue here: https://github.com/openlayers/openlayers for OpenLayers 2 but it's not really under active development anymore. There are companies providing support though and can fix this if you have funds for a support contract.

**Comment by xzhangdewberry** [comment]
To fix it, you need to change Google Map API url from v3 to v3.5

**Comment by arthurnl** [comment]
great. that worked for me!
