### ISSUE TITLE
Feature Animation Example Causes Browser to Become Unresponsive

### ISSUE THREAD

**Issue by wlerner** [openlayers/ol3#4074]
There is an issue with the Feature Animation example at the URL below:

http://openlayers.org/en/v3.8.2/examples/feature-animation.html 

When this example is loaded, Firefox and Chrome will both eventually become unresponsive.  A sample of the error is below.  The error is repeated in the developer console until the browser freezes.

12:25:36.500 Expected color but found '0'.       from DOM

The issue is repeatable.

**Comment by wlerner** [comment]
This issue is repeatable in the new 3.9.0 release.  I realize this issue was not addressed by this release, however, I thought it would be helpful to note.

http://openlayers.org/en/v3.9.0/examples/feature-animation.html

When this example is loaded, Firefox and Chrome will both eventually become unresponsive. A sample of the error is below. The error is repeated in the developer console until the browser freezes.

Error provided: Expected color but found '0'. from DOM

The issue is repeatable.

**Comment by elemoine** [comment]
How much time do you need to wait before seeing the error?

**Comment by wlerner** [comment]
The error is seen almost immediately in the Firefox and Chrome consoles.  The error increments quite rapidly.

**Comment by elemoine** [comment]
It looks like I can reproduce in Firefox, but not in Chrome.

**Comment by elemoine** [comment]
But the problem is not repeatable for me, even in Firefox.

**Comment by wlerner** [comment]
I am unable to reproduce the problem on my Mac using Chrome Version 46.0.2490.22 beta (64-bit).  However, I am able to reproduce the problem on a page refresh or reload of both URLs above using Firefox 41.0.b1 and previous versions.  I have been seeing this issue on a Linux based PC at work with older versions of both browsers.

![screen shot 2015-09-11 at 9 43 34 am](https://cloud.githubusercontent.com/assets/14095650/9816231/abdcce3c-5869-11e5-98a9-9049278d20aa.png)
![screen shot 2015-09-11 at 9 43 57 am](https://cloud.githubusercontent.com/assets/14095650/9816234/b17a84ce-5869-11e5-8ac0-7a083dd90d28.png)

**Comment by wlerner** [comment]
Adding the following code to the example will make the error disappear from the console.  I believe this is sub-optimal and not a solution, more of a temporary workaround.

    fill: new ol.style.Fill({
                color: 'rgba(0, 0, 0, 0)'
              })

**Comment by elemoine** [comment]
I think I found the bug. Your workaround put me on the right track! I'll create a PR.
