### ISSUE TITLE
Error occurs when click on map

### ISSUE THREAD

**Issue by namld** [openlayers/ol3#4097]
Hi, I'm developent use openlayer v3 libary. Sometime I meet error when click on map, the map suddenly invisible content. You can see its result when click on map in example like bellow:http://openlayers.org/en/v3.8.2/examples/overlay.html :
![oenlayererrorwhenclickonmap](https://cloud.githubusercontent.com/assets/1930328/9755089/3f51579a-56f9-11e5-9f1e-94b95cbd7c6a.png)

**Comment by namld** [comment]
This bug still occur in http://openlayers.org/en/v3.10.1/examples/overlay.html.

**Comment by ahocevar** [comment]
See http://openlayers.org/en/v3.10.1/examples/popup.html. The automatic positioning does not work with Bootstrap popovers. So please create your popup like in the example I linked.
