### ISSUE TITLE
Raster file Image quality in OL3 is low as compare to OPENLAYERS 2

### ISSUE THREAD

**Issue by yatenj** [openlayers/ol3#4098]
Hi,
I have a raster Image.
When I publish that image in OL 3, Image quality is low (blured, ).
But same image when I published using OPENLAYERS 2, quality is good.

in both I have used TileWMS as it is published in GeoServer.
In OL3 I havwe tried it to publish using ImageWMS.
But there is no improvement in quality.

What are the available options and configurations in OL3 by which image quality can be improved.

Thanks :)

**Comment by taviroquai** [comment]
Hi,

I think I came across a similar problem...

Using the same WMS service (mapserver), Tile layer appears blurry (note that the single image tile is returned correct from the server).
Althought, when I change to Image layer, the images are fine.

Are there any options about this? Could this blurry issue be related to the tile grid?

Thanks

**Comment by yatenj** [comment]
Hi Thanks for reply,
I have tried with Image layer also.
But there is no improvement.

Can anyone help on this.

Thanks

**Comment by tschaub** [comment]
Things that would improve the likelihood that this ticket gets attention:

 * runnable code (here is an example to get you started http://jsfiddle.net/tschaub/j2cP4/)
 * screenshots that detail the differences in rendering quality

**Comment by taviroquai** [comment]
Thanks Tim for your attention.

The problem is the BLUR display as described bellow.

These are the relevant parts of my map:
```
proj4.defs("EPSG:27492", "+proj=tmerc +lat_0=39.66666666666666 +lon_0=-8.131906111111112 +k=1 +x_0=180.598 +y_0=-86.98999999999999 +ellps=intl +towgs84=-223.237,110.193,36.649,0,0,0,0 +units=m +no_defs");

var proj27492 = new ol.proj.Projection({
    code: 'EPSG:27492',
    extent: [-127101.82, -300782.39, 160592.41, 278542.12]
});

ol.proj.addProjection(proj27492);

self.map = new ol.Map({
        target: 'map',
        controls: [new ol.control.ScaleLine()],
        layers: [],
        view: new ol.View({
            projection: proj27492,
            extent: config.map.extent,
            //resolutions: [61.547744757882036, 32.82546387087041920, 16.41273193543520960, 8.20636596771760480, 4.10318298385880240, 2.05159149192940120, 1.02579574596470060, 0.51289787298235030, 0.25644893649117515, 0.10257957459647006, 0.05128978729823503],
            minResolution: 0.05128978729823503,
            maxResolution: 61.547744757882036,
            center: ol.proj.transform([0, 0], 'EPSG:4326', 'EPSG:' + config.map.crs),
            zoom: 0
        })
});
```

Now, using the same map and an Image layer:
```
layer = new ol.layer.Image({
        visible: config.visible,
        source: new ol.source.ImageWMS(config)
});
```

.. I get this (screenshot, no blur):
![ol-screenshot-source-image](https://cloud.githubusercontent.com/assets/498409/10040996/b738e5e0-61d8-11e5-84f3-fdfca3cb7585.png)

Using Tile layer, same map:
```
layer = new ol.layer.Tile({
        visible: config.visible,
        source: new ol.source.TileWMS(config)
});
```

... I get this (screenshot, WITH BLUR):

![ol-screenshot-source-tile](https://cloud.githubusercontent.com/assets/498409/10041012/debf127e-61d8-11e5-9e9c-34d72cae5c4c.png)

**Comment by yatenj** [comment]
Thanks for explaining.
It worked for me.

**Comment by ahocevar** [comment]
The resolutions for your view need to match the resolutions of your layer's tile grid, otherwise you'll get scaled images. So make sure that your `minResolution` and `maxResolution` values match values from the list of layer resolutions (`layer.getTileGrid().getResolutions()`).

**Comment by taviroquai** [comment]
Hi,

Thanks Andreas, creating the layer specifying the tile grid (the same configuration as on map) as solved the scaling problem, but this rises the question:

Can I create the layer without specifying the tile grid but instead using configuration from the map?
In my case doesn't make sense specifying other tile grid configuration, resulting, as we can see from above, in wrong scaling.

Thanks!

**Comment by ahocevar** [comment]
Not with a tile layer. But with `ol.layer.Image` and `ol.source.ImageWMS`, you'll always get images for the current view resolution and extent.
