### ISSUE TITLE
Simplify attributions

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#4100]
I think the most straightforward way to support source attribution would be to allow either of the following:

```js
var source = new ol.source.XYZ({
  attribution: 'My <b>favorite</b> tile source'
})
```

or

```js
var source = new ol.source.XYZ({
  attribution: function(view) {
    // or frameState if we want awkwardness
    return 'Maybe this depends on what is rendered';
  }
});
```

Instead we have an `attributions` option for sources where each `ol.Attribution` accepts an `html` option and an undocumented `tileRanges` option (of type `Object.<string, Array.<ol.TileRange>>`).  Since the `tileRanges` option is undocumented and unnecessarily tied to one particular implementation (not all sources are tile sources), users do not have real control over which of the attributions is rendered, and there is no purpose to supplying an array.

Since `ol.Attribution` is marked as stable, one option would be to give it a `render` option (or similar) that is type `function(ol.View):boolean` and determines when the attribution is rendered.

Another option would be to remove the experimental `attributions` options from tile sources and add a single `attribution` option that was type `string|function(ol.View):boolean`.  This would leave `ol.Attribution` orphaned and deprecated.

Any opinions?

**Comment by marcjansen** [comment]
Plus one for simplification.

What about simply (haha) changing option 'attributions' that accepts a string or a function with your signature or an ol.Attribution or an array of those?

This would be backward compatible and we could even deprecate the usage of ol.Attribution.

Thiswould be a big change in terms of touched code, I fear.

**Comment by ahocevar** [comment]
+1 on changing something here at least. Since Bing advertises attributions in extents and not in tile ranges, we could switch to an implementation that uses extents instead of tile ranges.

And as @tschaub suggests, a shortcut for attributions that are valid for the whole world would be an `attribution` config option.

**Comment by elemoine** [comment]
> Another option would be to remove the experimental attributions options from tile sources and add a single attribution option that was type string|function(ol.View):boolean. This would leave ol.Attribution orphaned and deprecated.

I think I'd go with that. But I think we can use `string` or `string|ol.Attribution` for the type, and add `function(ol.View):boolean` as a possible type in the future if needed.
