### ISSUE TITLE
Blank Base Map

### ISSUE THREAD

**Issue by abhijitgujar86** [openlayers/ol3#4103]
Blank base map is often required. it would be good and handy if there could be some option to easily add a blank base map. It is more of new feature rather than issue but i did not know where to post new idea or requested so i posted it in issues . sorry and thanks for open layer 3. I like it. Hope someday i can contribute to it.

**Comment by elemoine** [comment]
We have multiple applications with a blank background image. And we just use an `ol.layer.Tile` layer with no source. See https://github.com/Geoportail-Luxembourg/geoportailv3/blob/46e8190da8d2889b9338c7d614792072fbf83d0c/geoportailv3/static/js/backgroundlayer/blanklayerservice.js for example. I am going to close this issue as there's no plan to introduce more specific support for that in the library.
