### ISSUE TITLE
Panning with touch doesn't work in Microsoft Edge browser

### ISSUE THREAD

**Issue by eemikula** [openlayers/ol3#4105]
This applies for every example I can find: ol3 won't pan using a touch-screen and the new browser in Windows 10. Works fine with normal click-and-drag, and also with other browsers.

Just as one example: http://openlayers.org/en/v3.9.0/examples/attributions.html

**Comment by calummm** [comment]
This issue also seems to be affecting zoom and rotation using touch as well. Pinch zoom does not work but pressing with two fingers causes a zoom in to occur. I have not yet worked out how to disable page zooming in Microsoft Edge. 

If the map is made full screen however, everything works as expected - as per [http://openlayers.org/en/v3.9.0/examples/full-screen-drag-rotate-and-zoom.html](http://openlayers.org/en/v3.9.0/examples/full-screen-drag-rotate-and-zoom.html)
