### ISSUE TITLE
forEachFeatureAtPixel and Firefox >= 40 offset

### ISSUE THREAD

**Issue by canonex** [openlayers/ol3#4112]
I'm building a web application using forEachFeatureAtPixel to open a pop-up.
Using with all browsers except latest versions of Firefox I'm able to correctly point the mouse and click, finding features. For what I could debug, when using Firefox 40 the map margins are not considered. Using Firefox <40 it works (as it does with other browsers).

Test using this page [test project](http://130.192.92.243:8000/~invito/?page_id=2&pname=project&act=view&cid=202) and try to select a feature.

When using Firefox you can select features with an offset equal to the right panel width:
**clickHere.........................marginLeftWidth..............................featureSelectedHere**

If you enlarge the map (top left icon on the map) the margin is zero and you can again select correctly the features.

In the debugger you can see the click event and, when a feature is detected. the popup coords.
I don't know if is an underlying problem of OL or a firefox problem. The project is currently using OL 3.0 but, with a quick test, the latest version is affected by the same problem.

**Thank you**,
Rickyx

**Comment by tsauerwein** [comment]
Could you provide a minimal example (for example a JSFiddle) demonstrating the problem? Because for example in the [icon example](http://openlayers.org/en/v3.9.0/examples/icon.html) `forEachFeatureAtPixel` works on Firefox 40 (also when setting a left margin on the map div).

**Comment by Matthias84** [comment]
Wether an minimal example, nor an JSFiddle, but I notice this Problem also on [my project](http://map.on-i.de/) with OL3.5 and it seems to persist on OL3.9 (local dev):
If you want to click on a node, the feature is detected just a few pixels left from the rendered node. Have a look at [onimap.js](http://map.on-i.de/static/onimaps.js) setupPopup(). I tried to find if it's an issue with my code, but as other notice this problem, too, I guess its related to OL itself?

**Comment by elemoine** [comment]
@Matthias84, do you observe the same problem if you add `<!DOCTYPE>` as the first line of the HTML page?

**Comment by canonex** [comment]
I can't reproduce in JSFiddle because I can't find out which setting are wrong and are causing the issue:
and yes, in the icon example is working.

**Comment by Matthias84** [comment]
I can confirm (for my example), that OL 3.9 doesn't has the problem, so I consider it to be fixed already. Can you confirm @canonex that an upgrade is an working solution?

**Comment by canonex** [comment]
It will take me some days to port the application to the new OL 3.9.
I'll write a review right after.

**Comment by canonex** [comment]
The upgrade worked smoother that I thought and I'm testing OL 3.9.

The **big problem** is solved: that means that the margins are now interpreted correctly and I can point and click on the features.

The **small problem** ( as pointed by Matthias84 ) can still occur:
![coordsdelta](https://cloud.githubusercontent.com/assets/1444378/10076100/d969e78e-62d9-11e5-8196-8d0a0c92a01e.png)

Thank you,
Riccardo

**Comment by elemoine** [comment]
It would be good to have an example using v3.9.0 that demonstrates the "small" problem.

**Comment by canonex** [comment]
The problem is the same that in the example I posted:
[test project](http://130.192.92.243:8000/~invito/?page_id=2&pname=project&act=view&cid=202)

After you got to select a geometry and pan from top left to bottom right the popup (and the sensitive point) moves, from almost centered, to out of the circle.  *The project is still in the old version, you need to try at some point, the width of the left panel, on the left.*

Tomorrow I'll try to post some more explicative example.

**Comment by canonex** [comment]
I could not reproduce the issue ( "small" problem :smiley: ).
Version 3.9 anyway is fixing the original problem therefore I close this report.

Thank you,
Riccardo

**Comment by Matthias84** [comment]
I'm sorry but I guess the "small problem" is reproducible to me on 3.9.:

* Open http://map.on-i.de/#15;12.122793682887732;54.082354008638845
* Move mouse to a node on the left side of the map -> hovering is ok and in sync with visuals
* Move mouse to a node on the right side of the map -> hovering is async and shifted ~15px to the left

Will this help @canonex ? Plz. tell me how I might help to isolate the problem

**Comment by canonex** [comment]
Yes, that's it: what is the reason for this shift?
I can't guess it...

**Comment by skewty** [comment]
I am having this issue as well.

Firefox 46.0  (Ubuntu 16.04 x64)
OpenLayers 3.15.1
