### ISSUE TITLE
z-index not working with geolocation

### ISSUE THREAD

**Issue by levinzz** [openlayers/ol3#4113]
With OL 3.9 create a geolocation layer like in the example :
```
var accuracyFeature = new ol.Feature();
var positionFeature = new ol.Feature();
var collection = new ol.Collection([accuracyFeature, positionFeature]);
var featuresOverlay = new ol.layer.Vector({
            map: map,
            source: new ol.source.Vector({
                features: collection,
                useSpatialIndex: false // optional, might improve performance
            }),
            updateWhileAnimating: true, // optional, for instant visual feedback
            updateWhileInteracting: true, // optional, for instant visual feedback
            zIndex: 2
        });

geolocation.on('change:accuracyGeometry', function () {
                    accuracyFeature.setGeometry(geolocation.getAccuracyGeometry());
                });

geolocation.on('change', function (evt) {
                    var newPosition = geolocation.getPosition();
                    vm.view.setCenter(newPosition);
                    vm.view.setZoom(16);
                });
```

Create another layer :
```
var clusterLayer = new ol.layer.Vector({
                source: ...,
                style: function (feature, resolution) {
                    return ...;
                },
                zIndex: 7
            });
map.addLayer(requestClusterLayer);
```

The geolocation feature is above the cluster feature :
![image](https://cloud.githubusercontent.com/assets/10078646/9880365/93b1c0fa-5bcb-11e5-9b3a-6e1b7f95b5f1.png)

**EDIT : added Plunker** : http://plnkr.co/edit/febEYh?p=preview

**Comment by alvinlindstam** [comment]
Z-index for layers was added in https://github.com/openlayers/ol3/pull/4069. Allowing the user to set the Z-index of unmanaged layers was discussed, but it seems the merged PR forces `zIndex: Infinity` on unmanaged layers.

The question here is probably if unmanaged layers should always be on top or not, or if this difference should be better documented.

You could make the `featuresOverlay` layer a managed layer, in which case you could choose it's Z-index.

**Comment by levinzz** [comment]
Indeed it works when I make it a managed layer.

Now I get why the geolocation example layer is still named a "features**Overlay**" even though it doesn't seem any different than other vector layers...

The difference being so subtle, I'd vote for some more emphasis on this in the documentation.

Thanks !

**Comment by clegeard** [comment]
Hi levinzz,
I have the same issue, how do you make the featuresOverlaly a managed layer?
Thanks

**Comment by levinzz** [comment]
According to the Vector doc : https://openlayers.org/en/latest/apidoc/ol.layer.Vector.html

"new ol.layer.Vector(opt_options)
map : Sets the layer as overlay on a map. The map will not manage this layer in its layers collection, and the layer will be rendered on top. This is useful for temporary layers. The standard way to add a layer to a map and have it managed by the map is to use ol.Map#addLayer."

so instead of setting the map as a constructor option of the featureOverlay, add it to the map using ol.Map#addLayer

**Comment by clegeard** [comment]
Thank you very much! You saved my day.

**Comment by ahocevar** [comment]
#8515 adds `zIndex` support for unmanaged layers.
