### ISSUE TITLE
Draw interaction does not work as expect when there is a select interaction

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#4114]
```
diff --git a/examples/draw-features.js b/examples/draw-features.js
index b7cb4ce..5f13bae 100644
--- a/examples/draw-features.js
+++ b/examples/draw-features.js
@@ -2,6 +2,7 @@ goog.require('ol.Map');
 goog.require('ol.View');
 goog.require('ol.geom.Polygon');
 goog.require('ol.interaction.Draw');
+goog.require('ol.interaction.Select');
 goog.require('ol.layer.Tile');
 goog.require('ol.layer.Vector');
 goog.require('ol.source.MapQuest');
@@ -46,6 +47,8 @@ var map = new ol.Map({
   })
 });
 
+map.addInteraction(new ol.interaction.Select());
+
 var typeSelect = document.getElementById('type');
 
 var draw; // global so we can remove it later
```

![screen shot 2015-09-15 at 19 26 23](https://cloud.githubusercontent.com/assets/319678/9884377/ab70a2ba-5bdf-11e5-8647-9e7be8a69ece.png)

Is there an obvious reason why this combination of interactions should be avoided?

**Comment by bartvde** [comment]
Also, this does not happen if the layer is unmanaged. If the layer is managed, you can see the above effect.

**Comment by bartvde** [comment]
This line is causing the observed behaviour: https://github.com/openlayers/ol3/blob/master/src/ol/interaction/selectinteraction.js#L257

**Comment by bartvde** [comment]
In the end I made sure in my application I did not have these two interactions active at the same time. Workaround though.

**Comment by ahocevar** [comment]
Can you reference the faulty logic me in selectinteraction.js for the revision in question instead of master? The line on master is a JSDoc comment.
