### ISSUE TITLE
Vector feature are moving after animation end

### ISSUE THREAD

**Issue by adube** [openlayers/ol3#4115]
This odd behaviour seems to have appeared in v3.8.x., i.e. I can't reproduce this in v3.7.0: in a map that has vector features in it, after the zoom animation ends, we can see the features slightly move around.  This even occur when zooming out completely.  In fact, it's even more noticeable that way.

See http://openlayers.org/en/v3.8.2/examples/icon.html.  Zoom out using the mouse scroll.  Upon reaching the end, continue to scroll out.  You'll see the behaviour occur.

See in http://openlayers.org/en/v3.7.0/examples/icon.html, that didn't happen.

**Comment by alvinlindstam** [comment]
`map.on('postcompose', function(evt){console.log(evt.frameState.viewState.center.join(","), evt.frameState.animate)})` on the 3.8.3 example show that the center is flickering in when trying to zoom out more than possible. The center remains stable on 3.7.

**Comment by elemoine** [comment]
Would be worth to git-bisect this…

**Comment by alvinlindstam** [comment]
I did a git-bisect. This behavious appeared in https://github.com/openlayers/ol3/pull/3933

**Comment by elemoine** [comment]
@adube could you please test with v3.9.0? http://openlayers.org/en/v3.9.0/examples/icon.html Thanks.

**Comment by adube** [comment]
Sure.  I don't understand why, but I'm no longer to reproduce the issue with this particular example.  This other example shows the issue: http://openlayers.org/en/v3.9.0/examples/vector-labels.html?q=label

Try zooming out until the end and you should see the features flicker.
