### ISSUE TITLE
Raster reprojection stitch lines visible between triangles for semi-transparent sources

### ISSUE THREAD

**Issue by klokan** [openlayers/ol3#4123]
Related to PR #4122

When rendering content of reprojection triangles, a clip path is set up on the canvas 2d context. However, in most browsers, the operations on the clip path edges are antialiased.

When rendering two neighboring triangles, the edge between them is slightly transparent (blending 50% opacity over 50% opacity does not produce 100% opacity):

![gap](https://cloud.githubusercontent.com/assets/707817/9254671/1429b59a-41e5-11e5-8a73-8ca3cc7be6cd.png)

**This does not happen in Chrome**, which does not antialias clip path edges, but it is currently reported as a bug and probably will be "fixed" in the future: http://crbug.com/424291

Although there are several possible `globalCompositeOperation` on canvas 2d context (see https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation for examples), none of them can be used to solve this issue -- the RGB values on the edge should be identical in both triangles, but we need to "sum" the alpha channel.

Currently, this is partially **solved by expanding the clip path triangles** by 1px so that the triangles slightly overlap and the gap is not visible.

This works well, **no gaps are visible usually**, unless the source data are semi-transparent - such as WMS serving partly transparent PNG tiles (the overlap results in noticeable line):

![semitrans](https://cloud.githubusercontent.com/assets/707817/9259881/b2646a6a-4204-11e5-9fd6-a9bc6a326747.png)

The special case of semi-transparent raster sources could be probably solved in future by implementing a manual (custom) compositing operation on the canvas in JavaScript, when alpha channel is treated non-standardly for this use-case.

**Comment by bartvde** [comment]
These issues were created so we document the knowledge, but they are not active issues being worked on, so I'm going to close them.
Thanks for documenting them though @petrsloup they will be kept for posterity.

**Comment by pksorensen** [comment]
Do anyone have an estimate on what it would cost to fix this? 

"Currently, this is partially solved by expanding the clip path triangles by 1px so that the triangles slightly overlap and the gap is not visible." How does one enable this?

https://github.com/openlayers/openlayers/issues/6342

**Comment by ahocevar** [comment]
@pksorensen There is not really a way to fix this. But what you reported in #6342 can be solved. Let's continue the discussion there.
