### ISSUE TITLE
Raster reprojection source resolution

### ISSUE THREAD

**Issue by petrsloup** [openlayers/ol3#4124]
Related to PR #4122

When reprojecting tiled-based raster sources, required source resolution is calculated precisely for each reprojected tile (in it's center) using `ol.reproj.calculateSourceResolution`.

The resolution to be used (zoom level) is then selected from the available resolutions on the tile grid using `ol.tilegrid.TileGrid#getZForResolution`, which by default finds the **nearest** resolution (and zoom level). (The zoom level is then constant for the whole reprojected tile.)
This sometimes results in magnification:
![closest_crop](https://cloud.githubusercontent.com/assets/707817/9755929/746e629c-56d6-11e5-9b86-84c5c3f39e15.png)

Some better method for resolution selection could be implemented to improve the visual quality by changing `this.srcZ_ = sourceTileGrid.getZForResolution(sourceResolution);` in `ol.reproj.Tile` to different algorithm.

- Always-**magnify** approach produces very blurry results (`ol.array.linearFindNearest(sourceTileGrid.getResolutions(), sourceResolution, 1);`):
![oversampling_crop](https://cloud.githubusercontent.com/assets/707817/9755965/ac915742-56d6-11e5-804f-fa6ffcfd5944.png)

- Always-**shrink** approach (`ol.array.linearFindNearest(sourceTileGrid.getResolutions(), sourceResolution, -1);`) sometimes works better:
![shrinking](https://cloud.githubusercontent.com/assets/707817/9757864/7331e95a-56e3-11e5-8a8f-1b2447a95c26.png)
, but more data have to be loaded and labels can be hard to read:
![shrinking_labels](https://cloud.githubusercontent.com/assets/707817/9757880/86d54204-56e3-11e5-9329-3c40761b665e.png)

- Alternatively, some new **threshold** value can be added to determine, when round the resolution up and when down (`0.5` would be equal to the "closest").

**Comment by bartvde** [comment]
These issues were created so we document the knowledge, but they are not active issues being worked on, so I'm going to close them.
Thanks for documenting them though @petrsloup they will be kept for posterity.
