### ISSUE TITLE
Custom build fails with Node 4.0

### ISSUE THREAD

**Issue by ebridger** [openlayers/ol3#4127]
Following the  [custom build tutorial]( http://openlayers.org/en/v3.9.0/doc/tutorials/custom-builds.html ) using NodeJS v4.0.0 (admittedly just released) fails with:

    $ node tasks/build.js build/ol-custom.json build/ol-custom.js
    ERR! Trouble generating info: Failed to parse output as JSON: . . .

Reverting to NodeJS v0.12.7 everything works as expected.  Only tested on OS 10.10.5 with Java 7

**Comment by tschaub** [comment]
@ebridger this is due to nodejs/node#2972.  Before putting together a workaround, I'd like to get confirmation that it is an upstream issue.

**Comment by mlegenhausen** [comment]
+1 same error under 4.1.0.

**Comment by big-r81** [comment]
same error for me under 4.1.0.

**Comment by mlegenhausen** [comment]
Seems to be fixed under 4.1.1

**Comment by big-r81** [comment]
for me it is not working under 4.1.1!

**Comment by tschaub** [comment]
See #4163 for a Node 4.x fix.

**Comment by jonataswalker** [comment]
Still failing to build under Node 4.2.2.

`ERR! Trouble generating info: Failed to parse output as JSON`

**Comment by fredj** [comment]
@jonataswalker It's working for me with node v4.2.2
Try to run `npm install`, `make clean` and then `make build`

**Comment by jonataswalker** [comment]
I was trying a custom build but same error with standard build:
```
$ make build
npm install

> openlayers@3.11.2 install /home/www/ol3
> node tasks/install.js

> openlayers@3.11.2 postinstall /home/www/ol3
> closure-util update

npm WARN unmet dependency /home/www/ol3/node_modules/browserify requires glob@'^5.0.15' but will load
npm WARN unmet dependency /home/www/ol3/node_modules/glob,
npm WARN unmet dependency which is version 6.0.1
npm WARN unmet dependency /home/www/ol3/node_modules/metalsmith/node_modules/rimraf requires glob@'^5.0.14' but will load
npm WARN unmet dependency /home/www/ol3/node_modules/glob,
npm WARN unmet dependency which is version 6.0.1
npm WARN unmet dependency /home/www/ol3/node_modules/slimerjs-edge/node_modules/rimraf requires glob@'^5.0.14' but will load
npm WARN unmet dependency /home/www/ol3/node_modules/glob,
npm WARN unmet dependency which is version 6.0.1
npm WARN unmet dependency /home/www/ol3/node_modules/istanbul/node_modules/fileset requires glob@'5.x' but will load
npm WARN unmet dependency /home/www/ol3/node_modules/glob,
npm WARN unmet dependency which is version 6.0.1
npm WARN unmet dependency /home/www/ol3/node_modules/phantomjs/node_modules/fs-extra/node_modules/rimraf requires glob@'^5.0.14' but will load
npm WARN unmet dependency /home/www/ol3/node_modules/glob,
npm WARN unmet dependency which is version 6.0.1
Running cleancss...
node tasks/build.js config/ol.json build/ol.js
ERR! Trouble generating info: Failed to parse output as JSON: 
```

**Comment by tschaub** [comment]
@jonataswalker this was the failure we got before upgrading to jsdoc@3.4.0.  Can you report on the version in your `node_modules/jsdoc/package.json`?

My suggestions:
```
rm -rf node_modules
npm install
node tasks/build.js config/ol.json ol-full.js
```

**Comment by jonataswalker** [comment]
It says (said):
```
  "version": "3.4.0",
  "revision": "1447115289326"
```
But now, yeah, just fine. Remove all and reinstall.
Thank you @tschaub.

**Comment by zhangwei0402** [comment]
ERR! Trouble generating info: 'D:\Program' is not recognized as an internal or external command,
operable program or batch file.
System: Win8
Nodejs version: v4.2.3

**Comment by ahocevar** [comment]
@zhangwei0402 Some Windows shells are known to have problems with paths that contain ` `s, like in `D:\Program Files\`. Try to work from path that has no blanks in it.
