### ISSUE TITLE
Remove brightness, hue, saturation, and contrast as layer properties

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#4130]
These properties are only supported by the WebGL renderer.  Instead of porting the functionality to the Canvas renderer, I think it makes sense to remove them entirely.

What do others think?

**Comment by tschaub** [comment]
Here's a branch for consideration: https://github.com/openlayers/ol3/compare/openlayers:master...tschaub:fewer-layer-props

46 additions and 1,683 deletions.  6,143 B smaller.

**Comment by elemoine** [comment]
I am mixed feeling of this. On one side, it feels strange to remove features. Features that some people may actually use in application. On the other side, it's a good idea to remove this if no one uses it and if we think this is useless. So +0 from me, and deferring to others.

**Comment by ahocevar** [comment]
I think it's a good idea to remove this. As a replacement, we could make an example that uses postcompose hooks to change hue, saturation and contrast on the application level, using the standard canvas renderer.

**Comment by marcjansen** [comment]
I am also not blocking this. The eaxamole is a very good idea, @ahocevar

**Comment by bartvde** [comment]
I'm also supportive of the idea to remove it

**Comment by gberaudo** [comment]
I am also concerned about the removal.
It seems a reasonable feature for the WEBGL renderer and is [supported by Cesium](https://cesiumjs.org/Cesium/Build/Documentation/ImageryLayer.html?classFilter=imagerylay).
Cesium also supports global filters (applied to the whole scene), in a dedicated branch.

Since the work is already done and reasonable, there is no known bug and there is no immediate benefit for the removal I think it would be better to keep the code for now.

We can always reconsider later when the situation changes.

**Comment by tschaub** [comment]
[I was opposed](https://github.com/openlayers/ol3/pull/37) to the addition of these properties from the start for several reasons:
 * they are gratuitous demonstrations of WebGL shaders
 * instead of being general purpose transforms, they are specific and uncommon operations to perform on map data
 * they cannot be implemented efficiently and consistently in all renderers

At the time they were added, there was an undue amount of emphasis placed on the WebGL renderer.  Years later, the WebGL renderer still isn't a clear choice as a default, yet we have base layer properties that are only supported in this one renderer.

I still believe that these properties serve no real purpose except to demonstrate capability.  And to say that they are also supported by downstream integration libraries (Cesium or GeoExt or anything else) is not justification for their existence in my opinion.

So the reason to remove them is because there is no reason to have them.  Code that serves no purpose should not have been added to the library in the first place.

An example like @ahocevar suggests could prove to be useful to people who want to change the hue of a layer.  In addition, if someone could demonstrate how custom shaders could be used by the WebGL renderer, that would be a more general and powerful demonstration of capability than `layer.setHue()` et al.

**Comment by elemoine** [comment]
I find @tschaub's arguments quite convincing.

**Comment by gberaudo** [comment]
Looking more deeply into this, I see a clear use case for supporting saturation in WebGL.
It makes rendering colored and gray layers from a single colored source possible, in realtime:
```js
var source = new ol.source.TileWMS();
var coloredLayer = new ol.layer.Layer({source: source});
var grayLayer = new ol.layer.Layer({source: source, saturation: 0});
```
The source tiles are downloaded once, put in just one cache and rendered through two different layers. In WEBGL, this is possible without performance impact, which is a strong point for WEBGL over Canvas.

So I think at least one of the properties is useful and removing everything without distinction would be a loss for OpenLayers.

**Comment by tschaub** [comment]
@gberaudo with apologies, I am not compelled.  It would be cool if you could demonstrate how a more arbitrary transform could be applied to pixel data from more than one source to render another.  But this saturation example is of such minimal utility that it doesn't justify maintaining this code in the library.

Again, I think it would be very compelling if someone could demonstrate how to use custom shaders with the WebGL renderer.

**Comment by tschaub** [comment]
> would be a loss for OpenLayers

Yes.  This is a loss of 6,143 bytes.  Good riddance.

**Comment by elemoine** [comment]
> Yes. This is a loss of 6,143 bytes of compiled code. Good riddance.

2,941 bytes when `ol.ENABLE_WEBGL` is set to `false`.

**Comment by gberaudo** [comment]
With this feature, it is possible to share the source cache and only download tiles once for both color and gray layers. It is 3KB of library but many MB of tile bandwidth saved.

**Comment by gberaudo** [comment]
For the record, the Cesium client uses gamma for on-the-fly correction of some maps.
Gamma = 1.3 for Bing maps: https://github.com/AnalyticalGraphicsInc/cesium/blob/4fa8c23/Source/Scene/BingMapsImageryProvider.js#L124-L125.
Gamma = 1.9 for Google earth: https://github.com/AnalyticalGraphicsInc/cesium/blob/4fa8c2370f347c0aa424f9679d7b7dd977d80529/Source/Scene/GoogleEarthImageryProvider.js#L128.
