### ISSUE TITLE
Show GIF on map

### ISSUE THREAD

**Issue by Pedrazl** [openlayers/ol3#4133]
Hello,
As I can see, Openlayers doesn´t support anymore loading <b>layers from gif images</b>. Is that true or I'm missing something? 
Is there any alternative approach for that case?

**Comment by ahocevar** [comment]
You're missing something. OpenLayers can handle all types of images that your browser can handle. And gif is definitely a format that your browser can handle. See http://jsfiddle.net/ahocevar/j1zxfvda/ for an example that loads a WMS layer using gif images.

**Comment by Pedrazl** [comment]
Thanks @ahocevar. But what I mean is to load an animated gif, not a single image. On Openlayers 2 it was possible to see the sequence on the map, but now it just show one single frame...

**Comment by illogicz** [comment]
My solution for animated tile layers is to load png images containing all the frames, then splitting them up into separate custom tiles with their own canvas. You'll also need to create a custom tile source to manage and cache them.

If you simply want to display a gif over the map you could put them in an overlay.

**Comment by Pedrazl** [comment]
Thanks for your answer @illogicz. Could you please provide some code to fully understand your approach?

**Comment by fredj** [comment]
It should be possible to see the animated GIF by using the dom renderer instead of the default canvas.
See http://openlayers.org/en/v3.14.1/apidoc/ol.Map.html (`renderer` parameter)

**Comment by rkdhanyakula** [comment]
@fredj  i tried what you said, with DOM and Webgl. But its not rendering the gif sequence,

**Comment by marcjansen** [comment]
The DOM renderer was removed, see #5815

**Comment by willingSi** [comment]
@Pedrazl  hi!i am looking for a resolution of show gif over the map . Do you ever find a way ?

**Comment by rkdhanyakula** [comment]
`var ForecastTotalImages = [];

var ForecastImages = [];

var ImgNum = 0;
var ImgLength = ForecastImages.length - 1;

var delay = 250;

var lock = false;
var run;

var centerX = 110.25;
var centerY = 5.65;
zoomLvl = 4.98;

// Create map
var map = new ol.Map({
	controls: [],
	interactions: [],
    target: 'mapdiv2',  // The DOM element that will contains the map
    layers: [
        new ol.layer.Tile({
            source: new ol.source.OSM()
        })
    ],
    // Create a view centered on the specified location and zoom level
    view: new ol.View({
        center: ol.proj.transform([centerX, centerY], 'EPSG:4326', 'EPSG:3857'),
        zoom: zoomLvl
    })
});

imageLayer = new ol.layer.Image({
    opacity: 0.75,
    source: new ol.source.ImageStatic({
        url: '/resources/media/icons/img-trans.png',   	 
        projection: map.getView().getProjection(),
    imageExtent: ol.extent.applyTransform(boundaries, ol.proj.getTransform("EPSG:4326", "EPSG:3857"))
    })
});

map.addLayer(imageLayer);

function createForecast(data) {
	
	ForecastTotalImages = data.replace('[', '').replace(']', '').split(',');
		
};

function chgImg(direction) {
 
 if (document.images) {
  console.log("ImgLength" + ImgLength);
  ImgNum = ImgNum + direction;
  if (ImgNum > ImgLength) {
   ImgNum = 0;
  }
  if (ImgNum < 0) {
   ImgNum = ImgLength;
  }
  console.log("ImgNum " + ImgNum);
  console.log("direction " + direction+" "+ForecastImages[ImgNum]);

  var source = new ol.source.ImageStatic({
      url: ForecastImages[ImgNum],   	 
      projection: map.getView().getProjection(),
  imageExtent: ol.extent.applyTransform(boundaries, ol.proj.getTransform("EPSG:4326", "EPSG:3857"))
  })

  imageLayer.setProperties({source: source});
 }
};

function auto() {
 if (lock == true) {
  lock = false;
  window.clearInterval(run);
 } else if (lock == false) {
  lock = true;
  run = setInterval("chgImg(1)", delay);
 }
};

function forecast0m() {
	
	ForecastImages = [];
	
	for(i=0;i<ForecastTotalImages.length;i++)
	{
		if(ForecastTotalImages[i].indexOf("_0m_") !=-1)
		{
		ForecastImages.push(ForecastTotalImages[i]);
		}
	}
	 
	 ImgLength = ForecastImages.length - 1;

	  var firstImage = ForecastImages[0];
	  
	    var source = new ol.source.ImageStatic({
	        url: firstImage,   	 
	        projection: map.getView().getProjection(),
	    imageExtent: ol.extent.applyTransform(boundaries, ol.proj.getTransform("EPSG:4326", "EPSG:3857"))
	    })
	  
	  imageLayer.setProperties({source: source});
	  	 
};

**Comment by rkdhanyakula** [comment]
I added a Transparent Image layer, Then with basic java script changing the image source and playing in a direction.

**Comment by Pedrazl** [comment]
Hi @willingSi ,
Unfortunately right now the only way I see to do something close is the approach of @rkdhanyakula. 
Good luck!

**Comment by willingSi** [comment]
thanks anyway@Pedrazl

**Comment by ischas** [comment]
Since the DOM-renderer was removed shouldn't this issue be reopened?

**Comment by ahocevar** [comment]
There are other solutions that involve a custom `imageLoadFunction` for the image source. Instead of returning the image itself, return a canvas with a frame of the gif, which you can get using third party libraries (e.g. http://themadcreator.github.io/gifler/docs.html#animator::createBufferCanvas()).

**Comment by yungfei1989** [comment]
@ahocevar can you give a sample how to make a marker as feature from layer can use gif image which moving picture

**Comment by ahocevar** [comment]
@yungfei1989 This ticket is about loading layers from a GIF, not markers.

**Comment by 100phel** [comment]
@ahocevar "There are other solutions that involve a custom imageLoadFunction for the image source..."

I tried using your idea, but didn't manage to display the canvas on the map. Moreover, I didn't manage to display any HTMLCanvaElement on the map. Could you please, provide an example? 

Here's my code: 

```javascript
new ol.layer.Image({
    name: 'precip_layer',
    opacity: 0.8,
    zIndex: 1,
    source: new ol.source.ImageWMS({
        url: 'http://weather-services.telventdtn.com/basic/wms_v1/wms.wsgi?',
        params: {
            'REQUEST'    : 'GetAnimationFile',
            'VERSION'    : '1.3.0',
            'SERVICE'    : 'WMS',
            'STYLES'     : '',
            'LAYERS'     : 'RADAR_US_CURRENT',
            'CRS'        : 'EPSG:900913',
            'BBOX'       : '-16730536.751059378,2397065.207023127,-3629841.5992064495,8198941.401981145',
            'FORMAT'     : 'image/gif',
            'WIDTH'      : '2678',
            'HEIGHT'     : '1186',
            'FRAMEDELAY' : '20',
            'TRANSPARENT': 'TRUE'
        },
        imageLoadFunction: function (image, src) {

            var client = new XMLHttpRequest();
            client.open('GET', src, true);
            client.setRequestHeader('Authorization', "Basic " + btoa("login:password"));
            client.responseType = "arraybuffer";

            client.onload = function () {

                var byteArray = new Uint8Array(this.response);
                var blob = new Blob([byteArray], {type: "image/png"});
                var urlCreator = window.URL || window.webkitURL;
                var imageUrl = urlCreator.createObjectURL(blob);

                gifler(imageUrl)
                    .get()
                    .then(function(animator) {
                        var BufferCanvas = animator.constructor.createBufferCanvas(animator._frames[0], animator.width, animator.height);
                        animator.animateInCanvas(BufferCanvas);
                        image.setImage(BufferCanvas);
                        image.load();
                    });
            };

            client.send();
        }
    })
});
```

Thank you!
