### ISSUE TITLE
Enhance documentation with more prose

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#4135]
It'd be nice if we had more prose documentation for certain things in the library. Let's try to add more prose doc to the following things (feel free to add bad documented stuff): 

- [ ] ol.style.Text (the keys e.g. could need some love)
  - [current output](http://openlayers.org/en/master/apidoc/ol.style.Text.html)
  - [Where to edit](https://github.com/openlayers/ol3/blob/master/externs/olx.js#L6149)

**Comment by ekargee** [comment]
Where can I find default values for (e.g.) scale, textAlign? Not in style/textstyle.js?

**Comment by marcjansen** [comment]
I think these are the browser defaults… e.g. they may vary.

**Comment by tsauerwein** [comment]
The defaults are listed here:
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text

**Comment by elemoine** [comment]
Closed with https://github.com/openlayers/ol3/pull/4138.
