### ISSUE TITLE
ol.interaction.Translate doesn't fire any event

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#4146]
I've tried the following code but neither fires anything:
```javascript
var drag = new ol.interaction.Translate({
	features: collection
});
map.addInteraction(drag);

drag.on('change:active', function(evt){
	console.info(evt);
});
drag.on('change', function(evt){
	console.info(evt);
});
```
http://jsfiddle.net/jonataswalker/ugtc5ada/

**Comment by elemoine** [comment]
What kind of notifications are you expecting? Do you want events on "translate start" and "translate end"?

**Comment by jonataswalker** [comment]
"translate start" and "translate end" is exactly what I'm looking for. I'd like to know coordinates of dragging move.

**Comment by jonataswalker** [comment]
I know there are other options but shouldn't `ol.interaction.Translate` fire at least the `'change:active'` event?

**Comment by elemoine** [comment]
`change:active` is triggered when `setActive` is called.

**Comment by jonataswalker** [comment]
I see, but is there a way to know when "translate ended"?

**Comment by elemoine** [comment]
There's no easy way. We need to add "translatestart" and "translateend" events.

**Comment by jonataswalker** [comment]
Until now we have (as far as I know) three options to drag things on map:
* `ol.interaction.Modify`
* subclassing `ol.interaction.Pointer` - [example](http://openlayers.org/en/v3.9.0/examples/drag-features.html)
* `ol.interaction.Translate`

I was thinking on write some code and contribute with a PR. Would `ol.interaction.Translate` the main method on this matter?

**Comment by elemoine** [comment]
You cannot drag polygons and lines using `ol.interaction.Modify`. The `drag-features.html` example shows how to create a custom interaction, I guess it should be renamed `custom-interactions.html` or something I guess.

**Comment by jonataswalker** [comment]
All right. I'll try to write these translate events.
Thanks for now.
