### ISSUE TITLE
make install hangs on windows (phantomjs wrapper version 1.9.10)

### ISSUE THREAD

**Issue by micking** [openlayers/ol3#4152]
on windows machines a make install hangs while installing phantomjs. 
changing the version of the phantomjs wrapper in package.json  from 1.9.10 to 1.9.18 (currently the newest version) solves the issue.

**Comment by elemoine** [comment]
Feel free to submit a PR for this.

**Comment by fredj** [comment]
We're using phantomjs v1.9.19 now; this issue should be fixed.
Please re-open if it's not the case.
