### ISSUE TITLE
Map interaction KeyboardZoom and KeyboardPan doesn't work on Google Chrome 45 and Firefox

### ISSUE THREAD

**Issue by kroupaTomass** [openlayers/ol3#4155]
Hi,
i've problem with interactions KeyboardZoom and KeyboardPan in the browsers Google Chrome and Mozzila Firefox. This interactions in these browsers doesn't working, only browser where problem doesn't occure is Internet Explorer.

Interaction KeyboardZoom you can try out at this link:
http://openlayers.org/en/v3.9.0/examples/full-screen-drag-rotate-and-zoom.html

Regards,
Tomas

**Comment by elemoine** [comment]
See http://openlayers.org/en/v3.9.0/examples/accessible.html. And see the `keyboardEventTarget` Map option: http://openlayers.org/en/v3.9.0/apidoc/ol.Map.html.

**Comment by kroupaTomass** [comment]
Thanks for the help.
