### ISSUE TITLE
ol.interaction.Interaction getMap()

### ISSUE THREAD

**Issue by GeorgeNarcis** [openlayers/ol3#4169]
It seems that the ol-debug.js version comes with the getMap() function available on ol.interaction.Interaction class, however that function is missing from the release version ol.js, and a call to that function will result in error.
  Is this a bug or am I missing something ?

**Comment by bartvde** [comment]
It's not part of the API so you cannot use it as is. It will be minified in the production version.

**Comment by bartvde** [comment]
I see we have it in the API for control, is anybody against adding this to the API for interactions?

**Comment by marcjansen** [comment]
We should have it for interactions as well, I guess. +1 for adding it.
