### ISSUE TITLE
UTF Grid Support - Syntax Errors

### ISSUE THREAD

**Issue by colin1001** [openlayers/ol3#4193]
Hello,

I see that support was added for UTF grids about a year ago (https://github.com/openlayers/ol3/pull/3015).

Does support for UTF grids work for connecting raw UTF grid files to a map, or does it only work in conjunction with MBTiles? I am using Open Layers v3.9.0 and I'm trying to create a UTF grid that consumes files I'm hosting on my own server in the following format:

````
var gridLayer = new ol.layer.Tile({
    source: new ol.source.TileUTFGrid({
        url: http://45.79.165.188/utfgrid/{z}/{x}/{y}.json
    })
});
````

This is throwing a 404 error in the console log of the browser and the data is not being loaded:

````
Request URL:http://45.79.165.188/utfgrid/%7Bz%7D/%7Bx%7D/%7By%7D.json?callback=_callbacks_._0if5hhikt
Request Method:GET
Status Code:404 Not Found
````

If I go directly and visit http://45.79.165.188/utfgrid/13/2183/3051.json for example, the data shows up as expected. This method works well in Open Layers 2 using the following code:

````
var utfgrid = new OpenLayers.Layer.UTFGrid({
    url: "http://45.79.165.188/utfgrid/${z}/${x}/${y}.json",
    utfgridResolution: 4, 
});
````

Can you help me solve this problem or is what I'm doing not possible in OL3?

I've been looking at this example (http://openlayers.org/en/v3.9.0/examples/tileutfgrid.html) but the file they are pointing to is not a grid file, but is a JSON object that has a "grids" property.

Any help would be appreciated.

**Comment by colin1001** [comment]
If anyone else has the same issue, the solution can be found here:

http://oobrien.com/2015/01/openlayers-3-and-datashine/

**Comment by CaitW** [comment]
Can we get more documentation about how to use UTFGrids? Specifically, how do we use the tileJson property of the UTFGrid source / what do we do when our UTF grid provider doesn't serve a TileJSON file?

Currently a major service (Carto) doesn't provide TileJSON like Mapbox, and instead serves grid tiles like any other tile:

`http://path.to.carto/0/{z}/{x}/{y}.grid.json`

**Comment by ahocevar** [comment]
You can find the TileJSON spec here: https://github.com/mapbox/tilejson-spec/tree/master/2.2.0.

In your case, the simplest possible configuration would be
```js
new TileUTFGrid({
  tileJSON: {
    grids: 'http://path.to.carto/0/{z}/{x}/{y}.grid.json'
  } 
});
```
A pull request with doc improvements would be appreciated.

**Comment by iamvdo** [comment]
@ahocevar Nice tip, thanks!
Is there a way to make this work with tiled WMS url? (using `getMap` request and `BBOX` attribute instead)?
Or maybe another approach to add interactivity to WMS?
Thanks.

**Comment by ahocevar** [comment]
@iamvdo This is currently not possible. But maybe your server supports TMS or WMTS in addition to WMS? Then you can use it like in https://github.com/openlayers/openlayers/issues/4193#issuecomment-409464898.

**Comment by iamvdo** [comment]
@ahocevar Thanks for your quick response.
Well, I'm not responsible of the server. I'm using a public service and found out that the WMS returns UTFGrids, so I was expecting to be able to use them.
I'm a bit sad now :)

**Comment by ahocevar** [comment]
@iamvdo There's a good chance the server is a GeoServer, and GeoServer does support TMS. If you provide the service url here, we might be able to point you to a solution.
