### ISSUE TITLE
Translate interaction: unreachable/unneeded if-branch?

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#4201]
In be2e4a3 (a part of #4192) the condition of an `else if`-branch in the translate interaction has been changed because it that change in logic was 

> not drastic, avoids throwing

[Comment by @tschaub](https://github.com/openlayers/ol3/pull/4192#issuecomment-144631900)

Previousy the relevant lines read

```javascript
// …
} else if (goog.isNull(this.lastFeature_)) {
  var geom = this.lastFeature_.getGeometry();
  // …
}
```

now these lines read

```javascript
// …
} else if (this.lastFeature_) {
  var geom = this.lastFeature_.getGeometry();
  // …
}
```

I still wonder why this hasn't failed previously. Can this code ever be reached or is it useless in which case it should probably be removed?

Maybe @Morgul or @elemoine can chime in here?

**Comment by elemoine** [comment]
The provious code was incorrect. The problem was "invisible" because the translate interaction is configured with a feature collection in the `translate-features` example. We should add a test. Thanks for fixing this.
