### ISSUE TITLE
Dragbox, support Stylefunction and array of style

### ISSUE THREAD

**Issue by DavidHequet** [openlayers/ol3#4204]
Ol.interaction.dragbox only support simple ol.style.Style, it could be great to support ol.style.Style | Array.<ol.style.Style> | ol.style.StyleFunction | undefined like others interaction (select, draw...)

**Comment by ahocevar** [comment]
We'll very likely change ol.interaction.DragBox to use a div element styled with a border instead of drawing to the canvas eventually. So such a change would not live long.

**Comment by DavidHequet** [comment]
Ah ok, that's why styles are experimental API. 
Will you provide a way to apply style to the div? 

thank you

**Comment by ahocevar** [comment]
That will be pure CSS then.

**Comment by DavidHequet** [comment]
Ok, since the Dragbox will go css, i close this issue
