### ISSUE TITLE
Select features example does not work in chrome 

### ISSUE THREAD

**Issue by phrei** [openlayers/ol3#4210]
Reproduction:
1. Go to http://openlayers.org/en/v3.9.0/examples/select-features.html?q=select
2. For the Action type select "Click"
3. Click on any Polygon (Country)
--> Nothing happens

Works fine in IE 11 and FireFox.

I'm using chrome version 45.0.2454.101

I also noticed that the following functions don't work with chrome (I guess the issues are connected):

- map.forEachFeatureAtPixel 
- map.hasFeatureAtPixel

**Comment by jonataswalker** [comment]
Everything's OK here with Chrome Version 43.

![workspace 1_013](https://cloud.githubusercontent.com/assets/10571881/10244055/194ecff0-68d3-11e5-9b4f-45de31449e1d.png)

**Comment by phrei** [comment]
Thank you for the hint. I went through all my extensions and found out at that the extension called "CanvasFingerprintBlock" caused the misbehaviour.

The extension blocks the result of the function "getImageData" of a canvas (for privacy reasons). 

So I think it is not really an issue of OpenLayers.
