### ISSUE TITLE
OL3 does not support OGC WKT projection definitions with "units":"degree"

### ISSUE THREAD

**Issue by tbarsballe** [openlayers/ol3#4233]
The OGC WKT specification uses "degree" to specify units in degrees, eg:
```
GEOGCS["OS(SN)80",
    DATUM["OS_SN_1980",
        SPHEROID["Airy 1830",6377563.396,299.3249646,
            AUTHORITY["EPSG","7001"]],
        AUTHORITY["EPSG","6279"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.01745329251994328,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4279"]]
```
 
When adding such a WKD definition using proj4.defs(srs, wkt), the resulting projection definition will include `to_meter:"0.01745329251994328"` and `units:"degree"`

ol/proj/proj.js has several predefined units in `ol.proj.METERS_PER_UNIT`, including "degrees" (note the 's').
When adding a new ol.proj.Projection via a proj4 definition, OL only uses the `to_meter` value if `units` is undefined (see https://github.com/openlayers/ol3/blob/master/src/ol/proj/proj.js#L156). In this instance, OL tries to look up the units factor using `ol.proj.METERS_PER_UNIT['degree']`, which fails due to the difference of 's'.

proj.js should be updated to handle this case (perhaps a seperate check for when units is defined but not in METERS_PER_UNIT?

**Comment by ahocevar** [comment]
Can you please ticket this under https://github.com/proj4js/proj4js? Thanks.

**Comment by ahocevar** [comment]
Wait, I need to take a closer look at this.

**Comment by tbarsballe** [comment]
Yes, there are actually two distinct issues here. I have been looking into it and have created a seperate issue in proj4.js: https://github.com/proj4js/proj4js/issues/156

The ol3 issue is specifically linked to a new value def.units with an associated def.to_meter value.
