### ISSUE TITLE
ol3 V3.9.0 lol-debug.js have a error on draw lineString

### ISSUE THREAD

**Issue by kping** [openlayers/ol3#4235]
when i use LineString draw way, cannot modify  the line when i choose the line on middle, not  the change point.   ol-debug.js have this error. ol.js is right.

the chrome console is Uncaught AssertionError: Assertion failed.

**Comment by elemoine** [comment]
Fixed with https://github.com/openlayers/ol3/pull/4151.

Please verify that it works with http://openlayers.org/en/master/build/ol-debug.js.
