### ISSUE TITLE
Text fill style do not show unless they have stroke style as well.

### ISSUE THREAD

**Issue by jmekaelthas** [openlayers/ol3#4240]
Hello,

I upgraded to 3.10.0 this morning and when I run my app I have noticed that all labels disappeared.

After some research I have found the problem. If I have the fill style I also need the stroke style set for the ol.style.Text.
This is caused by this piece of code:

ol.render.canvas.TextReplay.prototype.drawText =
    function(flatCoordinates, offset, end, stride, geometry, feature) {
  if (this.text_ === '' ||
      !this.textState_ ||
      (this.textFillState_ &&
       !this.textStrokeState_)) {
    return;
  }
....

As you can see if fill style is set and stroke style is not - the method quits and does not render the text.
While the method:

ol.render.canvas.TextReplay.prototype.setTextStyle

sets the values for textFillState_ and textStrokeState_ independantly and does not require textStrokeState_ to exist if the fill is given.

As a temporal workaround I have added the stroke style to my text style
text.stroke = new ol.style.Stroke({color: 'rgba(0, 0, 0, 0)'})
just to make it work as expected.

But I am guessing it might be a bug :)

**Comment by marcjansen** [comment]
Possible regression from 31a68e21a51ee378c3698354523d185eef52f543

Previously the relevant lines looked:

```javascript
  if (this.text_ === '' ||
      goog.isNull(this.textState_) ||
      (goog.isNull(this.textFillState_) &&
       goog.isNull(this.textStrokeState_))) {
    return;
  }
```

after 31a68e21a51ee378c3698354523d185eef52f543

They look like

```javascript
  if (this.text_ === '' ||
      !this.textState_ ||
      (this.textFillState_ &&
       !this.textStrokeState_)) {
    return;
  }
```

I think it should be 

```javascript
  if (this.text_ === '' ||
      !this.textState_ ||
      (!this.textFillState_ &&
       !this.textStrokeState_)) {
    return;
  }
```

**Comment by marcjansen** [comment]
We definitely need tests for these as @tschaub already mentioned (https://github.com/openlayers/ol3/pull/4216#issuecomment-145614080)

**Comment by marcjansen** [comment]
@jmekaelthas Can you check if #4242 fixes your issue?

**Comment by jmekaelthas** [comment]
I have downloaded 3.10.1 a moment ago. The issue seems fixed :) Thanks a lot.
