### ISSUE TITLE
ol.style.Text Not Displaying Text

### ISSUE THREAD

**Issue by charliegeiger89** [openlayers/ol3#4247]
Testing out v3.10.0, I noticed that my markers with text are no longer displaying text. I have narrowed down the issue and it appears to directly relate to defining ol.style.Text without a stroke. If you define a text style without a stroke it will not display the text. If you view the cluster example you can see this bug ( http://openlayers.org/en/v3.10.0/examples/cluster.html ).

Examples: 
**Broken example**: http://jsfiddle.net/3pphebqu/
**Working example**: http://jsfiddle.net/ek4dkxmw/

**Comment by marcjansen** [comment]
Could you try v3.10.1?  I hope to have fixed this in #4242

**Comment by charliegeiger89** [comment]
That fixed it.

I tried searching but didn't come across #4242, thanks!
