### ISSUE TITLE
ZoomSlider control min/max orientation

### ISSUE THREAD

**Issue by eciuli** [openlayers/ol3#4253]
Taking into account the horizontal zoom slider control available in this example: http://openlayers.org/en/v3.10.0/examples/zoomslider.html we experienced an issue with specifying min-max values from left to right of the control. Since the horizontal control  is just a re-sized version of the vertical one.
We've experimented with CSS transform and it generates a faulty behavior in click event handler.

Is there a way to easily specify the orientation of min/max values in this control?

**Comment by ahocevar** [comment]
It is not entirely clear to me what you want to achieve - what min-max values are you talking about?

**Comment by eciuli** [comment]
We would like the horizontal slider to behave as follows:

|-------------------------|
min zoom               max zoom
max resolution       min resolution

At zoom-in the slider thumb should move to right and at zoom-out should go left. So, we were wondering if we could reverse the direction of the slider.

For the end-user the slider represents zoom values not resolutions, hence the desired behavior.
Maybe its worth mentioning that the library is not used as a standard mapping tool, but it is used to view PDFs/images tilesets.
