### ISSUE TITLE
Map not moving at MS Edge on Win10 Mobile

### ISSUE THREAD

**Issue by goshi** [openlayers/ol3#4262]
When click to the map and try to move it - nothing happens. Zoom works fine. Clicks on the overlays work fine too. 
Tested on the map on main page openlayers.org and projects for some clients

**Comment by ahocevar** [comment]
Have you tried the latest version, v3.10.1? This issue should be fixed already. Try e.g. with http://openlayers.org/en/v3.10.1/examples/simple.html.

**Comment by fredj** [comment]
Caused by #4167 (v3.10.1 if affected too).
I'm on it.

**Comment by goshi** [comment]
Nope, not works. Edge version 20.10536.1004.0

**Comment by fredj** [comment]
@goshi the issue is now fixed in the master branch. Thanks for the report.
You can tests it here: http://openlayers.org/en/master/examples/

**Comment by goshi** [comment]
Thanks, @fredj. Now it is ok!
