### ISSUE TITLE
ImageStatic at high zoom levels in Chrome

### ISSUE THREAD

**Issue by dyd81** [openlayers/ol3#4274]
The [static image example](http://openlayers.org/en/v3.10.1/examples/static-image.html) has a problem with Chrome at high zoom levels: after a certain zoom level it just disappears.
In the example, it happens at zoom 23, but I had the same thing happen in another map at a different zoom level. E.g. in [this fiddle](http://jsfiddle.net/zwwn05m3/) using a red/yellow 4x4 image with dataUrl, it happens at zoom 24.

I tried with two different versions of Chrome (*46.0.2490.71 m* and *48.0.2536.0 canary*), with the same results (see screenshots below).
I have no problem zooming to max zoom with IE (11.0.9600.18015) or Firefox (41.0.1) or Firefox Developer Edition (43.0a2).

![zoom22](https://cloud.githubusercontent.com/assets/15138318/10509014/be45d98e-732a-11e5-80bf-13b65c9753fc.PNG)
*Zoom 22*

![zoom23](https://cloud.githubusercontent.com/assets/15138318/10509015/be460cd8-732a-11e5-9052-b2cd164d486d.PNG)
*Zoom 23*

I know this is almost the opposite of [another issue](https://github.com/openlayers/ol3/issues/3712) ... strange, but this is what happens to me

**Comment by ahocevar** [comment]
This issue, like #3712, has to do with the number ranges that are available for matrix transformations on a canvas. If these number ranges are exceeded, the transformation will fail, and no image will be rendered. Usually it does not make sense to go beyond zoom level 21 anyway, so we should change the example to use a `maxZoom` of 21.
