### ISSUE TITLE
Vector Icon Example popup does not work properly with several features

### ISSUE THREAD

**Issue by geocre** [openlayers/ol3#4281]
The Vector Icon Example (http://openlayers.org/en/v3.10.1/examples/icon.html?q=icon) has only one feature. By clicking on it, an attribute is displayed in a popup window. If you use this example with several features and click one after another, the popup content is not updated; the attribute of the first feature is displayed again. Modified example with two features: https://jsfiddle.net/npu6Lp40/

**Comment by marcjansen** [comment]
I think this is related to the way the popovers of bootstrap work. This question on [SO](http://stackoverflow.com/questions/13564782/bootstrap-popover-content-cannot-changed-dynamically) looks as if some more code is needed to update the content of a popover.

Anyhow, I don't think this is an issue with OpenLayers or the example, so I'll close this issue.

**Comment by geocre** [comment]
You're right, it's not an OpenLayers issue. Anyway, here's a working example with several features: https://jsfiddle.net/5r8fk1m8/
