### ISSUE TITLE
forEachFeatureAtPixel freezes/super slow performance on ff and ie #4232

### ISSUE THREAD

**Issue by cvenzin** [openlayers/ol3#4282]
Because i cannot reopen the issue #4232 I opened a new one.
The performance for tooltips or hover interactions are very slow on Firefox and IE. Chrome is the only browser I've tested so far where these functions work fine.
Example: http://openlayers.org/en/v3.10.1/examples/kml-earthquakes.html?q=toolt

**Comment by ahocevar** [comment]
Reopened #4232, closing this.
