### ISSUE TITLE
getProjection returns null on ol.source.Vector with GeoJSON data.

### ISSUE THREAD

**Issue by roemhildtg** [openlayers/ol3#4284]
I am trying to get the projection object from the ol.source.Vector after GeoJSON data has been added to it using features property during construction. The vector and map projections may be different and when I try to get the projection for the source after it is instantiated, it returns null. 

http://jsbin.com/lekibamune/1/edit?js,console,output

Quick example: 
```javascript
     var source = new ol.source.Vector({
        features: (new ol.format.GeoJSON()).readFeatures(featureCollection, {
          dataProjection: ol.proj.get(featureCollection.crs.properties.name),
          featureProjection: this.attr('map').getView().getProjection()
        })
      });
      console.log(ol.proj.get(featureCollection.crs.properties.name)) //null
```

How can I get the projection of the vector source, or am I doing something wrong here?

**Comment by ahocevar** [comment]
The thing you're missing is that the the feature projection of the source *is* the view projection. And to get the data projection (i.e. the CRS used in your GeoJSON), use `ol.format.GeoJSON#getProjection()`. If you load your GeoJSON from a file, you can simplify the above snippet:
```js
var source = new ol.source.Vector({
  url: 'http://path/to/your.geojson' 
});
```
If you have your GeoJSON in memory already, you can also simplify the above snippet:
```js
var source = new ol.source.Vector({
  loader: function(extent, resolution, projection) {
    source.addFeatures(
        new ol.format.GeoJSON().readFeatures(featureCollection, {featureProjection: projection}));
  }
});
```
