### ISSUE TITLE
Cached WMS Options/Parameters from GetCapabilities

### ISSUE THREAD

**Issue by geekdenz** [openlayers/ol3#4285]
Noticed there is a GetCapabilities response parser for WMS. There is also a WMTS capabilities parser that gets the view and layer options/params which is nice.

However, I couldn't find a WMS capabilities to options/params function for cached WMS (MapCache). I think I could implement this and would be happy to, at least for MapServer/MapCache responses, because that is what we use. I do want to make you aware of this though and ask if you even find this worth doing/possible and sensible.

I'm particularly interested because we use WMS 1.1.1 (MapServer/MapCache) still and I am having to manually generate the view/layer options etc.

We will probably move to WMTS soon, but maybe there is still interest for this function.

See http://proxy.zen.landcareresearch.co.nz/zentilegen-a/mapcache/gen/?MAP=%2Fopt%2Fmapserver%2Fmapfiles%2Ftopobasemap.map&SERVICE=WMS&REQUEST=GetCapabilities 

```xml
<VendorSpecificCapabilities>
<TileSet>
<SRS>EPSG:2193</SRS>
<BoundingBox SRS="EPSG:2193" minx="1000000.000000" miny="4700000.000000" maxx="2200000.000000" maxy="6300000.000000"/>
<Resolutions>
8466.66209466913642245345 5644.44139644609094830230 2822.22069822304547415115 1411.11034911152273707557 705.55517455576136853779 352.77758727788068426889 176.38879363894034213445 88.19439681947017106722 35.27775872778806132146 17.63887936389403066073 8.81943968194701533037 3.52777587277880622096
</Resolutions>
<Width>256</Width>
<Height>256</Height>
<Format>image/png</Format>
<Layers>landscape_shaded_relief</Layers>
<Styles/>
</TileSet>
</VendorSpecificCapabilities>
```

Especially getting the Resolutions automatically would be nice as otherwise one has to manually get them and put them into the code or in another way store them. We currently have a Layer Configuration Service for this, but it seems like it shouldn't be necessary with the GetCapabilities response having all the information.

I did notice that these are vendor specific parameters, so am guessing that's why it hasn't been done. Maybe this shouldn't even be part of the ol3 project or maybe someone has done this already somewhere else. If you know where, please let me know.

**Comment by ahocevar** [comment]
You may want to take a look at the Jsonix ecosystem and ows.js. It will probably make more sense to use those or to contribute there.

* https://github.com/highsource/jsonix/
* https://github.com/highsource/ogc-schemas
* https://github.com/OSGeo/ows.js

As I've [thought out loud before](https://groups.google.com/d/msg/ol3-dev/IG8mdqU-joA/TMC3IhBFBGwJ), I'd prefer if OpenLayers wouldn't ship with any non-feature formats at all, but integrate well with the ows.js and ogc-schemas libraries.

**Comment by bartvde** [comment]
Right, I' ve been using the WMS-C parser from JSONIX successfully in https://github.com/MapStory/story-tools/pull/212

**Comment by WillieMaddox** [comment]
Ok. This isn't as straightforward as I thought it would be.  I can't even get the schemas to load into my scripts.  Is there any documentation explaining how to use the ogc-schemas with ol3?
