### ISSUE TITLE
Getting MAXSCALEDENOM from layer definition to setup maxResolution for WFS layers

### ISSUE THREAD

**Issue by khamyl** [openlayers/ol3#4290]
It would be nice (if it is possible) to setup the layer's max/minResolution according the MAXSCALEDENOM (mapserver) value if it exists when requesting data from server using WFS.

**Comment by ahocevar** [comment]
MAXSCALEDENOM is a WMS concept, not WFS. A WFS service never reports a max scale denominator.

**Comment by bartvde** [comment]
You can always hook up this kind of workflow at the application level. But it doesn't have any place in ol3.
