### ISSUE TITLE
Pixelworks dependency unresolved in ol-debug.js

### ISSUE THREAD

**Issue by Brictarus** [openlayers/ol3#4295]
Hi,

I cloned the ol3 repository, and checkout on tag v3.10.1.
I ran a make build, and got the ol-debug.js in the build directory.
But there's a remaining 
```javascript
require('./processor')
```
 in it, that drives me crazy. The file is not usable due to this unresolved dependency.

That dependency seems to be brought by pixelworks

Any suggestion ?

**Comment by ahocevar** [comment]
Confirmed that this is a bug when using CommonJS, in my case Browserify. Investigating...

**Comment by ahocevar** [comment]
@Brictarus Can you please check if #4297 fixes your issue?

**Comment by Brictarus** [comment]
Yup, it seems to do the job :-)
