### ISSUE TITLE
Unable to dynamically change ol.source.ImageStatic URL and imageExtent

### ISSUE THREAD

**Issue by 1Map** [openlayers/ol3#4300]
How do I dynamically change the url and imageExtent for ol.source.ImageStatic ?

**Comment by ahocevar** [comment]
You don't. If you have multiple static images, create a source for each. You can dynamically change the source of the layer:
```js
imageLayer.setSource(staticSource);
```

**Comment by 1Map** [comment]
That is what I am doing at the moment. I have a grid and when user selects
a record from grid it loads the static image from the selected record into
the map. Problem is that memory builds up as you move through the grid.
Don't you need to destroy the existing source before creating a new source?

**Comment by ahocevar** [comment]
> Problem is that memory builds up as you move through the grid. Don't you need to destroy the existing source before creating a new source?

As long as you don't reference the source anywhere when it's not used any more, the garbage collector should remove it from memory eventually.
