### ISSUE TITLE
My script not working

### ISSUE THREAD

**Issue by Amrizhan** [openlayers/ol3#4303]
Hi, I am creating local open street map on Windows, so next steps is done:
1.Postgis+OSM2POSTGIS/ so my data in postgis
2. Mapnik render tiles from generate_tiles.py
3.XAMMP (apache 2.4, not modifyed). Put my tiles into web server. localhost/osm is working

But this script didn't show me tiles as {z}/{x}/{-y}.png

![default](https://cloud.githubusercontent.com/assets/15119373/10658458/d9b7937c-78b8-11e5-838f-becdf196c527.png)

**Comment by tsauerwein** [comment]
If you've generated your tiles with the standard tilegrid, the url would be:

    url: 'http://localhost/osm/{z}/{x}/{y}.png'

See also: http://openlayers.org/en/master/apidoc/ol.source.OSM.html

**Comment by Amrizhan** [comment]
my url is the same, my tiles generated by mapnik, also i tried to use TileMill generetad tiles, result is the same

**Comment by Amrizhan** [comment]
id does not helps=(((
