### ISSUE TITLE
How to run build.py????

### ISSUE THREAD

**Issue by Amrizhan** [openlayers/ol3#4309]
Hi everybody

The question on building openlayer 3 on Windows

Where I can found build.py?
I downloaded openlayer 3.10, but didn't understand what is my next steps???
By one tutorial  I need run build.py, by next one I need to install Cygwin and something like node.exe with commands like node tasks\generate-exports.js build\exports.js

I have mapnik rendered tiles so I need just to see it in a web browser.

Pls help me to finish my project!!!

thank you!!!

**Comment by bill-chadwick** [comment]
You should be typing 'make build', 'make test' etc. after installing CygWin and GNU make. See the windows section at the bottom of here https://github.com/openlayers/ol3/blob/master/CONTRIBUTING.md

**Comment by Amrizhan** [comment]
During instalation cygwin i choose Devel, Phyton and Web, now i tried to type: 
'npm install' 'make check-deps'
but came with error like: command npm can'find and no rules for check-deps'

Sorry, I am new one on working with maps, what does it mean?

**Comment by bill-chadwick** [comment]
You might find some more info to help here

https://github.com/openlayers/ol3/issues/3648
