### ISSUE TITLE
Ability to set a custom DPI on ol.source.TileArcGISRest

### ISSUE THREAD

**Issue by Kintamasis** [openlayers/ol3#4312]
It seems that ol.layer.Tile with source new ol.source.TileArcGISRest() ignores "projection" parameter. It uses EPSG:3857 instead. Am I wrong?

My code:
```javascript
new ol.layer.Tile({
	extent: [306520.146, 5973291.050, 680103.277, 6257813.452],
	source: new ol.source.TileArcGISRest({
		url: "http://www.domain.com/some_url/MapServer/",
		params: {
			FORMAT: "png8",
			DPI: 96
		},
		projection: ol.proj.get("EPSG:3346")
	})
})
```

By the way, I can't set custom DPI also! Documentation doesn't mention I can't do that!

**Comment by bartvde** [comment]
Tiles will be requested in the view's projection.

**Comment by bartvde** [comment]
DPI parameter will be set automatically so it matches the pixelRatio used internally: https://github.com/openlayers/ol3/blob/master/src/ol/source/tilearcgisrestsource.js#L115

So you would want to set the value of 90 and have it multiplied with the device's pixelRatio?

**Comment by Kintamasis** [comment]
Thanks! Setting projection in map's view solved the issue!
I just thought it would be possible to set custom DPI like in ArcGIS JS API.

**Comment by bartvde** [comment]
Sure I think that is a valid enhancement request to be able to set the DPI. I'll update the title of this ticket to reflect that.
