### ISSUE TITLE
Switched ol.source.ImageWMS BBOX coordinates, when using some custom projection?

### ISSUE THREAD

**Issue by Kintamasis** [openlayers/ol3#4314]
My code snippet looks like this:

```javascript
new ol.layer.Image({
	source: new ol.source.ImageWMS({
		url: 'http://195.182.71.164:8080/geoserver/BP/wms',
		params: {'LAYERS': 'BP_inzinerine_infrastruktura'},
		serverType: 'geoserver',
		projection: ol.proj.get("EPSG:3346")
	})
})
```

This code generates URL:
http://195.182.71.164:8080/geoserver/BP/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=BP_inzinerine_infrastruktura&CRS=EPSG%3A3346&STYLES=&WIDTH=1871&HEIGHT=944&BBOX=296090.96544524713%2C5901662.523222233%2C867505.2989656775%2C6189965.639653706

And I get an empty image...

If I manually switch BBOX values like shown below, I get a correct one.

http://195.182.71.164:8080/geoserver/BP/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=BP_inzinerine_infrastruktura&CRS=EPSG%3A3346&STYLES=&WIDTH=1871&HEIGHT=944&BBOX=5901662.523222233%2C296090.96544524713%2C6189965.639653706%2C867505.2989656775

Is there an easy fix for this? I am new to WMS, so there may be something important I don't understand at the moment. Or is it a GeoServer issue? The problem is that this service is not mine.

**Comment by Kintamasis** [comment]
I have just found some dirty solution by looking at ol.js code. Projection must have `g` property with "ne" value in order to work properly... Is there some cleaner solution? At least it works!

**Comment by bartvde** [comment]
How do you define your projection object? Make sure you define the axisOrientation config correctly see: http://openlayers.org/en/v3.10.1/apidoc/ol.proj.Projection.html

**Comment by Kintamasis** [comment]
You are right! I was using too basic projection definition.
I have just defined my CRS with ol.proj.Projection() using proper `axisOrientation` value and it works like a charm!
Thank you again!
