### ISSUE TITLE
Problems passing to version 3.4.0 to 3.10.1

### ISSUE THREAD

**Issue by jfantunes** [openlayers/ol3#4318]
Hi!
I'm extending ol3 using google closure. I could achieve that with version 3.4.0 with no problems, but when i updated it to 3.10.1 i can see the map and interact with it but i'm getting always this errors when i initialize it:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:63342/webmapping-lib/webmapping-lib/ol3/src/ol/color/colormatrix.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:63342/webmapping-lib/webmapping-lib/ol3/src/ol/render/webgl/webglimagecolorshader.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:63342/webmapping-lib/webmapping-lib/ol3/src/ol/renderer/webgl/webglmapcolorshader.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:63342/webmapping-lib/webmapping-lib/ol3/src/ol/featureoverlay.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:63342/webmapping-lib/webmapping-lib/ol3/src/ol/tilegrid/xyztilegrid.js Failed to load resource: the server responded with a status of 404 (Not Found)

Could someone give me a clue?

**Comment by ahocevar** [comment]
Looks like you have a script loader that references files that no longer exist. All the files you listed have indeed been removed. Maybe try deleting your build directory, so outdated files get regenerated.

**Comment by jfantunes** [comment]
Sorry for the late reply Andreas. Thank you for your help, indeed i was missing some updated references. Problem solved
