### ISSUE TITLE
wrapX: false wont work on clustering source

### ISSUE THREAD

**Issue by FRizZL** [openlayers/ol3#4319]
I had a single map working with all my features (because of the wrapX option). As soon as I changed my source from Vector() to Cluster() it showed multiple features, as if there are more worlds to show. Strangely it only affects the source layer and not the map layer.
This have to be a bug, cause the docs say: Cluster() extends Vector() so wrapX has to be available in my opinion..

```javascript

... more code above here ...

var sourcePhotos = new ol.layer.Vector({
    source: new ol.source.Cluster({
        distance: 20,
        source: new ol.source.Vector({
            url: '/photo/markers', // works perfectly
            format: new ol.format.GeoJSON(),
        }),
        wrapX: false // <--- its there
    }),
    style: function (feature, resolution) {
        var size = feature.get('features').length;

        style = [new ol.style.Style({
                image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ {
                    anchor: [8, 8],
                    anchorXUnits: 'pixels',
                    anchorYUnits: 'pixels',
                    src: '/img/camera.png'
                }),
                text: new ol.style.Text({
                    text: size.toString(),
                    fill: new ol.style.Fill({
                        color: '#000'
                    }),
                    offsetX: 18
                }),
            })];
        return style;
    }
});

.. more code below here ...
```
![bug-1](https://cloud.githubusercontent.com/assets/1866925/10742194/2c4a0266-7c2c-11e5-9c3b-c42a39058490.png)

**Comment by ahocevar** [comment]
You are right, this is a bug. `olx.source.ClusterOptions` (see `externs/olx.js` should accept a `wrapX` option and pass it to the superclass. Would you be able and willing to create a pull request?

**Comment by FRizZL** [comment]
Will do.
