### ISSUE TITLE
Simplify and make less sources-consuming the feature clicked style 

### ISSUE THREAD

**Issue by spyroSlevin** [openlayers/ol3#4324]
Here is a scenario with OL3

I have a vector layer and I want the clicked feature to have different style than the rest. I want the LineStrings to have width more than 1 pixel , so they can stand out and be more easily clicked. So I will use a style function , so I can do `if (geom == 'LineString') {//set width...`

So I set the default style using a style function

    function styleFunction(feature, resolution) {
        	var color = feature.get('color');
	        var geom = feature.getGeometry().getType();

	       var fill = new ol.style.Fill({
		         color: color
	        });

	       var stroke = new ol.style.Stroke({
		       color: color,
		       lineCap: "butt",
		       lineJoin: "bevel",
		       width:1			
	         });
	
	        if (geom == 'LineString') {
		      var stroke = new ol.style.Stroke({
		            color: color,
		            width:8
	              });
	        }
	       var cStyle = new ol.style.Style({
		     fill: fill,
		     stroke: stroke
	        });

	        return [cStyle];
    }

And then I set a click event for the map

	var select = new ol.interaction.Select();
	 map.addInteraction(select);

I set the function and a style for the clicked feature

     select.on('select', function(e) {
			var ccolor = e.selected[0].get('color');
			var cgeom = e.selected[0].getGeometry().getType();		

			var cfill = new ol.style.Fill({
				color: ccolor				
			});

			if (cgeom == 'LineString') {
				var cstroke = new ol.style.Stroke({
				     color: ccolor,
				      width:14
			        });
			}else{
				var cstroke = new ol.style.Stroke({
					color: ccolor,
					lineCap: "butt",
					lineJoin: "bevel",
					width:6			
				});			
			}						
		
			var clickedStyle = new ol.style.Style({
				fill: cfill,
				stroke: cstroke
			});

			
		     var allfe = sourceVector.getFeatures();		
		     for (i in allfe){	
			   allfe[i].setStyle(styleFunction);	 //back to default
		     }	

		     e.selected[0].setStyle(clickedStyle);//reset the clicked one

    });

As you can see, I have to set another style for the clicked features. Before I apply it to the clicked feature, I have to loop through all of them and pass them the default style, and then reset the clicked style to the one feature.

Three issues
-`allfe[i].setStyle(styleFunction);` does not work. I get `Uncaught TypeError: feature.get is not a function` error, and I dont know why is that,

-you could create a "clicked" attribute for vector layers, where the style of the clicked features will be set, so developers dont have to manually set it inside the event function

-I now set the style three times. OL3 silently loop to render the `styleFunction` the first time the layer loads. Then I loop again all the features trying to set the `styleFunction` again and then I set another style to the clicked feature. What if I had a couple of hundreds features. That will defenently slow down the response and rendering times.

Thank you

**Comment by alvinlindstam** [comment]
You have already posted this on http://stackoverflow.com/q/33322722/5149997, and gotten decent replies solving your issue.
