### ISSUE TITLE
Single tile WMS re-requesting layer after every pan

### ISSUE THREAD

**Issue by StewartBellamy** [openlayers/ol3#4325]
Since 3.8 if you pan the map, even a small amount, any single tile wms layers are re-requested.

This one is working fine:
http://openlayers.org/en/v3.8.2/examples/wms-tiled.html

This re-requests the wms on every pan:
http://openlayers.org/en/v3.10.1/examples/wms-image.html

Thanks

Stewart

**Comment by marcjansen** [comment]
This are two different examples, one shows how to fetch WMS tiled, one as a single image. I don't think this is a bug, but a feature.

**Comment by StewartBellamy** [comment]
Sorry, the first link was incorrect - http://openlayers.org/en/v3.8.2/examples/wms-image.html.

My understanding was that the ImageWMS has a default ratio of 1.5.  So, the image requested is 1.5* the size of the map viewport meaning that a new image need only be requested once the user pans beyond the original image extents and not every time the user pans the map.  In the 3.8.2 example I can see (using Fiddler) that the WMS is only re-requested once the user has panned beyond the original image extents whereas in the 3.10.1 example the image is re-requested after any pan.  

I discovered this when I was implementing a 'map loading' indicator using the imageloadstart and imageloadend events.  I have a map with 7 wms overlays and it is performing poorly because all 7 layers are requested after any pan event.  When setting the ratio to a higher value I can see a larger image is requested but all the layers are re-requested after even the tiniest pan.

**Comment by ahocevar** [comment]
This is a bug. Pull request #4334 created.
