### ISSUE TITLE
Zero value of feature ID is changed to Undefined

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#4326]
One of my rendered feature has intentionally ID set to 0. Since 3.10.1 when this feature is retrieved using vectorLayer.getSource().getFeatures(), that zero value ID is converted into 'Undefined'. Should I avoid such values or is it a newly introduced bug in OL?

**Comment by ahocevar** [comment]
This is a bug, introduced with the removal of `goog.isDef` and `goog.isNull`. Thanks for reporting.

**Comment by jan-tosovsky-cz** [comment]
Thanks a lot for quick fix!
