### ISSUE TITLE
Gap between tiles in mapbox vector tile in Firefox

### ISSUE THREAD

**Issue by tonio** [openlayers/ol3#4329]
In FF on Linux & Windows (7&10, at least), there’s a vertical gap between tiles ( see #4219 )

![screenshot from 2015-10-28 11 19 51](https://cloud.githubusercontent.com/assets/21686/10789158/01cb6312-7d7c-11e5-967e-1aa61475dba9.png)

**Comment by jan-tosovsky-cz** [comment]
Similar issue to https://github.com/openlayers/ol3/issues/3799
