### ISSUE TITLE
svg icon in image style not drawn in Safari if offset is used

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#4337]
This is similar to: http://stackoverflow.com/questions/29633355/canvas-context-drawimage-differences-across-browsers

Changing the draw instruction to:

```
         context.drawImage(image, originX, originY, width - originX, height - originY,
                x, y, width * pixelRatio, height * pixelRatio);
```

fixes this issue and the icon is drawn correctly.

**Comment by timkeane** [comment]
this bug or something similar seems to have crept back into the builds 3.11.2 and 3.12.1

**Comment by bartvde** [comment]
I think https://github.com/openlayers/ol3/pull/4647 will fix this

**Comment by bartvde** [comment]
Hmm let me at least investigate whether or not this is the case

@timekeane we might have lost that fix since it caused issues just after the release, so we reverted it. I'm not sure if we picked it back up again though, will investigate.

**Comment by bartvde** [comment]
No unfortunately this is still broken, I'll open up a new issue

**Comment by timkeane** [comment]
thanks

**Comment by bartvde** [comment]
@timkeane should be in the upcoming 3.13 release which should be out this week likely.
