### ISSUE TITLE
Type mismatch in generated externs

### ISSUE THREAD

**Issue by gberaudo** [openlayers/ol3#4340]
Closure complains in OL3-Cesium with the following message:
```
ERR! compile ol3/build/ol-externs.js:3727: ERROR - mismatch of the getSource property type and the type of the property it overrides from superclass ol.layer.Layer
ERR! compile original: function (this:ol.layer.Vector): (null|ol.source.Vector)
ERR! compile override: function (this:ol.layer.VectorTile): (null|ol.source.VectorTile)
ERR! compile ol.layer.VectorTile.prototype.getSource = function() {};
```
I see that `ol.layer.VectorTile` extends `ol.layer.Vector`.
However `ol.source.VectorTile` does not extend `ol.source.Vector`.

**Comment by adube** [comment]
The same issue occurs in OL3-Google-Maps.

**Comment by gberaudo** [comment]
For information, we are no more relying on OpenLayers externs for OL3-Cesium.
Instead, we compile OL3 + OL3-Cesium code together.

**Comment by ahocevar** [comment]
@adube Can we close this?
