### ISSUE TITLE
ol.proj.transform error

### ISSUE THREAD

**Issue by naturalmechanics** [openlayers/ol3#4342]
Consider this :

for(var k = 0; k <items.length; k++) {console.log([items[k].lon,items[k].lat]);
// lon -71.4052070950878 and lat 41.7884922648353, 
	var iconFeature = new ol.Feature({	
	geometry: new ol.geom.Point(ol.proj.transform([items[k].lon,items[k].lat],'EPSG:4326','EPSG:3857')),
	name: 'null land'
	});
						
	iconFeatures.push(iconFeature);						console.log("pushing");
						
	}	

This should create a point in North America, However, point is being created in Argentina. 

Why?

Full code : http://pastebin.com/aHSvmAV5
(the coordinates are : lon -71.4052070950878 and lat 41.7884922648353)

**Comment by tsauerwein** [comment]
Are you sure that `lon` and `lat` are numbers and not strings? If not you would have to use `parseFloat` to convert.

**Comment by tsauerwein** [comment]
I just noticed that you cross-posted the question on [StackOverflow](http://stackoverflow.com/questions/33429491/urgent-openlayers-3-projection-lat-lon-to-web-mercator). So, closing this ticket to keep the discussion in one place.
