### ISSUE TITLE
ol.extent.getArea() missing from the release version

### ISSUE THREAD

**Issue by bojko108** [openlayers/ol3#4343]
Hello,
I was using ol.extent.getArea() method from OpenLayers debug library v3.10.1 to check if an extent is empty. However, the same method is undefined when I try to use the release version of the same library. Is this method only accessible through the debug version?

Thanks

**Comment by bartvde** [comment]
It's not in our API. Why not simply use getWidth and getHeight instead?

**Comment by bartvde** [comment]
Btw there is also ```ol.extent.isEmpty``` in the API

**Comment by bojko108** [comment]
Yes, I changed the logic and now I'm using isEmpty() method, but is there any reason getArea() to be missing from the release library? I'm just curious because there can be more methods missing from the library...

**Comment by bartvde** [comment]
Not all methods are defined in our API, only methods we intend to have used by our end users.
You should not use the debug library to see what is available, instead you should use our API docs instead.

**Comment by bojko108** [comment]
Thanks for the response!
