### ISSUE TITLE
Cannot override resetNorth on the ol.control.Rotate control

### ISSUE THREAD

**Issue by tamarmot** [openlayers/ol3#4348]
I have a map using lunar polar stereographic projection for the south pole, and where my view is, North is not at rotation 0.  I want to use the rotation control to indicate north, and need to override the resetNorth method as well as the render method.  ResetNorth is not exposed as overridable.

Related to issue: https://github.com/openlayers/ol3/issues/4346

**Comment by tschaub** [comment]
Fixed by #4362 (thanks @tamarmot).
