### ISSUE TITLE
Vector shapes are distorted when zoomed enough

### ISSUE THREAD

**Issue by mstrop** [openlayers/ol3#4350]
I have a problem with drawing my vector shapes - when I zoom enough, it looks like some coordinates are skipped and the shape gets distorted - see the attached picture:

![bad_shape](https://cloud.githubusercontent.com/assets/12169104/10842699/fd728fe2-7ef3-11e5-85c2-27c23f47f453.png)

The shape is loaded from geojson file, where it's defined like:

"coordinates":[[[18.58235,49.81784],[18.58545,49.81738],[18.59252,49.81296]
,[18.59279,49.80395],[18.59986,49.79953],[18.60013,49.79051]
,[18.60719,49.78609],[18.61425,49.78168],[18.61093,49.7663]
,[18.07565,49.432],[18.07509,49.43198],[18.06119,49.43289]
,[18.04734,49.43411],[18.03356,49.43564],[18.01987,49.43747]
,[18.00628,49.4396],[17.99281,49.44204],[17.98218,49.44422]]]

Working example of this is here - http://www.stropici.cz/distor/distor.html

Marek

**Comment by tschaub** [comment]
Thanks for the report and the nice test case @mstrop.  If you can pare down the data to just a single geometry that demonstrates the problem, that will make debugging even easier.

**Comment by mstrop** [comment]
Sure, no problem. Now just the geometry is there. On other hand it's not the only one causing the problem, so probably I can return the whole set for a final test.

**Comment by mstrop** [comment]
The issue is, that the first and last coords are not same.
