### ISSUE TITLE
ol.ext install should be documented

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#4351]
It's a while since I created a new build, and I've just run into a problem trying to do so. I got a dependency error that it couldn't find ol.ext/pbf. AFAICS this was because I'd upgraded to latest node packages using `npm update`; `build/ol.ext` is however created with an install script which isn't run when you do `npm update`.

AFAICS, `ol.ext` isn't documented anywhere, so I think as a minimum a section on upgrading to the latest package versions should be added to the custom build tutorial. If my comments above are right, then this should specify that people should always use `npm install` to update, not `npm update`.

**Comment by probins** [comment]
Could someone update me on the status with `ol.ext`? Was this only a temporary issue when updating from pre-ol.ext to post-, or should `build-ext.js` be run every time the source is updated?

**Comment by ahocevar** [comment]
This should be fixed now. Just make sure to run `npm install`, not `npm update` if anything does not finish during the build process.

**Comment by probins** [comment]
ok, I will add something to the custom build tutorial.
