### ISSUE TITLE
Polygon rendering bug, misses significant vertex

### ISSUE THREAD

**Issue by alvinlindstam** [openlayers/ol3#4354]
See this minimal jsfiddle: http://jsfiddle.net/s8defc0m/3/.

A simple four-vertex Polygon is displayed, but depending on zoom and center, the top edge is moving to different places. It is correct when zoomed out, but at higher zoom levels (including the initial zoom level) one of the four vertices seems to be ignored.

There is also a modified version without this issue, where the only difference is a fifth vertex with the same coordinates as the first: http://jsfiddle.net/s8defc0m/4/

Originally reported by `user3523426` at http://stackoverflow.com/questions/33432970/openlayer-distors-vector-shapes

**Comment by alvinlindstam** [comment]
See this version with only three vertices (where the zoom makes ol3 render a single line): http://jsfiddle.net/s8defc0m/5/

**Comment by ahocevar** [comment]
Maybe we should document this better, but OpenLayers (like most, if not all, Open Source geospatial libraries) requires that a polygon has its last vertex at the same coordinate as the first vertex.

**Comment by alvinlindstam** [comment]
Ah, yes. I was not aware of that.

**Comment by tschaub** [comment]
This looks like a duplicate of #4350.

The only time unclosed rings present a problem is when we do clipping in the Canvas renderer.  We could update [this code](https://github.com/openlayers/ol3/blob/7946298e676d8beab748dc3c75b52cf4840c8fe6/src/ol/render/canvas/canvasreplay.js#L195-L198) to be tolerant of unclosed rings.
