### ISSUE TITLE
Support per-layer translation for tiled image layers

### ISSUE THREAD

**Issue by zeodtr** [openlayers/ol3#4373]
Sometimes it's useful to apply translation (that is, pixel offset) to a layer (and not other layers).

For example, two line-based layers can be visually compared by translating (that is, offsetting) a layer.

For vector layers, it can be done by translating vector features. But for the tiled image layers, (for example, road traffic information tiles generated by GeoServer) it seems that there is no means to do that.

Perhaps a combination of overriden tileGrid.getTileRangeForExtentAndResolution() and         this.olLayer.on('postcompose', ...) would do the trick, but it seems hacky.

**Comment by bartvde** [comment]
http://stackoverflow.com/questions/33511975/openlayers-3-per-layer-translation-for-tiled-image-layers

**Comment by zeodtr** [comment]
bartvde, please pick one. I'll close the others.

**Comment by ahocevar** [comment]
Answered on stackoverflow.

**Comment by zeodtr** [comment]
@ahocevar No, the answer has a serious problem that I was aware of before I opened this issue. Please read the answer again. I've already commented regarding the answer.
