### ISSUE TITLE
Missing tiles in raster reprojection example

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#4380]
![screen shot 2015-11-05 at 11 51 12](https://cloud.githubusercontent.com/assets/319678/10966389/8e79f980-83b3-11e5-87f1-623fb6631f06.png)

Running into quite a few situations where no tiles are displayed for certain areas (see screenshot).
cc @petrsloup

**Comment by petrsloup** [comment]
After some debugging I realized this is actually not an issue with the reprojection.
I same the same problem at http://openlayers.org/en/master/examples/wms-custom-tilegrid-512x256.html

Looks like there is some problem (temporary?) with the WMS itself:
e.g. http://demo.boundlessgeo.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=topp%3Astates&TILED=true&WIDTH=512&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-7623269.642878361%2C3833530.4571513445%2C-6370925.371454033%2C4459702.5928635085 returns transparent image (and sometimes even `java.lang.NullPointerException` if you keep refreshing).

**Comment by bartvde** [comment]
Ah interesting, hadn't noticed this on my end.

**Comment by bartvde** [comment]
Thanks for your quick feedback!
