### ISSUE TITLE
There's no way to update min/max resolution/zoom after the view is created.

### ISSUE THREAD

**Issue by Distem** [openlayers/ol3#4398]
Hi, I'm working on a web app with ol3 and need to restrict the minimum zoom the user is able to zoom out to when some geometry is selected.
And at the moment there seems to be no way to update the min/max resolution/zoom after the view is created.

This seems to do the job:

`ol.View.prototype.setResolutionConstraint = function(options) {`
`  var resolutionConstraintInfo = ol.View.createResolutionConstraint_(options);`

`  this.maxResolution_ = resolutionConstraintInfo.maxResolution;`
`  this.minResolution_ = resolutionConstraintInfo.minResolution;`
`  this.minZoom_ = resolutionConstraintInfo.minZoom;`
`  this.constraints_.resolution = resolutionConstraintInfo.constraint;`
`}; `

`options` object being `{minResolution, maxResolution, minZoom, maxZoom}` with precedence like in the View constructor.

What do you think?

**Comment by cs09g** [comment]
anyone working on this? I even tried to use minZoom, maxZoom in the ol.Map with TileImage, then it doesn't seem to work.

**Comment by ahocevar** [comment]
What you can always do is crete a new view and assign it to the map:
```js
map.setView(new ol.View({
  center: map.getView().getCenter(),
  zoom: map.getView().getZoom(), // or other zoom level depending on your new configuration
  // your new options here
});

**Comment by Distem** [comment]
I still use my code from above - https://github.com/openlayers/ol3/commit/430ac933c39cc75c275d07d36f1d6edfd297eb50

just because I need to share the View between multiple maps (different base layers), and it's easier to update a single view then to update multiple maps.
