### ISSUE TITLE
gdal2tiles example usage

### ISSUE THREAD

**Issue by gwacker** [openlayers/ol3#4402]
Would it be possible to publish an example using an image tiled with gdal2tiles?

The examples created with gdal2tiles still use OL2 and I can't quite piece together how it works in OL3. I have a decent start but can't figure out how to calculate the center based on a transformed image height/2 and width/2 or extent. The jsfiddle example was just centered by me trying some numbers until I could see the tiles.

http://jsfiddle.net/gwacker/3qpto0yf/3/

**Comment by bartvde** [comment]
did you see this? http://gis.stackexchange.com/questions/110566/problem-in-displaying-tile-images-using-openlayers3
