### ISSUE TITLE
WMS layer shift in >= 3.11.0

### ISSUE THREAD

**Issue by jachym** [openlayers/ol3#4403]
When adding WMS layer according to example at http://openlayers.org/en/v3.10.1/examples/wms-image.html with OpenLayer 3.11, the WMS is shifted. 

3.10. Works well

For testing, see 

http://jsfiddle.net/jachymc/cw30xa9z/

**Comment by ahocevar** [comment]
Thanks for the report @jachym, this is clearly a regression.

**Comment by ahocevar** [comment]
This regression is caused by 40c1a6d11286309555c5938bd38a8266d224d754.

**Comment by tschaub** [comment]
Fixed with #4408.
