### ISSUE TITLE
Vector rendering performance regression

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#4405]
See https://groups.google.com/d/msgid/ol3-dev/56447d46.e8c9c20a.2003.32e8%40mx.google.com for a detailed report.

I'm looking into this now.

**Comment by ahocevar** [comment]
This regression is caused by 979342091ac6dae4cbb8e5e8c187a6286ed10a28.

**Comment by ahocevar** [comment]
Now looking into this. Unless @bartvde is looking already.

**Comment by ahocevar** [comment]
There must be an equality check for the previous `/* {number} */ resolution` which always evaluates to true for a new `/* {Array} */` resolution somewhere. Because a new replay is generated for each frame.

**Comment by bartvde** [comment]
I haven't looked as yet @ahocevar

**Comment by ahocevar** [comment]
Ok @bartvde, then I'll continue digging.

**Comment by bartvde** [comment]
I'm guessing http://openlayers.org/en/v3.11.0/examples/mapguide-untiled.html is broken as well due to the same change

**Comment by tschaub** [comment]
Fixed with #4412.
