### ISSUE TITLE
Broken GetFeatureInfo examples

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#4421]
I'm seeing frequent transparent tiles in the [tiled GetFeatureInfo example](http://openlayers.org/en/v3.11.1/examples/getfeatureinfo-tile.html):

![image](https://cloud.githubusercontent.com/assets/41094/11166344/a156b53a-8aec-11e5-93b4-c9cf4c4f44da.png)

And the [image layer version](http://openlayers.org/en/v3.11.1/examples/getfeatureinfo-image.html) of the same gets frequent `504`s.

When these examples do load, the cursor changes described don't happen because the responses are missing CORS headers.

**Comment by tschaub** [comment]
I've addressed the CORS issue in https://github.com/openlayers/ol3/commit/5295a22e76b1b3d57d06c75adef20dd956f42ed1#diff-2986a0d19c9f6451163c5d53f6a4e87aR11 (as part of #4420).  Not sure if it is possible to address the `504` and transparent tile issue.

**Comment by bartvde** [comment]
yes demo.boundlessgeo.com has been acting very funny lately

**Comment by fredj** [comment]
Fixed: demo.boundlessgeo.com is up again
