### ISSUE TITLE
Don't trigger the event "change:resolution" on max/min zoom

### ISSUE THREAD

**Issue by THernandez03** [openlayers/ol3#4427]
#### Settings
I have listening the event `change:resolution` on an `ol.View` and also set the limits of zoom (`minZoom and maxZoom`).

#### Problem
When i zoom-out or zoom-in on the map until reach the limit, the event is triggered even if the zoom isn't changed

I made this example (https://jsfiddle.net/he1m2t00/) to show you the problem.

---

_If you want more descriptive issue or i'm wrong just tell me_

**Comment by fredj** [comment]
What about only dispatching an event if the value changes?

**Comment by fredj** [comment]
Something like: https://github.com/openlayers/ol3/compare/master...fredj:object_change_evt

**Comment by ahocevar** [comment]
+1 @fredj.

**Comment by THernandez03** [comment]
+1... thanks a lot
