### ISSUE TITLE
Feature with big icon doesn't get selected

### ISSUE THREAD

**Issue by sanderd17** [openlayers/ol3#4430]
I dynamically generate SVG icons to show the status of some feature on the map. This often results in icons with a height of over 200px, and a width of only 40px. 

The images are anchored at the bottom, but I noticed that when I click on the top of the icon, the feature doesn't get selected. I estimate the cutoff is around 100px from the feature position.

Every time the feature status changes, I generate a new style and bind a new SVG to it through a data URI. So I don't think it's an issue with the generated SVGs.

Is it true there is a cutoff, and can the cutoff be eliminated in some way? 

_If you need a minimal example, I could probably make one, just ask for it_

**Comment by tschaub** [comment]
@sanderd17 thanks for the report.  This sounds like a bug.  Having a minimal example that reproduces the problem would be great.

**Comment by sanderd17** [comment]
Here is my minimal example: https://www.dropbox.com/s/xv9dh9vfpjvw5m6/minimal.html?dl=0

I tested it in the latest FF and Chromium, the issue appears in both. The map shows a feature at (0, 0), the feature has an icon with a width of 40px and a height of 200px. When you open the JS console of your browser, it will output how many features are selected and deselected.

So you can test that clicking on the top half of the icon never selects it.

(note that I usesJS template strings for the SVG creation, so a recent browser and recent syntax highlighting is advised).

**Comment by sanderd17** [comment]
I just noticed that the same cutoff happens for rendering too. When you pan the map so the feature coordinates are more than 100 px below the edge of the screen, the icon will disappear.
Though this is less severe IMO, it might be related

**Comment by tsauerwein** [comment]
> I just noticed that the same cutoff happens for rendering too. When you pan the map so the feature coordinates are more than 100 px below the edge of the screen, the icon will disappear.

To avoid this you can set a custom `renderBuffer` on [ol.layer.Vector](http://openlayers.org/en/master/apidoc/ol.layer.Vector.html).
