### ISSUE TITLE
Side-by-side example broken

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#4431]
On first load, not all tiles are rendered on all maps in the [side-by-side example](http://openlayers.org/en/master/examples/side-by-side.html)

![image](https://cloud.githubusercontent.com/assets/41094/11194628/573daaba-8c6a-11e5-9d8a-4cad1b993281.png)

**Comment by fredj** [comment]
b57cdb730c5b57450a2f9adcca44038994181165 is the first bad commit

See #3895

**Comment by fredj** [comment]
fixed with #4536
