### ISSUE TITLE
Tissot example broken

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#4432]
The [Tissot example](http://openlayers.org/en/master/examples/tissot.html) doesn't look good:

![image](https://cloud.githubusercontent.com/assets/41094/11196402/0bb60948-8c74-11e5-8fec-760c95d76853.png)

Haven't dug to see if this is just an issue with the underlying service.  See #4431 for another example with multiple maps that is broken.  See #4421 for another example using this service that is broken.  Not sure which is related.

**Comment by ahocevar** [comment]
I'm going to see if this can be fixed on the Boundless side of things - looks like demo.boundlessgeo.com has hickups.

**Comment by ahocevar** [comment]
demo.boundlessgeo.com is working reliably again, and I'm in the process of establishing a maintenance duty for that server so it doesn't happen again. I'm also going to update the examples that use it to make use of its built-in GeoWebCache, to take load off the server.

**Comment by fredj** [comment]
It's fixed (this issue was not related to #4431)
