### ISSUE TITLE
ol.Map#forEachLayerAtPixel is broken for image and tile layers

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#4437]
The bug can be reproduced with the getfeatureinfo-image and getfeatureinfo-tile examples. It looks like the transforms used to get the image data for the specified pixel are wrong.

**Comment by tsauerwein** [comment]
In the console I am getting: "Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.".

Is this maybe related to the changes to the "demo.boundlessgeo.com" server?

**Comment by ahocevar** [comment]
@tsauerwein No, this is because the value for `crossOrigin` needs to be `'anonymous'`, not `''`. See my https://github.com/openlayers/ol3/commit/5295a22e76b1b3d57d06c75adef20dd956f42ed1#commitcomment-14438868.

**Comment by tsauerwein** [comment]
Sorry, I missed that comment. But I tested with `anonymous` (on branch strapless) and the examples work correctly (that is the mouse cursor changes when you hover a non-transparent pixel).

**Comment by ahocevar** [comment]
@tsauerwein It looks like it's only broken for HiDPI devices, so something must be wrong with the way pixelRatio is (not) handled.

**Comment by ahocevar** [comment]
@tsauerwein If you don't have a physical HiDPI device, zoom the page on Chrome with Ctrl-+ to e.g. 150%, and reload the page. Then you should see the issue.

**Comment by fredj** [comment]
The empty string needs to be allowed, from the spec: "The empty string is also a valid keyword, and maps to the Anonymous state"
See http://www.w3.org/TR/html5/infrastructure.html#cors-settings-attribute

**Comment by ahocevar** [comment]
@fredj So the checks we have for `if (crossOrigin)` need to be changed to `if (crossOrigin !== undefined)`. That will fix the regression.

**Comment by fredj** [comment]
@ahocevar yes, it should fix it

**Comment by ahocevar** [comment]
@fredj See #4439.

**Comment by fredj** [comment]
@ahocevar fixed with #4439 ?

**Comment by ahocevar** [comment]
@fredj The HiDPI issue is not fixed yet.

**Comment by bartvde** [comment]
@ahocevar do you have any plans to fix this before the 3.12 release or not?

**Comment by ahocevar** [comment]
I probably won't have time @bartvde.

**Comment by marcjansen** [comment]
Running into the hidpi issue right now. @ahocevar, if you don't have time to look into this, can you outline where you would attempt to fix this? Thanks.

**Comment by ahocevar** [comment]
@marcjansen I think the issue is different for image and tile layers, but I'd start searching for the problem in the layer renderer's `forEachLayerAtPixel` methods. Unfortunately I don't have time right now to investigate this better.

**Comment by marcjansen** [comment]
Ok, good to know. Thanks, Andreas.

**Comment by ahocevar** [comment]
The remaining issue now has its own ticket #5601, so I'm closing this one.
