### ISSUE TITLE
crossOrigin valid type

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4438]
[`crossOrigin`](https://github.com/openlayers/ol3/blob/v3.11.1/externs/olx.js#L3975)  type may be `null`, `string` or `undefined`; what's the reason to accept `null`?

**Comment by ahocevar** [comment]
As far as I remember, the reason was to allow to unset  crossOrigin for sources where the default is 'anonymous', e.g. ol.source.OSM.

**Comment by bartvde** [comment]
@fredj is this still relevant after the merge of #4439 ?

**Comment by fredj** [comment]
There's no difference between having `crossOrigin` `null` or `undefined`.
We can keep the externs as it.
(thanks for the reminder @bartvde)
