### ISSUE TITLE
Earthquake clusters example broken since v3.11.0

### ISSUE THREAD

**Issue by dtreiter** [openlayers/ol3#4441]
The earthquake cluster example has an issue when hovering over a cluster.

## Expected behavior
Should display the features which are part of the cluster.

## Actual behavior
Rapidly blinks between showing the individual features and showing the cluster when the mouse is moving through a cluster's circle.

Verified in Chrome and Firefox.

## To reproduce
Go the earthquake cluster example and mouse over a cluster:
[Earthquake Example](http://openlayers.org/en/v3.11.1/examples/earthquake-clusters.html?q=cluster)

Note that this seems to be working prior to v3.11.0. For example, v3.10.1 is fine.
[v3.10.1 Example](http://openlayers.org/en/v3.10.1/examples/earthquake-clusters.html?q=cluster)

**Comment by ahocevar** [comment]
Thanks for the great bug report. This looks like a regression, and i already have an idea what might be causing it. I'll investigate more after getting some sleep.

**Comment by ahocevar** [comment]
I am working on this right now.
