### ISSUE TITLE
Init google map v3

### ISSUE THREAD

**Issue by nsuprin** [openlayers/ol3#4443]
Hi,
On my web site, my map doesn't load, i get an empty grey background.
I have the same issue on this exemple : http://dev.openlayers.org/examples/google.html

If I switch on satellite, it loads, and then, if i switch to another layer, it loads succesfully...
So I temporaly configured my map with this sattelite default layer. But I really need to have a default "street" layer.

**Comment by DLaskov** [comment]
I have the same problem.
Maybe Google has changed something? But anyway, now all my maps does not work!!!

**Comment by bartvde** [comment]
OpenLayers 3 (this bug tracker) has no Google Maps support.

**Comment by bartvde** [comment]
see: https://github.com/openlayers/openlayers/issues/1450#issuecomment-157611045
