### ISSUE TITLE
Change fullscreen icon

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#4445]
This came up in a Twitter discussion:

https://twitter.com/01241/status/666901750557892609

Proposal is: http://fiddle.jshell.net/Markus_Steiger/8q4mtxL3/

I agree that the new icon is better, what do others think?

**Comment by ahocevar** [comment]
Agreed. Strange to get this as tweet instead of a pull request though.

**Comment by bartvde** [comment]
Working on PR now on this one.

**Comment by ahocevar** [comment]
Instead of the implementation in the fiddle, I'd suggest using a different label:

⤢
NORTH EAST AND SOUTH WEST ARROW
Unicode: U+2922, UTF-8: E2 A4 A2
