### ISSUE TITLE
Cannot create ol.source.TileWMS with only tileLoadFunction in version 3.11.1

### ISSUE THREAD

**Issue by jmekaelthas** [openlayers/ol3#4446]
I just upgraded to version 3.11.1 from 3.10.1.
Unfortunately I cannot create ol.source.TileWMS without 'url' or 'urls' parameter in options.
The error comes from this method:
ol.source.TileWMS.prototype.resetCoordKeyPrefix_
It tries to iterate over 'this.urls' array which is actually null.
Previously this method iterated on 'this.urls_' and it worked fine.

**Comment by bartvde** [comment]
looks like a regression from: https://github.com/openlayers/ol3/commit/4784b7f2e232489b574ab10a6301b1825a9f7db1#diff-bb813c61da61d2bf1fe0544f3ca4626a

**Comment by fredj** [comment]
`this.urls` was previously always and array; now it may be null

**Comment by bartvde** [comment]
going to create a PR now, unless you're already doing so @fredj

**Comment by fredj** [comment]
I've already started to do it ...

**Comment by bartvde** [comment]
okay please continue
