### ISSUE TITLE
`ol.events.condition.click(evt)` always returns false

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#4453]
To answer this [question](http://stackoverflow.com/q/33783420/4640499) I came up this `ol.interaction.Draw#condition` function:
```javascript
function drawCondition(evt) {
  var ctrl = ol.events.condition.platformModifierKeyOnly(evt);
  //var click = evt.type == 'pointerdown';
  var click = ol.events.condition.click(evt);
  console.info('ctrl key: ' + ctrl);
  console.info('clicked: ' + click);
  return ctrl && click;
}
```
But `ol.events.condition.click(evt)` is always false because [of](https://github.com/openlayers/ol3/blob/v3.11.0/src/ol/events/condition.js#l72):
```javascript
ol.events.condition.click = function(mapBrowserEvent) {
  return mapBrowserEvent.type == ol.MapBrowserEvent.EventType.CLICK;
};
```
`mapBrowserEvent.type` is `'pointerdown'` while `ol.MapBrowserEvent.EventType.CLICK` is `'click'`.

Fiddle - http://jsfiddle.net/jonataswalker/q4kdfx74/

**Comment by fredj** [comment]
The problem is that `evt` is a `ol.MapBrowserPointerEvent` not a `ol.MapBrowserEvent`

**Comment by fredj** [comment]
In `ol.MapBrowserPointerEvent`, `click` and `touchstart` event are normalized to `pointerdown` 

Your proposal to use ```var click = evt.type == 'pointerdown';``` is correct

**Comment by jonataswalker** [comment]
But according to `ol.interaction.Draw` [docs](http://openlayers.org/en/v3.11.0/apidoc/ol.interaction.Draw.html) `evt` is a `ol.MapBrowserEvent`. And I guess everyone will tend to check on `ol.events.condition.click(evt)`.

**Comment by jonataswalker** [comment]
@fredj would you mind to argue my last comment so we can finish this?
Maybe a documentation change?

**Comment by MarByteBeep** [comment]
As of 2020 the documentation still is incorrect. I ran into the exact same issue
