### ISSUE TITLE
Google (v3) Layer Example not working

### ISSUE THREAD

**Issue by bsmpeter** [openlayers/ol3#4454]
for some reason, Google map in Openlayers is not working. We are using OL 2, and I found that OL 3 has the same issue.
http://dev.openlayers.org/examples/google.html

**Comment by adube** [comment]
OpenLayers 2.13.1 is known to not work with Google Maps 3.21+.  It worked with version 3.20, but it just got [deprecated by Google yesterday](https://groups.google.com/forum/#!topic/google-maps-js-api-v3-notify/prpOYuTs6jk).  Apparently, [reverting to OpenLayers 2.11](http://osgeo-org.1560.x6.nabble.com/Openlayers-2-13-1-Google-maps-not-showing-recently-Sep-2015-td5222280.html) was a known working solution.  See this [example of OL2.11](http://dev.openlayers.org/releases/OpenLayers-2.11/examples/google-v3.html).

For OpenLayers 3, Google is not an official supported source.  There has been an example back in v3.0, but it was removed thereafter and discouraged to combine both.  There's a third-party library that tries to combine the two of them: [OL3-Google-Maps](https://github.com/mapgears/ol3-google-maps).  Feel free to check it out and try it.

**Comment by bartvde** [comment]
see also: https://github.com/openlayers/openlayers/issues/1450#issuecomment-157977067 in case you're using OpenLayers 2
