### ISSUE TITLE
Performance of WMTS Dimension changes

### ISSUE THREAD

**Issue by thomasmoelhave** [openlayers/ol3#4455]
#4389 was recently merged and provides improved handling of WMTS layers when the dimensions change.  #4389 is a reworked version of #3660 that (amont other things) much more closely aligns with ol3 coding and documentation conventions. However, much effort went into tuning the perceived performance of #3660 and the performance of the currently merged solution based on #4389 does not achieve the same performance.

I adjusted the #3660 example to use a window of the same size as the new dynamic WMTS dimension example in ol3 master to allow for an apples-to-apples comparison, so if you fire up `examples/wmts-dimensions.html` from ol3 master and compare it to http://scalgo.com/stuff/ol3/build/examples/smooth-params-big.html at the same window size you can compare them directly.

Zoom in on some area, e.g. the Netherlands and the eastern UK and drag the sea-level slider continuously, and at a decent speed, from one end of the slider range to the other. You should notice a significant decrease in perceived performance. As a result, certain tiles "get stuck" for longer periods in the new version resulting in visible tile boundaries as shown in the attached figure. 
![d3e5f280-8e0d-11e5-8f37-ed7b44d5a70a](https://cloud.githubusercontent.com/assets/179143/11251196/84117298-8e30-11e5-83ba-3da6011a4571.png)
These glitches also appear in #3660, but they persist for much longer in this version. The combined result of this is a degradation of the user experience and the feeling that everything is slow, which is unfortunate as this goes against the fundamental appeal of dynamic WMTS dimensions. I have tested this in both Firefox and Chromium on Ubuntu 14.04.

At the moment I don't understand the structure of @elemoine's work to the extend that I can point to a particular thing that causes this issue, but it's probably worth looking into as the user experience could be better and this patch likely makes it much harder to apply the other patch at the same time. It might be something trivial, or something fundamental.

@elemoine are you already aware of any low-hanging fruit, or of ideas from #3660 that you were unable to port over that I could have a look at?

**Comment by thomasmoelhave** [comment]
We are still stuck on v3.7 due to this issue (since we can no longer cleanly apply our own version due to conflicts with the current solution), so I spent a little more time investigating the perfomance regression.

Specifically I looked at the the network tab in Chromium on Linux while draggin the sea-level slider in the version at http://scalgo.com/stuff/ol3/build/examples/smooth-params-big.html that implements our original submission in #3660 with the version from the latest release at http://openlayers.org/en/latest/examples/wmts-dimensions.html.

### current ol3 version
![selection_050](https://cloud.githubusercontent.com/assets/179143/16803790/b4550936-4908-11e6-9546-aa4f5692c723.png)

### #3660 version
![selection_049](https://cloud.githubusercontent.com/assets/179143/16803793/b6947416-4908-11e6-801f-c65f7f22e6a5.png)

It strikes me that the current version is not dropping requests at the right time when the threshold changes. Ideally we should be seeing a monotonically increasing sequence of WMTS dimension values (assuming the slider is dragged to the right), and that's what we see in #3660, but not in the current version).

@elemoine / @tschaub  I'd love to hear your thoughts on whether this is the expected behavior - and if you have any ideas on how it could be improved?

**Comment by ahocevar** [comment]
This might be related to the general observation of #5532 that tile requests do not get aborted. Any help with finding a fix for that would be much appreciated.

**Comment by thomasmoelhave** [comment]
@ahocevar I think this particular case is simpler. We don't have to abort requests that have already been made, and indeed, the #3660-version does not attempt that either.  However, we do have to careful about not scheduling new request for tiles that have already been deprecated by a subsequent change in dimension, and I think that's the problem here.

**Comment by ahocevar** [comment]
Please test, but I think you are right and #5595 should fix this issue.

**Comment by thomasmoelhave** [comment]
Hello @ahocevar.  Your fix is a huge improvement, it is much faster now. We have tested on chrome/ff/ie and on a big 4k display to get an idea of the performance. If it doesn't cause issues elsewhere (I have not noticed any) then I definitely think it should be merged.

However, even with your patch, the perceived performance is still lower than the #3660 version. It can be seen in particular when dragging the slider in the example at medium speed. I think this is caused by the handling of outdated tiles. In #3660 we use a sequence number per tile to determine if a tile that arrived from the server is newer than what's currently shown - and if it is we submit the tile for rendering. This happens even if the dimension has changed in the interim ([here's the code](https://github.com/openlayers/ol3/commit/cbc8e7e57a037b8d836a240ed6f9a796058c21be#diff-c4373b774a597750cb202cf726c7303fR294)). 
I think that the behavior of the current ol3 version is different in that successfully retrieved tiles are discarded if the dimension has changed since the request was made, is that correct?
This means that the during a drag action, the user sees only the initial rendering, and the final rendering - with no visual feedback during the slider drag. In #3660 the map renders the tiles as they arrive (taking care to not display tiles that arrive out of sequence) which means that the map is changing with the slider and this makes a decent difference in terms of perceived performance. This effect is more pronounced on full screen renderings and on slower connections.

**Comment by thomasmoelhave** [comment]
@ahocevar  thanks again for spending time on this issue.
I am still interested in addressing the concern about rendering the interim tiles that I mentioned in my previous comment but I'm not sure exactly where to start For instance, where are the incoming tiles "outdated" tiles discarded, and what's the interactions involving interim tiles. I've been sifting through the code but if  you could point me in the right direction @ahocevar  (or others) I could spend some time on trying to change the behavior.

**Comment by ahocevar** [comment]
@thomasmoelhave I cannot spend more time on this, but I think on top of what we have now after merging #5595, you should be able to achieve the performance from #3660 by bringing back your highest sequence number handling, and applying it to ´ol.Tile#interimTile` (which is what was `outOfBandTile` in your code. In addition, you'll need a `getInterimTile` function, which will give you the interim tile with the highest sequence number, instead of the direct interim tile of the current tile.

**Comment by thomasmoelhave** [comment]
@ahocevar yeah I understand - that's why I'll try to bring this forward on my own.
However, the coaching is appreciated though, thanks! I'll see what I can come up with.
