### ISSUE TITLE
how to change view's projection when add layers with different projction

### ISSUE THREAD

**Issue by topwood** [openlayers/ol3#4456]
I  have many wmts serives with two different projetions such like "epsg:4326" and "epsg:3857" ,and i want to add them to my openlayer map. I used to use map.setView() to set the view directly, but it is not a kind way i think. In cesium，when i add a layer, i just set the projection type 'WebMercatorTilingScheme' or 'GeographicTilingScheme'  ,when i remove a layer, i dont need to set my viewer.But in openlayers, i need to get the top layer and set the view by my self. How can i do?
thank you!

**Comment by bartvde** [comment]
Look into 3.11 which includes raster reprojection

**Comment by topwood** [comment]
@bartvde thank you very much, i have seen the example!

**Comment by petrsloup** [comment]
Raster reprojection tutorial is now online: http://openlayers.org/en/master/doc/tutorials/raster-reprojection.html
