### ISSUE TITLE
ol.interaction.Select not being notified

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#4459]
Hi devs,

To answer this [question](http://stackoverflow.com/q/33777429/4640499) I'm trying a solution that adds (based on some conditions) a `ol.Feature` to a collection like the old `ol.FeatureOverlay`.

Also I have an `ol.interaction.Select` that reads from that same collection. If I register this listener:
```javascript
collection.on('change:length', function(evt) {
  if (collection.getLength() > 0) {
    var feature = hoverInteraction.getFeatures().item(0);
    console.info('feature in select interaction: ', feature.getId());
  }
});
```
I see what I expect, but on this other listener I'm not being notified:
```javascript
hoverInteraction.on('select', function(evt) {
  console.info(evt.selected);
  if(evt.selected.length > 0){
    console.info('selected: ' + evt.selected[0].getId());
  }
});
```
Fiddle - http://jsfiddle.net/jonataswalker/ad8rzsyn/. Open console.

**Comment by fredj** [comment]
In the Fiddle, the interaction is not added to the map: `map.addInteraction(hoverInteraction);`

**Comment by jonataswalker** [comment]
Uuh ... thanks @fredj.
