### ISSUE TITLE
ol.format.WMTSCapabilities can't read getcapabilities xml without namespace 'ows'

### ISSUE THREAD

**Issue by topwood** [openlayers/ol3#4467]
My getcapabilities response xml has no namespace at all,for example as a part of xml:
``` 
<Layer>
            <Title>eva</Title>
            <Abstract>eva</Abstract>
            <Identifier>eva</Identifier>
            <WGS84BoundingBox>
                <LowerCorner>-180.0 -90.0</LowerCorner>
                <UpperCorner>180.0 90.0</UpperCorner>
            </WGS84BoundingBox>
            <BoundingBox>
                <LowerCorner>-180.0 -90.0</LowerCorner>
                <UpperCorner>180.0 90.0</UpperCorner>
            </BoundingBox>
            <Style>
                <Identifier>default</Identifier>
            </Style>
            <Format>tiles</Format>
            <TileMatrixSetLink>
                <TileMatrixSet>c</TileMatrixSet>
            </TileMatrixSetLink>
        </Layer>
```
and the parser can not read it rightly.why? Is every getcapabilities reponse need a namespace?
I am a new fish in gis and ol3. Thankyou very much..

**Comment by bartvde** [comment]
Can you show your full GetCapabilities XML?

**Comment by topwood** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Capabilities
    xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://schemas.opengis.net/wmts/1.0.0/wmtsGetCapabilities_response.xsd"
    version="1.0.0" xmlns="http://www.opengis.net/wmts/1.0"
    xmlns:ows="http://www.opengis.net/ows/1.1"
    xmlns:gml="http://www.opengis.net/gml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink">
    <ServiceIdentification>
        <Title>xxx</Title>
        <Abstract>xx</Abstract>
        <Keywords>
            <Keyword>OGC</Keyword>
        </Keywords>
        <ServiceType codeSpace="wmts"/>
        <ServiceTypeVersion>1.0.0</ServiceTypeVersion>
        <Fees>none</Fees>
        <AccessConstraints>none</AccessConstraints>
    </ServiceIdentification>
    <ServiceProvider>
        <ProviderName>xxxxxx</ProviderName>
        <ProviderSite>http://www.tianditu.com</ProviderSite>
        <ServiceContact>
            <IndividualName>Mr Liu</IndividualName>
            <PositionName>Software Engineer</PositionName>
            <ContactInfo>
                <Phone>
                    <Voice>010-88187700</Voice>
                    <Facsimile>010-88187700</Facsimile>
                </Phone>
                <Address>
                    <DeliveryPoint>xxxx</DeliveryPoint>
                    <City>xxx</City>
                    <AdministrativeArea>xxx</AdministrativeArea>
                    <Country>xxx</Country>
                    <PostalCode>101399</PostalCode>
                    <ElectronicMailAddress>tianditu.com</ElectronicMailAddress>
                </Address>
                <OnlineResource xlink:type="simple" xlink:href="http://www.tianditu.com"/>
            </ContactInfo>
        </ServiceContact>
    </ServiceProvider>
    <OperationsMetadata>
        <Operation name="GetCapabilities">
            <DCP>
                <HTTP>
                    <Get xlink:href="http://t0.tianditu.com/eva_c/wmts?">
                        <Constraint name="GetEncoding">
                            <AllowedValues>
                                <Value>KVP</Value>
                            </AllowedValues>
                        </Constraint>
                    </Get>
                </HTTP>
            </DCP>
        </Operation>
        <Operation name="GetTile">
            <DCP>
                <HTTP>
                    <Get xlink:href="http://t0.tianditu.com/eva_c/wmts?">
                        <Constraint name="GetEncoding">
                            <AllowedValues>
                                <Value>KVP</Value>
                            </AllowedValues>
                        </Constraint>
                    </Get>
                </HTTP>
            </DCP>
        </Operation>
    </OperationsMetadata>
    <Contents>
        <Layer>
            <Title>eva</Title>
            <Abstract>eva</Abstract>
            <Identifier>eva</Identifier>
            <WGS84BoundingBox>
                <LowerCorner>-180.0 -90.0</LowerCorner>
                <UpperCorner>180.0 90.0</UpperCorner>
            </WGS84BoundingBox>
            <BoundingBox>
                <LowerCorner>-180.0 -90.0</LowerCorner>
                <UpperCorner>180.0 90.0</UpperCorner>
            </BoundingBox>
            <Style>
                <Identifier>default</Identifier>
            </Style>
            <Format>tiles</Format>
            <TileMatrixSetLink>
                <TileMatrixSet>c</TileMatrixSet>
            </TileMatrixSetLink>
        </Layer>
        <TileMatrixSet>
            <Identifier>c</Identifier>
            <SupportedCRS>EPSG:4326</SupportedCRS>
            <TileMatrix>
                <Identifier>1</Identifier>
                <ScaleDenominator>2.958293554545656E8</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>2</MatrixWidth>
                <MatrixHeight>1</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>2</Identifier>
                <ScaleDenominator>1.479146777272828E8</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>4</MatrixWidth>
                <MatrixHeight>2</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>3</Identifier>
                <ScaleDenominator>7.39573388636414E7</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>8</MatrixWidth>
                <MatrixHeight>4</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>4</Identifier>
                <ScaleDenominator>3.69786694318207E7</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>16</MatrixWidth>
                <MatrixHeight>8</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>5</Identifier>
                <ScaleDenominator>1.848933471591035E7</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>32</MatrixWidth>
                <MatrixHeight>16</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>6</Identifier>
                <ScaleDenominator>9244667.357955175</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>64</MatrixWidth>
                <MatrixHeight>32</MatrixHeight>
            </TileMatrix>                
			    <TileMatrix>
                <Identifier>7</Identifier>
                <ScaleDenominator>4622333.678977588</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>128</MatrixWidth>
                <MatrixHeight>64</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>8</Identifier>
                <ScaleDenominator>2311166.839488794</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>256</MatrixWidth>
                <MatrixHeight>128</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>9</Identifier>
                <ScaleDenominator>1155583.419744397</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>512</MatrixWidth>
                <MatrixHeight>256</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>10</Identifier>
                <ScaleDenominator>577791.7098721985</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>1024</MatrixWidth>
                <MatrixHeight>512</MatrixHeight>            
            </TileMatrix>
        </TileMatrixSet>
    </Contents>
</Capabilities>

**Comment by topwood** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<Capabilities
    xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://schemas.opengis.net/wmts/1.0.0/wmtsGetCapabilities_response.xsd"
    version="1.0.0" xmlns="http://www.opengis.net/wmts/1.0"
    xmlns:ows="http://www.opengis.net/ows/1.1"
    xmlns:gml="http://www.opengis.net/gml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink">
    <ServiceIdentification>
        <Title>xxx</Title>
        <Abstract>xx</Abstract>
        <Keywords>
            <Keyword>OGC</Keyword>
        </Keywords>
        <ServiceType codeSpace="wmts"/>
        <ServiceTypeVersion>1.0.0</ServiceTypeVersion>
        <Fees>none</Fees>
        <AccessConstraints>none</AccessConstraints>
    </ServiceIdentification>
    <ServiceProvider>
        <ProviderName>xxxxxx</ProviderName>
        <ProviderSite>http://www.tianditu.com</ProviderSite>
        <ServiceContact>
            <IndividualName>Mr Liu</IndividualName>
            <PositionName>Software Engineer</PositionName>
            <ContactInfo>
                <Phone>
                    <Voice>010-88187700</Voice>
                    <Facsimile>010-88187700</Facsimile>
                </Phone>
                <Address>
                    <DeliveryPoint>xxxx</DeliveryPoint>
                    <City>xxx</City>
                    <AdministrativeArea>xxx</AdministrativeArea>
                    <Country>xxx</Country>
                    <PostalCode>101399</PostalCode>
                    <ElectronicMailAddress>tianditu.com</ElectronicMailAddress>
                </Address>
                <OnlineResource xlink:type="simple" xlink:href="http://www.tianditu.com"/>
            </ContactInfo>
        </ServiceContact>
    </ServiceProvider>
    <OperationsMetadata>
        <Operation name="GetCapabilities">
            <DCP>
                <HTTP>
                    <Get xlink:href="http://t0.tianditu.com/eva_c/wmts?">
                        <Constraint name="GetEncoding">
                            <AllowedValues>
                                <Value>KVP</Value>
                            </AllowedValues>
                        </Constraint>
                    </Get>
                </HTTP>
            </DCP>
        </Operation>
        <Operation name="GetTile">
            <DCP>
                <HTTP>
                    <Get xlink:href="http://t0.tianditu.com/eva_c/wmts?">
                        <Constraint name="GetEncoding">
                            <AllowedValues>
                                <Value>KVP</Value>
                            </AllowedValues>
                        </Constraint>
                    </Get>
                </HTTP>
            </DCP>
        </Operation>
    </OperationsMetadata>
    <Contents>
        <Layer>
            <Title>eva</Title>
            <Abstract>eva</Abstract>
            <Identifier>eva</Identifier>
            <WGS84BoundingBox>
                <LowerCorner>-180.0 -90.0</LowerCorner>
                <UpperCorner>180.0 90.0</UpperCorner>
            </WGS84BoundingBox>
            <BoundingBox>
                <LowerCorner>-180.0 -90.0</LowerCorner>
                <UpperCorner>180.0 90.0</UpperCorner>
            </BoundingBox>
            <Style>
                <Identifier>default</Identifier>
            </Style>
            <Format>tiles</Format>
            <TileMatrixSetLink>
                <TileMatrixSet>c</TileMatrixSet>
            </TileMatrixSetLink>
        </Layer>
        <TileMatrixSet>
            <Identifier>c</Identifier>
            <SupportedCRS>EPSG:4326</SupportedCRS>
            <TileMatrix>
                <Identifier>1</Identifier>
                <ScaleDenominator>2.958293554545656E8</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>2</MatrixWidth>
                <MatrixHeight>1</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>2</Identifier>
                <ScaleDenominator>1.479146777272828E8</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>4</MatrixWidth>
                <MatrixHeight>2</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>3</Identifier>
                <ScaleDenominator>7.39573388636414E7</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>8</MatrixWidth>
                <MatrixHeight>4</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>4</Identifier>
                <ScaleDenominator>3.69786694318207E7</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>16</MatrixWidth>
                <MatrixHeight>8</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>5</Identifier>
                <ScaleDenominator>1.848933471591035E7</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>32</MatrixWidth>
                <MatrixHeight>16</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>6</Identifier>
                <ScaleDenominator>9244667.357955175</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>64</MatrixWidth>
                <MatrixHeight>32</MatrixHeight>
            </TileMatrix>                
			    <TileMatrix>
                <Identifier>7</Identifier>
                <ScaleDenominator>4622333.678977588</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>128</MatrixWidth>
                <MatrixHeight>64</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>8</Identifier>
                <ScaleDenominator>2311166.839488794</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>256</MatrixWidth>
                <MatrixHeight>128</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>9</Identifier>
                <ScaleDenominator>1155583.419744397</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>512</MatrixWidth>
                <MatrixHeight>256</MatrixHeight>
            </TileMatrix>
            <TileMatrix>
                <Identifier>10</Identifier>
                <ScaleDenominator>577791.7098721985</ScaleDenominator>
                <TopLeftCorner>90.0 -180.0</TopLeftCorner>
                <TileWidth>256</TileWidth>
                <TileHeight>256</TileHeight>
                <MatrixWidth>1024</MatrixWidth>
                <MatrixHeight>512</MatrixHeight>            
            </TileMatrix>
        </TileMatrixSet>
    </Contents>
</Capabilities>
```

**Comment by bartvde** [comment]
what software generated this? There are many validation errors in this XML, use an XML validator.

**Comment by topwood** [comment]
e..it is a valid xml..

**Comment by bartvde** [comment]
Not according to the schema http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd

**Comment by topwood** [comment]
ok,thank you, how to test if it is according to this schema..

**Comment by bartvde** [comment]
You can use Xerces, I use a tool called Oxygen XML but it's not free.

**Comment by topwood** [comment]
you mean these tools can test if my response match the wmts schema?

**Comment by topwood** [comment]
it seems that the 'ows' namespace is needed in this schema

**Comment by topwood** [comment]
Thank you very much!
