### ISSUE TITLE
Handling the maxResolution parameter

### ISSUE THREAD

**Issue by thhomas** [openlayers/ol3#4468]
The `maxResolution` layer attribute is used as a "strict" limit. It means when defining a maxResolution, one cannot access to layer at this resolution but the previous one.

**Comment by ahocevar** [comment]
This is intentional. Layer options are always related to rendering. If you don't want to load tiles beyond a certain zoom level, use the minZoom and maxZoom settings on the source.

**Comment by thhomas** [comment]
`minZoom` and `maxZoom` settings does not exist for the source but for layer or tileGrid. And when using it, I got the #4383 issue back.

**Comment by ahocevar** [comment]
The tileGrid configuration is the one I meant, sorry. What exactly do you want to achieve?
