### ISSUE TITLE
XYZ ZoomLevel doesn't work and displays wrong tiles on zoom

### ISSUE THREAD

**Issue by taigi100** [openlayers/ol3#4473]
I'm trying to make a map using a bigger picture, I've resized it and cut it using powers of 2 ( I have resized it from 1024 to 8192 [ 8 zoom levels] ). I'm trying to use the basic template maptiler gives off.

By keeping the default `minZoom(0)` and `maxZoom(4)` it displays the entire image, but when zooming in, after 2 zooms it starts calling for the wrong tiles : As if the map would move to the left by 1 tile or something.

When changing the `maxZoom` to 7, it only displays 1/4 of the image: the top left corner.

I've tried setting the `extent` to 8192, to the full res or to some big numbers, also tried using all the params in the extent but nothing seems to work.

What should I do to make this work? I see that maptiler even uses non-square images well, but all only on 4 levels of zoom ...

**Comment by ahocevar** [comment]
You will need to configure a tileGrid with the correct resolutions. If your images are oversampled, you also need to configure the correct tilePixelRatio on the source.

**Comment by taigi100** [comment]
I do have a tilegrid ... also not exactly sure about the tilePixelRatio ( can't find anything about that ) but my tiles are 256x256 and that's default as far as I know.

**Comment by ahocevar** [comment]
See http://openlayers.org/en/v3.11.2/apidoc/ol.source.XYZ.html for tilePixelRatio.

**Comment by taigi100** [comment]
As mentioned earlier, I'm using 256pxx256px images so the ratio is set correctly. I know it's ugly but here's the code I'm using : http://paste.isomorphis.me/Dk6. I have tried to use different extents, make my own projection and so on as described in the first post.
