### ISSUE TITLE
Vector Tile missing Projection

### ISSUE THREAD

**Issue by sbowler** [openlayers/ol3#4491]
Hello,

I've noticed an issue with the changes from 3.10 to 3.11 and geoJson Vector tiles. Previously it seemed like the correct projections were automatically handled so they would be converted properly. When `ol.format.Feature.transformWithOptions` was called it properly had the correct `dataProjection` and `featureProjection` in the options; converting our tiles that are in EPSG:4326 to the map EPSG:3857 coordinates correctly.

In 3.11 the `featureProjection` is always null. I've traced this back to being called from a function in `ol.featureloader.loadFeaturesXhr` where the projection is null. I traced that call back to `ol.VectorTile.prototype.load` where the loader appears to be called with the projection hard coded to null. This seems a bit odd that you wouldn't pass along `this.projection_` as the projection. Of course I only have a vague understanding of how this all works.

So far I've frivolously tried to pass in the correct projection any way I could to no avail.
```
new ol.layer.VectorTile({
  source: new ol.source.VectorTile({
    format: new ol.format.GeoJSON({
      defaultFeatureProjection: 'EPSG:3857'
    }),
    projection: 'EPSG:3857',
    defaultFeatureProjection: 'EPSG:3857',
    featureProjection: 'EPSG:3857',
    tileGrid: ol.tilegrid.createXYZ({
        maxZoom: 4
    }),
    url: "/geojsontiles/land/{z}/{x}/{y}.json",
      attributions: [attribution]
    })
})
```

I'll keep looking at ways to work around this issue, but it seems like the new code is not handling different projections as well as the old code.

**Comment by ahocevar** [comment]
Real vector tiles only work for rendering in the projection they were made for. If you want to continue doing what you did in 3.10 with `ol.source.TileVector` and vector features that are chopped into tiles, you have to use a plain `ol.layer.Vector` with an `ol.source.Vector` and an `ol.loadingstrategy.tile`:
```js
var vector = new ol.layer.Vector({
  source: new ol.source.Vector({
    format: new ol.format.GeoJSON(),
    strategy: ol.loadingstrategy.tile(ol.tilegrid.createXYZ({
        maxZoom: 4
    })),
    url: "/geojsontiles/land/{z}/{x}/{y}.json",
    attributions: [attribution]
  })
});
```
In addition, you have to clear the source when the resolution changes, e.g.
```js
map.getView().on('change:resolution', function() {
  vector.getSource().clear();
});
```

**Comment by ahocevar** [comment]
Above snippet not yet functional. I'll provide an updated one in a few minutes.

**Comment by ahocevar** [comment]
Above snippet updated to be functional. Also see this fiddle: http://jsfiddle.net/7tyyowuo/1/. This gives you the same behaviour as the old `ol.source.TileVector`, but without its memory leak (it did not prune tiles from cached resolutions).

Having shown and said all that, I recommend using real vector tiles when rendering is the priority, and plain vector layers when access to the feature geometries and properties is the priority. The approach we offered with `ol.source.TileVector` was problematic in sevaral ways.

**Comment by sbowler** [comment]
Thanks for the information. I just want to try to clarify something. We generated our tiles from large geojson files using https://github.com/mapbox/geojson-vt . It sounded like one of the other OL3 developers was doing the same. Are you saying those aren't "real" vector tiles or is it just the coordinate conversion is really that much of an issue?

**Comment by ahocevar** [comment]
geojson-vt was used for debugging in OpenLayers. Tiles generated with it have one aspect of real vector tiles: they simplify geomeries for a view resolution. But they do not adjust content based on resolution. Mapbox-gl-js uses geojson-vt to render GeoJSON data. OpenLayers can render GeoJSON directly, and it also natively simplifies geometries for the viewport and view resolution. So geojson-vt is not the right tool for creating vector data sets for OpenLayers.

**Comment by femski** [comment]
I don;t understand why geojson-vt is not the right librray to use with ol3. For large datasets, Openlayer's GeoJSON performance is poor compared to geojson-vt. There should be a way take geojson-vt output an feed it into Openlayer easily. Too bad there are no working example for geojson-vt and ol3 integration.

**Comment by jlecordier** [comment]
Hi,
I understand why you should not reproject a Vector, but in my case they are just points, so it would be very convenient for me to have this feature...
Let me explain my situation :
My view is using the default EPSG:3857 projection, but I need to fetch my features (lonlat points), using a lonlat bbox of 15°x10° for cache optimization.
So I am using a custom GridTile with this exact tile size, in the EPSG:4326 projection.
But now, I need to reproject those points.
What would be your advices ? Keep everything in EPSG:3857 projection but use a custom tileLoadFunction to reproject the extent to EPSG:4326, call my API, then reproject the points back to EPSG:3857 ?
