### ISSUE TITLE
Using XYZ tile source with a raster.

### ISSUE THREAD

**Issue by roby2001** [openlayers/ol3#4495]
I've taken the example from the site : http://openlayers.org/en/v3.11.2/examples/color-manipulation.html and tried to change the raster source layer from stamen to a valid XYZ source. I also changed the view settings from to map to the following : 

      projection: ol.proj.get('PIXELS'),
      extent: mapExtent,
      maxResolution: mapTileGrid.getResolution(0)

If I keep the default view settings the map fails to loads and crashes. With those view settings it works, I can see the sliders for hue and the others but I don't have any map, feels like the 'map' div is empty. The console is empty, showing no errors.

I also tried adding `console.log` in different places such as the raster.on function or in the operations function. It seems like they don't get fired at all.

**Comment by roby2001** [comment]
So, can anyone help me using a XYZ source layer with a Raster or is this a known issue ?

**Comment by bartvde** [comment]
Can you show us what you tried in a jsFiddle?
