### ISSUE TITLE
Custom vector (polygon) icons

### ISSUE THREAD

**Issue by jgalrito-i9** [openlayers/ol3#4496]
Is there a way to generate vector styles for features other than Circles, Icons and RegularShapes? If I wanted for ex. to style a feature as a zoom independent isosceles triangle with angle and color depending on some properties of the feature.

**Comment by adube** [comment]
Hello.  Questions related to the usability of OL3 should be asked on StackOverflow: http://stackoverflow.com/questions/tagged/openlayers-3

Would you please close this issue ?

Cheers
