### ISSUE TITLE
Error placing a static image with OL3 (works fine on OL2)

### ISSUE THREAD

**Issue by Pedrazl** [openlayers/ol3#4497]
Working with the last version of Openlayers 3, I'm not able to load correctly a static image over the map. After some test (with similar configuration) I found that the image looks fine on OL2, while on OL3 it has a displacement of several kilometers, as you can see on the following image:

![pasted image at 2015_11_26 01_56 pm](https://cloud.githubusercontent.com/assets/10074431/11427838/70cb7d6e-9466-11e5-80cb-539649337dee.png)

I've done a plunker with that example. Could it be a bug or I'm missing something?
http://plnkr.co/lzAKNGdkXkz6ZCM9H6ml

(Code: http://plnkr.co/edit/lzAKNGdkXkz6ZCM9H6ml?p=preview)

Thanks,

**Comment by ahocevar** [comment]
This has been fixed with #4426.

**Comment by Pedrazl** [comment]
Thanks @ahocevar, 
pointing to the master works fine.
