### ISSUE TITLE
Select interaction selects features currently drawn

### ISSUE THREAD

**Issue by pgiraud** [openlayers/ol3#4504]
After the recent commits regarding unmanaged layers, `forEachFeatureAtPixel`, the layerFilter and the `Select` interaction, an unexpected behavior now happens.

In an application where there are both a draw and a select interactions, the select interaction selects the feature which is currently drawn sketched.

In the following fiddle, the selection clearly appears with a blue color. Adding or not the `filter` option has no effect.
See http://jsfiddle.net/pgiraud/0cf1e4yb/3/

After a quick bisect I found that the behavior changed after the following pull-request : https://github.com/openlayers/ol3/pull/4450

I'm looking for explanations or workarounds.
My goal is to get a select interaction working only on a given collection of features. I was previously using the filter option as follows:

```
filter: function(feature, layer) {
  return myCollectionOfFeatures.getArray().indexOf(feature) != -1;
}
```

**Comment by ahocevar** [comment]
@pgiraud, #4472 should fix your problem. Can you verify?

**Comment by pgiraud** [comment]
I checked out your branch (commit 8fa294d9df766f02254b64fbae5071efbd6b7f24) and it still behaves incorrectly at least not as I expect.
I pushed a commit with the example (select-features.html).
https://github.com/pgiraud/ol3/tree/layer-filter

**Comment by ahocevar** [comment]
Thanks for testing @pgiraud. I updated the pull request, and now the example you committed works with it as expected. Can you check again please?

**Comment by pgiraud** [comment]
Thanks @ahocevar. This works for me both on the small example I created and on the application I'm working on.
What changed in your pull request? Did you amend @elemoine's commit?

**Comment by ahocevar** [comment]
Yes @pgiraud, I amended @elemoine's commit. This was the change:
```diff
--- a/src/ol/interaction/selectinteraction.js
+++ b/src/ol/interaction/selectinteraction.js
@@ -283,7 +283,7 @@ ol.interaction.Select.handleEvent = function(mapBrowserEvent) {
          * @param {ol.layer.Layer} layer Layer.
          */
         function(feature, layer) {
-          if (!layer || this.filter_(feature, layer)) {
+          if (this.filter_(feature, layer)) {
             selected.push(feature);
             this.addFeatureLayerAssociation_(feature, layer);
             return !this.multi_;
```

**Comment by pgiraud** [comment]
Are you sure? This reverts the following commit: https://github.com/openlayers/ol3/pull/4450
Sorry I'm lost.

**Comment by ahocevar** [comment]
Yes I'm sure @pgiraud. It does not revert that commit, it is just another change on the same line.

**Comment by ahocevar** [comment]
@pgiraud It restores the state we had before #4391, i.e. the state we had when @elemoine submitted the original pull request.
