### ISSUE TITLE
ol.interaction.Pointer : handleUpEvent doesn't fire

### ISSUE THREAD

**Issue by pierregaboriaud** [openlayers/ol3#4509]
Hi,

The handleUpEvent of ol.interaction.Pointer doesn't fire if a drag sequence was not started.

**Comment by tsauerwein** [comment]
Could you please provide an example demonstrating the issue?

**Comment by pierregaboriaud** [comment]
According to the documentation of "ol.interaction.Pointer" :::
Base class that calls user-defined functions on down, move and UP EVENTS. This class ALSO manages "drag sequences".

JSFiddle : http://jsfiddle.net/Frrrt/vn1qv1mg/

**Comment by tsauerwein** [comment]
Thanks for the example. Yes, you are right. `handleDownEvent` and `handleUpEvent` assume a drag sequence. If you need more control, you can directly overwrite `handleEvent`:
http://jsfiddle.net/48ykaLhq/

I also recommend to take a look at source code of `ol.interaction.Pointer` to better understand what's happening:
https://github.com/openlayers/ol3/blob/master/src/ol/interaction/pointerinteraction.js#L183
