### ISSUE TITLE
Use ol.render.canvas.Immediate on an arbitrary canvas

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#4514]
Thinking #4513 further, we could make `ol.render.canvas.Immediate`  work to draw vector geometries on an arbitrary canvas. Users could then easily use arbitrary shapes as icon images, or use them to fill a polygon once #4241 is merged.

The API could look like this:
```js
var canvas = document.createElement('canvas');
canvas.width = 24;
canvas.height = 24;

/**
 * @type {ol.render.canvas.Immediate}
 */
var render = ol.render.toContext(canvas.getContext('2d'));

render.setFillStrokeStyle(new ol.style.Fill({color: 'blue'}));
render.drawPolygonGeometry(new ol.geom.Polygon([[[0, 0], [0, 23], [23, 0], [0, 0]]]);
```
The above would draw a blue triangle that fills the top left half of the 24x24 canvas.

**Comment by jonataswalker** [comment]
This is becoming so interesting and powerful.
