### ISSUE TITLE
Transform projection for VectorTile rendering in VectorTile layer

### ISSUE THREAD

**Issue by JWGmeligMeyling** [openlayers/ol3#4516]
I found out that the transformation is not passed to the loader for transforming the JSON data. (See https://github.com/openlayers/ol3/blob/2f06d214f5ead84f3119f2ffa1867a97c0ccd7e9/src/ol/vectortile.js#L141). In order to set it, I had to come up with the following:

```js
	function TransformedTile() { ol.VectorTile.apply(this, arguments); }
	ol.inherits(TransformedTile, ol.VectorTile);
	TransformedTile.prototype.load = function() {
		if (this.state == ol.TileState.IDLE) {
			this.setState(ol.TileState.LOADING);
			this.tileLoadFunction_(this, this.url_);
			this.loader_(null, NaN, 'EPSG:3857');
		}
	};
```

And:
```js
new ol.layer.VectorTile({
  source: new ol.source.VectorTile({
   format: new ol.format.GeoJSON({
    defaultDataProjection: "dataprojection"
  }),
  tileClass: TransformedTile
});
```

Shouldn't the VectorTile API be modified slightly for easier access to the projection on the loader?

**Comment by ahocevar** [comment]
Don't you get gaps at tile borders with that code? This will only work to transform between projections that result in straight tile borders when projected.

**Comment by JWGmeligMeyling** [comment]
I'm going to check for artefacts then. But what would be a preferred way of tile rendering tiles for data with a specific projection (it only has to work within the bounds of the projection, in this case epsg:28992)

**Comment by ahocevar** [comment]
Vector tiles should be optimized for rendering, i.e. the data should either be in pixel coordinates (which is the case for Mapbox vector tiles) or in the view projection.

**Comment by JWGmeligMeyling** [comment]
Allright! Thanks for the info, I'll close this issue then. One more question. How should one handle geometries that overlap across several tiles (eg. very long lines?)

**Comment by ahocevar** [comment]
They should be clipped at the tile border, but with a buffer of a few pixels (especially for polygons).

Note that if you want access to the geometries for purposes other than rendering, you should not be using vector tiles, but something like I described in https://github.com/openlayers/ol3/issues/4501#issuecomment-160560255.

**Comment by JWGmeligMeyling** [comment]
Yes I figured out the buffer for the polygons, as the bounding box became part of the polygon. Would a polygon/line part overlap between multiple tiles, selection behaviour is pretty much undefined as well right? 

I have been using plain vector layers so far only to be confronted with much larger data than expected. So right now I'm just checking my options. I'll definitely have a look on your comment there. Thanks!

**Comment by ahocevar** [comment]
> Would a polygon/line part overlap between multiple tiles, selection behaviour is pretty much undefined as well right?

It is well defined - selection will only apply to the segment in the clicked tile.

**Comment by JWGmeligMeyling** [comment]
Thanks a ton! I think you're example really gets me started. The selection behaviour for the VectorTile makes sense. How would the code from the example behave? Would it also create two features for two features of the same id?

**Comment by ahocevar** [comment]
Yes, my example would create two features and remove their ids to make that possible.

**Comment by ahocevar** [comment]
See #4518, which would make your implementation work without a hack. But again, if you have a chance to choose a different implementation path, please do so.

**Comment by JWGmeligMeyling** [comment]
Your effort is appreciated, I'll definitely keep an eye on the PR. As I actually want to draw as well I think I'm staying with vector layers, I wan't aware of the `loadingstrategy` possibility, which seems to do the trick.

Unfortunately I am a bit dependent on the selection and ID value for meta data purposes, and I think it would be a bit surprising experience to select a polygon and only see a part of it being selected (as it is split up across visible tiles). So either I'm going to transfer the ID as property field, or I have to come up with something very clever in order to merge such geometries together.  So that's going to be a very challenging :wink:

Anyways, thanks for your efforts and keep up the good work on this project!
