### ISSUE TITLE
unknown Extent JSON query on GeoServer 2.6.5

### ISSUE THREAD

**Issue by yatenj** [openlayers/ol3#4517]
Hi,
I need some help.
I have upgraded Geoserver from 2.3 to 2.6.5
Currently I am using GeoServer 2.6.5 and having problem with this new version.
while searching point features on GeoServer my query contains 

request=GetFeature & outputFormat=json

I get the result and then I read result in GeoJSON() format with readFeatures()

I am getting point features but with [X,Y] coordinate value as [NaN, NaN].

Same way getting extent for source is [NaN, NaN, NaN, NaN].

Rest other attributes returned correctly except X, Y and extent

But when I switch Back to GeoServer 2.3 version, I get X, Y and Extent proper values.

Is it OL3 issue or GeoServer issue?

I have enabled JSONP in GeroServer web.xml
Published layer correctly
Debuged and compared both GeoServer xml result.
 
 I found this difference in JSON query results. 
GeoServer 2.3 result : "crs":{"type":"EPSG","properties":{"code":"27700"}}

GeoServer 2.6.5 result : "crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::27700"}}

Can any one help.
I am not sure where to post this issue. 
In GeoServer or OL3.

BR

**Comment by bartvde** [comment]
Better to post this at GeoServer, doesn't seem to be an issue for ol3

**Comment by bartvde** [comment]
Ah that might have been to quick, didn't read far enough.

**Comment by bartvde** [comment]
Try registering ```urn:ogc:def:crs:EPSG::27700``` as an alias in your ol3 application, using ol.proj.addEquivalentProjections

**Comment by bartvde** [comment]
closing this issue, please reopen if you're sure there is an issue in openlayers
