### ISSUE TITLE
Wrong coordenate when click on map with openlayers 3

### ISSUE THREAD

**Issue by costales** [openlayers/ol3#4522]
Hi! I'm not sure if I'm doing this well.

Please, take a look to this:

 * Open this example: http://jsfiddle.net/19m99mfu/
 * Drag the map to the right 3 worlds (as example).
 * Click on the map, as you see, the **Longitude will be wrong** with a so high value.

Do you know if it's wrong my code (line 18 converting coordenate)? Could this be a bug in openlayers?

Thanks!

**Comment by ahocevar** [comment]
This is by design. You can get the correct longitude if you use longitude modulo 360. I updated your jsfiddle: http://jsfiddle.net/ahocevar/19m99mfu/1/.

**Comment by costales** [comment]
Thanks @ahocevar for update the example, but in my test, it's working not fine yet :o: 

Steps:
1. Click on north of Spain, longitude = -5,7

![pantallazo-1](https://cloud.githubusercontent.com/assets/5886786/11613139/6c3e6baa-9c16-11e5-8511-ba9e90cdd573.png)

2. Drag right 1 world
3. Click on same location again, longitude = 354.55

![pantallazo-2](https://cloud.githubusercontent.com/assets/5886786/11613143/8838e2c2-9c16-11e5-81ab-b63c5fce0237.png)
, latitude = -5,7

**Comment by ahocevar** [comment]
Ok, then try http://jsfiddle.net/ahocevar/19m99mfu/2/.
