### ISSUE TITLE
CDN response 413 Request Entity Too Large

### ISSUE THREAD

**Issue by winsento** [openlayers/ol3#4533]
See: https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol-debug.min.js
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>
```

**UPD**
Write issue here https://github.com/cdnjs/cdnjs/issues/6431

**Comment by bartvde** [comment]
You should either use (minified, production use): https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol.js or https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol-debug.js (debug use)

**Comment by winsento** [comment]
It was fixed here https://github.com/cdnjs/cdnjs/issues/6431
