### ISSUE TITLE
Layer Definition renderBuffer of Vector Tile

### ISSUE THREAD

**Issue by Taekjoon** [openlayers/ol3#4538]
the renderBuffer of vector tile layer does not display label and point symbol properly.
the symbologies is splitted off outside the tiles..

When can be fixed ? It's critical for me hall...

**Comment by ahocevar** [comment]
This is very likely a problem with your tiles. Points near the tile border need to be included in all neighboring tiles, i.e. your tiles need a buffer.

Can you share a jsfifddle that shows the problem?

**Comment by Taekjoon** [comment]
<img width="627" alt="vectortile_ol3" src="https://cloud.githubusercontent.com/assets/11939087/11733466/f5692b08-9ff0-11e5-8ccf-a284f2af59de.png">

I cannot share fiddle and I attach the screen copy.
You can see the regular shape symbols (with red circle) which is not displayed properly. that has one point which contains a regularshape and label...

**Comment by Taekjoon** [comment]
I think "renderBuffer" option of ol.layer.VectorTile in OL v3.11.2 API documentattion should be worked as it describes...

thanks..

**Comment by tsauerwein** [comment]
I think there is a misunderstanding here. There is a difference between the `renderBuffer` property on [ol.layer.VectorTile](http://openlayers.org/en/master/apidoc/ol.layer.VectorTile.html) and [ol.layer.Vector](http://openlayers.org/en/master/apidoc/ol.layer.Vector.html), and the [buffer](https://www.mapbox.com/help/source-manual/#buffers) that you are using when creating your vector tiles. The latter makes sure that points, that are close to a tile border, are included in the two tiles.

**Comment by ahocevar** [comment]
The documentation for the renderBuffer option is indeed misleading. I'll create a pull request.

**Comment by Taekjoon** [comment]
How about drawing the point itself, ignoring tile border.
As for my understanding, a point, (which has one coordinate), beside the border should be exists in  neighbor tiles as for you concerned.
This make the tiles bigger... How do you think ?

thanks.
