### ISSUE TITLE
Security exception 'SecurityError: The operation is insecure.' when using canvas.toDataURL() 

### ISSUE THREAD

**Issue by Anupam-** [openlayers/ol3#4547]
If there are more then 1 layer is open then toDataURL() throw a security exception(The operation is insecure.) for map canvas.

**Comment by ahocevar** [comment]
This has nothing to do with the number of layers. You need to make sure that all servers you request data from have proper CORS headers set, and that your sources set the  `crossOrigin` property to 'anonymous'. Otherwise the canvas will be tainted.

**Comment by Anupam-** [comment]
Thanks,
There was an issue of CORS and its mandatory to set crossOrigin attribute while adding Style in features.
