### ISSUE TITLE
Blink (when refresh) and duplicate (when move)  - Features on vector layer

### ISSUE THREAD

**Issue by Bear4** [openlayers/ol3#4558]
I have a problem with refresh vector layer every X seconds. I was looking solutions many times without luck. I have code but with blink effect (blinking features, when I clear old and add new features): 
 [OL v 3.11.2]

---------------------------------
var sourceVector = new ol.source.Vector({
	loader: function(extent) {
		$.ajax('http://server/wfs_ant',{
			type: 'GET',
			data: {
				service: 'WFS',
				version: '1.1.0',
				request: 'GetFeature',
				typename: 'v_wezel_rfid',
				srsname: 'EPSG:3857',
				bbox: extent.join(',') + ',EPSG:3857'
				},
			}).done(loadFeatures);
		},
		strategy: ol.loadingstrategy.bbox
	});

var loadFeatures = function(response) {
    formatWFS = new ol.format.WFS(),
		//sourceVector.clear();
		sourceVector.addFeatures(formatWFS.readFeatures(response));
		console.log('loadFeatures');
    };

function refresh(sourceVector){
	sourceVector.clear();
	sourceVector;
	console.log(' refresh');
	}

var layerVector = new ol.layer.Vector({
    source: sourceVector,
    style: vectorStyle
    });
setInterval(function(){refresh(sourceVector); }, 10000);

--------------------------------------------
I was trying remove: sourceVector.clear() in loadFeature section but then loading wfs features going on endless  loop.
Second problem is duplicate features, when move map there show duplicate features and duplicate are add every move map. I have unique id on wfs.

**Comment by Bear4** [comment]
Duplicate features (at loading strategy bbox) problem omited by change:
from -> strategy: ol.loadingstrategy.bbox
to -> strategy: ol.loadingstrategy.tile(new ol.tilegrid.createXYZ())

**Comment by ahocevar** [comment]
When you have unique ids on your features, there should be no duplicates. Maybe double-check if they are really as fid when you get the data from your server.

The classic solution for avoiding blink effects is to use two sources, and switch from the old source to the new source when the features are loaded. And yes, call `clear()` on the source to trigger a reload.

Also, your code could be simplified by just using a `url` function instead of a loader.

**Comment by Bear4** [comment]
Use two sources and switch between... it's gently complicated, would be nice to have simpler solution.

Thx for new OL3

**Comment by ahocevar** [comment]
It's not that complicated. Look at this fiddle: http://jsfiddle.net/ahocevar/tLt5wdpz/.
