### ISSUE TITLE
Add configuration property to ol.interaction.DragBox for the hysteresis value

### ISSUE THREAD

**Issue by pkovac** [openlayers/ol3#4565]
Currently, the area of a DragBox is compared against a constant, HYSTERESIS_PIXELS_SQUARED, as a threshold before a 'boxend' DragBoxEvent is fired. For different use-cases, different thresholds might be appropriate, or no threshold at all. I suggest that ol.interaction.DragBox include an options parameter to replace ol.DRAG_BOX_HYSTERESIS_PIXELS, with that constant as the default value should none be specified.

**Comment by ahocevar** [comment]
I think that constant is misleading anyway. What about a boolean `boxEndCondition(width, height)` function as config option, which defaults to
```js
function(startPixel, endPixel) {
  var width = endPixel[0] - startPixel[0];
  var height = endPixel[1] - endPixel[1];
  return width * width + height * height >= ol.DRAG_BOX_HYSTERESIS_PIXELS_SQUARED;
}
```

**Comment by pkovac** [comment]
This seems like a reasonable approach. When you labelled it pull request accepted, are you planning on making the change or are you waiting for a pull request from me?

**Comment by marcjansen** [comment]
The label is just a sign that we agree that the suggested change has a high chance of getting into the library as there is consensus about the nature of the change.

We would be very very happy if you can come up with a PR! Go for it.
