### ISSUE TITLE
view.getResolutionForExtent only works in OL_Debug Errors in ol.js

### ISSUE THREAD

**Issue by flipper44** [openlayers/ol3#4573]
Enough said in the title

**Comment by bartvde** [comment]
This is not part of the API currently can you give us a use case why you need to have it exported in your application?

**Comment by flipper44** [comment]
Why is it ol_debug. I use it for my main mapping (Mapguide) layer  to set resolution on the view.
It seems like a quite handy function when one knows the initial extent and map size.
I can just grab the code from ol_debug I guess, just assumed it was a mistake that it didn't make the minified version.
Model.Map = new ol.Map({
	layers: ol_layers,
	target : document.getElementById('map'),
	controls : loadControlsController.loadMapControls(),
	interactions: loadControlsController.loadMapInteractions(),
});
var size = Model.Map.getSize();
var center = ol.extent.getCenter(initial_extent);
var view = new ol.View({
	center: center,
	projection: Model.Config.general.display_srs
});
///Only in ol_debug
var res =  view.getResolutionForExtent(initial_extent,size);
view.setResolution(res);
Model.Map.setView(view);
Model.Map.render();

**Comment by ahocevar** [comment]
> It seems like a quite handy function when one knows the initial extent and map size.

@flipper44 Have you looked at [ol.View#fit()](http://openlayers.org/en/v3.12.1/apidoc/ol.View.html#fit)?

**Comment by flipper44** [comment]
That should Work. Didn't see that one somehow. Feel free to close.
Thanks

**Comment by flipper44** [comment]
This Yields Different Results..ol.View#fit() seems to not do a true fit, but must be taking tile Zoom level into acoount, whereas var res = view.getResolutionForExtent(initial_extent,size);
view.setResolution(res); sets the exact extents correctly for me

**Comment by ahocevar** [comment]
In you want an exact fit, you can use `view.fit(extent, size, {constrainResolution: false});`.

**Comment by flipper44** [comment]
That works perfectly!
