### ISSUE TITLE
TileArcGISRest with the deprecated ESRI projection 102113

### ISSUE THREAD

**Issue by irmanator** [openlayers/ol3#4585]
I'm using the TileArcGISRest with experimental parameter passing in my OL3 application.

var parameter = {
	'F': 'image',
	'FORMAT': 'PNG32',
	'TRANSPARENT': true,
	'SIZE':256,
	'BBOX':minlon,minlat,maxlon,maxlats,
	'BBOXSR' :msg[i]['sr'],
	'IMAGESR':msg[i]['sr'],
	'DPI':'90'
};

source: new ol.source.TileArcGISRest({
	params:parameter,
	url:msg[i]['url']+'/export'
})

The maps from many arcgis services will show correctly, except this one:
http://webgis.dephut.go.id/ArcGIS/rest/services/Mangrove/MapServer/
This map is using 102113 projection, the deprecated ESRI projection, and the firebug says:

NetworkError: 500 Internal Server Error - http://webgis.dephut.go.id/arcgis/rest/services/Mangrove/MapServer/export/?F=image&FORMAT=PNG32&TRANSPARENT=true&SIZE=256%2C256&BBOX=10018754.17139462%2C-1252344.271424327%2C11271098.442818947%2C6.984919309616089e-10&BBOXSR=3857&IMAGESR=3857&DPI=90

If we change the IMAGESR and BBOXSR from 3857 to 102113 the tile image will show.
http://webgis.dephut.go.id/arcgis/rest/services/Mangrove/MapServer/export/?F=image&FORMAT=PNG32&TRANSPARENT=true&SIZE=256%2C256&BBOX=10018754.17139462%2C-1252344.271424327%2C11271098.442818947%2C6.984919309616089e-10&BBOXSR=102113&IMAGESR=102113&DPI=90

By reading this API
http://openlayers.org/en/v3.12.1/apidoc/ol.source.TileArcGISRest.html, it will tell us that
SIZE, BBOXSR, and IMAGESR will be set dynamically.

And i checked the ol-debug.js, and show that if OL3 finds EPSG:102113, EPSG:900913, EPSG:102100, then OL3 will convert them into EPSG:3857 automatically.
Looks like that this is one of the suspect error.

I wonder if we can change IMAGESR and BBOXSR parameter, so hopefully this will solve this issue.
Thanks.

**Comment by bartvde** [comment]
interesting report, I'll have a look

**Comment by bartvde** [comment]
can you try changing your view to:

```
  view: new ol.View({
    projection: 'EPSG:102113',
    center: [-10997148, 4569099],
    zoom: 4
  })
```

In the arcgis-tiled.html example that did the trick for me:

http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StateCityHighway_USA/MapServer/export?F=image&FORMAT=PNG32&TRANSPARENT=true&SIZE=256%2C256&BBOX=-7514065.628545966%2C2504688.542848654%2C-5009377.08569731%2C5009377.08569731&BBOXSR=102113&IMAGESR=102113&DPI=90

**Comment by bartvde** [comment]
Closing, please reopen if you still have issues.

**Comment by irmanator** [comment]
You're the best bro!
Thank you...
