### ISSUE TITLE
canvasreplay.js - 4th instruction is not a string when zooming on graph

### ISSUE THREAD

**Issue by ncphillips** [openlayers/ol3#4587]
Line 380 of src/ol/render/canvas/canvasreplay.js fails an assertion goog.isString. 

After this occurs, the map is no longer rendered correctly. See the image below for an example.

![screen shot 2015-12-22 at 11 18 35 am](https://cloud.githubusercontent.com/assets/824015/11958342/cc61c732-a89d-11e5-8004-a99ff0713888.png)

**Comment by bartvde** [comment]
are you sending a ```ol.style.Text``` text property that is undefined or something like that?

**Comment by ncphillips** [comment]
Thanks for the hint! The style wasn't undefined but we were passing a Date object instead of a string. We changed the function to call `toTimeString()` and now it works.
