### ISSUE TITLE
Don't hardwire version numbers in examples

### ISSUE THREAD

**Issue by jidanni** [openlayers/ol3#4592]
Are you sure you still want to hardwire version numbers into your examples there on http://openlayers.org/en/v3.12.1/doc/quickstart.html ?

Google doesn't do that anymore in their examples.
https://developers.google.com/maps/tutorials/fundamentals/adding-a-google-map

Compare src="https://maps.googleapis.com/maps/api/js" vs. src="http://openlayers.org/en/v3.12.1/build/ol.js".

**Comment by jidanni** [comment]
In fact, this penchant for adding version numbers results in major fragmentation for any Google search results:
openlayers.org/en/v3.4.0/examples/kml.html
openlayers.org/en/v3.2.1/examples/
openlayers.org/en/v3.8.2/examples/simple.html

**Comment by fredj** [comment]
https://github.com/openlayers/openlayers.github.io/pull/62
