### ISSUE TITLE
Canvas setting to "display:none" on resize of the Collapsed Tab

### ISSUE THREAD

**Issue by khavrenko** [openlayers/ol3#4601]
Env: version 3.12.1, browser Chrome 47.0.2526.106 m (64-bit), OS Windows 7 x64

1. Collapse the Map Section
2. Resize the Browser Screen
3. Expand the Map Section( Now the Map was not rendering (it is blank), instead display:none was attached to the Canvas Element)

Note: when i manually invoke $mapContainer.find('.ol-viewport canvas').show(),  map was displayed, but default controls are not working)

P.S. it is the same behavior as https://github.com/tombatossals/angular-openlayers-directive/issues/199

**Comment by ahocevar** [comment]
Try to call `map.updateSize();` after expanding the map section.

**Comment by khavrenko** [comment]
thanks, it helps with setTimeout usage
