### ISSUE TITLE
Z-Index and order problems of rendering in layer collection

### ISSUE THREAD

**Issue by tds4u** [openlayers/ol3#4611]
Hello,

please look at https://www.dreiharden.net/proxy/maps/dreiharden/

Change base map at top right to "Luftbild" and you'll see that the vector layer for POIs is now under all other layers. Clicking back to normal base map "Karte" all things are fine.

index 5, name markerpois, z-index 1000
index 4, name map4, z-index 10
index 3, name map3, z-index 10
index 2, name map2, z-index 10
index 1, name map1, z-index 10
index 0, name google, z-index 0

So, POIs are on top of z-index and last in rendering chain of OL3. But for google satellite it's under other WMS layers.

Please help fixing that. Thanks in advance.

**Comment by ahocevar** [comment]
This is not an OpenLayers issue, but related to ol3-gm. Please report there: https://github.com/mapgears/ol3-google-maps/issues.
