### ISSUE TITLE
Example 'Icon Symbolizer': popups buggy for multiple markers

### ISSUE THREAD

**Issue by atarax42** [openlayers/ol3#4623]
When you create a map similar to the example at http://openlayers.org/en/v3.12.1/examples/icon.html but with multiple markers, the contents of the popup bubble is not being updated when you click on one marker after another. In my example below you may click on 'Paris' and the bubble for Paris is being shown. If your next click is on 'London' still the bubble for Paris will be shown. Only if you first click on a spot on the map that has no marker feature the bubble contents will be updated for the next click on a marker.

I could not figure out why this happens, so I report this behaviour here. If there is a better place for discussing this, please tell me. Thank you.

    <!DOCTYPE html>
    <html>
      <head>
        <title>Icon Symbolizer</title>
        <link rel="stylesheet" href="http://openlayers.org/en/v3.12.1/css/ol.css" type="text/css">
        <script src="http://openlayers.org/en/v3.12.1/build/ol.js"></script>
        <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <style>
          #map {
            position: relative;
          }
        </style>
      </head>
      <body>
        <div id="map" class="map"><div id="popup"></div></div>
        <script>
          
          var places = [
            [13.409436, 52.520791, 'Berlin'],
            [-0.12769, 51.50736, 'London'],
            [2.34684, 48.8551, 'Paris']
          ];

          var iconStyle = new ol.style.Style({
            image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
              anchor: [0.5, 41],
              anchorXUnits: 'fraction',
              anchorYUnits: 'pixels',
              opacity: 0.75,
              src: 'http://www.openstreetmap.org/assets/images/marker-icon-915e83a6fc798c599e5c9e3f759d6bc065d65151019acd0410d1f4731bcaaf72.png'
            }))
          });

          var vectorSource = new ol.source.Vector({});
          
          for (var i = 0; i < places.length; i++){
            var iconFeature = new ol.Feature({
              geometry: new ol.geom.Point(ol.proj.transform([places[i][0], places[i][1]], 'EPSG:4326', 'EPSG:3857')),
              name: places[i][2]
            });
            vectorSource.addFeature(iconFeature);
          }
          
          var vectorLayer = new ol.layer.Vector({
            source: vectorSource,
            style: iconStyle
          });

          var rasterLayer = new ol.layer.Tile({
            source: new ol.source.TileJSON({
              url: 'http://api.tiles.mapbox.com/v3/mapbox.geography-class.jsonp',
              crossOrigin: ''
            })
          });

          var map = new ol.Map({
            layers: [rasterLayer, vectorLayer],
            target: document.getElementById('map'),
            view: new ol.View({
              center: ol.proj.fromLonLat([6.958122, 50.941309]),
              zoom: 4
            })
          });

          var element = document.getElementById('popup');

          var popup = new ol.Overlay({
            element: element,
            positioning: 'bottom-center',
            stopEvent: false
          });
          map.addOverlay(popup);

          // display popup on click
          map.on('click', function(evt) {
            var feature = map.forEachFeatureAtPixel(evt.pixel,
                function(feature, layer) {
                  return feature;
                });
            if (feature) {
              popup.setPosition(evt.coordinate);
              $(element).popover({
                'placement': 'top',
                'html': true,
                'content': feature.get('name')
              });
              $(element).popover('show');
            } else {
              $(element).popover('destroy');
            }
          });

          // change mouse cursor when over marker
          map.on('pointermove', function(e) {
            if (e.dragging) {
              $(element).popover('destroy');
              return;
            }
            var pixel = map.getEventPixel(e.originalEvent);
            var hit = map.hasFeatureAtPixel(pixel);
            map.getTarget().style.cursor = hit ? 'pointer' : '';
          });
        </script>
      </body>
    </html>

**Comment by fredj** [comment]
The issue comes from the popover usage not ol3
The `name` property used for the popover content is correct for for some reasons the text is not updated.

Maybe the popover should be destroyed (untested )
