### ISSUE TITLE
Bing Attribution Crashes when Map layers are reprojected.

### ISSUE THREAD

**Issue by flipper44** [openlayers/ol3#4634]
Not sure Why this Happens. This does not happen With OSM or MapQuest (as far as I have tested).
This Happens in a very odd place in ol-debug as well (see attached image)
![capture4](https://cloud.githubusercontent.com/assets/16003063/12181030/727ee2ae-b545-11e5-936c-4700a65e36be.JPG)

Can likely be tested in the new Indiana State plane East Sample that is to be merged later

**Comment by ahocevar** [comment]
This is because the projection is not configured with an extent, and `ol.Attribution` requires a projection extent, which it should not. See #4638 for a fix.

**Comment by marcjansen** [comment]
Thanks for the bug report.
