### ISSUE TITLE
GeoJSON is really slow with a different projection

### ISSUE THREAD

**Issue by leolorenzoluis** [openlayers/ol3#4637]
Given the sample code, it takes awhile to load the map.

    <!DOCTYPE html>
    <html>
      <head>
        <title>GeoJSON</title>
        <link rel="stylesheet" href="http://openlayers.org/en/v3.12.1/css/ol.css" type="text/css">
        <script src="http://openlayers.org/en/v3.12.1/build/ol.js"></script>
      </head>
      <body>
        <div id="map" class="map"></div>
        <script>
          var image = new ol.style.Circle({
            radius: 5,
            fill: null,
            stroke: new ol.style.Stroke({color: 'red', width: 1})
          });

          var styles = {
            'Point': new ol.style.Style({
              image: image
            }),
            'LineString': new ol.style.Style({
              stroke: new ol.style.Stroke({
                color: 'green',
                width: 1
              })
            }),
            'MultiLineString': new ol.style.Style({
              stroke: new ol.style.Stroke({
                color: 'green',
                width: 1
              })
            }),
            'MultiPoint': new ol.style.Style({
              image: image
            }),
            'MultiPolygon': new ol.style.Style({
              stroke: new ol.style.Stroke({
                color: 'yellow',
                width: 1
              }),
              fill: new ol.style.Fill({
                color: 'rgba(255, 255, 0, 0.1)'
              })
            }),
            'Polygon': new ol.style.Style({
              stroke: new ol.style.Stroke({
                color: 'blue',
                lineDash: [4],
                width: 3
              }),
              fill: new ol.style.Fill({
                color: 'rgba(0, 0, 255, 0.1)'
              })
            }),
            'GeometryCollection': new ol.style.Style({
              stroke: new ol.style.Stroke({
                color: 'magenta',
                width: 2
              }),
              fill: new ol.style.Fill({
                color: 'magenta'
              }),
              image: new ol.style.Circle({
                radius: 10,
                fill: null,
                stroke: new ol.style.Stroke({
                  color: 'magenta'
                })
              })
            }),
            'Circle': new ol.style.Style({
              stroke: new ol.style.Stroke({
                color: 'red',
                width: 2
              }),
              fill: new ol.style.Fill({
                color: 'rgba(255,0,0,0.2)'
              })
            })
          };

          var styleFunction = function(feature, resolution) {
            return styles[feature.getGeometry().getType()];
          };

          var geojsonObject = {
            'type': 'FeatureCollection',
            'crs': {
              'type': 'name',
              'properties': {
                'name': 'EPSG:4326'
              }
            },
            'features': [

              {
                'type': 'Feature',
                'geometry': {
                  'type': 'Polygon',
                  'coordinates': [
                        [
                            [ -104.047534, 49.000239 ],
                            [ -104.042057, 47.861036 ],
                            [ -104.047534, 45.944106 ],
                            [ -104.042057, 44.996596 ],
                            [ -104.058488, 44.996596 ],
                            [ -105.91517, 45.002073 ],
                            [ -109.080842, 45.002073 ],
                            [ -111.05254, 45.002073 ],
                            [ -111.047063, 44.476286 ],
                            [ -111.227803, 44.580348 ],
                            [ -111.386634, 44.75561 ],
                            [ -111.616665, 44.547487 ],
                            [ -111.819312, 44.509148 ],
                            [ -111.868605, 44.563917 ],
                            [ -112.104113, 44.520102 ],
                            [ -112.241036, 44.569394 ],
                            [ -112.471068, 44.481763 ],
                            [ -112.783254, 44.48724 ],
                            [ -112.887315, 44.394132 ],
                            [ -113.002331, 44.448902 ],
                            [ -113.133778, 44.772041 ],
                            [ -113.341901, 44.782995 ],
                            [ -113.456917, 44.865149 ],
                            [ -113.45144, 45.056842 ],
                            [ -113.571933, 45.128042 ],
                            [ -113.736241, 45.330689 ],
                            [ -113.834826, 45.522382 ],
                            [ -113.807441, 45.604536 ],
                            [ -113.98818, 45.703121 ],
                            [ -114.086765, 45.593582 ],
                            [ -114.333228, 45.456659 ],
                            [ -114.546828, 45.560721 ],
                            [ -114.497536, 45.670259 ],
                            [ -114.568736, 45.774321 ],
                            [ -114.387997, 45.88386 ],
                            [ -114.492059, 46.037214 ],
                            [ -114.464674, 46.272723 ],
                            [ -114.322274, 46.645155 ],
                            [ -114.612552, 46.639678 ],
                            [ -114.623506, 46.705401 ],
                            [ -114.886399, 46.809463 ],
                            [ -114.930214, 46.919002 ],
                            [ -115.302646, 47.187372 ],
                            [ -115.324554, 47.258572 ],
                            [ -115.527201, 47.302388 ],
                            [ -115.718894, 47.42288 ],
                            [ -115.724371, 47.696727 ],
                            [ -116.04751, 47.976051 ],
                            [ -116.04751, 49.000239 ],
                            [ -111.50165, 48.994762 ],
                            [ -109.453274, 49.000239 ],
                            [ -104.047534, 49.000239 ]
                        ]
                    ]
                }
              }
            ]
          };

          var vectorSource = new ol.source.Vector({
            features: (new ol.format.GeoJSON({
                projection: 'EPSG:4326'
            })).readFeatures(geojsonObject)
          });

          //vectorSource.addFeature(new ol.Feature(new ol.geom.Circle([5e6, 7e6], 1e6)));

          var vectorLayer = new ol.layer.Vector({
            source: vectorSource,
            style: styleFunction
          });

          var map = new ol.Map({
            layers: [
              new ol.layer.Tile({
                source: new ol.source.OSM()
              }),
              vectorLayer
            ],
            target: 'map',
            controls: ol.control.defaults({
              attributionOptions: /** @type {olx.control.AttributionOptions} */ ({
                collapsible: false
              })
            }),
            view: new ol.View({
            projection:'EPSG:4326',
              center: [0, 0],
              zoom: 2
            })
          });
        </script>
      </body>
    </html>

**Comment by ahocevar** [comment]
What you are seeing has nothing to do with GeoJSON. Because you are using an `ol.source.OSM`, which provides tiles in EPSG:3857, but your view is in EPSG:4326, OpenLayers applies raster reprojection to the OSM layer. So what takes some time to render is the OSM layer, not the vector layer.

You may want to look for a base layer that is available in your view projection, e.g. http://maps.omniscale.com/en/openstreetmap/epsg-4326.
