### ISSUE TITLE
Why ol.geom.Linestring.getCoordinates() returning array of coordinate

### ISSUE THREAD

**Issue by lol2x** [openlayers/ol3#4640]
I'm currently working with ol.geom and I noticed that:
ol.geom.LineString.getCoordinates() return {Array.ol.Coordinate} [Doc](http://openlayers.org/en/v3.12.1/apidoc/ol.geom.LineString.html#getCoordinates)
while 
ol.geom.Polygon.getCoordinates() return {Array.Array.ol.Coordinate} [Doc](http://openlayers.org/en/v3.12.1/apidoc/ol.geom.Polygon.html#getCoordinates)

Why this isn't normalised? Point have return like LineString (without highest Array) but I think that all outputs should be 'same'

**Comment by ahocevar** [comment]
A polygon is made up of rings, to allow for holes. The outer ring is the first entry in the array, then followed by inner rings. `ol.geom.LinearRing` is probably what you are looking for:
```js
polygon.getLinearRings().forEach(function(linearRing) {
  var coordinates = linearRing.getCoordinates(); // {Array.<ol.Coordinate>}
});
