### ISSUE TITLE
GeoJSON not populating ids given feature objects 

### ISSUE THREAD

**Issue by leolorenzoluis** [openlayers/ol3#4643]
Given the following geojson

    {
        "type": "FeatureCollection",
        "features": [
            {
                "id": "Apple",
                "type": "Feature",
                "properties": {
                    "ID_0": 179,
                    "NL_NAME_1": "",
                    "VARNAME_1": ""
                },
            {
                "id": "Orange",
                "type": "Feature",
                "properties": {               
                    "ID_0": 179,
                    "NL_NAME_1": "",
                    "VARNAME_1": ""
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [ 121.41948699951172, 15.215220451355094 ],
                            [ 121.34188079834007, 14.997309684753418 ],
                            [ 121.31174468994163, 15.19941329956066 ],
                            [ 121.3762130737307, 15.48357009887701 ],
                            [ 121.28172302246128, 15.770520210266227 ],
                            [ 121.46764373779308, 15.916589736938477 ],
                            [ 122.13166046142578, 16.530120849609318 ],
                            [ 122.27221679687534, 16.52355003356945 ],
                            [ 122.1995315551759, 16.434970855712947 ],
                            [ 122.22328948974632, 16.38949966430664 ],
                            [ 122.24360656738315, 16.420560836792106 ],
                            [ 122.17983245849655, 16.303319931030273 ],
                            [ 122.23805236816418, 16.312219619750977 ],
                            [ 122.2055587768557, 16.240829467773438 ],
                            [ 122.03204345703125, 16.04998970031744 ],
                            [ 121.98931884765625, 16.029060363769474 ],
                            [ 122.13111114501953, 16.261390686035156 ],
                            [ 122.07111358642624, 16.241670608520565 ],
                            [ 122.07826232910156, 16.18992042541504 ],
                            [ 121.74147796630871, 16.068660736083984 ],
                            [ 121.55480957031261, 15.898360252380485 ],
                            [ 121.55317687988281, 15.787429809570312 ],
                            [ 121.6395416259769, 15.704130172729549 ],
                            [ 121.49336242675804, 15.523579597473145 ],
                            [ 121.47521209716808, 15.416839599609375 ],
                            [ 121.38445281982445, 15.364999771118164 ],
                            [ 121.41948699951172, 15.215220451355094 ]
                        ]
                    ]
                }
            },
            {
                "id": "Batman",
                "type": "Feature",
                "properties": {
                    "ID_0": 179,
                    "NL_NAME_1": "",
                    "VARNAME_1": ""
                },
                "geometry": {
                    "type": "MultiPolygon",
                    "coordinates": [
                        [
                            [
                                [ 121.58891296386741, 6.6834001541137695 ],
                                [ 121.63266754150402, 6.652299880981502 ],
                                [ 121.61872100830078, 6.558469772338867 ],
                                [ 121.56405639648438, 6.704150199890137 ],
                                [ 121.58891296386741, 6.6834001541137695 ]
                            ]
                        ],
                        [
                            [
                                [ 122.06276702880871, 6.751669883728141 ],
                                [ 122.14378356933639, 6.6700201034547035 ],
                                [ 122.32694244384777, 6.616940021514893 ],
                                [ 122.21278381347668, 6.58027982711792 ],
                                [ 122.1816635131836, 6.4524998664856525 ],
                                [ 121.95644378662121, 6.406290054321403 ],
                                [ 121.79360961914074, 6.6280598640441895 ],
                                [ 122.06276702880871, 6.751669883728141 ]
                            ]
                        ]
                    ]
                }
            }
         }
      }

When I do the following code 

            var vectorSource = new ol.source.Vector({
            url: '/api/sample',
            format: new ol.format.GeoJSON({
                projection: 'EPSG:4326',
                defaultDataProjection: 'EPSG:4326'
            })
          });

Only some of the feature objects get their id populated. Batman feature object doesn't get Batman id. When I try to query all features, everything except Batman gets populated. I have no idea why and I assume it has something to do with how GeoJSON works?

I'm currently using v3.12. for ol.js

**Comment by tschaub** [comment]
The GeoJSON you pasted above is not valid (it is missing the closing `}` for the first feature.  Would it be possible to provide the actual URL that you use in your application?  If not, you can paste your feature collection into http://geojson.io/ to confirm that is valid, and then share the link to the same here.

**Comment by leolorenzoluis** [comment]
ubuntuws-s7638bee.cloudapp.net/api/geo

**Comment by fredj** [comment]
The GeoJSON is still invalid: some `id` have an extra colon (`:`)
Example: `"[...] 1042"},"id:":"Misamis Occidental","geom [...]`

**Comment by leolorenzoluis** [comment]
You were right. Thank you for pointing it out. Closing this issue.
