### ISSUE TITLE
selectInteraction was added to map and map can not pan

### ISSUE THREAD

**Issue by FreeGIS** [openlayers/ol3#4646]
var selectSingleClick = new ol.interaction.Select();
  var map = new ol.Map({
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            }),gpsLayer
        ],
interactions:[selectSingleClick ],
        overlays: [overlay],
        target: 'map',
        view: new ol.View({
            center: ol.proj.fromLonLat([118.7,32]),
            zoom: 12
        })
    });
when i write code as top,the map can not pan .but if i write as bottom

var map = new ol.Map({
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            }),gpsLayer
        ],
        overlays: [overlay],
        target: 'map',
        view: new ol.View({
            center: ol.proj.fromLonLat([118.7,32]),
            zoom: 12
        })
    });
    map.addInteraction(selectSingleClick);
the map can be pan.  I think there was a bug.

**Comment by marcjansen** [comment]
This is not a bug. In your first example you map only has the `selectSingleClick` interaction, and hence you cannot e.g. pan (you'd need a `ol.interaction.DragPan`).

Your second example though has the [default interactions (scroll down a bit)] (http://openlayers.org/en/v3.12.1/apidoc/ol.interaction.html#defaults) and additionally the `selectSingleClick` interaction. If you want to add to the defaults while instantiating the map, you could use:

```js
var map = new ol.Map({
  interactions: (ol.interaction.defaults()).extend([selectSingleClick])
  // other ol.Map-configs
});
```

The above is untested.
