### ISSUE TITLE
Allow definition of a target for FullScreen control

### ISSUE THREAD

**Issue by maveric1977** [openlayers/ol3#4650]
The ol.control.FullScreen gets always the map.target as it's FullScreen target.
I would suggest to extend the olx.control.FullScreenOptions with a new fullScreenTarget parameter and handle the FullScreen for this dom element when it is provided.

![fullscreentarget](https://cloud.githubusercontent.com/assets/5349934/12260294/6a799020-b91b-11e5-9422-72390b785c74.png)

I have already developed this functionality for one of our intern projects as a custom ol control extending the default ol.control.FullScreen, but it may make more sense to include it in the default ol.control.FullScreen.

**Comment by ahocevar** [comment]
What would be the benefit? It wouldn't change the appearance of the fullscreen map, since it is, hm, fullscreen anyway.

**Comment by marcjansen** [comment]
I think you misunderstood, @ahocevar.

If I understand @maveric1977 correctly, the red rectangle in his picturee is a dom-element, which contains the map-div and a another div (`side-panel`). Once the fullscreen-btn is clicked, the red-framed-div should `requestFullScreen`.

Did I understand that correctly?

BTW I'd not ata ll opposed to such a configuration option.

**Comment by maveric1977** [comment]
@marcjansen: exactly what I mean.
@ahocevar: I work in geo-informatics branch for the last 20 years and normally a user does not have an isolated map component only, but also other components for descriptive data or tools or meta data or a layer switcher. What I proposed maintains the current functionality of the FullScreen control and enables the users with such requirements to have the other components in FullScreen mode as well.

**Comment by ahocevar** [comment]
I see now what you mean, thanks for the explanation.

But if you want to full screen more than the map, it becomes the responsibility of your application IMHO.

I agree this would be a simple change, but I am not sure if it is right to make that change. What do others think?

**Comment by marcjansen** [comment]
As I said earlier, I am :+1: for such a change. I think it is a fairly common need that more than only the map div should be full screen. Any applications would need to duplicate a lot of logic/code to achieve a similar result. I do not have a strong feeling, so a can live with any consensus decision here.

**Comment by maveric1977** [comment]
@ahocevar I do understand the tendency not to include irrelevant logic into the library, but if you consider the use cases you would see that it is indeed relevant. Let's say for a geomatic solution more than 90% of time the requirement is to have a layer switcher and a toolbox to be able to change the visibility and order of layers and do some geospatial tasks like vector editing and measurement etc. 
These are the main map-related tools which makes the full screen map unusable if they are not available in this mode.
So without having this functionality, 90% of the time, people have to ignore the ol.control.FullScreen and write their own FullScreen routine and then somehow integrate it into ol command button, if they want to maintain the same styling for all of their tool buttons like Zoom In and Out.
With respect to the minimal amount of code change that is proposed, I think that it would worth it.

@marcjansen Thanks for the :+1:

**Comment by ahocevar** [comment]
+0, I'm not going to oppose if someone comes up with a pull request.
