### ISSUE TITLE
Bing Maps key has expired

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4653]
The current Bing Maps key for the examples has expired.

**Comment by fredj** [comment]
@tschaub are you willing to create a new another key?

**Comment by buddebej** [comment]
None of the Bing examples is working. Does anyone know a workaround to fix this?

**Comment by bartvde** [comment]
Register for your key at https://www.bingmapsportal.com and then use that as the ```key``` property of ```ol.source.BingMaps```

**Comment by tschaub** [comment]
![image](https://cloud.githubusercontent.com/assets/41094/12431596/9bc3022c-beb3-11e5-94ba-950835b03f5e.png)

This will happen again as long as people copy/paste from our examples (without reading the comments about registering for their own key).

I'll register for another key, but this will happen again.  The Bing folks haven't come back with any alternatives (a key that only works for openlayers.org and localhost for example) when I've asked.
