### ISSUE TITLE
Developer Documentation Update

### ISSUE THREAD

**Issue by maveric1977** [openlayers/ol3#4654]
As MetalSmith does not work with the older nodeJs versions, the [Development Dependencies of the DEVELOPING.md](https://github.com/openlayers/ol3/blob/master/DEVELOPING.md#development-dependencies) should be updated.

Ref: [no longer working on node 0.12](https://github.com/metalsmith/metalsmith/issues/161)

**Comment by marcjansen** [comment]
Are you up for a documentation change? PR welcome.

**Comment by maveric1977** [comment]
Sure :)
