### ISSUE TITLE
Polygon's degradation after zooming less then its size

### ISSUE THREAD

**Issue by khavrenko** [openlayers/ol3#4656]
Env.: version 3.12.1, browser Chrome 47.0.2526.106 m (64-bit) / Mozilla Firefox 43.0.2, OS Windows 7 x64

http://jsfiddle.net/e2djx009/

Steps:
1. Fit extent with feature 
![1](https://cloud.githubusercontent.com/assets/698987/12263498/9c90a77c-b940-11e5-8ac8-496c5ea1713a.png)
2. Zoom in
![2](https://cloud.githubusercontent.com/assets/698987/12263499/9c9404f8-b940-11e5-88da-d15712129eb8.png)
3. Pan map along polygon's border
![3](https://cloud.githubusercontent.com/assets/698987/12263497/9c902748-b940-11e5-9cfa-41124ae31b39.png)

I remember the problem in Openlayers 2 and it was fixed.

**Comment by ischas** [comment]
This seems not to happen, if you close the polygon with the beginning point:

```
var points = [[2472568.9181639114,8485996.678231196],...,[2472568.9181639114,8485996.678231196]];
```

**Comment by ahocevar** [comment]
It is a requirement for polygons to be closed, i.e. last coordinate equals first.
