### ISSUE TITLE
tinyows support?

### ISSUE THREAD

**Issue by WillieMaddox** [openlayers/ol3#4657]
Hello,

I would like to use ol3 rather than ol2 to connect to tinyows. The mapserver [example](http://mapserver.org/tinyows/openlayershowto.html) uses ol2.  Has anyone had success using tinyows with ol3?

Thanks,

**Comment by ahocevar** [comment]
Should not be a problem. It is just WFS-T. See http://gis.stackexchange.com/questions/155394/using-wfs-t-in-openlayers-3 for a thread with good explanations.

**Comment by WillieMaddox** [comment]
Right, I've been working with examples from that thread as well.  I think the issue is that all the examples (or all the ones that I've found anyway)  that use ol2/tinyows do so via a proxy.  However, all the ol3/geoserver examples use no such proxy.  So, I guess the question is can ol3 work with tinyows without a proxy? or is a proxy still necessary?  I haven't found anything on the web that describes how to do either configuration.
