### ISSUE TITLE
Margin have impact on feature location

### ISSUE THREAD

**Issue by driz764** [openlayers/ol3#4662]
https://jsfiddle.net/557qumh9/

margin on top component of the map ( body in the jsfiddle) make Map.eachFeaturesAtPixel being out of sync with the view.

For testing, in jsfiddle, hover the feature and observe that the pointer become a cursor at the right. Then click the text "Click to change margin", hovering the feature will not work anymore. In fact it works but with an offset. 
![good](https://cloud.githubusercontent.com/assets/1301452/12271211/3d37333a-b95a-11e5-95d6-f377d249a8b7.png)

![bad](https://cloud.githubusercontent.com/assets/1301452/12271218/44adc2f0-b95a-11e5-84bf-1067fe235850.png)

Browser : Chrome Version 47.0.2526.106

**Comment by tsauerwein** [comment]
You'll have to use [updateSize()](http://openlayers.org/en/master/apidoc/ol.Map.html#updateSize) to tell OpenLayers that the size of your map container has changed:

    document.querySelector("body").style.margin='20px';
    map.updateSize();

https://jsfiddle.net/557qumh9/1/
