### ISSUE TITLE
Using setUrl on a source.TileWMS

### ISSUE THREAD

**Issue by jgalrito-i9** [openlayers/ol3#4670]
Apparently, setting a TileWMS source URL through setUrl() (instead of config object) causes the requests to be made without parameters (BBOX, LAYERS, etc.)

**Comment by ahocevar** [comment]
Looks like a bug. Thanks for reporting it!

**Comment by ahocevar** [comment]
It appers to be broken since v3.11 - in 3.10 it still worked.

**Comment by ahocevar** [comment]
See #4673 for a fix.
