### ISSUE TITLE
Get rid of bin/check-whitespace.py

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4672]
With https://github.com/openlayers/eslint-config-openlayers/pull/2, we can get rid of `bin/check-whitespace.py`

**Comment by fredj** [comment]
`bin/check-whitespace.py` also checks [if the first line has no leading whitespace](https://github.com/openlayers/ol3/blob/master/bin/check-whitespace.py#L22-L24) but it's not very important

**Comment by ahocevar** [comment]
+1 on removing it.
