### ISSUE TITLE
Tiles loading issue

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4674]
- http://openlayers.org/en/master/examples/simple.html
 - pan

-> the tiles are not loaded

The issue is not present in the latest release (v3.12.1)

**Comment by fredj** [comment]
552063aeac2b77576994d8f85596c704d6fb7677 is the first bad commit

**Comment by petrsloup** [comment]
Yes, this seems to be happening for me only when scrolling and dragging *simultaneously*.

**Comment by fredj** [comment]
Note: the issue is present only if the kinetic effect does not occur
