### ISSUE TITLE
Raster reprojection with TileWMS source

### ISSUE THREAD

**Issue by sookoll** [openlayers/ol3#4681]
ol-3.12.1.
I tried to use raster reprojection from EPSG:3301 to EPSG:3857. At first I notice horisontal caps between tilerows at larger zoomlevels, then I tried to use gutter and result was gutter-sized caps over tiles.

jsfiddle: https://jsfiddle.net/aymvra7g/

note: not sure does this wms server accessible outside of Estonia. Screen:
http://sookoll.ee/failid/ol_reproject_bug.png

**Comment by ahocevar** [comment]
This seems to be a bug in OpenLayers. The same problem was reported here: http://stackoverflow.com/questions/35335067/openlayers-3-white-gaps-between-osm-map-tiles.

I added another JSFiddle to reproduce the issue in #4721.

**Comment by petrsloup** [comment]
@ahocevar This actually turns out to be unrelated issue. See https://github.com/openlayers/ol3/pull/4869 for a fix.

**Comment by petrsloup** [comment]
@sookoll The fix for this should be included in v3.14.0.
