### ISSUE TITLE
Image Layer as BLOB ?

### ISSUE THREAD

**Issue by gvatin** [openlayers/ol3#4683]
Hi all,
- sorry for the duplication from Google Groups, I'm tring all the ways ;) -

Is there any trick to create an image layer, not from a source URL, but from something such as a Binary large object (BLOB) ?
The thing is that I use GDAL on my server to create image from a PostGIS DB, using complex SQL queries, average distance, count etc. and other algorithms.
This "GDAL web server" is used from OpenLayers (3) map, on moveend listener : jQuery sends a query with map parameters (bbox etc) to the GDAL web service, that processes the data and creates an image file. The service returns the file name to the client, which is added to "refresh the image layer" on the map.
It works great for my single usage, but this is impossible to think of this at a production size (several thousand images created on server side). Even with a regular clean on the img folder, I fear we don't have enough disk space.

Maybe we can pass the image to OL as a binary object, so no image is actually created on the server ?

Do you have any ideas how to deal with this? Thanks for the tips !

Gabriel

**Comment by bartvde** [comment]
Most developers are both on ol3-dev and github, so please don't do this duplication.

**Comment by RyanRutkin** [comment]
@gvatin Could you provide a link to the duplicated issue in Google Groups?
I'm having the same problem, and the fact that this question was closed without providing a link to where it was duplicated from makes this a useless link to someone looking for answers.
Thanks!

**Comment by RyanRutkin** [comment]
This looks to solve a similar issue:
https://github.com/openlayers/openlayers/issues/4213#issuecomment-145149625
Also, see [ImageWMS](https://openlayers.org/en/latest/apidoc/module-ol_source_ImageWMS-ImageWMS.html) and [imageLoadFunction](https://openlayers.org/en/latest/apidoc/module-ol_Image.html#~LoadFunction)
