### ISSUE TITLE
getTileUrlFunction() returns unbinded function

### ISSUE THREAD

**Issue by gberaudo** [openlayers/ol3#4695]
By default, the function returned by `source.getTileUrlFunction()` used to be binded to the source.
It is no longer the case since https://github.com/openlayers/ol3/pull/4673, at least for TileWMS sources.

In the call `source.getTileUrlFunction()(...)`, `this` equals the `Window` object.
Is it expected behavior?

**Comment by ahocevar** [comment]
If we expect the function returned by `ol.source.UrlTile#getTileUrlFunction()` to return a url even when executed outside the context of the source, then it should indeed be bound to the source. If we don't, then things can stay as they are.

Although not explicitly mentioned in the docs, I think it would make for a more intuitive API if the former was the case.

@gberaudo, would you be willing to create a pull request?

**Comment by gberaudo** [comment]
Would it be acceptable to bind the function returned in `ol.source.UrlTile.prototype.getTileUrlFunction` like this:
`return this.tileUrlFunction.bind(this);`?

**Comment by ahocevar** [comment]
I think it would be better to only change https://github.com/openlayers/ol3/blob/master/src/ol/source/urltilesource.js#L66-L67 to something like
```js
  this.tileUrlFunction = this.fixedTileUrlFunction ?
      this.fixedTileUrlFunction.bind(this) || ol.TileUrlFunction.nullTileUrlFunction;
```

**Comment by gberaudo** [comment]
There are several places where the tileUrlFunction is changed so we might lose the binding in some cases. For example https://github.com/openlayers/ol3/blob/master/src/ol/source/urltilesource.js#L187-L188 we might get an unbinded version of `this.fixedTileUrlFunction`.

As a generalization of what you suggested in https://github.com/openlayers/ol3/issues/4695#issuecomment-173229514, I can also bind the above case and all the other references to `this.fixedTileUrlFunction`. Would it be good for you?

**Comment by ahocevar** [comment]
That would be fine @gberaudo. Thanks!
