### ISSUE TITLE
Text Style icons with custom font only update after clicking on the map

### ISSUE THREAD

**Issue by jgalrito-i9** [openlayers/ol3#4696]
![image](https://cloud.githubusercontent.com/assets/15655550/12453384/e1e41e1c-bf8a-11e5-9535-95390acf5e91.png)

I'm using a custom icon font as a Text Style, but only after I click on the map do the icons render, until then these 'unknown' characters show (I assume the font is not loaded yet)

**Comment by jgalrito-i9** [comment]
This might have more to do with canvas than OpenLayers

http://stackoverflow.com/questions/2756575/drawing-text-to-canvas-with-font-face-does-not-work-at-the-first-time

**Comment by ahocevar** [comment]
It is the responsibility of the application to make sure that the font is loaded before the map is rendered.
