### ISSUE TITLE
GPX export not compatible with several programs e.g. Garmin Basecamp

### ISSUE THREAD

**Issue by jaykayone** [openlayers/ol3#4699]
The GPX files exported with ol2 where using tracks (trk tags with trkpt)
The GPX files exported with ol3 are using routes (rte with rtept)

Several programs like Garmin basecamp or the iPhone app "Scout" don't manage to read these files.
They can manage to read the files produced by ol2 though.

[gpx_bug.zip](https://github.com/openlayers/ol3/files/97687/gpx_bug.zip)

**Comment by sookoll** [comment]
confirm that.

**Comment by ahocevar** [comment]
The GPX serializer creates routes from LineString geometries, and tracks from MultiLineString geometries.

If you want to draw a track on your map, set the `type` option of ol.interaction.Draw to `ol.geom.MultiLineString` instead of `ol.geom.LineString`.

Does this help?

**Comment by jaykayone** [comment]
this could help indeed. we'll give it a try and keep you informed. thanks

**Comment by rmichaelis** [comment]
This is not a problem of route or trackpoint.
Basecamp of Garmin is looking for the xsi namespace.

```
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1" creator="OpenLayers" >
```
Is there a way to add this namespace ?

**Comment by penpendede** [comment]
Importing of GPX exported by OpenLayers into Garmin devices still fails. As @rmichaelis already pointed out, Garmin requires xmlns:xsi to function in the first place.

However, there is another issue: Garmin insists that data strictly adheres to the actual GPX specification (see http://www.topografix.com/GPX/1/1/gpx.xsd) that requires one to stick to the following order:

1. An optional instance of <meta />
2. An arbitrary number of instances of <wpt />
3. An arbitrary number of instances of <rte />
4. An arbitrary number of instances of <trk />
5. An optional instance of <extensions />

OpenLayers' writeFeatures for GPX however does **not** ensure the given order. Of course it is possible to sort the features before calling writeFeatures but to my understanding this task should be performed by the writeFeatures itself.

**Comment by penpendede** [comment]
A suggestion one of my colleagues how to solve the issue is two changes to the writeFeaturesNode method in **gpxformat.js** that seem to be sufficient:

1. Generate an XML that has the Topografix XMLNS, then add a second namespace as well version number and possibly a creator (see @rmichaelis' above contribution) as attributes.

2. Soft features before ol.xml.pushSerializeAndPop

Concerning the namespace issue see e.g. http://blogs.msmvps.com/martin-honnen/2009/04/13/creating-xml-with-namespaces-with-javascript-and-the-w3c-dom/

**Comment by probins** [comment]
AFAICS, OL2 didn't sort features either, so I don't see how OL2 would work if this was required. OL2 did however output the xsi namespace, together with creator and version, both of which are required according to the spec.

**Comment by penpendede** [comment]
@probins I checked it again by directly copying the GPX files to my Garmin Dakota 20. As Radio Yerevan would put it: In principle  you are right that there is **no** issue with Garmin devices. However, the issue **is** present in *Garmin Basecamp*, a free-for-download software by Garmin that many people including me and my boss use to transfer GPX data to their devices.

**Comment by probins** [comment]
#5471 adds the xsi namespace, creator and version, exactly as used in the 'fells_loop' example file. Pls check that the devices/apps mentioned accept the output from this patch. I can't test this, as I don't have a GPS device.

@penpendede I'm not disputing that the current output doesn't work with Basecamp. It's correct that the spec does define the points/routes/tracks as an xsd:sequence, so they should be in that order, but, if as the OP wrote OL2 output worked with it, I don't see how sorting features can be an issue. If this is still an issue, another change could be made to output them in the correct sequence, though an easy workaround would surely be to create different files for the points and routes/tracks, and feed them separately to the device/app.

**Comment by probins** [comment]
#5471 should have fixed this. If there are still issues, pls reopen this, or open a new issue.
