### ISSUE TITLE
Change value DEFAULT_TILE_CACHE_HIGH_WATER_MARK in code

### ISSUE THREAD

**Issue by kroupaTomass** [openlayers/ol3#4702]
Exist the other option, how can i set value DEFAULT_TILE_CACHE_HIGH_WATER_MARK without own build library OL3? My application can be compilated on more computers and our problem is hold everywhere the same version, moreover we use the package manager NPM. I need set this value before loading map.

Thanks.

**Comment by jakubbican** [comment]
Is is similar to https://github.com/openlayers/ol3/issues/3816
