### ISSUE TITLE
Interaction.Select toggleCondition not working for deselection

### ISSUE THREAD

**Issue by Gudahtt** [openlayers/ol3#4704]
Since `v3.13.0`, toggle deselection hasn't been working. This can be demonstrated with the [select-features example](http://openlayers.org/en/v3.13.0/examples/select-features.html). Holding the shift key still allows selection, but not deselection.

**Comment by bartvde** [comment]
thanks for your report, indeed this is a regression

**Comment by bartvde** [comment]
a65d2d40782b1884fdf3b4347410f68eea4bca71 is the first bad commit

**Comment by ahocevar** [comment]
See #4736 for a fix, with tests. @fredj or @bartvde, maybe you want to review that.
