### ISSUE TITLE
How to do cachewrite and cacheread using OpenLayers 3?

### ISSUE THREAD

**Issue by chicks2014** [openlayers/ol3#4707]
I'm using Openlayer3. I want to read-write cache in ol3 for offline map storage in cache memory. I had seen this example of ol2

I want similar functionalities in ol3 version. I had tried  new ol.control.cacheWrite but there are no such methods. ol3 api

Please let me know if you have any idea of this.

**Comment by bartvde** [comment]
Please don't open this up in multiple locations: http://stackoverflow.com/questions/34922414/how-to-do-cachewrite-and-cacheread-using-openlayers-3

**Comment by bartvde** [comment]
If the answers aren't coming in quickly enough for you, you should consider getting commercial support.
