### ISSUE TITLE
How can open an offline vector map?

### ISSUE THREAD

**Issue by costales** [openlayers/ol3#4710]
Hi!
Is there any example about to open an offline vector map? Maybe a .osm? (I don't know if there is a better format for load, any tip is appreciated).
Thanks in advance!

**Comment by ahocevar** [comment]
Formats supported by OpenLayers include GeoJSON, TopoJSON, MVT and more. You can either use vector tiles or plain vector tiles. Look at the `http://openlayers.org/en/v3.13.0/examples/` collection to find all different kinds. For offline use, it depends on what you mean by it. Different browser [offline storage technologies](http://www.html5rocks.com/en/features/storage) can be used by providing custom `tileLoadFunction` (for `ol.source.VectorTile`) or `loader` (for `ol.source.Vector`) handlers.
