### ISSUE TITLE
getPixelFromCoordinate function does not work properly

### ISSUE THREAD

**Issue by aystep** [openlayers/ol3#4713]
getPixelFromCoordinate function does not work properly, when I try to use this function for full scrolled map.
F.ex. add circle feature at 0,0 coordinates.
Then get pixels:
map.getPixelFromCoordinate(feature.getGeometry().getCoordinates()); // output [600,650]
Then move map over whole world and try to get pixels from target feature:
map.getPixelFromCoordinate(feature.getGeometry().getCoordinates()); //output [-1700, 650]
But expected output [600,650]

**Comment by ahocevar** [comment]
I know it feels strange, but this is expected behaviour. This way we avoid cursor jumps when working with map views that cross the date line.

**Comment by aystep** [comment]
Hm.. Interesting. If this is expected behaviour, how to get real pixel coordinates of feature which is respect to map viewport on the screen?
I know that we can get screen pixel coordinates from different mouse events.... But it is not enough in many cases.

**Comment by ahocevar** [comment]
Untested, but try something like
```js
var pixel = map.getPixelFromCoordinate(coordinate);
var width = map.getSize()[0];
var pixelX = ((pixel[0] % width) + width) % width;
var pixelY = pixel[1];
```

**Comment by aystep** [comment]
Ok. Let's comments with details:
F.ex. we have a map with big zoom level 6-7.
This map has viewport width = 1000px.
map.getPixelFromCoordinate() - will return f.ex. 2100px by X coordinate (we a little bit moved map with feature beyond the viewport).
Does it mean that real viewport screen coordinates of feature is (2100%1000 + 1000)%1000 = 100 px?
No. We can not calculate this using only width of viewport, because we don't know width of whole map in pixels for target zoom level. We need to calculate, that we passed over whole world or not.
For above example this feature should not be visible on the map viewport at all.
When we pass whole map this feature will appear again on the map view and we somehow should receive pixel coordinates on the map view.
But how this can be calculated using exists OL api?

**Comment by aystep** [comment]
Any comments?
Is it possible to get size of whole map in pixels, depending on zooming?
Could you please add appropriate function in OL API?

**Comment by ahocevar** [comment]
You're right, you need modulo world width, not modulo viewport width:
```js
var pixel = map.getPixelFromCoordinate(coordinate);
var view = map.getView();
var width = ol.extent.getWidth(view.getProjection().getExtent()) / view.getResolution();
var pixelX = ((pixel[0] % width) + width) % width;
var pixelY = pixel[1];
```

**Comment by aystep** [comment]
This is really helpful! Projection and Extent are very powerful! Thank you!
No need any changes in API.
