### ISSUE TITLE
Keyboard focus is lost after clicking in map viewport

### ISSUE THREAD

**Issue by pkovac** [openlayers/ol3#4724]
Keyboard navigation functions as expected if the user has clicked on an openlayers control, but upon clicking on the map canvas itself, the keyboard pan/zoom shortcuts no longer function. 

Steps to reproduce:
1. Load an openlayers demo. (http://openlayers.org/en/v3.13.0/examples/regularshape.html works)
2. Click a zoom button in or out.
3. Pan/zoom around using keyboard arrow keys and +/-
4. Click on the map content itself.
5. Attempt to pan/zoom using keyboard shortcuts.

**Comment by pkovac** [comment]
It looks like the way to fix this behavior is to give a tabIndex to the canvas, otherwise the canvas is not focusable by default. http://stackoverflow.com/questions/1829586/how-do-i-give-an-html-canvas-the-keyboard-focus-using-jquery

I've tested this in my project and on the example page, and it seems to give the desired result. Perhaps tabIndex for the canvas should be a configurable property at map creation time, since it could create problems to assume a value for it, putting it in the middle of someone's tabbing order.

**Comment by fredj** [comment]
It works with the [accessible example](http://openlayers.org/en/v3.13.0/examples/accessible.html)

**Comment by pkovac** [comment]
Oh, hrm. Didn't realize you could set the tabindex on the parent div and get the same effect. Since you can get this working without reaching in and modifying the canvas created by OL, I guess this isn't really an issue. My mistake. Thanks.
