### ISSUE TITLE
transformExtent fails when going from EPSG:3857 to EPSG:8155

### ISSUE THREAD

**Issue by andersmd7** [openlayers/ol3#4744]
I'm trying to get the extent of a view, so that I can use it in a CQL filter to limit the requested data to the area currently shown in the map extent.  To do this, I have to transform the extent into the source layer SRID coordinates, but I am getting an error when I try this.  The code I'm using is:

	var currentExtent =	map.getView().calculateExtent(map.getSize());
	transformedExtent = ol.proj.transformExtent(currentExtent,'EPSG:3857','EPSG:8155');

I get the following error bubbling up in Firebug:

TypeError: c is undefined
	function Je(b,c){var d=b.a,e=c.a,f;d in Ke&&e in Ke[d]&&(f=Ke[d][e]);void 0===f&...

If I transform from 3857 to 4326 using the following, it works as expected, giving me coordinates that make sense for 4326:

	transformedExtent = ol.proj.transformExtent(currentExtent,'EPSG:3857','EPSG:4326');

Wondering if there is something missing in transformations for EPSG:8155 -- "WYLAM"...?

**Comment by marcjansen** [comment]
So does openlayers know about `EPSG:8155`?

```js
      var projection = new ol.proj.Projection({
        code: 'EPSG:21781',
        extent: [ /* the extent */]
        // other properties
      });
```

**Comment by thiagogcm** [comment]
OL3 only knows EPSG:3857 and EPSG:4326

to include more definitions you can do like this (for EPSG 31983). To get more defs u can check them out in [http://spatialreference.org/](url)

    proj4.defs("EPSG:31983","+proj=utm +zone=23 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");

    var projection = new ol.proj.Projection({
        code: 'EPSG:31983',

        extent:[719611.0694339676,7754122.175521086,732426.449433967,7773345.245521082],
        units: 'm'
    });
    ol.proj.addProjection(projection);

**Comment by andersmd7** [comment]
Thank you.  The Proj4 definition is missing at Spatial Reference, but if I understand correctly you're saying I can generate from scratch, as in the example above, using the known parameters for the projection...?

**Comment by thiagogcm** [comment]
that's right. also make sure to include http://proj4js.org/

**Comment by andersmd7** [comment]
I have one follow-up on this issue...  

I was able to enable transformation by adding the following to the proj4text column in _spatial_ref_sys_

`"+proj=lcc +lat_1=41 +lat_2=45 +lat_0=41 +lon_0=-107.5 +k_0=1 +x_0=500000 +y_0=200000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"`

However, when I try to transform (with ST_Transform) points from another coordinate system that uses NAD27 (e.g., UTM Zone 12N, NAD27 -- EPSG: 26712), I wind up with the resulting points being offset about 50m to the east, and 4m to the North from where they should be.  Am I missing something in the proj4text that would enable Post to make this transformation correctly?

**Comment by marcjansen** [comment]
Is this a question about the postgis function `st_transform`? If so, it should be asked at their relevant places to ask.

**Comment by andersmd7** [comment]
Yes -- you're right.  It's really a question about transforming coordinates and proj4 definitions, not specifically one about OL.
