### ISSUE TITLE
Disable Simplyfying Polygons

### ISSUE THREAD

**Issue by SimonA84** [openlayers/ol3#4752]
Is it possible to disable the Simplyfying-Algorithm for special layers or sources?

Here is a screenshot with disabled the simplyfying.
![image](https://cloud.githubusercontent.com/assets/16936569/12642691/bcb277c8-c5b7-11e5-9ed5-dc35b2484392.png)

And here with active simplyfying.
![image](https://cloud.githubusercontent.com/assets/16936569/12642747/0b875760-c5b8-11e5-80e7-d9469422a963.png)

The version with disabled simplyfying is the correct layout.

**Comment by bartvde** [comment]
Try a custom build with a different value for ol.SIMPLIFY_TOLERANCE

**Comment by bartvde** [comment]
No I don't think it can be disabled on a layer / source basis, it's a general setting currently.

**Comment by SimonA84** [comment]
Is there a possibility to make the simplify_tolerance configurable?

**Comment by tschaub** [comment]
@SimonA84 can you provide a link to an example that reproduces the issue you are seeing?

**Comment by SimonA84** [comment]
At the moment it's not possible to provide a link. 
The problem didn't appear with OL3.10.1 but with newer versions.

**Comment by SimonA84** [comment]
I dont't know what has changed, but the problem didn't occour in my last test.

@tschaub One of the customers of the company changed to the new product version. So can I provide a link http://84.46.99.78:8081/HHOHL/
