### ISSUE TITLE
Canvas resize error for map component in React.

### ISSUE THREAD

**Issue by AndreasRohl** [openlayers/ol3#4757]
I have created a simple React component with a single div and created a map when component is mounted. However the internal resize mechanism for the canvas does not work for the height when you resize the window. It simply continues to grow even if you just resize window horizontally. If you inspect the internal canvas element you can see that the size is set incorrectly. I have created a simple demo page for you test this. 

http://geometra.cafebabe.se/#/mappage

Go to that link and simply resize window to left and right and you will see that the map canvas will keep growing in height. Using 1.13.0 of OL3.

**Comment by ahocevar** [comment]
You need to get notified by React when the size of the map container has changed, and then call `ol.Map#updateSize()`.

**Comment by AndreasRohl** [comment]
I am actually doing that and it puzzles me why it works excellent for horizontal changes but not for vertical ? without calling updateSize() it gets really weird. There should be console log that prints what I receive for window property size and what the view port tries to set.
