### ISSUE TITLE
add OSGeo project badge to website

### ISSUE THREAD

**Issue by jodygarnett** [openlayers/ol3#4760]
Would like to ask that the OSGeo project logo be added to the project website.

(We will also be removing the http://www.osgeo.org/openlayers landing page and directing visitors directly to http://openlayers.org)

**Comment by jodygarnett** [comment]
The openlayers website has a nice user focused approach. Consider adding a small version of the logo to the footer where the other project details information resides.

**Comment by marcjansen** [comment]
Would this be the loge:

**Comment by jodygarnett** [comment]
Here is the link to svn:

https://trac.osgeo.org/osgeo/browser/marketing/logo/svg/OSGeo_project.svg

If you look in the folder https://trac.osgeo.org/osgeo/browser/marketing/logo you can see different sizes and formats (PNG, SVG, etc...)
