### ISSUE TITLE
localized-openstreetmap example broken

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4767]
http://openlayers.org/en/v3.13.0/examples/localized-openstreetmap.html
zoom in and out

**Comment by tsauerwein** [comment]
Could this be related to https://github.com/openlayers/ol3/issues/4763?

**Comment by fredj** [comment]
Yes, maybe. They both uses a `ol.source.OSM` with a custom url

**Comment by fredj** [comment]
That's because the OpenSeaMap tiles are transparent but the ol.source.OSM is always opaque
