### ISSUE TITLE
Failing tests in IE 11 (different document-modes)

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#4768]
While checking #4711, several test failures in `master` were detected:

* In IE 11 (document-mode: 'Edge (default)')
  * `ol.source.TileImage` => `#getTile` (4 tests fail, with a timeout, also when run via grep)
* In IE 11 (document-mode  '10')
  * `ol.source.TileImage` => `#getTile` (4 tests fail, with a timeout, also when run via grep)
  * `ol.Map` => `#getEventPixel` (2 tests fail, "expected 3306 to sort of equal 190")
* In IE 11 (document-mode  '9')
  * `ol.source.TileImage` => `#getTile` (4 tests fail, but with a timeout, also when run via grep)
  * `ol.Map` => `#getEventPixel` (2 tests fail, "expected 3306 to sort of equal 190")
  * The suite stops at 88% with a mocha.js exception.

**Comment by fredj** [comment]
> The suite stops at 88% with a mocha.js exception.

probably #4886

**Comment by marcjansen** [comment]
Hopefully. I am not able to retest on windows for at least a week, sorry.

**Comment by bartvde** [comment]
pure bliss @marcjansen ;-)

**Comment by marcjansen** [comment]
Yeah, sure. 😸

**Comment by ahocevar** [comment]
As of 2df40f4b88bc062695ddcc756d1d20a116e1b27c, all mentioned problems are fixed.
