### ISSUE TITLE
Performance problem with a huge GeoJson.

### ISSUE THREAD

**Issue by niba** [openlayers/ol3#4770]
I have test application with two map frameworks: OpenLayers and Leaflet and I loaded to both of them a big GeoJson (about 7000 polygons). OpenLayers experience is terrible in opposite to Leaflet which works flawlessly. I used AtlasManager and canvas renderer in my OL implementation. Do you know why there is a such difference?

**Comment by ahocevar** [comment]
Could you maybe share your test application?

**Comment by niba** [comment]
Sure. Here you have. To switch between frameworks change
` <script src="scriptL.js"></script>`
to 
` <script src="scriptOL.js"></script>`
in index.html

[TestMapFrameworks.zip](https://github.com/openlayers/ol3/files/114561/TestMapFrameworks.zip)

**Comment by ahocevar** [comment]
Thanks. The difference is that your OpenLayers version re-renders all visible polygons with every animation frame, i.e. when you pan and zoom the map. To get similar behaviour and performance as in Leaflet, you can use an image layer with an `ol.source.ImageVector`:
```js
var vector = new ol.layer.Image({
  source: new ol.source.ImageVector({
    source: vectorSource,
    style: function(feature) {
      return styles;
    }
  })
});
```

**Comment by niba** [comment]
Thanks for great tips. Didn't know about ImageVector. It's so much better now.
