### ISSUE TITLE
Polygon creation from huge array of rings

### ISSUE THREAD

**Issue by brunobck** [openlayers/ol3#4773]
I have a huge array of lat and long coordinates, which I create an array of rings and then create the polygon from the rings... When there are few coordinates inside de ring, polygon gets created perfectly. However when there are a huge array of rings the polygon does not get created... I was debbuging in the browser and I noticed a weird behaviour when I have huge array of rings, it seems that the browser separate smaller arrays inside arrays, I mean visually the array gets rearranged into nested arrays... Whilest the array contais few rings, the array is visually normal.
What's the matter when I got a huge array of rings? Can't I draw complex polygon with this procedure?

small array that gets created
![image](https://cloud.githubusercontent.com/assets/8991612/12763459/ba9c161a-c9db-11e5-86cf-e5029207ecbd.png)

Huge array that doesn't get created
![image](https://cloud.githubusercontent.com/assets/8991612/12763463/bf08b3f2-c9db-11e5-877f-37fb37d6671b.png)

code
`    var erri = "MULTIPOLYGON(((-44.2098427332555 -14.2445978473128,-44.2091227108444 -14.2466718521242,-44.2075597808592 -14.2481879382227,-44.2035881723562 -14.2505558261904,-44.2012367482773 -14.2511368961508,-44.2012887380848 ...(so on)... )))";

    var text = erri.replace("MULTIPOLYGON", "").replace("(((", "").replace(")))", "");

    var geometry = text.split(',');
    var onion = [];

    for (var i = 0; i < geometry.length; i++) {
        var coordss = geometry[i].split(' ');
        onion.push([Number(coordss[0]), Number(coordss[1])]);
    }

    var bigArray = [];

    for (var i = 0; i <= onion.length; i++) {
        bigArray.push(onion[i]);
    }

    bigArray.push(onion[0]);

    var a = [
        {
            "lng": -53.128530722141,
            "lat": -13.908015361071
        },
        {
            "lng": -15.46875,
            "lat": -16.912673327062
        },
        {
            "lng": -18.984375,
            "lat": 9.84375
        },
        {
            "lng": -53.128530722141,
            "lat": -13.908015361071
        }
    ];

    //A ring must be closed, that is its last coordinate
    //should be the same as its first coordinate.
    var ring = [
      [a[0].lng, a[0].lat], [a[1].lng, a[1].lat],
      [a[2].lng, a[2].lat], [a[0].lng, a[0].lat]
    ];

    //// A polygon is an array of rings, the first ring is
    //// the exterior ring, the others are the interior rings.
    //// In your case there is one ring only.
    var polygon = new ol.geom.Polygon([bigArray]);

    polygon.transform('EPSG:4326', 'EPSG:3857');

    // Create feature with polygon.
    var feature = new ol.Feature(polygon);

    // Create vector source and the feature to it.
    var vectorSource = new ol.source.Vector();
    vectorSource.addFeature(feature);

    // Create vector layer attached to the vector source.
    var vectorLayer = new ol.layer.Vector({
        source: vectorSource
    });

    // Add the vector layer to the map.
    map.addLayer(vectorLayer);

    var layers;
    map.getLayers().forEach(function (layer) {
        if (layer instanceof ol.layer.Base) {
            layers = layer;
        }
    }, this);`

**Comment by ahocevar** [comment]
Why don't you just use
```js
new ol.format.WKT().readFeatures("MULTIPOLYGON(((-44.2098427332555 -14.2445978473128,-44.2091227108444 -14.2466718521242,-44.2075597808592 -14.2481879382227,-44.2035881723562 -14.2505558261904,-44.2012367482773 -14.2511368961508,-44.2012887380848 ...(so on)... )))", {featureProjection: 'EPSG:3857'});
```
instead of everything you have?

**Comment by brunobck** [comment]
@ahocevar thanks a million!! It worket perctly!!
 I think in this case my poor geographic knowledge didn't help too much...
