### ISSUE TITLE
Cannot build the example reprojection-image.js

### ISSUE THREAD

**Issue by adube** [openlayers/ol3#4779]
When running `make check-examples` on the current master branch, I get the following error:

```
$ make check-examples
./node_modules/.bin/phantomjs --local-to-remote-url-access=true --ssl-protocol=any --ignore-ssl-errors=true bin/check-example.js build/hosted/master/examples/reprojection-image.html
JavaScript ERROR: TypeError: 'undefined' is not a function (evaluating 'function(){this.i=void 0;this.no.call(this,Date.now())}.bind(this)')
TRACE:
 -> file:///opt/ol3/adube/build/hosted/master/build/ol.js: 404 (in function "T")
 -> file:///opt/ol3/adube/build/hosted/master/examples/reprojection-image.js: 27
make: *** [build/timestamps/check-reprojection-image-timestamp] Error 1
```

Anyone aware of this issue ?

**Comment by ahocevar** [comment]
Looks like you're running an old phantomjs which does not support `Function.prototype.bind`. Make sure you use phantomjs >= 2.0.0. When working off the OpenLayers package, run `npm install phantomjs` to get the update according to package.json.

**Comment by adube** [comment]
Thanks, @ahocevar.  Just out of curiosity, why is it not in package.json ?  It would seem that is was there before (in 3.13.0 at least): https://github.com/openlayers/ol3/blob/v3.13.0/package.json#L66 (version 1.9.19)

But in master it's no longer there.  There's a `phantomjs-prebuilt": "2.1.3`, though.  I wonder why I had to run `npm install phantomjs` if, to my eye, that prebuilt should have done the trick.  Any pointer would be appreciated.

**Comment by ahocevar** [comment]
My mistake. The package was renamed, and `phantoms-prebuilt` is the new package name. See #4751. Sorry, I cannot keep up with every change. But it looks like you were able to figure it out with my initial hint anyway.

**Comment by adube** [comment]
No problem.  But just to make sure I understand correctly.  Before running `npm install phantomjs`, I had the error when running `make check-examples`.  Should this be something to include in the installation process, as an additional command to run ?   Just trying to understand.  Thanks!

**Comment by ahocevar** [comment]
No need to run `npm install phantomjs`. This was just a guess to fix your situation, without knowing that the new package name is `phantomjs-prebuilt`.

If you don`t have `phantomjs-prebuilt` in your OpenLayers's `node_modules` yet, just run `npm install` from the OpenLayers directory to get the update.

**Comment by adube** [comment]
Thanks for the help.  Here's a final update.

I did have the `node_modules/phantomjs-prebuilt` directory, so I'm not sure what went wrong there with for me to have the error.  Doing a `npm install` didn't change anything.  So I deleted the `node_modules` directory and did a fresh `npm install` and after that it worked as expected!

Thanks again.
