### ISSUE TITLE
Odd use of goog.object functions in KML format

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#4781]
The changes in #4316 introduced some odd use of `goog.object.clone()` and `goog.object.isEmpty()`.

The KML format [uses `goog.object.clone()`](https://github.com/openlayers/ol3/blob/473cbba26e005cf200acc779e2d69f0ba9524d13/src/ol/format/kmlformat.js#L335-L336) to "clone" a `ol.style.Text` instance.

In addition, the format uses [`goog.object.isEmpty()`](https://github.com/openlayers/ol3/blob/473cbba26e005cf200acc779e2d69f0ba9524d13/src/ol/format/kmlformat.js#L334) to try to determine something about the `ol.style.Text` instance.

If we need to have a method to clone a text style, then we should add one.  And this format should use a different way to determine if a text style is "empty" (it is unclear what that means from the current use).

cc @marcjansen and @tamarmot.

**Comment by tamarmot** [comment]
Thanks for pointing that out, I'll take a look and submit a fresh pull
request with improvements.

**Comment by tamarmot** [comment]
Would you prefer I add methods to clone text style and to see if a style has a text style, or would you prefer I put the code just in kmlformat.js?  Seems like generic methods in style.js might be useful for other code as well.

**Comment by tschaub** [comment]
> Would you prefer I add methods to clone text style and to see if a style has a text style

I think `style.getText() === null` would be the way to check if a style has a text symbolizer.

For cloning, a method would make it more convenient, but since there is only one use for it now, it could be an easier change to just do what needs to be done in the KML format.

Here's what is there right now:
```
if (!goog.object.isEmpty(foundStyle.getText())) {
  textStyle = /** @type {ol.style.Text} */
    (goog.object.clone(foundStyle.getText()));
  textStyle.setText(name);
  textStyle.setTextAlign(textAlign);
  textStyle.setOffsetX(textOffset[0]);
  textStyle.setOffsetY(textOffset[1]);
}
```

So, I'm guessing that the intention of this code is
```
if the foundStyle instance has a text symbolizer, then
  create a new text symbolizer with all the same properties
  and set new text, textAlign, offsetX, and offsetY properties
```

Which could be written like this:
```js
var foundText = foundStyle.getText();
if (foundText) {
  textStyle = new ol.style.Text({
    text: name,
    textAlign: textAlign,
    offsetX: textOffset[0],
    offsetY: textOffset[1],
    font: foundText.getFont(),
    scale: foundText.getScale(),
    rotation: foundText.getRotation(),
    textBaseline: foundText.getTextBaseline(),
    fill: foundText.getFill() || undefined,
    stroke: foundText.getStroke() || undefined
  });
}
```

The things that suck about the code above are that it is fragile (it wouldn't necessarily do all you want in the future if new text properties are added) and it is weird that you have to provide `undefined` for fill and stroke if they are absent in the original (this could be improved with a small change to the text symbolizer constructor).

But it is still less code than you'd have to write for a `clone` method.  And I imagine people would ask about clone methods for other style things.  And is it deep clone (e.g. do fill and stroke get cloned for text)?

Does the code above look like it would do what you want?  It is not clear to me why some things like `textAlign` would get overridden and other things like `rotation` would not.  But I haven't looked where this gets called.

**Comment by tamarmot** [comment]
Hi, sorry for the radio silence.  So this code is all within the kml format -- so what I was trying to do was see if there was a style in the KML that was read in.  For example, in Google Earth if you create a placemark and give it a name, that name is rendered next to the placemark as a label.  You can also add a style to that placemark for the label, so yes your interpretation is correct.

This style definition should come from https://developers.google.com/kml/documentation/kmlreference#labelstyle

and this is parsed by the ol.format.KML.LabelStyleParser_ 
So it has color, colorMode,  and scale.

I think what would be more flexible / better would be to iterate through the keys in the javascript  dictionary coming in and copy their values.  How about I take a crack at it and do another pull request?

Tamar

**Comment by probins** [comment]
any progress on this? This is the only place in the library still using `goog.object`.

**Comment by tamarmot** [comment]
Hi, sorry for the radio silence -- I've been overly busy.
Realistically I will not be able to start working on this until 7/1 or so
-- if you want to fix it yourself that is completely fine with me.
I will put it on my calendar to start the work on 7/1.

Thanks for the reminder
Tamar

**Comment by tamarmot** [comment]
I have just initiated a pull request with the fixes for this issue, and also fixed rendering of icons and labels for KML placemarks.

**Comment by tamarmot** [comment]
I had to review the tests after my changes, and I discovered some more inconsistencies in the way OpenLayers rendered placemarks.  I have modified kml.js to now support placemarks with no icon, as that is one of the options in KML. Now, however, there are a bunch of code changes in this one commit so I'm not sure it'll pass muster.

**Comment by fredj** [comment]
#5745
