### ISSUE TITLE
Error in popup layer after upgrading from 3 to 3.8.2

### ISSUE THREAD

**Issue by bharathnav** [openlayers/ol3#4784]
Hi,

I was using openlayer 3.0.0 and angular-openlayers-directive 1.7.0. I upgraded from these version to 3.8.2 and 1.8.2. After doing so everything works fine apart from my popup marker. Please find attached the code below. Help me to resolve this issue.

		var marker = {
          lat : 41.19,
          lon : 10,
          label : {
            message: mapSiteDetails(building.name, ('Temp address ' + building.name)),
            show: false,
            showOnMouseClick: true
          },
          style : mapsMarkerStyle()
        }
		
		var mapSiteDetails = function(name, address){
		var content = '<div class="site-details"> ' +
							'<h4>' +
							name  +
							'</h4> ' +
							'<p> ' +
								address +
							'</p> ' +
							'<div>' +
								'<div> ' +
									'Building ' +
									'<br/>' +
									'<span>' +
										'-- ' +
									'</span>' +
								'</div>' +
								'<div>' +
									'Destination ' +
									'<br/>' +
									'<span>' +
										'--' +
									'</span>' +
								'</div>' +
							'</div>' +
						'</div> ';
		return content;
	  };

This code was working fine with older versions. After upgrade I'm getting the following error : 
_"Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'"_

Thanks,
Barry

**Comment by ahocevar** [comment]
I think you'd get better information regarding angular-openlayers-directive issues on https://github.com/tombatossals/angular-openlayers-directive.
