### ISSUE TITLE
issue with bingmap when feature more thn 5000

### ISSUE THREAD

**Issue by s332401890** [openlayers/ol3#4786]
when i load bingmap ,the feature more than  5000 ,bingmap will not be loaded。 on chrome、Firefox。

**Comment by ahocevar** [comment]
What feature are you referring to? Please share some code so we can understand the issue.

**Comment by s332401890** [comment]
feature = new ol.Feature({geometry:geom,id:data[i].id})

Simple square feature

**Comment by ahocevar** [comment]
Sorry, you're still very cryptic @s332401890. What is the exact issue you are seeing? How does the snippet you posted above relate to Bing Maps? If you want to report an issue or request help, please be so kind and spend some time describing your issue in a way so others can understand and reproduce it. A [JSFiddle](http://jsfiddle.net/) would be ideal, and you can use on of our [examples](http://openlayers.org/en/v3.13.1/examples/) as starting point.

**Comment by s332401890** [comment]
<html>
<head>
    <link rel="stylesheet" href="./css/ol.css" type="text/css" />
    <title>test</title>
</head>
<body>
<div id="Map">
    <input type="button"  id="square" value="矩形">
</div>
<script type="text/javascript" src="./js/ol.js"></script>
<script type="text/javascript" src="./js/jquery-1.11.2.js"></script>
<script type="text/javascript" src="./data/data.js"></script>
<script type="text/javascript">
    $(function(){
        var layer = null;
        var features = [];
        var baseLayer = new ol.layer.Tile();//地图底图图层
        var source_ = new ol.source.BingMaps({
            key: 'AkGbxXx6tDWf1swIhPJyoAVp06H0s0gDTYslNWWHZ6RoPqMpB9ld5FY1WutX8UoF',
            imagerySet: 'Aerial'
        });
        baseLayer.setSource(source_);
        var currMap = new ol.Map({
            layers: [baseLayer],
            target: 'Map',
            view: new ol.View({
                projection: 'EPSG:3857',
                center: new ol.proj.transform([112,23],'EPSG:4326', 'EPSG:3857'),
                zoom: 6
            })
        });
        $('#square').on('click',function(){
           if(layer) {
               currMap.removeLayer(layer);
               layer = null;
               return;
           } else {
               var data = tempData;
               var style = new ol.style.Style({
                   fill: new ol.style.Fill({
                       color: 'skyblue'
                   }),
                   stroke: new ol.style.Stroke({
                       color: 'black',
                       width: 1
                   })
               });
               layer = new ol.layer.Vector({
                   source: new ol.source.Vector({
                   }),
                   style: style
               });
               currMap.addLayer(layer);
               for(var i = 0;i<data.length; i++){
                   var feature, geom, itemCoords, coords = [];
                   itemCoords = data[i].coords;
                   for (var j = 0, lenn = itemCoords.length; j < lenn; j++) {
                       if(itemCoords[0].lon!=itemCoords[itemCoords.length-1].lon || itemCoords[0].lat!=itemCoords[itemCoords.length-1].lat){
                           itemCoords.push(itemCoords[0])
                       }
                       coords.push([itemCoords[j].lon, itemCoords[j].lat]);
                   }
                   geom = new ol.geom.Polygon([coords]);
                   geom.transform('EPSG:4326', 'EPSG:3857');
                   feature = new ol.Feature({
                       geometry : geom,
                       id: data[i].id
                   });
                   features.push(feature);
               }
               layer.getSource().addFeatures(features);
           }
        });
        
        $('#square').trigger("click");
    });

</script>
</body>
</html>

tempData like 
var tempData = [{"id":"polygon1","coords":[{"lon":116.153076,"lat":28.733948},{"lon":116.353076171875,"lat":28.733948},{"lon":116.353076171875,"lat":28.93394775390625},{"lon":116.153076,"lat":28.93394775390625}]}, ....];

**Comment by s332401890** [comment]
$(function(){
        var layer = null;
        var features = [];
        var baseLayer = new ol.layer.Tile();//地图底图图层
        var source_ = new ol.source.BingMaps({
            key: 'AkGbxXx6tDWf1swIhPJyoAVp06H0s0gDTYslNWWHZ6RoPqMpB9ld5FY1WutX8UoF',
            imagerySet: 'Aerial'
        });
        baseLayer.setSource(source_);
        var currMap = new ol.Map({
            layers: [baseLayer],
            target: 'Map',
            view: new ol.View({
                projection: 'EPSG:3857',
                center: new ol.proj.transform([112,23],'EPSG:4326', 'EPSG:3857'),
                zoom: 6
            })
        });
        var addFeature  = function(){
           if(layer) {
               currMap.removeLayer(layer);
               layer = null;
               return;
           } else {
               var data = tempData;
               var style = new ol.style.Style({
                   fill: new ol.style.Fill({
                       color: 'skyblue'
                   }),
                   stroke: new ol.style.Stroke({
                       color: 'black',
                       width: 1
                   })
               });
               layer = new ol.layer.Vector({
                   source: new ol.source.Vector({
                   }),
                   style: style
               });
               currMap.addLayer(layer);
               for(var i = 0;i<data.length; i++){
                   var feature, geom, itemCoords, coords = [];
                   itemCoords = data[i].coords;
                   for (var j = 0, lenn = itemCoords.length; j < lenn; j++) {
                       if(itemCoords[0].lon!=itemCoords[itemCoords.length-1].lon || itemCoords[0].lat!=itemCoords[itemCoords.length-1].lat){
                           itemCoords.push(itemCoords[0])
                       }
                       coords.push([itemCoords[j].lon, itemCoords[j].lat]);
                   }
                   geom = new ol.geom.Polygon([coords]);
                   geom.transform('EPSG:4326', 'EPSG:3857');
                   feature = new ol.Feature({
                       geometry : geom,
                       id: data[i].id
                   });
                   features.push(feature);
               }
               layer.getSource().addFeatures(features);
           }
        }
        
        addFeature();
    });

tempData like 
var tempData = [{"id":"polygon1","coords":[{"lon":116.153076,"lat":28.733948},{"lon":116.353076171875,"lat":28.733948},{"lon":116.353076171875,"lat":28.93394775390625},{"lon":116.153076,"lat":28.93394775390625}]}, ....];

**Comment by s332401890** [comment]
openlayer version V3.8.2

**Comment by ahocevar** [comment]
You are generating invalid geometries. A polygon needs to have the first point repeated as last point. Also, you may want to look into a more efficient format to transfer your data, e.g. GeoJSON, and use the `url` and `format` options of `ol.source.Vector` instead of using an inefficient custom `addFeature` function to parse your data.

If you still feel it's too slow after these improvements, use `ol.source.ImageVector` for a faster way of rendering, without a re-render at every frame.
