### ISSUE TITLE
Consider keeping max tile loads constant

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#4790]
Currently, the number of concurrent tile loads allowed [scales with the number of tile sources](https://github.com/openlayers/ol3/blob/master/src/ol/map.js#L1032-L1033).  This means degraded application performance with more tile sources.  We should try keeping this constant and test performance in applications with many tile sources.

See https://github.com/tschaub/ol3/commit/c2831c7e8517609d5e5792e5db2d7f2348cf682a#commitcomment-15879564 for the original discussion.

**Comment by marcjansen** [comment]
:+1: on the general idea of having the max tile load not being dependent on the number of tile sources.

**Comment by ahocevar** [comment]
Working on a pull request for this right now.
