### ISSUE TITLE
Feature attribute gets broken randomly

### ISSUE THREAD

**Issue by vicvolk** [openlayers/ol3#4799]
Below I provide a code that demonstrates the issue. To make it clear, I added two console.log statements. 

    <html>
    <head>
    <title></title>
    <link rel="stylesheet" href="/js/v3.12.1/css/ol.css" type="text/css" />
    <script src="/js/v3.12.1/build/ol-debug.js"></script>
    </head>
    <body>
    <input type="button" value="Draw" onclick="drawIt()"/> &nbsp; <input type="button" value="Select" onclick="selectIt()" /> <BR/>
    <div id="map"></div>
    <script type="text/javascript">

        var osm = new ol.layer.Tile({
		    source: new ol.source.OSM()
	    });
	
	    var source = new ol.source.Vector({wrapX: false});
	
	    var features = new ol.Collection();
	
	    var vector = new ol.layer.Vector({
		    source: source,
		    style: function(feature, resolution){
		        console.log(feature.get('secret_key'));
                // ^^^ it's ok. it prints "007"
			    return new ol.style.Style({
				    fill: new ol.style.Fill({
					    color: 'rgba(255, 255, 255, 0.2)'
				    }),
				    stroke: new ol.style.Stroke({
					    color: '#ffcc33',
					    width: 2
				    }),
				    image: new ol.style.Circle({
					    radius: 27,
					    fill: new ol.style.Fill({
						    color: '#ffcc33'
					    })
				    })
			    });
		    }
        });
	  
	    var map = new ol.Map({
	        layers: [osm, vector],
	        target: 'map',
	        view: new ol.View({
	            center: ol.proj.transform([0, 0], "EPSG:4326", "EPSG:3857"),
	            zoom: 4
	        })
        });
	
	
	    function drawIt(){
	        clearInteractions();
		
            var draw = new ol.interaction.Draw({
		        source: source,
			    features: features,
		        type: ("Point")
	        });
		    draw.on('drawend', function(e) {
			    e.feature.setProperties({
				    'secret_key': '007'
			    });
		    });		
	        map.addInteraction(draw);

            var modify = new ol.interaction.Modify({
		        features: features,
			    deleteCondition: function(event) {
			      return ol.events.condition.shiftKeyOnly(event) &&
				  ol.events.condition.singleClick(event);
			    }
		    });
		    map.addInteraction(modify);
		
	    }
	
	    function selectIt(){
	        clearInteractions();
            var select = new ol.interaction.Select();
		    map.addInteraction(select);
		    select.on('select', function(evt){
			    var selected = evt.selected;
			    selected.forEach(function(feature){
				    console.log(feature.get('secret_key'));
                    // ^^^ insane randomness
                    // sometimes it prints "007"
                    // sometimes not
			    });
		    });		
	    }
	
	    function clearInteractions(){
	        map.getInteractions().forEach(function(interaction){
		        map.removeInteraction(interaction);
		    });
	    }
	
    </script>
    </body>
    </html>

As you can see, one log statement works good and shows that feature property is set correctly. Another log statement, which is inside `Select` interaction demonstrates total randomness.

**Comment by vicvolk** [comment]
I see the very same issue in the last release of the library (3.13.1).

**Comment by ahocevar** [comment]
Your features are fine. but your Select interaction may select the editing vertex from your Modify interaction. Configure your Select interaction with a layers option to make sure you're only selecting from the vector layer:
```js
var select = new ol.interaction.Select({layers: [vector]});
```

**Comment by vicvolk** [comment]
Thank you, sir!
