### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by speechlogger** [openlayers/ol3#4801]
What does "documentation and/or other materials" mean exactly? 
"Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution."
I'm developing an app... So, in the "about" ? Does it have to be visible on the map itself? In the app-store listing?
Thanks!

**Comment by tschaub** [comment]
OpenLayers is licensed with the BSD 2-Clause License (see https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)).  You do not need to make the copyright notice or the full text of the license visible on the map itself.

When you build an application that includes OpenLayers, the license for your application should (or must according to the BSD 2-Clause) include the copyright notice for OpenLayers (e.g. 'Copyright  OpenLayers Contributors. All rights reserved.') and the full text of the original license.  I imagine you would include this wherever you describe the license for your application.

You might find more specific advice on a forum for whatever app store you are using.  The only part about OpenLayers that you need to know is that it is distributed with the BSD 2-Clause license.

**Comment by speechlogger** [comment]
Got it, thanks!


All the best,

Speechlogger team

More of our highest quality, free & unlimited web-apps:

https://speechnotes.co - The best Dictation Notepad on the web
http://ttsreader.com - Full articles reader online, natural voices,
multilingual
https://speechlogger.appspot.com/ - Real time captioning and translation
http://speechninja.co - An online aid for speech difficulties (AAC)
--
If you like speechlogger please share it with friends, and / or rate us on
the chrome store:
https://chrome.google.com/webstore/detail/speech-recognition-transl/jjgohjmefljmabkekbfgfhockfegohfp?hl=en

https://chrome.google.com/webstore/detail/speechnotes-dictation-not/opekipbefdbacebgkjjdgoiofdbhocok/reviews?hl=en



--


2016-02-07 19:24 GMT+02:00 Tim Schaub <notifications@github.com>:
