### ISSUE TITLE
Update documentation to add API key parameter in code samples

### ISSUE THREAD

**Issue by huguesnarjoux** [openlayers/ol3#4807]
Hi,

Google Maps team here. Google is encouraging the use of keys for Google Maps APIs as described here:
https://developers.google.com/maps/documentation/javascript/get-api-key

Could you update your documentation and code samples to reflect this please? In particular this page:
http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/google-v3.html

Thanks,

**Comment by ahocevar** [comment]
Wrong repository. I created openlayers/ol2#1487.
