### ISSUE TITLE
Map doesn't reappear after hiding the container, resizing the viewport and displaying the container again

### ISSUE THREAD

**Issue by codemusings** [openlayers/ol3#4817]
Hi there,

it seems like the map canvas is being hidden and disabled when I hide its container, resize the viewport and display the container again. I have a self contained example here:

     https://gist.github.com/codemusings/dae2c4edc16edd6ea708

It seems that when the viewport is resized and the map canvas is off-screen it gains the attribute "display: none". Even if I remove it manually the map doesn't respond to input events anymore. Is there any way to work around this?

I've reproduced this in Firefox 44, Chrome 47, Chromium 47, Chrome for Android.

**Comment by codemusings** [comment]
So in case somebody has the same problem. Calling [updateSize()](http://openlayers.org/en/v3.13.1/apidoc/ol.Map.html#updateSize) after the container is shown again fixes the problem. I don't think this is desired behaviour though.

**Comment by ahocevar** [comment]
Another way to temporarily remove a map is to call `map.setTarget(null);`.

**Comment by codemusings** [comment]
So no fix? I spent hours debugging this. On mobile it's perfectly normal to hide and display container views depending on what the focus is at the moment. And the viewport gets resized pretty often when the keyboard is being shown and hidden again. This is hardly expected!

**Comment by ahocevar** [comment]
What kind of fix are you suggesting?

**Comment by codemusings** [comment]
To not hide the canvas element and not disable the map interaction when the viewport gets resized? I don't understand why this happens in the first place. Also the controls are still visible when this happens. So even if this is expected behavior it's not really a consistent one.

**Comment by ahocevar** [comment]
OpenLayers listens for resize events on the browser window. This should cover resizes when the map is visible. Can you verify that it works when you do not set the map container to `display:none`?

**Comment by codemusings** [comment]
I'm unclear on what you mean.
> OpenLayers listens for resize events on the browser window. This should cover resizes when the map is visible.

This would only make sense if the ol-viewport element would span the whole browser viewport. Which it obviously does not by default. I'm assuming it listens to resize events of the containing element to determine whether it needs to render stuff.

> Can you verify that it works when you do not set the map container to display:none?

That obviously works because other wise the map would disappear everytime a browser window gets resized. But maybe I just don't understand what you're saying.

**Comment by ahocevar** [comment]
> This would only make sense if the ol-viewport element would span the whole browser viewport. Which it obviously does not by default. I'm assuming it listens to resize events of the containing element to determine whether it needs to render stuff.

There is no resize event on arbitrary dom elements, only on `window`.

**Comment by giridharkl** [comment]
Hi,
I have a similar issue. My environment is Angular 4, using openlayers npm package. In my application i have multiple tabs. Each tab contains a location map. When I resize the browser window, only the last tab content holds the map and the other tabs lose the map. However when I checked the map in other tab the property "display:none" on the canvas. If I disable it the map shows up again. I tried capturing the window:resize event and call map.updateSize(). The event gets triggered, but the map do not re-appear in the tab content. 

I tried the following code:
@HostListener('window:resize', ['$event'])
  onResize(event) {
    //debugger;
    //event.target.innerWidth;
    this.map.updateSize();
  } 
This did not yield expected result. Also tried the following code:
ngAfterViewChecked() {
    //debugger;
    if (this.locMap.nativeElement.getAttribute('height') != '200px' || 
      this.locMap.nativeElement.getAttribute('widht') != '300px') {
        this.map.updateSize();
      }
  } 

Please help me to resolve this issue. Even an idea how to go about it would be of great help.
Thanks
Giri

**Comment by auspex** [comment]
@ahocevar I think you've misunderstood part of the original problem statement. He hides the container, but he does __not__ add the `display:none` style to the canvas. Openlayers seems to do this for some reason. In my case, when I shrink my original window to less than 2/3 it's original width, the map disappears, and calling `.updateSize()` doesn't bring it back after I enlarge the window. I have to manually reset the `display` style.

**Comment by ahocevar** [comment]
You're right @auspex. The map renderer sets the map canvas's display to 'none' when there is no frame state, i.e. when the renderer has nothing to render. Anyway, you're the first one saying that `updateSize()` does not bring the map back. Can you share a minimal code example that shows the issue?

**Comment by auspex** [comment]
I'll try when I get back into work. I need to minimize my code, anyway, to
figure out why the damn thing just completely disappears in the first place

derek

**Comment by auspex** [comment]
Sorry, I did, finally (much later) track it down to an interaction with
bootstrap. An outer DIV was classed "hidden-xs". When the window was made
small enough to hide the div, then the canvas gets "display:none", then
enlarging it again never reset the display style.

derek

**Comment by cvanslyke** [comment]
@auspex 
Can you give me a code example of how you worked around this issue? I'm having what sounds like this exact same problem (but only on IE).  I've tried calling updateSize() doesn't bring it back.

**Comment by auspex** [comment]
Pretty simple. It was just 
```
<div class="hidden-xs">
	<form onsubmit="return false;">
		<label class="hideable">Tow Ids (separated by ,)
			<input id="towIds" type="text">
		</label>
		<div id="map" class="map">
		</div>
		<div style="width:50%;margin:auto;">
			<button id="printBtn" class="btn btn-default" type="button"><i class="glyphicon glyphicon-print"></i> Print Map</button>
			<a id="export-png" class="btn btn-default" download="map.png"><i class="icon-download"></i> Export PNG</a>
		</div>
	</form>
</div>
```
where the map is in the `<div id="map>` tag.  When the view gets too small, Bootstrap hides the `<div class="hidden-xs">` but when it enlarges again, bootstrap will redisplay the outer `<div>` but openlayers  leaves the inner div with `style="display:none"`

**Comment by ojathelonius** [comment]
I solved the issue by manually displaying the canvas after resizing the container : 

```javascript
document.querySelectorAll("#map canvas");
```

I had this issue while changing the map target with `map.setTarget('another-map')` : the map canvas would stay blank and only controls would appear.

**Comment by ojathelonius** [comment]
For those having an issue with updating size, see https://github.com/openlayers/openlayers/issues/4601

You need to give OL some time to resize the map before updating, as shown below : 

```javascript
setTimeout(function() {
    map.updateSize();
}, 100);
```

This is not the cleanest solution but it does work.

**Comment by jaumemirallesisern** [comment]
> For those having an issue with updating size, see #4601
> 
> You need to give OL some time to resize the map before updating, as shown below :
> 
> ```js
> setTimeout(function() {
>     map.updateSize();
> }, 100);
> ```
> 
> This is not the cleanest solution but it does work.

This solution worked for me as well. The map.updateSize() without time didn't. Thanks.

**Comment by loicbcn** [comment]
Hello, 
Look like it depends the transition duration in Bootstrap:
In bootstrap 5:
```css
.fade {
    transition: opacity .15s linear;}
```
Then
```javascript
setTimeout(function() {
    map.updateSize();
}, 100);
```
is not working BUT
```javascript
setTimeout(function() {
    map.updateSize();
}, 160);
```
Is working.
