### ISSUE TITLE
async/callback-based tile url function support

### ISSUE THREAD

**Issue by jumpinjackie** [openlayers/ol3#4820]
It would be great if tile url functions can be asynchronous and take a callback that the tile url function can pass the tile url back into.

This would allow for cases where we can have tile url functions that can return tile data URIs stored in a local IndexedDB, whose APIs (and most wrappers for it) are all asynchronous in nature. This would enable us to build something similar to the CacheRead/CacheWrite controls in OL2.

**Comment by ahocevar** [comment]
Have you had a look at `tileLoadFunction`? It was made exactly for that purpose.

**Comment by jumpinjackie** [comment]
Ah, yes I see how it works.
