### ISSUE TITLE
Simulate moveByPx

### ISSUE THREAD

**Issue by krzbor** [openlayers/ol3#4834]
I have to synchronize my map with OL3. In the previous version (OL2) there was the function map.moveByPx. How to simulate this function on the OL3?

**Comment by tsauerwein** [comment]
You could use [ol.Map#getPixelFromCoordinate](http://openlayers.org/en/v3.13.1/apidoc/ol.Map.html#getPixelFromCoordinate) and [ol.Map#getCoordinateFromPixel](http://openlayers.org/en/v3.13.1/apidoc/ol.Map.html#getCoordinateFromPixel) for the center:

        var view = map.getView();
        var center = view.getCenter();
        var centerPx = map.getPixelFromCoordinate(center);
        var newCenterPx = [centerPx[0] + 10, centerPx[1] + 10];
        var newCenter = map.getCoordinateFromPixel(newCenterPx);
        view.setCenter(newCenter);  

http://jsfiddle.net/knv1mb2p/

**Comment by krzbor** [comment]
Thank you very much
