### ISSUE TITLE
Tooltip does not work with newest angular

### ISSUE THREAD

**Issue by minhduong** [openlayers/ol3#4835]
Hi,
This is not work with newest angular
http://openlayers.org/en/v3.13.1/examples/kml-earthquakes.html

Error: info.tooltip is not a function
["D:\\project\\fieldtec\\source\\development\\fieldtec-web\\client\\app\\scripts\\modules\\core\\directives\\AddressMap.js"]</</<.link@http://localhost:3000/scripts/bundle.js:3079:1
cloneAndAnnotateFn/<@http://localhost:3000/scripts/bundle.js:140194:41
invokeLinkFn@http://localhost:3000/scripts/bundle.js:140200:9
nodeLinkFn@http://localhost:3000/scripts/bundle.js:139694:1
compileTemplateUrl/<@http://localhost:3000/scripts/bundle.js:139931:1
processQueue@http://localhost:3000/scripts/bundle.js:146151:28
scheduleProcessQueue/<@http://localhost:3000/scripts/bundle.js:146167:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/scripts/bundle.js:147411:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/scripts/bundle.js:147229:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/scripts/bundle.js:147519:13
done@http://localhost:3000/scripts/bundle.js:141948:36
completeRequest@http://localhost:3000/scripts/bundle.js:142146:7
requestLoaded@http://localhost:3000/scripts/bundle.js:142087:1

<ft-address-map class="ng-isolate-scope" doc="ngModel.doc" tpl="ngModel.tpl" key="0" store="save()" account="user.filteredAccount">

**Comment by tschaub** [comment]
The `tooltip` function in that example comes from [Bootstrap](http://getbootstrap.com/javascript/#tooltips).  You would need to include the Bootstrap JavaScript in your application if you wanted to use the same function.  However, since you are using Angular to provide UI elements, you'd be better off creating your own tooltips with Angular.
