### ISSUE TITLE
GeoJSON with OGC CRS URN may raise error

### ISSUE THREAD

**Issue by jvanulde** [openlayers/ol3#4840]
A GeoJSON file with a CRS will raise error `Uncaught AssertionError: Assertion failed: transform should be defined` and fail to load if there is no colon in the projection. For example the following will work: `"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS:84" } }` but  `"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } }` won't work. Note the lack of a colon between CRS and 84.

**Comment by ahocevar** [comment]
`"urn:ogc:def:crs:OGC:1.3:CRS:84"` is not a registered alias for EPSG:4326 in OpenLayers. Maybe you want to create a pull request and add it to `src/ol/proj/epsg4326projection.js`?

**Comment by jvanulde** [comment]
Is there a way to programatically add an alias?

**Comment by ahocevar** [comment]
With proj4js it's super easy:
```
proj4.defs('urn:ogc:def:crs:OGC:1.3:CRS:84', proj4.defs('EPSG:4326');
```

**Comment by bartvde** [comment]
Please note that the axis order for CRS84 is different from EPSG:4326

**Comment by ahocevar** [comment]
proj4.js does not know about axis order though. @bartvde may correct me, but I think GeoJSON always uses x, y axis order.

**Comment by bartvde** [comment]
Ah sorry I was thinking of ```ol.proj.addEquivalentProjections``` for adding the alias, in which case the ol projection objects do know about axis order.

**Comment by jvanulde** [comment]
If I employ the solution suggested by @ahocevar it works. I simply added 'proj4.defs('urn:ogc:def:crs:OGC:1.3:CRS84', proj4.defs('EPSG:4326'));'

**Comment by jvanulde** [comment]
Although added the alias programatically solves the problem it isn't ideal for dynamically loaded data where the projection is not known before initialization. If both versions of the URN (i.e. with and without the colon) are valid according to the specification then perhaps the both aliases should be available by default.

**Comment by bartvde** [comment]
I personally doubt the second version is valid.

**Comment by ahocevar** [comment]
@jvanulde If you want to load arbitrary GeoJSON data with different projection, it will probably be best to run a preflight check on the GeoJSON and work with an online service (e.g. http://epsg.io/) to load proj4.js definitions before you process the GeoJSON in OpenLayers.

**Comment by jvanulde** [comment]
@bartvde see http://portal.opengeospatial.org/files/?artifact_id=30575, Table 3. Seems as though CRS84 is acceptable.

**Comment by ahocevar** [comment]
We have that as alias @jvanulde. We don't have the `CRS:84` one.

**Comment by bartvde** [comment]
![screen shot 2016-02-15 at 15 56 25](https://cloud.githubusercontent.com/assets/319678/13052012/b28f76bc-d3fc-11e5-878a-fd9898277aac.png)

Here they say previously referenced as ```CRS:84```

**Comment by bartvde** [comment]
So maybe both were valid at some point in time, how I love the OGC :-)

**Comment by ahocevar** [comment]
Exactly @bartvde. `urn:ogc:def:crs:OGC:1.3:CRS84` and `CRS:84` are equivalent, and we have aliases for both. `urn:ogc:def:crs:OGC:1.3:CRS:84` is invalid though.

**Comment by bartvde** [comment]
Correct @ahocevar, this is confusing though :-)

**Comment by jvanulde** [comment]
Nice find @bartvde! So it seems as though both are "valid".

**Comment by ahocevar** [comment]
No @jvanulde. Use your choice of `CRS:84` or `urn:ogc:def:crs:OGC:1.3:CRS84`, but not `urn:ogc:def:crs:OGC:1.3:CRS:84`.

**Comment by bartvde** [comment]
Hmm in https://portal.opengeospatial.org/modules/admin/license_agreement.php?suppressHeaders=0&access_license_id=3&target=http://portal.opengeospatial.org/files/?artifact_id=33316 there is a reference though @ahocevar 

![screen shot 2016-02-15 at 16 02 03](https://cloud.githubusercontent.com/assets/319678/13052153/8e20b0d8-d3fd-11e5-8e45-892e1c30dc33.png)

**Comment by ahocevar** [comment]
OGC madness.

**Comment by ahocevar** [comment]
If in doubt, I prefer what the GeoJSON spec says: http://geojson.org/geojson-spec.html#named-crs

**Comment by ahocevar** [comment]
@bartvde, you're the one who can judge best what do do with OGC madness. Should `urn:ogc:def:crs:OGC:1.3:CRS:84` be added as alias for `CRS:84` in `src/ol/proj/epsg4326projection.js` or not?

**Comment by bartvde** [comment]
haha, am I the expert on OGC madness :-) ?
I'm not against adding it.

**Comment by ahocevar** [comment]
haha, you're the expert in **dealing with** OGC madness!

**Comment by bartvde** [comment]
LOL

**Comment by ahocevar** [comment]
So @jvanulde, like I [suggested](https://github.com/openlayers/ol3/issues/4840#issuecomment-184211462).

**Comment by fredj** [comment]
@jvanulde, @ahocevar, @bartvde can we close this issue?

**Comment by bartvde** [comment]
@jvanulde are you up for doing a PR as @ahocevar suggested?
If not, let's close this.

**Comment by jvanulde** [comment]
I don't think there is any point in adding the one alias. I will close.
