### ISSUE TITLE
Dashed line style not rendered properly when projected

### ISSUE THREAD

**Issue by jvanulde** [openlayers/ol3#4844]
Dash is not rendered properly on all feature segments of projected layer. See attached image. Datasource is TopoJSON and style contains `strokeDash: [ 6, 4 ]`. Note solid line on border between Canada and Alaska.

![screen shot 2016-02-15 at 8 52 41 am](https://cloud.githubusercontent.com/assets/2255248/13055016/b7e3d22e-d3c1-11e5-91c4-21d154dd7e63.png)

**Comment by ahocevar** [comment]
My guess is that the dashes from the Canada polygon outline and the U.S.A. polygon outline align in a way that they result in a solid line.

**Comment by jvanulde** [comment]
That is my thought as well, but since it's TopoJSON I would expect that type of anomaly to be minimized.

**Comment by ahocevar** [comment]
OpenLayers generates plain, non-topological geometries out of TopoJSON. So you have two lines with the exact same vertices overlapping at borders, but the dashes along the line don't align with vertices of course for a smooth appearance.

**Comment by jvanulde** [comment]
Makes sense but why is it that the UK and Alaska are not dashed? There are not shared boundaries there.

**Comment by ischas** [comment]
Is there only the UK as whole unit or are there the members (England, Scotland, ...), too? If the last is correct, then the outlines of the UK and its members may overlap.

**Comment by ahocevar** [comment]
Without seeing your data, we can only speculate.

**Comment by jvanulde** [comment]
[https://github.com/mbostock/topojson/blob/master/examples/world-110m.json](url)

**Comment by ahocevar** [comment]
Are the borders rendered on an `ol.layer.Vector`? Or `ol.layer.ImageVector`? Or something else? The same data set is used in http://openlayers.org/en/v3.13.1/topojson.html. Are you able to create a JSFiddle from that example that shows the issue?

**Comment by jvanulde** [comment]
It is rendered on an ol.layer.Vector as follows:

    var myLayer = new ol.layer.Vector( {    
        source: new ol.source.Vector( {
            url: layerUrl,
            format: new ol.format.TopoJSON(),
            strategy: ol.loadingstrategy.bbox
        } )
    } );

**Comment by ahocevar** [comment]
Ha! The `strategy` might duplicate your features. Try to remove `strategy: ol.loadingstrategy.bbox`.

**Comment by jvanulde** [comment]
No change when removing the strategy.

![screen shot 2016-02-16 at 1 38 52 pm](https://cloud.githubusercontent.com/assets/2255248/13092033/d4289ff4-d4b2-11e5-9c12-d94665845661.png)

**Comment by ahocevar** [comment]
For debugging: give each country border a random color, then you'll see if lines with different colors overlap.

**Comment by tschaub** [comment]
That `world-110m.json` file includes a geometry that represents all land masses.  When rendered together with country polygons, you might see duplicate dashed strokes resulting in a solid line.  If this is your issue, you might find that filtering out features without an `id` get rid of the redundant geometry.  See the [topojson example](https://github.com/openlayers/ol3/blob/9dbf9541e9de713e2fb8081a981c7d34f7fe0c37/examples/topojson.js#L34-L37) for inspiration.

**Comment by tschaub** [comment]
@jvanulde that is a nice looking map.  Can you share a link?

**Comment by jvanulde** [comment]
@tschaub as soon as I am done I will post a link.

**Comment by jvanulde** [comment]
Using @tschaub suggestion above I was able to fix the issue by removing the redundant geometry.
