### ISSUE TITLE
How to determine whether the currently executing a PinchMove?

### ISSUE THREAD

**Issue by krzbor** [openlayers/ol3#4850]
How to determine whether the currently executing a PinchMove? How does PinchZoom.on()? I have to synchronize my map with PinchMove.

**Comment by ahocevar** [comment]
`ol.interaction.PinchZoom` does not emit any events. Can you put your question in a context, i.e. where would that information be useful?

**Comment by krzbor** [comment]
I have two maps. Maps overlap. At the bottom is my map, and at the top is "OL3". I sync maps using "movend." I use "pointerdrag" when moving. I discovered that "pointerdrag" is also fired during PinchZoom. This solves my problem.
