### ISSUE TITLE
Support minZoom in ol.source.Stamen

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#4853]
[These lines](https://github.com/openlayers/ol3/blob/13a981c94be6e4c79f54e1fdd1f052c39f46163b/src/ol/source/stamensource.js#L108-L109) have a `FIXME` which we might be able to remove, right?

AFAICT our tilegrid supports `minZoom`.

The `FIXME` wass added in 6d6188ea791b7d6033f9e0c2aeae9cccf004199d (nearly 3 years ago).

**Comment by ahocevar** [comment]
This can be fixed now, but not by passing `minZoom: options.minZoom` to the superclass of the source. Instead, by passing `tileGrid: ol.tilegrid.createXYZ({minZoom: options.minZoom})` to the superclass. Untested.
