### ISSUE TITLE
Drag&Drop, drag only feature clone

### ISSUE THREAD

**Issue by janczewskit** [openlayers/ol3#4857]
When i drag feature i want see feature copy in start position. Idea is something like shoping where features are products and buyer can drag element to basket more than one time. http://openlayers.org/en/v3.6.0/examples/drag-features.html  i was trying edit code from this link but when i use clone feature and add to layer dragging stop working or copy of feature still not visible

**Comment by ahocevar** [comment]
Please consider asking usage questions on http://stackoverflow.com/, using the `openlayers-3` tag. The issue tracker is for bug reports and feature requests.
