### ISSUE TITLE
ol.Overlay autoPan pans to outside of olView extent and in wrong direction

### ISSUE THREAD

**Issue by jvanulde** [openlayers/ol3#4859]
I have a popup overlay on my map with autoPan set to true on ol.Overlay. The map is panned outside of the set ol.View extent and sometimes is panned in the wrong direction (e.g. pans left instead of right). Here is my code:

	// Create an overlay to anchor the popup to the map.
	var overlay = new ol.Overlay(/** @type {olx.OverlayOptions} */ ( {
		element: document.getElementById( "popup" ),
		autoPan: true,
		autoPanAnimation: {
			duration: 250
		}
	} ) );

The map is projected in case that might be causing an issue. As this is experimental, I would be interested in other ways to implement the desired functionality.

**Comment by ahocevar** [comment]
Can you create a reproducible example, maybe based on http://openlayers.org/en/v3.13.1/examples/popup.html?

Note: When something is marked 'Experimental' in the API docs, it does not mean that it does not work well. It only means that the user facing API might change in the future.

**Comment by jvanulde** [comment]
I have tried setting up a fiddle here: [http://jsfiddle.net/jvanulde/b6hh5gv7/16/](http://jsfiddle.net/jvanulde/b6hh5gv7/16/) but for some reason the base layer isn't rendering. It's more or less to cut and paste from my existing code that displays the map in the image below.

![screen shot 2016-02-22 at 1 47 43 pm](https://cloud.githubusercontent.com/assets/2255248/13233899/e82bb1f0-d96a-11e5-8f94-6d7f1b9df8e1.png)

**Comment by jvanulde** [comment]
I solved this by setting the overlay position to undefined when a feature was deselected.
