### ISSUE TITLE
Examples failed to load on IE 9

### ISSUE THREAD

**Issue by oterral** [openlayers/ol3#4865]
Just open http://openlayers.org/en/master/examples/animation.html on IE9

Js Error: 
```
SCRIPT438: L’objet ne gère pas la propriété ou la méthode « requestAnimationFrame »
```

It seems the problem comes from [here](https://github.com/openlayers/ol3/blob/master/src/ol/map.js#L1233)

**Comment by oterral** [comment]
@ahocevar have you an idea what is the reason ? becaus it worked  with [v3-13-1](http://openlayers.org/en/v3.13.1/examples/animation.html)

**Comment by ahocevar** [comment]
@oterral The removal of goog.events.*.

**Comment by oterral** [comment]
We'll prefer to don't have to add polyfill.js in our project could we simply remove the use of `goog.global.requestAnimationFrame` ?

**Comment by fredj** [comment]
Note that the function used previously (`goog.async.AnimationDelay`) was only a [requestAnimationFrame polyfill](https://github.com/google/closure-library/blob/20160208/closure/goog/async/animationdelay.js#L42-L43)

**Comment by oterral** [comment]
Thx @fredj , I guess adding polyfill.js is the good way to do that.
