### ISSUE TITLE
Allow refreshing a source

### ISSUE THREAD

**Issue by sebasbaumh** [openlayers/ol3#4867]
My need is to refresh a given layer in a map by refreshing its source to reload tiles from an URL.

Currently `changed` can be called on a source to refresh it, which is good for most of the cases.
But unfortunately it does not clean up internal state for already loaded tiles in a `ol.source.Tile` source.
The tiles still live in the `tileCache` and are not reloaded at all.

The pull request I am creating will allow to refresh any source.
For most of the sources just a `changed` event is fired, but for tile sources the internal tile cache is cleared beforehand.
From the API point of view it will be sufficient to just call `refresh` on any source.

**Comment by tschaub** [comment]
This was fixed by #4868.
