### ISSUE TITLE
Travis CI build fails with timeout

### ISSUE THREAD

**Issue by sebasbaumh** [openlayers/ol3#4871]
Seems like there is an issue with the Travis CI build.
It failed with a timeout though I just added one function to two classes, which shouldn't trigger a timeout.

See here for the log: https://travis-ci.org/openlayers/ol3/builds/110145868#L4363

**Comment by ahocevar** [comment]
I restarted the build. It's not unusual for Travis to have occasional hickups.

**Comment by sebasbaumh** [comment]
Thanks! Unfortunately I was unable to restart the build by myself (beside committing to the existing pull request, which I wanted to avoid).

**Comment by tschaub** [comment]
@sebasbaumh note that you can force push a commit to trigger a build.  While we don't force push to master, it is common for feature branches.

```
git commit --amend
git push --force your-origin your-branch-name
```

**Comment by sebasbaumh** [comment]
Ah ok.
I just refused to push a trivial commit, which would clutter the pull request, just for restarting the build.
