### ISSUE TITLE
Issue when using Openlayers proj4js with RequireJS.

### ISSUE THREAD

**Issue by GraemeMcCartneyIBI** [openlayers/ol3#4875]
I am experiencing an issue when using Openlayers proj4js with RequireJS.

I have a fairly standard piece of code that works without Require managing the dependancies. It displays a map and shows the coordinates in EPSG:27700 using an Openlayers mouse position control.

When using Require, the code fails when getting the projection using an Openlayers proj.get. The dependencies are defined as follows:

    define(['openlayers', 'proj4'], function (openLayers, proj4) {
    
The projection is added as follows, but the proj.get returns undefined:

    proj4.defs('EPSG:27700', '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs');

    openLayers.proj.get("EPSG:27700").setExtent([0, 0, 700000, 1300000]);

I am aware of a previous issue (#3990) where there was an issue using proj4js with Require.  I have made sure that I am using the latest version of OL3 in line with that resolved issue.

**Comment by ahocevar** [comment]
Try
```js
define(['openlayers', 'proj4'], function (openLayers, proj4) {
  openLayers.proj.setProj4(proj4);
  proj4.defs('EPSG:27700', '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs');
  openLayers.proj.get("EPSG:27700").setExtent([0, 0, 700000, 1300000]);
});
```
The important line is `openLayers.proj.setProj4(proj4)`. Requires OpenLayers > v3.13.0.
