### ISSUE TITLE
Can openlayer3 supporty Custom coordinate system?

### ISSUE THREAD

**Issue by s332401890** [openlayers/ol3#4878]
Can openlayer3 supporty Custom coordinate system?
i want to use Custom coordinate system,Is there any way to support ?

**Comment by s332401890** [comment]
Logical coordinate system

**Comment by ahocevar** [comment]
OpenLayers supports any coordinate system with x and y coordinates. As additional dimensions, it supports z and measure dimensions. You may want to read the documentation on [projections](http://openlayers.org/en/v3.13.1/apidoc/ol.proj.html).
