### ISSUE TITLE
Open Layers Example Navigation issue

### ISSUE THREAD

**Issue by edussooriya** [openlayers/ol3#4883]
goto http://openlayers.org/ and click on "Examples" then it will redirect to "http://openlayers.org/en/v3.13.1/examples/". it displays nothing.

![open layeres example doesn t work](https://cloud.githubusercontent.com/assets/4322937/13243182/7fd4a504-da22-11e5-9fc7-a49b1e29daa7.png)

**Comment by petrsloup** [comment]
This is working ok for me -- I see the examples listed as expected.

**Comment by fredj** [comment]
It's also working for me

**Comment by edussooriya** [comment]
@petrsloup nothing work for me though. checked on 2 broesers. ff and chrome. chrome version : Version 48.0.2564.116 & ff version 43.0.4

**Comment by ischas** [comment]
Cannot confirm this issue, but found another one concerning examples:

The Development/Production-selectbox on the upper right corner is poorly styled. The text should be black and not white.

![image](https://cloud.githubusercontent.com/assets/8558126/13246349/5f833342-da13-11e5-82d1-e4b5a220da6c.png)

Furthermore, the impact of this box should be explained somewhere.

**Comment by edussooriya** [comment]
looks wired. it doesn't even show any content in my IE too. but checked this in an another machine and it works fine. don't know what the problem is. anyway this can be closed if none of the others getting this issue.
