### ISSUE TITLE
Poor styling of examples' selectbox

### ISSUE THREAD

**Issue by ischas** [openlayers/ol3#4888]
Since the other issue is closed, here a copy of https://github.com/openlayers/ol3/issues/4883#issuecomment-187606395

The Development/Production-selectbox on the upper right corner is poorly styled. The text should be black and not white.

![image](https://cloud.githubusercontent.com/assets/8558126/13246349/5f833342-da13-11e5-82d1-e4b5a220da6c.png)

Furthermore, the impact of this box should be explained somewhere.

**Comment by tsauerwein** [comment]
Pull-request welcome! :)

**Comment by ischas** [comment]
The image is taken from 3.13.1, on master it's worse.

![image](https://cloud.githubusercontent.com/assets/8558126/13255967/f035e850-da48-11e5-8767-c63c6ab47cab.png)

@simonseyock @penpendede Anyone up for it?
Files to change: ol3/examples/resources/layout.css and ol3/examples/resources/common.js

**Comment by jonataswalker** [comment]
@ischas may you inform browser with version?

Here is how it looks:
![ol3-examples](https://cloud.githubusercontent.com/assets/10571881/13258399/c274060c-da31-11e5-8783-eea0b0cdef4a.png)

Either Chrome 48 or Firefox 44.

**Comment by ischas** [comment]
Okay, further research shows that it is not a version problem (FF 39, 42, 44, Chrome 48) but a matter of the window width.

On monitor 1 (window.innerWidth = 1366) it displays correctly (as shown by @jonataswalker ), but on monitor 2 (window.innerWidth = 1920) it looks like shown in in my previous comment.

The examples for version 3.13.1 look perfect on both monitors.

**Comment by ischas** [comment]
The position problem in the examples overview page comes from `.search-form { position: absolute; left: 450 px; }`.

The color problem comes from `.navbar { color: white; }`.

I don't get the position problem in the examples page, no CSS "expert", but I guess it's trivial. ;-)
