### ISSUE TITLE
Add arbitrary shape of style 

### ISSUE THREAD

**Issue by anzhihun** [openlayers/ol3#4898]
Sometimes, `ol.style.RegularShape`, `ol.style.Circle` and `ol.style.Image` can not handle my cases,  I need some arbitrary shape with different size and color. such as 
![shape1](https://cloud.githubusercontent.com/assets/1855738/13276040/2db9f66e-daf6-11e5-8627-f97cdbbfd020.png)
![shape2](https://cloud.githubusercontent.com/assets/1855738/13276044/31f2dfc0-daf6-11e5-8aa7-008ac50e46f8.png)
I have added a new style `ol.style.ArbitraryShape` . It can be used as follows:
```
         feature.setStyle(new ol.style.Style({
			image: new ol.style.ArbitraryShape({
				fill: new ol.style.Fill({
					color: 'red'
				}),
				stroke: new ol.style.Stroke({
					color: '#0000ff',
					width: 2
				}),
				size: [100, 100],
				points: [[1, 1], [1, 99], [99, 99], [99, 1]],
				rotation: 30 * Math.PI / 180
			})
		}));
```
`size`: `{ol.Size}` size of image.
`points`: `{Array.<ol.Coordinate>}` points of the arbitrary shape.

The new style can make shapes showed before.  So I think it maybe useful to others, I want to pull the code to the master if you like it. Do you like it?  Also, any suggestion? Thank you.

**Comment by ahocevar** [comment]
Have you seen the http://openlayers.org/en/v3.13.1/examples/earthquake-custom-symbol.html example?

**Comment by anzhihun** [comment]
Thank you! It is nice.  `Canvas` + `ol.style.Icon` seems to more flexible.
