### ISSUE TITLE
Manually add point to drawing instance(ol.interaction.Draw polygon)

### ISSUE THREAD

**Issue by QingyaFan** [openlayers/ol3#4904]
I'm working on a webpage based on android browser, and I want to add a point who's coordinate is from html5 Geolocation API to a polygon drawing by the ol.interaction.Draw instance(the polygon is unfinished). 

First I want to get the draw interaction's sketchCoords_(private) ,and push a new coordinate. But I can't get sketchCoords_,I remember previous version allow that, but now I use the latest version, and failed!

Then I noticed draw interaction has a method 'handleEvent(mapBrowserEvent), so I want to initialize a ol.MapBrowserEvent instance with my custom coordinate, but an error said that: 'ol.MapBrowserEvent()' is not a constructor.

Well, what I want to ask is:
1. Is there any possible I can get the drawing sketch?
2. How can I initialize a custom ol.MapBrowserEvent?
Or
My solutions are not right, any other ideas is welcomed. Can someone help me out? Thanks in advance!

**Comment by ahocevar** [comment]
You have several options, including
* Create a polygon geometry without Draw interaction, and add point to it using a point Draw interaction for manual input and Geolocation for GPS input.
* Use a polygon Draw interaction with a `geometryFunction`, which gives you access to the sketch coordinates.

**Comment by QingyaFan** [comment]
Thank you @ahocevar !  It works!
