### ISSUE TITLE
Layer groups with vector layers can not be hidden in dom renderer

### ISSUE THREAD

**Issue by chrisg86** [openlayers/ol3#4907]
Hey all,
I noticed that when you set the map renderer to 'dom', layer groups with vector layers cannot be hidden. We have switched from canvas to dom renderer, as there were problems with the canvas renderer as well (this is another problem). Additionally we are also using the ol3-layerswitcher plugin. Unselecting the layer group holding the vector layers in the layer switcher seems to disable the recalculation of the position for that layer, but does not hide it from the map.

Here's an example you can play around with. Code is taken from the openlayers website as well as the ol3-layerswitcher github page's basic example.
http://codepen.io/chrgl86/pen/BjXKrK

**Comment by tschaub** [comment]
Can you also create an issue describing your issues with the Canvas renderer?

**Comment by fredj** [comment]
@chrisg86 try with this build of OpenLayers: http://dev.camptocamp.com/files/fredj/ol_4907/ol.js

**Comment by chrisg86** [comment]
@fredj Thanks for the quick reply! It seems to work well in the codepen example. I will try it out in our project asap.

@tschaub will do.

**Comment by chrisg86** [comment]
@fredj I can confirm that the dev build fixes the problem. Thanks guys! Is there going to be a new production build soon including this fix?

**Comment by chrisg86** [comment]
@tschaub Regarding the other issue with the canvas renderer, I've just noticed that it has been fixed in the latest v3.14.0 Version. The problem was that a non `type:'base'` Layer in a layer group was getting messed up when you started to pan around or zoom in/out. The tiles had been randomly drawn at places where they did not belong. If you're still interested I can provide another fiddle/codepen.

**Comment by tschaub** [comment]
@chrisg86 thanks for the additional detail.  If you can provide an example demonstrating an issue with the Canvas renderer, that would be great.

**Comment by bartvde** [comment]
@tschaub but if it is no issue with 3.14 anymore (fixed with 3.14), do we still need to details?

**Comment by tschaub** [comment]
Thanks for pointing that out @bartvde.  No need for more detail if it has been resolved.
