### ISSUE TITLE
Creating custom builds : KML is not a source

### ISSUE THREAD

**Issue by xlhomme** [openlayers/ol3#4910]
Hi 
In the heatmaps-earthquakes sample of the Creating custom builds page, 
the export list is wrong: 
you should replace ol.source.kml by ol.format.KML ,... 

something like this
  "exports": [
  "ol.layer.Heatmap",
    "ol.source.Vector",
    "ol.format.KML",
    "ol.layer.Heatmap#getSource",
    "ol.source.Vector#on",
    "ol.source.VectorEvent#feature",
    "ol.Feature#get",
    "ol.Feature#set",
    "ol.layer.Tile",
    "ol.source.Stamen",
    "ol.Map",
    "ol.View",
    "ol.layer.Heatmap#setRadius",
    "ol.layer.Heatmap#setBlur"
  ],

**Comment by fredj** [comment]
@xlhomme thanks for the report, can you create a pull request ?

**Comment by xlhomme** [comment]
@fredj : can you tell me where I should  find the custom-builds.html file  ?

**Comment by bartvde** [comment]
https://github.com/openlayers/ol3/blob/master/doc/tutorials/custom-builds.md

**Comment by xlhomme** [comment]
thanks @bartvde I finally found the way to create the pull request.

**Comment by fredj** [comment]
Fixed with #4923
