### ISSUE TITLE
There is no way to programatically select a feature in ol.interaction.Select

### ISSUE THREAD

**Issue by ccapndave** [openlayers/ol3#4912]
I really want to be able to write some code to select a feature:

```
const selector = new ol.interaction.Select({ ... })
```

and later:

```
// select
selector.setFeature(feature);

// or deselect
selector.setFeature(null);
```

Am I missing something, or is this really not possible?

**Comment by marcjansen** [comment]
You should be able to modify the underlying collection of features.

**Comment by ccapndave** [comment]
But how?  As far as I can tell `selector` doesn't have any methods to get at what is currently selected.

**Comment by tsauerwein** [comment]
See: http://stackoverflow.com/questions/26422598/openlayers-3-select-a-feature-programmatically

**Comment by ccapndave** [comment]
Hooray!  Thanks a lot :)
