### ISSUE TITLE
Layer on change event issue when migrating from 3.10.1 to 3.14.0

### ISSUE THREAD

**Issue by jvanulde** [openlayers/ol3#4919]
I was using the following code to access features on a layer once they are loaded. It no longer works, and I get the following error: `Uncaught TypeError: Cannot read property 'getSource' of undefined`. Here is the code that worked under 3.10.1:

    // Wait until all features are loaded, then process features
    myLayer.once( "change", function ( evt ) {
        this.getSource().forEachFeature( function ( feature ) {
            // set feature id's etc...
        })
    })

`this` is undefined. Is there another/better way to do this now?

**Comment by tsauerwein** [comment]
Make sure that you bind `this`:

    myLayer.once( "change", function ( evt ) {...}, myLayer);

See also: http://openlayers.org/en/master/apidoc/ol.layer.Base.html#once

**Comment by jvanulde** [comment]
@tsauerwein that worked except now I get the following error `Uncaught RangeError: Maximum call stack size exceeded`. I am setting two properties on each layer as follows:

    // Wait until all features are loaded, then process features
    myLayer.once( "change", function ( evt ) {
        this.getSource().forEachFeature( function ( feature ) {
            feature.setId( generateGuid() );
            feature.layerId = myLayer.id;
        })
    }, myLayer );

Maybe this isn't the most efficient way to do this?

**Comment by ahocevar** [comment]
You should be listening on the source, not the layer:
```js
var source = myLayer.getSource();
var key = source.on('change', function(evt) {
  if (source.getState() == 'loaded') {
    source.unByKey(key);
    feature.setId(generateGuid());
    feature.layerId = myLayer.id;
  }
});
```

**Comment by tschaub** [comment]
Since `change` events are fired synchronously, there is a chance to get unwanted recursion if you modify an object in its change listener.  Not sure if this is happening here, but the call stack size issue above suggests it.  Also not sure if the synchronous `change` event is new with 3.14.

**Comment by ahocevar** [comment]
This is a regression. See #4921 for a fix.

**Comment by jvanulde** [comment]
@ahocevar I tested the fix and can confirm that it works. However, I needed to listen for the `ready` state instead of  `loaded`. 

Here is what worked for me:

    	var source = myLayer.getSource();

        var key = source.on( "change", function( evt ) {
	        if ( source.getState() == "ready" ) {
                source.unByKey( key );
                this.forEachFeature( function ( feature ) { ... } );
            }
        }

BTW - what does `source.unByKey( key );` do?

**Comment by ahocevar** [comment]
> BTW - what does `source.unByKey( key )`; do?

It unregisters the listener that was registered with `var key = source.on(...)`.
