### ISSUE TITLE
CalculateExtent() doesn't work after a setCenter()

### ISSUE THREAD

**Issue by JustDoItSascha** [openlayers/ol3#4933]
I took notice of a fuzzy bug: After I do a setCenter() on the View, I cannot calculate the extent anymore, not until I zoom the map or change the extent a little bit.

`map.getView().calculateExtent(map.getSize())` returns just an Array with [NaN, NaN, NaN, NaN].

**Comment by fredj** [comment]
Cannot reproduce (http://openlayers.org/en/v3.14.0/examples/simple.html):
```javascript
map.getView().setCenter([10000000, -1000000])
map.getView().calculateExtent(map.getSize())
```
Works as expected.

**Comment by JustDoItSascha** [comment]
Found the mistake:

    map.getView().setCenter(["10000000", "-1000000"])
    map.getView().calculateExtent(map.getSize())

setCenter accepts strings as values, but then calculateExtent does not work. So either setCenter should be changed to throw an error or at least a hint or calculateExtent should also parse the strings itself.

**Comment by bartvde** [comment]
setCenter does not accept strings see: http://openlayers.org/en/v3.14.0/apidoc/ol.View.html#setCenter http://openlayers.org/en/v3.14.0/apidoc/ol.html#.Coordinate

**Comment by JustDoItSascha** [comment]
Yeah, but what should I tell you? `map.getView().setCenter(["10000000", "-1000000"])` just works.

**Comment by bartvde** [comment]
We made a decision a long time ago in the project not to handle user input error IIRC, I'm not sure if people are open to revisiting this?

**Comment by ahocevar** [comment]
Since we'll probably soon have typescript support, and we already have type checking for Closure Compiler, I don't think we need to add the overhead of runtime type checking.

**Comment by JustDoItSascha** [comment]
Its very confusing, because maybe you implement a setCenter and after months you add a new feature with e.g. calculateExtent and it does not work and you have no idea why...

**Comment by ahocevar** [comment]
Respecting accepted types in your application code is always a good idea, and OpenLayers API docs always show you the allowed types.

**Comment by JustDoItSascha** [comment]
Yeah but it is also a good idea to change the API docs so they show correct information. Imho strings ARE accepted, regardless what the docs say. So either the docs should be changed, the setCenter should not accept strings (or at least throw a hint in the console) or functions like calculateExtent should also accept strings... Everything else is very shortsighted, because stuff like that can be a real struggle for developers!

**Comment by JustDoItSascha** [comment]
@bartvde "I'm not sure if people are open to revisiting this?" -> Obviously they are not.
