### ISSUE TITLE
Tile layer opacity issue in v3.14

### ISSUE THREAD

**Issue by norric** [openlayers/ol3#4934]
In v3.14, the layer opacity behavior has changed. It appears that the opacity is no longer directly applied when the tile is loaded, causing flicker when dragging the map.

Refer to the following fiddles and drag the map around to load new tiles:
v3.13.1: http://jsfiddle.net/norric/g52zuf2x/
v3.14.0: http://jsfiddle.net/norric/h74hnrhu/

Related to https://github.com/openlayers/ol3/pull/4597 ?

**Comment by ahocevar** [comment]
This is indeed related to #4597. Because `ol.source.OSM` has the `opaque` flag set to `true`, no clip regions for visible lower resolution tiles will be calculate, causing lower resolution tiles and actual tiles to overlap until all are loaded.

For now, you can configure your `ol.source.OSM` with `opaque: false` to make this issue go away. But since this is a regression, I think we'll also check for layer `opacity` in addition to source `opaque` before we skip calculation of clip regions.

**Comment by norric** [comment]
Thanks for the quick response.

Using `opaque: false` seems to solve one part of it. However, it made me notice something else: Sometimes when you zoom, flickering lines appear at the tile seams. If you quickly zoom in or out multiple steps you can see it. 

The lines appear also without `opaque: false` but are less noticeable when the tiles themselves flicker as well. Looks fine on 3.13.

**Comment by ahocevar** [comment]
I noticed these lines to - it's because the clip regions do not align with the tiles in a pixel exact manner. I'll be fixing both.

**Comment by ahocevar** [comment]
#4939 fixes the regression.

**Comment by norric** [comment]
Unfortunately, the lines still appear when zooming in 3.14.1

See http://jsfiddle.net/norric/mopu8d7x/

**Comment by ahocevar** [comment]
This is as good as it gets with the new renderer code. The remaining lines are not related to the opacity.

**Comment by ahocevar** [comment]
I ticketed the remaining issue as #4943. Maybe I have some time before v3.15 to investigate possible fixes.

**Comment by norric** [comment]
Thanks!

**Comment by ahocevar** [comment]
Actually the remaining lines are indeed still an opacity issue, and not the ones I described in #4943. I created #4960 with a simplification and fix.

**Comment by ahocevar** [comment]
@norric I updated your fiddle to use the fix I propsed in #4960: http://jsfiddle.net/mopu8d7x/2/. Can you please test if that satisfies?

**Comment by norric** [comment]
I couldn't get that fiddle to load the ol.js, but I got it working in this one: http://jsfiddle.net/mopu8d7x/6/

It looks great now! No signs of flickering tiles or lines. Thanks Andreas!
