### ISSUE TITLE
Export to PNG, issue with image size

### ISSUE THREAD

**Issue by rfinquiron** [openlayers/ol3#4935]
I am trying to export openlayers 3 map to PNG.

This example is working well http://openlayers.org/en/master/examples/export-map.html , but the export image width and height are double than the original map canvas.

If the map canvas is 1330x440, I get the exported png image as 2660x880 pixels.

Any idea how to get the export size same as canvas size ?

**Comment by ahocevar** [comment]
This is because your device pixel ratio is 2. You can either configure your map with `{pixelRatio: 1}`, or scale the resulting image by `1 / ol.has.DEVICE_PIXEL_RATIO`.
