### ISSUE TITLE
XmlHttpRequest inside of TileJSON constructor provides no error mechanism

### ISSUE THREAD

**Issue by richard3d** [openlayers/ol3#4948]
When the TileJSON constructor initializes the xhr, callbacks for success and fail are defined. However there is no callback for onerror() defined. Currently, if an application hits a valid (but non-OpenLayer) URL and an error occurs there will be no response (handleTileJSONError is never called) and the application has no way of notifying the user.

**Comment by tschaub** [comment]
The way things are currently, you could do this to notify the user on error:

```js
var source = new ol.source.TileJSON({url: '/bogus-url'});
source.on('change', function() {
  if (source.getState() === 'error') {
    alert('Something went wrong');
  }
});
```

Things that are inconvenient about this:

 * this only works for a narrow class of error (timeouts, cors issues, and more go unnoticed; JSON parsing issues leave the source forever "loading"; etc.)
 * you have to register for the very generic "change" event, who knows when else this gets fired
 * you can't get any detail about what went wrong

At a minimum, more error cases could be handled.  With the generic "change" event, we don't really have a place to communicate information about the error.  Curious what others think about making this more user friendly.

**Comment by ahocevar** [comment]
Agreed. I think there should be at least a 'change:state' event on all sources, and that could have additional properties to describe state details.

**Comment by ahocevar** [comment]
Event name could also be 'changestate' or something else, to not conflict with Object event names.

**Comment by richard3d** [comment]
As long as all http error cases are handled via the event I think that would be fine. Again, the first solution mentioned ( using '.on()' ) does not solve the problem I am having (which is essentially a CORS issue). While knowing the error details (404 etc.) is helpful, it is more important initially for an application to know that the source loading failed period. I hope this makes sense and illustrates the real heart of the issue.
