### ISSUE TITLE
ImageStatic and rotation?

### ISSUE THREAD

**Issue by ch08532** [openlayers/ol3#4949]
First off, forgive me if this is not the appropriate place to ask questions about the API.

I was wondering if there is a way to rotate a ol.source.ImageStatic?  I am trying to support the KML GroundOverlay feature and part of the standard allows for rotation of the imageExtent.  I do not see this ability supported in ImageStatic.  Anybody know if this is possible?  Thank you.

**Comment by ahocevar** [comment]
This is not directly supported, but it is possible: You can define a custom `imageLoadFunction` with the `ol.source.ImageStaticConstructor`, in which you can load the image, create a canvas, rotate the canvas, and use the canvas context's `drawImage()` method to place the image on the rotated canvas.

**Comment by mike-000** [comment]
Another method is to use reprojection.  Ground overlays are intended to fit an equidistant cylindrical projection.  For the most accurate results the correct projection should be calculated so the image can be reprojected to the view projection.  If the image is rotated the projection can be customised to handle rotation.  Demo of that https://codepen.io/anon/pen/LomLYe derived from https://renenyffenegger.ch/notes/tools/Google-Earth/kml/index

**Comment by garpenholm** [comment]
I also would appreciate a **rotate:** attribute in the ImageStatic module, like;

Just a suggestion:
```
var staticSource = new ol.source.ImageStatic({
                        url: 'images/myImage.png',
                        rotate: 16.35,
                        attributions: 'Copyright Me',
                        projection: myView.getProjection(),
                        imageExtent: myImageExtent
                });
```

**Comment by mike-000** [comment]
> I also would appreciate a **rotate:** attribute in the ImageStatic module, like;
> 
> Just a suggestion:
> 
> ```
> var staticSource = new ol.source.ImageStatic({
>                         url: 'images/myImage.png',
>                         rotate: 16.35,
>                         attributions: 'Copyright Me',
>                         projection: myView.getProjection(),
>                         imageExtent: myImageExtent
>                 });
> ```

Copy the `rotateProjection` function from https://codesandbox.io/s/reprojection-image-z0uit

then use 

`                         projection: rotateProjection(myView.getProjection(), 16.35 * Math.PI/180, myImageExtent),
`

**Comment by garpenholm** [comment]
> > I also would appreciate a **rotate:** attribute in the ImageStatic module, like;
> > Just a suggestion:
> > ```
> > var staticSource = new ol.source.ImageStatic({
> >                         url: 'images/myImage.png',
> >                         rotate: 16.35,
> >                         attributions: 'Copyright Me',
> >                         projection: myView.getProjection(),
> >                         imageExtent: myImageExtent
> >                 });
> > ```
> 
> Copy the `rotateProjection` function from https://codesandbox.io/s/reprojection-image-z0uit
> 
> then use
> 
> ` projection: rotateProjection(myView.getProjection(), 16.35 * Math.PI/180, myImageExtent),`

Thank you for your answer!
I also find the GeoImg useful, where you can rotate 'on the fly' like;
myGeoImgObject.getSource().setRotation($("#rotation").val()*Math.PI/180);
where $("#rotation").val is a number value from e.g. an input element.

**Comment by carlosjpr-collab** [comment]
@mike-000  @ahocevar @garpenholm 
I have an image with extent in 'EPSG:4326' 
like this [east: 1.387570379, north: 43.564392055451, south: 43.564157998954, west: 1.386958959643]

What are the modifications that i can do so the this example https://codesandbox.io/s/reprojection-image-z0uit will work with my case ?
