### ISSUE TITLE
Adding marker labels create an error

### ISSUE THREAD

**Issue by Sehsyha** [openlayers/ol3#4952]
I want to add a message to a marker but it creates the error "Node.appendChild does not implement interface Node." at line 74836 of the library.

It seems that the element we want to append is not a DOM element.

**Comment by ahocevar** [comment]
You will have to use `ol-debug.js` instead of `ol.js` and report a full stack trace here. Also, share some context, i.e. a code snippet with the "marker" and how you were trying to add a "message" to it.

**Comment by Sehsyha** [comment]
I'm using angular-openlayers-directive but I don't think that the problem come from this.

I just tried with the most simple example with a message : 

`  <openlayers class="col s12" height="400px" zoom="5" ol-center="center">
    <ol-marker lat="39.92" lon="116.38" message="Here is Beijing. Dreamful place."></ol-marker>
  </openlayers>`

and this gives this stack trace : 

`Error: Argument 1 of Node.appendChild does not implement interface Node.
ol.Overlay.prototype.handleElementChanged@http://localhost:3000/app/js/ol.js:74836:5
ol.events.bindListener_/boundListener@http://localhost:3000/app/js/ol.js:5793:12
ol.events.EventTarget.prototype.dispatchEvent@http://localhost:3000/app/js/ol.js:6500:11
ol.Object.prototype.notify@http://localhost:3000/app/js/ol.js:6915:1
ol.Object.prototype.set@http://localhost:3000/app/js/ol.js:6935:7
ol.Overlay.prototype.setElement@http://localhost:3000/app/js/ol.js:74908:3
ol.Overlay@http://localhost:3000/app/js/ol.js:74740:5
.createOverlay@http://localhost:3000/app/js/directives/openLayer.js:1890:22
.link/<@http://localhost:3000/app/js/directives/openLayer.js:758:33
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:3000/app/js/angular/angular.min.js:11722:31
qFactory/ref/<.then/<@http://localhost:3000/app/js/angular/angular.min.js:11808:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/app/js/angular/angular.min.js:12851:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/app/js/angular/angular.min.js:12663:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/app/js/angular/angular.min.js:12955:13
done@http://localhost:3000/app/js/angular/angular.min.js:8466:34
completeRequest@http://localhost:3000/app/js/angular/angular.min.js:8680:7
createHttpBackend/</xhr.onreadystatechange@http://localhost:3000/app/js/angular/angular.min.js:8619:1`


I'm using ol-debug.js and not ol.js
The center works perfectly, and the class of the openlayers is just for css and width.

**Comment by ahocevar** [comment]
You should report this issues where it belongs: [openlayers-angular-directive](https://github.com/tombatossals/angular-openlayers-directive).
