### ISSUE TITLE
Extends annotation but no goog.inherits

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4966]
* `ol.webgl.Context` `@extends {ol.events.EventTarget}` without `goog.inherits`
 * `ol.render.canvas.Immediate` `@extends {ol.render.VectorContext}` without `goog.inherits`

**Comment by tschaub** [comment]
The issue with #4966 is addressed in #4950.  I could take care of `ol.render.canvas.Immediate` there as well.

**Comment by tschaub** [comment]
I think doing this in #4967 is a better idea since `ol.Disposable` is not in the prototype chain.
