### ISSUE TITLE
DOM Renderer uses canvas element

### ISSUE THREAD

**Issue by mukil** [openlayers/ol3#4972]
When opening [Simple Map Example with the `?renderer=dom` Option](http://openlayers.org/en/master/examples/simple.html?renderer=dom) and the [Shared Views Example](http://openlayers.org/en/v3.14.2/examples/side-by-side.html) with two different browsers but also in the latter, the "DOM" rendered map always shows its Tile Layer within a `canvas` element.  AFAIK this behaviour is not as intended when showing an example of a DOM Renderer but please correct me if i am wrong. I would expect that all the tiles are arranged in div-container elements and not in a canvas.

I tried both with Firefox 44.0.2 (on Ubuntu 14.04 having WebGL support "disabled or unavailable")
and with a Chromium 48.0.2564.116 (Ubuntu 14.04 64-bit) with WebGL support).

Furthermore, starting with a very basic map setup, one taken from the [Quickstart](http://openlayers.org/en/v3.14.2/doc/quickstart.html) page i could not make any use of the 'renderer' option through specifying the 'dom' renderer according to the [API Docs](http://openlayers.org/en/v3.0.0/apidoc/ol.html#RendererType).

I setup a very simple [jsfiddle](http://jsfiddle.net/xug1nsbb/7/) which is basically just concerned with this rendererType option. If i open it with the two mentioned browsers i get the map in a `canvas` element.

Is this an issue in OL 3.14.2? Thankful for your support and any clarification on this.

Cheers!

**Comment by mukil** [comment]
That jsfiddle (besides using OL in v3.8.2) is based upon this stackoverflow question which seems to experience the very same issue:
http://stackoverflow.com/questions/32400495/openlayers-cant-change-renderer-to-dom

Nonetheless the issue does not change if i test this option locally with the release of today 3.14.2.

Thanks in advance for your support.

**Comment by tsauerwein** [comment]
Not all examples allow to add an URL parameter `?renderer=...` and you'd have to run the example in 'un-compiled mode', for example:
http://openlayers.org/en/master/examples/icon.html?renderer=dom&mode=raw

The examples use a special function which reads the renderer from the URL (for example like [here](https://github.com/openlayers/ol3/blob/c9e2b384e7f3214847c38e6967e1ba2540eeae27/examples/icon.js#L48)), this is not done automatically. Otherwise you have to set the renderer on the map, like you did in your JSFiddle.

The dom renderer directly uses image elements for tile layers. But for vector data it still uses canvas. That's why you are seeing the canvas element. But you will also see your images:

![ol-dom](https://cloud.githubusercontent.com/assets/266474/13534344/f937b6c4-e234-11e5-8e45-667a55d3a994.png)

**Comment by mukil** [comment]
Oh, yes, sorry! I did not see that. Indeed, the tiles are `img` in the `div`. I must have been blinded by the sheer existence of the `canvas` element because i did not inspect the container element above it.

Additionally, at my first glance, i could not think of that someone would want to use the `canvas` element to render vectors but after spending a second thought, two advantages of this approach immediately came to mind:
1. one needs just one canvas implementation to support different type of layout engines and browsers (unlike when using e.g. VML for IE and SVG for FFOX) and
2. in some special cases (like for example placing thousands or millions of items on a map) the performance for the end-user across devices may be much better due to the hardware support canvas brings into the browser

However, in my use-case performance is not a primary concern but machine readability (of geomap elements, like for example Layers and Features) is. I am currently focussing on how to improve the expressiveness of the HTML ol3 generates when "users" do simple "map mashups". After what i know now this seems no easy feat considering the canvas based vector layer implementation. As it turns the map overlays effectively into an image (black box) and render the contents inaccessible for tools which run outside of ol3JavaScript scope. The only technical option for me when wanting to build on ol3 seems to be writing an extension or plugin which does somehow duplicate the needed Elements into (a possible "hidden") part of the HTML Document and thus make the contents of the map accessible for third party tools.

Anyway, so much for now. Thank you very much for your support and clarification on this, you've clearly helped me to understand a bit more on how OL3 currently goes about rendering the map into HTML. If anyone has pointers where similar things were brought up and discussed for ol3, please let me know so i can connect to the existing work.

Thank you very much & Cheers!

**Comment by tsauerwein** [comment]
> I am currently focussing on how to improve the expressiveness of the HTML ol3 generates when "users" do simple "map mashups".

Maybe the project [angular-openlayers-directive](https://github.com/tombatossals/angular-openlayers-directive) is what you are looking for. It lets you write something like this:

      <openlayers ol-center="center" height="400px" width="100%">
          <ol-marker name="London" lat="51.505" lon="-0.09"></ol-marker>
      </openlayers>

http://tombatossals.github.io/angular-openlayers-directive/examples/060-marker-example.html
