### ISSUE TITLE
How to trigger a pinch zoom (and only that event?)

### ISSUE THREAD

**Issue by costales** [openlayers/ol3#4979]
Hi,
I was looking a lot for an example, but the unique solution I found is this:
```
		map.getView().on('propertychange', function(e) {
			if (e.key == 'resolution') {
				console.log('Event triggered');
			}
		});
```

But this is triggering the pan event too.

Please, how could I trigger just only the pinch zoom event?

Thanks a lot!

**Comment by ahocevar** [comment]
There is no event that gets triggered on pinch zoom specifically. What are you trying to achieve? I may be missing something, but I don't see why someone would want to know specifically when a user pinch-zoomed.

**Comment by costales** [comment]
Hi @ahocevar  :)

I'm developing [uNav](https://code.launchpad.net/unav) GPS Navigation, and I would need to control the pinch zoom and the drag events in a different way (for unfocus the view on car).

A hug!

**Comment by ahocevar** [comment]
Your code above should work, as long as you do not programmatically change the resolution, e.g. by using `ol.View#setZoom()' , `ol.View#setResolution()` or `ol.View#fit()`. Just drag-panning the map (with one finger on touch devices) will not change the resolution, and the `'change:resolution'` event (which you could use instead of `propertychange`) won't fire.

**Comment by costales** [comment]
In my tests pinch the zoom is triggering the drag too :)
A hug!

**Comment by ahocevar** [comment]
Your snippet tests for resolution change. The event will be triggered only when zooming, but not when panning using one finger.

**Comment by costales** [comment]
@ahocevar Yes :) That is my issue. I would need the zoom event not trigger the pan event :)
My solution by now will be disable the pinch events :P 
A hug and thanks for your support!

**Comment by ahocevar** [comment]
I edited my above comment to show you how you might be able to combine listening for two different events to determine what the user did.
