### ISSUE TITLE
Problem in showing KML files

### ISSUE THREAD

**Issue by Beniy** [openlayers/ol3#4985]
Dear Openlayers Experts,
I hope you are doing well.
At 1st thanks for your support.
There are some issues with different KML files which most of my KML files can not be oppened in Openlayers but I can open them through the other tools.

I will appreciate if you check attached example and let me know what is the issue.
Thanks a lot in advance.
BR,

**Comment by marcjansen** [comment]
This looks as if it may be a usage question. Can you please ask this over at stackoverflow (tagged with openlayers-3)? It'd be best to upload your problematic kml somewhere. Please also add the code you use to load and display the KML.

**Comment by Beniy** [comment]
Thanks for your answer,
Where should I ask this question?

**Comment by Beniy** [comment]
Should I go to "Open a ticket" and create a new one?

https://github.com/openlayers/ol3/issues/new 
??

**Comment by Beniy** [comment]
Please take a look in attached KML.
It can not be openned in your example page
http://openlayers.org/en/v3.14.2/examples/drag-and-drop.html

**Comment by Beniy** [comment]
This is the example of kml which cannot be openned by your example page
http://www.4shared.com/zip/BHF-ZxFHba/MS1.html?

**Comment by marcjansen** [comment]
What I originally meant was to ask the question here: http://stackoverflow.com/questions/tagged/openlayers-3

**Comment by marcjansen** [comment]
PS the download location looks really fishy...
