### ISSUE TITLE
 ol.events.EventTarget#dispatchEvent fails if a handler causes listeners to be removed

### ISSUE THREAD

**Issue by schmidtk** [openlayers/ol3#4986]
If an event handler causes other handlers for the same event type to be removed, `
ol.events.EventTarget#dispatchEvent` may call handlers multiple times. If multiple handlers are removed, dispatchEvent may throw an error.

This is dependent on the order of listeners, but see my fiddle here with a very basic worst-case (error) example:
http://jsfiddle.net/9cgmw6r8/2/

This is a regression from the Closure event stack, which copies the listener array and checks if each listener has been removed before calling it (see [goog.events.EventTarget#fireListeners](https://github.com/google/closure-library/blob/master/closure/goog/events/eventtarget.js#L261)).

**Comment by ahocevar** [comment]
Thanks for reporting this regression @schmidtk.

It would be great if we could fix this without copying the listener array, because that had put a lot of pressure on the garbage collector with the Closure event stack.

**Comment by tschaub** [comment]
It seems like one option would be to do a "soft removal" of the listener when unregistering - marking the listener as removed but not modifying the array.  Then the listener array could be modified in the next tick - removing marked listeners.  When dispatching, only unmarked listeners would get called.

**Comment by ahocevar** [comment]
Thanks @tschaub, I did something along these lines in #4991.

@schmidtk, can you please test if that fixes your issue, and report back here?

**Comment by schmidtk** [comment]
Thanks for the fix @ahocevar. I'll have to wait until I can pull your fix to our dev network to test this, but I reviewed the code and it looks like it will resolve our issue. Thanks for the GC-friendly solution as well. Closure's event stack is a hungry, hungry beast. :)
