### ISSUE TITLE
ol.source.TileJSON contructor does not return full JSON payload

### ISSUE THREAD

**Issue by richard3d** [openlayers/ol3#4987]
When a http response comes back, handleTileJSONResponse strips certain attributes from the full JSON payload to put into the returned source object. For instance if an application wants to know the display-friendly name of a map (vice the id), it has no way of knowing since the source object/handleTileJSONResponse never sets a 'this.name'. The TileJSON constructor should either redefine the source object to support the full payload info, or have the full JSON payload be returned as part of an event parameter as discussed in issue #4948.

**Comment by fredj** [comment]
The source can store the json file and expose a function to return it
