### ISSUE TITLE
ol.proj.fromLonLat needs that latitude is a number (string not working)

### ISSUE THREAD

**Issue by rollingnet** [openlayers/ol3#4989]
I have just discovered that ol.proj.fromLonLat function requires that the 2n component of array (i.e. latitude) is a number. If it is a string, it returns strange results.
The 1st argument (longitude) is correct even if it is a string.

**Comment by ahocevar** [comment]
Yes, and it's documented - the first argument of [`ol.proj.fromLonLat`](http://openlayers.org/en/v3.14.2/apidoc/ol.proj.html#.fromLonLat) is an [`ol.Coordinate`](http://openlayers.org/en/v3.14.2/apidoc/ol.html#.Coordinate), which is an `Array.<number>`.
