### ISSUE TITLE
Alpha value in ol.Color

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#4993]
When `ol.Color` is used as Array, `alpha` value could be `1` by default instead of [`undefined`](https://github.com/openlayers/ol3/blob/master/src/ol/color/color.js#L296), so we can use like `[51, 51, 51]` instead of `[51, 51, 51, 1]`.

**Comment by tschaub** [comment]
I agree this would be nice.

**Comment by fredj** [comment]
Fixes with #4994
