### ISSUE TITLE
Can not access feature properties from ol.format.MVT (mapbox vector tile)

### ISSUE THREAD

**Issue by bwyss** [openlayers/ol3#4996]
I am not able to access the feature properties of a mapbox vector tile.

My layer:

    var observationLayer = new ol.layer.VectorTile({
      source: new ol.source.VectorTile({
        format: new ol.format.MVT({layerName: ['id']}),
        tileGrid: ol.tilegrid.createXYZ({maxZoom: 22}),
        tilePixelRatio: 16,
        url: '/services/postgis/test_observations/geometry/vector-tiles/{z}/{x}/{y}.pbf'
      }),
      style: observationStyle
    }); 

Trying to access feature properties:

      map.on(ol.MapBrowserEvent.EventType.SINGLECLICK, function (e) {
        console.log('e:');
        console.log(e);
        map.forEachFeatureAtPixel(e.pixel, function (feature, layer) {
          console.log('feature.getProperties():');
          console.log(feature.getProperties());
          // This only returns: id: "test_observations_geometry"
          // instead of all of the layers attributes. If I change the layer to a GeoJSON source,
          // then it works correctly. 
        });
      });

**Comment by ahocevar** [comment]
You have a configuration problem. The value of the `layerName` config option is supposed to be a string, not an array.

**Comment by bwyss** [comment]
I have tried using both:
`format: new ol.format.MVT({layerName: 'id'})`
`format: new ol.format.MVT()`

however the out come is always the same:
feature.getProperties() only returns "test_observations_geometry"

**Comment by ahocevar** [comment]
Are you sure that other properties are encoded in your tiles? You could test using [vector-tile-js](https://github.com/mapbox/vector-tile-js) directly. OpenLayers simply sets the [VectorFeature](https://github.com/mapbox/vector-tile-js#vectortilefeature)'s `properties` as feature properties.

**Comment by bwyss** [comment]
Thanks, you are correct, this is an issue with the vector tiles encoding and not with Openlayes.
