### ISSUE TITLE
updated 3.12.1 => 3.14.2 and got blurry view

### ISSUE THREAD

**Issue by nd0ut** [openlayers/ol3#5004]
Before:
![0.12.1](http://i.imgur.com/p2drpYp.jpg)

After:
![0.14.2](http://i.imgur.com/S10FBTx.jpg)

As you can see both tile layer and vector labels layer are blurry. What can cause such problem?
Now I'm trying to find out which version is causing the problem.

**Comment by nd0ut** [comment]
It starts from `0.14`. And it seems that blur rate depends on pixel position. For example, label `Arctic Ocean` is more blurry if I drag it to the top of the screen, and there is almost no blur on the center.

**Comment by nd0ut** [comment]
Also I'm using custom projection with proj4 (EPSG:3413)

**Comment by ahocevar** [comment]
Can you create a fiddle with the map/layers you took the screenshot from? The only possible cause that comes to mind is that your layer resolutions are different from the view resolution, but that should also have caused blurry images in oder versions. If your labels are from an `ol.layer.Vector`, I don't see any reason why they get blurred.

**Comment by nd0ut** [comment]
I found the problem. There was an initial rotation `!= 0` passed to the view. So if you start to rotate the view then it becomes blurry. It's easily to see it on the labels. Here is the jsfiddle: http://jsfiddle.net/nd0ut/twLh50pc/12/

**Comment by ahocevar** [comment]
That makes sense. In 3.14.x, we changed the way the canvas renderer works, for performance reasons. Previously, the map canvas was never rotated, and layer renderers had to take care of rotating their content. Now, the map canvas is rotated after all layer rendering is done on a straight-up canvas.

The issue you are seeing depends on the device and the pixel ratio, e.g. it cannot be observed on HiDPI devices. To work around it, you could configure your map with
```js
pixelRatio: Math.min(2, ol.has.DEVICE_PIXEL_RATIO),
```
This will use a higher canvas resolution and render more pixels - so the caveat is that rendering performance will suffer, so you won't get the performance gains we introduced with v3.14.x.

**Comment by nd0ut** [comment]
@ahocevar thank you. Increasing of the `pixelRatio` turns the map dragging into slideshow :smiley:  We have some problems with the performance cause there is many layers so I think that the presence of that blur does not matter. But I noticed that the performance when the canvas rotated is lower than the straight-up canvas. Is it ok?

And here is the another question about performance: does it make sense to optimize the tiles? I mean, will the performance increased if I pass the tiles through a pngquant, reduce their size and the amount of colors.

**Comment by ahocevar** [comment]
> But I noticed that the performance when the canvas rotated is lower than the straight-up canvas. Is it ok?

That is expected. When the view is rotated, the canvas will be rotated and drawn to the final canvas. Without rotation, everything will be rendered to the final canvas directly.

> And here is the another question about performance: does it make sense to optimize the tiles? I mean, will the performance increased if I pass the tiles through a pngquant, reduce their size and the amount of colors.

That should not matter. One thing you can try is use the DOM renderer instead of the Canvas renderer, which is known to perform better when you have many tile layers. Configure your map with
```js
new ol.Map({
  renderer: 'dom'
});
```
