### ISSUE TITLE
Custom build

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#5005]
I've a got a lot errors on a custom building like:

```
ERR! compile /home/www/ol3/node_modules/closure-util/.deps/library/c00d1243c49bb8dad16f671f09a3facded9f3cd9/closure/goog/array/array.js:55: ERROR - Name Array in JSDoc is implicitly nullable.
ERR! compile Please add a ! to make it non-nullable, or a ? to make it explicitly nullable.
ERR! compile  * @typedef {Array|NodeList|Arguments|{length: number}}
ERR! compile              ^
```

**Comment by jonataswalker** [comment]
If I `rm -fr node_modules && npm install` I get a `404` error from `slimerjs-edge`

```
Downloading http://download.slimerjs.org/nightlies/0.10.0pre/slimerjs-0.10.0pre-linux-x86_64.tar.bz2
Saving to /tmp/slimerjs/slimerjs-0.10.0pre-linux-x86_64.tar.bz2
Receiving...
Error requesting archive.
Status: 404
```

**Comment by ahocevar** [comment]
This problem was brought up in the ol3-dev list [today](https://groups.google.com/d/msgid/ol3-dev/55d418cc-b007-493f-84b1-2538daa67086%40googlegroups.com?utm_medium=email&utm_source=footer) as well. The issue was reported: laurentj/slimerjs#442.

**Comment by ahocevar** [comment]
ping @tsauerwein - I think the slimerjs-edge release we use was created upon your request. Any ideas?

**Comment by ahocevar** [comment]
@tsauerwein: Actually it seems we can switch to the maintained package. Let's hope that Travis agrees - see #5006.

**Comment by jonataswalker** [comment]
```
ERR! compile Please add a ! to make it non-nullable, or a ? to make it explicitly nullable.
ERR! compile  * @typedef {Array|NodeList|Arguments|{length: number}}
```

@ahocevar Would these errors related to slimerjs?

**Comment by ahocevar** [comment]
@jonataswalker No, more likely to an outdated closure-util package.

**Comment by gberaudo** [comment]
@jonataswalker, have you updated closure-util but not your build config?
Maybe you are missing an `"analyzerChecks"` item in the `jscomp_off` section.

**Comment by jonataswalker** [comment]
> Maybe you are missing an "analyzerChecks" item in the jscomp_off section.

Bingo!

Another error appears:

`ERROR - unknown @define variable goog.json.USE_NATIVE_JSON`

And removing this line from `"define"` section all goes well. Maybe we should have an up-to-date guide to cover these changes.

**Comment by probins** [comment]
if you mean the custom-build tutorial, `goog.json` was removed from that with #4937. However, other changes to `jscomp_off` were not; looks like greenkeeper removed these from `config` files, but not the tutorial.

**Comment by ahocevar** [comment]
@gberaudo, any chance you could create a pull request to update http://openlayers.org/en/v3.14.2/doc/tutorials/custom-builds.html? I think http://github.com/openlayers/workshop also needs to be updated somewhere. Would be much appreciated.

**Comment by marcjansen** [comment]
See openlayers/workshop#46

**Comment by gberaudo** [comment]
@ahocevar, there should be no need to change anything in the custom-builds.html file since it is not using
```
"jscomp_error": [
  "*"
],
```.
Otherwise there could be some simplifications in the closure.md doc. I will prepare a PR.
