### ISSUE TITLE
begining from ol 3.14, nothing is shown in javaFx webview component

### ISSUE THREAD

**Issue by rsobies** [openlayers/ol3#5008]
below is html code to display in javafx webview component
`<!doctype html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="ol.css" type="text/css">
        <style>
            .map {
                height: 100%;
                width: 100%;
            }
        </style>
        <script src="ol_14.0.js" type="text/javascript"></script>
        <title>OpenLayers 3 example</title>

    </head>
    <body>

        <div id="map" class="map" ></div>
        <script type="text/javascript">
            var layerMap = new ol.layer.Tile({
                source: new ol.source.OSM()
            });

            var map = new ol.Map({
                
                target: 'map',
                layers: [
                    layerMap

                            // shplay
                ],
               
                view: new ol.View({
                   
                    center: ol.proj.fromLonLat([0, 0.0]),
                  
                    zoom: 18
                })
            });

        </script>
    </body>
</html>`

after updateing ol.js to 3.14.0 (or 3.14.1) html page stops rendering, when i change script src to point ol 3.13.1 version, it is back to normal. the page works fine in chrome browser in both version of ol.js

**Comment by fredj** [comment]
See #4978
