### ISSUE TITLE
Mapbox vector tiles gutter issue with points

### ISSUE THREAD

**Issue by loicgasser** [openlayers/ol3#5017]
Hi,
I created mbtiles and it seems to me that there might be an issue at the edge of the tiles when rendering points. (around 20'000 in my case)

Here is a link using the latest release of ol3 that illustrates my observation:
http://codepen.io/loicgasser/pen/reLZWL

And thank you for this awesome feature.

**Comment by ahocevar** [comment]
This is not a problem with OpenLayers, but with your tile provider: each tile needs to include nearby features from neighbouring tiles. Some tile generators/servers work with a fixed buffer, some take the intended symbol size into account and only include nearby features that would be cut off.

**Comment by loicgasser** [comment]
OK, thank you very much for this valuable information. I'm sorry for that.
