### ISSUE TITLE
Build: SlimerJS dependency not installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by geekdenz** [openlayers/ol3#5018]
See https://github.com/graingert/slimerjs/issues/36 .

Logged this issue here for reference because ol3 wasn't building for me on Ubuntu 14.04.

**Comment by jonataswalker** [comment]
It looks like you're not with the latest changes. See https://github.com/openlayers/ol3/issues/5005.

**Comment by fredj** [comment]
Fixed with #5006
