### ISSUE TITLE
Jerky panning in Firefox

### ISSUE THREAD

**Issue by heiki112** [openlayers/ol3#5022]
I see a very noticeable stutter every second or so when panning. Doesn't happen in Chrome or Edge.

![ff](https://cloud.githubusercontent.com/assets/2315736/13722384/6f7f39c0-e84c-11e5-8b63-325bfd8f963b.PNG)

**Comment by ahocevar** [comment]
Thanks for reporting this. I did some research and found a fix, see #5024.

**Comment by heiki112** [comment]
Tried it out, seems smooth.
