### ISSUE TITLE
Heatmap opacity has different effect.

### ISSUE THREAD

**Issue by rfinquiron** [openlayers/ol3#5026]
I can see the heatmap opacity doesn't work actually as opacity.
I plotted just two heatmap points on a map(see screenshot below) with opacity set to 1(full) but I can still see the background map.
![image](https://cloud.githubusercontent.com/assets/4939880/13728080/cab1f782-e924-11e5-8971-dffd97c0a31e.png)

Can somebody help me understand how this works and what changes would I need to make this make this work as actual opacity ?

**Comment by ahocevar** [comment]
That's the whole idea of a heatmap - it only gets fully opaque in regions where the heat is really, really on (i.e. many features with a high `weight`). If you want to increase the opacity, you could use a constant weight, e.g.
```js
new ol.layer.Heatmap({
  weight: function() { return 1; },
  // ...
});
```

**Comment by Lenninlasd** [comment]
Hi @ahocevar, How can I make, if I want the same level of opacity for all the values, but preserving the gradient of the colors, for example: 

<img width="350" alt="screen shot 2017-01-17 at 14 12 23" src="https://cloud.githubusercontent.com/assets/7197750/22035838/60bac78e-dcbf-11e6-83ea-bfb09d0f2f28.png">

**Comment by sandra-tu** [comment]
@Lenninlasd Hello! I am struggling with this exact same thing as well, have you managed to find a solution? Also @ahocevar if you have any knowledge for potential solutions please share!
