### ISSUE TITLE
forEachFeatureAtPixel doesn't work correctly for Point geometry

### ISSUE THREAD

**Issue by mstrop** [openlayers/ol3#5029]
A feature is not found, when I click far enough from centre of the Point geometry (close enough to its border, but still inside of it). I have created an example here - https://jsfiddle.net/mstrop/4gvLhfje/7/.
When you start clicking on border and you will continue towards the centre of the circle you will see, that the circle is found quite far from the border. Tested on IE, FF and Chrome.

**Comment by tsauerwein** [comment]
The property `renderBuffer` (see [ol.layer.Vector](http://openlayers.org/en/master/apidoc/ol.layer.Vector.html)) is taken into account for the hit detection. By default it is set to 100 pixels. If you have larger symbols, you will have to adjust it accordingly, e.g.:

```js
var vectorLayer = new ol.layer.Vector({
  source: vectorSource,
  style: styleFunction,
  renderBuffer: 200
});
```
https://jsfiddle.net/4gvLhfje/10/

**Comment by mstrop** [comment]
Thanks a lot and sorry for bothering.
