### ISSUE TITLE
Get View Resolutions

### ISSUE THREAD

**Issue by marlowp** [openlayers/ol3#5030]
How can I get the resolutions of the ol.View object?

At present we can pass in an Array<number> as the resolutions option when creating an ol.View, however I can't see any way to access that resolution array after the ol.View has been created. Is this intentional?

My usecase for wanting to get access to this is for creating a custom slider control. My current workaround is to save the resolution array I pass when creating ol.View, but I think it would be better if I could just get the resolutions array from the ol.View.

Also unless I'm misunderstanding how resolutions work (which is quite possible) it sounds like a good idea to be able to access this resolutions array from the ol.View object, perhaps just as a simple getResolutions() function.

**Comment by ahocevar** [comment]
Not sure if this helps for your custom slider, but there is an `ol.View#constrainResolution()` function. It is called with any resolution, and returns the closest resolution that the view was configured with.

If that isn't sufficient, we'd accept a pull request for adding a `getResolutions()` function.

**Comment by marlowp** [comment]
Thanks @ahocevar that function is very useful. I still think it would be helpful to be able to access the array of resolutions that are stored against the ol.View though. I would like to contribute to the OpenLayers 3 library so I'll see if I can get time in the coming weeks to try and implement the above.

**Comment by fredj** [comment]
#5352
