### ISSUE TITLE
A beautiful curve line/markline

### ISSUE THREAD

**Issue by ZoeHuang13** [openlayers/ol3#5037]
Is it possible to draw the line with animation like this?
![curveline](https://cloud.githubusercontent.com/assets/17848583/13774545/8e5099ee-eada-11e5-987f-1f0af13cab62.png)

like this [http://echarts.baidu.com/echarts2/doc/example/map11.html#-en](http://echarts.baidu.com/echarts2/doc/example/map11.html#-en)

I just achieve like this.
![my](https://cloud.githubusercontent.com/assets/17848583/13774661/18663fc6-eadb-11e5-8666-2859a78f8785.png)

Thank you.

**Comment by DavidHequet** [comment]
Are you looking for this?
http://openlayers.org/en/v3.14.2/examples/flight-animation.html

**Comment by ZoeHuang13** [comment]
I have seen this. To be honest, it's not beautiful. And I want the curve line but not the arc line related to the geographical position. I have found the other .js.
I focus on the visualization method.
I hope put in some beautiful visualization method like that.
And it is possible to integrate dynamic d3? The example is static. In other words, I want put d3's element(such as Sunburst Partition) in the ol3's map and the d3's element also can be interactived by the mouse.
Thank you for your reply.

**Comment by ahocevar** [comment]
You can do all kinds of things using the map's or layer's `precompose` and `postcompose` events, which give you direct access to the rendering context of the canvas.

Discussion can continue, but I'm closing this because it's not about an OpenLayers issue.
