### ISSUE TITLE
The position does not update when resize Map

### ISSUE THREAD

**Issue by minhduong** [openlayers/ol3#5047]
Hi,
I am using this example. However, when i resize the map (left or right), the position does not update.
http://openlayers.org/en/v3.14.2/examples/geolocation-orientation.html?q=geolocation

**Comment by ahocevar** [comment]
Cannot reproduce. Can you provide a screencast that shows the issue?

**Comment by fredj** [comment]
cannot reproduce with the [latest version](http://openlayers.org/en/v3.18.1/examples/geolocation-orientation.html).
