### ISSUE TITLE
Rendering issues with the immediate API

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#5067]
In 3.13.0, it was possible to use `precompose` and `postcompose` along with the immediate rendering API to clip layer rendering to a geometry.  See this example clipping a layer to a polygon: http://jsfiddle.net/yqwyp8md/

![v3 13 0](https://cloud.githubusercontent.com/assets/41094/13852393/6e862298-ec27-11e5-8e26-774840f7e957.gif)

In 3.14.2, the same example shows nothing rendered for the layer: http://jsfiddle.net/s4jrdqdc/

![v3 14 2](https://cloud.githubusercontent.com/assets/41094/13852404/7f4352c2-ec27-11e5-8300-194899fbf6d6.gif)

In master (with the current hosted build of master), the example sort of works.  It renders initially, but then flashes during rotation, and will disappear completely when the map is resized: http://jsfiddle.net/r87meu6c/

![master](https://cloud.githubusercontent.com/assets/41094/13852411/85e4bcce-ec27-11e5-8bf7-591cdc251457.gif)

**Comment by tschaub** [comment]
So 600c139a617cdb7ad24194eb6b40677ad865c631 is the cause for the difference between [3.14.2](http://jsfiddle.net/s4jrdqdc/) and [master](http://jsfiddle.net/r87meu6c/).

**Comment by tschaub** [comment]
This turns out to be because the `precompose` event handler code runs to completion before the "immediate" rendering actually happens (the path isn't drawn until `vectorContext.flush()` is called).  So in the example above, `context.clip()` is getting called before the geometry is drawn.

I don't think we need to make this work.  Instead, I think we could have convenient (and predictable) geometry rendering with `setStyle()` and `drawGeometry()` methods (see #5072).

**Comment by tschaub** [comment]
I'd also be up for revisiting #1473 and making all "immediate" rendering calls synchronous.  This would mean we would say that if you want `zIndex` support, use a vector layer.  Curious what others think.

**Comment by ahocevar** [comment]
Making "immediate" calls synchronous would also mean that users no longer need to listen for both `precompose` and `postcompose` for certain operations. The loss of `zIndex` support should not be a big problem, because users have full control over what gets rendered when as soon as the whole API is synchronous. Or am I missing something?

**Comment by tschaub** [comment]
I agree about `zIndex` support not being a problem.  If you care about `zIndex` you can either order your calls to the immediate API or use a vector layer.

See https://github.com/openlayers/ol3/compare/master...tschaub:more-immediate.

**Comment by tschaub** [comment]
Immediate rendering for `drawFeature()` in #5077.
