### ISSUE TITLE
Missed docs for ol.raster

### ISSUE THREAD

**Issue by drnextgis** [openlayers/ol3#5091]
If open `ol.source.Raster` [docs](http://openlayers.org/en/v3.14.2/apidoc/ol.source.Raster.html) and try to click on [operation](http://openlayers.org/en/v3.14.2/apidoc/ol.raster.html#.Operation) or [operationType](http://openlayers.org/en/v3.14.2/apidoc/ol.raster.html#.OperationType) then you get 404.

**Comment by fredj** [comment]
`src/ol/raster.jsdoc` is missing

**Comment by drnextgis** [comment]
PR https://github.com/openlayers/ol3/pull/5092

**Comment by bartvde** [comment]
thanks @drnextgis for all your great contributions lately, much appreciated!
