### ISSUE TITLE
Problem while migrating code for country borders from Openlayers2 to Openlayers3

### ISSUE THREAD

**Issue by vidhyadhari** [openlayers/ol3#5101]
I have this code in openlayers2:

`new OpenLayers.Layer.WMS('Country Boundaries',
          'http://geonetwork3.fao.org/ows/14074?', {
              layers: 'Country Boundaries',
              transparent: true
          }, {
              opacity: 0.4,
              wrapDateLine: true,
              tileOrigin: new OpenLayers.LonLat(-180, -90)
          });`

It works fine in Openlayers2. 

But when I migrate it to Openlayers3 using the below code:
`new ol.layer.Tile({
                source: new ol.source.TileWMS({
                   url: 'http://geonetwork3.fao.org/ows/14074?',
                   params: {
                    layers: 'Country Boundaries',
                    transparent: true
                }}),
                opacity: 0.4,
                wrapDateLine: true,
                isBaseLayer:false
            }),`
It doesn't work. I tried changing projection of the view to ESPG:4326 according to this http://comments.gmane.org/gmane.comp.gis.openlayers.devel.ol3/4288. But it too dint work well. The map doesn't show up anything.

Any suggestion on this would be of great help for me.

**Comment by ahocevar** [comment]
Working JSFiddle: http://jsfiddle.net/9zgudyft/.

**Comment by vidhyadhari** [comment]
Thanks it is working. I have used ol.proj.get('ESPG:4326') instead of 'ESPG:4326' in projection. Was the problem because of it. Just wanted to know what went wrong.

**Comment by ahocevar** [comment]
It's 'EPSG', not 'ESPG'. You can use `ol.proj.get('EPSG:4326')` as well.
