### ISSUE TITLE
TileGrid order reversed

### ISSUE THREAD

**Issue by exotfboy** [openlayers/ol3#5103]
I have an custom tilesets based on an image whose size is(6800, 3400).The tiles are generated according to the top - left(0, 0) of the image, and the x increase from left to right, and the y increase from top to bottom.

And I tried to add it using ol3:
```
    var mapSource = new ol.source.XYZ({
        tileGrid: new ol.tilegrid.TileGrid({
            origin: [1, 3400],
            resolutions: tresolution,
            extent: [1, 1, 6800, 3400]
        }),
        tileUrlFunction: function(xyz, ratio, projection) {
            var row = xyz[2],
                column = xyz[1],
                level = xyz[0];
            var src = '/z' + z + '/' + row + '/' + column + '.jpg';
            return "http://localhost/pub/" + src;
        }

    });

	var map = new ol.Map({
	    target: 'map',
	    layers: [
	        new ol.layer.Tile({
	            source: mapSource
	        })
	    ]
	    view: new ol.View({
	        center: [1, 1],
	        zoom: 1,
	        resolutions: tresolution
	    }),
	    renderer: 'dom'
	});
```

However after the map loaded, I found that the `top` and `bottom` tiles are reversed. The `y` of the tile increases from `bottom` to `top`.

What's going on ?

**Comment by ahocevar** [comment]
Correct. OpenLayers uses TMS tile coordinates internally. Instead of configuring a `tileUrlFunction`, you can configure a `url`:
```js
url: 'http://localhost/pub/{z}/{y}/{x}.jpg'
```
If you want to continue using a `tileUrlFunction`, you'll need `var row = -xyz[2] - 1`.

**Comment by ahocevar** [comment]
Also see http://openlayers.org/en/v3.14.2/examples/canvas-tiles.html.

**Comment by exotfboy** [comment]
No, I can not use the url template, since the url is full custom which owns some dynamic calculation.

**Comment by ahocevar** [comment]
See above: `var row = -xyz[2] - 1`. Maybe you have to change the origin too then.

**Comment by exotfboy** [comment]
I change the `row = -xyz[2]-1` and it works now.

I think it would be better add this in the basic concepts of the ol3 docs. 

BTW, I found that the `ol.source.OSM` works normally, and I have dig into the codes, but I have not find any magic. How did osm do that?

**Comment by ahocevar** [comment]
> I think it would be better to add this in the basic concepts of the ol3 docs.

Pull request welcome.

> BTW, I found that the ol.source.OSM works normally, and I have dig into the codes, but I have not find any magic. How did osm do that?

It uses the template, which always replaces `{y}` with `-xyz[2] - 1`.
