### ISSUE TITLE
ol3 and Mootools | Document isn't the same

### ISSUE THREAD

**Issue by stefanheimes** [openlayers/ol3#5104]
Hi, i have trouble with ol3 and Mootools. 

You have a check for the XML see: https://github.com/openlayers/ol3/blob/master/src/ol/xml.js#L95
If MooTools is enabled on the page, this check will always return false. Without MooTools the function works. 

The main problem is that MooTools change the Document. 

With MooTools i got this error:
Uncaught AssertionError: Assertion failed: node.nodeType should be ELEMENT

With MooTools the Document looks so:
![image](https://cloud.githubusercontent.com/assets/988286/13984403/4fc0a6fc-f0f6-11e5-8a29-c228c9fcfb52.png)

Without MooTools the Document looks so:
![image](https://cloud.githubusercontent.com/assets/988286/13984431/7ae56b88-f0f6-11e5-839c-6df799234a65.png)

**Comment by ahocevar** [comment]
Mootools stores the original `Document` in `Browser.Document`. Maybe you can just set
```js
Document = Browser.Document;
```
before running any OpenLayers code?

**Comment by stefanheimes** [comment]
Okay I'll try it thx.

**Comment by stefanheimes** [comment]
Okay it works. 

 So it is possible to add this on ol3, something like this:

```javascript
/**
 * @param {?} value Value.
 * @return {boolean} Is document.
 */
ol.xml.isDocument = function(value) {
    if(window.MooTools && Browser.Document) {
        return value instanceof Browser.Document;
    } else {
        return value instanceof Document;
    }  
};
```

**Comment by ahocevar** [comment]
Possible? Yes. Desirable? Not at all. Maybe a duck-type check like `return !!value.documentElement;` would be nicer.

**Comment by fredj** [comment]
can we close this issue?
