### ISSUE TITLE
Dashed line style not working on IE10

### ISSUE THREAD

**Issue by Sylphide** [openlayers/ol3#5114]
Hi,
I'm trying to draw a dotted line and it works fine on every navigator except on IE10 where only color and width parameters are applied.

Here is my style:
```
new this.ol.style.Style({
      stroke: new this.ol.style.Stroke({
        width: 4,
        color: [0, 44, 129, 1],
        lineDash: [1, 8]
      }),
      zIndex: 1
    });
```

**Comment by ahocevar** [comment]
The canvas context's `setLineDash` method is not supported by IE 10. See https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash.
