### ISSUE TITLE
Add events on ol.source.Raster page

### ISSUE THREAD

**Issue by drnextgis** [openlayers/ol3#5117]
I'm not sure that I correctly understood API docs structure, but why [here](http://openlayers.org/en/v3.14.2/apidoc/ol.source.Raster.html) no information about `afteroperations` and `beforeoperations` [events](http://openlayers.org/en/v3.14.2/apidoc/ol.source.RasterEvent.html)?

**Comment by fredj** [comment]
The `@fires` jsdoc annotation is probably missing.
Example https://github.com/openlayers/ol3/blob/v3.14.2/src/ol/layer/imagelayer.js#L16

untested

**Comment by drnextgis** [comment]
You are right. Problem was fixed by adding this annotation.
