### ISSUE TITLE
ESRI - TILE ARCGIS REST SERVICE PARAMS SIZE PROBLEM

### ISSUE THREAD

**Issue by ahmetmum** [openlayers/ol3#5126]
`SIZE` parameter not working in `params`.

**Class:**
`ol.source.TileArcGISRest`

**Sample Code:**
`var layer = new ol.layer.Tile({`
`source: new ol.source.TileArcGISRest({`
`urls: urls,`
`tileLoadFunction: function (image, src) {`
`image.getImage().src = src + "&rnd=" + Math.random();`
`},`
`params: { LAYERS: layers, SIZE: size }`
`}),`
`opacity: 1,`
`visible: true,`
`zIndex: 500`
`});`

Thanks

**Comment by bartvde** [comment]
What are you trying to achieve? A single tile request?

Size is determined by the tileSize, see: https://github.com/openlayers/ol3/blob/master/src/ol/source/tilearcgisrestsource.js#L96

**Comment by ahmetmum** [comment]
Hello there.
As is known, the `SIZE` of in `TileArcGISRest` service should be based on the resolution of the screen that labels are placed correctly.
`params` but I could not provide the solution to provide you with `TileGrid`.
I did as follows:

.........
```
source: new ol.source.TileArcGISRest({
                        urls: urls,
                        tileGrid: new ol.tilegrid.TileGrid({
                            tileSize: size,
                            extent: extent,
                            resolutions: resolutions
                        }),
                        tileLoadFunction: function (image, src) {
                            image.getImage().src = src + "&rnd=" + Math.random();
                        },
                        params: { LAYERS: layers }
                    }),
```
.........

Thank you
