### ISSUE TITLE
How to show a tile from another layer if the current layer doesn't exist?

### ISSUE THREAD

**Issue by costales** [openlayers/ol3#5142]
Hi :) I would like to use an offline tile if it is local available.

Then the approach should be:
 - Map has an offline layer.
 - openlayers ask for 1 offline tile map, if it doesn't exist, ask for an online tile map in another layer.

```
	var offlineLayer = new ol.layer.Tile({
		source: new ol.source.OSM({
			url: 'maps/{z}/{x}/{y}.png'
		})
	});
	var onlineLayer = new ol.layer.Tile({
			source: new ol.source.MapQuest({layer: 'osm'})
		})
	});

	var map = new ol.Map({
		layers: [
			offlineLayer
		],
	  controls: [],
	  target: 'map',
	  view: new ol.View({
		center: ol.proj.transform([4.666389, 50.009167], 'EPSG:4326', 'EPSG:3857'),
		zoom: 4,
		minZoom: 1,
		maxZoom: 20
	  })
	});

	offlineLayer.getSource().on('tileloaderror', function(event) {
		console.log('here ask for a onlineLayer tile');
	});
```

Is this possible? I think with [tileloaderror](http://openlayers.org/en/v3.7.0/apidoc/ol.source.OSM.html)? But I didn't find a simple example about change the tile url on fly just for 1 tile.

Thanks in advance!

**Comment by ahocevar** [comment]
Why not just
```js
    offlineLayer.getSource().on('tileloaderror', function(event) {
        map.addLayer(onlineLayer);
        map.removeLayer(offlineLayer);
    });
```

**Comment by ahocevar** [comment]
If you need per-tile control, configure just one layer, and use its `tileLoadFunction` with an `XMLHttpRequest` for the tile image of the offline image. If it fails, set the `src` of the tile to one that points to the online resource.

**Comment by costales** [comment]
Hi Andreas,
Yes a per-tile control would be the desire. Do you have any code
example about tileLoadFunction & XMLHttpRequest? :)
Thanks a lot!

**Comment by brunopacola** [comment]
Hi everyone,

I’ve been reading this discussion and it’s exactly the kind of feature I’m looking for. I’d like to ask if there has been any progress on this over the years. Has this challenge been solved in any way, either natively in OpenLayers or through a recommended workaround?

Thank you in advance!

**Comment by ahocevar** [comment]
@brunopacola It's now even easier than before, with a `TileImage` source and a `loader` configured to try fetching an image from one source, and if it fails fall back to another. Something like this:
```js
  async loader(z, x, y) {
    for (const url of [`source1/${z}/${x}/${y}.png`, `source2/${z}/${x}/${y}.png`]) {
      const image = new Image();
      image.src = url;
      try {
        await image.decode();
        return createImageBitmap(image);
      } catch {
        // next source
      }
    }
    throw new Error('No image available');
  }

**Comment by brunopacola** [comment]
THANK YOU!!!
