### ISSUE TITLE
getCoordinateFromPixel returns different positions with same pixel

### ISSUE THREAD

**Issue by nugetchar** [openlayers/ol3#5143]
I have a feature representing a vehicle which **does not move at all** on a map. I want, periodically, to retrieve the point's coordinates located at a constant distance of the vehicle. When the vehicle does not move, the point's coordinates should be the same.

I use getCoordinatesFromPixel in order to manage to do that, but, although the pixel passed in argument is still the same, the coordinates I get are differents, resulting in some oscillations on screen.

**How to reproduce : **
Assuming you've got vehMapPos, an array containing the vehicle position (in map units) and map, the Map.
On the Map, rotated with any angle, put a feature and center the map on the feature. Then, launch a setInterval. In this interval, do the following : 

```
var elem = document.getElementById('yourMapId');
var clientRect = elem.getBoundingClientRect();
//Getting pixel coordinates
var centerPixelX = clientRect.width/2;
var tierPixelY = clientRect.height/3;
var pixel = [centerPixelX, 2*tierPixelY];


//Problem is here
var point = map.getCoordinateFromPixel(pixel);

//Creating vector from vehicle to pixel
var X = point[0];
var Y = point[1];

var x = vehMapPos[0];
var y = vehMapPos[1];

var vector = {
   'vx': (x-X),
   'vy': (y-Y)
};

//Centering map to the vector coordinates
var mapCenter  = map.getView().getCenter();
var newCenter = [mapCenter[0] + vector.vx, mapCenter[1] - vector.vy];
map.getView.setCenter(newCenter);
```

I hope this code helps and do no hesitate to question me if you cannot reproduce the bug. It is very annoying, as we'd like to do a GPS functionality.

Regards

**Comment by ahocevar** [comment]
The map does exactly what you tell it to do. The pixel position will map to a different coordinate when the center changes, because the pixel is relative to the map viewport, whereas the map center (and the coordinate of the vehicle) is in map coordinates.

**Comment by nugetchar** [comment]
Ho @ahocevar, the problem is that the vehicle does not move, so the centre should not move.

**Comment by ahocevar** [comment]
@nugetchar your vector points to a pixel position on the map, and the vector is involved in the calculation of the new center. So the new center will be different, making the next pixel to coordinate conversion different.

If I'm missing something, please create a JSFiddle that shows your problem.

**Comment by nugetchar** [comment]
No, the new center won't be different. I said the vehicle does not move. It does not move, and we want to center the map, not at the vehicle's coordinate, but at the vehicle coordinates AND some delta. Example: 
vehicle = {x: 1, y: 2};
vector = {vx: 4, vy: 3};

===> center = {x: 5, y: 5}

I'll try not using the mapCenter (I use it because at first the map is centered on the vehicle's coordinates). But still, the new center shouldn't oscillate between two coordinates.

**Comment by ahocevar** [comment]
Provide a JSFiddle, and we can continue the discussion.

**Comment by nugetchar** [comment]
I've got a JSFiddle but it won't show the map.

**Comment by tsauerwein** [comment]
You can start from this one: http://jsfiddle.net/vqu45s4g/

**Comment by nugetchar** [comment]
Ok I managed to do what should work: [JSFiddle](http://jsfiddle.net/a020po05/). As you can see, the center is never different. Unfortunately, I cannot manage to reproduce the oscillations. I am working on it, maybe it's the projection, I am kind of lost with it.

I tried to see what happened in debug mode, when the `getCoordinateFromPixel `is executed. I noticed it calls the following method: `ol.vec.Mat4.multiVec2 = function(mat, vec, resultVec){//code here}` => the `mat` argument is non-constant (it should be, as the center should be the same in my case).

**Comment by nugetchar** [comment]
I finally managed to reproduce the bug wit the v3.11.2 release here: [JSFiddle with oscillation](http://jsfiddle.net/a020po05/3/).

Now, I have only one question: we use this release because it is patched for integration with proj4js. Is there any patch with the v3.14.2 release ? :)

**Comment by tsauerwein** [comment]
Thanks for the JSFiddle. But I can't really see what should be wrong with the behavior of `getCoordinateFromPixel`. You call `getCoordinateFromPixel` on a fixed pixel value, you create a vector from this coordinate with the vehicle position (which does not change). Then you add this vector to the current center, and change the center. If you call `getCoordinateFromPixel` the next time with the same pixel, you get a different coordinate because the center has changed. That is correct.

> ...  we want to center the map, not at the vehicle's coordinate, but at the vehicle coordinates AND some delta

"and some delta" - what should this delta be? A pixel distance? E.g. center the map 20px from the vehicle position?

**Comment by nugetchar** [comment]
Hi @tsauerwein ,
First of all, thanks for your quick answer.

> If you call getCoordinateFromPixel the next time with the same pixel, you get a different coordinate because the center has changed

That is not the case here, you can see it in the JSFiddle, because I do not simply apply a vector to the center of the map. In fact, I simply calculate the coordinates of the point where I should center the map, so the vehicle appears at 1-third of the map's height (starting from the bottom). So no, once again: there should be absolutely no change regarding the center.

Finally, if you check the second JSFiddle I provided ([**this one**](http://jsfiddle.net/a020po05/4/)), you will see the oscillation problem I am talking about.
I already found out it was due to a release problem, and, as I asked:

> I finally managed to reproduce the bug with the v3.11.2 release here: [JSFiddle with oscillation](http://jsfiddle.net/a020po05/4/).
> Now, I have only one question: we use this release because it is patched for integration with proj4js. Is there any patch with the v3.14.2 release ? :)

**Comment by ahocevar** [comment]
> Now, I have only one question: we use this release because it is patched for integration with proj4js. Is there any patch with the v3.14.2 release ? :)

Proj4js is integrated in v3.14.x just as good as it is in v3.11.x.

**Comment by nugetchar** [comment]
> Proj4js is integrated in v3.14.x just as good as it is in v3.11.x.

Yes, it is integrated. But we still have to add the proj4js requirement at the beginning:
`(function (root, factory) {
   if (typeof exports === "object") {
      // added
      module.exports = factory(require("proj4js"));
   } else if (typeof define === "function" && define.amd) {
      define(["proj"], factory);
   } else {
     // added
     root.ol = factory(root.proj4);
   }
 // added
}(this, function(proj4){...}
`
Also, please stop responding to me like that: since the beginning you give me the impression that you do not take this problem seriously. I had to explain it to you four times, and even with the JSFiddle you seemed not to understand what I was explaining. I am encountering some problems and I am just looking for solutions.

**Comment by ahocevar** [comment]
In v3.14.x, you can use `ol.proj.setProj4(require('proj4js'));` to integrate Proj4js. No need to patch anything.

**Comment by nugetchar** [comment]
OK, so it's a miscommunication between us, sorry for that.

**Comment by ahocevar** [comment]
> OK, so it's a miscommunication between us, sorry for that.

Obviously. What @tsauerwein and I were trying to explain is that what you are seeing (the "oscillation") is expected behaviour. A pixel on the map can represent several hundred meters, depending on the resolution. This is the cause for your oscillation. If you do the whole calculation in pixels, you always round to the center of a screen pixel, and can avoid the oscillation. I've updated your fiddle to show how this is done: http://jsfiddle.net/a020po05/5/.

A hint for the future: before accusing a library you're using of having a bug, it's better to show a code snippet and ask whether it's something in your application, or if there could be the possibility of a bug in the library. Sounds much friendlier, doesn't it?
