### ISSUE TITLE
Encrypt your OpenLayers website please

### ISSUE THREAD

**Issue by paladox** [openlayers/ol3#5144]
Hi please can you Encrypt your website and use https links. There are free ssl tools such as https://letsencrypt.org/

So it will be free and no cost to it.

**Comment by fredj** [comment]
If you need a CDN on https, the recommended solution is to use https://cdnjs.com/libraries/ol3

**Comment by paladox** [comment]
Oh but what about the map data the images that are stored on your end.

Thanks for the link.

**Comment by ahocevar** [comment]
OpenLayers does not store nor provide any map data. It is up to you to use sources with https:// urls if that is what you want.

**Comment by paladox** [comment]
Oh where does it get its map data from since in the f12 tools it shows warning related to this image is insecure please use https or something similar to that.

**Comment by bartvde** [comment]
Can you please specify what resource exactly you are talking about?

**Comment by paladox** [comment]
Well ln OpenLayersV2 when we load it we load the images from our site but the map data is stored else were. I presume this happends with OpenLayersV3.

**Comment by bartvde** [comment]
You are talking about a resource accessed over http in the console, can you be more specific which resource? Otherwise there is no point in discussing this issue any further.

**Comment by virginielgb** [comment]
Hello,
Related to @paladox 's issue:
I have a website with SSL encryption, and I load a map. I'm hosting myself the openlayer JavaScript file to avoid any issue.
However, the tiles I use are hosted on http://demo.opengeo.org/geoserver/wms, which is something I found on OpenLayer's website's examples a while back.
I can't find any similar times hosted over HTTPS and this is starting to bug me :/
Any idea where to find those?
Any chance OL would add some https link in the examples section?

Cheers

**Comment by probins** [comment]
The shaded-relief example fetches Mapbox tiles via https; the OSM source always uses https, though tiles can be loaded with either protocol.
