### ISSUE TITLE
Uncaught TypeError when modifying shape right after drawing it.

### ISSUE THREAD

**Issue by jtomi85** [openlayers/ol3#5145]
Hi,

I'd like to modify a polygon after it has been drawn. For this I've created a listener for 'drawend' and another for 'addfeature' events. In the first handler the draw interaction is removed from the map and the feature is stored in a temporary list. With the help of this list I can determine when the feature drawn will be added to the layer's source. When it happens I add a modify interaction to the map.
However when I close the polygon with a single click it produces an error that comes from modify interaction.

jsFiddle: https://jsfiddle.net/tomi85/4qhpsz67/2/
Platform: Windows 8.1 / Chrome 49 (in FireFox it's ok)

How to reproduce the error:
Please draw an arbitrary shape, but when you are ready to close it to finish your polygon, move your mouse exactly right above to the closing point then click (single click) and don't move until you get an error: "Uncaught TypeError: Cannot read property 'length' of null". This error comes from ol.interaction.Modify.prototype.removeVertex_ function, where this.dragSegments_ value is null. This error or bug can be fixed by setting the line (row 191) from "this.dragSegments_ = null;" to "this.dragSegments_ = [];" in modifyinteraction.js. But you should further check this.

Many thanks,
Tomi

**Comment by ahocevar** [comment]
The change you suggest above makes sense. In addition, it would make sense to change line 544 to `this.dragSegments_.length = 0;`. Pull request accepted.
