### ISSUE TITLE
Suspicious return value from ol.interaction.Modify#removeVertex_

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5146]
The function [returns true if the vertex was removed](https://github.com/openlayers/ol3/blob/v3.14.2/src/ol/interaction/modifyinteraction.js#L879) but [`true`](https://github.com/openlayers/ol3/blob/v3.14.2/src/ol/interaction/modifyinteraction.js#L974) is always returned.

**Comment by nicholas-l** [comment]
Should be ```return deleted```?

**Comment by fredj** [comment]
yes, it should be `return deleted;`
