### ISSUE TITLE
Lazy Render 

### ISSUE THREAD

**Issue by jfantunes** [openlayers/ol3#5147]
Hi there, i would like to know if there is a way or a future revision to enable lazy rendering like google maps has. Instead of rendering the entire view at the same time it would render only bites of data sequentially. In this particular case i'm talking about vector layers.

Thank you

**Comment by ahocevar** [comment]
OpenLayers has several ways to do this already: with vector tiles, using `ol.layer.VectorTile` and `ol.source.VectorTile`, or with an `ol.layer.Vector` with `ol.source.Vector` and `strategy: ol.loadingstrategy.tile(ol.tilegrid.createXYZ())`.
