### ISSUE TITLE
Uncaught TypeError in GeoJSON format read features (v3.14.2)

### ISSUE THREAD

**Issue by JWallaceDev** [openlayers/ol3#5156]
Hi Guys

I'm trying to read some geoJSON and change the projection before adding to a vector layer.

When doing so I'm getting the following error:

"Uncaught TypeError: this.getObject_ is not a function"

From format.readFeatures:

```
var features = new format.readFeatures(geojsonObject, {
            dataProjection: 'EPSG:4326',
            featureProjection: 'EPSG:3857'
        });
```

Details:

JSFiddle: https://jsfiddle.net/JWallaceDev/7dr12occ/
Platform: Windows 7, Chrome, and CEF

I'm using the scripts from the OL website, as per the examples:

http://openlayers.org/en/v3.14.2/build/ol.js

Couldn't get these to work in the JSFiddle tho, so have left the External Resources blank.

I tried going right back to v3.0.0 and still encountered the issue.

I'm fairly new to OpenLayers so may be going about it in the wrong way, and if so any suggestions would be much appreciated. 

Many Thanks

**Comment by tsauerwein** [comment]
```javascript
var features = new format.readFeatures(geojsonObject, {
```
This should be:
```javascript
var features = format.readFeatures(geojsonObject, {
```

**Comment by JWallaceDev** [comment]
Ah of course :/

Working perfectly now thank you
