### ISSUE TITLE
Build error when using ol-externs.js

### ISSUE THREAD

**Issue by adube** [openlayers/ol3#5168]
In an application I build using OpenLayers' ol-externs.js file, after upgrading to v3.15.0 I get the following error.

```
ERR! compile node_modules/openlayers/build/ol-externs.js:18672:
    ERROR - Bad type annotation. type not recognized due to syntax error
ERR! compile  * @typedef {{}}
ERR! compile               ^
ERR! compile 
ERR! compile 
ERR! compile 1 error(s), 0 warning(s)
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 1 
```

I would be willing to work on a fix for this, but I'm not sure how this should be addressed.  If someone could give me a hint, I'd work on a PR for this.

Also, this is not the first time I get errors when using the ol-externs.js file after upgrading.  It would make sense if the Continuous Integration could test that file also for tickets causing those errors be responsible of making sure that the proper fix is made immediately.

Thoughts about this would be welcome.

Thanks,

Alexandre

**Comment by fredj** [comment]
The problem is the `olx.source.AttributionOption` in `externs/olx.js`

**Comment by marcjansen** [comment]
Thanks for the issue, @adube. I would be very i nterested in catching things like this earlier, ideally during CI. Ideas anyone?
