### ISSUE TITLE
Strange behavior of feature setStyle on Selection interaction

### ISSUE THREAD

**Issue by Gudahtt** [openlayers/ol3#5175]
As of version 3.15.0, I've noticed that the setting feature style on the 'select' event for the Selection interaction has behaved very strangely. The style I'm attempting to set on the selected feature will either be set on seemingly random nearby features as well, or the entire background will have the style applied... I'm not sure what's going on here.

I've made an attempt at creating a minimal jsfiddle of the problem [here.](http://jsfiddle.net/enfumpz5/2/)

At first I thought it was a problem with using setStyle on features in general, but I couldn't reproduce the problem until using the selection interaction.

**Comment by ahocevar** [comment]
Thanks for the good bug report. Obviously the recent vector renderer optimizations (#5149) do not work when features are skipped in the replay - the Select interacion uses `ol.Map#skipFeature`.

To make it work, when skipping a feature in the replay, we need to check if a fill or stroke is pending, and call `context.fill()` or `context.stroke()` and context.beginPath().

**Comment by ahocevar** [comment]
@fredj, do you want me to take a closer look? Or are you guys working on it?

**Comment by fredj** [comment]
I'm not looking at it right now but I've added the label to not forget that we must address this issue
