### ISSUE TITLE
Bing maps broken?

### ISSUE THREAD

**Issue by mamayoleksandr** [openlayers/ol3#5181]
Noticed today that our ol3 doesn't render Bing maps.
The example seems also broken
http://twpayne.github.io/ol3/remote-vector/examples/bing-maps.html

**Comment by fredj** [comment]
It's working with the official one: http://openlayers.org/en/v3.15.0/examples/bing-maps.html

**Comment by jonataswalker** [comment]
It can be a non (anymore) valid key.

**Comment by fredj** [comment]
The examples at http://twpayne.github.io/ol3/remote-vector/examples/ are very old and must not be used
