### ISSUE TITLE
BoundingBox WMS 1.3.0

### ISSUE THREAD

**Issue by lehmannwebdev** [openlayers/ol3#5182]
I have a problem with bad bounding box generated when WMS verision is set to 1.3.0.

WMS standard (http://docs.geoserver.org/latest/en/user/services/wms/basics.html):
1.0.0 = SRS = X Y = BBOX:latitude/longitude
1.1.0 = SRS = X Y = BBOX:latitude/longitude
1.1.1 = SRS = X Y = BBOX:latitude/longitude
1.3.0 = CRS = I J = BBOX:longitude/latitude 

bbox for 1.1.1 = [minx, miny, maxx, maxy]
bbox for 1.3.0 should be [miny, minx, maxy, maxx]

When I set ol.source.TileWMS params "VERSION" 1.1.1 or 1.3.0 open layer generate bounding box in one format "BBOX:latitude/longitude".

example:
https://fiddle.jshell.net/w0qz2fox/4/

generate:
- for 1.1.1 
http://wms.hgis.cartomatic.pl/topo/2180/wig25k?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=wig25k&WIDTH=256&HEIGHT=256&SRS=EPSG%3A2180&STYLES=&BBOX=462995.2590149492%2C743968.6351981647%2C464216.88238965883%2C745190.2585728744

- for 1.3.0
http://wms.hgis.cartomatic.pl/topo/2180/wig25k?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=wig25k&WIDTH=256&HEIGHT=256&CRS=EPSG%3A2180&STYLES=&BBOX=462995.2590149492%2C743968.6351981647%2C464216.88238965883%2C745190.2585728744

As you can see bbox is these same.

When i make bbox in correct order it works:

http://wms.hgis.cartomatic.pl/topo/2180/wig25k?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=wig25k&WIDTH=256&HEIGHT=256&CRS=EPSG%3A2180&STYLES=&BBOX=743968.6351981647,462995.2590149492,745190.2585728744,464216.88238965883

**Comment by ahocevar** [comment]
EPSG:2180 is not latitude/longitude, it is x/y. So it looks like your GeoServer is misconfigured. A temporary workaround is to change the proj4 string, i.e. add `+axis=neu` to it. See https://fiddle.jshell.net/w0qz2fox/5/ for an updated fiddle.
