### ISSUE TITLE
Perhaps the problem ol.control.Rotate when using your own image

### ISSUE THREAD

**Issue by AnatolyAG** [openlayers/ol3#5199]
I use my image to the image code:

```
var tmpImg = new Image(40, 40);
    tmpImg.src = "img/kompas.svg";
    try{
    
 var cntrlRotate = new ol.control.Rotate({
        className: 'ol-rotate-my',
        autoHide: false,
        label: tmpImg,
        tipLabel: 'Direction north, for rotate  Shift+Alt + left button mouse.',
        target: elemDivCntrl 
    });


    map.addControl(cntrlRotate);
    }
    catch (errrot){}
```

an error in the debug on line 35675:

` if (typeof label === 'string') {
    this.label_ = goog.dom.createDom('SPAN',
        'ol-compass', label);
  } else {
    this.label_ = label;
   ** this.label_.classList.add(this.label_, 'ol-compass');**
  }`

You might be so?

` ** this.label_.classList.add('ol-compass');**`

**Comment by bartvde** [comment]
You're right thanks for the report, I will create a pull request

**Comment by AnatolyAG** [comment]
OK. Thank you.
