### ISSUE TITLE
Change in cdnjs files

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5202]
Not sure whether this is intentional or not, and I can't find where it's defined.
Up to 3.14.2 there were 3 files on cdnjs: ol.js, ol-debug, ol.min.js https://cdnjs.com/libraries/ol3/3.14.2
From 3.15.0 there are only 2. https://cdnjs.com/libraries/ol3/3.15.0
I was using ol.min.js but this no longer exists.
If this was intentional, I think it should be mentioned in the release notes.

**Comment by marcjansen** [comment]
I think these commits are rellevant: https://github.com/cdnjs/cdnjs/commit/bb25f72c0884dec641a6f0ad32b221506cc6a0cd#diff-95a95a9c0e9d8318f833fdeb8f203823 & https://github.com/cdnjs/cdnjs/commit/899d6cc39a04b50a121bb4e1651cac425a46d2f7#diff-95a95a9c0e9d8318f833fdeb8f203823 both from @PeterDaveHello.

I am by no means an expert though. Perhaps @PeterDaveHello can say something?

**Comment by ahocevar** [comment]
Actually the change on cdnjs makes sense - ol.min.js was the closure minified build run through uglifyjs again. So `ol.js is` the file you should be using in production, or `ol-debug.js` for debugging. Do we advise users to use `ol.min.js` anywhere? If so, that should be changed.

**Comment by probins** [comment]
right. I recently added mention of cdnjs files and didn't specify which one to use, so this is only a (minor) issue for anyone like me who happened to use min.js. So I'll close
