### ISSUE TITLE
ol3 doesn't work anymore since v3.13.0 under Qt's WebKit

### ISSUE THREAD

**Issue by olivierdalang** [openlayers/ol3#5214]
Hi !

Since version v3.13.0, ol3 doesn't work anymore under Qt's WebKit. One could think that no one cares about Qt's WebKit, but it's a very convenient way to render web maps to PDFs using wkhtmltopdf...

Here are the results of the simple map example (I used QtWeb to debug Qt's javascript : http://www.qtweb.net/download.html ) :

- http://openlayers.org/en/v3.12.1/examples/simple.html?mode=raw
Displays properly

- http://openlayers.org/en/v3.13.0/examples/simple.html?mode=raw
```
TypeError: 'undefined' is not a function (evaluating 'handler.bind(s)')
[pointereventhandler.js:123]
```

- http://openlayers.org/en/v3.15.1/examples/simple.html?mode=raw
```
TypeError: 'undefined' is not a function (evaluating 'function() {
    this.animationDelayKey_ = undefined;
    this.renderFrame_.call(this, Date.now());
  }.bind(this)')
typeerror: 'undefined' is not a function (evaluating 'function() {    this.animationDelayKey_ = undefined;    this.renderFrame_.call(this, Date.now());  }.bind(this)')
[map.js:207]
```

Thanks !!

Olivier

**Comment by fredj** [comment]
ol3 requires a ECMAScript 5 environment; you need to include polyfills. See #4706

**Comment by nicholas-l** [comment]
Hi
You most likely need to add the bind polyfill. See polyfill.io for bind (https://cdn.polyfill.io/v2/polyfill.min.js?features=Function.prototype.bind)

**Comment by olivierdalang** [comment]
@fredj @nicholas-l 
Thanks ! I would never have thought of that !

Is there a list of features one needs to polyfill ?

I had some success with 
`<script src="https://cdn.polyfill.io/v2/polyfill.js?features=requestAnimationFrame,Function.prototype.bind&unknown=polyfill"></script>`, but I still get some errors (and unfortunately, I'm having a lot of trouble of debugging the javascript because wkhtmltopdf's output is not verbose at all).

Thanks again !
