### ISSUE TITLE
ol.source.CartoDB.prototype.setConfig needs to be exportable

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#5217]
Without this, [the CartoDB example](http://openlayers.org/en/v3.15.1/examples/cartodb.html) doesn't work.
```
TypeError: cartoDBSource.setConfig is not a function
```

**Comment by mileslee1987** [comment]
Dear Tschaub,

I know this is an old question, but however, I've added @api annotation before .setConfig but it still shows the same error. Would you please give some tips about this issue which would be really appreciated .

Thank you.

**Comment by tschaub** [comment]
@mileslee1987 - if you use a recent release of the library, this issue should be fixed.  What version are you using?

**Comment by mileslee1987** [comment]
Hi Tschaub,

I am using v4.6.5, as my old codes need to follow the "module.exports" style instead of "import, export" style in v5+. So if I am using v4.6.5, is there any solution to this ? Many thanks !!!

**Comment by tschaub** [comment]
@mileslee1987 - it looks like the change that added the `@api` annotation came well before 4.6.5 (see https://github.com/openlayers/openlayers/commit/d4ac5800d5e49b39c859fe6052d53a21b787226a).  So the `setConfig` method should be available to custom builds of 4.6.5.

This example uses the `setConfig` method: http://openlayers.org/en/v4.6.5/examples/cartodb.html – and it looks to me like that is working.
