### ISSUE TITLE
rework ol.animations

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5234]
from #2588:

I'm planning on reworking how animation is done.  Instead of setting the final view state and then adding functions that tween the frame state, the view will be animated.  This will make synchronized maps work as expected during animated transitions.

Instead of a `beforeRender` function on the map, the view may have an `animate` method.

**Comment by gberaudo** [comment]
FWIW, if the view is updated during the animation, an event will be triggered at each change and it will cause the recomputation of the camera state in OL3-Cesium.

**Comment by tschaub** [comment]
> FWIW, if the view is updated during the animation, an event will be triggered at each change and it will cause the recomputation of the camera state in OL3-Cesium.

I assume anybody who doesn't want to do extra work during animated view transitions would benefit from a flag (or hint) indicating that an animation is underway.

I also imagine that it would be a nice feature to be able to synchronize a 3d and 2d view during a transition.

**Comment by gberaudo** [comment]
I agree it would be cool to have animations during view transitions.

Currently, it would be possible to create a Cesium fly animation from the current position to the target position provided by OL3, however we do not have the duration of the animation and obviously we cannot take the exact same path as OL3.

If the mechanism is changed, we will not know the target position / or the intermediate positions and will not be able to prepare a fly path. I fear having to compute a high rate of new positions per second may be too expensive ; we can try though.
