### ISSUE TITLE
Chome doesn't render map correctly with projection

### ISSUE THREAD

**Issue by rgvassar** [openlayers/ol3#5236]
The following fiddle works fine for me in everything but Chrome. If you remove the projection from the view constructor, it works fine.[fiddle](http://jsfiddle.net/wvoxygr9/1/)

**Comment by marcjansen** [comment]
It renders as expected in my Chrome 46, Linux. What exactly isn't working for you?

Side note: With `projection` set, the tiles from OpenStreetMap will be reprojected from `EPSG:3857` to `EPSG:4326`.

**Comment by ptsagkis** [comment]
I have the same problem using tile reprojection and Chrome. 
You can see the the buggy attitude with the example [http://openlayers.org/en/v3.15.1/examples/reprojection-wgs84.html]. This is happening since version 3.14 and above. Me chrome version is 50.0.2661.75 m

**Comment by rgvassar** [comment]
It's hard to explain. Only a small portion of the map is rendered. Most of the map is just white. It has problems rendering any geometries I add to the map as well. I tested with Edge, Firefox, and Chrome. Only Chrome has the problem. I'm on Windows 10 Pro 64 bit with Chrome 49.0.2623.112 m

**Comment by probins** [comment]
I'm using Chrome 49.0.2623.112 as well, but I don't see this issue. It's slow to render, so you have to wait for several seconds for it to display, but I don't see any difference between http://openlayers.org/en/v3.15.1/examples/reprojection-wgs84.html and http://openlayers.org/en/v3.13.0/examples/reprojection-wgs84.html

**Comment by probins** [comment]
I'm not using Windows, so maybe this is Windows-specific?

**Comment by ptsagkis** [comment]
I have tested it with linux based machine on chrome and it works fine, so seems to be related with chrome on windows machine. Chrome 49...... on windows has the same problem. 
Tile images are comming back from server corectly but seems that chrome is confused on where to place them. Then the whole map is a mess.

**Comment by Delagen** [comment]
+1 Preview in responsive mode.
![image](https://cloud.githubusercontent.com/assets/783335/14604885/83d8e070-057e-11e6-872f-53c8e94bb136.png)

**Comment by ptsagkis** [comment]
[here is screen shot ](http://s1.postimg.org/hmzq15dtr/mapexmple.png) while viewing example --> http://openlayers.org/en/master/examples/reprojection-wgs84.html.
using chrome on windows based machine

**Comment by Delagen** [comment]
Found that canvas in ol-viewport does not use 100% of height.
Width equals to width of container, but height of canvas is original size of canvas. Due to devicePixelRatio is greater than 1 we see this effect.
Fixed this with add position:absolute to canvas in .ol-viewport context

**Comment by ptsagkis** [comment]
@Delagen are you sure we talk about the same issue????? Maybe I am missing something but the issue here is that chrome doesnt render tile images when reprojecting them using latest version of ol3.

**Comment by Delagen** [comment]
@ptsagkis may be. So my problem solved. I you still experience issues don't close issue )

**Comment by ahocevar** [comment]
This is a very strange issue. I can reproduce it with both Chrome 49 and Chrome 50 on Windows 10. The first thing I notice is that the reprojection is extremely slow (in all versions of OpenLayers). And the second thing I notice are strange rendering artefacts (maybe only in master, but might also be in older versions):

![master](https://cloud.githubusercontent.com/assets/211514/14639393/cc3172ba-063c-11e6-8c81-95c52ec1d563.png)

cc @petrsloup - can you maybe take a look at this?

**Comment by petrsloup** [comment]
The reprojection rendering is extremely slow for me in Chrome 50 on Windows 10, but I don't see any artefacts.
I'm quite sure this is some performance regression in the Chrome itself, so I did some searching and experimenting.

If I uncheck "Use hardware acceleration when available" in `chrome://settings/` ("Show advanced settings...") everything works as expected on my PC, so it seems there is some problem with the hardware acceleration.
Can anyone else confirm this workaround on another machine?

**Comment by petrsloup** [comment]
I also tried to use larger tiles for the internal reprojection (512x512 instead of the default 256x256) and the performance is much better:
http://jsfiddle.net/sgcphkg4/

**Comment by ptsagkis** [comment]
@petrsloup Just try your workaround (uncheck "Use hardware acceleration when available") and it works fine. Thanks dude.

**Comment by JelmerBaas** [comment]
Might be related to my issue. (#5251). Just updated my AMD / ATI drivers and Chrome, but still experience this issue. Firefox and IE work OK, and no other machines here have this issue.

**Comment by ahocevar** [comment]
This Chrome bug/regression should be reported. Anyone volunteering to create a good bug report with a minimal example that exposes the issue?

**Comment by JelmerBaas** [comment]
My fiddle could be used, but please let me know in that case (the overlay layer normally expires, so I have to change some things).

**Comment by petrsloup** [comment]
I was going to prepare the minimal example for reporting, but I believe the core issue is already reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=568153

There is a significant performance issue when running `drawImage` from one canvas to another with HW acceleration enabled in Chrome on Windows.

**Comment by ahocevar** [comment]
Thanks a lot for the investigation @petrsloup. I think that is indeed the issue we are facing.

**Comment by ahocevar** [comment]
Looks like that issue only covers the performance problem. We still need to investigate or report the problem that only 1 tile is rendered on Chrome/Windows with hardware acceleration enabled.

**Comment by petrsloup** [comment]
I did some more testing, but everything renders correctly for me (although it can take a while).
I suspect the internal gpu process is under heavy load and possibly times out on certain hardware/driver combination.

There's a log at the end of chrome://gpu/ diagnostics page. Can someone who can see the artefacts (/only one tile) check if the log contains something useful?

**Comment by JelmerBaas** [comment]
I doubt it's heavy-load related. I have a pretty beefy GPU here (ATI HD7950).

The chrome://gpu/ page doesn't show anything I interpret as being an issue, except:
Accelerated rasterization has been disabled, either via about:flags or command line.
Disabled Features: rasterization
Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
Disabled Features: native_gpu_memory_buffers

I attached the file, so someone can compare.

**Comment by ptsagkis** [comment]
@petrsloup is right. I have the same attitude, takes a bit to load but then it works as expected. The only differnece is that my chrome got updated to version 50.0.2661.94 m. Maybe that matters. 

This my  chrome://gpu/ page ([link here](https://gist.github.com/ptsagkis/d7619bbce1f120b51df4588ecff12ee6)) . More or less like @JelmerBaas file.

**Comment by ahocevar** [comment]
@ptsagkis, do you see the issue described in #5305?

**Comment by ptsagkis** [comment]
@ahocevar No I never had problems for non-reprojected tiles [#5305](https://github.com/openlayers/ol3/issues/5305). I have just tested without any probms for versions 3.14 -3.15. (in every test I have made, my hardware acceleration is checked). I had issues only when reprojecting tiles. But it seems with latest chrome version everything works fine. I have tested using several windows OS machines using chrome latest version and hardware acceleration checked and all of them had the same attitude --> A bit of freezing on the very beginning but then everything works as expected.

**Comment by ptsagkis** [comment]
I have just tried to stretch my graphics card and see if that has any affect. So the problems appears, no matter the latest chrome version, when my hardware graphics card is under heavy load. So propably my previous assumption (latest chrome fixes the problem) is no so correct. Just to let you know. I ll keep testing and if I come up with something intersting I ll let you know.

**Comment by ahocevar** [comment]
Maybe the same issue as #5305. See https://github.com/openlayers/ol3/issues/5305#issuecomment-218448195

**Comment by rgvassar** [comment]
I'm going to close this. It looks like it works fine now.
