### ISSUE TITLE
ol.geom.GeometryType should be exposed by the API (as the docs state)

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5241]
As stated in #3671 ol.geom.GeometryType isn't exposed as API, but I don't understand the ratio. Why shouldn't we have access to the constants (as OL3 internal code do)? They're are en important foundation for API robustness, instead of using the strings directly.
Also [the docs](http://openlayers.org/en/v3.14.2/apidoc/ol.geom.html?stableonly=true#.GeometryType) state they're available in (stable) API

**Comment by ahocevar** [comment]
Looks like you misunderstood the docs. `ol.geom.GeometryType` is not a constant, but an enumeration. The docs list the allowed values.

**Comment by giohappy** [comment]
I see... you're right.  I suggest to expose them as constants, it's a usual way of exposing this kind of enumerations.

**Comment by dbaston** [comment]
Could this be reopened as a feature request?  Comparison to strings is error-prone.

**Comment by ahocevar** [comment]
Sorry, we've made the decision to not expose enumerations to the API.
