### ISSUE TITLE
Cross-origin authenticated layers with xhr option "withCredentials"

### ISSUE THREAD

**Issue by juristr** [openlayers/ol3#5244]
Hi,

I'm having an application running under host, say, http://maps.myservice.com. Through ol3 I'm registering 3 different endpoints to overcome the usual browser connection limit:

- `a-maps.myservice.com`
- `b-maps.myservice.com`
- `c-maps.myservice.com`

Now the problem is that XHR requests don't send authentication information to the backend when they're going cross-domain, obviously (we use Kerberos authentication, not forms or basic).  
To overcome this limitation, a possible strategy is to set the `withCredentials: true` option on the xhr object. [See here for more information](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials).

**My question is** whether currently there is some possibility to augment the internal XHR object that's being used by ol3 with such custom properties.

Thx for any hint/help!

**Comment by tsauerwein** [comment]
Have you seen https://github.com/openlayers/ol3/issues/4213?

**Comment by juristr** [comment]
@tsauerwein Nope, searched the issues, but couldn't find it. But that's awesome and should definitely help :+1:. I'll verify and then close the issue, thx!

**Comment by juristr** [comment]
@tsauerwein ok, seems to work, although I'd prefer to like get an instance of an `XMLHttpRequest` object handed over by ol3 which I can then augment with custom props rather then overriding the complete implementation which forces me to handle also the association of image tiles and potentially other logic..

**Comment by ahocevar** [comment]
@juristr There is no `XMLHttpRequest` involved in fetching image tiles. It's just setting the `src` of an `Image`.

**Comment by juristr** [comment]
ah I see, thx for answering @ahocevar
