### ISSUE TITLE
Assign @api annotation to ol.source.Tile.prototype.getTilePixelRatio

### ISSUE THREAD

**Issue by zeodtr** [openlayers/ol3#5245]
Please assign @api annotation to ol.source.Tile.prototype.getTilePixelRatio() so that the function name can survive the build process. Since it plays crucial part on rendering when the pixel ratio is other than 1, without it one cannot externally implement a ol.source.Tile derived class correctly.
Maybe one can include the derived source to the openlayers source and build openlayers itself, it's overkill.

**Comment by ahocevar** [comment]
You can simply use `ol.has.DEVICE_PIXEL_RATIO` instead. Please close this issue if that works for you.

**Comment by zeodtr** [comment]
@ahocevar Thanks.

I've solved the problem (temporarily?) by explicitly assigning tilePixelRatio in the options parameter to ol.has.DEVICE_PIXEL_RATIO when invoking ol.source.TileImage.call() in the constructor of the derived class.

But on ol.renderer.canvas.TileLayer.prototype.composeFrame() it seems that the pixelRatio is determined dynamically by the frameState. So my class may not behave correctly when pixelRatio is changed on runtime.

In theory the device pixel ratio will not change, but browsers like Google Chrome has the functionality that one can change the screen resolution at any time(Ctrl +, Ctrl -). Currently it seems that Google Chrome does not change the device pixel ratio for the browser window lifetime, but I'm not sure that it would keep that behavior in future.

So, I think that it would be the best if ol.source.Tile.prototype.getTilePixelRatio() could be externally overriden. ol.source.TileWMS class uses that feature.

**Comment by ahocevar** [comment]
> But on ol.renderer.canvas.TileLayer.prototype.composeFrame() it seems that the pixelRatio is determined dynamically by the frameState. So my class may not behave correctly when pixelRatio is changed on runtime.

OpenLayers always uses `ol.has.DEVICE_PIXEL_RATIO` when it needs the pixel ratio, and that is only calculated once when the library is loaded.

**Comment by ahocevar** [comment]
On a related note, I'd be interested to hear more about your rationale behind subclassing `ol.source.TileImage`. Usually it should be enough to use that class directly, maybe with a custom `tileUrlFunction`.

**Comment by zeodtr** [comment]
@ahocevar Thanks. Then I can safely use `ol.has.DEVICE_PIXEL_RATIO`.

About rationale, my class uses different WMS URL per zoom level range. For example, for zoom level range 0~10 `http://wmsserver.com/rough/x/y/z`, while for 11~13 `http://wmsserver.com/detailed/x/y/z`. So my class' name is `PerZoomRangeTileWMSSource`.

I'm not sure this is a correct approach, but in my application there are so many layers that require this kind of functionality, so I need a place to handle this.

**Comment by ahocevar** [comment]
For the case above, your tileUrlFunction could look like this:
```js
function(tileCoord, pixelRatio, projection) {
  var z = tileCoord[0];
  return (z <= 10 ? 'http://wmsserver.com/rough/' : 'http://wmsserver.com/detailed/') +
      tileCoord[1] + '/' + (-tileCoord[2] - 1) + '/' + z;
}
```
Note that the `pixelRatio` is even passed to that function as argument, so you do not need to get it from elsewhere at all.

**Comment by zeodtr** [comment]
@ahocevar Thanks.

In my case, my tileUrlFunction would be almost identical to that of the ol.source.TileWMS, except for  the zoom level related options. While it seemed that ol.source.TileWMS.tileUrlFunction was related a lot with its internals. So what I did was as follows:

1. Copy ol.source.TileWMS (which is derived from ol.source.TileImage) source to my project directory.
2. Modify a few zoom level related details.

Sounded simple enough.

But step 2 was not at all easy because of the name mangling of OpenLayers 3 build system. TileWMS source referenced a lot of internal utility functions that were not available to the outside because of the name mangling, so I copied them too. The source code began to be somewhat bloated.

Anyways It seemed working, until the getPixelRatio() function overriding failed.

This is my story.

**Comment by ahocevar** [comment]
In your case, I would have created a LayerGroup with two WMS layers, with minResolution and maxResolution set accordingly.

**Comment by zeodtr** [comment]
@ahocevar Thank you! LayerGroup seems to be the one I've sought for. I'll try to apply it to the other cases.

**Comment by zeodtr** [comment]
@ahocevar If I implement the layer with LayerGroup, one feature will be missing. It is the 'temporary tile image borrowing from the other zoom levels'.

OpenLayers layers borrows the tile images temporarily from the tile images of the other zoom levels when the tile images of the current zoom level is not available, so that the user can see smoother zoom transition.

But since the layers in LayerGroup are the separate ones, smooth zoom transition between the zoom level boundary will not occur.

**Comment by ahocevar** [comment]
@zeodtr You might want to address this by chaining the default tileUrlFunction with your own:
```js
var originalTileUrlFunction = source.getTileUrlFunction();
source.setTileUrlFunction(function(tileCoord, pixelRatio, projection) {
  var url = originalTileUrlFunction(tileCoord, pixelRatio, projection);
  // modify url here
  return url;
});
```
