### ISSUE TITLE
Proposal: add setter to flatcoordinates to track changes

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5246]
Some interactions alterate features geometry without cloning it, consequently feature "geometry:change" doesn't fire. In this case, and when geometries are not bound to features, it would be helpful to be able to track geometry changes, which boils down to track flatcoordinates. 

Possible solutions:
**GENERIC**: Flatcoordinates don't have "set" methods, being plain arrays, so we would need setters to track changes and, eventually, emit "change" events.
This can become a performance bottleneck, a workaround could be: as soon as a listener registers for flatcoordinates changes, setter method will be used, otherwise flatcoordinates assignment could be shortcircuited to array methods (as it is now).

**THROUGH METHODS**: emit events within setter methods (setCoordinates, translate, etc.). This should be managed by the geometry class itself for specific methods, ot abstrac base class (geometry/simplegeometry/geometrycollections) otherwise.

**Comment by ahocevar** [comment]
Are you talking about `change:geometry` events on `ol.Feature`, or about `change` on `ol.geom.Geometry`?

**Comment by giohappy** [comment]
I've just grasped the change tracking system of OL3, and I see the this.changed() is always triggered by ol.geom.Geometry, so I will close this issue/proposal.
I missed one combination: when a feature geometry change "under the hoods", i.e. when the geometry is changed (ol.geom.Geometry "change" event emitted) but feature.setGeometry is called on the same geometry reference (ol.feature "change:geometry" not emitted) I cannot know what feature the changed geometry is bound to. 
I will have to manage it at a higher level, E.g. listening to ol.interaction.Translate "transaltestart" and ol.interaction.Modify "modifystart" events.
