### ISSUE TITLE
Deselection fails on vectorTileLayer when two features share the same id

### ISSUE THREAD

**Issue by JWGmeligMeyling** [openlayers/ol3#5248]
When I use an `ol.interaction.Select` on a  `ol.layer.VectorTile`, and have a feature that is split up between two tiles, and then select both of these feature segments, and clear (parts of) my selection containing this feature, the selection tool fails with the following error:

```
Uncaught AssertionError: Assertion failed: featureKey exists in featureChangeKeys 
```

The stack trace is:
```
goog.debug.Error (.point…bundle.js:2881)
goog.asserts.AssertionError (.point…bundle.js:4580)
goog.asserts.doAssertFailure_ (.point…bundle.js:4637)
goog.asserts.assert (.point…bundle.js:4667)
ol.source.Vector.removeFeatureInternal (.point…undle.js:72610)
ol.source.Vector.removeFeature (.point…undle.js:72598)
(anonymous function) (.point…undle.js:72161)
goog.events.EventTarget.fireListeners (.point…undle.js:12722)
goog.events.EventTarget.dispatchEventInternal_ (.point…undle.js:12819)
goog.events.EventTarget.dispatchEvent (.point…undle.js:12634)
ol.Collection.removeAt (.point…undle.js:24129)
ol.Collection.pop (…undle.js:24083)
ol.Collection.clear (.point…undle.js:23992)
ol.interaction.Select.handleEvent (.point…ndle.js:113046)
ol.Map.handleMapBrowserEvent (.point…undle.js:83997)
goog.events.EventTarget.fireListeners (.point…undle.js:12722)
goog.events.EventTarget.dispatchEventInternal_ (.point…undle.js:12819)
goog.events.EventTarget.dispatchEvent (.point…undle.js:12634)
(anonymous function) (.point…undle.js:49610)
```

* Is splitting up features across tile layers, and leaving them with the same id, wrong?
* Is `ol.interaction.Select` supported for `ol.layer.VectorTile`?
* Or: is this an edge case problem for `ol.interaction.Select`?

**Comment by ahocevar** [comment]
> Is splitting up features across tile layers, and leaving them with the same id, wrong?

It is not wrong, but it prevents you from using `ol.interaction.Select`.

> Is ol.interaction.Select supported for ol.layer.VectorTile?

Yes, if you use `ol.Feature` (and not `ol.RenderFeature`) features, and if you do not have the same feature ids in different tiles.

> Or: is this an edge case problem for ol.interaction.Select?

Yes. The primary purpose of vector tiles is rendering. You can use `map.forEachFeatureAtPixel` to get interactivity.

**Comment by JWGmeligMeyling** [comment]
Would it be possible to modify ol.interaction.Select in such a way that this would become possible? And would a PR for that have any chance of being merged?

**Comment by ahocevar** [comment]
Can't you use `ol.Map#forEachFeatureAtPixel` instead? Remember:

>  The primary purpose of vector tiles is rendering.

What you could do is something like
```js
var selectedId;
vectorTileLayer.setStyle(function(feature, resolution) {
  return feature.getId() == selectedId ? selectedStyle : defaultStyle;
});
map.on('singleclick', function(e) {
  var feature = map.forEachFeatureAtPixel(e.pixel, function(feature) {
    return feature;
  });
  selectedId = feature ? feature.getId() : undefined;
});
```

**Comment by JWGmeligMeyling** [comment]
That seems indeed a better option than what I was thinking of. I will try that approach, thanks!

**Comment by ahocevar** [comment]
Can we close this @JWGmeligMeyling?

**Comment by JWGmeligMeyling** [comment]
I was trying to resolve this issue. I do however still have no clue why the feature is removed twice internally. Seems to me that the id's are unique and that the code should just work, even with the same feature on two tiles. I ended up with disabling the assertion and now it works just fine... But there should be a cleaner work around. I was however unable to make sense of the stack and see where the removals came from, the structure with the collection in a source triggering an event that triggers a remove in another thing was not completely transparent to me. If you could give me a pointer I am defenitely willing to look further but yes we can close this issue 😄

**Comment by ahocevar** [comment]
See http://jsfiddle.net/8a4wqtjc/2/ @JWGmeligMeyling, which implements my suggestion from above. You can click on a building there to select it. If you click one that spans multiple tiles, all parts will be selected because they share the same id.

**Comment by shaunakv1** [comment]
@ahocevar: I think I am running to the same issue here, but could be wrong.  I am loading a point layer using tile loading strategy. 

Here's my code snippet: 

```
selectInteraction = new ol.interaction.Select({
     condition: ol.events.condition.click
});
selectInteraction.on('select', function(e) {
     console.log( e.target.getLayer());  
});
map.addInteraction(vm.selectInteraction);
```

This Throws an error 42: 

`Expected an ol.Feature, but got an ol.RenderFeature.`

I understand your explanation above of why this happens, but it still feels like a bug in the API because users would naturally expect this to work.  It does work fine if I use click event on map, and search it by the pixel, but then I loose the convenience of an select interactions. 

Any suggestions?

**Comment by ahocevar** [comment]
This is actually a different issue @shaunakv1. `e.target.getLayer()` in your application is incorrect. The `getLayer()` method needs to be called with a feature as argument. The assertion is misleading, and that is a bug, which I just ticketed as #5958.
