### ISSUE TITLE
Documentation ol.style.Icon, getAnchor() wrong?

### ISSUE THREAD

**Issue by dnlkoch** [openlayers/ol3#5253]
It seems to me, that the documentation for the method [getAnchor()](http://openlayers.org/en/master/apidoc/ol.style.Icon.html#getAnchor) in `ol.style.Icon` is wrong as it says:
> (...) Its units are determined by anchorXUnits and anchorYUnits.

But the [implementation](https://github.com/openlayers/ol3/blob/a81150508dd1f15ab4dd99ee1ef6f748a33a37fd/src/ol/style/iconstyle.js#L206) always returns the normalized anchor (in pixel units).

I'd be willing to provide a PR fixing this, if you agree with the above.

**Comment by marcjansen** [comment]
ISTM you are right, @dnlkoch. Thanks for noticing this and we would be happy if you could provide us with a documentation enhancement.
