### ISSUE TITLE
Add finishFunction to ol.interaction.Draw

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5260]
My proposal is to add finishFunction  to ol.interaction.Draw options to let the user have the last word before finishDrawing is called. AFAICS there's no other mean to stop finishDrawing after _atFinish has been called, i.e. when a potential coordinate is spot during pointer up handling.

finishFunction would be called only is _atFinish returns true, and it will be passed the pointer event. If it returns true the finishDrawing will be called otherwise the dragging continues.

I have already submitted a PR (#5258) for this. I'm sorry for having missed the contibution guidelines before...

**Comment by giohappy** [comment]
Just to add some context here it is my use case. I have to digitize linestrings with a constraint: its extreme vertexes must be coincident to some specific points. You can think to ways that must snap to junctions.
I can verify it while digitizing using a custom geometryFunction, but I have no way to prevent a double click to finish the drawing.  
Do I miss an alternative solution?

**Comment by ahocevar** [comment]
Currently, there is a `condition` that you can configure to decide whether to draw a vertex or not. If you need special handling for the last vertex (which I can see some justification for), a useful counterpart would be a `finishCondition`. Your pull request's `finishFunction` is already called with the right argument, but I'd really rename it to `finishCondition`.

**Comment by giohappy** [comment]
Ok, I will chance the function name and squash the commits to cleanup thd PR

**Comment by giohappy** [comment]
New clean PR #5261
