### ISSUE TITLE
new ol.Map initialize error on Android4.2

### ISSUE THREAD

**Issue by katsu-sakamoto** [openlayers/ol3#5263]
Error has occurred on the Android4.2.
In Version 3.14.0 or later.

v3.13.1 initialize success.
v3.14.0 initialize error(script error).

**Comment by ahocevar** [comment]
You need to load polyfills for XMLHttpRequest and Function.prototype.bind before loading OpenLayers.

**Comment by katsu-sakamoto** [comment]
I tried very simple exsample of just displaying the map.
But script error occurs on Android4.2.

Like this)
http://openlayers.org/en/v3.15.1/examples/attributions.html

**Comment by katsu-sakamoto** [comment]
http://openlayers.org/en/v3.15.1/doc/quickstart.html

Quick Start > Put a map on a page

This basic sample code is not work on Android4.2.

**Comment by ischas** [comment]
Try adding this polyfill: `<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList"></script>`

I guess the polyfill should be added to the quickstart.

**Comment by katsu-sakamoto** [comment]
I try adding polyfill.
But script error occurs on Android4.2.

```
<!doctype html>
<html lang="en">
  <head>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList"></script>
    <link rel="stylesheet" href="http://openlayers.org/en/v3.15.1/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="http://openlayers.org/en/v3.15.1/build/ol.js" type="text/javascript"></script>
    <title>OpenLayers 3 example</title>
  </head>
  <body>
    <h2>My Map</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.MapQuest({layer: 'sat'})
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([37.41, 8.82]),
          zoom: 4
        })
      });
      alert("success");
    </script>
  </body>
</html>
```

Script stoped before alert Line.

**Comment by katsu-sakamoto** [comment]
This error reproduce in the emulator of the Android Studio.

**Comment by fredj** [comment]
Try to add the `Function.prototype.bind` in the polyfill (as suggested earlier by @ahocevar)

**Comment by katsu-sakamoto** [comment]
Android4.2 has Function.prototype.bind.

alert(Function.prototype.bind)

Android4.2 alert message was "function bind() {[native code]}".

I think that it is another cause.

**Comment by ahocevar** [comment]
Can anyone reproduce this and provide a stack trace?

**Comment by katsu-sakamoto** [comment]
```
<!doctype html>
<html lang="en">
  <head>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList"></script>
    <link rel="stylesheet" href="http://openlayers.org/en/v3.15.1/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="http://openlayers.org/en/v3.15.1/build/ol.js" type="text/javascript"></script>
    <title>OpenLayers 3 example</title>
  </head>
  <body>
    <h2>My Map</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
  try {
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.MapQuest({layer: 'sat'})
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([37.41, 8.82]),
          zoom: 4
        })
      });
  }
  catch(e) {
      console.log(e.stack);
  }
      alert("success");
    </script>
  </body>
</html>

```

This console.log message.

TypeError: Object [object DOMWindow] has no method 'requestAnimationFrame'
  at R.render (http://openlayers.org/en/v3.15.1/build/ol.js:405:469)
  at R.Ck (http://openlayers.org/en/v3.15.1/build/ol.js:405:344)
  at R.c (http://openlayers.org/en/v3.15.1/build/ol.js:23:1491)
  at R.<anonymous> (http://openlayers.org/en/v3.15.1/build/ol.js:25:902)
  at Nb (http://openlayers.org/en/v3.15.1/build/ol.js:27:548)
  at R.set (http://openlayers.org/en/v3.15.1/build/ol.js:28:69)
  at R.<anonymous> (http://openlayers.org/en/v3.15.1/build/ol.js:28:122)
  at new R (http://openlayers.org/en/v3.15.1/build/ol.js:397:12)

**Comment by ahocevar** [comment]
Looks like you're not getting the correct polyfill with https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame. Maybe try a [different polyfill](https://rawgit.com/paulirish/1579671/raw/682e5c880c92b445650c4880a6bf9f3897ec1c5b/rAF.js) instead.

**Comment by katsu-sakamoto** [comment]
It's work!

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame"></script>`
typeof window.requestAnimationFrame is undefined.

`<script src="rAF.js"></script>`
typeof window.requestAnimationFrame is function and map displayed!

It was found "polyfills" problem.

ahocevar san.
Thank you for your support!
