### ISSUE TITLE
ol.colorlike - Page not Found

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#5265]
If you open http://openlayers.org/en/master/apidoc/ol.style.Fill.html there's a link to[ `ol.colorlike`](http://openlayers.org/en/master/apidoc/ol.colorlike.html) but it's 404.

Maybe it should point to http://openlayers.org/en/master/apidoc/ol.html#.ColorLike?

**Comment by jonataswalker** [comment]
@fredj Would you tell me how to link to http://openlayers.org/en/master/apidoc/ol.html#.ColorLike?

Is it something like `ol#.ColorLike`?

**Comment by ahocevar** [comment]
See #5266.

**Comment by jonataswalker** [comment]
Great @ahocevar. Closing then.
