### ISSUE TITLE
geolocation and device orientation examples broken

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5276]
The examples are broken on Chrome >= 50 because they are running on insecure origin.
To fix this issue, http://openlayers.org/ must run on HTTPS

**Comment by ahocevar** [comment]
See isaacs/github#156.

**Comment by dddesign** [comment]
I updated my android to 6.0.1 and geolocation is not working since then (chrome 50.0.2661.89, I don't know the version before). it's not working for the latest geolocation example on openlayers.org and also not on openlayer v3.11.1 which I use for my webapp rraaddaarr.com/firepit
do I have to run all on https (so I need to download all js of openlayers etc. to my server)? or is there another way or a bug fix in ol js?

**Comment by ischas** [comment]
This issue is independent from OL. Chrome doesn't give geolocation information to non-HTTPS-applications anymore. There is no fix but switching to HTTPS.

**Comment by dddesign** [comment]
I see, thanks.
So I switched all to HTTPS (with let's encrypt cert).
It would be great if openlayers.org could be accessibly by HTTPS to get js and css.

**Comment by ischas** [comment]
How about this CDN: https://cdnjs.com/libraries/ol3

**Comment by probins** [comment]
I don't think this issue should be closed. I'm not entirely convinced by 'https everywhere', but Google and others are, and are gradually introducing restrictions like this. So, if Github Pages can't/won't support https fully, then it would be better either to move openlayers.org elsewhere (I'm currently experimenting with Gitlab Pages), or to use a front-end like Cloudflare.

**Comment by ahocevar** [comment]
@probins Sorry, I thought this was a duplicate, but realised just now that it isn't. Reopening.

**Comment by bartvde** [comment]
https://github.com/blog/2186-https-for-github-pages

**Comment by probins** [comment]
I don't think that helps @bartvde because (AFAIK) it only covers the subdomains of github.io, not custom domains

**Comment by ahocevar** [comment]
Correct. See https://help.github.com/articles/securing-your-github-pages-site-with-https/: "HTTPS is not supported for GitHub Pages using custom domains."

Screenshot from our site's settings page:
<img width="634" alt="untitled" src="https://cloud.githubusercontent.com/assets/211514/15907397/5584bbe2-2dbd-11e6-9d0c-618e3cdc4a2b.png">

**Comment by bartvde** [comment]
ah hadn't seen that
