### ISSUE TITLE
Remove vertex programmatically during ol.interaction.Modify

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5281]
With ol.interaction.Draw.removeLastPoint() I'm able to handle a key event to let the user remove the last drawn point.
I would like to obtain something similar with ol.interaction.Modify. What about exposing removeVertex_ publicly?

**Comment by ahocevar** [comment]
+1 on exposing `removeVertex_`. For consistent naming, I'd expose it as `removePoint`.

**Comment by giohappy** [comment]
I will provide a PR soon.

**Comment by giohappy** [comment]
MODIFYSTART/MODIFYEND events are triggered by handleEvent before/after removeVertex_, but I cannot trigger this events from outside a pointer handler because I miss the mapBrowserEvent. 
Therefore If ol.interaction.Modify.removePoint() is called programmatically MODIFYEND won't be triggered. It's ok for me, but I'm not sure if it's ok for everyone.

**Comment by ahocevar** [comment]
You'll need to do more work anyway than just exposing `removeVertex_` as `removePoint`. You will have to cache the pointer event and also make sure that `willModifyFeatures_` is called, so you will also be able to trigger the events properly.

**Comment by giohappy** [comment]
Yes, that's what I was doing. I'm analyzing the right position to cache/uncache the event.

**Comment by giohappy** [comment]
PR #5288

**Comment by bjornharrtell** [comment]
@ahocevar just a friendly reminder that you can close this issue now as #5288 is merged.
