### ISSUE TITLE
Once event being removed early causing an error

### ISSUE THREAD

**Issue by oukjweather** [openlayers/ol3#5282]
ol.events.unlistenByKey function is not taking into account pending removals created by key.target.removeEventListener. As a result when it does a splice to remove an event, the parameters of the for loop in the function ol.events.EventTarget.prototype.dispatchEvent are changed. This creates an error on the last iteration where ii is greater than the actual number of listeners. As a result an attempt is made to call a undefined listener at the end of the loop. The removal of the event should wait till the for loop is completed as would seem to be the purpose of the pendingRemovals variable. From my quick glance of the code, the root of the problem would seem to be in the ol.events.unlistenByKey function not taking into account pending removals properly.

**Comment by ahocevar** [comment]
Would you be able to provide a test case that shows the issue?

**Comment by oukjweather** [comment]
Certainly. This should do it.

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <link rel="stylesheet" href="http://openlayers.org/en/v3.15.1/css/ol.css" type="text/css">
    <script src="http://openlayers.org/en/v3.15.1/build/ol-debug.js"></script>
  </head>
  <body>
    <div class="container"> 
          <div id="map" class="map"></div>
    </div>
    <script>

        set_feature_id = function (feature) {
            if(!feature.getId() && feature.get('future_ID')) {
                feature.setId(feature.get('future_ID'));
            }
            feature.set('style', true);
        };

        var source = new ol.source.Vector({
            projection:'EPSG:900913'
        });
        source.once('change', function (event) {
            source.forEachFeature(set_feature_id, this);
            console.log('do something once...');
        }, this);
        source.on('change', function (event) {
            console.log('do something over and over again...');
        }, this); 
        var vector_layer = new ol.layer.Vector({
            source: source
        });
    

        var map = new ol.Map({
            layers: [
        new ol.layer.Tile({
            style: 'Road',
            source: new ol.source.MapQuest({layer: 'osm'}),
            resolutions: [156543.03390625, 78271.516953125, 39135.7584765625,
                19567.87923828125, 9783.939619140625, 4891.9698095703125,
                2445.9849047851562, 1222.9924523925781, 611.4962261962891,
                305.74811309814453, 152.87405654907226, 76.43702827453613,
                38.218514137268066, 19.109257068634033, 9.554628534317017,
                4.777314267158508, 2.388657133579254, 1.194328566789627,
                0.5971642833948135, 0.25],
            serverResolutions: [156543.03390625, 78271.516953125, 39135.7584765625,
                19567.87923828125, 9783.939619140625,
                4891.9698095703125, 2445.9849047851562,
                1222.9924523925781, 611.4962261962891,
                305.74811309814453, 152.87405654907226,
                76.43702827453613, 38.218514137268066,
                19.109257068634033, 9.554628534317017,
                4.777314267158508, 2.388657133579254]
        }),
        vector_layer
            ],
  target: 'map',
  view: new ol.View({
    center: [0, 0],
    zoom: 2
  })
});

        var features = []; 
        
        feature1 = new ol.Feature({
            geometry: new ol.geom.Point(ol.proj.transform([-96, 36], 'EPSG:4326', 'EPSG:900913'))
        });
        feature1.set('future_ID', 'location1');
        
        feature2 = new ol.Feature({
            geometry: new ol.geom.Point(ol.proj.transform([-97, 36], 'EPSG:4326', 'EPSG:900913'))
        });
        feature2.set('future_ID', 'location2');
             
        
        features.push(feature1);
        features.push(feature2);
        source.addFeatures(features);
    </script>
  </body>
</html>

**Comment by ahocevar** [comment]
Can you put this in a JSFiddle and provide some explanation on how to trigger the bug? Thanks.

**Comment by oukjweather** [comment]
Here is the jsfiddle: https://jsfiddle.net/gpwL4ztv/1/

No idea if it is working correctly in there or not. I'm not familiar with JS fiddle enough to know what is going on with it. Certainly willing to learn more about it if you have any pointers. The error occurs with the  initial execution of the code. From the scope of the JS fiddle, the error occurs with the execution of line 68: "source.addFeatures(features);"

**Comment by ahocevar** [comment]
Thanks for the good bug report and the test case. The problem should be fixed with #5291.
