### ISSUE TITLE
New Feature: BBox Interaction

### ISSUE THREAD

**Issue by tbarsballe** [openlayers/ol3#5283]
I was working on a project using OL3, and wound up making this interaction. I figgured it might be sufficiently useful to others that I could try and contribute it to the OL3 project.
(code is here if anyone wants to take a look: https://github.com/tbarsballe/ol3/blob/bboxinteraction/src/ol/interaction/bboxinteraction.js)

**Use case**: Selecting a bbox/extent on a map.
More advanced than the existing ol.interaction.dragboxinteraction
Similar to ol.interaction.modify interaction, but constrained to a rectangle shape.

While the interaction is active, you can draw a box by clicking and dragging
Unlike the `dragboxinteraction`, the box will remain visible on the map
You can resize the box by clicking and dragging a vertex or an edge (this will affect adjacent vertices as appropriate).
Like the `modifyinteraction`, the cursor will snap to the box when you are able to interact with it.
Clicking outside the bbox will remove it. Clicking and dragging will create a new bbox.

**Comment by ahocevar** [comment]
Nice @tbarsballe. I have seen feature requests for something like this already. I'd only call it `ol.interaction.Extent`, because we haven't used the term BBox in OpenLayers so far. Pull request welcome.

**Comment by tbarsballe** [comment]
PR (with BBox renamed to Extent) here: https://github.com/openlayers/ol3/pull/5290

**Comment by fredj** [comment]
fixed with #5290
