### ISSUE TITLE
mapguide3.0 WFS openlayers3 GML3

### ISSUE THREAD

**Issue by boyucjz** [openlayers/ol3#5292]
<gml:posList>-87.714582 43.764863</gml:posList> 在openlayers3中，调用mapguide3.0.0 的WFS服务，在openlayers3中无法正常显示，经过测试，发现生成的GML3信息中的经纬度信息中的坐标顺序与标准不一致。应该先输出纬度坐标，再输出经度坐标。请问如何处理？谢谢。

**Comment by ahocevar** [comment]
What projection are you using? When the GML is in EPSG:4326, the order is [latitude, longitude]. When it is in CRS:84, the order is [longitude, latitude]. So you may want to play with projection settings. If you provided the relevant portions of your code, we could even tell you where exactly. And it would be easier if you'd write in English.

**Comment by boyucjz** [comment]
thank you!   我当时用的是EPSG:4326。
