### ISSUE TITLE
What's the purpose of componentSegments object inside ol.interaction.Modify.handleDownEvent_ ?

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5294]
It seems that [this object](https://github.com/openlayers/ol3/blob/master/src/ol/interaction/modifyinteraction.js#L565) is never used. It's only created and populated inside the if / else if statements, which are mutually exclusive.

**Comment by ahocevar** [comment]
Not sure what you mean. The `componentSegments` are used in the for loop that walks through all segments of all features, and is used inside that for loop a lot.

**Comment by giohappy** [comment]
Sorry, I misread a line of code. It's cleat now
