### ISSUE TITLE
getFeaturesAtCoordinate returns false for ol.geom.Point because constainsXY is falsy

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5295]
I wonder why containsXY is not implemented for ol.geom.Point. From a logical point of view I would expect ol.source.Vector.getFeaturesAtCoordinate to return the matching features. They're found indeed by the internal featuresTree but then they aren't returned [here](https://github.com/openlayers/ol3/blob/master/src/ol/source/vectorsource.js#L465) because ol.geom.Point.containsXY is falsy (it's the base ol.geom.Geometry.containsXY function).

**Comment by ahocevar** [comment]
The RTree only does a bounding box match, not an exact geometry match.

Maybe you are looking for pixel exact hit detection? In that case `ol.Map#forEachFeatureAtPixel()` is your friend.

**Comment by giohappy** [comment]
No, I cannot use `ol.Map#forEachFeatureAtPixel()` because my features lie beyond the viewed portion of the map, and they wouldn't be hit by the hit detection mechanism.
What I'm saying is that `ol.source.Vector#getFeaturesAtCoordinate()` works fine, but it doesn't return simply because `ol.geom.Point#containsXY()` is not implemented. The same would happen for linestrings.

The SF Specification is meant to work for points and linestrings too, as in SQL ST_Contains, thus I think containsXY could be implemented for points and linestrings too.

In the meanwhile I'm using `ol.source.Vector#getFeaturesInExtent()` with a micro buffer around my coordinate...

**Comment by ahocevar** [comment]
For `ol.geom.Point`, it should be straightforward, tight?
```js
ol.geom.Point.containsXY = function(x, y) {
  retrurn this.flatCoordinates[0] == x && this.flatCoordinates[1] == y;
};
```
Or am I missing something?

**Comment by giohappy** [comment]
Yes, I was just asking if there was a reason of it not being implemented.
If it's ok to do it I will implement it both for points/multipoints and linestrings/multilinestrings

**Comment by ahocevar** [comment]
For linestrings, you should be able to use `getClosestPoint`. Should be straightforward too.

**Comment by giohappy** [comment]
I would rather implement something like ol.geom.flat.contains.xy which is a generic way to check if any coordinate in flatcoordinates is the same as the searched one.
closestPoint would give false positives.

**Comment by ahocevar** [comment]
I haven't checked the simple features spec, but if contains means only actual vertices and not points on a segment, then you're right.

**Comment by giohappy** [comment]
If we want to follow the sf spec it wouldn't be ok, and in case of linestrings we should also exclude the starting and ending vertices, because they're the boundary of the linestring while contains considers only the interior.
In this case we should have an intersectsXY too to consider the boundary too (and touchesXY if we want to exclude the interior).
I will close this issue for the moment and I will reopen another one later for a wider discussion on spatial relations.

**Comment by ahocevar** [comment]
Also keep in mind that OpenLayers was designed to work well with Turf or JSTS.

**Comment by giohappy** [comment]
Yes, I'm altresì already using both. Probably OL shouldn't replicate spatial relations operators as defined by the spec. They're already covered, e.g., by JSTS.
ContainsXY can be considered as an "intersects a given coordinate" wherever it's located (boundary or interior).

**Comment by jbelien** [comment]
Hello @giohappy ,

I'm having the same issue as you mentionned here :
> No, I cannot use `ol.Map#forEachFeatureAtPixel()` because my features lie beyond the viewed portion of the map, and they wouldn't be hit by the hit detection mechanism.

Did you find a solution for this issue ?

Thanks a lot.
