### ISSUE TITLE
Make typedefs compatible with modular structure

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5299]
As discussed in #5226 and briefly in https://github.com/openlayers/ol3/issues/4128#issuecomment-201858324, currently typedefs are defined as part of the `ol` namespace in source files, some of them with a `goog.provide`. Some of them are also `goog.require()`d in source files that refer to them. Typedefs are however only used by the compiler with type checking (and also for reference in the docs), so are not really part of the source code. They are also never assigned a value, and so are not namespaces and are not part of the dependency structure. So they do not need a `goog.provide`, nor is a `goog.require` needed when the types they define are referred to in the code.

So the proposal is to change this as part of the move away from global namespaces towards standard modules. I see 2 distinct phases to this:

- [x] move the typedefs out of the source files, and into a separate `typedefs.js` file, removing any `goog.provide`, and also any `goog.require` referring to them.
- [x] deal with `ol.vec.Mat4.Number` - see #5138

There is a third task, which is to remove the `ol` namespace structure from their names, for example, `ol.AttributionLike` would become just `AttributionLike`. This would not affect people using the supplied builds or those creating a custom build, as apps don't refer to the types. It might however affect someone compiling code together with the library, as their code might refer to these types. So this step can be left until conversion to ES6 modules.

I'll draw up a PR to tackle the first task, and report back if I find any further issues. ~~As a side effect, I believe this will also fix #4945, as the typedefs will no longer rely 'on types defined throughout the library', but be collected in one file that is always included in builds. I will also test this.~~  (Crossed out, as doesn't fix problem.)

**Comment by gberaudo** [comment]
Thanks @probins for going forward on this issue.

A small precision: typedefs are not only in the `ol` namespace but also in subnamespaces, like for example `ol.interaction.DrawGeometryFunctionType`.

I think it is better to keep the typedef symbols unchanged (no phase 2). It would avoid:
- conflicts with javascript;
- conflicts between symbols from different subnamespaces;
- API breakage: all uses of the typedefs would have to be changed in client code.

Regarding phase 1, it will greatly simplify dependency management and I think it is a good move.

**Comment by probins** [comment]
ok, [here's](https://github.com/openlayers/ol3/compare/master...probins:typedefs) my preliminary PR diff. Ignore the travis.yml change, which is just to get Travis to run on my branch; this won't be in the actual PR. This diff moves the typedefs to `typedefs.js`, and removes all the associated `goog.provide`s and any `goog.require`s of these typedefs, in the code and also in the tests. I have put them in alpha sequence, which they weren't always in the original.

I found when compiling the examples that `typedefs.js` also needs to create the sub-namespaces to prevent not found errors when application code is compiled with the library. For example, the examples do not use `ol.raster`, so defining `ol.raster.Operation` creates an error. I was assuming we would remove the namespace structure in this file as everywhere else, and replace `ol.interaction.DrawGeometryFunctionType` perhaps with `interactionDrawGeometryFunctionType`. However, it might be better to maintain the current structure as @gberaudo suggests, and use the `namespace = namespace || {}` pattern throughout; this has the extra advantage of being less work 😄 

I encountered 2 problems:
* a minor one: moving ol.Extent leads to:
<br>src/ol/format/ogc/filter.js:373: ERROR - assignment to property extent of ol.format.ogc.filter.Bbox
<br>ERR! compile found   : (Array<number>|null)
<br>ERR! compile required: Array<number>
<br>I got around this by removing '!' (non-nullable) from lines 353 and 371. I have no idea why the compiler's behaviour should change here, but removing '!' seems like an acceptable fix.
* the more serious one is moving ol.events.EventTargetLike. This produces 103 errors, such as:
<br>  src/ol/tilequeue.js:91: ERROR - actual parameter 1 of ol.events.unlisten does not match formal parameter
 <br> ERR! compile found   : ol.Tile
  <br>ERR! compile required: (EventTarget|null|{
  <br>ERR! compile   addEventListener: function (string, (Function|null), boolean=): ?, 
  <br>ERR! compile   dispatchEvent: function (string): ?, 
  <br>ERR! compile   removeEventListener: function (string, (Function|null), boolean=): ?
  <br>ERR! compile })
  <br>ERR! compile     ol.events.unlisten(tile, ol.events.EventType.CHANGE,
<br>So the compiler seems to think that ol.events.EventTarget is null. Again, I have no idea why this is happening, and have left this in events.js until someone can tell me what needs fixing where.

A couple of other minor observations:
* framestate.js contains 2 typedefs which I moved, plus a FIXME comment. This seems out of date, as the 2 vars referred to don't seem to be used anywhere, so I removed this file completely
* `ol.TileCoordTransformType` in tileurlfunction.js doesn't seem to be used anywhere. I have copied this to `typedefs.js`, but it may be that this can be deleted.
* I have left vec.mat4 as this is pending goog replacement (#5138) and changing it here would create a merge conflict. This can be moved later when 5138 is merged
* a minor point, but wouldn't ol.source.ImageOptions/SourceOptions/TileOptions/UrlTileOptions be better in olx?
* source.urltilesource.js has require(ol.proj) which is not used (except in options), so I removed this

I generated the API docs and all looks ok. I can push this dir to the web for inspection if people like.

**Comment by gberaudo** [comment]
Thanks @probins for the detailed report. I tried your branch but with a simple `make check` it does not compile (due to the `namespace = namespace || {}` trick).

I removed the `||` from `typedefs.js` and tried to get `make check` and `make compile-example` work without error.

>  minor one: moving ol.Extent leads to: 

This issue is rather strange. To avoid changing the function signature, it is possible to add a (surnumerous) `goog.asserts.assert`. This makes the compiler happy.

> the more serious one is moving ol.events.EventTargetLike. This produces 103 errors, such as: 

Closure does not like that typedefs.js is passed as the last file. Creating a second typedef file and including it before everything else makes the compilation pass (with some warnings). This needs more investigation.

See my branch at https://github.com/gberaudo/ol3/tree/typedefs.

**Comment by probins** [comment]
> with a simple make check it does not compile

don't understand that. I ran it through several different builds, and also ci on Travis and it all compiles without problem. ci runs `build`, which runs the same build as `make check`, so I don't understand why you would get errors with `make check`. The problem with your proposed changes to the namespace check is that this will only work for the specific case of compiling the examples. Other cases where people compile code with the library may not use other sub-namespaces which will similarly not be defined.

> This issue is rather strange

indeed :-). If your proposed addition of a `goog.assert` solves the issue, that's fine - but I don't understand why!

Similarly for the 2 typedefs file solution. I too tried passing the typedefs file as the first file, but this gave a lot of warnings. Maybe I should try with the new `dependency_mode` flag instead of `manage_closure_dependencies` and see if that makes any difference. The compiler is probably making assumptions about the order files are in which aren't being met in this case, or some similar problem.

**Comment by probins** [comment]
> it all compiles without problem

correction. It compiles without _error_, but does produce a whole pile of warnings due to the `namespace ||` thingy. I just checked that Travis finished ok, and didn't bother scrolling down for warnings. I'll push a revised version that doesn't produce warnings, and will have to think some more about how to cater for those compiling their code with the library.

**Comment by probins** [comment]
ok, revised version which compiles without warnings. [Travis report](https://travis-ci.org/probins/ol3/builds/127320341). This is just a hack to get it to compile; will have to think some more about the namespace issue.

**Comment by gberaudo** [comment]
>> with a simple make check it does not compile

> don't understand that. I ran it through several different builds, and also ci on Travis and it all compiles 

I tried your changes and it didn't compiled until I cleaned and `rm -rf node_modules`. Then it compiles without error or warning.

Then I tried compiling an individual example but I got this error: 
```
make  build/compiled-examples/simple.combined.js
node tasks/build.js build/compiled-examples/simple.json build/compiled-examples/simple.combined.js
info ol Parsing dependencies
info ol Compiling 311 sources
ERR! compile src/ol/typedefs.js:379: ERROR - Property WKT never defined on ol.format
ERR! compile ol.format.WKT.Token;
ERR! compile           ^
ERR! compile 
ERR! compile 
ERR! compile 
ERR! compile 1
ERR! compile  error(s), 0 warning(s), 
ERR! compile 96,9
ERR! compile % typed
```

**Comment by probins** [comment]
yes, this is the problem with these sub-namespaces; that's why I added the `namespace || {}`, but this doesn't work because these typedefs are a form of dependency. Even though I add `typedefs.js` at the end, the compiler sees that they're needed by the files that refer to them, so moves `typedefs.js` to the front. This means that the sub-namespace is being created in `typedefs.js` before it's used/created by `goog.provide`. ATM I don't see any way round this other than to remove the namespaces from the typedef names, so the 2nd part of my previous post. As a temporary measure, we could leave the typedefs in the respective files to maintain bc for those compiling code with the library, warning people in the release notes that the namespaces will be removed in a later release. I think this is similar to what you're proposing for enums.

**Comment by probins** [comment]
> we could leave the typedefs in the respective files

this is only necessary for the sub-namespaces. Typedefs in the `ol` namespace can remain in `typedefs.js`.

**Comment by probins** [comment]
> As a temporary measure, we could leave the typedefs in the respective files to maintain bc

alternatively, we could have duplicate typedefs, one without the sub-namespace(s) in `typedefs.js`, and one with the sub-namespace in each file as at present. References within the code can be changed to the one in `typedefs.js`, so the ones in each file are purely for bc for those compiling their code with the library. Encourage the latter in the release notes to also rename the type references in their code, with a warning that the defs with the sub-namespaces will disappear when the code is converted to modules. I think that should work. I'll experiment with this.

We can probably do something similar for the enums.

**Comment by gberaudo** [comment]
I don't think the compiler actually moves the typedefs.js front, because there would be an error with the `ol` namespacel, which is not defined in `typedefs.js`. When compiling a single example, the files which are not required by the example are not passed to the compiler and the namespaces (and symbols) are not created. The `ol` namespace is required by some files so is defined, but the `ol.format` or `ol.format.WKT?` namespace is not required so not defined.

> alternatively, we could have duplicate typedefs, one without the sub-namespace(s) in typedefs.js, and one 

Not enthousiastic about this.

A possibility might be to move all typedefs to a dedicated hierarchy, like `olx` and `oli`: `olt.XX` however it would completly break backward compatiblity.

We can also try moving the typedefs to their namespaces (no typedefs.js), like you suggest. But contrary to what you propose, I would just keep the typedefs there and not display warnings or change the symbols afterwards.

The last possiblity I see is to keep the typedefs where they are now and only remove the goog.provide if it conflicts with a future goog.module declaration.

**Comment by probins** [comment]
the `goog.provide`s and `goog.require`s can be removed anyway - they're not needed.

**Comment by probins** [comment]
https://github.com/openlayers/ol3/compare/master...probins:toplevel-typedefs is a new branch which only moves the 'top-level' typedefs, and leaves the others where they are for the moment. So this:
* moves all the top-level typedefs to `typedefs.js`
* removes all the `goog.provide`/`goog.require` for all typedefs
* incorporates @gberaudo's suggestion for adding a `goog.assert` to get round the `ol.Extent` problem previously mentioned

Although this does not handle the non-top-level typedefs, IMO this already considerably simplifies the code. So any reason why this can't be put in a PR? Travis approves.

**Comment by probins** [comment]
forgot to mention 2 small exceptions. `raster/pixel` only contains a typedef, so needs a `goog.provide` to get through Closure-util; `raster/operation` without a `goog.provide` gets through the full build but for some reason the example compile fails, so I added a `goog.provide` there too. It might be better to combine these 2 files into `ol/raster.js`, which would also remove the need for `raster.jsdoc`.

**Comment by probins** [comment]
> A possibility might be to move all typedefs to a dedicated hierarchy, like olx and oli: olt.XX however it would completly break backward compatiblity.

as I noted before, ol.source.ImageOptions/SourceOptions/TileOptions/UrlTileOptions could be moved to olx. Debatable whether this is part of the api or not (and so needs to be bc). The docs do display the name, for example http://openlayers.org/en/master/apidoc/ol.source.Tile.html, but greyed out and gives no further details.

**Comment by gberaudo** [comment]
Have you tried moving the `ol` typedefs in the `ol` namespace instead of `typedefs.js`? I think 
it would be more consistent.

I want to try if compilation works for individual examples. But actually many examples are already failing in master: most due to unnecessary dependency but there are also other problems which need investigation. Unfortunately I am on vacations until next Monday.

I put my WIP code in https://github.com/gberaudo/ol3/tree/test_combined if anyone is interested in the meantime.

**Comment by probins** [comment]
> Have you tried moving the ol typedefs in the ol namespace instead of typedefs.js? I think 
> it would be more consistent.

no, I don't really agree with that. For me, the objective is to move away from namespaces and towards modules. Do I think that typedefs should be in an `ol` module? No. I don't think they should be in any module, as they are not code and not imported or exported. They are only for GCC, and people not using GCC should be able to ignore them. I'm very open to better suggestions, but AFAICS the best way to enable that is to move them to a separate file. It doesn't really matter to me (or to the majority of OL users) whether the namespace element in their names is kept or not. Leaving it in seems to cause problems, so ISTM the way forward is to remove it, keeping the existing structure as a duplicate if that helps those who want to continue to compile code with the library to migrate. In any case, at least some of these types are pretty obscure (KMLVec2_? does anybody use that?) and I would doubt whether renaming them would cause many people problems.

**Comment by probins** [comment]
continuing on from this, I count 43 typedefs which are in sub-namespaces, of which only 13 are marked as api. Renaming the others shouldn't cause problems, so I'm working on another commit which does this (most of them are only used internally in 1 file). Renaming the 13 api ones may or may not affect people compiling code with the library, but I would doubt whether this will have a serious impact, especially if we keep duplicates as is for the moment and document the change in the release notes. I'll look into a further commit for this.

**Comment by probins** [comment]
work is continuing in my [typedefs branch](https://github.com/openlayers/ol3/compare/master...probins:typedefs). Getting near a PR for formal review.

**Comment by probins** [comment]
I have found a solution for EventTargetLike. If I move the typedef into its own file, _and_ insert a `goog.provide`, _and_ a `goog.require` where this is used (only `events.js`), then it compiles with no error. I think this should work in the modular setup too. This would not be a module, so would not be converted into the `var x = goog.require` pattern. Whatever script we have for converting/transpiling the `goog.module`s into CommonJS (or ES6) could ignore the typedef files and the `goog.require`s without `var x = ...`. So this would only be used for GCC and would not be part of the CJS/ES6 modules.

I still have no idea why this typedef is the only one to cause errors, but I'm now wondering whether it wouldn't be better to use this pattern for all the api sub-namespace typedefs. More experimentation.

**Comment by gberaudo** [comment]
@probins, thanks for your work. I had a quick look to it and I am concerned it is going too far from the initial idea of a simple typedefs.js file.

Looking back to https://github.com/openlayers/ol3/issues/5299#issuecomment-216480664, I think the `last possiblity`: `keep the typedefs where they are now and only remove the goog.provide if it conflicts with a future goog.module declaration` is close to what you are trying to achieve while having the advantage of smaller changes and no API breakage.

**Comment by probins** [comment]
I don't think keeping the typedefs where they are in their current form is a viable option if the objective is to convert to standard modules, whether that be CommonJS or ES6. If we go with `goog.module`, it will work only when using GCC, as only GCC knows about the namespace structure. If the plan is to have some sort of conversion script/transpiler to convert `goog.module` to CJS so other tools can use the modules, this will only work if the namespace structure disappears. To take a simple example in your branch, `centerconstraint.js` should be straightforward to convert to CJS: the 2 `goog.module` lines can be removed, and assuming you have things like `var math = goog.require('ol.math')`, that can be converted to `var math = require('ol/math')` or `./ol/math.js` or something similarly CJS-style. The `exports` will probably work in CJS without any conversion. I don't know of any current CJS to ES6 transpilers, but these will undoubtedly appear once ES6 modules start to be implemented, so a simple conversion from CJS to ES6 should be also be straightforward.

If the typedefs remain where they are, they would have to be renamed to get rid of the namespace structure, so `ol.format.WFS.FeatureCollectionMetadata` would become `var WFSFeatureCollectionMetadata` or some such. That makes them convertible to CJS but any linter would see them as unused vars, and it isn't backward compatible (though that doesn't matter for the non-API ones).

Another possibility would be for the transpiler to ignore them somehow, perhaps by adding a `\\ typedef` comment at the end of the definition, so the transpiler knows to ignore those lines, but if the longer-term plan is to convert to ES6, this won't help, as the typedefs shouldn't be in the modules anyway.

What I'm now proposing in my branch moves all the typedefs out of the code. This enables a simple transpile to CJS without any API breakage.

**Comment by gberaudo** [comment]
Being able to directly use OL3 code without pre-processing would be great but I fear it may be too ambitious.

Writing typedefs as modules (using the `exports` variable) does not work (at least what I tried). If you have a dependency on a typedef you will have a `goog.require` pointing to a non module file, which is OK with GCC but probably not with other tools.

With such a preprocessing tool, it looks manageable to filter out `goog.require` pointing to typedef code, with a comment like you suggest or another way. I think it would work even with typedef symbols keeping their hierarchical structure.

**Comment by tschaub** [comment]
It sounds to me like we're back at the suggestion to have all `@typedef` in a single file (as suggested in https://github.com/openlayers/ol3/pull/5210#issuecomment-209586078).  This makes sense to me.

**Comment by probins** [comment]
as I see it, the `goog.require`s that point to typedefs aren't imports, so they won't be `var x = goog.require...` but just `goog.require`. A transpiler could ignore them.

**Comment by probins** [comment]
but that doesn't work, Tim, because of the namespace dependency issue. `ol.style.Atlas.Block` depends on `ol.style.Atlas`. If you have that in a typedefs file and someone compiles their code with the library and their code doesn't create `ol.style.Atlas`, you have an undefined error.

**Comment by probins** [comment]
my branch is pretty much ready for a PR but I decided it would be simpler to separate out the 1st commit, which just removes the unneeded `goog.require`s in the current code, and put that in a separate PR, as it's independent of converting to a new structure.

**Comment by tschaub** [comment]
> but that doesn't work, Tim, because of the namespace dependency issue. ol.style.Atlas.Block depends on ol.style.Atlas. If you have that in a typedefs file and someone compiles their code with the library and their code doesn't create ol.style.Atlas, you have an undefined error.

I think the compiler considers this a `JSC_POSSIBLE_INEXISTENT_PROPERTY` (not an undefined error).  But it doesn't have to fail.

**Comment by probins** [comment]
that's right - it creates a warning not an error. So perhaps another possibility is to just ignore those warnings?

**Comment by gberaudo** [comment]
Yes, would be acceptable I think.

**Comment by probins** [comment]
after a lot of trial and error, I've found that my idea of splitting the typedefs file into one file per sub-namespace doesn't fix the problem, and raises exactly the same issues as having them all in one file. To recap, these are:
* with all provides/requires removed, the standard full build throws 2 errors as described in https://github.com/openlayers/ol3/issues/5299#issuecomment-216207123. I don't understand these errors, but they can be fixed by adding a `goog.provide` for both in the typedefs file, and also a `goog.require` in the file where the error occurs
* this means the standard full build compiles ok, but the examples build fails because `ol.raster.Pixel` is used in 2 examples, but `ol.raster.Operation` (the only other property of `ol.raster`) isn't, so the `ol.raster` namespace is never created. This can be resolved by adding `goog.provide('ol.raster.Pixel')` in the typedefs file. Because other people compiling their code with the library may refer to typedefs in other namespaces that aren't otherwise used in their code (this is particularly a problem with the olx options which refer to types whether the options are used or not), a solution is to add a `goog.provide` for at least one typedef for each sub-namespace
* I tried adding a `goog.provide` for all typedefs in sub-namespaces, but then you get errors about missing `goog.require`s, and you have to add some of these back in
* there are also sub-sub-namespaces, like `ol.style.Atlas.Block`, but I think these are all non-api, so can be renamed to be in the sub-namespace, like `ol.style.AtlasBlock`. There is in any case a lot of inconsistency in the naming, for example, `ol.style.AtlasInfo`, and renaming makes the naming more consistent.

I think this is a reasonable solution. The important thing is to move the typedefs out of the code modules. Even if there are a few `goog.require`s in the module code, a transpiler can ignore them as they are not imports.

So, I will look into creating a new branch/PR for this proposal, going back to my original one typedefs file, but it will probably be next week before I can get around to this.

There is one outstanding item: I haven't touched `ol.vec.Mat4.Number` because this is affected by #5138. It might be better if that PR renames this to `ol.vec.Mat4Number` or even `ol.vecMat4Number`.

**Comment by ahocevar** [comment]
+1 on renaming typedefs - the names are not part of the API anyway.

**Comment by gberaudo** [comment]
>> I think the compiler considers this a JSC_POSSIBLE_INEXISTENT_PROPERTY (not an undefined error). But it doesn't have to fail.

> that's right - it creates a warning not an error. So perhaps another possibility is to just ignore those warnings?

@probins, have you tried this possibility?

**Comment by probins** [comment]
@gberaudo I found this wasn't necessary

**Comment by probins** [comment]
`ol.vec.Mat4.Number` now dealt with, so this can be closed
