### ISSUE TITLE
Pause or Stop listening to change event temporary

### ISSUE THREAD

**Issue by psyntium** [openlayers/ol3#5301]
Is there a way to pause or stop change event to be triggered temporary while all updates are still being applied?

Basically, I want to update a number of features, (e.g. 500 features) and only allow the layer to redraw once all updates has been applied.

**Comment by fredj** [comment]
You can change a feature's property silently with: `feature.set('foo', 42, true);`

**Comment by bartvde** [comment]
See also: http://stackoverflow.com/questions/36974264/on-openlayers-3-how-do-you-pause-a-change-event-when-updating-features
