### ISSUE TITLE
update layer source params (redrawing layer)

### ISSUE THREAD

**Issue by KlemenSpruk** [openlayers/ol3#5307]
I have a map like this:

var map = new ol.Map({
  target: 'map',
  view: new ol.View({
    projection: 'EPSG:3857', 
    center: [0, 0],
    zoom: 2
  }),
  layers: [
    new ol.layer.Tile({
      source: new ol.source.TileWMS({
        projection: 'EPSG:4326', 
        url: 'http://demo.boundlessgeo.com/geoserver/wms',
        params: {
          'LAYERS': 'ne:NE1_HR_LC_SR_W_DR'
        }
      })
    })
  ]
});

when I call updateParams method on layer source, source params are updated but the layer on screen is not reloaded. When I pan the map i can see that the layer params were updated because new features are being drawn. This only happens when map has different projection than layer.

Any idea why layer in not redrawn if it has other projection than map?

Thanks!

**Comment by bartvde** [comment]
Try adding a random parameter, so you by-pass browser cache.

**Comment by MarcoCiaramella** [comment]
Did you solve the problem?

**Comment by ahocevar** [comment]
See #5841.
