### ISSUE TITLE
Vector tiles for different zoom levels rendered simultaneously

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#5317]
When loading vector GeoJSON tiles (which differs for every zoom level) using the following approach, some tiles are rendered incorrectly:

1. on several tiles features for specific zoomlevel are covered with features for another level
2. on several other tiles features doesn't change with the change of zoomlevel

I suspect case (2) is just specific variant of case (1) and those correct features are rendered beneath that visible layer.

When minZoom/maxZoom is set to the same value, all tiles are rendered correctly.

```javascript
var tileGrid = ol.tilegrid.createXYZ({
    minZoom: 6,
    maxZoom: 10
});

var vectorSource = new ol.source.Vector({
    format: new ol.format.GeoJSON({
        defaultDataProjection: 'EPSG:3857'
    }),
    strategy: ol.loadingstrategy.tile(tileGrid),
    url: function(extent, resolution) {
        var tileCoord = tileGrid.getTileCoordForCoordAndResolution(ol.extent.getCenter(extent), resolution);
        return 'tiles/' +
            tileCoord[0] + '/' +
            tileCoord[1] + '/' +
            (Math.pow(2, tileCoord[0]) + tileCoord[2]) + '.json';
    }
});
```
Is it necessary to clear something on my side?

**Comment by ahocevar** [comment]
Why aren't you using `ol.source.VectorTile` with an `ol.layer.VectorTile`?

**Comment by jan-tosovsky-cz** [comment]
@ahocevar My code is based on suggested code for https://github.com/openlayers/ol3/issues/4501 (after some time I continue on my unfinished project).

**Comment by ahocevar** [comment]
For this to work, you would have to call `clear()` on the source when the resolution changes.

**Comment by jan-tosovsky-cz** [comment]
Yes, this helped, thanks. 

```javascript
mapView.on('propertychange', function(e) {
   switch (e.key) {
      case 'resolution':
        vectorSource.clear();
        break;
   }
});
```

Btw, any idea how to clear the obsolete stuff after loading the new content? Now I am getting annoying blinking. I am thinking about zoomlevel stamp to each feature and later use it to determine which ones should be deleted (which needs inefficient iteration all of the features).

**Comment by ahocevar** [comment]
Not much you can do to work around a data source which is neither vector data nor vector tiles on the client. Maybe you can improve or change your data source?
