### ISSUE TITLE
Line crossing 180th meridian

### ISSUE THREAD

**Issue by tananaev** [openlayers/ol3#5318]
I am a developer of [open source GPS tracking system](https://github.com/tananaev/traccar). My platform uses ol3 library for drawing map. System allows to display historical tracks of various objects and that's where the problem happens. When an object crosses 180th meridian, the connecting line is drawn through the whole globe backwards (see image below).

![traccar1](https://cloud.githubusercontent.com/assets/1161863/15100716/de310f10-15ce-11e6-99e6-d4441624a3ea.jpg)

I understand why it's happening from the technical point of view, but is there any solution to this problem. Is there a way to tell ol3 to draw the shortest connecting line instead?

**Comment by dbazile** [comment]
I bumped into this behavior with allowing users to draw arbitrary bounding boxes.  On doing some research, I found this:

> Unfortunately this is a known problem. The issue is that geometries that cross the date line like this are ambiguous. The OL and GeoServer renderers have no easy way of knowing that the intention is to go the "short" way around the world so they just interpret for instance 170 to -170 the "regular" way and go the long way around the world.
>
> Unfortunately there is no good solution for this except to split up your geometries that lie across the dateline.

_Source: http://gis.stackexchange.com/a/7067/71050_

I'm sure you've found a workaround by now, but I figure I'd put this here for anyone else who runs into this problem. :)

**Comment by tananaev** [comment]
Unfortunately I don't have any workarounds. Just waiting for OpenLayers team to come up with some solution.

Thanks for the link. I think I've seen it before.

**Comment by ahocevar** [comment]
The link explains why there is no solution that can be built into OpenLayers. Most workarounds I've seen out there in the wild involve splitting geometries at 180/-180 and continue them at -180/180. In JavaScript, you should be able to use [JSTS](https://github.com/bjornharrtell/jsts) for that.

**Comment by goran-pantic** [comment]
I have also encountered this problem but and created a solution for it. You can see it on my repl.it here: https://repl.it/@gpantic/OpenLayersSplitRouteOverPacific
