### ISSUE TITLE
requestAnimationFrame on older mobiles (and a solution!)

### ISSUE THREAD

**Issue by zstauber** [openlayers/ol3#5321]
Just did the "Hello, world!" with v3.15.1 and it works on every browser I've tried except my Android Internet browser.  In the browser console I get

> "Uncaught TypeError: Object [object DOMWindow] has no method 'requestAnimationFrame'

Now, I did some digging, and it is because my browser version needs a prefix on the function name.

I'm using Android Browser on a Samsung Galaxy S III running Android 4.4.2.  If I use the debug version of ol, ol-debug.js and change the function on line 67995 from requestAnimationFrame to webkitRequestAnimationFrame, it works on the mobile browser, but of course breaks it for everything else.  [This guy](https://davidwalsh.name/requestanimationframe-shim) has a fix.

```
var requestAnimationFrame = window.requestAnimationFrame
    || window.webkitRequestAnimationFrame
    || window.mozRequestAnimationFrame
    || window.msRequestAnimationFrame
    || function(callback) { return setTimeout(callback, 1000 / 60); };
```

If instead of adding the prefix on line 67995, you insert the above polyfill on line 4 after the opening comments and BEFORE the enclosure for any ol code, it also fixes it and of course works for all browsers.  You would probably want to insert the polyfill within the main code block, but I'm not JS savvy enough to figure out how to make that work (I tried, but "window" gets aliased and so the polyfill doesn't work as written).  Anyway, I would be greatly appreciative if you would include this polyfill in the main code.

**Comment by ahocevar** [comment]
OpenLayers no longer includes polyfills for old browsers. See the [v3.14.0 release notes](https://github.com/openlayers/ol3/releases/tag/v3.14.0) under the "Internet Explorer 9 support" section.

**Comment by zstauber** [comment]
OK, thanks.  Well, I'll just include it in my copy of OL I guess.
