### ISSUE TITLE
About icon color example

### ISSUE THREAD

**Issue by ZoeHuang13** [openlayers/ol3#5336]
version:3.15.1
I download the v3.15.1.zip, open the file:///D:/Openlayers3.15.1/examples/icon-color.html. 
Nothing show on the map. 
![1](https://cloud.githubusercontent.com/assets/17848583/15208419/0e187ed4-185e-11e6-896f-4765e9a1371f.png)

But in http://openlayers.org/en/v3.15.1/examples/icon-color.html, icons have shown.
![2](https://cloud.githubusercontent.com/assets/17848583/15208460/4d93c9d8-185e-11e6-9369-7f5782c5d60d.png)

If I remove the color option from iconstyle, icon can show.
![3](https://cloud.githubusercontent.com/assets/17848583/15208692/89d1a23e-185f-11e6-9f9e-1d243ad13de2.png)

Is there anything wrong with icon color?

**Comment by ahocevar** [comment]
This is expected, because a file:/// url (for the example's js) is never the same origin as another file:/// url (for the icon image), so the canvas is tainted, and you cannot access it to change the color.

**Comment by marcjansen** [comment]
A PR explaining this in the example description would be much appreciated, though.

**Comment by ahocevar** [comment]
Pull request: #6349.
