### ISSUE TITLE
Scrollbar disappears in API documentation

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#5338]
Screenshots:

![workspace 1_014](https://cloud.githubusercontent.com/assets/10571881/15213993/c743d13a-1820-11e6-8115-9ec76b6f6975.png)

Some more scrolling:

![workspace 1_015](https://cloud.githubusercontent.com/assets/10571881/15214000/d553c26c-1820-11e6-8e77-2654e3f33109.png)

**Comment by probins** [comment]
yes, I've just noticed this. It's not just the scroll bar - you can't scroll at all. I think this is after the latest changes to put the version at the top of the column.

**Comment by ahocevar** [comment]
> I think this is after the latest changes to put the version at the top of the column.

I'm going to revert that change anyway. So stay tuned.
