### ISSUE TITLE
Clarifying 'api' for typedefs/enums/options

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5346]
As a follow-up to my suggestion in #5335 that the two `ol.format.WFS.xxx` typedefs be renamed despite their currently being labelled 'api', I think it would be good if the documentation explicitly defined what the supported api for all the object types consists of, in other words what the 'contract' is between the library and the application developer. AFAICS the only documentation for this at the moment is in the [Introduction tutorial](http://openlayers.org/en/latest/doc/tutorials/introduction.html), which mentions the 'exportable properties and methods'. The constructor and static function names should be added to this.

With the constructor options, it is the property names that are important, not the name of the options object itself. The `olx` definitions are included in the docs, and are linked to when part of another options object, for example, http://openlayers.org/en/master/apidoc/ol.source.Vector.html links to `olx.LogoOptions`, so these names are part of the api docs, even though they are never used in application code and not exported.

Similarly, the typedef and enum names are referred to in the docs, but are not used by application code or exported. With enums it is the enumerated values that are used in apps and so are part of the api; for example, the possible values of `ol.OverlayPositioning` are the important thing, not the name of the enum itself. In the case of typedefs, I think the only effect of marking one as 'api' is that it appears in the docs.

As another example, I would suggest getting rid of `ol.raster`. This only consists of 2 typedefs and 1 enum, and in module terms it makes no sense to import a module just for an enum. The enum is only used in `source.raster`, so could be moved there - provided that renaming it and the 2 typedefs doesn't break the api.

Although changing the names of typedefs and enums doesn't affect the majority who use built versions of the library, it might affect people compiling app code together with the library if they refer to the types in their code. So maybe part of the 'contract' is defining under what circumstances they may be changed, and documenting changes in release notes

So, I think the definition of 'api' should be clarified. Is the introduction tutorial the best place for this? Perhaps have a section in the api docs landing page?

**Comment by ahocevar** [comment]
The `@api` *annotation* on typedefs is mostly there to simply include the documentation of the type in the API documentation.

The *API* is what you see in the API docs and what you work with in your applications. The typedefs in the API docs are just links to a section that shows the actual type, e.g. `ol.Pixel` -> `Array.<number>`.

The *names* of these typedefs, as you said correctly, only matter to users who use Closure compiler to compile applications together with the library.

Here's my suggestion for the API contract regarding typedefs: The names of typedefs are subject to change. Such name changes will be mentioned in the upgrade notes, so it should be easy for users to update their code with a simple search/replace operation.

The explanation of what API means could go as fine print section on the API docs entry page, `config/jsdoc/api/index.md`.

**Comment by probins** [comment]
> 'exportable properties and methods'.

in fact, I don't think there are many exportable properties. There are a few constants, for example in `ol.has`, but instance properties are only available via accessors, and I don't think any of the static objects have any exportable properties.

**Comment by ahocevar** [comment]
> in fact, I don't think there are many exportable properties.

The event properties are. Like e.g. `pixel` or `coordinate` on `ol.MapBrowserEvent`.

**Comment by probins** [comment]
fixed with #5353
