### ISSUE TITLE
Parsing MapServer GML with multiple feature types

### ISSUE THREAD

**Issue by tsauerwein** [openlayers/ol3#5357]
I am trying to parse a GML3 response of a `GetFeature` request to a MapServer instance which contains multiple feature types (here is an [example](https://github.com/tsauerwein/ol3/commit/acaa0b2889c4c969f313580b8a8e17334f7cd5c1#diff-541ce474963c61df73b52fba2de2daba)), using `ol.format.WFS`.

While GeoServer by default seems to return a single `featureMembers` element, MapServer uses a `featureMember` element for each feature. As long as the GML contains only one feature type, this is not a problem. But the parsing fails with multiple feature types. Here is a failing test demonstrating the issue: https://github.com/tsauerwein/ol3/commit/acaa0b2889c4c969f313580b8a8e17334f7cd5c1#diff-a5a1ca3bd6339e3b5b633c25aa74c367R864

Am I doing it wrong? If not I will try to dig into the WFS parser.

**Comment by bartvde** [comment]
Interesting, I don't think you're doing it wrong @tsauerwein this is likely an oversight / not implemented case. I guess it also doesn't work when using ol.format.GML3 ?

**Comment by tsauerwein** [comment]
Thanks for your feedback, Bart! `ol.format.GML3` also didn't work, but I prepared a fix here: https://github.com/openlayers/ol3/pull/5358
