### ISSUE TITLE
Feature id for MVT layer features is undefined

### ISSUE THREAD

**Issue by drnextgis** [openlayers/ol3#5366]
I'm trying add select capability to MVT layer as proposed by @ahocevar [here](https://github.com/openlayers/ol3/issues/5248#issuecomment-211878312), but as I can see `feature.getId()` always returns `undefined` because `feature._id` is `undefined`. Am I missing something?

**Comment by ahocevar** [comment]
The suggestion you cited above was for a VectorTile layer that used a format different than MVT (e.g. GeoJSON). We cannot parse ids in `ol.format.MVT`. The vector-tile library we use does not provide an id (see https://github.com/mapbox/vector-tile-js), except when using `VectorTileFeature#toGeoJSON()`, which we don't use for performance reasons.

If you want to have access to ids from MVT features, the first step would be to create a pull request on https://github.com/mapbox/vector-tile-js to make the currently private `_id` on `VectorTileFeature` a public `id` property.

**Comment by drnextgis** [comment]
Make VectorTileFeature#id a public property pull request has landed to vector-tile-js repository.

**Comment by drnextgis** [comment]
Please review PR.

**Comment by drnextgis** [comment]
Fixed via https://github.com/openlayers/ol3/commit/8e31b65a87a00ae3b1bfcda12e9ab1b232e6ee4e
