### ISSUE TITLE
Midnight wraparound in IGC Format

### ISSUE THREAD

**Issue by Turbo87** [openlayers/ol3#5371]
The IGC format reader is parsing the start date from the `HFDTE` record and is using it to calculate fix times. At the moment the reader isn't accounting for the UTC midnight wraparound though which leads to wrong timestamps if a flight log starts e.g. at 23:00:00 UTC and ends at 01:00:00 UTC on the next UTC day.

/cc @twpayne

**Comment by ahocevar** [comment]
@Turbo87 Are you able and willing to create a pull request with a fix? @twpayne is not actively working on OpenLayers any more.

**Comment by Turbo87** [comment]
if I find the time at some point I might do that. I'm not using the format implementation at the moment, but wanted to document this as a known issue for now.
