### ISSUE TITLE
POI symbols in vector tiles

### ISSUE THREAD

**Issue by apachemaven** [openlayers/ol3#5374]
I just find that ol3 support the vector tiles [here](http://openlayers.org/en/latest/examples/mapbox-vector-tiles-advanced.html), however I can hardly find a point or road symbols in the map, so I wonder if this is on the progress or I miss anything?

**Comment by tsauerwein** [comment]
Styles for vector tiles are rendered the same way as for other kind of vector data. So, you can use all available styles: http://openlayers.org/en/master/apidoc/ol.style.html

In [this](http://openlayers.org/en/master/examples/mapbox-vector-tiles.html) vector tile example you can see some icons when you zoom in. The style definition for this example is here: https://github.com/openlayers/ol3/blob/412dc04/examples/resources/mapbox-streets-v6-style.js#L17-L20

**Comment by apachemaven** [comment]
Sorry, my mistake. And I tired to reset the styles for the points and it works. However there are still some problems, for example does the label(text style) for the point support `word wrap` and `responsive direction` according to the icon?

Example:
![image](https://cloud.githubusercontent.com/assets/4485890/15488550/06146588-218a-11e6-8293-2e74876618f8.png)

As shown, the label can create line breaks when the text are too long, also the position of the label can reside at the left/top/right of the icon.

**Comment by tsauerwein** [comment]
ol3 does not do automatic label placement (as for example [Mapbox GL is doing](https://www.mapbox.com/blog/placing-labels/)).

**Comment by fredj** [comment]
>  does the label(text style) for the point support word wrap

Multiple lines is supported; a new line is created when the `\n`character is found in the string

**Comment by ahocevar** [comment]
> also the position of the label can reside at the left/top/right of the icon

This is also supported. You can play around live with most of the available options in this example: http://openlayers.org/en/latest/examples/vector-labels.html.
