### ISSUE TITLE
Dynamic geojson layer only supports EPSG:3857, but not EPSG:4326

### ISSUE THREAD

**Issue by yong2khoo88** [openlayers/ol3#5385]
I am using jquery to get the geojson from the server, and then using something like this to dynamically add that layer to the map:

```
var newVectorSource = new ol.source.Vector({
                    features: (new ol.format.GeoJSON()).readFeatures(myDynamicGeoJson)
                });

var layerGeoJson = new ol.layer.Vector({
                    source: newVectorSource
 })

 map.addLayer(layerGeoJson);
```

What i discover is that, it only works IF the `myDynamicGeoJson` is in the projection of EPSG:3857, which is, as same as the one in this[ demo page](http://openlayers.org/en/latest/examples/geojson.html). However, if it is EPSG:4326, my dynamic layer will all be rendered wrong (all centered around (0,0))

One thing to note is that, it only happens to the dynamic layer. If i follows the normal usage like the one below, it works properly.
```
var layerGeoJson = new ol.layer.Vector({
            source: new ol.source.Vector({
                url: urlGeoServerWFS,
                format: new ol.format.GeoJSON()
            }),
            style: customStyleFunction
        });
```

My current workaround, is to convert my data to the format in EPSG:3857.
Do let me know if there would be any fix for this in the future. Thanks.

**Comment by ahocevar** [comment]
When you populate a source with features as in your first snippet, you have to pass the feature projection to the format's `readFeatures` method:
```js
var newVectorSource = new ol.source.Vector({
  features: (new ol.format.GeoJSON()).readFeatures(myDynamicGeoJson,
      {featureProjection: map.getView().getProjection())
});

**Comment by yong2khoo88** [comment]
Thanks ahocevar! It works like a charm!
