### ISSUE TITLE
Introductory materials?

### ISSUE THREAD

**Issue by bethrobson** [openlayers/ol3#5386]
Do you have a link to any introduction to Open Layers? The "Introduction" and "Basic Concepts" in the docs assume the reader already knows what Open Layers is. 

Does it work with the Geolocation API? 

Thank you.

**Comment by bartvde** [comment]
Did you do the workshop http://openlayers.org/workshop/ ?

**Comment by bethrobson** [comment]
No, I hadn't seen that, thanks for the link. This looks like a good resource, although it still doesn't tell me what OpenLayers *is*. There is no "about" page on the site, and no description other than that it is "A high-performance, feature-packed library for all your mapping needs". The workshop says "OpenLayers as a web mapping solution", again, not really saying much more about what it is. Is it associated with OpenStreetMap? Is it a JavaScript library? Etc. I can figure out what it is through doing the workshop, but I think a good "About" page would add a lot to this project!

The workshop also assumes familiarity with npm (meaning Node), meaning your audience is somewhat advanced, so on the About page, perhaps a description of what the developer should already know would be helpful. Looks to me like a fairly advanced knowledge of JavaScript is necessary, along with an understanding of what Closure is, and some basic design patterns knowledge. 

I am hoping to point my students to this as a resource, but when a newbie comes to the front page, there is very little information to help guide them to get started. I was not able to find a link to the workshop anywhere on the front page. 

Thank you.

**Comment by bethrobson** [comment]
P.S. An example of a library that has a good description is Leaflet:

http://leaflet.org/

Right there on the front page I can learn a great deal about what Leaflet is and if it's appropriate for what I want to do.

**Comment by ahocevar** [comment]
Thanks for the excellent feedback @bethrobson. Interesting side note: the official web page for Leaflet is http://leafletjs.com/, and I was not even aware of the probably privately run http://leaflet.org/.

We are constantly trying to improve documentation and learning resources, but it is not easy to create a balance between focus on library development and documentation. That said, pull requests that improve our documentation are always welcome. In case you or some of your students are willing to help: The website sources are in https://github.com/openlayers/openlayers.github.io. The documentation is in the `doc` folder of https://github.com/openlayers/ol3, and the workshop is in https://github.com/openlayers/workshop.

**Comment by crschmidt** [comment]
I wonder if adding something like the description from OLv2 page ("OpenLayers makes it easy to put a dynamic map in any web page. It can display map tiles and markers loaded from any source. OpenLayers has been developed to further the use of geographic information of all kinds. It is completely free, Open Source JavaScript, released under the 2-clause BSD License (also known as the FreeBSD).") would be helpful? Reading the current OpenLayers homepage, I agree that it feels a bit like it's missing a mission statement for users who aren't already aware of what OpenLayers is...

**Comment by bartvde** [comment]
This was added to the website by @ahocevar, so closing.
