### ISSUE TITLE
WMTS is rendered completely, ignoring the extent property on the view

### ISSUE THREAD

**Issue by cvenzin** [openlayers/ol3#5387]
I was just playing around with extents on the view and layers. It seems that the extent property on the view is ignored on an ol.layer.Tile with an ol.source.WMTS. The WMTS is rendered beyond the views extent.
However an ol.layer.Tile with an ol.source.TileWMS works as expected.

I used the https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissalti3d-reliefschattierung/default/{Time}/21781/{TileMatrix}/{TileRow}/{TileCol}.png WMTS with EPSG:21781.

**Comment by ahocevar** [comment]
The view extent only restricts the center to always be inside. So what you are seeing is expected behaviour. If you want to restrict which tiles are being shown, you have to set an extent on the layer.

When you say things work as expected with a TileWMS source, what exactly do you mean?

**Comment by cvenzin** [comment]
Ok, maybe the question "What is expected?" should be clarified first.
The TileWMS is only rendered inside the views extent. So, the behaviour is different between WMTS and TileWMS.

**Comment by ahocevar** [comment]
That's interesting. Can you share an example (JSFiddle) for both cases, i.e. TileWMS and WMTS?

**Comment by cvenzin** [comment]
I'll make one.

**Comment by cvenzin** [comment]
Sorry, my fault. I linked the views extent to the extent of the projection, missleading my conclusion. The views property extent is absolutely working fine.
It's actually the projections extent, limiting the rendering of a WMS (image or tile), but not of a WMTS. The WMTS always renders completely in its extent ignoring the projections extent. 
Hmm, so usually the projections extent should be larger than the layers ones, so this bug report can be closed.

**Comment by ahocevar** [comment]
> It's actually the projections extent, limiting the rendering of a WMS (image or tile), but not of a WMTS.

The projection extent influences auto-generated tile grids. Usually, you provide your own tile grid for WMTS, so that won't happen. Whereas for TileWMS, users typically rely on an auto-generated tile grid.
