### ISSUE TITLE
API docs title

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#5389]
If you open http://openlayers.org/en/master/apidoc/ you'll see 
```html
<title>OpenLayers v3.15.1 API - Index</title>
```

**Comment by ahocevar** [comment]
The title is generated from information in `package.json`, so even when viewing master docs, it will show the latest release.

That said, I'm currently running the doc generator for master, and after the update, it will show `v3.16.0`.

**Comment by jonataswalker** [comment]
:zap: closing
