### ISSUE TITLE
Problem in loading a georeferenced image through ol.source.ImageStatic() source

### ISSUE THREAD

**Issue by EGLadona** [openlayers/ol3#5391]
I apologize if here is not the adequate place to note this problem but I notified it in the [Stackoverflow](http://stackoverflow.com/questions/37279575/openlayers-3-why-a-georeferenced-image-is-badly-placed-in-recent-ol3-releases) site and nobody reacted. I've decided to put here because I have downloaded the most recent ol3 release v3.16.0 and the problem is still there:
I load a georeferenced SST image through a ImageStatic source into an Image layer and the image seems to be badly projected over the basic map. This was good up to v 3.7.0 and the problem appear at least from 3.14.0 ( I did not verify the releases in between). To show it I have prepared demos for some release versions as indicated in the Stackoverflow site.

I would like to know if it is a bug or perhaps I'm missing something non-evident to me ?

Thank you for your time, patience and interest.

**Comment by ahocevar** [comment]
Answered on [Stackoverflow](http://stackoverflow.com/questions/37279575/openlayers-3-why-a-georeferenced-image-is-badly-placed-in-recent-ol3-releases). Not a bug.

**Comment by EGLadona** [comment]
I'm very sorry for the typo !!. I was very confused trying to update from version 3.3. Thanks for your attention.
