### ISSUE TITLE
ol.format.WFS.prototype.writeTransaction doesn't  use options.srsname

### ISSUE THREAD

**Issue by anzhihun** [openlayers/ol3#5397]
When  using  [ol.format.WFS.prototype.writeTransaction](https://github.com/openlayers/ol3/blob/v3.16.0/src/ol/format/wfsformat.js#L842) to insert new features to geoserver,  I found the coordinates is wrong. Because `writeTransaction` doesn't  use  options.srsname, see [https://github.com/openlayers/ol3/blob/v3.16.0/src/ol/format/wfsformat.js#L859](https://github.com/openlayers/ol3/blob/v3.16.0/src/ol/format/wfsformat.js#L859). After changing code to below: 
```javascript
obj = {node: node, featureNS: options.featureNS,
      featureType: options.featureType, featurePrefix: options.featurePrefix, srsName: options.srsName};
```
The coordinates inserted are right.  
Is it a bug or is something wrong with me? Thanks!

**Comment by bartvde** [comment]
I think this is a bug, are you able to create a pull request?
