### ISSUE TITLE
Fill polygon with image

### ISSUE THREAD

**Issue by anzhihun** [openlayers/ol3#5398]
I can't find the way to fill polygon with image as follow: 
![fillpolygon](https://cloud.githubusercontent.com/assets/1855738/15564580/4eae701e-2346-11e6-8202-5293590bc53d.jpg)

Does not ol3 provide the way? Or does I miss something?  Is there any other way to do this? Thanks!

**Comment by jmekaelthas** [comment]
I think that currently it is not possible. But I would vote  for such feature to be added to OL3. It's quite important to be able fill both polygons and polylines with texture.

**Comment by tsauerwein** [comment]
PR https://github.com/openlayers/ol3/pull/4632 added support for [CanvasPattern](https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern) and [CanvasGradient](https://developer.mozilla.org/en-US/docs/Web/API/CanvasGradient). Unfortunately there is no "official" example but there are some JSFiddles:
http://jsfiddle.net/61b7szjn/
http://jsfiddle.net/07366L44/

**Comment by anzhihun** [comment]
@tsauerwein  Thank you very much !
