### ISSUE TITLE
Why using the tileLoadFunction for the TileWMS ends up with empty images?

### ISSUE THREAD

**Issue by yong2khoo88** [openlayers/ol3#5401]
#4213 (Reference)

I need to set the request header using tileLoadFunction as mentioned in the previous post.

The attached shows my observation: 
![why-not-shown](https://cloud.githubusercontent.com/assets/5007089/15603996/6f956860-2430-11e6-9e60-8e2abbb5d1a9.jpg)

The thing is, it does return an image - as when i double-click the link shown in the 'Network', it does display the image tile from the browser. However, it just doesn't appear in my map.

Also, if i remove the tileLoadFunction, the tile images are shown properly on the map. So it makes me think that, it could be something wrong with that code in the tileLoadFunction.

Here's my code (slightly different with the one in the post):
```
tileLoadFunction: function (tile, src) {
	var client = new XMLHttpRequest();
	client.open('GET', src);
	
	//client.setRequestHeader('testheader', 'myheadersecret');
	client.onload = function () {
		var data = 'data:image/png;base64,' + btoa(unescape(encodeURIComponent(this.responseText)));
		tile.getImage().src = data;
	};
	
	client.send();
},

```
something to note is that, my current setting is, the tile server is accessible regardless of having the request header being set or not. 

What did i miss? Any suggestion is appreciated!

**Comment by yong2khoo88** [comment]
i personally think that these 2 lines don't work:
```
var data = 'data:image/png;base64,' + btoa(unescape(encodeURIComponent(this.responseText)));
tile.getImage().src = data;
```

**Comment by cvenzin** [comment]
When you have a bytearray server side, use this:
```
var xhr = new XMLHttpRequest();
xhr.open("GET", src);
xhr.responseType = "arraybuffer";

xhr.onload = function () {
    var arrayBufferView = new Uint8Array(this.response);
    var blob = new Blob([arrayBufferView], { type: 'image/png' });
    var urlCreator = window.URL || window.webkitURL;
    var imageUrl = urlCreator.createObjectURL(blob);
    image.getImage().src = imageUrl;
};
xhr.send();
```

**Comment by cvenzin** [comment]
Keep in mind, if the url is cors your browser will do a pre-flight OPTIONS request. Thus most WMS out there will reject your requests. In this case (e.g. for basic authentication), a proxy is needed that thus the xhr request on server side.

**Comment by yong2khoo88** [comment]
Hi cvenzin,

It works like a charm!! Thank you so much for pointing out that it is a 'bytearray'.

I am going to close this. Just curious, what is the normal format if it isn't a 'bytearray'? My WMS is GeoServer, but I add a layer(basically an API, or that's called a proxy) which authenticates user in C#. With some tuning, it returns the 'bytearray' instead.

Or i should ask, apart from 'bytearray' format, what is the usual format used?

Again, Thanks a lot for your solution!

**Comment by Saurbaum** [comment]
I keep seeing these examples and they always seem to assume png.  Does this mean to successfully perform this header addition we have to also take on the responsibility of fetching the image capabilities?

**Comment by mohitb3** [comment]
Here in 2021, I have a more updated solution using fetch and async/await
```
imageLoadFunction: async function (image, url) {
  const init = { ... } // add your request headers
  const response = await fetch(url, init)
  const imageData = await response.blob()
  image.getImage().src = window.URL.createObjectURL(imageData)
}
``` 

and if you're using typescript
```
imageLoadFunction: async function (image: ImageWrapper, url: string) {
  const init = { ... } // add your request headers
  const response = await fetch(url, init)
  const imageData = await response.blob()
  const imageElement = image.getImage() as HTMLImageElement
  imageElement.src = window.URL.createObjectURL(imageData)
}
```

**Comment by mohitb3** [comment]
@Nuyoah-me hard to tell from that. Maybe your `init` variable is misconfigured?
