### ISSUE TITLE
is there a method to refresh the map

### ISSUE THREAD

**Issue by s332401890** [openlayers/ol3#5406]
As described in the title

**Comment by bartvde** [comment]
http://gis.stackexchange.com/questions/127972/refresh-the-map-ol3-openlayers3

**Comment by s332401890** [comment]
Thank you for your answer，i've tried it ,but no effect,
No trigger ol.layer.Vector style func

**Comment by bartvde** [comment]
Call changed() on your vector layer. Otherwise show us a jsFiddle.

**Comment by s332401890** [comment]
i know this, there is no better choice.ths ：)
