### ISSUE TITLE
Replace `@api` annotation with `@doc` for types

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5416]
As mentioned in https://github.com/openlayers/ol3/pull/5368#issuecomment-220344323 and https://github.com/openlayers/ol3/pull/5353#issue-154974267, `@api` should be limited to what is exported and usable in user apps. Types, such as typedefs, enums, and options objects, are not exported, but are currently labelled `@api` so they appear in the docs. This should be changed to a new `@doc` annotation for those types which should appear in the docs but not be exported.

I can probably find time for this this month, but it would help if someone could point me in the right direction. Do we need a new `config/jsdoc/api/plugins/` similar to `api.js`? Anything else needed?

**Comment by gberaudo** [comment]
Is this complexity due to the `custom builds` feature?
Do we have stats about the usage of this feature?

**Comment by ahocevar** [comment]
> Is this complexity due to the custom builds feature?

No. `@api` was meant to mark exportable symbols (i.e. those that the compiler does not mangle). It does not matter whether you use all of them (default full build) or a subset (custom build).

**Comment by ahocevar** [comment]
> This should be changed to a new @doc annotation for those types which should appear in the docs but not be exported.

Maybe the doc generator could be made smart enough to automatically include all typedefs, enums and options objects that are used by exportable functions/properties. Something similar is done already with superclasses whose constructors are not exportable.

**Comment by probins** [comment]
so you mean remove the `@api` for these types, and make `jsdoc` output them without any annotation?

**Comment by ahocevar** [comment]
> so you mean remove the @api for these types, and make jsdoc output them without any annotation?

Yes - but it's been a while since I've written the jsdoc plugins for our doc generation, so I cannot provide much guidance at this point unfortunately.

**Comment by gberaudo** [comment]
>> Is this complexity due to the custom builds feature?

> No. @api was meant to mark exportable symbols (i.e. those that the compiler does not mangle). It does not matter whether you use all of them (default full build) or a subset (custom build).

The compiler [now understands](https://github.com/google/closure-compiler/wiki/Releases#june-9-2015-v20150609) the `@export` annotation for properties. With this annotation, exports are automatically generated by the compiler.Could drastically simplify the build process.

**Comment by probins** [comment]
`@export`s are always exported though, which isn't wanted for custom builds

**Comment by probins** [comment]
> but it's been a while since I've written the jsdoc plugins for our doc generation, so I cannot provide much guidance at this point unfortunately.

ok, well, I'll take a look at the jsdoc process, and see if I can work it out. I know in general how jsdoc works, but not at the more detailed plugin level. I'll try a new `@doc` plugin along the lines of `@api`, and if that works that will be the simplest way of doing this for the moment.

**Comment by probins** [comment]
fixed in a different way with #5427
