### ISSUE TITLE
ol.style.Icon: size option not used

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5419]
Edit https://github.com/openlayers/ol3/blob/master/examples/icon.js and add `size: [200, 200]` in `ol.style.Icon`: the size doesn't change.

**Comment by ahocevar** [comment]
According to the docs, this is expected: `Icon size in pixel. Can be used together with offset to define the sub-rectangle to use from the origin (sprite) icon image.`. And I agree that this is counter-intuitive. When I needed to specify a size, I used the `scale` property. But it does not allow you to change the aspect ratio.

**Comment by fredj** [comment]
You're right; `size` is the "crop size", thanks for the clarification !

**Comment by marcjansen** [comment]
I also misunderstood this many times.... can we change the docs... or provide a more intuitive option?

**Comment by bartvde** [comment]
indeed same here

**Comment by bartvde** [comment]
see also some previous discussion here: https://github.com/openlayers/ol3/issues/2720

**Comment by marcjansen** [comment]
So 4 people with 'deeper' knowledge of the library get this wrong every now and then... we should make this more intuitive then, I guess
