### ISSUE TITLE
ol.interaction.Select: too many select event

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5422]
`select` event are dispatched even if no feature is selected or deselected.

To reproduce the issue (?):
 - http://openlayers.org/en/v3.16.0/examples/select-features.html
 - set a beakpoint at https://github.com/openlayers/ol3/blob/v3.16.0/examples/select-features.js#L74
 - mouse click in the ocean

The `select`event is dispatched but no feature is selected or deselected.

Is it the expected behavior ?

**Comment by stewberticus** [comment]
also events come in pairs, set up a counter and you wont see an odd number;
