### ISSUE TITLE
WMS param STYLES is by default sent without =

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/ol3#5430]
This is a regression in 3.16.0. 

Problem can be seen in the example:
http://openlayers.org/en/v3.16.0/examples/wms-image.html?q=wms

WMS request like the following can be observed:
`http://demo.boundlessgeo.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=topp%3Astates&CRS=EPSG%3A3857&STYLES&WIDTH=986&HEIGHT=532&BBOX=-15492472.25%2C2003371.5%2C-5847584.75%2C7205188.5`

Issue existed before and was fixed #242 (pre 3.0) but probably had another cause back then.

**Comment by bjornharrtell** [comment]
Never used `git bisect` before but thought this was a good case to try it out. It tells me that the problem was introduced with 63ebed437b835e06f1e483391644be7cc569593e. I can't say I understand why. @fredj?

**Comment by marcjansen** [comment]
Is `new String()` truthy, while `''` us falsy...?

**Comment by ischas** [comment]
```
if (new String('')) {console.log('true')} else {console.log('false')}
true
```

```
if ('') {console.log('true')} else {console.log('false')}
false
```

**Comment by bjornharrtell** [comment]
Found it. It seems to be the intended behaviour of URI building with Closure Library. See https://github.com/google/closure-library/blob/v20160517/closure/goog/uri/utils.js#L650.

**Comment by probins** [comment]
time to stop using `goog.uri` :-)

**Comment by marcjansen** [comment]
Right. Or to not set the key `STYLES` at all? `undefined !== ''` .

**Comment by bjornharrtell** [comment]
Working on `goog.uri` replacement. `STYLES` is a required parameter and omitting it makes some WMS servers unhappy.
