### ISSUE TITLE
client zoom misses tiles

### ISSUE THREAD

**Issue by ditor2** [openlayers/ol3#5431]
There's a client zoom example page:
http://dev.openlayers.org/examples/clientzoom.html
The issue comes with two simple steps:
1) press the + sign on the navtoolbar to zoom in to the first client zoom level,
2) then press the - sign on the navtoolbar to get back to the original view. Some tiles on the top left part of the map will be white (empty) instead of showing the map tiles.
(Tried with firefox 46.0.1 and chrome 50.0.2661.102m)

**Comment by bartvde** [comment]
wrong issue tracker, use https://github.com/openlayers/ol2/issues instead
