### ISSUE TITLE
VectorLayer.getSource().clear() will work only if user doesn't zoom map

### ISSUE THREAD

**Issue by markokostovski** [openlayers/ol3#5437]
Hello, so, I want to change features on some filter change for my map (show different markers), and I want to remove all current features and add a new ones. So I use `vectorLayer.getSource().clear()` (`this.map.getLayers().a[i].getSource().clear()` => in my case) and all features are removed until map is zoomed in or out. After that all "cleared" features are back on map again. 

Therefore I need effective way of clearing all features in vector. Besides clear(), I've tried .removeFeature(featureThatIWantToRemove) but it will have same result as clear().

Am I missing something? Or is this a known bug? I've spent more then 2 working days on this now..

EDIT: I'm using latest version -> 3.16.0

**Comment by marcjansen** [comment]
Side note: `a[1]` looks dangerous to me.

**Comment by markokostovski** [comment]
I don't have latest code here, it's at my PC at work. But it's done like this, I have 6 layers of tiles with different maps that can be toggled from. My 7th layer is dark overlay and lastly 8th layer is vector with features. 

The way I initialize vector with features (once more, this code is outdated few days, but I need pattern not exact solution):

` let features = new Array(aircrafts);
        let map;
        let activeFeature;
        let hoverFeature;
        // Hate to to this, but maps :(
        let self = this;

        for (let i = 0; i < aircrafts.length; ++i) {

            // Transfer lat and long to coordinates
            let coordinates = new ol.geom.Point(ol.proj.transform([aircrafts[i].lat, aircrafts[i].long], 'EPSG:4326', 'EPSG:3857'));
            features[i] = new ol.Feature({
                geometry: coordinates,
                attributes: aircrafts[i]
            });
        }

        // Draw planes
        let source = new ol.source.Vector({
            features: features
        });

        let clusterSource = new ol.source.Cluster({
            distance: 40,
            source: source
        });

        let styleCache = {};
        let clusters = new ol.layer.Vector({
            source: clusterSource,
            style: function (feature) {
                let size = feature.get('features').length;
                let attributes = feature.getProperties().features[0].U.attributes;

                let image = {
                    scale: 0.8,
                    rotation: attributes.rotation,
                    src: '/images/normal.png'
                };
                let text = {
                    text: size.toString() > 1 ? size.toString() : '',
                    offsetY: 14,
                    color: 'white'
                };

                styleCache[size] = self.newStyle(image, text);
                return styleCache[size];
            }
        });`

and later I put that cluster inside of map, before I initialize it.

I have `a[i]` because when I click, or select, or on render event, I have 8 layers, therefore I have to find which layer is the vector with features that I need.

**Comment by ahocevar** [comment]
What if you also call `clear()` on the cluster source?

**Comment by markokostovski** [comment]
Here jsfiddle, I'm not even going to use my complex project.. Here is example from their website, and in the end you will see setTimeout, which will simulate clearing of all features, but if you zoom in or out, it will re-apear again.

http://jsfiddle.net/eu7nfjtk/

**Comment by markokostovski** [comment]
@ahocevar no matter where I put `clear()` it will either only clear until zoomed in or out, or not work at all.

I'm thinking that it's related to clusters that i've using? Because they are grouping multiple features into single one, and being recalculated on each map zoom. I will try to check more on that today

**Comment by tsauerwein** [comment]
Calling `clear` both on the original vector source and the cluster source fixes the problem:
http://jsfiddle.net/eu7nfjtk/1/

**Comment by markokostovski** [comment]
@tsauerwein, awesome, I will try to implement that.. I'll be back as soon as I check it out

**Comment by markokostovski** [comment]
Wohoo, progress, thx @tsauerwein and @ahocevar, you also said the same thing..

The solution was, as you've said, that I have to clear vector and cluster source:
```
                        this.map.getLayers().a[i].getSource().clear();
                        this.map.getLayers().a[i].getSource().getSource().clear();
```

**Comment by tsauerwein** [comment]
I would recommend you not to rely on code like `a[i]`. This is not part of the API and you risk that your code breaks when updating to a later version of ol3.

**Comment by ahocevar** [comment]
Look at the API docs: http://openlayers.org/en/latest/apidoc/. What you're trying to do is:
```js
 this.map.getLayers().item(i).getSource().clear();
 this.map.getLayers().item(i).getSource().getSource().clear();
```

**Comment by markokostovski** [comment]
It works with `item(i)`, thx guys :)
