### ISSUE TITLE
LineString Arrows example code does not work

### ISSUE THREAD

**Issue by InsaneJ** [openlayers/ol3#5447]
The supplied code of the LineString example does not work. Example can be found here: http://openlayers.org/en/latest/examples/line-arrows.html

The demo on that page works. But the code which you can copy below it does not.

**Comment by bartvde** [comment]
it's because it cannot find the arrow image: 404 on http://fiddle.jshell.net/_display/data/arrow.png

**Comment by ahocevar** [comment]
That's a shortcoming in the way we generate the code for JSFiddle. For now, you'll have to modify the url of the arrow. http://openlayers.org/en/latest/examples/data/arrow.png in this case.

**Comment by InsaneJ** [comment]
Thanks, that solved it :)

My expectation was that the arrows were vectors as well. It hadn't occurred to me that a .png file was used for the arrows.

**Comment by marcjansen** [comment]
Could we use a `data:uri`  as `src` of the icon in the example? Together with a short comment why we do it?

**Comment by ahocevar** [comment]
An image style with `drawGeometry` would be smarter, like in the http://openlayers.org/en/latest/examples/earthquake-custom-symbol.html example.

**Comment by marcjansen** [comment]
Yeah. But we have an example for that, right?

**Comment by ahocevar** [comment]
Also true. We have other examples too that use data with urls relative to the `examples/` directory. Not sure it would make sense to use data uris everywhere. Probably better to either use something other than JSFiddle that allows to upload accompanying data, or to dynamically change the URLs in the code we send to JSFiddle.

**Comment by marcjansen** [comment]
Real urls would also work, probably easier to implement

**Comment by ahocevar** [comment]
True. Especially now that we have http://openlayers.org/en/latest/.

**Comment by marcjansen** [comment]
I'll try to come up with a PR that uses absolute URLs, if you agree. This'll need to wait until tomorrow, though.

**Comment by ahocevar** [comment]
On second thought, let's check first if it wouldn't be easier to do a programmatic search/replace when we generate the JSFiddle code. Because always pointing to http://openlayers.org/en/latest/ when running examples locally might be annoying/slow.

**Comment by marcjansen** [comment]
Search/replace to a datauri or a bersioned URL?

**Comment by ahocevar** [comment]
We do some search/replace for the fiddle code generation already (e.g. cloak api keys). I think it would be safe to use and `'../examples/data/`.

**Comment by ahocevar** [comment]
Could also be versioned instead of `latest`.

**Comment by marcjansen** [comment]
Hmm. Why would we want to have code changing this dynamically? Performance? 

Would be way easier to always use an URL, or not?

**Comment by ahocevar** [comment]
Easier yes, but potentially problematic (point to inexistent files, wrong versions, slow when running locally).

**Comment by marcjansen** [comment]
Ok. Agreed. Who'll do it?

**Comment by ahocevar** [comment]
If you haven't started already, I'm volunteering.

**Comment by marcjansen** [comment]
I already started.

**Comment by ahocevar** [comment]
Oops, read your comment too late. #5449 is my fix.
