### ISSUE TITLE
Disable dragPan doesn't work

### ISSUE THREAD

**Issue by geraldo** [openlayers/ol3#5451]
I create a map deactivating certain default interactions, but some of theme still are active:

```
  interactions: ol.interaction.defaults({
    pinchRotate: false,
    dragPan: false,
    mouseWheelZoom: false
  }),
```
mouseWheelZoom is successfully deactivated while dragPan and pinchRotate still are active.

**Comment by tsauerwein** [comment]
I gave it a quick try and `dragPan: false` correctly disables panning, see http://jsfiddle.net/2w69wcy2/

Could you provide an example that demonstrates the issue?

**Comment by ahocevar** [comment]
Same with `pinchRotate: false`. Works as expected: http://jsfiddle.net/q586vbfa/.

**Comment by geraldo** [comment]
Sorry for the false alarm, seems that my project got to complex for me (http://cartahistorica.muhba.cat/). I manually enabled dragPan somehow later and everything works as expected. Thanks for your great work on OpenLayers!

**Comment by tsauerwein** [comment]
> ... (http://cartahistorica.muhba.cat/).

That's a nicely designed map! :+1:
