### ISSUE TITLE
Need delay for using getPixelFromCoordinate

### ISSUE THREAD

**Issue by cs09g** [openlayers/ol3#5456]
Hi, I'm newbie at OL3.

I was trying to use this function just after the map is initialized.
But, I could not due to frameState == null.
maybe the function is for inner logic, or for something else, so it cause this kind of situation when user access the function directly.

Actually, get pixel from coordination is kind of math. So it shouldn't be waiting until the map really rendered on the screen. for only calculation!

so, I just overrided the function and it may be helpful for someone like me. and you team can refer this.

```
ol.Map.prototype.getPixelFromCoordinate = function(coordinate, resolution, rotation) {
  var frameState = this.frameState_;
  var coords = coordinate.slice(0, 2);

  var coordinateToPixelMatrix = [];

  if (frameState) {
  	coordinateToPixelMatrix = frameState.coordinateToPixelMatrix;
  } else {
    coordinateToPixelMatrix = ol.vec.Mat4.makeTransform2D(
	  	goog.vec.Mat4.createNumber(), 
	  	this.viewport_.clientWidth / 2, this.viewport_.clientHeight / 2,
	  	1 / resolution, -1 / resolution,
	  	-rotation,
	  	-coords[0], -coords[1])
  }

  return ol.vec.Mat4.multVec2(coordinateToPixelMatrix, coords, coords);
};
```

**Comment by ahocevar** [comment]
I'd be careful with this. You might get wrong results, e.g. when the map does not have the final layout yet. It is better to wait with the first coordinate to pixel conversion until the map is rendered. You do not need a timeout for this, we have the `'postrender'` event on `ol.Map`. So in your initialisation code, you could do something like this:
```js
map.once('postrender', function() {
  // safe to call map.getPixelFromCoordinate from now on
});

**Comment by cs09g** [comment]
Thank you, that works great!

But, how can I use it in specific function?
I mean how can I use this function as one of API's list?
i.e.)
```
this.map = map;
// ... (omit) ...
myfunction = function() {
   // need map.getPixelFromCoordinate
   // this.map.once("postrender", function()) is not possible
}
```

of course, if I cover all by map.once("postrender", function()), it's fine.
however, in the situation when we can't cover, it is not very helpful.

**Comment by ahocevar** [comment]
What about something like
```js
getPixelFromCoordinateAsync = function(coordinate, callback) {
  var pixel = map.getPixelFromCoordinate(coordinate);
  if (pixel) {
    window.setTimeout(function() { callback(pixel); }, 0);
  } else {
    map.on('postrender', function() {
      getPixelFromCoordinateAsync(coordinate, callback);
    });
  }
}
```

**Comment by danielsefton** [comment]
Calling getPixelFromCoordinate works when you call it in the 'postrender' event, but it's not working if I call it in the 'pointermove' event, and I'd expect that by the time I've moved my cursor the frameState_ will have been populated, but it seems not. I'm guessing it's some kind of JavaScript rule that I'm missing. I tried registering the 'pointermove' event within 'postrender' success callback, but that doesn't work either. Any idea how to combine the use of 'postrender' with 'pointermove'? Thanks!

**Comment by ahocevar** [comment]
That should work fine:
```js
map.once('postrender', function() {
  map.on('pointermove', function(e) {
    var pixel = e.pixel;
    var coordinate = e.coordinate;
  });
});
```
Note that you don't need to use `getPixelFromCoordinate`, because the `pointermove´ event has both `pixel` and `coordinate` properties.

**Comment by bradleytaftsmith** [comment]
I have a question similar to this that may not warrant opening another issue. This seems like a good place to ask, though I would be happy to take elsewhere if preferable.

Is there any sort of 'delay' or 'pause' option on the `pointermove` event?

OL2 had a few documented options to delay interactions on hover events like so: http://dev.openlayers.org/examples/hover-handler.html

I've been looking for examples and documentation on how to do the same thing in OL3, and coming up short.
