### ISSUE TITLE
Refresh layer does not work

### ISSUE THREAD

**Issue by AnatolyAG** [openlayers/ol3#5461]
refresh stopped working layer.
before
`var tmpSource = LayerOl.getSource ();
tmpSource.setTileUrlFunction (tmpSource.getTileUrlFunction ());
`
It led to clear your cache and re-load layer
now there is no.
is there another way to reset the layer?

**Comment by cs09g** [comment]
how about to use
```
getSource().refresh()
```

**Comment by AnatolyAG** [comment]
Thank you already saw. the previous version was not well that we decided to introduce this approach and the various workarounds were not.
