### ISSUE TITLE
Typo in webglmaprenderer.js

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#5464]
In the file https://github.com/openlayers/ol3/blob/master/src/ol/renderer/webgl/webglmaprenderer.js, on line 199, there should be goog.webgl.TEXTURE_MIN_FILTER instead of goog.webgl.TEXTURE_MAG_FILTER.

**Comment by gberaudo** [comment]
You are right @jan-tosovsky-cz, thanks. I created PR https://github.com/openlayers/ol3/pull/5469 with the fix.
