### ISSUE TITLE
Layer spy example in IE 9 virtual environment

### ISSUE THREAD

**Issue by cs09g** [openlayers/ol3#5468]
I tested Layer spy example in IE 11 and it worked perfectly.
then I changed browser version to 9 in F12 tools and it shows an error.
it highlights ```this.element.classList.add("ol-hidden")``` 
and says ```this.element.classList``` is undefined or null so it can't use ```add```.

is this happening the same in real IE 9 ?

I guess it is the part in ol-debug.js
```
/**
   * @private
   * @type {number|undefined}
   */
  this.rotation_ = undefined;

  if (this.autoHide_) {
    this.element.classList.add(ol.css.CLASS_HIDDEN);
  }
```

**Comment by ischas** [comment]
Since 3.15 you need a polyfill for this.

https://github.com/openlayers/ol3/releases/tag/v3.15.0

**Comment by cs09g** [comment]
Thanks @ischas !
load polyfill then it's done?

**Comment by ischas** [comment]
Load a polyfill like 
`<script type="text/javascript" src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>`
before you load the ol3-library and you're fine.
