### ISSUE TITLE
Slimerjs no longer supporting downloads to Travis

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5470]
Since a few days ago, Travis has stopped working on my branch, getting 403 errors trying to download the slimerjs package. This seems to be because the slimerjs server has blocked access from AWS and hence Travis; see https://github.com/graingert/slimerjs/issues/39.

I'm assuming that it stopped working on my branch because a cached copy expired, and that it will stop working on ol master whenever that cached copy expires.

The slimerjs people are saying that a copy should be available in the user dir instead of Travis downloading it every time from their server - it is a large package. Any ideas on how best to implement this?

**Comment by tschaub** [comment]
I'd like to try moving back to Karma to run tests in various browsers.  Travis has Firefox installed (https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI).  We could configure Karma to run our tests on Firefox there.  It would be nice to get rid of the Phantom and Slimer dependencies.

**Comment by tschaub** [comment]
I'll try to put up a branch with Karma later today.

**Comment by marcjansen** [comment]
Plus one for karma!

**Comment by graingert** [comment]
slimerjs 0.960.2 should fix your problem for now

**Comment by tschaub** [comment]
Great.  If someone can solve any immediate problems with SlimerJS 0.960.2, please go ahead.  The Karma work is going to be more involved, so I'll just continue on that separately.

**Comment by graingert** [comment]
https://github.com/openlayers/ol3/pull/5479

**Comment by ahocevar** [comment]
Fixed with #5479.

**Comment by probins** [comment]
yup, Travis now works again on my fork 👍
