### ISSUE TITLE
crossOrigin option is not documented

### ISSUE THREAD

**Issue by aberenyi** [openlayers/ol3#5472]
I cannot see why this should not be mentioned in the API docs, but correct me if I'm wrong.

In the use case of map printing w/ html2canvas + jsPDF this can be really important.

Cheers

**Comment by bartvde** [comment]
What do you mean it's not documented? See e.g. here: http://openlayers.org/en/latest/apidoc/ol.source.TileWMS.html

You cannot search for properties in the API docs though, that is a known issue.

**Comment by aberenyi** [comment]
Oh, my bad then.

I didn't know that you cannot search for props - gonna close this.
