### ISSUE TITLE
Vector Tiles data source will soon disappear

### ISSUE THREAD

**Issue by migurski** [openlayers/ol3#5473]
Hi,

In approximately two months, @iandees and I will be turning off the experimental Vector Tiles service hosted at https://openstreetmap.us/~migurski/vector-datasource/. Going through our referer logs, we’ve found these openlayers.org pages using the service:

* http://openlayers.org/en/latest/examples/osm-vector-tiles.html?q=vectortile
* http://openlayers.org/en/v3.15.1/examples/osm-vector-tiles.html?q=vector
* http://openlayers.org/en/v3.0.0/examples/tile-vector.html
* http://openlayers.org/en/v3.1.0/examples/tile-vector.html
* http://openlayers.org/en/v3.5.0/examples/tile-vector.html
* http://openlayers.org/en/master/examples/osm-vector-tiles.html
* http://openlayers.org/en/v3.2.1/examples/tile-vector.html
* http://openlayers.org/en/v3.15.1/examples/osm-vector-tiles.html
* http://openlayers.org/en/latest/examples/osm-vector-tiles.html

My recommendation is to switch these pages to using Mapzen’s equivalent, supported service: https://mapzen.com/projects/vector-tiles/. We may provide HTTP 301 redirects for individual tiles after August, which may work seamlessly.

**Comment by marcjansen** [comment]
Thanks for telling us!
