### ISSUE TITLE
Renderer performance is very poor on Firefox (47)

### ISSUE THREAD

**Issue by gholol** [openlayers/ol3#5483]
Hello, I'm experiencing some problems with the performance on the newest firefox.

I have a custom map in which I'm using a pretty large (2620x2620) static image (svg).

Now, normally,  it works okay. Dragging over the layer is fine. But It gets  awfully slow on zooming in and out. When I'm using zoom, rendering gets very choppy and RAM increases up to 1-1,5GB, and can even cause the whole browser to crash. The same map works super fluently in chrome, where RAM stays at the same level, no matter what...

Is there any way to fix this?

**Comment by ahocevar** [comment]
Look at your SVG file. Does it have a width and height in pixels specified in the svg root element, e.g.
```xml
<svg width="2620" height="2620">
```
If it doesn't, you might want to add that.

**Comment by gholol** [comment]
Yes, width and height are set, there's no change. 

Performance logs while zooming in an out.

Firefox: 
![firefox](http://i.imgur.com/XGYfcHL.png)

Chrome:
![chrome](http://i.imgur.com/jJqFB6n.png)

**Comment by gholol** [comment]
After being unable to identify the issue, I rewrote everything to Leaflet.
