### ISSUE TITLE
fit 3857 tile map data to 4326 proj map

### ISSUE THREAD

**Issue by s332401890** [openlayers/ol3#5485]
```
mapOption = {
	layers : [new ol.layer.Tile({
			source : new ol.source.XYZ({
				url : 'mapserver',
				projection : sourceProj
			})
		})]
	view : {
		center : [0, 0],
		zoom : 1,
		projection : mapProj,
		minZoom : 1,
		maxZoom : 12
	}
}
```
this is my map option ,i have do my best to fit 3857 tile map data  to 4326 proj
when 
sourceProj = "EPSG:4326"
mapProj = "EPSG:4326"
result is  Antarctic disappeared on the map

when 
sourceProj = "EPSG:3857"
mapProj = "EPSG:4326"
retult is Pictures will be compressed

i also see http://openlayers.org/en/latest/examples/xyz-esri-4326-512.html  this example but my picture is 256x256  this not works very well. some tile rquest is wrong and there are also some error in tileRange

i will paste this examples code soon

**Comment by s332401890** [comment]
```

var projection = ol.proj.get('EPSG:4326');
var projectionExtent = projection.getExtent();

var tileSize = 256;

var maxResolution = ol.extent.getWidth(projectionExtent) / (tileSize * 2);
var resolutions = new Array(28);
var z;
for (z = 0; z < 28; ++z) {
	resolutions[z] = maxResolution / Math.pow(2, z);
}

var urlTemplate = '3857mapserver';

//数据源的layer
var MapDataSource = this.MapDataSource = {
	"GIS" : new ol.layer.Tile({
		source : new ol.source.TileImage({
			crossOrigin : null,
			//extent: projectionExtent,
			projection : projection,
			tileGrid : new ol.tilegrid.TileGrid({
				extent : projectionExtent,
				origin : ol.extent.getTopLeft(projectionExtent),
				resolutions : resolutions,
				tileSize : tileSize,
				minZoom : 1
			}),
			tileUrlFunction : function (tileCoord, pixelRatio, projection) {
				var z = tileCoord[0];
				var x = tileCoord[1];
				var y = -tileCoord[2] - 1;
				// wrap the world on the X axis
				var n = Math.pow(2, z + 1); // 2 tiles at z=0
				x = x % n;

				if (x * n < 0) {
					// x and n differ in sign so add n to wrap the result
					// to the correct sign
					x = x + n;
				}

				return urlTemplate.replace('{z}', z.toString())
				.replace('{y}', y.toString())
				.replace('{x}', x.toString());
			},
		})
	})
};
```

**Comment by s332401890** [comment]
sorry for this stupid question , i have solved this problem by  debugging ol3.js.
because 3857 map is square and tileRange must be power(4,n).
so projectionExtent  must be a square .， i have tested  it works well ,if this is uesfull can you add a example for this?

**Comment by s332401890** [comment]
i have another question . 4326 is a 2:1 rectangle data  and 3857 is a 1:1 square  data? can i understand that like this ?

**Comment by craigsnyders** [comment]
This may help your understanding: http://epsg.io/3857 and http://epsg.io/4326
EPSG:3857 bounds in WGS84 stop at 85.06°S and 85.06°N, whereas EPSG:4326 goes all they way to 90°.

**Comment by craigsnyders** [comment]
This may help your understanding: http://epsg.io/3857 and http://epsg.io/4326 
EPSG:3857 bounds in WGS84 stop at 85.06°S and 85.06°N, whereas EPSG:4326 goes up to 90°

**Comment by s332401890** [comment]
i get some error , when projectionExtent must be a square ,the map location is wrong.but i find http://epsg.io/4326  and http://epsg.io/3857 is all right , can i know the code of  http://epsg.io  how is it load google mapd tile data? to fit 3857 data  to 4326 proj

**Comment by s332401890** [comment]
it load 3857 data ,when show it translate 3857 to 4326?

**Comment by s332401890** [comment]
I think it might be my requirement is unreasonable

**Comment by craigsnyders** [comment]
`projectionExtent` can be a rectangle of any size - it simply limits tells openlayers the boundary of your source so that it will not request tiles which are unavailable, or restricted.  

I don't really understand your requirement, but you're exactly right that part of antarctica is cut off using a view with projection EPSG:3857.
