### ISSUE TITLE
Replacing goog.Uri

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5486]
This is only used in KML format. It would be possible to reproduce the current code, but essentially this is already natively available as the URL() constructor in all browsers except IE https://developer.mozilla.org/en-US/docs/Web/API/URL/URL My suggestion would be to use URL() and add a comment to the docs and the release notes that those wanting to support IE should use a polyfill, for example, from cdn.polyfill.io

**Comment by ahocevar** [comment]
Does the URL() constructor work in Edge? If so, I agree to your suggestion @probins. If not, I think we should use custom code to resolve URLs in ol.format.KML.

**Comment by bartvde** [comment]
I've used https://www.npmjs.com/package/url-parse as well for this purpose

**Comment by ahocevar** [comment]
But I don't think we want to bring this dependency into OpenLayers.

**Comment by probins** [comment]
> Does the URL() constructor work in Edge?

according to https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/spec/whatwg-url/ yes, though I don't use Windows myself and can't verify this. (All that's needed here is the constructor, and then the href property of the created instance.)

**Comment by ischas** [comment]
![url-edge](https://cloud.githubusercontent.com/assets/8558126/16144443/497f161e-3473-11e6-9245-1289dd3d0cb8.png)

**Comment by probins** [comment]
thanks @ischas 

I'll create a PR using URL() then

**Comment by probins** [comment]
this is more complicated than I thought, because `goog.Uri` is also used in 4 test files. This runs in Node, which does not implement URL(), so maybe I'll have to go back to implementing the current goog code?

**Comment by bartvde** [comment]
why not use url-parse for the tests then?

**Comment by probins** [comment]
How does that work in tests? How do you `require` the module?

**Comment by bartvde** [comment]
Argh I didn't think about our test setup :-) been working on a project where I can just require in the unit tests for too long ;-)

**Comment by probins** [comment]
I think what I have to do is add the URL polyfill to `test/index.html` - trying that now ...

**Comment by probins** [comment]
yup, that works :-)

**Comment by tschaub** [comment]
> This runs in Node, which does not implement URL(), so maybe I'll have to go back to implementing the current goog code?

The tests are not run in Node.  They are run in PhantomJS though.  Perhaps this is what you meant.

**Comment by probins** [comment]
which uses QtWebKit I see - either way, doesn't support URL()
