### ISSUE TITLE
ol.View minResolution is overriden if set

### ISSUE THREAD

**Issue by KlemenSpruk** [openlayers/ol3#5487]
Hello!
I have noticed that if I pass minResolution to ol.View opitions min resolution value is overriden in 
ol.View.createResolutionConstraint_ function.
Why is this propery overriden with calculation from maxResolution property? Is this ok?

**Comment by ahocevar** [comment]
Not sure what code you are referring to. https://github.com/openlayers/ol3/blob/v3.16.0/src/ol/view.js#L723-L735 looks to me like it does the right thing. Am I missing something?

**Comment by KlemenSpruk** [comment]
Hello!
In line https://github.com/openlayers/ol3/blob/v3.16.0/src/ol/view.js#L740 minResolution is calculated from maxResolution. And then view object on map has different minResolution property than user provided minResolution. Is there a way to set view minResolution property to user provided value?

**Comment by ahocevar** [comment]
https://github.com/openlayers/ol3/blob/v3.16.0/src/ol/view.js#L740 should only adjust `minResolution` to the closest resolution, considering the `zoomFactor`. So this is very likely ok. Do you have a configuration to share that made you think it is not?

**Comment by KlemenSpruk** [comment]
I agree that is ok to adjust minResolution to highest zoom level resolution. But is it possible to bypass this and use user provided resolution?

**Comment by ahocevar** [comment]
@KlemenSpruk You can always provide a full array of `resolutions`, which will be fully respected.

Since resolutions are translated to zoom levels by applying a zoom factor, starting at `maxResolution`, the zoom factor would be incorrect for transitioning to `minResolution` at the highest zoom level.
