### ISSUE TITLE
How do I get on the listserv

### ISSUE THREAD

**Issue by thomasgwatson** [openlayers/ol3#5491]
Can't easily find a way. Is it dead?

Trying to get help with: http://stackoverflow.com/questions/37871588/bug-when-converting-synthetic-points-example-from-openlayers-3-5-to-3-16

**Comment by tschaub** [comment]
There is a Google Group that is intended to be about OpenLayers development (I don't have the links handy).  The idea with encouraging people to use StackOverflow for usage questions was that the answers would be more easily discovered by others.

**Comment by thomasgwatson** [comment]
Yes, certainly want to move discussion into the indexed/searchable domain! However, my impression was that there are still a collection of wise-heads on the mailing list. I'll search for the google group
