### ISSUE TITLE
Map distorted when initialized 

### ISSUE THREAD

**Issue by exotfboy** [openlayers/ol3#5493]
When the map are loaded at the first time, the map will be distorted once the viewport is small:
![image](https://cloud.githubusercontent.com/assets/16457917/16180810/90c9c1ee-36c2-11e6-8178-d1afb2501b14.png)

While when you resize the window, the map will refresh to normal:
![image](https://cloud.githubusercontent.com/assets/16457917/16180813/9fdef5f0-36c2-11e6-8acb-38148bbf09d7.png)

[Codepen](http://codepen.io/anon/pen/EygQjM)

**Comment by ahocevar** [comment]
You have to call `map.updateSize();` at the end of your `resize` function. Otherwise the map does not know that you have resized its container.
