### ISSUE TITLE
Custom Style Filled Polygon and Serrated PolyLine

### ISSUE THREAD

**Issue by LeventOzcelik** [openlayers/ol3#5500]
Hey,
I want to give special style to my feature but I can only customize dashed lines on openlayers3.

https://i.imgsafe.org/8fc2ad8af0.jpg

I want filled polygon or custom dashed PolyLine. How can I do that ?

**Comment by ahocevar** [comment]
For polygons, you can do all this. For line strings, you are limited to dash styles. See #5398 for a ticket that links to examples.

**Comment by LeventOzcelik** [comment]
Thank you ahocevar i will use styling polygon for now
