### ISSUE TITLE
Please expose several public methods of ol.tilegrid.TileGrid in public api

### ISSUE THREAD

**Issue by ashchurova** [openlayers/ol3#5502]
Please expose the following methods of ol.tilegrid.TileGrid.prototype in your api:

1. ol.tilegrid.TileGrid.prototype.getZForResolution
2. ol.tilegrid.TileGrid.prototype.getTileRangeForExtentAndZ

I have implemented CartoDb Torque Layer for OpenLayers. I would like to contribute this implementation back to CartoDb and it is imposible without these methods.   Thanks.

**Comment by fredj** [comment]
`ol.tilegrid.TileGrid#getTileCoordExtent` is already exposed, do you have any issue accessing this function?

**Comment by ahocevar** [comment]
@ashchurova Would you mind pointing us to your code? Making `#getZForResolution` exportable sounds reasonable, but `#getTileRangeForExtentAndZ` would expose tile ranges, which I'd rather keep internal. Also, have you considered contributing your torque layer to OpenLayers instead of CartoDB? We do have `ol.source.CartoDB` already, so having Torque support would make sense.

**Comment by ashchurova** [comment]
@fredj - you are correct, my bad, getTileCoordExtent is already a part of public api. Than you.

**Comment by ashchurova** [comment]
@ahocevar I work for Bloomberg LP and we are working closely with CartoDb on custom mapping solutions for our terminal so it was natural to us to contribute to them first. There are also legal policies that I have to obey in order to contribute my work to open source and my contribution request has to be approved by legal department first. Cartodb has been approved by legal before for other projects so it is moving a little faster.
We use OpenLayers as well and would like to make a contribution to your Cartodb support. I am aware you guys introduced new CartoDb source but we can't use it as it is because our CartoDb maps configuration is saved in json file and generation of map's tiles url was also modified for Bloomberg.   Right now I load the json file and use combination of ol.source.XYZ and ol.source.TileUTFGrid sources and ol.layer.Tile layer to display CartoDb map in OpenLayers.
