### ISSUE TITLE
ScaleLine size is calculated incorrectly with EPSG4326

### ISSUE THREAD

**Issue by matthiasdailey-ccri** [openlayers/ol3#5503]
The ScaleLine is supposed to adjust its size when you pan vertically, as you can see in the OL Example: http://jsfiddle.net/g6t89mxb/. When you pan the map up and down, the scale line gets wider and smaller.

**But**, when you change the View projection to `EPSG:4326`, the scale line does not adjust its size anymore: http://jsfiddle.net/jtbtotq2/

I think it was caused by this commit: https://github.com/openlayers/ol3/commit/6b8da1237c4009974c351e0c43de283ad5f9310f#diff-a431a0bf935fd3aa3295a310b6a39a42R196

EPSG:4326 uses degrees, and it appears to implement the `.getPointResolution` method incorrectly:
https://github.com/openlayers/ol3/blob/29c8af755930c2ad1633377ffceb61fa8eab0a84/src/ol/proj/epsg4326projection.js#L40
```
ol.proj.EPSG4326_.prototype.getPointResolution = function(resolution, point) {
  return resolution;
};
```

Because the point resolution should change as the latitude changes, right? One pixel at the north pole is a fraction of the distance of one at the equator. So the implementation of... wait.. EPSG4326 uses degrees, so the degree distance would be the same at every latitude. So this method is correct.

**So actually**, it would seem that the `ol.control.ScaleLine.prototype.updateElement_()` method is the thing that isn't working well with ESPG4326 (or any projection that uses degrees as its units, I think).

**Comment by matthiasdailey-ccri** [comment]
I think that https://github.com/openlayers/ol3/issues/4819 might be a similar problem

**Comment by bill-chadwick** [comment]
I think the .getPointResolution implementation is correct as it returns the point resolution in degrees (the units of the projection) which is invariant for 4326. The problem lies with the ScaleLine not dealing with a scale line in non degree units when the view projection has units of degrees.

**Comment by ahocevar** [comment]
@bill-chadwick is right. A pragmatic "fix" for this issue is to document the ScaleLine control properly, i.e. clearly state that the scale line is based on y-axis distances, not x-axis. I created #5534 for this.

**Comment by matthiasdailey-ccri** [comment]
I see. So 4326's X and Y axes have different meters-per-pixel values, and the scale line measures the Y axis value. And for 4326, the Y value does not change with longitude, but the X value does change with longitude. Let me know if I misread any of that.

In previous versions (like 3.11.2), the scale line's size (with metric units) _did_ change with the longitude. ([jsfiddle](http://jsfiddle.net/2wq5qfb4/2/)). Was that a bug then, in previous versions?

**Comment by bill-chadwick** [comment]
I think you meant to say the X value changes with latitude. There may have
been different treatments for 4326 in OL  in the past but they would not
have been any more valid than the current treatment.

Bill

**Comment by matthiasdailey-ccri** [comment]
@bill-chadwick , yes, sorry I got those terms mixed up. 

This is what I meant to say:
With 4326, no matter what latitude, the _height_ of a pixel represents the same amount of meters, whereas the _width_ varies in the amount of meters it represents.
