### ISSUE TITLE
can not set min/max zoom for TileImage layer

### ISSUE THREAD

**Issue by cs09g** [openlayers/ol3#5515]
I want to set min/max zoom after done creating the map.
So I tried to set the layer to call setMaxResolution as an indirect access.

But then, it half works. 
That is, map only shows in the min/max resolution range but I still can zoom in/out. 

when resolution range is [1000 ~ 500] and the level is [10 ~ 11] 
then, map is being rendered in 10~11 and if I zoom in to 12, it doesn't rendered the map.

1. should I block the zoom event for the map by myself? 

2. have any plan to support setMin/MaxZoom for layer? 
now it supports by only min/maxResolution.

**Comment by cs09g** [comment]
I tried to set max/minZoom in source.tilegrid then, it doesn't load new tiles of the resolution/level but still zooming as an image.

**Comment by ahocevar** [comment]
If you want to restrict how far users can zoom in/out, you have to configure that on the view, not the layer. The layer source will always provide an image that best matches the resolution requested by the view.

**Comment by cs09g** [comment]
but if I set min/maxZoom on the view, it doesn't show correctly. 
```
view: new ol.View({
  extent: extent,
  projection: projection,
  resolution: resolution,
  zoom: zoom,
  minZoom: minZoom,
  maxZoom: maxZoom,
})
// source = ol.source.TileImage
// tileLayer = ol.layer.Tile({source:source})
// addLayer(tileLayer)
```
when I code like this, min ~ max seems weird. my level is 0 ~ 13 but it works between -2 ~ 9

and my question is how to limit this min/max zoom after setting the map.

**Comment by ahocevar** [comment]
When you want to limit the zoom levels after creating the map, you just use `map.setView()` to assign a different view.

Not sure what you mean by "doesn't show correctly". But if the resolutions of your view match the ones of your layer, the layer will display without up-/downscaling. In your view configuration, you have to set iether zoom or resolution. Not both.

**Comment by cs09g** [comment]
Thank you for answering. 
actually that is 'resolutions'

setting zoom: 9, and minZoom: 0 then initialized with zoom 9
setting zoom: 9, and minZoom: 1 then initialized with zoom 8
setting zoom: 9, and minZoom: -1 then initialized with zoom 10
...

can't understand why works like this.
