### ISSUE TITLE
Property 'condition' is missing on olx.interaction.DragPanOptions

### ISSUE THREAD

**Issue by SamuelBerger** [openlayers/ol3#5518]
Hi,
The property 'condition' for olx.interaction.DragPanOptions is not declared in the olx.js even though it is accepted in the constructor. 
Do you prefer a PR for such little things or just pinpointing it in an issue?

Thanks, 
sam

**Comment by tsauerwein** [comment]
Yes, you are right. It would be great if you could provide a PR!

**Comment by fredj** [comment]
#5522
