### ISSUE TITLE
Skipped feature hit detection

### ISSUE THREAD

**Issue by jsalankey** [openlayers/ol3#5527]
At [canvasvectorlayerrenderer.js:170](https://github.com/openlayers/ol3/blob/master/src/ol/renderer/canvas/canvasvectorlayerrenderer.js#L170), the `forEachFeatureAtPixel` method deliberately doesn't use the `frameState.skippedFeatureUids` property. Is there a particular reason why an empty object is passed in place of the skipped features for the purposes of hit detection? 

It seems like this would add hit detection overhead. It's also causing a problem where hidden features are being hit detected and highlighted on hover in our application. This can be worked around within the app, but it seems like they shouldn't even be hit detected in the first place if they are hidden.

**Comment by ahocevar** [comment]
There is a purpose for the way it is done: the Select interaction moves features to a different layer to apply the select style. In order to still be able to get feature information for selected features, it is necessary that skipped features get hit detected.

I have proposed [elsewhere](https://github.com/openlayers/ol3/pull/5255#issuecomment-214836638) that the whole feature skipping stuff is fragile and should be removed, but I didn't get [much response](https://github.com/openlayers/ol3/pull/5279).

**Comment by schmidtk** [comment]
@ahocevar I noticed something else related in [canvasreplay:267-273](https://github.com/openlayers/ol3/blob/a30d4843cf5fe66cc3fdbec358d4a57a8c287c4e/src/ol/render/canvas/canvasreplay.js#L267).

If the feature is determined to be skipped (line 267) or outside the hit extent (line 271), `i` is set to the value in the last instruction for `ol.render.canvas.Instruction.BEGIN_GEOMETRY`. This is the `ol.render.canvas.Instruction.END_GEOMETRY` instruction for that feature, which makes the feature callback to check if the feature is at that location. Shouldn't it instead immediately move to the next begin feature instruction? This would avoid unnecessary expensive calls like context.getImageData if we have already determined the feature should not be returned by hit detection.

**Comment by ahocevar** [comment]
@schmidtk I have not experimented with it, but you may be right. Would you be willing to spend some time playing with it, and submit a pull request if there is indeed potential for improvement? I'd be glad to review.

**Comment by schmidtk** [comment]
Yeah can do. I tried the change at work and it seemed considerably faster for features outside the hit extent and I didn't notice any breaking behavior. I'll test it out some more tomorrow, but figured I'd run it by you first.

**Comment by ahocevar** [comment]
Related to #4232.
