### ISSUE TITLE
"null is not an object" if ol.js is loaded before the body tag

### ISSUE THREAD

**Issue by spatialillusions** [openlayers/ol3#5554]
With version 3.17.0 I get the following error if ol.js is loaded before the body-tag in my document:
TypeError: null is not an object (evaluating 'a.webkitRequestFullscreen')
ol-debug.js:25495

I get similar errors in Safari, Chrome and Firefox.

How to reproduce:
- Go to http://openlayers.org/en/v3.17.0/examples/animation.html
- Copy the code and create a new html file just containing the code
- Open the new html file.

**Comment by ahocevar** [comment]
This is a regression and will be fixed with #5548.
