### ISSUE TITLE
Problem with 3.17.0

### ISSUE THREAD

**Issue by LaySoft** [openlayers/ol3#5555]
I tried the newest 3.17.0 version with my existing projects, but it doesn't works:

Error: TypeError: a is null
Source: http://openlayers.org/en/v3.17.0/build/ol.js
Line: 116

And in my code:

Error: ReferenceError: ol is not defined

I tried some [examples]( http://openlayers.org/en/latest/examples/) with copy paste the code, but neither works.

**Comment by marcjansen** [comment]
Related to https://github.com/openlayers/ol3/pull/5548 ??

A  new patch release is likely to come soon.

**Comment by bartvde** [comment]
Should be fixed with 3.17.1
