### ISSUE TITLE
Content Security Policy error (since v3.16.0, included)

### ISSUE THREAD

**Issue by gvlachos** [openlayers/ol3#5572]
In my project we have Content Security Policy setup (https://w3c.github.io/webappsec/specs/content-security-policy, https://developer.chrome.com/extensions/contentSecurityPolicy).

While trying to upgrade the OpenLayers I am getting the following error since v3.16.0 (included)

 ``Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'". ``

in the following line:

 `` ol.global = Function('return this')();  ``

Note that using unsafe-eval is strongly recommended against (https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval)

**Comment by ahocevar** [comment]
While unsafe-eval is not unsafe here because we do not pass user provided content to the `Function` constructor, the problem reported here is a real one. There are other ways to get the global object, but the one we use now is the one that requires the least amount of code.

**Comment by marcjansen** [comment]
> …  that requires the least amount of code

…and the one we thought was less error prone and guaranteed to always produce the correct global object; even though I also labeled it 'obscure'.

See #5178

**Comment by ahocevar** [comment]
#5573 solves this in a way that may look even more obscure to some 😄

**Comment by marcjansen** [comment]
Obscureness: confirmed

**Comment by spatialillusions** [comment]
Or you should be able to do:
ol.global = new function(){return this;}

**Comment by ahocevar** [comment]
@spatialillusions Are you sure that this always works? In a commonjs environment, this will probably not return the global object because unlike using eval, your code will be executed in the current scope.

**Comment by spatialillusions** [comment]
You could be right about about this, I have to admit I didn't test it, just
know that I have done things similar to that in other projects.

**Comment by ahocevar** [comment]
@gvlachos: Does the following work for you:
```js
ol.global = typeof window == 'undefined' ? Function('return this')() : window;
```

**Comment by gvlachos** [comment]
@ahocevar yes that worked.
