### ISSUE TITLE
Combine Constrained Zoom and Zoomify example

### ISSUE THREAD

**Issue by fschroiff** [openlayers/ol3#5581]
When using Zoomify tiles the `minzoom` and `maxzoom` view options do not seem to have any effect. Or they work differently than I would expect. 

I created a code example: http://jsfiddle.net/r4ku2jwz/

You can zoom in and out as far as you like even though `minzoom` and `maxzoom` are set.

**Comment by fredj** [comment]
It's `minZoom` and `maxZoom` instead of `minzoom` and `maxzoom`

Updated jsfiddle: http://jsfiddle.net/r4ku2jwz/1/

**Comment by fschroiff** [comment]
OMG 😳
