### ISSUE TITLE
clustering labels across layers

### ISSUE THREAD

**Issue by nospor** [openlayers/ol3#5585]
Right now I have few layers. Each layer has clustering and it works fine for specific layer but still labels from different layers overlap. Is it possible to add clustering for labels across layers?

**Comment by ahocevar** [comment]
No, this is currently not possible.

**Comment by nospor** [comment]
Thx for answer. But is there a chance that ol3 will have this functionality in some next release?

**Comment by ahocevar** [comment]
As far as I know, nobody is currently working on something like this.

**Comment by nospor** [comment]
So maybe do you know how people right now handle with problem, that labels from different layers overlap?

**Comment by ahocevar** [comment]
This question is probably better suited for [Stackoverflow](http://stackoverflow.com/tags/openlayers-3/).

**Comment by nospor** [comment]
I've asked there but know one answered :( 

http://stackoverflow.com/questions/38179782/clustering-across-layers
