### ISSUE TITLE
openlayer with mapquest not working

### ISSUE THREAD

**Issue by dharmender-ucodesoft** [openlayers/ol3#5588]
I am suing openlayer 3 with mapquest but mapquest has been discontinued direct tile access from July 11, 2016.
[Modernization of MapQuest results in changes to direct tile access](http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/)

 I have created API key on mapquest. So how can i pass the key to mapquest using openlayer?

**Comment by bartvde** [comment]
You cannot see: https://github.com/openlayers/ol3/blob/master/changelog/v3.17.0.md#olsourcemapquest-removal for details.
