### ISSUE TITLE
Replace goog.asserts.*

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#5600]
See #4128.

There are several options to replace `goog.asserts.*`. After doing some research, I would like to propose the following:

* Introduce a global `DEBUG` `@define` as replacement for `goog.DEBUG`.
* Use `DEBUG && console.assert()` instead of `goog.asserts.*`.
* Replace assertions that are only there to satisfy the compiler with type casts. These can be easily identified, because the complier will issue errors once they are replaced with `DEBUG && console.assert`.

This approach will work fine in the future with all minifiers that support global defines and can remove dead code. The reason why I suggest to use `DEBUG` and not `ol.DEBUG` is because minifiers like UglifyJS2 do not support namespaces in global defines.

**Comment by marcjansen** [comment]
Can we put this line

```js
DEBUG && console.assert
```

In a method `ol.assert`? Will this be removable as well?

**Comment by ahocevar** [comment]
No, this won't work as nicely @marcjansen. Most minifiers will leave an empty function there. For UglifyJS2, this could be avoided by calling it with `--compress pure_funcs=[\'ol.assert\']`, but that's not a nice workaround I would say.

**Comment by probins** [comment]
Do you have an idea what proportion can be replaced with typecasts?

**Comment by ahocevar** [comment]
@probins I'm not sure, but definitely more than 50%.

**Comment by tschaub** [comment]
Do people feel like we are getting any value from the asserts that are not about type casting?

I can see value in an assert function that was left in for production builds.  Maybe something like:

```js
ol.assert(foo, 123);
```

And if `foo` was not truthy, we would throw with a message like "Expected `false` to be truthy, see http://openlayers.org/en/v4.5.6/errors/#123 for detail.  This would require that we maintain and deploy a page with error messages.

This would make for a much nicer user experience.

**Comment by ahocevar** [comment]
I'm open to suggestions like the above, as long as we do not sacrifice performance. Currently we have some assertions on the hot path, like canvas replays. Those should only remain in minified builds if they are super inexpensive to calculate.

**Comment by tschaub** [comment]
I agree about not having assertions in hot paths.

**Comment by ahocevar** [comment]
Ok cool, I'm working on a pull request now.

**Comment by probins** [comment]
what are the use cases for non-typecast asserts? Can someone give some examples? Writing to console is only useful in test environments. I can see that throwing errors might be useful in production environments, but ISTM this should be limited to a numeric code or something similar which applications can handle. Messages in English don't improve the user experience if the user doesn't read English :-)

**Comment by ahocevar** [comment]
@probins Aside from the type asserts to satisfy the compiler, we have two kinds:

 1. Sanity checks for library developers, e.g. https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/render/canvas/canvasreplay.js#L559-L560
 2. Sanity checks for app developers, e.g. https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/control/scalelinecontrol.js#L247

The (1) style asserts make sense to be stripped out in minified builds, and the (2) style ones make sense to be handled in the way suggested by @tschaub.

**Comment by probins** [comment]
ok, so apps would do a try/catch for your (2) example. In which case, the app would need only a numeric code, 123 in @tschaub's example, which it would map to a list and output an appropriate error message to the user. What would be the purpose of the "Expected false to be truthy, see http://openlayers.org/en/v4.5.6/errors/#123 for detail" string message? AFAICS this just adds unnecessarily to the build size.

**Comment by ahocevar** [comment]
That does not add much to the build size:
```js
ol.assert = function(result, errorCode) {
  if (!result) {
    throw new Error('Expected ' + result + ' to be truthy. See http://openlayers.org/en/' +
        ol.VERSION + '/errors/#' + errorCode + ' for details.');
  }
}
```

**Comment by probins** [comment]
but how does the app handle that? It can't pass that string on to the user, as few users will understand it. What the app needs is the errorCode: `throw errorCode` then
```
catch(errorCode) {
  var msg = lookup(errorCode); // such as 'Invalid capabilities file' in the user's language
  alert(msg); // or whatever
}
```

**Comment by ahocevar** [comment]
We could make it so `ol.assert` can be replaced by a custom function. Then you can do whatever you want. Like e.g. not throw an exception at all, provide your own error messages, etc.

**Comment by probins** [comment]
> I suggest to use DEBUG and not ol.DEBUG

Using a global brings the usual risk of conflicting with other globals called 'DEBUG', but we can change this when we convert to modules. Tools like Uglify are currently a bit behind in implementing ES6 but future versions should be able to handle `import {DEBUG} from ol` or similar.

**Comment by probins** [comment]
> We could make it so ol.assert can be replaced by a custom function

yes, I like that idea. In principle, I agree with @tschaub that it would be useful for apps to have the ability to catch errors. This could also be useful for situations like vector files that do not contain features - not an error as such but the (end) user should be notified.

**Comment by ahocevar** [comment]
I am making good progress, and should have a pull request ready later today. For now, I went with `ol.DEBUG`, which we can change later in case we need to. For `ol.assert`, I created an `Error` subclass with a `code` property, so applications have the error code if they need it.

**Comment by fredj** [comment]
`goog.asserts.*` are gone, thanks @ahocevar
