### ISSUE TITLE
'forEachLayerAtPixel' tile layer method does not account for pixelRatio of device.

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol3#5601]
The method only works if the pixelRatio of the device is 1.

The canvas [height and width ](https://github.com/openlayers/ol3/blob/master/src/ol/renderer/canvas/canvastilelayerrenderer.js#L200-L201) both need to be multiplied by the pixelRatio.

**Comment by ahocevar** [comment]
@Benjaki2, would you be able to provide a pull request with a fix?

**Comment by Benjaki2** [comment]
@ahocevar, sure thing.

**Comment by anzeznidarsic** [comment]
Was a fix for this worked on?

**Comment by ahocevar** [comment]
Fixed with #5731.

**Comment by ahocevar** [comment]
Actually not fixed with #5731,
