### ISSUE TITLE
Ol2 migrate to Ol3 but nothing alike found for getURL with the same parameters.

### ISSUE THREAD

**Issue by wanermiranda** [openlayers/ol3#5604]
Guys, 

I have a working code on Ol2 to use gdal tiles, it is important becase it fits the zoom levels between the bounds. As the layer only starts to appears (at zoom 0) only at the certain point of the big map. 

But I can't find nothing alike in the ol3. 

See the code bellow. 
There are various methods and properties with non related update. 

Ty so much!
```js
function getURL(bounds) {
                  bounds = this.adjustBounds(bounds);
                  var res = this.getServerResolution();
                  var x = Math.round((bounds.left - this.tileOrigin.lon) / (res * this.tileSize.w));
                  var y = Math.round((bounds.bottom - this.tileOrigin.lat) / (res * this.tileSize.h));
                  var z = this.getServerZoom();
                  var path = this.serviceVersion + "/" + this.layername + "/" + z + "/" + x + "/" + y + "." + this.type;
                  var url = this.url;
                  if (OpenLayers.Util.isArray(url)) {
                      url = this.selectUrl(path, url);
                  }
                  if (mapBounds.intersectsBounds(bounds) && (z >= mapMinZoom) && (z <= mapMaxZoom)) {
                      return url + path;
                  } else {
                      return emptyTileURL;
                  }
              }
```

**Comment by ahocevar** [comment]
This looks like a plain `ol.source.XYZ` would be your friend, maybe with a custom `ol.tilegrid.TileGrid`. You'll probably get a better answer on http://stackoverflow.com/tags/openlayers-3. But make sure you provide a working JSFiddle there so the code can be tested.
