### ISSUE TITLE
exposing getFeatures api for ol.source.VectorTile with MVT format

### ISSUE THREAD

**Issue by senthanal** [openlayers/ol3#5607]
Seems getFeatures api is not exposed to ol.source.VectorTile with MVT format. How can I get this functionality?

**Comment by ahocevar** [comment]
`ol.source.VectorTile` is optimized for rendering. It has feature access through `ol.Map#forEachFeatureAtPixel` only. If you want access to all features, you'd have to hook into the `tileLoadFunction` and grab the features in the same pass you use `ol.VectorTile#setFeatures`. This way you'll gather the features tile by tile.
