### ISSUE TITLE
ol.source.VectorTile vs ol.source.TileVector

### ISSUE THREAD

**Issue by senthanal** [openlayers/ol3#5608]
What is the difference(use cases) between ol.source.VectorTile and ol.source.TileVector?
ol.source.VectorTile is for **Vector Tiles**?
ol.source.TileVector? is for **Raster Tiles**?

**Comment by ahocevar** [comment]
`ol.source.TileVector` is not available any more. It has been replaced by `ol.source.VectorTile`.
