### ISSUE TITLE
ol.format.WFSCapabilities

### ISSUE THREAD

**Issue by WillieMaddox** [openlayers/ol3#5610]
Are there any plans to add this? Is there any reason why it wasn't ported over from ol2?

**Comment by ahocevar** [comment]
Like many other non-feature formats, WFS capabilities can be parsed with JSONIX. See https://github.com/highsource/ogc-schemas. We decided to not duplicate the effort, and recommend JSONIX.

**Comment by WillieMaddox** [comment]
Great thanks.  I can work with that.  Question though, you imply WFS is a "non-feature format"?  My understanding was that WMS is a "non-feature" format and WFS is a "feature" format.  Am I backwards on this?

**Comment by ahocevar** [comment]
You were asking about WFS Capabilities, which is a metadata format. OpenLayers comes with GML and WFS readers/writers, which are feature (as in `ol.Feature`) formats.

**Comment by WillieMaddox** [comment]
Ok I get it.  WFS is a feature format, while WFS "Capabilites" is a metadata format.
Thanks.

**Comment by WillieMaddox** [comment]
Ok. This isn't as straightforward as I thought it would be. I can't even get the schemas to load into my scripts. Is there any documentation explaining how to use the ogc-schemas with ol3?

**Comment by ahocevar** [comment]
The documentation for JSONIX can be found here: https://github.com/highsource/jsonix. The ogc-schema package provides the bindings. The best thing is probably to look at the WPS test, since it is also an OGC format: https://github.com/highsource/jsonix/tree/master/nodejs/tests/wps. Especially look at the prepublish script in the package.json there:
```
java -jar node_modules/jsonix/lib/jsonix-schema-compiler-full.jar -catalog catalog/catalog.cat -extension -d mappings schemas/ogc/wps/1.0.0/wpsAll.xsd -b bindings/bindings.xjb
```
