### ISSUE TITLE
Replacing goog.getUid

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5615]
There are currently 75 matches for this in the library. It simply maintains a counter for the library as a whole and then adds one for each call, storing the result in a custom property on the object concerned. It should be straightforward to reproduce this as `ol.uidCounter` and `ol.getUid`. Anyone got any better solutions, or should I put together a PR to do this?

**Comment by ahocevar** [comment]
Basically yes, that's the way to do it. It might make sense to not use `ol.uidCounter` directly, but create something like `ol.events.LISTENER_MAP_PROP_`.

**Comment by probins** [comment]
> currently 75 matches

+ 7 in the tests

**Comment by ahocevar** [comment]
Forget what I said about `ol.events.LISTENER_MAP_PROP`. It would be great if you could create a pull request the way you suggested.
