### ISSUE TITLE
UpdateParams makes the TileWMS layer flicker when called for the first time

### ISSUE THREAD

**Issue by rrutkows** [openlayers/ol3#5617]
OL 3.15
1. Create a TileWMS source without providing an URL in the options.
2. Pass the URLs with the `setUrls` method.
3. Call updateParams after the layer is displayed.
When called for the first time, `updateParams` makes the layer flicker. Probably because `coordKeyPrefix_` is set to an empty string initially. Shouldn't `setUrls` call `resetCoordKeyPrefix_`?

**Comment by ahocevar** [comment]
This should have been fixed in the meantime. Can you try with v3.17.1 or master?

**Comment by rrutkows** [comment]
Tested with 3.17.1 and the issue is there too.

In both 3.15 and 3.17, it's OK, if you pass the urls in the constructor instead of `setUrls`.

**Comment by ahocevar** [comment]
You mean you get the flicker with `updateParams()` every time *after* you have used `setUrls()`? If the problem is what you suspect above, would you be able to create a pull request with a fix?

**Comment by rrutkows** [comment]
No, only the first time. `updateParams` resets the `coordKeyPrefix_` to reflect the current urls, so `coordKeyPrefix_` does not change anymore on subsequent `updateParams` calls.

I'll prepare that pull request.
