### ISSUE TITLE
equivalent of alwaysInRange in OL2

### ISSUE THREAD

**Issue by sylvainpolletvillard** [openlayers/ol3#5618]
Hello,

I have a tile layer configured with a `minResolution` as a global constraint because the tiles server cannot serve tiles with a zoom level over 18. I would like to configure the layer so that the user is able to zoom in  over 18, and get the lowest resolution tiles available, even if pixelated.

This was possible in OL2 with the `alwaysInRange` property. Is there any equivalent in OL3 ? I tried to override `visibleAtResolution` to always return true but then the tiles are requested with unavailable zoom levels.

Thanks

**Comment by ahocevar** [comment]
You'll have to configure the source of the layer with an `ol.tilegrid.TileGrid` that matches what you have available on the server. Then just configure the layer without `minResolution`, and you'll get the desired behaviour.

Explanation: What you configure on the layer is for rendering, and what you configure on the source is for fetching from the server.
