### ISSUE TITLE
Negative Ys on Vector layer

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [openlayers/ol3#5624]
I'm drawing rectangles on a map with two layers: a tiled high res image and a vector layer. 

When I call (new GeoJSON()).writeFeature(feature), all the Y coordinates in in geometry are negative. I'm guessing that the origin is the top of the map and going downward as -Y gets smaller.

**I'm wondering why the Y are negative?**

Before upgrading my app from OL2 to OL3, all my Y coordinates were positive (relative to the bottom of the map, going upward as Y gets bigger). When I draw the OL2 features on a OL3 map, they don't appear anywhere. When I draw my OL3 features on my OL2 map, all features appear BELOW the bottom of the image.

**Is that due to a settings, or is it a change in the default behaviour from OL2 to OL3?** 

I can provide more details about the way I construct my maps and obtain the feature coordinates if that helps.

**Comment by ahocevar** [comment]
This is probably because you set an incorrect view center, or have a different projection configuration. It's probably better to ask this question on http://stackoverflow.com with the openlayers-3 tag, and provide a JSFiddle with your code.

**Comment by geoffroy-noel-ddh** [comment]
http://gis.stackexchange.com/questions/203081/direction-of-the-y-axis-in-openlayers
