### ISSUE TITLE
pointerdrag event isn't always followed by moveend

### ISSUE THREAD

**Issue by dbaston** [openlayers/ol3#5626]
I'm trying to keep track of whether a map is moving using an approach like the following:

```
var is_moving = false;
map.on('pointerdrag', function(e) {
    is_moving = true;
});
map.on('moveend', function(e) {
    is_moving = false;
});
```

The problem is that it's possible to click and move the mouse very slightly, triggering a `pointerdrag` event that is never followed by a `moveend`.  (A related problem is that my click events sometimes do not fire because the click is interpreted as a `pointerdrag`).

Am I wrong to assume that a `pointerdrag` event should always result in map movement?  And if so, is there a better way to determine if the map is moving?

**Comment by ahocevar** [comment]
There is a better way. See #3985. If you have `movestart` and `moveend`, you know that the map center is changing between the two.

**Comment by dbaston** [comment]
Much better indeed, thank you for the reference.
