### ISSUE TITLE
Text hit detection issue

### ISSUE THREAD

**Issue by strikehawk** [openlayers/ol3#5627]
Text hit detection seems to have an issue if text is wider than a specific size. I have created a jsfiddle to reproduce this issue: http://jsfiddle.net/strikehawk/wtp07gfp/.

As you can see in the sample, “Small text” reacts to mouse click on all its width, but “Much larger text to demonstrate hit detection issue” is reactive on its central part only (see the comments under the map in the jsfiddle).

I think it is related to the size of the renderBuffer (see [ol.layer.Vector](http://openlayers.org/en/v3.17.1/apidoc/ol.layer.Vector.html)). I have found [this thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ol3-dev/El6_R7ttXGg/Zt9wB2WQQqUJ) with a possible workaround but I am a bit concerned with the idea of increasing the renderBuffer for hit detection purposes. 

The objective of using a renderBuffer seems to be to narrow down the list of objects in the vicinity of the mouse click. The larger the renderBuffer, the more features will have to go through a finer hit detection process. Cannot this lead to performance issues? I need to display more than 5000 features on a single map for my project. Some of them are points represented by text, and the user can select any feature to edit it (e.g. customize its style). If I have to set the renderBuffer to the size of the largest text (which is by the way not so trivial to compute from performance point of view), hit detection will have to process way too many objects.

What’s your opinion on this one?

**Comment by ahocevar** [comment]
You have to configure the vector layer with a `renderBuffer` value that matches the longest label in pixels. I updated your fiddle with `renderBuffer: 250` and it works fine now: http://jsfiddle.net/wtp07gfp/3/.

**Comment by ahocevar** [comment]
For 5000 features, this will work fine if you hit-detect on click. Performance would only become an issue on hover.
