### ISSUE TITLE
Refresh ol.source.Vector with bbox strategy without clearing the whole source

### ISSUE THREAD

**Issue by ceiblef** [openlayers/ol3#5629]
I have a vector layer with a vector source loading features from somewhere using the loader function and the loading strategy "bbox". When I pan the map the loader is called and adds the new features to the source - everything is fine. When I move the map using `getView().setCenter(...)` the loader is not called.

I have created a [plunker](https://plnkr.co/edit/b4yuPPeL58Z0EWUvDVPy?p=preview): It has a feature right in the center of the extent. Pan the map until the feature is outside of the extent. Click home - and watch the console output - the loader is not called. In my real example there won't be a feature anymore.

**Comment by ahocevar** [comment]
The loader will only be called if you are viewing an extent that has not previously been loaded. So it is expected and perfectly fine when calling `setCenter()` on the view does not always trigger the loader.

Regarding your real example: no features should disappear, until you do something to make them disappear in the loader.

**Comment by ceiblef** [comment]
Thanks Andreas, I understand and you are totally right! The features disappear because I delete them when I pan the map and the feature is not in the extent anymore. That is because my features are very dynamic and might have been gone! 
So I need to fetch every time even when the extent was visible before. How do I achieve this?

**Comment by ahocevar** [comment]
In this case, you'd have to call `clear()` on the source. In addition to deleting all features, this will reset all loaded extents.

**Comment by ceiblef** [comment]
I know that this could solve my problem, but the layers are configurable and I don't want to work through all the layers to clear the sources - especially when they have cluster sources. Wouldn't it make sense to leave it to the developer to decide if the extents should be cached, and make it configurable? So the developer can decide for every single layer at creation time...

**Comment by ahocevar** [comment]
This is a good idea actually. What about implementing the `refresh` method for `ol.source.Vector`, so it reloads all cached extents? Would you be willing to create a pull request for that?

**Comment by ahocevar** [comment]
Hm, thinking again, this would not be much different from calling `clear()`.

**Comment by ahocevar** [comment]
Why don't you just call `ol.source.Vector#clear()` as first thing in your loader? This should fix your issue.

**Comment by ceiblef** [comment]
But the loader-function is not called in case of cached extents. So how should I know?. Even so, clear() deletes all features, and if it takes time to fetch the new ones that might not look very nice. 
I would prefer a source parameter like "fetchAlways" in combination with the bbox-strategy to fetch always regardless if the extent was fetched before...

**Comment by ceiblef** [comment]
Then it is up to the loader-function to clear() or have a more advanced update functionality.

**Comment by ahocevar** [comment]
I thought you actually delete your features in your loader function. What would be the difference? When you call `clear()`, it will also just reload the extent you are currently viewing.

If you want to do proper feature updates, use `ol.source#getFeatureById()`, and update the feature instead of deleting it. You can do this completely separate from the loader.

**Comment by ceiblef** [comment]
The way I update the features in the source is not the problem. 
My initial problem is, that the loader-function does not get called when the extent was already cached. I don't want the caller of setCenter() to execute something additional to clear/update explicitly all the layer sources. In addition, if I do introduce and additional fetch mechanism which is called independently from the fetch cache/fetch mechanism of the source, I will for sure do fetch things twice in case of not cached extents.
Isn't it simply possible to deactivate the caching mechanism of the extents?

**Comment by ahocevar** [comment]
I do understand your initial problem. And we already agreed that `setCenter` is not your problem. What I do not understand is why you want to leave it to the loader to update your features. Because from a user perspective, this means the user won't see any updates before they navigate the map.

Of course it would not be a problem from a tech perspective to implement what you want, but I'm hesitant to extend the API with something that is really a super narrow corner case, and will confuse all users that do not need that corner case.

**Comment by ceiblef** [comment]
Whenever a feature is updated in the backend, I will get informed through websockets. This is somehow linked the the source. Then I can update the features in the dedicated source. 
For updating features during normal interaction (Pan, Zoom, setCenter) i would prefer to use the ol-workflow. Also because the caller of setCenter() does not care about sources and how the needs to be updated. At the end, both update trigger call the same function to update the source.
What about ol.loadingstrategy.allways?

**Comment by ahocevar** [comment]
Ok, now you're talking. The websocket part makes sense. The rest does not. Instead of reloading features, look them up by id and modify them in your websocket handler. Then you do not need two ways of handling updates.

**Comment by ceiblef** [comment]
On websocket events I update the source feature by feature, like you mentioned. But I can not load all features at once and track them all during life-cycle because that would be too much. So I have to work on bbox-base. Now when the center is set to an previous extent, I need to add the features of the previously loaded extent again.

**Comment by ahocevar** [comment]
Ok, that makes sense. I'm afraid simply introducing a property that makes the source forget cached extents won't help, because the source won't re-add features with the same id. And clearing features by cached extents is not a solution either, because it would clear linestrings and polygons from other extents if they reach into the extent to clear.

**Comment by ceiblef** [comment]
I had a look in ol.source.Vector loadFeatures function which actually checks for existing extents and puts the extent in the loadedExtentsRtree. Loaded extents are completely independent from the loaded features, right? 
Introducing an always-loading-strategy, skip the alreadyLoaded-check in case, and always call the loader-function should do no harm to existing functionality. With the loader-function it is always up to the developer to manage the features in the source. Am I too simple?

**Comment by ahocevar** [comment]
Your observation is correct, and I still think you'd handle this better by leaving the loading responsibility entirely to your application. You can do that without any extra steps by registering a listener to the map's layers collection:
```js
var layers = map.getLayers();
layers.on('add', function(evt) {
  var source = evt.element.getSource();
  if (source && source instanceof ol.source.Vector) {
    var view = map.getView();
    var listenerKey = view.on(['change:center', 'change:resolution', 'change:rotation'], function() {
      var extent = view.calculateExtent(map.getSize());
      source.loader(extent, source.getResolution(), source.getProjection());
    });
    layers.on('remove', function() {
      view.unByKey(listenerKey);
    });
  }
});
```
Then simply configure your sources like this:
```js
new ol.source.Vector({
  loader: function(extent, resolution, projection) {
    // same as your existing loader function
  },
  strategy: function(extent, resolution) {
    // never load anything
    return [];
  }
});
```
The TODO on the library side would be to improve the docs for `ol.LoadingStrategy`, because it can be any function that takes an extent and a resolution as argument and returns an array of extents.

**Comment by ceiblef** [comment]
Many thank you for your time, discussion and the code sample!
I know, we can manage it somehow, but I am still not happy with such a solution. I have the feeling that this is a workaround. For me it is the ol.source.Vectors and strategies responsibility. The additional listeners on the view should not be necessary. I also would need to consider and exclude other loading-strategies in the view-change-handler, because their behavior shouldn't be affected. For me that is to much code to bypass extent caching mechanism.

**Comment by ahocevar** [comment]
As I said already, to me your case looks like a very narrow corner case. In OpenLayers, we provide some nice high-level functionality (like loaders and strategies), which satisfy 99% of use cases. If an application developer needs something else, the way to go is through a lower level API. So my suggested solution is not a workaround, it is just handling things at a lower level.
