### ISSUE TITLE
ReferenceError: ol is not defined

### ISSUE THREAD

**Issue by JPVenson** [openlayers/ol3#5639]
Hey,

Pre: Yes i included the script and i see the browser to load it.

It seems like the browser is trying to load the ol.js script and there is a valid response, but Chrome( 52.0.2743.82) does not include it into Window. It is neither available in my script nor in the Sources tab.

**Comment by JPVenson** [comment]
Update:
When using the CDN, the script is loaded into to Window but never executed. Same as with Edge.

**Comment by JPVenson** [comment]
https://jsfiddle.net/orw21pgf/1/

**Comment by ahocevar** [comment]
Works fine here: https://jsfiddle.net/orw21pgf/2/

**Comment by Agimovel** [comment]
Problem still ocurring in 2019. I add the script in a modal, as tutorial says. On document.ready I call ol map script and throws same error.

**Comment by rewerewe** [comment]
@marceloagil How about change the position of import line that ol.js file on top in HTML? I found out the way to fix. Check out code. :) 
```
  <script src='./libs/v6.3.1-dist/ol.js'></script>
    <script src="./main.js"></script>
```
