### ISSUE TITLE
bug in ol.format.XSD.readDateTime

### ISSUE THREAD

**Issue by lvalva** [openlayers/ol3#5643]
```js
ol.format.XSD.readDateTime = function(node) {
  var s = ol.xml.getAllTextContent(node, false);
  var re =
      /^\s*(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(Z|(?:([+\-])(\d{2})(?::(\d{2}))?))\s*$/;
  var m = re.exec(s);
  if (m) {
    var year = parseInt(m[1], 10);
    var month = parseInt(m[2], 10) - 1;
    var day = parseInt(m[3], 10);
    var hour = parseInt(m[4], 10);
    var minute = parseInt(m[5], 10);
    var second = parseInt(m[6], 10);
    var dateTime = Date.UTC(year, month, day, hour, minute, second) / 1000;
    if (m[7] != 'Z') {
      var sign = m[8] == '-' ? -1 : 1;
      dateTime += sign * 60 * parseInt(m[9], 10); //BUG dateTime += sign * 60 *60* parseInt(m[9], 10)
      if (m[10] !== undefined) {
        dateTime += sign * 60 * 60 * parseInt(m[10], 10);  //dateTime += sign * 60 *  parseInt(m[10], 10);
      }
    }
    return dateTime;
  } else {
    return undefined;
  }
};
```

**Comment by ahocevar** [comment]
Would you mind putting the above snippet in some context? What is the bug, what is the expected behavior?

**Comment by lvalva** [comment]
By loading gpx files where time tag in format <time>2016-07-12T15:28:57+06:00</time>.
Where format is  <time>2016-07-12T15:28:57Z</time> all fine

**Comment by lvalva** [comment]
`function tstBug() {
  var vectorData = '<?xml version="1.0" encoding="UTF-8"?>'+
  '<gpx version="1.0" creator="OpenStreetMap.org" xmlns="http://www.topografix.com/GPX/1/0">'+
  '<trk>'+
    '<trkseg>'+
      '<trkpt lat="56" lon="34">'+
        '<time>2016-07-12T15:00:00+00:00</time>'+
      '</trkpt>'+  
      '<trkpt lat="56.1" lon="34.1">'+
        '<time>2016-07-12T15:00:00+03:00</time>'+
      '</trkpt>'+
    '</trkseg>'+
  '</trk>'+
  '</gpx>';
  
  var sourceFormat = new ol.format.GPX();
  var dataProjection = sourceFormat.readProjection(vectorData);
  var currentProj = new ol.proj.Projection({code: 'EPSG:3857'});
  fs = sourceFormat.readFeatures(vectorData, {dataProjection: dataProjection,featureProjection: currentProj});
  
  var coord = fs[0].getGeometry().getCoordinates();
  timestamp1 = coord[0][0][3];
  var d1= new Date(timestamp1 * 1000);
  timestamp2 = coord[0][1][3];
  var d2= new Date(timestamp2 * 1000);
  
  console.log('date1='+d1.toISOString(),'; date2='+d2.toISOString());
  //output:  date1=2016-07-12T15:00:00.000Z ; date2=2016-07-12T15:03:00.000Z
  //must be: date1=2016-07-12T15:00:00.000Z ; date2=2016-07-12T18:00:00.000Z
  //delta 3 min (mast be 3 hour)
};`

**Comment by ahocevar** [comment]
Would you mind sharing what's going on in your head? Is there still a problem in OpenLayers? Was there a problem in your application that you figured out?

**Comment by lvalva** [comment]
[tst_bug.txt](https://github.com/openlayers/ol3/files/383355/tst_bug.txt)

**Comment by ahocevar** [comment]
Ok, can you put this into a pull request with a test case that fails before and passes after your fix?

**Comment by lvalva** [comment]
I am novice in github
this issue only for information

**Comment by ahocevar** [comment]
Ok, thanks for reporting the issue!

**Comment by ahocevar** [comment]
For the record: your test case is also incorrect. `2016-07-12T15:00:00+03:00` means `2016-07-12T12:00:00.000Z` in Zulu.
