### ISSUE TITLE
dotted line performance

### ISSUE THREAD

**Issue by s332401890** [openlayers/ol3#5645]
_var lineFeature1 = new ol.Feature(new ol.geom.LineString([ [ -1e7, 1e6 ],
		[ -1e6, 3e6 ] ]));
var lineFeature2 = new ol.Feature(new ol.geom.LineString([ [ -1e7, 1e6 ],
		[ -2e6, 3e6 ] ]));
var lineFeature3 = new ol.Feature(new ol.geom.LineString([ [ -1e7, 1e6 ],
		[ -3e6, 4e6 ] ]));
var map = new ol.Map({
	layers : [ new ol.layer.Vector({
		source : new ol.source.Vector({
			features : [ lineFeature1, lineFeature2, lineFeature3 ]
		}),
		style : new ol.style.Style({
			stroke : new ol.style.Stroke({
				width : 1,
				lineDash : [ 10 ]
			}),
		})
	}) ],
	target : 'map',
	view : new ol.View({
		center : [ 0, 0 ],
		zoom : 2
	})
});_

**Comment by s332401890** [comment]
when the zoom level is 17, the frame rate is just 1.7fps.

**Comment by s332401890** [comment]
i have imitated the similar data with canvas , frame rate is 7fps。 can you tell me what can i do to improve performance .thanks a lot.

**Comment by ahocevar** [comment]
Your lines are too long. Split them into shorter lines.

**Comment by s332401890** [comment]
thanks :) i will try it.  thanks again.

**Comment by s332401890** [comment]
is MultiLineString useful?

**Comment by ahocevar** [comment]
Yes, but even a LineString will do - just make sure your segments (i.e. the distance between vertices) are shorter.
