### ISSUE TITLE
Some samples don't work normally in Chrome by file protocol since 3.14.2

### ISSUE THREAD

**Issue by cityant** [openlayers/ol3#5647]
Hi,

I have a question that since 3.14.0, some samples like earthquake-clusters.html, vector-labels.html etc don't work normally by file:// in Chrome (Version 52.0.2743.82 m in my case), even chrome opened with option  --allow-file-access-from-files. However it works by http:// in Chorme and In Firefox, these samples work by both file and http protocols.

I have to use these in nwjs (Chrome as the core) which use file protocol. Anybody have clue for solving the problem?

**Comment by ahocevar** [comment]
Does it work with the `--local-to-remote-url-access=true` option?

**Comment by cityant** [comment]
No it doesn't work even with --local-to-remote-url-access=true.

After debugging, I found that seems something is different between 3.13.1 (working) and 3.14.2 (non-working). In ol.featureloader.loadFeaturesXhr, goog.net.XhrIo() changed to XMLHttpRequest(). Does it matter and cause the problem?

**Comment by ahocevar** [comment]
Might be. `goog.net.XhrIo` uses `XMLHttpRequest` internally, maybe with some non-standard options that we do not use now.

**Comment by cityant** [comment]
Anyone else has the same issue?

**Comment by ahocevar** [comment]
I just tried to reproduce this, but I cannot reproduce it. When the example is opened from a file:// url and the kml is from a file:// url too, I get an error with both v3.13.1 and v3.14.0. When the kml is from a http:// url, it works with both versions.

**Comment by cityant** [comment]
Have you tried option --allow-file-access-from-files? After adding it, file protocol should be ok on v3.13.1.

**Comment by ahocevar** [comment]
Thanks, now I was able to reproduce. See #5652 for a fix.
