### ISSUE TITLE
Draw interaction position off

### ISSUE THREAD

**Issue by domiSchenk** [openlayers/ol3#5655]
Since some days i have this wired bug that my mouse Position is off when drawing.
![Position Off](http://i.imgur.com/XKfV0IO.png)

Normally the blue circle is centered to mouse tip:
![Position centred](http://i.imgur.com/RhPAF5O.png)

Does anyone have a Solution for this, or did have the same problem?
This problem does not occur in Internet Explorer.

**Comment by ahocevar** [comment]
If you click, does the vertex get drawn at the mouse cursor position, or the center of the circle?

**Comment by domiSchenk** [comment]
its drawn at the center of the circle.
its also only happen in my app, on other apps it does not.

**Comment by ahocevar** [comment]
This is very likely a CSS issue, e.g. a margin on the container element that OpenLayers creates inside the map div. If it isn't, then it might go away when you call `map.updateSize()` before activating the Draw interaction.

**Comment by domiSchenk** [comment]
Thank you very much!

the problem was following:
On site loading there was a Scrollbar. This created my canvas with 100% width but only 1903 pixels.
