### ISSUE TITLE
Cannot set a gradient on a style fill color

### ISSUE THREAD

**Issue by ca0v** [openlayers/ol3#5660]
For example, the circle style has code which assumes the fill color is not colorLike:
``` 
ol.color.asString(this.fill_.getColor());
```
Being able to do this would facilitate heatmap like functionality using styling alone and would also expand the already amazing styling options by providing all kinds of textures to represent point features.

**Comment by ahocevar** [comment]
Did you mean to close this @ca0v?

**Comment by ca0v** [comment]
Yes, I was using 3.12, [works great](https://rawgit.com/ca0v/ol3-lab/master/rawgit.html?run=ux/style-lab) in 3.17.
