### ISSUE TITLE
Does not support openlayers 3.11.1 with Angularjs 1.5

### ISSUE THREAD

**Issue by lilan123** [openlayers/ol3#5663]
Hi, 

We have tried this with AngularJs 1.5 and most functionalities like search location get coordinates didn't work. 

Appreciate if you could help, 

Thanks, 
Lilan

**Comment by ahocevar** [comment]
You have to be more specific when reporting an issue. And I'm guessing you have reached the wrong issue tracker, because OpenLayers does not ship with a location search.

**Comment by lilan123** [comment]
Hi @ahocevar , Please refer below URL 

http://openlayers.org/en/latest/examples/reprojection-by-code.html

What I meant by  location search is above.  It does the Reprojection but it does not return coordinates values. 

Further Appreciate your quick response. 
 
Thanks 
Lilan

**Comment by ahocevar** [comment]
The form in that example is not meant to return coordinates. If you are looking for a location search that you can use with OpenLayers, you may want to have a look at https://github.com/jonataswalker/ol3-geocoder.
