### ISSUE TITLE
ol.proj.get return undefined or null?

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5666]
I've just been looking at `ol.proj.get` and there seems to be an inconsistency in what it returns if the code is not in the list. Docs say 'null' if code is not in the list, but if the code is not in `projections_` and/or there is no proj4js def for that code, it will return 'undefined' not 'null'. It only returns 'null' if code is neither a projection object nor a string. ISTM it would be better if it were to return 'null' or 'undefined' in all cases.

**Comment by fredj** [comment]
See #3175

**Comment by ahocevar** [comment]
See #5667 for a fix.
