### ISSUE TITLE
Assertion error is thrown in ol.debug when ol.map logo is set to false

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol3#5671]
Message: "Assertion failed: logo.href should be a string"

Is a result of this [merge](https://github.com/openlayers/ol3/commit/3665e21341289104292743236ee874b0e01175cf)

**Comment by ahocevar** [comment]
This is fixed with #5619.

**Comment by tschaub** [comment]
Would be good to leave this open until #5619 is merged.

**Comment by fredj** [comment]
#5619 is now merged
