### ISSUE TITLE
a.hf is not a function when adding marker with a data:image/png;base64 src (data url)

### ISSUE THREAD

**Issue by spyhunter99** [openlayers/ol3#5677]
I have a use case where I'm using a js library to generate a base64 encoded png that needs to be used as the marker's icon on the map.

I'm using the following example: http://openlayers.org/en/v3.0.0/examples/icon.js replacing the iconStyle `src: 'data/icon.png'` with the data url parameter, which looks like this
````
data:image/png;base64, ......
````

This sample library can also generate an svg data url, however the content of the svg xml is basically the base64 encoded png.

When attempting to render, I get the following error message:
````
Uncaught TypeError: a.hf is not a function @ ol.js:180 (minimized v3.17.1)
````

Question: this is scenario supported and/or are there any workarounds to resolve this?

**Comment by fredj** [comment]
base64 images are supported, see http://jsfiddle.net/fredj/bt9c85j0/
