### ISSUE TITLE
Add ol.geom.Geometry.prototype.scale

### ISSUE THREAD

**Issue by ca0v** [openlayers/ol3#5684]
ol.render.toContext renders a feature to an arbitrary context but there are not enough tools available in the library to transform the points into pixel coordinates.  Please add the following methods to facilitate scaling a geometry:

```
ol.geom.SimpleGeometry.prototype.scale = function (deltaX, deltaY) {
  var flatCoordinates = this.getFlatCoordinates();
  if (flatCoordinates) {
    var stride = this.getStride();
    ol.geom.flat.transform.scale(
        flatCoordinates, 0, flatCoordinates.length, stride,
        deltaX, deltaY, flatCoordinates);
    this.changed();
  }
}

ol.geom.flat.transform.scale =
    function (flatCoordinates, offset, end, stride, deltaX, deltaY, opt_dest) {
        var dest = opt_dest ? opt_dest : [];
        var i = 0;
        var j, k;
        for (j = offset; j < end; j += stride) {
            dest[i++] = flatCoordinates[j] * deltaX;
            dest[i++] = flatCoordinates[j + 1] * deltaY;
            for (k = j + 2; k < j + stride; ++k) {
                dest[i++] = flatCoordinates[k];
            }
        }
        if (opt_dest && dest.length != i) {
            dest.length = i;
        }
        return dest;
    };

```

With those in place we have the tools necessary to render a feature on a canvas:

    render(canvas: HTMLCanvasElement, feature: ol.Feature) {
        feature = feature.clone();        
        let geom = feature.getGeometry();
        let extent = geom.getExtent();

        let [dx, dy] = ol.extent.getCenter(extent);
        let [sx, sy] = [canvas.width / ol.extent.getWidth(extent), canvas.height / ol.extent.getHeight(extent)];

        geom.translate(-dx, -dy);
        geom.scale(Math.min(sx, sy), -Math.min(sx, sy));
        geom.translate(canvas.width / 2, canvas.height / 2);

        let vtx = ol.render.toContext(canvas.getContext("2d"));
        vtx.drawFeature(feature, feature.getStyleFunction()(0));
    }

**Comment by tschaub** [comment]
I'd suggest that we allow for a scaling origin as well:

```
/**
 * Scale the geometry (with an optional origin).  This modifies the geometry
 * coordinates in place.
 * @param {number} sx The scaling factor in the x direction.
 * @param {number} opt_sy The scaling factor in the y direction (defaults to
 *     sx if not provided).
 * @param {ol.Coordinate} opt_anchor The scale origin (defaults to the center
 *     of the geometry extent).
 * @api
 */
ol.geom.Geometry.prototype.scale = goog.abstractMethod;
```
