### ISSUE TITLE
White lines for Zoomify source starting from 3.14.0

### ISSUE THREAD

**Issue by yurykovshov** [openlayers/ol3#5690]
I noticed that in the last version 3.17.1 there is white lines are blinking when you fast zoom in or zoom out (in Chrome, FF, IE). And looks like it happens only for Zoomify sources. Such behavior has started from 3.14. 

To show you I uploaded some examples (custom code is the same, but different OL):
1) With white lines (using 3.17.1): http://demo.smartinmedia.com/openlayers/examples/issue17.html
2) Without (using 3.13.1): http://demo.smartinmedia.com/openlayers/examples/issue13.html

For now we decided to fallback to 3.13.1. But if you will have time - just have a look.

**Comment by eciuli** [comment]
Indeed, we experienced it too. Sadly, we had to revert as well. 
It seems the issue was also present in ol2, at some point, however only on Firefox: https://github.com/openlayers/ol2/issues/458

**Comment by ahocevar** [comment]
This is not specific to Zoomify sources, and is caused by tiles of different resolutions not aligning when the view is scaled during zoom level transitions. See #5890 for a fix.

**Comment by yurykovshov** [comment]
@ahocevar I've just tried again with the last 3.19.1 and still reproducible.

**Comment by tchandelle** [comment]
It was reverted in #6022, you can use v3.19.0 instead

**Comment by yurykovshov** [comment]
Thanks. In 3.19.0 it looks good.
