### ISSUE TITLE
Geolocation broken

### ISSUE THREAD

**Issue by mstenta** [openlayers/ol3#5700]
It seems that Geolocation is currently broken - in both Chrome and Firefox. See the official example:

http://openlayers.org/en/latest/examples/geolocation.html

Note that this appears to be a different issue than #5276 because it is also happening on HTTPS sites, and not just in Chrome.

**Comment by mstenta** [comment]
Ah... this may be related to Google's recent API changes that require an API key.

In the official example, if you change the URL to https:// and try to Geolocate, the following message appears:

> Network location provider at 'https://www.googleapis.com/' : Returned error code 403.

https://openlayers.org/en/latest/examples/geolocation.html

**Comment by mstenta** [comment]
HA! Even Google's own examples are failing...

https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

This might not be an Openlayers bug after all...

**Comment by ahocevar** [comment]
You have to allow your browser to access your location, then it will work on a https:// site. Try this one: https://jsfiddle.net/ahocevar/uh85vrLs/1/.

**Comment by mstenta** [comment]
This is a different issue - unrelated to HTTPS. Did you try the example? Did it work for you?

I get:

> Network location provider at 'https://www.googleapis.com/' : Returned error code 403.

Even Google's own example doesn't work:

https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

So I don't think this is an Openlayers issue.

**Comment by mstenta** [comment]
Also: it doesn't work in Firefox either. The HTTPS insecure origins issue only applies to Chromium as far as I know.

**Comment by ahocevar** [comment]
You cannot access openlayers.org through https, because it does not have a certificate. This is why I pointed you to the fiddle, which is all https with certificate. If you try the example on your own https server with certificate, it will work.

**Comment by mstenta** [comment]
@ahocevar Thanks - but this is not working on my HTTPS sites. In Chrome or Firefox. As I said above - it appears to be an issue with Google's servers... not Openlayers after all. Did you try the Google example? Or the example you posted? Did it work for you?

**Comment by probins** [comment]
the Geolocation API has nothing to do with Google. I think you're confusing 2 different things

**Comment by ahocevar** [comment]
All examples linked in this ticket work for me. Maybe you have not allowed your browser to access your location?

**Comment by mstenta** [comment]
@ahocevar and @probins - Hmm - It's definitely possible that I'm confusing things. I'm not very familiar with the inner workings of the Geolocation API. One of my users reported that Geolocation wasn't working for them, and I confirmed that it isn't working for me either. I tried on HTTPS as well as HTTP. And even the official Google example is not working. I did grant access to my location in both Chrome and Firefox when prompted by the browser, yes.... so something else must be going wrong. Strange that it is working for you....

**Comment by mstenta** [comment]
Huh - very strange. I tried it on my wife's computer (Windows), and it worked. But it is not working on mine (Ubuntu). The plot thickens...

**Comment by mstenta** [comment]
It appears that this is also not working in Chrome on Android.

I'm assuming that this is an issue with Linux support...

This issue can remain closed because it is not an Openlayers-specific issue.

**Comment by mstenta** [comment]
Just an update on this in case anyone finds this issue later:

I still haven't figured out why my laptop isn't working - but my phone was set to use "Device only" location services (which just uses the GPS), rather than "high accuracy" (which also uses wifi, cell towers, etc).  Changing to "high accuracy" fixed the issue on my phone.

I assume it's something similar on my laptop... sorry for the false alarms.
