### ISSUE TITLE
Wrong cursor style of translate interaction

### ISSUE THREAD

**Issue by mzur** [openlayers/ol3#5703]
The translate interaction has [contradictory cursor styles](https://github.com/openlayers/ol3/blob/907a65ab83ef86d9927f0fced17fab66d14f980a/src/ol/interaction/translate.js#L234-L240) for Webkit browsers and the rest. I think the styles for Webkit browsers are correct, so the code should be (note the missing `!`):

```js
elem.style.cursor = this.lastCoordinate_ ?
    'grabbing' : (isSelected ? 'grab' : 'pointer');
```

I'm willing to submit a PR if I must but since I haven't signed the CLA yet maybe someone else can fix this more quickly.

**Comment by bartvde** [comment]
see also: #5689

**Comment by mzur** [comment]
Oh sorry, I only searched the issues for similar topics.
