### ISSUE TITLE
Fetch (polyfill?) no longer works for file:// urls in PhantomJS

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#5712]
Travis is failing with the following stack trace for examples that use `fetch()`:
```
JavaScript ERROR: Uncaught (in promise) file:///Users/ahocevar/projects/ol3/build/hosted/master/examples/flight-animation.js:72:29
callHanler@https://cdn.polyfill.io/v2/polyfill.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL:1656:24
tryCatcher@https://cdn.polyfill.io/v2/polyfill.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL:1373:38
https://cdn.polyfill.io/v2/polyfill.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL:1512:39
flush@https://cdn.polyfill.io/v2/polyfill.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL:1415:20
```
It turns out that network requests through file urls are not handled by the polyfill.

**Comment by ahocevar** [comment]
Actually native fetch implementations also do not work with file:// urls. So I think we'd be better off running the check-examples task through http://.

**Comment by probins** [comment]
from the [spec](https://fetch.spec.whatwg.org/#basic-fetch): "For now, unfortunate as it is, file and ftp URLs are left as an exercise for the reader. When in doubt, return a network error." :-)
