### ISSUE TITLE
Rotation of the view failed on HiDPI screens

### ISSUE THREAD

**Issue by felixveysseyre** [openlayers/ol3#5716]
Following the issue #5489, when rotating the view of my map the result depend of the screen type I used.

Taking the example given by @ahocevar http://jsfiddle.net/otbvz824/, here is the result I got.

On my external monitor:
![capture d ecran 2016-08-12 a 12 09 57](https://cloud.githubusercontent.com/assets/4909259/17619616/dc413768-6086-11e6-9b7f-120923cc64c6.png)

On my internal monitor (HiDPI, MacBookPro retina 13", 'more space' configuration):
<img width="500" alt="capture d ecran 2016-08-12 a 12 10 12" src="https://cloud.githubusercontent.com/assets/4909259/17619652/11b7121e-6087-11e6-8ac7-81cf236ee1d6.png">

Hope it will help.

**Comment by ahocevar** [comment]
Looks like we do not take the device pixel ratio into account when we rotate the clip extent on the layer.

**Comment by ahocevar** [comment]
Can also be reproduced with http://openlayers.org/en/latest/examples/layer-extent.html.

**Comment by ahocevar** [comment]
And http://openlayers.org/en/latest/examples/wms-tiled.html.

**Comment by ahocevar** [comment]
I did a git bisect:
```
44a4fbdda2e87c2ee3018b212bc07ef0079e747c is the first bad commit
commit 44a4fbdda2e87c2ee3018b212bc07ef0079e747c
Author: Ian Schneider <planablediglet@gmail.com>
Date:   Wed Jun 15 11:17:34 2016 -0600

    respect layer.extent in canvas tilelayer renderer

:040000 040000 e2b56d8729745b56ba2ae151d6643632aee853c4 a8241a215a89730c7a5fee75b2c7866ffeffe538 M	src
```
ping @ischneider - any help you could provide here would be much appreciated.

**Comment by ahocevar** [comment]
Thanks @felixveysseyre for reporting this issue.

**Comment by ahocevar** [comment]
I think I found the problem @ischneider. Pull request to come.

**Comment by ischneider** [comment]
Thanks for figuring that out @ahocevar - the HiDPI bites me often w/ ol3 as I don't have one of those.

**Comment by felixveysseyre** [comment]
@ahocevar You are welcome, thanks for this great tool !

**Comment by felixveysseyre** [comment]
@ahocevar Do you know when the next release will come ?
