### ISSUE TITLE
Assert errors on tilegrid/wmts

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5722]
Some tilegrids which were working fine up to 3.17.1 are no longer working since assert error 21 was changed to throw in built code. Example capabilities http://www.ign.es/wmts/mapa-raster?request=GetCapabilities&service=WMTS
Using the EPSG:25830 matrix set gives:
```
new ol.tilegrid.WMTS({
  extent: [-1079526.585009098, 2450926.618387835, 1462559.4951461395, 5127818.100512035],
  sizes: [[5, -8], [10, -15], [20, -29], [40, -57], [79, -114], [158, -228],
    [315, -456], [630, -911], [1259, -1821], [2517, -3641], [5034, -7283], [10067, -14565]],
  origins: [[-1968157.095, 7827955], [-1968157.095, 7514869], [-1968157.095, 7358326],
    [-1968157.095, 7280055], [-1968157.095, 7280055], [-1968157.095, 7280055],
    [-1968157.095, 7280055], [-1968157.095, 7275163], [-1968157.095, 7272717],
    [-1968157.095, 7271494], [-1968157.095, 7272105], [-1968157.095, 7271800]],
  resolutions: [8735660.377232144 * 0.28E-3,
    4367830.188616072 * 0.28E-3, 2183915.094308036 * 0.28E-3, 1091957.547154018 * 0.28E-3,
    545978.773577009 * 0.28E-3, 272989.38678571396 * 0.28E-3, 136494.69339285715 * 0.28E-3,
    68247.34669642858 * 0.28E-3, 34123.67334821425 * 0.28E-3, 17061.836674107144 * 0.28E-3,
    8530.918337053572 * 0.28E-3, 4265.459168526786 * 0.28E-3],
  matrixIds: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
})
```
This can be tried in for example http://openlayers.org/en/v3.17.1/examples/wmts.html  where it works (though not in raw mode) and in http://openlayers.org/en/master/examples/wmts.html where it fails.

Some other servers I access are also failing. As these work fine in 3.17.1, this makes me think this is a false negative. I have never noticed the fail in raw mode because I hardly ever use it.

**Comment by ahocevar** [comment]
This may indeed be a false negative. Would you be able to create a pull request that removes the assert? Thanks!

**Comment by ahocevar** [comment]
Hm, I just looked at your pull request, and I don't see the assertion fail in http://openlayers.org/en/master/examples/wmts.html. I do remember that there was a reason for adding this assertion, but I do not remember what it was, and the reason might be gone. I think it was something with world wrapping. Could you maybe provide a JSFiddle with a WMTS layer that works but violates the assertion?

**Comment by probins** [comment]
just so there's no misunderstanding: I meant that if you try to create the tilegrid I gave it fails in for example http://openlayers.org/en/master/examples/wmts.html. Consequently, if you create a layer using that tilegrid, that will fail too. You don't need a fiddle; you can test this with any build that includes tilegrid/wmts. http://jsfiddle.net/qgx5zu09/ uses that layer/source/tilegrid, using 3.17.1; change that to use master (or raw/debug) and it fails. The problem isn't limited to that particular server; there are others that fail too.

**Comment by ahocevar** [comment]
There is something wrong with that tile grid: Zoom in 3 times and the map will be gone. So I'm hesitant to merge #5725 without knowing what's going on.

**Comment by probins** [comment]
it isn't gone - just blank tiles for that resolution/position :-) This is a map primarily of Spain but which also includes the Canaries. If you pan to Spain first, then zoom, you'll the map works fine.

**Comment by probins** [comment]
or try http://jsfiddle.net/qgx5zu09/2/ centred on point in Spain instead

**Comment by ahocevar** [comment]
Ok, thanks for the explanation! I'm convinced.
