### ISSUE TITLE
renderer option != RendererType?

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5726]
ATM the docs for the Map renderer option say it can be a RendererType, an array of RendererTypes, or undefined, in which case the default logic is used. The docs though also say it can be any other string. This is surely wrong, isn't it? Is there a use case for entering a string which is not a RendererType here?

**Comment by probins** [comment]
comments anyone?

**Comment by ahocevar** [comment]
I'm pretty sure the plain `string` types were only added to satisfy the compiler at some point. +1 on getting rid of them.

**Comment by probins** [comment]
hmm, this seems to still be an issue. The examples that use `getRendererFromQueryString()` fail to compile; presumably there needs to be a typecast to RendererType for this?

**Comment by ahocevar** [comment]
We could also get rid of `getRendererFromQueryString`. If someone wants to test other renderers, they can modify the examples.

**Comment by probins** [comment]
yes, copying to JSFiddle and changing/adding the renderer there would be an option. It's only a minority of examples that use it.

**Comment by probins** [comment]
so should I put together a PR to remove `getRendererFromQueryString`?

**Comment by ahocevar** [comment]
Yes, please @probins. I think it will simplify things a bit, because we also have a regex in the examples build process that removes the option from the source code listing.

**Comment by probins** [comment]
ok, I'll look into that

**Comment by probins** [comment]
sadly, that does not fix the problem. It now complains about the examples that define a renderer, like `renderer: 'webgl'`, because it doesn't know that those are `RendererType`s. There are 11 of these. 7 of these use ''canvas', which AFAICS isn't necessary as that's the default anyway, so these could be removed. However, to fix the other 4, I assume they have to be cast, perhaps by defining a `var renderer = 'webgl'` with the type, and then add a comment to tell people that this is only needed when compiling code with library.

**Comment by ahocevar** [comment]
We use such casts elsewhere and have no comment about it. Ideally we'd have a regex to strip the casts out for the source code listing. @marcjansen has attempted this already if I remember correctly.

**Comment by ahocevar** [comment]
We could maybe also use different compiler options when compiling the examples, so these missing casts are no errors any more.
