### ISSUE TITLE
Features(array) order will break when polygons have more than 9 in one layer.

### ISSUE THREAD

**Issue by lepola** [openlayers/ol3#5729]
## EXAMPLE:
there i have 9 ploygons in layer and i will print them:

```
var features = vector.getSource().getFeatures();
features.forEach(function(feature) {
        var cord = feature.getGeometry().getCoordinates(); 
        console.log(cord);
});
```
result will be:

> 1. [array[4]] //polygon1
> 2. [array[5]] //polygon2
> 3. [array[6]] //polygon3
> 4. [array[7]] //polygon4
> 5. [array[8]] //polygon5
> 6. [array[9]] //polygon6
> 7. [array[10]] //polygon7
> 8. [array[11]] //polygon8
> 9. [array[12]] //polygon9

then i draw one polygon more so i have 10 polygons --> array order has changed:
result:

> 1. [Array[13]] //polygon10
> 2. [Array[10]] //polygon7
> 3. [Array[6]] //polygon3
> 4. [Array[7]] //polygon4
> 5. [Array[8]] //polygon5
> 6. [Array[9]] //polygon6
> 7. [Array[12]] //polygon9
> 8. [Array[11]] //polygon8
> 9. [Array[5]] //polygon2
> 10. [Array[4]] //polygon1

it would be nice that the order remained intact.

**Comment by fredj** [comment]
The array is indeed not ordered, I've added a note in the api doc.

**Comment by ahocevar** [comment]
If you need to maintain the order, you could create your vector source without spatial index (i.e. with `spatialIndex: false`. But be aware of the performance implications - only do so when your source is never going to have many features that are outside the visible map viewport at any time.
