### ISSUE TITLE
ol.uri.appendParams has different behavior than goog.uri.utils.appendParamsFromMap

### ISSUE THREAD

**Issue by adube** [openlayers/ol3#5730]
OpenLayers 3.17.0 introduces the `ol.uri.appendParams` method, which replaces `goog.uri.utils.appendParamsFromMap`.  The new method doesn't handle the parameters with the `null` value the same.  The Closure Library did not add null values in the url:

**Closure Library:**

    goog.uri.utils.appendParamsFromMap('a', {1: null, 2: '2'});
    // outputs:
    // "a?2=2"

**OpenLayers:**

    ol.uri.appendParams('a', {1: null, 2: '2'});
    // outputs:
    // "a?1=null&2=2"

The OpenLayers method does.  I think it shouldn't.  If one wanted to send a null string to the server, one could set `"null"`, as a string.

I'd like to work on a PR for this.  Please, comment.

**Comment by adube** [comment]
Here's where null values are skipped in Closure Library: https://github.com/google/closure-library/blob/v20160713/closure/goog/uri/utils.js#L643-L644

**Comment by bartvde** [comment]
I agree the change you propose makes sense @adube 

@probins any comments?

**Comment by ahocevar** [comment]
Does this reveal itself anywhere when used through the API? If not, I'd be inclined to keep things as they are for the sake of simplicity. Our goal is to make the goog.* replacements work in the library, not as an exact replacement.

**Comment by adube** [comment]
It is indirectly used through the API.  What I mean is one can define the parameters of a WMS source like this:

    source: new ol.source.ImageWMS({
      url: 'http://host.com',
      params: {
        'LAYERS': 'layer1,layer2',
        'CUSTOM_PARAM1': null
      },
      serverType: ol.source.wms.ServerType.MAPSERVER
    })

We use MapServer Run-time Substitution with this custom parameter.  It can be set to a value or reset to `null`.  `null` now being sent as a value, the validation on the server fails, as `null` is not a valid value.  I really think that `null` or `undefined` should be ignored, as one can build an application based on the logic of when something is null, it's not set and therefore we don't want it added in the parameters.

What do you think ?

**Comment by probins** [comment]
@adube's proposal makes sense to me

**Comment by adube** [comment]
FYI, #5733 is ready for review.  Thanks.
