### ISSUE TITLE
404 - API docs pointing to source code

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#5743]
It looks like #5693 introduced these link errors. Checking `ol.source.*`:

- [ol.source.BingMaps](https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/source/bingmaps.js)
- [ol.source.Cluster](https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/source/cluster.js)
- ol.source.Image (and Subclasses)
- ol.source.OSM
- ol.source.Raster
- ol.source.Stamen
- ol.source.Tile* (and Subclasses)
- ol.source.Vector*
- ol.source.WMTS
- ol.source.XYZ
- ol.source.Zoomify

Same with `ol.color`, `ol.control.*`, `ol.format.*`, `ol.interaction.*`, `ol.layer.*`,  `ol.proj.*`, `ol.render.Feature`, `ol.tilegrid`, `ol.tilegrid.WMTS`,  `ol.style.*`.

**Comment by probins** [comment]
should all work for the next release though :-)

**Comment by bartvde** [comment]
I guess we can close this one?

**Comment by jonataswalker** [comment]
Yes, everything fixed.
