### ISSUE TITLE
DOM renderer causes glitchy redrawing in Chrome

### ISSUE THREAD

**Issue by acls** [openlayers/ol3#5744]
To see what I mean by glitchy redrawing, view this fiddle in Chrome. You'll probably need to open it in Firefox to see the html causing it.
https://jsfiddle.net/qy48sn27/

Sometimes, in Chrome when panning or zooming the browser out, the dom renderer creates something similar to the above html. Usually the offending div is only there for a split second, but occasionally it is there longer, and in my app it was permanent. This fiddle reproduces the issue fairly reliably. It also attempts to detect it and log the div to the console.
http://jsfiddle.net/54L8L410/

The above fiddle never logs anything in FF, but FF wouldn't have a problem rendering it if it did happen to occur.

**Comment by fredj** [comment]
See also #1929

**Comment by acls** [comment]
Apparently I'm terrible at searching...
I couldn't get either of the examples to produce visual glitches, nor the html that causes the glitches. So hopefully the fiddles I provided will help you better identify the issue.

**Comment by ahocevar** [comment]
Looks like the transform uses parameters that are beyond the supported range. I guess this transform comes from trying to render lower resolution tiles with a way lower resolution.

**Comment by bartvde** [comment]
DOM renderer got removed with https://github.com/openlayers/ol3/pull/5815 so closing

**Comment by acls** [comment]
I tested this yesterday in Chrome 54, which should be released next month, and the glitches were gone. I just hadn't gotten around to leaving a comment.
It's too bad the DOM renderer is gone, since it has lower CPU usage and doesn't cause our app to crash in mobile browsers like the Canvas renderer does.

**Comment by ahocevar** [comment]
Memory issues with the Canvas renderer should be fixed in v3.18.2.

**Comment by acls** [comment]
Nice! That's good to hear.
