### ISSUE TITLE
'KeyboardEvent.keyIdentifier' deprecated

### ISSUE THREAD

**Issue by hanna97** [openlayers/ol3#5746]
Hi. Some days ago, Chrome wrote this warning on console:
> 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

I use OL v3.13.0 and I wanna know if you removed it in the newest versions or if you will remove it within Sept 2016 with a new version (3.18? lol)
![cattura](https://cloud.githubusercontent.com/assets/21087879/17764718/71813faa-6521-11e6-8239-d619b750f5ba.PNG)

**Comment by tsauerwein** [comment]
`keyIdentifier` is no longer used in the current version (3.17.1).
