### ISSUE TITLE
Heatmap layer clipping during rotation in latest (was previously working)

### ISSUE THREAD

**Issue by stephanelsmith** [openlayers/ol3#5750]
I just updated my OL3 js and am noticing a new issue.  You can see it in the examples:
http://openlayers.org/en/latest/examples/heatmap-earthquakes.html
Rotate the map and drag.  You will see the heatmap layer clipping.
![image](https://cloud.githubusercontent.com/assets/10711596/17790768/a750a530-655d-11e6-9580-a4049d73941e.png)

The last version I can find it working correctly is v3.13.1
http://openlayers.org/en/v3.13.1/examples/heatmap-earthquakes.html

Next version (v3.14.0) starts clipping: 
http://openlayers.org/en/v3.14.0/examples/heatmap-earthquakes.html

**Comment by ahocevar** [comment]
Thanks for reporting this issue @stephanelsmith. See #5752 for a fix.
