### ISSUE TITLE
Interaction doesn't self remove listeners

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5751]
Control remove listeners when [setMap](https://github.com/openlayers/ol3/blob/master/src/ol/control/control.js#L110) is called, while Interaction deoesn't do something similar, which means that the listener should stop listening by itself. That can cause leaks when an interaction is somehow destroyed elsewhere.
What about using the same approach of Control?

**Comment by ahocevar** [comment]
Which events are you refering to? Interactions usually just implement a handleEvent method which is called by the map.

**Comment by giohappy** [comment]
I mean listeners registered on the interaction, as it is for controls, like interaction.on(....).
On second thought, GC should do it, but I wonder why controls do it theirselves when map is set to null. Maybe becose of their internal DOM references?

**Comment by ahocevar** [comment]
Such listeners, when registered by an application, are *not* removed when a control is removed from a map. A control only removes DOM listeners it registers on its DOM elements when `setMap` is called. And as I said above, an interaction does not register such events, so it does not need such code in `setMap`.

Clear now, or am I missing something?

**Comment by giohappy** [comment]
I read the OL events system better. Now everything is cleat, I'm sorry fo the buzz ;)
I'm going to close this issue.
