### ISSUE TITLE
Labeling features from MVT source fails.

### ISSUE THREAD

**Issue by allspatial** [openlayers/ol3#5758]
I have a polygon layer served in Mapbox Vector Tile format by GeoServer (2.9.1). I can load that layer perfectly in OpenLayers (3.17.1) but when I try to label features (by adding an "ol.style.Text" object) I get this error: "TypeError: geometry.getFlatInteriorPoint is not a function" and the layer is not rendered. If I remove the text object from my ol.style.Style object the layer renders properly with fill and stroke (but of course has no labels). The code in the first screenshot fails and in the second screenshot works. Thus, currently I can use MVT layers but cannot label them.

![error](https://cloud.githubusercontent.com/assets/12534211/17856092/e55e3400-688c-11e6-92a4-9cef7741f5ab.png)
![ok](https://cloud.githubusercontent.com/assets/12534211/17856093/e5636132-688c-11e6-859c-6fbdd76ecfc5.png)

**Comment by ahocevar** [comment]
You have to configure the MVT format with `featureClass: ol.Feature` to create features that have geometries with support for geometry operations. Otherwise you get `ol.RenderFeature` features which are optimized for high performance.

**Comment by allspatial** [comment]
That did the trick. Many thanks for your swift reply and support!!!
