### ISSUE TITLE
Finish drawing a geometry while freehand is active cause error on next pan

### ISSUE THREAD

**Issue by tchandelle** [openlayers/ol3#5759]
1. http://openlayers.org/en/latest/examples/draw-and-modify-features.html
2. Start drawing a polygon
3. Hold SHIFT to enable freehand mode
4. Double-click to finish the geometry
5. Try to pan, it throws an exception : `Cannot read property 'getGeometry' of null`

**Comment by ahocevar** [comment]
Fixed with #5769.
