### ISSUE TITLE
Add ol.Map#forEachOverlayAtPixel

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#5760]
I came across [this question](http://stackoverflow.com/q/39038040/4640499)  and came up with [this fiddle](http://jsfiddle.net/jonataswalker/rnzgfg89/) to answer it.

```javascript
ol.Map.prototype.forEachOverlayAtPixel = function(pixel, callback) {
  var map = this;
  var callback_return;
  this.getOverlays().forEach(function(each) {
    var px = map.getPixelFromCoordinate(each.getPosition());
    var width = each.getElement().offsetWidth;
    var height = each.getElement().offsetHeight;
    var extent = [
      px[0] - (width / 2),
      px[1] - (height / 2),
      px[0] + (width / 2),
      px[1] + (height / 2)
    ];
    var inside = ol.extent.containsXY(extent, pixel[0], pixel[1]);
    callback_return = callback.call(undefined, inside ? each : undefined);
  });
  return callback_return;
};
```

By the way `pointerdown` and `pointerup` could be exposed.

**Comment by ahocevar** [comment]
I do not see the benefit of this. Overlays are DOM elements, so the natural way to achieve this is to register DOM listeners on the DOM elements that you connect the overlays to.

That aside, you should not have more than a handful of overlays on a map anyway.

**Comment by jonataswalker** [comment]
Well the initial (stackoverflow) question is:

> Can we make ol.Overlay draggable?

And I said "yes", are you saying "yes" too @ahocevar?

And what you're suggesting is something like: "Use a drag 'n drop library, like http://interactjs.io"?

Because I had a long time to answer this (initial) question and the point is: No matter what you try, you have, at the end of the dragging, `overlay.setPosition(final_coords)` and you can't simply convert the dragging final pixel coordinate &mdash; from the DOM &mdash; using `map.getCoordinateFromPixel` because it won't be the same position.

That's why, after a couple of tries, I came up with this method, if this is possible you'll have to do everything inside OpenLayers.

**Comment by ahocevar** [comment]
What about http://jsfiddle.net/rnzgfg89/3/?

**Comment by jonataswalker** [comment]
Much, much simpler, 100%! :grimacing:

But what about exposing `pointerdown` and `pointerup`?

**Comment by ahocevar** [comment]
That would be possible, but I do not think it's needed. See http://jsfiddle.net/rnzgfg89/6/.

Also note that `map.getCoordinateFromPixel` is not what you want to use when working with DOM events. `map.getEventCoordinate` is your friend.

**Comment by jonataswalker** [comment]
Fantastic! Thank you Andreas.
