### ISSUE TITLE
GWT wrapper for ol3 and ol3-cesium(based on cesium-gwt)

### ISSUE THREAD

**Issue by iSergio** [openlayers/ol3#5762]
Maybe it will be interesting for community. Sorry if no.
This wrapper will strive for 100% implementation of the functional OpenLayers 3 and OL3-Cesium.
https://github.com/iSergio/gwt-olcs

**Comment by ahocevar** [comment]
Thanks for sharing @iSergio, great work!

I'm closing this since there's no action to be taken on our end.
