### ISSUE TITLE
ol.style.defaultStyleFunction doesn't appear in full build

### ISSUE THREAD

**Issue by dmiddlecamp** [openlayers/ol3#5772]
I kept expecting to find "ol.style.defaultStyleFunction" in the full release build for 3.17.1 but it appears to not be included.  It does appear in the ol-debug.js build.

missing referenced function:
https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/style/style.js#L239

Thanks!
David

**Comment by ahocevar** [comment]
The default style function is not part of the official API. But you can copy and paste it from here: http://openlayers.org/en/latest/apidoc/ol.style.html

You can also use getStyleFunction on a fresh vector layer instance to get the default.
