### ISSUE TITLE
ol3 causes Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by Humeira** [openlayers/ol3#5773]
I am using ol3 with Webpack, when I added UglifyJS in my config.
I get the following

```
ERROR in ./w/js/13.176e5326690849f10749.app.js from UglifyJs
RangeError: Maximum call stack size exceeded
    at eval (eval at <anonymous> ....
```

However I have run into and old [issue on Meteor](https://github.com/meteor/meteor/issues/3019) But no luck.

Any ideas?

**Comment by ahocevar** [comment]
This does not look like an OpenLayers issue, so closing. But this should not keep anyone from providing help.

**Comment by larskendall** [comment]
I'm running into a similar issue. It's only happening in Chrome on a production server after everything is minified. The exception gets thrown during loading and always traces back to OL3. I'm not sure if it's directly related to OL3 or not, but if anyone has any suggestions I would really appreciate the help. Been stuck on this problem for a while now!

**Comment by simonseyock** [comment]
You can use the minified version of openlayers (which is already better compressed than you could with uglifyJS) and use
``exclude: /ol\.js/``
in the uglifyJS options.

**Comment by larskendall** [comment]
Looks like this fixed the problem! Thank you so much for your help!

**Comment by hfhanfei** [comment]
Chinese：我也遇到了这个问题，排查后发现是下面这种格式引起的打包后堆栈一出。
```
(function(root, factory) {
    if (typeof exports === "object")
        module.exports = factory();
    else if (typeof define === "function" && define.amd)
        define([], factory);
    else
        root.ol = factory()
}
)(this, fn)
```
打包后运行，传入第一个参数this(也就是window)时发生了爆栈，这里具体原因不清楚，因为我对ol文件进行了修改，所以我的解决办法是不使用这种加在方式，而是fn自调
```
+fn(){
   ...
  //这里需要注意的是，在结尾处有个 return OPENLAYERS.ol，这里需要去掉，改成 this.ol = OPENLAYERS.ol = ol;
}()
```
