### ISSUE TITLE
Can't use ol.style.Icon with ol.render.canvas.Immediate

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5777]
Because the style image is not loaded by the renderer (`ol.style.Image#load`).

**Comment by tschaub** [comment]
See also #2112.  Since fetching a resource from a URL is not "immediate," it is the user's responsibility to load images before using them with the immediate API.

**Comment by bartvde** [comment]
@fredj I guess we can close this one?

**Comment by fredj** [comment]
yes, closing
