### ISSUE TITLE
WMSGetFeatureInfo accept more formats

### ISSUE THREAD

**Issue by AlAlavi** [openlayers/ol3#5781]
Hi
According to documentation of WMSGetFeatureInfo, It currently supports only GML2. Some servers like GeoServer can provide other formats like JSON which maybe more common and in some cases, has smaller size -compared to GML-.
In fact, there are some ambiguity and indeterminacy for working with GML and considering different aspects of its different versions. for example, I couldn't display GML returned by Geoserver in response to getGetFeatureInfoUrl() method, contrary to JSON.

Thanks

**Comment by ahocevar** [comment]
In OpenLayers, you can pass any `INFO_FORMAT` to the `getGetFeatureInfoUrl()` method. And OpenLayers can also parse GML2, GML3 and GeoJSON using the respective format classes. The `ol.format.WMSGetFeatureInfo` format is mostly for MapServer.
