### ISSUE TITLE
VectorSource.Clear() doesn't work inside pointerdrag event

### ISSUE THREAD

**Issue by tpesl** [openlayers/ol3#5783]
Due to problem with performance (when dragging map full of points) I made a service, which return only points, contained inside viewport. To solve the performance problem, I want to clear vectorSource (so that map would be empty at the beginning of map drag action).

The problem is, that vectorSource in case below is cleared when pointerdrag finishes moving, and not at the beggining... How can I force clearing vectorSource when dragging the map since it seems that it doesn't work during moving/dragging map?

```
map.on('pointerdrag', onPointerDrag);
function onPointerDrag(evt) {
    vectorSource.clear(); // ol.source.Vector
}
```

**Comment by ahocevar** [comment]
Configure your map with `updateWhileInteracting: true`.

**Comment by tpesl** [comment]
Already tried. Unfortunately doesn't work. vectorSource is cleared when user stoppes dragging, instead immediately when it starts
