### ISSUE TITLE
<Literal> is missing in ol.format.ogc.filter.between()

### ISSUE THREAD

**Issue by AlAlavi** [openlayers/ol3#5787]
Hi all
There is an issue in between filter.  It's a sample filter created by  ol.format.ogc.filter.between() and passed to server:
```
<GetFeature xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" xsi:schemaLocation="http
://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd" xmlns:xsi="http://www.w3.org/2001
/XMLSchema-instance">
<Query typeName="ws:layer1" srsName="EPSG:4326" xmlns:gt="http://localhost:8080/wfs">
<Filter xmlns="http://www.opengis.net/ogc">
<PropertyIsBetween>
<PropertyName>Pop</PropertyName>
<LowerBoundary>1000000</LowerBoundary>
<UpperBoundary>70000000</UpperBoundary>
</PropertyIsBetween>
</Filter>
</Query>
</GetFeature>
```
Geoserver returns this error: "Attempted to construct illegal filter: Got to the end state of an incomplete filter, current state is LowerBoundary".
I just partly changed that to following and now it works:
```
<LowerBoundary><Literal>2000000</Literal></LowerBoundary>
<UpperBoundary><Literal>3000000</Literal></UpperBoundary>
```

It sounds Literal tag is missing in the filter created by OpenLayers.

Regards

**Comment by tsauerwein** [comment]
Thanks for noticing, a fix is in https://github.com/openlayers/ol3/pull/5800.
