### ISSUE TITLE
Allow arbitrary parameters for WMTS source.

### ISSUE THREAD

**Issue by tbarsballe** [openlayers/ol3#5788]
Similar to the `ol.source.WMS`, `ol.source.WMTS` should allow arbitrary parameter values, for compatibility with GeoServer/GeoWebCache

**Comment by ahocevar** [comment]
You should be able to add your custom params to the `url` that you configure the `ol.source.WMTS` source with. OpenLayers should handle `/geoserver/gwc/service/wmts/` just as fine as `/geoserver/gwc/service/wmts/?myparam=myvalue`.

**Comment by tbarsballe** [comment]
Surprised that works, I would have expected that to result in something like `/geoserver/gwc/service/wmts/?myparam=myvalue?defaultParams=defaultValues`.

Thanks for the help. I will close this issue.
This should perhaps be documented somewhere?
