### ISSUE TITLE
Cannot get a 2nd map to appear in bootstrap panels with angular

### ISSUE THREAD

**Issue by westandy** [openlayers/ol3#5789]
I posted this question on StackOverflow a few days ago: http://stackoverflow.com/questions/39132548/unable-to-have-an-ol3-map-in-each-angular-module

I'm thinking it's an ol3 issue.  

I have an accordian Bootstrap panel (see http://www.w3schools.com/bootstrap/bootstrap_collapse.asp).  The one panel, which is open by default, has a map that displays just fine.  That's ModuleA.  

The other panel, which is closed at first, has a map with `<canvas ... style="...;display:none;"></canvas>`.  That's ModuleB.

I am getting no JavaScript errors according to IE Edge's debugger.

**Comment by ahocevar** [comment]
Duplicate of #4601. You need to call `Map#updateSize()` when the initially hidden panel is made visible.

**Comment by westandy** [comment]
Sorry, what is the event: "when the initially hidden panel is made visible".  Is it show.bs.collapse, shown.bs.collapse, etc.?  Is there an intended event for which I should call #Map.updateSize()?

**Comment by ahocevar** [comment]
You need to direct your question to the respective Angular channels. The event you're looking for when the panel is visible and has reached its target size.

**Comment by westandy** [comment]
OK, it's an Angular/Bootstrap question then.  Thank you for your time!
