### ISSUE TITLE
Google Map with openlayers 3

### ISSUE THREAD

**Issue by mobileap** [openlayers/ol3#5796]
Hi, 
If I add google map as in this link (http://openlayers.org/en/v3.0.0/examples/google-map.html), when i zoom or drag the map, features also displacing from their position and coming back to its actual position. How can I add Google Map as base map Without displacement of features ???

Thank you.

**Comment by ahocevar** [comment]
The example you linked above was removed in later versions because it does not work properly. The only way to use Google Maps out of the box in OpenLayers is an `ol.layer.Image` with an `ol.source.Image`, using the Google Maps Static API.

You can also try a third-party library: http://mapgears.github.io/ol3-google-maps/.

**Comment by mobileap** [comment]
Hi ahocevar,
When am using http://mapgears.github.io/ol3-google-maps/ this library, am getting so many errors in openlayers 3 functionalities.

**Comment by ahocevar** [comment]
As I said, the only really sane way to use Google Maps with OpenLayers is the Google Maps Static API. However, I'm sure the developers of ol3-google-maps would be glad if you reported your issues there so they can improve the library.

**Comment by ahocevar** [comment]
With all the above said, my opinion is if you want to use Google Maps, use Google Maps directly. Otherwise, use OpenLayers.

**Comment by mobileap** [comment]
Ok  ahocevar, Thank for your help. If possible please help me with the related code or link for adding Google Maps with Google Maps Static API. I can't find it anywhere. Thank you.

**Comment by ahocevar** [comment]
@mobileap Please find out yourself. We cannot encourage the use of Google Maps with OpenLayers because the legal situation regarding Terms of Use are not clear.

**Comment by mobileap** [comment]
@ahocevar  ok thank you.
