### ISSUE TITLE
Circle rotation view problem

### ISSUE THREAD

**Issue by dhivehi** [openlayers/ol3#5797]
A circle drawn with ol.geom.Circle is not properly rendered in latest version. When the map is rotated, an extra line comes making a chord in the circle. 

To reproduce the problem:
* Go to http://openlayers.org/en/latest/examples/draw-features.html.
* Draw a circle
* Rotate the map
* You can see extra line in the circle

Please fix.

**Comment by ahocevar** [comment]
Thanks for reporting this regression. `git bisect` shows that eed52552a9061148c2f995158e90878761f94d1e is the first bad commit. I'm working on a fix now.
