### ISSUE TITLE
ol.ImageState vs ol.style.ImageState

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5799]
We have two enums for the loading state of an image:
 * `ol.ImageState`: https://github.com/openlayers/ol3/blob/v3.18.0/src/ol/imagebase.js#L9-L17
 * `ol.style.ImageState`: https://github.com/openlayers/ol3/blob/v3.18.0/src/ol/style/image.js#L5-L13

We should only keep one

**Comment by ahocevar** [comment]
Good find. I think it's ok to get rid of `ol.style.ImageState`.
