### ISSUE TITLE
Remove the DOM renderer

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#5813]
I anticipate that "build flags" will not be used frequently and that even when used, may not always result in complete dead code removal for unused renderers.  To reduce build sizes and reduce the library size overall, I suggest we remove the DOM renderer.

In order to avoid breaking applications that use it, we could fall back to the Canvas renderer if "dom" is supplied.

I'm interested to hear if others think there is value in keeping it around.

**Comment by bartvde** [comment]
Personally I have never used it, and I can't think of a compelling reason to keep it.

**Comment by fredj** [comment]
Same here: never used it.
Maybe we have kept it for #1084 ?

**Comment by adube** [comment]
We, at Mapgears, never used it in any of our projects.
