### ISSUE TITLE
Remove ol.global

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#5814]
I'm not sure we get any real benefit from using `ol.global` rather than relying on regular scoping behavior.  We are already inconsistent with our use of globals.

E.g. we check for a global `navigator` [in some places](https://github.com/openlayers/ol3/blob/3b6f1f99bc9b867845fcab48420aebce7ab8a8cf/src/ol/has.js#L8-L9) and `ol.global.navigator` [in others](https://github.com/openlayers/ol3/blob/3b6f1f99bc9b867845fcab48420aebce7ab8a8cf/src/ol/geolocation.js#L136-L141).  We also rely on a global `Image` constructor rather than using `ol.global.Image`.

We'll need to change how we override globals in tests, but I don't think this will make any difference for users of the library.  You already have to provide global shims if you run OpenLayers outside a browser.

**Comment by fredj** [comment]
+1 to remove ol.global

**Comment by ahocevar** [comment]
+1 from me as well.
