### ISSUE TITLE
ol.proj.transformExtent() results in -Infinity

### ISSUE THREAD

**Issue by lukerees** [openlayers/ol3#5817]
I am trying to transform the max bounds of EPSG:4326 to the max bounds of EPSG:3857 using `ol.proj.transformExtent([-180,-90,180,90], 'EPSG:4326', 'EPSG:3857');` The result is an extent of [-20037508.342789244, -Infinity, 20037508.342789244, 238107693.26496765].
I have also noticed this issue when reading a geojson from 4326 into a feature with 3857.
I have double checked all the docs and don't think I am doing anything wrong. Could this be a bug? I have tried with ol 3.17 and 3.18.
Thanks

**Comment by marcjansen** [comment]
I am pretty sure that EPSG:3857 isn't covering the whole world. It is cropped around the poles.

Please comment here if you disagree and think this is a bug on our side.
