### ISSUE TITLE
Build failures due to ArrayBuffer.isView renaming

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#5818]
We're getting [build failures](https://travis-ci.org/openlayers/ol3/builds/156674785) that look like they are due to overzealous property renaming within the pbf lib (see https://github.com/openlayers/ol3/pull/5815#issuecomment-243933337 and https://github.com/openlayers/ol3/pull/5794#issuecomment-243938518).

It looks like [this function](https://github.com/mapbox/pbf/blob/v3.0.0/index.js#L7-L11)
```js
function Pbf(buf) {
  this.buf = ArrayBuffer.isView(buf) ? buf : new Uint8Array(buf || 0);
  this.pos = 0;
  this.length = this.buf.length;
}
```
is getting compiled to this (with whitespace added):
```js
function f(a) {
  this.ac = ArrayBuffer.b(a) ? a : new Uint8Array(a || 0);
  this.da = 0;
  this.length = this.ac.length
}
```

So the `isView` property of `ArrayBuffer` is getting renamed to `b`.

Wondering if the Compiler lost some knowledge about `ArrayBuffer` with #5793.

**Comment by fredj** [comment]
`ArrayBuffer.isView` is not present in the closure-compiler externs

**Comment by fredj** [comment]
https://github.com/google/closure-compiler/pull/1991
