### ISSUE TITLE
forEachLayerAtPixel with ol.layer.Image broken for rotated views and device pixel ratio <> 1

### ISSUE THREAD

**Issue by tamaspaksi** [openlayers/ol3#5821]
I have implemented a tooltip function with popups with forEachLayerAtPixel function. It works fine on desktop PC's, but most of mobile devices not. The forEachLayerAtPixel works fine on icon and polygon but on images is founded the image layer not in correct place. If i click a little left-buttom near the image, then the layer is founded, so the place (founded layers on a pixel) is calculated wrong in case of images. (I think the difference, that icon and polygon are vector layers, but the image not.) After some analyse we have found, that it caused, when the css ratio is not 1 (window.devicePixelRatio <> 1). 
- at rotation (alt+shift+mouse) it works faulty also on desktop! The calculated place remaining somewhere on the original place, it's not moving with the picture.

I've attached a sample program:
[popup-1.zip](https://github.com/openlayers/ol3/files/449112/popup-1.zip)

**Comment by ahocevar** [comment]
What version of OpenLayers are you using? This issue should be fixed with v3.18.x. See #5731.

**Comment by tamaspaksi** [comment]
The problem comes with 3.18.1 too.

**Comment by ahocevar** [comment]
Oh, I see now you're using `ol.layer.Image`, not `ol.layer.Tile`. So it seems we're having the same issue there.

**Comment by ahocevar** [comment]
#5731 also did not fix the issue for tile layers.
