### ISSUE TITLE
vector render problem 

### ISSUE THREAD

**Issue by txtdevelop** [openlayers/ol3#5822]
ol version: 3.18.1
[http://jsfiddle.net/cakbfwff/6/](http://jsfiddle.net/cakbfwff/6/)
if you extend the map area in this fiddle you'll see that the right square will lose a vertex

![0](https://cloud.githubusercontent.com/assets/21575735/18163007/21eac29a-7039-11e6-8e73-a8551af6a2f3.png)
![1](https://cloud.githubusercontent.com/assets/21575735/18163013/27763f00-7039-11e6-9b37-4349057d6225.png)

**Comment by ahocevar** [comment]
Thanks for reporting this issue. It's a regression caused by #5708. See #5826 for a fix.
