### ISSUE TITLE
clone method for styles

### ISSUE THREAD

**Issue by simonseyock** [openlayers/ol3#5823]
i would like to make the proposal to introduce a clone method on styles which would create a new style object with the same properties as the old one.

This would be very useful if one would like to change the style of some features, which are styled by a style used for multiple features or even a whole layer - changing the style would result in changes for all other features. I am thinking especially about styles declared outside of the domain of the application, i.e. in a KML.

Sadly there is no base class for all styles, otherwise i would propose an abstract method on this class.

**Comment by simonseyock** [comment]
There is this answer on stackoverflow: http://gis.stackexchange.com/questions/158713/how-to-clone-an-ol3-style#158744
But i think this would be an useful feature to be covered by the library. And the proposed solution has the little caveat that the resulting object is not an ol.style.Style object but a generic one.

**Comment by tschaub** [comment]
A clone method for styles sounds like a good idea to me (see also https://github.com/openlayers/ol3/issues/4781#issuecomment-180082908).

I don't think we'd gain anything out of an abstract method on a base class.

**Comment by simonseyock** [comment]
It would look like #5830

**Comment by simonseyock** [comment]
https://github.com/openlayers/ol3/pull/5832

**Comment by simonseyock** [comment]
I wrote some clone methods and added a test for ol.style.Circle#clone. Does anyone wants to look into it?
See #5832

**Comment by simonseyock** [comment]
See #5832
