### ISSUE TITLE
GML writeFeatures doesn't output string

### ISSUE THREAD

**Issue by lol2x** [openlayers/ol3#5836]
When I'm trying to generate gml string it doesn't work and create a lot of errors:
[gist - gml](https://gist.run/?id=39e1d528f2203b1bd2b9dc0342493f01)
[image of errors](https://i.imgur.com/nFWblV9.png)

however same approach in kml works just fine:
[gist - kml](https://gist.run/?id=aab7e8788c58088de95eadd6acc6a966)

gists are based on OL3 box selection example so in order to generate gml/kml you need to Use Ctrl+Drag

**Comment by bartvde** [comment]
You need to specify featureNS and featureType in the ol.format.GML constructor when writing out.

**Comment by bartvde** [comment]
Closing, please reopen if this is still an issue for you.
