### ISSUE TITLE
wfs does not work. need help

### ISSUE THREAD

**Issue by Almodovar** [openlayers/ol3#5844]
http://openlayers.org/en/latest/examples/vector-wfs.html 

This example works on my computer. But when I change the wfs link from 

http://demo.boundlessgeo.com/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=osm:water_areas&outputFormat=application/json

to 

http://localhost:8080/geoserver/gullycreek/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gullycreek:field&outputFormat=application/json

the layer cannot be displayed. I've tested in geoserver that the json file is generated.

**Comment by ahocevar** [comment]
You may want to read up on Same Origin Policy and CORS headers.

**Comment by Almodovar** [comment]
http://demo.boundlessgeo.com/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=osm:water_areas&outputFormat=application/json

The example use this link which should be an external link right? In ol version 3.5, the ol.source.ServerVector is deleted and the sample on version 3.5 does not work.

**Comment by ahocevar** [comment]
Oh sorry, hadn't read your comment until the end. Ii's not a CORS or Same Origin Policy problem. More likely a projection and/or axis order problem. Carefully compare the WFS 1.0.0 and 1.1.0 responses, looking at the coordinates.

**Comment by Almodovar** [comment]
Thanks fro the reply. I compare the coordinates and they are exactly the same. When I use ol 3.4, I can display the layer using the ol.source.ServerVector with the same link.
