### ISSUE TITLE
MapGuide example is broken

### ISSUE THREAD

**Issue by TDesjardins** [openlayers/ol3#5847]
The MapGuide example doesn't work any more: 
http://openlayers.org/en/latest/examples/mapguide-untiled.html
Presumably this is not related to ol3 because it also doesn't work with older versions.

Error message:
`Problem:\nCannot establish connection to the MapGuide Server.\n\nPossible Causes:\n-Your session has been idle for too long;\n-MapGuide Server is no longer responding;\n-Internet connection problems.\n\nSolution:\nRestart your application / session, restart the MapGuide Server service, or contact with the server administrator.`

It seems this is not a temporarily issue because the problem exists for several days.

**Comment by bartvde** [comment]
@jumpinjackie any insight on this one?

**Comment by jumpinjackie** [comment]
@bartvde It looks like the mgserver process at data.mapguide.com is down. I'm not the operator of that site.

**Comment by bartvde** [comment]
thanks, okay so nothing we can do about it here, closing.

**Comment by jumpinjackie** [comment]
FYI data.mapguide.com appears to be back up and the ol3 example works again.

**Comment by bartvde** [comment]
thanks for the feedback @jumpinjackie
