### ISSUE TITLE
Drawing MultiPoint

### ISSUE THREAD

**Issue by domiSchenk** [openlayers/ol3#5850]
I noticed when drawing MultiPoints, i get a new Feature for each Point, with an MultiPoint geom, i draw. And not one MultiPoint with all Points inside.

Is this behavior desired? or do i miss somthing?

The same for MultiPolygon.

In my opinion the interaction should create one Feature with all Points/Polygons/... inside.

**Comment by ahocevar** [comment]
This is the intended behaviour, and is the same for all geometry types. If you want a different behaviour, you have to regroup geometries at the application level.
