### ISSUE TITLE
Polygons change shape when partially out of view

### ISSUE THREAD

**Issue by cm-perrs** [openlayers/ol3#5873]
Draw rectangular shaped polygons like so:
```
var outlineFeature = new ol.Feature({
	geometry: new ol.geom.Polygon([outline])
});
```
When the map is panned and the polygon is partially out of view, the rectangular shape changes. Is this a bug or is there a setting to stop this? 
Vector layer settings include:
`updateWhileAnimating: true, updateWhileInteracting: true`
Images attached.

![image](https://cloud.githubusercontent.com/assets/22140885/18424035/b0134782-78ee-11e6-8681-296de5178dd9.png)
![image](https://cloud.githubusercontent.com/assets/22140885/18424041/ba6ec9e0-78ee-11e6-8949-fd9b5ef88352.png)

**Comment by cs09g** [comment]
when drags feature, it happens the same.
![image](https://cloud.githubusercontent.com/assets/7428017/18424179/ef8a376a-78e7-11e6-97a8-4a86f79c644e.png)
![image](https://cloud.githubusercontent.com/assets/7428017/18424183/f988738a-78e7-11e6-9a2a-8ab87b998d3c.png)

**Comment by bartvde** [comment]
what version are you using? Did you check 3.18.2?

**Comment by ahocevar** [comment]
If you are using v3.18.2 already, make sure your polygon rings have the first vertex repeated as last vertex, so e.g. `[[10, 10], [20, 10], [20, 20], [10, 20], [10, 10]]`.

**Comment by cs09g** [comment]
Thank you @ahocevar

**Comment by ahocevar** [comment]
@cs09g Were you able to resolve your issue? Can we close this?

**Comment by cs09g** [comment]
@ahocevar That solves my problem but @cm-perrs

**Comment by cm-perrs** [comment]
@ahocevar thanks that works
