### ISSUE TITLE
Interactive OverviewMap ?

### ISSUE THREAD

**Issue by felixveysseyre** [openlayers/ol3#5874]
Hello,

Looking to make an interactive view on my OpenLayers3 map, I found this old issue https://github.com/openlayers/ol3/issues/3753.

I would like to know if any progress have been made on this subject, or if the advised solution is still to build it custom OverviewMap control.

Thanks,

**Comment by bartvde** [comment]
Please comment in the old ticket, instead of opening a new one.

**Comment by felixveysseyre** [comment]
@bartvde I already commented on the old ticket and I did not get any answer. That is why I have opened a new ticket.

**Comment by bartvde** [comment]
so probably nothing happened? I don't know of any efforts.

**Comment by jonataswalker** [comment]
@felixveysseyre I have a start on this, locally for now. Keep an eye at https://github.com/jonataswalker/ol3-interactive-overview.

**Comment by jonataswalker** [comment]
@felixveysseyre I've made a first commit there. I'll need some help.

**Comment by felixveysseyre** [comment]
@jonataswalker Looks good ! What do you need from me ?

**Comment by jonataswalker** [comment]
@felixveysseyre Let's talk there, but essentially is: usage and report bugs and missing features.

**Comment by felixveysseyre** [comment]
Hello @jonataswalker,

I have looked to your repo in details.

It was working correctly on my side but I had difficulties using as easily as the default _ol.control.OverviewMap_. Mostly because your custom control does not seem to inherit default parameters of the main map (_layer_, _view_, _projection_, etc.).
Therefore I have enhanced the default _ol.control.OverviewMap_ with requested behaviors to make it interactive. I have based my work on yours so I will make sure to tag you in the pull request.

Make sure to take a look to at: 
https://github.com/felixveysseyre/ol3/commit/2b7ed7381fb5d353f092b0dee84b3fd44e625f99

**Comment by jonataswalker** [comment]
Yeah, it is just a very beginning, a WIP.

**Comment by felixveysseyre** [comment]
Hello @bartvde,

I have improved the _ol.control.OverviewMap_ with an interactive option and created a pull request: https://github.com/openlayers/ol3/pull/5887.

What would be to correct behavior to merge-in this pull request ?

Thanks for your time.
