### ISSUE TITLE
Canvas renderer on android causing data to jump with the view

### ISSUE THREAD

**Issue by onack** [openlayers/ol3#5879]
When panning around the canvas layer is following the view on mobile, but panning correctly on desktop.

This might be an issue with mobile chrome and not openlayers

Works fine on Chrome 50.0.2661.75 and Firefox developers edition 50.0a2 on Linux Mint
Works on IE: 10.0.9200.17609 on Windows 7 SP1, view height is cut in half

Does not work on Chrome 52.0.2743.98 on Android 6.0.0(LG G4)
Does not work on Firefox 48 on Android 6.0.0(LG G4)
Does not work on Chrome 52.0.2743.98 on Android 6.0.1(Sony Xperia Z4 tablet)
Does not work on Safari iOS 9.3.5
Does not work on Chrome and Safari on 10.11.6 OSX

Example code:
https://jsfiddle.net/vmtgessy/4/

**Comment by ahocevar** [comment]
This is a problem with your application, not OpenLayers or Mobile Chrome. You need to use the `pixelRatio` that gets passed to the `canvasFunction` to create a canvas that also works on HiDPI devices. See https://jsfiddle.net/vmtgessy/5/ for an updated Fiddle.

**Comment by onack** [comment]
Thank you for the trouble
