### ISSUE TITLE
ol.source.TileWMS does not consider tilePixelRatio

### ISSUE THREAD

**Issue by cvenzin** [openlayers/ol3#5899]
I have a `ol.source.TileWMS` with a tile size of 256px but the server returns tiles with sizes of 512px (by intention). This gives you a better quality if you print the map due to the higher dpi. For this case, there is a `tilePixelRatio` property on the `ol.source.TileImage` and the `ol.source.TileWMS` inherits from this class. So `tilePixelRatio`  should be available in `ol.source.TileWMS` aswell.
Now, first problem,  I can't set the `tilePixelRatio` on the `ol.source.TileWMS` except with the private property `tilePixelRatio_` in debug mode. And even if I set it, there is a second problem, because the function `ol.source.Tile.prototype.getTilePixelSize = function(z, pixelRatio, projection)` does not take `tilePixelRatio_` into account and just returns the argument `pixelRatio` that is given to the function. 
If I change 

```
ol.source.TileWMS.prototype.getTilePixelRatio = function(pixelRatio) {
  return (!this.hidpi_ || this.serverType_ === undefined) ? 1 :
      /** @type {number} */ (pixelRatio);
};
```

to

```
ol.source.TileWMS.prototype.getTilePixelRatio = function(pixelRatio) {
  return (!this.hidpi_ || this.serverType_ === undefined) ? 1 :
      /** @type {number} */ (this.tilePixelRatio_);
};
```

it works, even with the property `gutter` set.
Did someone face the same problem or do I miss something?

**Comment by jhwegener** [comment]
Hey @cvenzin , i'm facing with the same problem! How did you solve it?
