### ISSUE TITLE
StyleFunction executed with wrong arguments

### ISSUE THREAD

**Issue by chrismayer** [openlayers/ol3#5902]
It looks like the ``ol.renderer.canvas.VectorLayer`` invokes a possible ``ol.StyleFunction`` in a wrong way:

```javascript
styles = styleFunction.call(feature, resolution);
```   
(see https://github.com/openlayers/ol3/blob/master/src/ol/renderer/canvas/vectorlayer.js#L293)

Since the call function is missing the owner object as first argument, the style function itself will be called with the resolution as the only argument because the feature is interpreted as owner object.

It seems that the invocation of the style function should be like this:

 ```javascript
styles = styleFunction.call(this, feature, resolution);
```  
Any thoughts on this? TIA!

**Comment by marcjansen** [comment]
Thanks for reporting this, I think you are right and this looks suspicious to me. I am not an expert though.

The code could even look like

```js
styles = styleFunction(feature, resolution);
```

like in the case below, right?

Can you come up with a pull request that includes a test for this case? 

Also I'd value the input of other people more involved in the canvas rendering thingy.

**Comment by marcjansen** [comment]
But…

http://openlayers.org/en/latest/apidoc/ol.html#.FeatureStyleFunction

tells me that a feature style function `… returns an array of styles given a resolution. The this keyword inside the function references the ol.Feature to be styled.`

Unsure here.

**Comment by bartvde** [comment]
I vaguely remember feature style functions behaving differently from layer style functions

**Comment by bartvde** [comment]
Right @marcjansen so I think the current code is correct given the API docs.

**Comment by fredj** [comment]
> I vaguely remember feature style functions behaving differently from layer style functions

For historical reasons we have both `ol.FeatureStyleFunction` and `ol.StyleFunction` typedefs.
We could simplify this by only keeping one typedef but it will break the stable api.

**Comment by chrismayer** [comment]
Thank you all for your comments! I see the difference now. So no need for a PR now.

From a personal point of view this can be confusing, if you are not into the details. A simplification, like @fredj already stated, would be good. But I see the problem with the API break.
