### ISSUE TITLE
Only rendering first 4 tile layers

### ISSUE THREAD

**Issue by Barryrowe** [openlayers/ol3#5908]
I've been doing some testing and it appears that any tile layers after 4th tile layer are not rendered.

We have a custom tile server that generates several pre-rendered layers with transparencies. If we try to layer on more than 4, the additional tile layers are not rendered. Any vector layers added afterward still render fine.

I've been digging through the API docs and other questions but haven't found anyone else encountering this issue.  

I'm working with version 3.18.2 (installed via NPM).

**Comment by marcjansen** [comment]
Huh?!?!

Fiddle or it didn't happen!

Can you provide a jsfddle where one can reproduce ?

**Comment by Barryrowe** [comment]
I'll work one up, is there a fiddle template handy anywhere I can drop some layer building code into?

**Comment by Barryrowe** [comment]
I think I see what's happening...I was expecting setAt() to bump the layer at the index up (and thusly adjust the array like an insertAt() would do).  But it appears to just replace it.  

Am I missing a way to insertAt() without clobbering a layer at the position?
