### ISSUE TITLE
Bug: ol.format.WFS omits Elements when tag name appears more than once

### ISSUE THREAD

**Issue by RobinJLuckey** [openlayers/ol3#5915]
Hi,

When a WFS sends a Response containing several elements with the same tag name only the first Feature is parsed.
Consider the example at the Bottom, the response contains multiple tags with the same name returnd by a WFS.
The parsed Object contains only the first <app:Leistungsname> as Element.

Thanks
Robin

Example:`
<gml:featureMember>
    <app:KitaEinrichtungen xmlns:app="http://www.deegree.org/app" gml:id="APP_KITAEINRICHTUNGEN_1012065">
      <app:Leistungsname>Krippe bis zu 8-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Krippe bis zu 6-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Krippe bis zu 5-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Krippe bis zu 4-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Krippe bis zu 12-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Krippe bis zu 10-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Elementar bis zu 8-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Elementar bis zu 12-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Elementar bis zu 6-stündige Betreuung</app:Leistungsname>
      <app:Leistungsname>Elementar bis zu 5-stündige Betreuung mit Mittagessen</app:Leistungsname>
      <app:Leistungsname>Elementar bis zu 10-stündige Betreuung</app:Leistungsname>
      <app:geom>
        
        <gml:Point gml:id="APP_KITAEINRICHTUNGEN_1012065_APP_GEOM" srsName="EPSG:25832">
          <gml:pos>561844.454 5933946.256</gml:pos>
        </gml:Point>
      </app:geom>
    </app:KitaEinrichtungen>
  </gml:featureMember>
`

**Comment by ahocevar** [comment]
OpenLayers's WFS format only parses simple features, so you cannot have a feature with multliple properties with the same name.
