### ISSUE TITLE
ol.format.filter yet documented as ol.format.ogc.filter

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5929]
Docs and examples still report ol.format.ogc.filter.* while filters are now rooted directly ander ol.format. Isn'it?

**Comment by bartvde** [comment]
I guess the docs haven't been updated since that change, it's a "manual thing" to re-deploy the website

**Comment by giohappy** [comment]
right @bartvde I see that, e.g., https://github.com/openlayers/ol3/blob/master/src/ol/format/filter/index.jsdoc is correctly up to date. 
So this is just a problem with the online apidocs not being updated...

**Comment by fredj** [comment]
Forgot to mention that I have updated the apidoc

**Comment by giohappy** [comment]
thanks @fredj I've seen (12 days ago). How often is the website content updated?

**Comment by bartvde** [comment]
There is no fixed frequency, whenever someone runs the scripts
