### ISSUE TITLE
Error with map.forEachFeatureAtPixel() on Safari

### ISSUE THREAD

**Issue by peder280370** [openlayers/ol3#5940]
Hi

I experience an error when trying to detect which features I hover over (or click) in a vector layer. The error only happens in Safari, not e.g. Chrome, Firefox or Edge, and only if some of the features are displayed using scaled icons (no error if icons are not scaled).

Basically, after a while the call to map.forEachFeatureAtPixel() will start returning too many features, and once OpenLayers has entered this bogus state, it will continue reporting false positives.

For verification, please use the following JSFiddle test with Safari:
https://jsfiddle.net/peder280370/s2myue71/3/
Initially, when you hover over the three features in turn, the correct one will be listed in the white panel, bottom-left. However, if you keep mousing over the three features, then at some stage OpenLayers will start wrongly reporting two matches at a time, and keep on doing that.

Versions: OpenLayers 3.18.2, Safari 10.0 on macOS Sierra.

Thanks,
- Peder

**Comment by fredj** [comment]
Do you have the same issue with the `master` version? http://openlayers.org/en/master/build/ol.js

**Comment by peder280370** [comment]
Yes, I see the same error with master.
I updated the test to use the current OL master version: https://niord-proxy.e-navigation.net/ol-error.html
Btw, I also tested a few older OL 3 versions, such as 3.15.1, and experienced the same issue, although the amount of time (or number of times) you have to hover over features before the bug kicks in might vary from version to version.

**Comment by fredj** [comment]
There's an error about the icon image (in the debugger console):
```
Unable to get image data from canvas because the canvas has been tainted by cross-origin data.
```

Try to copy the image locally and see if the issue persist. (or maybe it's the `0.3` scale that is not correctly handled)

**Comment by peder280370** [comment]
Ah, I forgot to move the image locally when I set up the new test site. Fixed now.
However, it has no bearing on the error. 
And yes, the error only occurs when I use a scaled icon. You need to repeatedly cycle the mouse cursor over the features for a while (typically 5-20 secs), before it enters the bogus state, after which map.forEachFeatureAtPixel() always returns two features, even when you just hover over a single one.

**Comment by ahocevar** [comment]
It turns out that this comes from floating point issues with transforming back and forth for applying scale and rotation to images and texts. In #5964, I changed this by using context.save/restore instead.
