### ISSUE TITLE
Styling modify interaction with geometry causes an error

### ISSUE THREAD

**Issue by dhivehi** [openlayers/ol3#5945]
cannot use the following function in modify interaction styling:       
geometry: function(feature) {
              var coordinates = feature.getGeometry().getCoordinates()[0];
              return new ol.geom.MultiPoint(coordinates);
 }

**Comment by tsauerwein** [comment]
Assuming that `feature.getGeometry()` is of type `MultiPoint`: [getCoordinates()](http://openlayers.org/en/master/apidoc/ol.geom.MultiPoint.html#getCoordinates) returns `Array.<ol.Coordinate>`. You are taking the first element, so the variable `coordinates` is of type `ol.Coordinate`. But the constructor of [MultiPoint](http://openlayers.org/en/master/apidoc/ol.geom.MultiPoint.html) expects `Array.<ol.Coordinate>`.

Either wrap `coordinates` in an array (e.g. `new ol.geom.MultiPoint([coordinates])`), or use [ol.geom.Point ](http://openlayers.org/en/master/apidoc/ol.geom.Point.html).
