### ISSUE TITLE
Constructor property "style" of ol.Feature does not apply

### ISSUE THREAD

**Issue by tSte** [openlayers/ol3#5947]
This bug broke our build recently when we updated to 3.18.2.

```
envelopeFeature = new ol.Feature({
    geometry: bboxGeom,
    style: envelopeStyle // instance of ol.style.Style
});

envelope.getStyle(); // returns null
```

We fixed this by adding `envelopeFeature.setStyle(envelopeStyle)`

**Comment by marcjansen** [comment]
But this was never possible, right?

With which version was the above supposed to return the passed `envelopeStyle` instead of `null`?

**Comment by tSte** [comment]
I looked into the source and you are right, this should be never possible. The strange thing is, that we supplied `style` to the `ol.Feature` constructor and the new feature was correctly rendered...

We updated the Closure compiler to the latest version, but I doubt that it could have any impact on this.

**Comment by marcjansen** [comment]
Thanks for the clarification.
