### ISSUE TITLE
[Help]Cluster Strategy openlayer 3

### ISSUE THREAD

**Issue by yungfei1989** [openlayers/ol3#5952]
[Help]
Hi all, can we implement strategy in cluster like openlayer 2? I don't find any example to cluster with strategy in openlayer3. I want to cluster only a feature which have the same class.. How to code it? thx

**Comment by bartvde** [comment]
http://stackoverflow.com/questions/39993096/how-to-make-clustering-strategy-in-openlayer-3 please don't use multiple channels
