### ISSUE TITLE
test_rendering broken

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#5968]
`make serve` and load http://localhost:3000/test_rendering/

Only the first test is run:

![rendering_tests](https://cloud.githubusercontent.com/assets/100959/19390392/2f8bdc20-9228-11e6-8c6a-6be08116490d.png)

**Comment by ahocevar** [comment]
@fredj ^^

**Comment by fredj** [comment]
![power-rangers](https://cloud.githubusercontent.com/assets/100959/19390908/948ca030-922a-11e6-9a33-203983097f70.gif)
