### ISSUE TITLE
KML placemark not working consistently

### ISSUE THREAD

**Issue by ssdhaliwal** [openlayers/ol3#5974]
The kml is valid and works when rendered directly - the entire KML is placemarks (over 90K) where placemarks are very close together (did not find a threshold setting for clustering to restrict max # of placemarks per cluster)

- this works

>                 var vectorKMLLayer = new ol.layer.Vector({
                    style: new ol.style.Style({
                        // placemark style
                        image: new ol.style.Circle({
                            radius: 6,
                            stroke: new ol.style.Stroke({
                                color: 'rgba(170,33,33, 0.3)',
                                width: 2
                            }),
                            fill: new ol.style.Fill({
                                color: 'rgba(170,33,33, 0.8)'
                            })
                        }),
                        // line style
                        stroke: new ol.style.Stroke({
                            color: '#ffcc33',
                            width: 2
                        })
                    })
                });
                vectorKMLLayer.setSource(vectorKMLSource);

- this returns error (but works with smaller dataset)

>                 var clusterKMLSource = new ol.source.Cluster({
                    distance: 10,
                    source: vectorKMLSource
                });
                var clusterKML = new ol.layer.Vector({
                    source: clusterKMLSource,
                    style: function (feature) {
                        var size = feature.get('features').length;
                        var style = clusterStyleCache[size];
                        if (!style) {
                            style = new ol.style.Style({
                                image: new ol.style.Circle({
                                    radius: 10,
                                    stroke: new ol.style.Stroke({
                                        color: '#fff'
                                    }),
                                    fill: new ol.style.Fill({
                                        color: '#3399CC'
                                    })
                                }),
                                text: new ol.style.Text({
                                    text: size.toString(),
                                    fill: new ol.style.Fill({
                                        color: '#fff'
                                    })
                                })
                            });
                            clusterStyleCache[size] = style;
                        }
                        return style;
                    }
                });

          mapView.addLayer(clusterKML);

Thanks

**Comment by ssdhaliwal** [comment]
narrowed down the issue to be processing of KML when using clustering.  Below is the small KML which works fine when rendering as individual placemarks - but fails when rendering using cluster placemark.  It is the special & in the name which was causing the issue.

I am able to duplicate this successfully - when placing & in the name the cluster fails but kml will render fine without clustering.

**Comment by ssdhaliwal** [comment]
Ok this started with error #10 for clustering but then found that normal rendering of placemark file with special characters seemed like it was working but it is not.

1) normal placemark rendering - if name has special character, then the processing is stopped but no error is reported.

2) clustering of placemarks - if name has special character, then error #10 is reported.

**Comment by ahocevar** [comment]
The ampersand (`&`) is an escape character in XML, unless your data is in a `CDATA` section. So you either need to escape the ampersand to `&amp;`, or put wrap the name in `<![CDATA[``]]>`.

**Comment by ssdhaliwal** [comment]
I understand the special character handling in kml, but what I found was there is no error when placemarks are rendered with special characters - the processing stops and placemarks which were not in error are rendered - rest are ignored.  There should be an error generated if the data is invalid.  The error is only generated when clustering is done, not for regular kml processing.
