### ISSUE TITLE
vector-osm example broken

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#5988]
The vector-osm example no longer works, because the maps XAPI from http://overpass-api.de/ is no longer available. See drolbr/Overpass-API#328.

**Comment by fredj** [comment]
See also #3577

I'm tempted to remove this example, what do you think? And if `ol.format.OSMXML` wasn't api stable I would have removed it too

**Comment by ahocevar** [comment]
It would make sense to remove both the example and the format. But the latter will have to wait until 4.0.

**Comment by mmd-osm** [comment]
No need to remove the example, just switch to Overpass QL:

Example: http://overpass-turbo.eu/s/jrA

**Comment by mmd-osm** [comment]
Or better even: use the map call instead: http://overpass-api.de/api/map?bbox=9.58186,49.20689,9.59870,49.21423

**Comment by ahocevar** [comment]
> No need to remove the example, just switch to Overpass QL

@mmd-osm Done in #6004.
