### ISSUE TITLE
Tiles reprojection doesn't work

### ISSUE THREAD

**Issue by drnextgis** [openlayers/ol3#5992]
Trying to display EPSG:3395 tile layer over EPSG:3857. As you can see in [this](https://jsfiddle.net/_DR_/e9vnmv0w/) demo - layers are shifted.

**Comment by ahocevar** [comment]
Are you sure you are using the correct tile grid and projection definition for the 3359 layer? The latter you can verify by transforming some points from 4326 or 3857 and checking their location on a OSM map. The former by using 3359 as view projection and rendering some 3359 points on top of the tile layer.

**Comment by drnextgis** [comment]
Yes I'm sure about projection definition for 3395 layer: openlayers and cs2cs returns the same coordinates. In the following [demo](https://jsfiddle.net/_DR_/e9vnmv0w/12/) I'm trying to display point with coordinates of Statue of Liberty but as you can see it doesn't work. Am I missing some tile grid options?

**Comment by fredj** [comment]
@drnextgis did you see http://gis.stackexchange.com/questions/187082/openlayers-3-projection-for-yandex-maps ?

**Comment by drnextgis** [comment]
@fredj, yes but in my last demo both layers has the same projection.

**Comment by ahocevar** [comment]
@drnextgis You'll need to use `ol.source.XYZ`, not `ol.source.OSM`. The latter uses a EPSG:3857 tile grid, and the former will generate a correct projection specific tile grid for you. I updated your JSFiddle [here](https://jsfiddle.net/e9vnmv0w/19/).

**Comment by drnextgis** [comment]
@ahocevar thanks! Could you help me with example from my second comment. Why vector point placed at not expected place https://jsfiddle.net/_DR_/e9vnmv0w/12/

**Comment by ahocevar** [comment]
What about [this](https://jsfiddle.net/e9vnmv0w/20/) @drnextgis? It looks like Yandex uses EPSG:3359 coordinates but EPSG:3857 tiles. Definitely more research needed to make it work correctly, but no OpenLayers bug here - just wrong configuration due to incomplete information.

**Comment by drnextgis** [comment]
It works! Another solution is set up extent of grid manually:

```js
new ol.layer.Tile({
  source: new ol.source.XYZ({
    url: 'http://vec01.maps.yandex.net/tiles?l=map&x={x}&y={y}&z={z}',
    projection: 'EPSG:3395',
    tileGrid: ol.tilegrid.createXYZ({
      extent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    })
  })
});
```

Full [demo](https://jsfiddle.net/_DR_/e9vnmv0w/21/)
