### ISSUE TITLE
Failing tests in MS Edge

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#5996]
We currently have 45 failing tests in Microsoft Edge 38.14393.0.0.

44 of them can be fixed by always using a [URL](https://developer.mozilla.org/en/docs/Web/API/URL)-polyfill, not only when the user-agent signals it to `polyfill.io`. PR to come.

The remaining error will be examined and tackled separately.

**Comment by marcjansen** [comment]
The remaining error is an IndexSizeError and occurs in `src/ol/renderer/canvas/tilelayer.js` (Line 364), when `renderContext.drawImage` is called.

From MSDN

> The numeric arguments are not valid (for example, the destination is a 0x0 rectangle). Versions earlier than Internet Explorer 10 use INDEX_SIZE_ERR.

The arguments for 

```js
renderContext.drawImage(tile.getImage(), tileGutter, tileGutter,
        tilePixelSize[0], tilePixelSize[1], left, top, w, h);
```

are:

```
tileGutter             (sx):    0
tileGutter             (sy):    0
tileGutilePixelSize[0] (sw):    256
tileGutilePixelSize[1] (sh):    256
left                   (dx):    -20037499
top                    (dy):    -60112487
w                      (dw):    40075017
h                      (dh):    40075017
```

The same values also come up in Chrome, but there the test passes.

Can anybody share an idea what is wrong there? @ahocevar possibly?

(Above values com from a variant of the current code, where the `img` from `getImage` is an image created with `new Image(10, 10)`, not sure if this has any impact.)

Are the remarks from [this MSDN-page on `canvas element | canvas object`](https://msdn.microsoft.com/en-us/library/ff975062(v=vs.85).aspx) somehow relevant?

> Note  The maximum size of the rendered area on a canvas is from 0,0 to 8192 x 8192 pixels, regardless of the size of the canvas. For example, a canvas is created with a width and height of 8292 pixels. A rectangular fill is then applied as "ctx.fillRect (0,0, canvas.width, canvas.height)".Only the area within the coordinates (0, 0, 8192, 8192) can be rendered, leaving a 100 pixel border on the right and bottom of the canvas.

**Comment by ahocevar** [comment]
Checking this now. Looks like we render to a map with an incorrect size.

**Comment by ahocevar** [comment]
@marcjansen #6000 fixes the test.
