### ISSUE TITLE
get all features in wms layer or ol.source.ImageWMS

### ISSUE THREAD

**Issue by xaadim** [openlayers/ol3#5998]
The OL3 getGetFeatureInfoUrl method is based on the coordinates (x, y), resolution, projection and output parameters. Here the features it only gets this message and what would be nice is to have the features not from that contact that represents a point but rather a BBOX like getFeaturesInExtent or forEachFeatureInExtent method that applies unfortunately that 'ol.source.Vector the source.

Ideas?

**Comment by ahocevar** [comment]
The WMS standard does not have a way to do this. If the WMS is linked to a WFS, you can use WFS GetFeature to achieve what you want.

**Comment by xaadim** [comment]
Thanks
