### ISSUE TITLE
gutter and pixelRatio

### ISSUE THREAD

**Issue by oterral** [openlayers/ol3#6001]
Since https://github.com/openlayers/ol3/pull/5273 our tiled WMS are not well aligned on devices with pixelRatio different higher than 1

There is an offset on top-left.

Here is the bug : https://jsfiddle.net/t8ycm06f/2/

Here is how th map should be: https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&X=187963.00&Y=673434.25&zoom=1&layers=ch.swisstopo.fixpunkte-lfp2

In the 2nd link the map is defined with the property pixelRatio to 1. 

We also have a problem with this PR https://github.com/openlayers/ol3/pull/5731 . Detection have also an offset on top-left

@fredj do you have an idea why?

**Comment by fredj** [comment]
@oterral The layer with the gutter is missing the `serverType: 'mapserver'` option, can you add it add tell if it looks better ?

**Comment by ahocevar** [comment]
It should also work when the source uses a different pixel ratio than the device. #6002 fixes this issue.

**Comment by fredj** [comment]
@oterral please open a new issue for the problem with #5731

**Comment by oterral** [comment]
@fredj Yes with `serverType: 'mapserver' ` it works.

Can you explain me why?

@ahocevar Thx for the quick fix !!!

**Comment by fredj** [comment]
By using `source.getTilePixelRatio(pixelRatio)` instead of `pixelRatio` (in `src/ol/renderer/canvas/tilelayer.js`) the pixel ratio of the source is used.
