### ISSUE TITLE
OSM vector tiles example does not work

### ISSUE THREAD

**Issue by simonseyock** [openlayers/ol3#6009]
The OSM vector tiles example does not work.

http://openlayers.org/en/master/examples/osm-vector-tiles.html

The vector tiles are not loaded and the server responds with the message `Mapzen has released Vector Tiles 1.0. For more information visit: https://mapzen.com/blog/v1-vector-tile-service/`

**Comment by marcjansen** [comment]
Fixed with #5985?

**Comment by simonseyock** [comment]
Yes, didn't see that.

**Comment by marcjansen** [comment]
`en/master/` has just been updated with latest master.
