### ISSUE TITLE
Regression: Fill style with CanvasPattern looks worse

### ISSUE THREAD

**Issue by tchandelle** [openlayers/ol3#6010]
Since f655f6740e262f14c376ca55964daacd69707664, Canvas Pattern looks worse at high zoom (> 20).

You can try here : https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html, zoom in 17 times on France for example.

Zoom 19 :
![image](https://cloud.githubusercontent.com/assets/19923657/19597530/7845aa5a-9795-11e6-843b-2b05f80c8298.png)
Zoom 20 :
![image](https://cloud.githubusercontent.com/assets/19923657/19597515/651d70c0-9795-11e6-8f66-acbd798a9830.png)
Zoom 21 :
![image](https://cloud.githubusercontent.com/assets/19923657/19597523/70062f4a-9795-11e6-890b-1a9805f5d4cf.png)

Tested on Chrome 53.0.2785.143 m and Firefox 49.0.1 on Windows 7.

**Comment by tchandelle** [comment]
Here is what it looks like in our applications : 

![image](https://cloud.githubusercontent.com/assets/19923657/19597644/14988436-9796-11e6-9096-3040bbad4eee.png)
![image](https://cloud.githubusercontent.com/assets/19923657/19597651/1f8acc28-9796-11e6-990d-b8ccf8370e0c.png)
![image](https://cloud.githubusercontent.com/assets/19923657/19597661/2c55638c-9796-11e6-89b0-4ad3e25c1251.png)

Even the stroke is sometimes misaligned compared to the Select style :
![image](https://cloud.githubusercontent.com/assets/19923657/19597677/4741e2f6-9796-11e6-96e7-dec2e0172640.png)

**Comment by marcjansen** [comment]
@ahocevar thoughts?

**Comment by ahocevar** [comment]
Definitely something that needs to be addressed, but I wouldn't call it a regression since pattern rendering was unusable *before* 3.19.

**Comment by fredj** [comment]
Probably Windows specific, this is what I get at zoom 21 (Linux Chrome version 53):

![canvas_pattern_21](https://cloud.githubusercontent.com/assets/100959/19601281/eed71042-97a8-11e6-8cf5-f6fa067a3e78.png)

**Comment by tchandelle** [comment]
@fredj You can still see some distortions in the middle. 

Can you also try to rotate the map ?

**Comment by fredj** [comment]
> Can you also try to rotate the map ?

I can see the same (bad) results when the view is rotated: it's not Windows specific
