### ISSUE TITLE
Bundling Openlayers with Ionic2/Angular2 AoT compilation

### ISSUE THREAD

**Issue by cvenzin** [openlayers/ol3#6021]
When Openlayers is bundled, an error occurs when the bundled js file is loaded.
In the beginning of ol-debug.js we have the following code:

```

;(function (root, factory) {
  if (typeof exports === "object") {
    module.exports = factory();
  } else if (typeof define === "function" && define.amd) {
    define([], factory);
  } else {
    root.ol = factory();
  }
}(this, function () {
  var OPENLAYERS = {};
  var goog = this.goog = {};
this.CLOSURE_NO_DEPS = true;
...
```

Usually `this` represents the `window`. In the bundled version after AoT compilation, `this` is `undefined` when the js file is parsed and thus an error is thrown => `Uncaught SyntaxError: Unexpected identifier`

Steps to reproduce:

```
npm install -g ionic cordova
ionic start someName --v2
cd someName 
npm install openlayers --save
npm install @types/openlayers --save
```
- In src/declarations.d.ts add `declare module 'openlayers';`
- In a component (e.g. src/pages/home/home.ts), add `import ol from 'openlayers';`
- call something like `ol.extent.createEmpty()` in the components constructor (unused imports are not bundled)

`ionic serve`

=> empty page - parse error in main.js

**Comment by Gussy** [comment]
I'm running into this issue as well.

The current work-around is to include `ol.js` with a script tag on `index.html`, rather than including it in any js/ts files (which would trigger it's inclusion in the AoT compilation).

**Comment by cvenzin** [comment]
Ionic updated their build script to use Webpack 2 instead of Rollup. Works now like a charm.
