### ISSUE TITLE
How to handle 4xx responses in Openlayers 3

### ISSUE THREAD

**Issue by subbuj9** [openlayers/ol3#6024]
We are using OSM map using Openlayers 3 API. We provided authentication by added in header and same received to tile server and using 3rd party labrary(OPENIDC) validating the token and if fails openidc sends 401 response to client.
How to handle this response in Openlayers 3.

Request in Openlayer3
========
ol.source.TileImage.defaultTileLoadFunction = function(imageTile, src)
 {
  var client = new XMLHttpRequest();
    client.open('GET', src);
      client.setRequestHeader('Authorization', 'Bearer mytoken123');
    client.setRequestHeader('From', 'test');
    client.onload = function () {
        var data = 'data:image/png;base64,' + btoa(unescape(encodeURIComponent(this.responseText)));
        imageTile.getImage().src = data;
    };
    client.send();
};

**Comment by ahocevar** [comment]
Note that the API has no `ol.source.TileImage.defaultTileLoadFunction`. You should be configuring the `tileLoadFunction` of your layer source instead.

For error handling, just configure a `client.onerror` handler for your `XMLHttpRequest`. You can then set `imageTile.getImage().src` to an alternative `src`, e.g. an error or blank image. If you don't, the tile will remain in `'loading'` state, which also isn't a problem.
