### ISSUE TITLE
draw circle broken when freehand enabled

### ISSUE THREAD

**Issue by craigsnyders** [openlayers/ol3#6029]
When the new freehand mode is enabled, it is no longer possible to draw a circle by performing two individual clicks, as was possible in 3.18. For example:
1. click once to place the centre
2. click once to place the radius

Without freehand mode (**working**): https://jsfiddle.net/kuhrmhae/
With freehand mode (**broken**): https://jsfiddle.net/4advhud2/2/

In the second fiddle, it is only possible to complete the circle by dragging the mouse.  Performing a single click does nothing.

I guess this happened as a result of https://github.com/openlayers/ol3/pull/5970 but have not checked.

**Comment by ahocevar** [comment]
You are right, the current behavior in freehand mode is unexpected. I created #6067 to fix it.

**Comment by tschaub** [comment]
> When the new freehand mode is enabled, it is no longer possible to draw a circle by performing two individual clicks, as was possible in 3.18.

In 3.18, when the draw interaction was in freehand mode, it was not possible to draw a circle.  See http://openlayers.org/en/v3.18.0/examples/draw-features.html.  If you hold `Shift` in that example, freehand mode is enabled.  And you cannot draw a circle in that example while in freehand mode (clicks do nothing and dragging creates a zoom box).

@ahocevar's fix in #6067 looks good to me.  But I wanted everybody to be clear that in freehand mode, you draw by dragging (not with two individual clicks).  So to draw a circle you drag.  This part was working in 3.19.0.  The part that was broken was that if you clicked without dragging, drawing would start but not finish.
