### ISSUE TITLE
Weird behavior on mouse wheel zooming with magic mouse 

### ISSUE THREAD

**Issue by cs09g** [openlayers/ol3#6030]
1. Put two fingers on magic mouse
2. Drag map -- dragging work is fine
3. One of the fingers up and start scroll ( one is on the mouse, the other one is scrolling the map)
4. Drag map again -- it works with changing resolutions
5. All fingers up and back to the step 1, 2 -- fine again.

I don't know why the wheel sensitivity became so high after step 3. 
When dragging the map, my fingers may move a little ahead and back on the mouse but it is the same when step 1, 2.

**Comment by ahocevar** [comment]
Looks like step 4 triggers the browser's zoom. But since I don't have a magic mouse and don't even know what it is, I cannot help you with this issue.

**Comment by cs09g** [comment]
magic mouse is apple's mouse. it has only one click button and has touch scroll function. Try it if you can, you will see the problem. it seems it holds some event at the step 3, so it does work two events at the same time.

**Comment by nkoren** [comment]
Replicated. Also note that this problem occurs when doing two-fingered scrolling on the Mac's trackpad. The problem is that both the magic mouse and the trackpad can send dozens of `wheel` events to openLayers, each of which are treated as a zoom. This over-sensitivity makes openLayers essentially useless on Apple hardware, so I'm surprised it's not more of a burning issue!

We're currently in the midst of fixing this by patching OL in our application, intercepting wheel events and doing a debounce. The current code which seems to work pretty well is as follows:

```javascript
function customZoom(map) {

  let _zoomInProgress = false;
  let _currentDeltaY = 0;
  let _timeoutInterval = 500;
  let lastTime;

  const _panAndZoom = function(map, event, coordinates, lastTime){
    let diff = event.timeStamp - lastTime;
    if (diff > 1.5*_timeoutInterval || diff === 0) {
      // Has been too long since the last wheel event, so this is a new zoom
      _zoomInProgress = false;
    }

    if (!_zoomInProgress) {
      if (event.deltaY) {
        // starting a new zoom
        _zoomInProgress = true;
        _currentDeltaY = event.deltaY;
        return event.timeStamp;
      } else {
        // spurious wheel signal
        return lastTime;
      }
    }

    if (diff < _timeoutInterval || Math.abs(_currentDeltaY) < 4) {
      // Cache the accumulated deltaY
      _currentDeltaY += event.deltaY;
      return lastTime;
    } else {
      let view = map.getView();
      let zoomingIn = _currentDeltaY > 0;
      ol.interaction.Interaction.zoomByDelta(map, view, zoomingIn ? -1 : 1, coordinates, _timeoutInterval / 2);
      _currentDeltaY = 0;
      return event.timeStamp;
    }
  };

  map.on('wheel', function(e){
    e.preventDefault();
    lastTime = _panAndZoom(e.map, e.originalEvent, e.coordinate, lastTime || e.originalEvent.timeStamp);
  });
}
```

**Comment by nkoren** [comment]
And just in case anyone is wondering what this looks like, here's a screen capture. In this case, I'm making the smallest-possible flicks of the scroll "wheel", which on Google maps would zoom 1 or 2 levels. Here you can see it's totally out of control:

![nov-01-2016 12-56-08](https://cloud.githubusercontent.com/assets/1158752/19890465/be771c2a-a032-11e6-9d9b-8ecc1e221132.gif)

**Comment by tschaub** [comment]
I agree that this behavior is severely broken.

**Comment by cs09g** [comment]
@nkoren Thank you for the reference!

**Comment by tschaub** [comment]
View animation is being completely reworked in #6079.  After this change is in, it will be easier to control animated zooming.

**Comment by tschaub** [comment]
Now that the new animation work is in, I'm starting to rework how we do scroll-zoom with trackpads.

**Comment by tschaub** [comment]
See #6113 (and the [hosted examples](http://tschaub.net/ol3/scroll-zoom/examples/simple.html)).  Please leave any comments on [that ticket](https://github.com/openlayers/ol3/pull/6113).
