### ISSUE TITLE
BingMaps missing HiDPI setting

### ISSUE THREAD

**Issue by achimha** [openlayers/ol3#6031]
Bing Maps added support for HiDPI/Retina/Hi-PPI maps in 2015:

https://blogs.bing.com/maps/2015/02/12/high-ppi-maps-now-available-in-the-bing-maps-ajax-control

There currently seems to be no way to set the flag in `ol.source.BingMaps`. Will there be support for this?

**Comment by bartvde** [comment]
@achimha can you check if #6077 does what you would expect?

**Comment by achimha** [comment]
Thanks, that's great! What is the easiest way to get a OL3 JavaScript bundle with the PR? I am not familiar with the build system.

**Comment by bartvde** [comment]
If you can send me an e-mail at bartvde [at] boundlessgeo [dot] com I'll send you one.

**Comment by achimha** [comment]
Thanks a lot @bartvde, it works beautifully!
