### ISSUE TITLE
After update to v3.19.0: updating text style stroke color has no effect

### ISSUE THREAD

**Issue by GitHubSCM** [openlayers/ol3#6033]
Hello,

first i want to thank you for the good work. In the application I use Openlayers for I've got a functionality to change the background color of the geometry viewer (which uses Openlayers). Changing the background color triggers an update of the colors in the involved caches. It looks like this:

``` javascript
    for (var i = 0; i < strokeKeys.length; i++) {
      var options = this.strokeCache[strokeKeys[i]];
      var contrastColorRgb = ...
      options.stroke.setColor(contrastColorRgb);
    }
```

After I updated from v3.15.1 to v3.19.0 changing the text style stroke colors (maybe others too) do not update in the viewer.

**Comment by ahocevar** [comment]
Can you provide a JSFiddle with your code so we have more context to look into this? Thanks.

**Comment by GitHubSCM** [comment]
When you click on the map the polygon and text colors change (or as in v3.19.0 only the polygon color changes, the text color does not change):

[using v3.15.1](https://jsfiddle.net/JsFiddleSCM/93aa6h25/89/)
[using v.3.19.0](https://jsfiddle.net/JsFiddleSCM/f4s4cahh/1/)

Somehow there s still a difference in behavior between my code and the v3.15.1 fiddle, In my code I use `textStrokeStyle.setColor(color1)` and not `textStyle.setFill(new ol.style.Stroke({ color: color1 }))`.

**Comment by ChouGary** [comment]
https://jsfiddle.net/f4s4cahh/3/
textStyle.setFill(new **ol.style.Fill**({ color: color1 }))
textStyle.setStroke(new ol.style.Stroke({ color: 'red' }))

**Comment by ahocevar** [comment]
You were mixing fill and stroke for the text. ol.style.Text takes a fill for the text, and a stroke for the halo. I updated your fiddle: https://jsfiddle.net/f4s4cahh/4/.
