### ISSUE TITLE
Lazy creation of KML default style breaks KML parsing 

### ISSUE THREAD

**Issue by oterral** [openlayers/ol3#6037]
I have a lot of errors since this PR:https://github.com/openlayers/ol3/commit/3630a043fe852f058c364d430ae7d9869c702648

1st reason:
The problem is  if we don't have these styles a lot of variables are undefined and makes the KML parsing totally different than before or broke it (no href for an IconStyle for example (fixed since), DEFAULT_TEXT_STYLE_.getScale is undefined ).

If we want a behavior like Google Earth does, these default styles are necessary. Since we don't use the defaultStyle property (and I don't think it's possible) to set them.

2nd reason:

If you create an `ol.format.KML()`  without `defaultStyle` then you create an `ol.format.KML()` with a `defaultStyle`. The default variable are set and so the KML parsing is again totally different. And I don't think a developer wants that.

I would like to revert this PR if you are agree?

**Comment by oterral** [comment]
Or maybe we can execute the ol.format.KML.createStyleDefaults_()  evry time in the constructor.

**Comment by oterral** [comment]
or only if the variable are not yet created.

**Comment by ahocevar** [comment]
> Or maybe we can execute the ol.format.KML.createStyleDefaults_() every time in the constructor.
> or only if the variables are not yet created.

It is done this way already. See https://github.com/openlayers/ol3/blob/640307d8f16978cbc9df99db6bcb505f72719342/src/ol/format/kml.js#L65.

Can you provide a JSFiddle that shows your problem?

**Comment by oterral** [comment]
The problem is these variables are not created if a defaultStyle is provided.

**Comment by oterral** [comment]
Here it's worjking: https://jsfiddle.net/api/post/library/pure/

and with a default style everything is broken because `ol.format.KML.DEFAULT_IMAGE_STYLE_SIZE_` is undefined : 
https://jsfiddle.net/p4buhfo1/

It's just one example on many others.

**Comment by ahocevar** [comment]
We're not going to revert 3630a04, but we accept a pull request that changes the constructor to always create the default styles when `ol.format.KML.DEFAULT_STYLE_ARRAY_` is undefined.

**Comment by oterral** [comment]
Yes a revert is useless. Thx @ahocevar
