### ISSUE TITLE
Use webgl renderer and canvas renderer both

### ISSUE THREAD

**Issue by EladIsraeli** [openlayers/ol3#6050]
There is any way of using webgl renderer to render  the points as it working now , and in the same time use the canvas renderer to render circles and lines ? 

The reason why i need this functionallity is because i want to use webgl to high performance and also be able to draw circles one or two and couple of lines ...

**Comment by ahocevar** [comment]
You should be able to render > 50000 points fine with the canvas renderer. And much more when you use `ol.source.ImageVector`. But there is no way to mix renderers.

**Comment by EladIsraeli** [comment]
If i use webgl i can only render 12k points , if i use canvas i can render just 2-4k points..
 @ahocevar

**Comment by ahocevar** [comment]
@EladIsraeli These are very low numbers. There is very likely room for optimisation elsewhere in your application.

**Comment by EladIsraeli** [comment]
@ahocevar 

Ive tried to use the ol.source.ImageVector
But i suffer from some problems can you show me a little example of how to implements it using imagevector ?

**Comment by ThomasG77** [comment]
Look at the official workshop http://openlayers.org/workshop/en/layers/imagevector.html and the official sample http://openlayers.org/en/v3.19.1/examples/image-vector-layer.html

**Comment by EladIsraeli** [comment]
Well after have a demo version of ImageVector it seems to still work bad on high amount of points i mean it just render about 20-30k points fine(and fine mean fine), but when the number increased its lack of low fps and no smoothness that i would like to have. 

Maybe someone can show me a really standard example to represent > 50k points on the map that will be smooth ? 

Tried imagevector , webgl usage still no perfromances changed , what would i do ? 

@ThomasG77  
@ahocevar

**Comment by ahocevar** [comment]
I'm pretty sure you are using an inefficient style function @EladIsraeli. Browse the examples and look at the style functions there - it is always a good idea to reuse style objects.
