### ISSUE TITLE
ol.interaction.Modify does not work well with map rotation

### ISSUE THREAD

**Issue by Schinkentanz** [openlayers/ol3#6051]
Hey there, we have an issue regarding the modify interaction. After drawing some ol.geom.Point(s) on the map, we wanted them to be modifiable via user interaction. The problem is, that when the map has a specific rotation, the size of the created box  [src/ol/interaction/modify.js#L707](https://github.com/openlayers/ol3/blob/e853f1ed2a7fdb64ff32924e759bd619320ed016/src/ol/interaction/modify.js#L707) varies: http://d.pr/i/NPsV (used rotation e.g. ```map.getView().setRotation(0.78)```).

We figured out that if the box is created from 4 points instead of only two, the box size is closer to the desired state. This box also varies in size and the highlighting / detection of the modifiable point does not match yet: http://d.pr/i/mPSr 

```javascript
  var upperLeft = map.getCoordinateFromPixel(
    [pixel[0] - this.pixelTolerance_, pixel[1] + this.pixelTolerance_]);
  var lowerLeft = map.getCoordinateFromPixel(
    [pixel[0] - this.pixelTolerance_, pixel[1] - this.pixelTolerance_]);
  var upperRight = map.getCoordinateFromPixel(
    [pixel[0] + this.pixelTolerance_, pixel[1] + this.pixelTolerance_]);
  var lowerRight = map.getCoordinateFromPixel(
    [pixel[0] + this.pixelTolerance_, pixel[1] - this.pixelTolerance_]);

  var box = ol.extent.boundingExtent([upperLeft, upperRight, lowerRight, lowerLeft]);
```

This behaviour can be tested with every modify example from http://openlayers.org/en/latest/examples/?q=modify (make sure the rotation is set to (e.g) 0.78).

**Comment by ahocevar** [comment]
#6064 implement the suggestion from above, though with less code.
