### ISSUE TITLE
ol.source.ImageWMS.getGetFeatureInfoUrl just return one feature fid

### ISSUE THREAD

**Issue by bsdfzzzy** [openlayers/ol3#6056]
http://openlayers.org/en/latest/examples/getfeatureinfo-image.html

At the above site, the getGetFeatureInfoUrl API return many features.But mine just return one fid.Is there anything need to fix?Should I focus on geoserver (.shp) or ArcGIS which is the software to create .shp?

**Comment by bartvde** [comment]
Normally only with overlapping features GetFeatureInfo can return multiple features. GeoServer has a vendor option called buffer to increase the search area for features though, but this is vendor-specific. I advise you to read the WMS specification, this is not really an OpenLayers question / issue.

**Comment by bartvde** [comment]
Or are you saying, wherever you click you will get the same feature back? Then this is more likely an issue with your WMS server instead.

**Comment by bsdfzzzy** [comment]
Yep, that's not really an OpenLayers question.
I'll read the WMS specification later.
Thanks!
