### ISSUE TITLE
Using ol-debug.js while using Webpack es2015 modules

### ISSUE THREAD

**Issue by thomasgwatson** [openlayers/ol3#6060]
In short, there isn't a clear way to use the debug (not minified) version of Openlayers when using Webpack/es2015 modules (import/from).

Posting this here in case others are facing the same difficulty.

http://stackoverflow.com/questions/40367623/load-debug-version-of-pre-built-module-via-npm-webpack

**Comment by Gussy** [comment]
This is probably related to #6021 also. Upstream support for ES2015 modules would be great 👍

**Comment by cvenzin** [comment]
It's not directly related  to #6021 but an other issue that I have aswell.

**Comment by aAXEe** [comment]
I don't think this is a openlayers bug.
At least I do not know a mechanism for a module to specify a different js file for release/debug. So all openlayers can do is to provide one version.

Webpack has configuration options for replacing a module into a different path: https://webpack.github.io/docs/configuration.html#resolve-alias

This resolves the openlayers import to use the debug version:

```
webpackConfig.resolve.alias: {
  openlayers: 'openlayers/dist/ol-debug.js'
}
```

See my [stackoverflow response](http://stackoverflow.com/a/40553801/5456507) for details on how to switch the debug/release depending on the environment.

**Comment by thomasgwatson** [comment]
Thanks @aAXEe
