### ISSUE TITLE
Problems with DragPan interaction

### ISSUE THREAD

**Issue by 8Duke8** [openlayers/ol3#6062]
I would like to run a code while a map is dragging, I found out that there is DragPan interaction. See my code below, I guess that I am doing something wrong. Could you please bring some light into it?

   ```
 var dragPanInteraction = new ol.interaction.DragPan({
      handleDragEvent: function() {
        // this code is not run during map dragging
      }
    });

    // this code works, but I don't want to handle it that way
    /*dragPanInteraction.handleDragEvent_ = (event) => {
...
    };*/
    map.addInteraction(dragPanInteraction);
```

**Comment by ahocevar** [comment]
Instead of subclassing `ol.interaction.DragPan`, which is not supported, you will probably want to configure the interaction's `condition` for custom behavior.
