### ISSUE TITLE
PinchRotate does not trigger a change rotation event

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol3#6070]
It appears that `map.getView().on("change:rotation")` is not triggered

**Comment by Benjaki2** [comment]
Error is on my side. Closing issue.

**Comment by mylen** [comment]
you could explain a bit ;)

**Comment by Benjaki2** [comment]
@mylen I believe I was seeing this in with an Iphone which at least at the time only allowed a certain number of updates to the url per second or minute. I had a listener updating the URL on `change:rotation`, so the pinch rotate surpassed the limit and was more or less breaking the app.  I resolved the issue with a `debouncer`.
