### ISSUE TITLE
The DOM render has been removed Assertion being fired

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol3#6071]
I imagine this in response to [#5815](https://github.com/openlayers/ol3/pull/5815)

**Comment by ahocevar** [comment]
Can you provide some context? There is no DOM renderer any more.

**Comment by bartvde** [comment]
I assume he's talking about the warning here?

https://github.com/openlayers/ol3/blob/master/src/ol/map.js#L1466

Just remove renderer: 'dom' from your map config @Benjaki2 to get rid of the warning

**Comment by Benjaki2** [comment]
That did the trick @bartvde. Thanks guys.
