### ISSUE TITLE
map.getView().setCenter() does not works

### ISSUE THREAD

**Issue by sombriks** [openlayers/ol3#6080]
see https://jsfiddle.net/m7uvsoef/3/

also tested against https://github.com/openlayers/ol3/releases/download/v3.19.1/v3.19.1-dist.zip same result.

any guidance on why it does not updates the map?

**Comment by ThomasG77** [comment]
Read the quickstart http://openlayers.org/en/latest/doc/quickstart.html to see you missed the `center: ol.proj.fromLonLat([37.41, 8.82]),` in the `ol.View`

The policy for users questions is to ask on StackOverflow http://stackoverflow.com/questions/tagged/openlayers-3 not here plz.

Moreover, you should also look the [doc part](http://openlayers.org/en/latest/doc/) of the official website

**Comment by sombriks** [comment]
Just found the **fromLonLat** a few instants ago and was on my way to close the issue. Thanks!
