### ISSUE TITLE
Unable to make small map rotation

### ISSUE THREAD

**Issue by jakubbican** [openlayers/ol3#6084]
We need to enable small map view rotations - now, when user rotates for just few degrees (less than 0.09 RAD), the map returns to zero rotation. When it is rotated more, then even the small rotation is possible.

It seems like that the rotation is snapping to 0 degrees with some tolerance.

We need to turn off this snapping.

(It is easily reproducible on standard examples.)

**Comment by ahocevar** [comment]
Just configure your `ol.View` instance with `constrainRotation: false`.

**Comment by jakubbican** [comment]
Works great. Thanks!
