### ISSUE TITLE
geodesicArea giving area as 0.

### ISSUE THREAD

**Issue by ni010go** [openlayers/ol3#6085]
I am using ol.Sphere(6378137) geodesicArea to calculate area of Polygon.
Polygon originally in epsg:3857, that is transformed into epsg:4326 and this polygon is passed into above api to calculate area. Problem is for some polygons it is giving Area as 0 which is actually non-zero. But if ol.geom.Polygon's getArea is used, it comes as a non-zero.

We are using geodesicArea as adviced "http://openlayers.org/en/latest/examples/measure.html" to work properly across projections.

Please advice.

Thanks in advance.

**Comment by ahocevar** [comment]
Can you share an example code snippet where geodesicArea returns an area of 0?

**Comment by ni010go** [comment]
function _getPolygonMeasurement(polygon, mapProjection, targetUnit, targetAreaUnit) {
            var coords, perimeter = 0, geom, area = 0;
                coords = angular.copy(polygon.getCoordinates());

                if (coords) {
                    perimeter = _getPolygonPerimeter(coords, mapProjection);
                    //geodesic area
                    geom = (polygon.clone().transform(mapProjection, 'EPSG:4326'));
                    if (geom) {
                        coords = geom.getLinearRing(0).getCoordinates();
                        area = _getPolygonArea(coords);
                    }
                }
            }

            

    var _getPolygonArea = function (coords) {
            var area = Math.abs(wgs84Sphere.geodesicArea(coords));
            return area;
        };

		
       var wgs84Sphere = new ol.Sphere(6378137);

**Comment by ni010go** [comment]
Example of coordinates on which it return area as 0:
coord1- [3394.775390152444, 89.99999999979232]
coord2- [3170.654296433642, 89.99999992661606]
coord3- [3660.6445307404347, 89.99999995871653]
coord4- [3394.775390152444, 89.99999999979232]

**Comment by bill-chadwick** [comment]
Those coords look very suspicious - the Xs vary but the Ys are nearly all the same. 
Are they supposed to be WGS84 / EPSG:4326 or EPSG:3857 ? If they are 4326 then they have wrapped around the world several times and are all more or less at the North pole !
Either way, the coords are pretty nearly in a straight line.

**Comment by ni010go** [comment]
I am receiving same result for below rectangular area on the map as well:
[cid:image001.png@01D239EF.85DC73F0]

**Comment by ahocevar** [comment]
@ni010go Please don't reply by e-mail when attaching images. And please provide the coordinates for the geometry in the image you meant to post.

**Comment by ni010go** [comment]
Example of coordinates for which area is coming as 0 are:
coordinates of polygon -3761.7187494763643,90,-3779.296874473918,90,281.24999996084966,90,1722.6562497602042,90,-3761.7187494763643,90


coordinates of polygon near Zambia in Africa 2478.5156246549877,-89.99999996591987,2337.890624674563,-89.99999999999706,2900.390624596262,-89.99999999998997,2478.5156246549877,-89.99999996591987

I am not able to post images here.

**Comment by ni010go** [comment]
![area01](https://cloud.githubusercontent.com/assets/16013408/20295183/7e606d24-ab29-11e6-9643-304eeb1c3d21.png)
![area02](https://cloud.githubusercontent.com/assets/16013408/20295184/7e673e06-ab29-11e6-9434-623a96c05e91.png)

**Comment by ahocevar** [comment]
Sorry, but both polygons you posted here actually do have an area of 0, because their y coordinates are all the same.
