### ISSUE TITLE
view.setCenter wrong go to wrong position

### ISSUE THREAD

**Issue by giordanoturrini** [openlayers/ol3#6086]
Hello and thanks anticipated to all. I have problem with setCenter. The code below:
function testcall() {
            var lat = document.getElementById('MainContent_txtLat').value;
            var lon = document.getElementById('MainContent_txtLng').value;

            var position = ol.proj.fromLonLat([lon, lat]);
            view.setCenter(position);
        };
must be move without recharge page the OpenLayer map on coordinated extract from textbox. The longitude run ok but latitude is wrong. The map center move in wrong position.
Someone have idea?
Thanks 
Giordano

**Comment by tsauerwein** [comment]
Make sure to call [fromLonLat](http://openlayers.org/en/master/apidoc/ol.proj.html#.fromLonLat) with numbers and not strings:

```
var lat = parseFloat(document.getElementById('MainContent_txtLat').value);
var lon = parseFloat(document.getElementById('MainContent_txtLng').value);
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat
