### ISSUE TITLE
Weird zoom animation

### ISSUE THREAD

**Issue by tchandelle** [openlayers/ol3#6096]
When zooming in or out while moving cursor, the animation looks weird, I don't know how to describe it :

![zoom](https://cloud.githubusercontent.com/assets/19923657/20137990/1817e7c2-a67e-11e6-95bc-f61e919af694.gif)

It looks like it's caused by #6079, especially commit 3acfe79, @tschaub ?

**Comment by tschaub** [comment]
@tchandelle - can you try to describe what you are doing in the graphic above?  Are you using a trackpad or mousewheel to zoom in?  Are you double-clicking?  Are you trying to drag the map while it is zooming?

**Comment by tchandelle** [comment]
I just zoom in with the mousewheel. While the mousewheel is still going up, I move the cursor, without pressing any buttons.

(the pan I do in the middle of the gif, from Canada to Europe, is not part of the problem)

**Comment by bjornharrtell** [comment]
Can reproduce. To me the issue seems to be that cursor movement during zoom animation will cause panning animation out of sync with the zoom. Looks like it happens late or after the zoom animation based on cursor movement during the zoom animation.

**Comment by tschaub** [comment]
See #6101 for a potential fix (I'll confirm with a mouse that has a wheel later).

I've gotten a start on reworking the wheel/scroll zooming entirely.  So #6101 is an interim solution.
