### ISSUE TITLE
Tiles fail to load at the end of a zoom animation

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#6102]
As reported in https://github.com/openlayers/ol3/pull/6079#issuecomment-259140978.  Steps to reproduce:

 * open the simple.html example
 * click the zoom in button many times
 * see that new tiles do not load at the end of the animation

![zoom](https://cloud.githubusercontent.com/assets/41094/20182639/ab2a5f1c-a71f-11e6-9eea-9987b55fb434.gif)

**Comment by ahocevar** [comment]
Unfortunatels #6103 only partially fixed the issue. When the zoom button is repeatedly pressed very quickly while a zoom animation is running, tiles still do not load at the end of the animation. In the gif below, I very quickly pressed the zoom-in button 4 times:
![nov-11-2016 13-01-32](https://cloud.githubusercontent.com/assets/211514/20214570/579cc74a-a80f-11e6-98b0-e5c1416a6508.gif)

**Comment by tschaub** [comment]
I'll take a look.

When animations are cancelled, we remove the animation hint on the view but don't make any changes that would trigger another render.  This may not be the root of the problem you are seeing, but I think this will need addressing as well (e.g. by calling `view.changed()` when animations are cancelled).

**Comment by tschaub** [comment]
Hmm.  I'm not able to reproduce this.  Still trying.

**Comment by tschaub** [comment]
Though I believe what you're seeing, I haven't been able to reproduce this with a variety of animation durations, network throttling, and clicking speeds.

I think it is not related, but I opened #6107 to tighten things up with cancelling animations.

**Comment by tschaub** [comment]
Closing again based on https://github.com/openlayers/ol3/pull/6107#pullrequestreview-8301945.  Please reopen if this can be reproduced.
