### ISSUE TITLE
Style Image rotation is anti-clockwise on WebGL

### ISSUE THREAD

**Issue by tchandelle** [openlayers/ol3#6123]
I noticed that [regularshape-canvas.png](https://github.com/openlayers/ol3/blob/8f6e07bfb84fe95bc196b17e7277c5c96888d03b/test_rendering/spec/ol/style/expected/regularshape-canvas.png) and [regularshape-webgl.png](https://github.com/openlayers/ol3/blob/8f6e07bfb84fe95bc196b17e7277c5c96888d03b/test_rendering/spec/ol/style/expected/regularshape-webgl.png) are different. 

But they both test, among other thing, the `rotation` option for `ol.style.RegularShape`, which is suppose to be clockwise.

The correction seems so easy (<strike>6648c82f8f301c7387fedaedaa4cdca8c9f08ad3</strike> 1ce2cd605ae8ae39a1c1a78a113e5372e5050eff) and the differences are so obvious that I wonder if there is a technical reason for that that I don't think about.

**Comment by asdawn** [comment]
I'm not familiar with ol's source, even js, sorry. 
But if the only problem is the rotation direction, clockwise or anticlockwise,  and you got the right position, that should be ok.  I think the equation are right:
clockwise x degree == anticlockwise -x degree, so x degree should be replaced by -x degree
sin(x)-->sin(-x) equals -sin(x),
cos(x)-->cos(-x) equal cos(x),
however,  the code in gberaudo's comment might be more readable and safe.
