### ISSUE TITLE
ol.style.Icon does not render when using the color property

### ISSUE THREAD

**Issue by crisley2016** [openlayers/ol3#6137]
If I run the IconColor example directly from https://openlayers.org/en/latest/examples/icon-color.html the three icons are shown on the map (Version 3.19.1).

If I click the "Edit" button and run the code in the linked JSFiddle, the three icons are not rendered onto the map.  Commenting out the 'color' property results in the icons being rendered (and they are filled with white).  I see the same issue when I use the 'color' property in my application.

**Comment by ahocevar** [comment]
When loading icons from a different origin, the server needs to support CORS and you need to configure the `crossOrigin` option (usually with `'anonymous'` as value) on the `ol.style.Icon` object. See https://jsfiddle.net/3n7mxxkL/.
