### ISSUE TITLE
Handling WMS exceptions in openlayers3

### ISSUE THREAD

**Issue by mfarook** [openlayers/ol3#6141]
I am loading a wms service reading from json.The WMS gets added successfully. I have no idea how to handle exceptions if there is any WMS request failure.I am new to openlayers.This is my function where am adding WMS.

`function (node) {
                if (!('name' in node)) {
                    return null;
                }
                var type = node['name'];
                if (type in layerCache) {
                    return layerCache[type];
                }
                var source;
                source = new ol.source.TileWMS({
                    url: node['source']['url'],
                    params: node['source']['params']
                });
                source.on('tileloadstart', function() {
                    progress.addLoading();
                });

                source.on('tileloadend', function() {
                    progress.addLoaded();
                });
                source.on('tileloaderror', function() {
                    progress.addLoaded();
                });
                var layer = new ol.layer.Tile({
                    source: source
                });
                layerCache[type] = layer;
                return layer;

            }`

**Comment by bartvde** [comment]
Please don't cross-post http://stackoverflow.com/questions/40653380/handling-wms-exceptions-in-openlayers3
