### ISSUE TITLE
VERSION and other constants are missing?

### ISSUE THREAD

**Issue by ablakey** [openlayers/ol3#6142]
I noticed that  `ol.VERSION` and `ol.geom.GeometryType` are both missing from my application. Before digging into Webpack to see what I may be doing wrong, I tested it out on Openlayers' demo pages. They seem to be missing there too.

Can anyone confirm that these things are supposed to be present and that they too can't find them anymore in 3.19.1 ?

**Comment by megawac** [comment]
Looks like some properties are not being protected and as a result getting mangled by the closure compiler

https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#protected

https://github.com/openlayers/ol3/blob/bdced571625ef2493377ba661fc48b8c0afa0e12/src/ol/geom/geometry.js#L17

**Comment by TDesjardins** [comment]
AFAICT there is unfortunately not a version flag ol.VERSION in the API. See https://github.com/openlayers/ol3/pull/2451

**Comment by ablakey** [comment]
Ah okay. Luckily I don't rely on it. Unluckily I tried to use it now as an example. =)

`ol.geom.GeometryType` is missing though, which clearly looks to be part of the API.

**Comment by ahocevar** [comment]
Type definitions are not exported. Use the documented values in your application instead.

**Comment by ablakey** [comment]
`ol.geom.GeometryType` looks official as far as the documentation shows. What am I supposed to look for to know what things in the documentation are not actually usable?

**Comment by bartvde** [comment]
You should simply use ```Point```, ```LineString``` etc. so the string values

**Comment by ablakey** [comment]
I understand how I can do this. I don't understand how to read the documentation and know that those elements don't actually exist in the dist version.

**Comment by probins** [comment]
http://openlayers.org/en/master/apidoc/ defines the api. `ol.geom.GeometryType` is a type definition, not included in this definition. Typedefs are only used for compiler optimization, and are not not useful in apps.

**Comment by ablakey** [comment]
Okay so the part that was non obvious is that type definitions are not included in the API. I must have missed the documentation stating that somewhere.

Thanks.

**Comment by probins** [comment]
IOW, you might do `feature.getGeometry().getType()` in your app, which will return 'Point' or whatever. You don't ever need to refer to `ol.geom.GeometryType` in your app.

**Comment by ahocevar** [comment]
See https://openlayers.org/en/latest/apidoc/ol.geom.html#.GeometryType - there you see a prose description with the values that can be used.
