### ISSUE TITLE
Two WMTS services, different levels of the interval,one of service still load it's max level

### ISSUE THREAD

**Issue by jacobking** [openlayers/ol3#6145]
as the title,when I use one service ,just call it AS,set it's matrixIds 15 to 16,and another service just call it BS set 17 to 18,and set the zoom to 17,the AS still load it's max matrixIds of 16,when I zoom the map to 18,the AS of level 16 layer still there and didn't destory.WHY&How to fix it?
the demo show link is[http://sandbox.runjs.cn/show/gjdqroo9](http://sandbox.runjs.cn/show/gjdqroo9),
the demo source link is[http://runjs.cn/detail/gjdqroo9](http://runjs.cn/detail/gjdqroo9)
Look forward to your reply.

**Comment by jacobking** [comment]
The ol2 has a param of removeBackBufferDelay to set layer's remove,if ol3 has this options?
link [http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Layer/Grid-js.html#OpenLayers.Layer.Grid.removeBackBufferDelay](http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Layer/Grid-js.html#OpenLayers.Layer.Grid.removeBackBufferDelay)

**Comment by ahocevar** [comment]
This is intended behaviour. What you have configured is just the zoom levels of the source, not what gets displayed. If you want that, you have to configure `minResolution` and `maxResolution` on the layer. See https://openlayers.org/en/latest/apidoc/ol.layer.Tile.html.

**Comment by jacobking** [comment]
@ahocevar well,minResolution and maxResolution didn't work.bug?,you can see in here [http://runjs.cn/detail/gjdqroo9](http://runjs.cn/detail/gjdqroo9)

**Comment by ahocevar** [comment]
I don't find the code on the page you have linked. Note that you need to set these on the layer, not the source.

**Comment by jacobking** [comment]
@ahocevar Thanks for your reply ,here is the jsfiddle version [https://jsfiddle.net/56Lc2749/2/](https://jsfiddle.net/56Lc2749/2/)
