### ISSUE TITLE
Set GeometryLayout correctly when reading GPX

### ISSUE THREAD

**Issue by romanzoller** [openlayers/ol3#6148]
The reader of `ol.format.GPX` currently always creates geometry with layout `ol.geom.GeometryLayout.XYZM`.

I am not sure if Z/M are ever used in the GPX parser, but I think when reading a GPX file that only has lat/lon trackpoints, the layout of the imported geometry should be `ol.geom.GeometryLayout.XY`.

**Comment by bartvde** [comment]
Are you up for a pull request?

**Comment by bartvde** [comment]
Elevation and time (Z, M) seem to be used conditionally right now: https://github.com/openlayers/ol3/blob/master/src/ol/format/gpx.js#L80:L91

**Comment by romanzoller** [comment]
Ah, yes, I hadn't seen that part yet, thanks. Yes, I can look into it.

So the idea would be:

- use `ol.geom.GeometryLayout.XY` by default
- use `ol.geom.GeometryLayout.XYZ` if there is at least one `ele` attribute
- use `ol.geom.GeometryLayout.XYM` if there is at least one `time` attribute
- use `ol.geom.GeometryLayout.XYZM` if there are both `ele` and `time`

Correct?

**Comment by bartvde** [comment]
yes that would make sense to me
