### ISSUE TITLE
read geojson file with crs definition: different behaviour ol3.18.2 versus ol3.19.1

### ISSUE THREAD

**Issue by veetrp** [openlayers/ol3#6149]
Hi good people, I came across the following. I have a simple geojson test file with and without a "crs" definition (crs btw is ED50 = EPSG4230):
file A with crs:
```
{	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::4230" } },
	"features": [
		{ "type": "Feature", "properties": { "Country": "NL", "Quad": "F" }, "geometry":
			{ "type": "MultiPolygon", "coordinates":
				[[[[ 4, 54 ],[ 5, 54 ],[ 5, 55 ],[ 4, 55 ],[ 4, 54 ]]]]
			}
		}
	]
}
```

file B without crs:
```
{	"type": "FeatureCollection",
	"features": [
		{ "type": "Feature", "properties": { "Country": "NL", "Quad": "F" }, "geometry":
			{ "type": "MultiPolygon", "coordinates":
				[[[[ 4, 54 ],[ 5, 54 ],[ 5, 55 ],[ 4, 55 ],[ 4, 54 ]]]]
			}
		}
	]
}
```

I read these file in with:
```
	var src = new ol.source.Vector({
		url: "./data/fileA_or_fileB.geojson",
		format: new ol.format.GeoJSON ({
			defaultDataProjection: "ed50_EPSG:4230",
			featureProjection: "webmc_EPSG:3857"
		})
	});
```
where:
```
	proj4.defs('ed50_EPSG:4230','+proj=longlat +ellps=intl +towgs84=-87,-98,-121,0,0,0,0 +no_defs');
	proj4.defs('webmc_EPSG:3857','+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs');

```

Problem/issue/observation:
With http://openlayers.org/en/v3.18.2/build/ol.js both files load and display ok.
With http://openlayers.org/en/v3.19.1/build/ol.js fileA does not load correctly (i.e. it doesn't display anything), fileB loads and displays ok.

So my workaround for now is to strip the crs from the geojson files because of each file I do know the source proj. But it made me wonder... (below a pic to make this issue more pleasing looking...)
Rgds, Reinoud

![image](https://cloud.githubusercontent.com/assets/23259176/20461218/0ac6da34-aef7-11e6-913b-ec44769e8def.png)

**Comment by bartvde** [comment]
Likely: https://github.com/openlayers/ol3/commit/4b6e907f698b63cd3daad2a6deb0b7d78c0419a9#diff-d9c5b31c4e9ededc41b2f7e3f42da5e5

is related

**Comment by bartvde** [comment]
Please note that with 3.18 and before featureProjection was not even recognised in the constructor as an option

**Comment by bartvde** [comment]
Also what does ol.proj.get('urn:ogc:def:crs:EPSG::4230')``` return for you? You might need to use something similar to the discussion in: https://github.com/openlayers/ol3/issues/4840

**Comment by veetrp** [comment]
ok. I'll check this out when I have time.

**Comment by veetrp** [comment]
ol.proj.get('urn:ogc:def:crs:EPSG::4230') returns null. Btw the string is not invented by me but created by QGIS when exporting to geojson (which doesn't mean that it is right of course).

I looked at #4840 and agree that it looks something like that. Also using proj4 as described by Andreas is probably a better way to go for me.

I guess the issue can be closed because:
1. ol3.18 doesn't care about the crs definition inside the geojson and
2. ol3.19 does, but doesn't recognise the string
This explains my observations

Tnx for the support!
