### ISSUE TITLE
ol.source.OSM and tilePixelRatio

### ISSUE THREAD

**Issue by sandman7920** [openlayers/ol3#6156]
ol.source.OSM doesn't pass tilePixelRatio in ol.source.XYZ constructor call

```javascript
ol.source.XYZ.call(this, {
    attributions: attributions,
    cacheSize: options.cacheSize,
    crossOrigin: crossOrigin,
    opaque: options.opaque !== undefined ? options.opaque : true,
    maxZoom: options.maxZoom !== undefined ? options.maxZoom : 19,
    reprojectionErrorThreshold: options.reprojectionErrorThreshold,
    tileLoadFunction: options.tileLoadFunction,
    url: url,
    wrapX: options.wrapX,
    //tilePixelRatio: options.tilePixelRatio // missing
  });
```

**Comment by ahocevar** [comment]
`ol.source.OSM` does not have a `tilePixelRatio` option. You can use `ol.source.XYZ` directly if you are using a tile source with a custom `tilePixelRatio`.

If you can point us to an OSM tile source out there which does use a different `tilePixelRatio` than 1, we might consider accepting a pull request that adds a `tilePixelRatio` option to `ol.source.OSM`.
