### ISSUE TITLE
Problem creating a map in 3.19.1: a.slice is not a function

### ISSUE THREAD

**Issue by krie0198** [openlayers/ol3#6158]
I am trying to update from 3.10.1 to 3.19.1, and I the following error when I try to create the map.

This is the stack trace:
ol.js:64 Uncaught TypeError: a.slice is not a function(…)
k.U	@	ol.js:64
k.Jo	@	ol.js:320
(anonymous function)	@	ol.js:307
requestAnimationFrame (async)		
k.render	@	ol.js:318
k.Ck	@	ol.js:318
b	@	ol.js:15
Ma.b	@	ol.js:18
Xa	@	ol.js:20
k.set	@	ol.js:21
k.H	@	ol.js:21
H	@	ol.js:309

I tried updating to each version in between 3.10 and 3.19, without changing any of my code that uses OL, and this error doesn't appear until 3.18. Did I miss an update in the way you need to create a map?

**Comment by fredj** [comment]
Can you please create a minimal jsfiddle to demonstrate the issue?

**Comment by krie0198** [comment]
I created the jsfiddle here (https://jsfiddle.net/2df83hj7/), and in doing so, I discovered a bug in my own code that ultimately caused this error. It turns out that there is a section of my code that was transforming the view center from an array to an object, and it wasn't causing an error in the older versions because of this change (https://github.com/openlayers/ol3/pull/5599/files). The way the OL code was prior to this change, my bug went unnoticed because your code handled it just fine.

My apologies for sounding a false alarm.

**Comment by boly38** [comment]
@krie0198 no way to apologies:
as openlayers 4.4 user, I was just able to reproduce the same issue...
I was able to quickly fix by reading this ticket ! so thX!  :+1: 
FYI I were using custom javascript object as "Overlay::position" instead of using "ol.proj.fromLonLat" result
