### ISSUE TITLE
How to make the feature rotate angle

### ISSUE THREAD

**Issue by lxh015** [openlayers/ol3#6162]
when draw the group of feature,I want to make the feature rotate angle.
Example：
![image](https://cloud.githubusercontent.com/assets/16249069/20552016/70141f28-b181-11e6-8b54-94426e40ec3c.png)
I has draw it,and now I want make it
![image](https://cloud.githubusercontent.com/assets/16249069/20552041/b7230442-b181-11e6-9198-f6590adba5b4.png)
rotate 45°,

Can you show me a demo?
And My English is not good,so sorry, hope you can got it. Thank you very much!

**Comment by tsauerwein** [comment]
Please ask such kind of usage question on [StackOverflow](http://stackoverflow.com/questions/tagged/openlayers-3). There are some plugins that might be interesting for you: http://viglino.github.io/ol3-ext/examples/map.interaction.transform.html https://ghettovoice.github.io/ol3-rotate-feature/

**Comment by lxh015** [comment]
thank you
