### ISSUE TITLE
Rectangle is being drawn as a triangle

### ISSUE THREAD

**Issue by stephan333** [openlayers/ol3#6163]
When I draw a rectangle (ol.geom.Polygon) with 4 vertices instead of 5, the shape is normally being closed automatically. However, if I draw two rectangles and the bottom right corner of the first rectangle (at the top) is the same as the top right corner of the second rectangle (at the bottom), the second rectangle is not closed properly, instead it is drawn as a triangle. I attached an archive that shows the problem.

[ol3-bugreport.tar.gz](https://github.com/openlayers/ol3/files/608872/ol3-bugreport.tar.gz)

**Comment by ahocevar** [comment]
Currently, when creating a polygon, you have to repeat the first coordinate as last coordinate. See #6063.
