### ISSUE TITLE
Modifying a 3D geometry replace the third coordinate of existing vertex by zero

### ISSUE THREAD

**Issue by tchandelle** [openlayers/ol3#6166]
https://jsfiddle.net/wj8oxuws/

You can test on this jsfiddle, I've added a third dimension on the red lines on the right. If you move an existing vertex, you'll see that the third coordinate is always replaced by zero.

I've already submitted a PR #6075

**Comment by marcjansen** [comment]
A valid concern. #6075 looks like a nice solution. I will hopefully review that PR soon.

**Comment by fredj** [comment]
fixed with #6075
