### ISSUE TITLE
No non-deprecated alternative for view.fit() with animation

### ISSUE THREAD

**Issue by tchandelle** [openlayers/ol3#6170]
Since `map.beforeRender()` will be deprecated in 3.20, it's not possible to correctly animate `view.fit()` without using `beforeRender`, like in this example : https://jsfiddle.net/fnsyLj34/

**Comment by tschaub** [comment]
We can add duration and easing options to fit.  If either is present, the method animates.

**Comment by tchandelle** [comment]
@tschaub : I've also added an alternative fix : #6186

**Comment by cs09g** [comment]
what if you need "[flyTo](http://openlayers.org/en/latest/examples/animation.html)" animation?

**Comment by ahocevar** [comment]
Use `ol.View#animate`, like shown in the example you linked.

**Comment by cs09g** [comment]
@ahocevar it can not be fly to with fit function. There's only duration and easing but zoom

**Comment by ahocevar** [comment]
Indeed. `ol.View.prototype.getResolutionForExtent` should be marked `@api` and modified to make `size` optional.

**Comment by cs09g** [comment]
@ahocevar I can have a look. Thanks for the quick feedback.
