### ISSUE TITLE
Icons style: wrong scale

### ISSUE THREAD

**Issue by jaforom** [openlayers/ol3#6171]
Hi,

I think the icons style has a wrong scale after version 3.18.2.

Loading this simple KML ([PruebaEscala.zip](https://github.com/openlayers/ol3/files/612989/PruebaEscala.zip), created with Google Earth) with a unique Placemark (point), the scale retrieved by OL3 is different using 3.18.2 and later versions:

- Using version 3.18.2, the scale is 1.0488088481701516
- Using versions 3.19.0 and 3.19.1, the scale is 0.55

Best regards

**Comment by jaforom** [comment]
I forgot to say that I load the features of the KML files using the ol.format.KML.readFeatures() method and then doing source.addFeature() .

Regards

**Comment by tchandelle** [comment]
Duplicate of #6044 ?

**Comment by jaforom** [comment]
Yes, I think so, sorry. Thank you very much.
