### ISSUE TITLE
how to solve the problem of rendering Point using the ol.layer.VectorTile Class

### ISSUE THREAD

**Issue by qly612525** [openlayers/ol3#6184]
my OL3 version is OL3.14.1
Vector Tile Server is developed by myself.

But I cannot handle this problem that the engine only render the part of the point style in the boundary of the tile. The issue like this picture below:
![image](https://cloud.githubusercontent.com/assets/6295521/20738964/fe262b74-b6f1-11e6-8692-4e6a29caa551.png)

how to solve it!

**Comment by tsauerwein** [comment]
Make sure to use a buffer when generating your vector tiles. The buffer should at least have the size of your largest symbol/label.

**Comment by qly612525** [comment]
@tsauerwein Thanks.

But I have not understanded it. Is the buffer  worked in server ? I cannot find some parameter like the buffer in ol3 document. And Have some demo for it? Thanks again!

**Comment by drnextgis** [comment]
Yes, you have to use server side buffer while creating your vector tiles.
