### ISSUE TITLE
ol.format.KML writing ExtendedData implementation

### ISSUE THREAD

**Issue by raiyni** [openlayers/ol3#6189]
I'm fairly close to having writeFeatures exporting ExtendedData done and was wondering which direction to go on the assumed implementation.

Currently, I have it working where it assumes that all keys under the properties that aren't reserved will be exported.

Ex

```
ol.format.KML.writePlacemark_ = function(node, feature, objectStack) {
  var /** @type {ol.XmlNodeStackItem} */ context = {node: node};

  // set id
  if (feature.getId()) {
    node.setAttribute('id', feature.getId());
  }

  // serialize properties (properties unknown to KML are not serialized)
  var properties = feature.getProperties();

  var keys = Object.keys(q).filter(function(v) { return v !== "geometry" }); // more reserved words
  var values = ol.xml.makeSequence(properties, keys);
```

or should it assume export data is set under the 'ExtendedData' key

```
ol.format.KML.writePlacemark_ = function (node, feature, objectStack) {
  var /** @type {ol.XmlNodeStackItem} */ context = { node: node };

  // set id
  if (feature.getId()) {
    node.setAttribute('id', feature.getId());
  }

  // serialize properties (properties unknown to KML are not serialized)
  var properties = feature.getProperties();
  if (feature.get('ExtendedData')) {
    var ed = feature.get('ExtendedData');
    var keys = Object.keys(ed);
    var values = ol.xml.makeSequence(ed, keys);
```

**Comment by bartvde** [comment]
Did you have a look at the logic in the openlayers 2 KML parser? That might provide some guidance

https://github.com/openlayers/ol2/blob/75716beaacc01955f05708c03438b588fc8db55d/lib/OpenLayers/Format/KML.js#L1482:L1514

Btw, geometry is not always named geometry, you would need to use getGeometryName()

**Comment by raiyni** [comment]
Go

**Comment by raiyni** [comment]
Pulls from the properties directly, thank you.
