### ISSUE TITLE
Problems when deleting a vertex from a triangle

### ISSUE THREAD

**Issue by tchandelle** [openlayers/ol3#6190]
The first problem is that it's impossible, but I can understand why it would be logical not to allow that. This *issue* is being discussed there #6188

The second problem is that the vertex you try to delete stay visible, detached from the polygon :
![deletevertex](https://cloud.githubusercontent.com/assets/19923657/20786731/039ed234-b7a8-11e6-83e8-6055524a64f0.gif)

**Comment by ahocevar** [comment]
First problem: A polygon needs to have at least 3 vertices. So that's correct. Second problem: The editing vertex should not detach itself. So that's a bug.
