### ISSUE TITLE
view.animate with duration: 0

### ISSUE THREAD

**Issue by cs09g** [openlayers/ol3#6191]
Hello, 

I tested view.animate which will be included in next release.
and It was very easy and comfortable to use. but one thing was unclear.

I expected it will skip the animation when I put 0 as its duration. but it just worked with default duration value. I guess it is 0 so it's recognized as false. 

I think it should be working unless the duration value is NaN though it seems there's no reason to use animate then.

**Comment by bartvde** [comment]
you're right this is because of:

```duration: options.duration || 1000,```

**Comment by bartvde** [comment]
@tschaub since you did the code, any opinion on whether this is intentional?

**Comment by cs09g** [comment]
the reason I report this is 0 was working before.

**Comment by bartvde** [comment]
ah thank you for the clarification @cs09g

**Comment by bartvde** [comment]
the previous code had:

```var duration = options.duration !== undefined ? options.duration : 1000;```

**Comment by tschaub** [comment]
I proposed #6202 to allow zero duration animations.
