### ISSUE TITLE
Print to pdf scale error in 1.45

### ISSUE THREAD

**Issue by AnatolyAG** [openlayers/ol3#6193]
Hello!
I'm trying to create a pdf file with the image with the correct scale.
do according to the example [https://openlayers.org/en/latest/examples/export-pdf.html](url)
I do the calculation scale of the two methods - the result is the same

      `
        var width = Math.round(dim_img[0] * resolution / 25.4);
        var height = Math.round(dim_img[1] * resolution / 25.4);
        _map_dop.setSize([width, height]);
        _map_dop.getView().fit(ext_new, /** @type {ol.Size} */ (_map_dop.getSize());
        var tmp_size = /** @type {ol.Size} */ (_map_dop.getSize());
        var tmp_extentR = ref_map.getView().calculateExtent(_map_dop.getSize());
        var tmp_Res = _map_dop.getView().getResolution();//curr resol
        var format = 'a4';
        var resolution = 150;

        var dim_img = [180,180];// result image size on the paper (mm)
       //method 1
        var width_ext = Math.abs(tmp_extentR[0] - tmp_extentR[2]);
        var height_ext = Math.abs(tmp_extentR[1] - tmp_extentR[3]);
        var ext_min = width_ext >= height_ext ? width_ext : height_ext;
        var scale_ext = (ext_min * 1000) / dim_img[0];
        //method 2
        var size_min = tmp_size[0] >= tmp_size[1] ? tmp_size[0] : tmp_size[1];
        var scale_res = (size_min * tmp_Res * 1000) / dim_img[0];`
scale_ext and scale_res - eq
but when i print pdf the resulting scale is different from the Calculate approximately 1.45 times. What could be the problem?

**Comment by ahocevar** [comment]
You'll need to use [`ol.proj.getPointResolution`](http://openlayers.org/en/latest/apidoc/ol.proj.html#.getPointResolution) to get the true resolution for the center of the map. In projections like Web Mercator, the view resolution only matches the true resolution at the equator.
