### ISSUE TITLE
Controls have different sizes in different browsers

### ISSUE THREAD

**Issue by jmgomezpoveda** [openlayers/ol3#6194]
The default controls have different sizes depending on the browser. For example, in https://openlayers.org/en/latest/examples/custom-controls.html

In Firefox 50 (Linux), OL3 controls are 33px wide. In Chromium (Linux), the same controls are about 25px wide.

Firefox screenshot:
![firefox](https://cloud.githubusercontent.com/assets/3722516/20819310/7018e7e6-b82b-11e6-900a-2f5ca51d24cc.png)

Chromium screenshot:
![chromium](https://cloud.githubusercontent.com/assets/3722516/20819311/7360272a-b82b-11e6-8a98-c4232628d810.png)

**Comment by raiyni** [comment]
On Firefox 50 (windows 10), it is the correct size for me.

**Comment by jmgomezpoveda** [comment]
What is the "correct" size, the one in the Chromium screenshot?

**Comment by raiyni** [comment]
Yes

**Comment by jmgomezpoveda** [comment]
On further testing on the same computer:
- Firefox 50 on Linux and Chrome 55 on Windows 10: icons are 25px
- Firefox 50 on Windows and Chromium 53 on Linux: icons are 33px

Taking it to StackOverflow (http://stackoverflow.com/questions/40935550/em-has-different-px-size-in-firefox-and-chrome) to see if anyone can give further clarity on the varying size of controls.

**Comment by jmgomezpoveda** [comment]
Ok, the difference in size seems to be that in Linux, Firefox is detecting my touch screen (and thus enabling the .ol-touch style), whereas Chrome is for some reason not enabling it. The weird thing is that in Windows it is Chrome the one enabling the .ol-touch style and not Firefox.

**Comment by jmgomezpoveda** [comment]
So, controls having different sizes is fine, as per the .ol-touch style. What is still weird is why browsers are sometimes being detected as touch or not.

**Comment by jmgomezpoveda** [comment]
Checking the code I see:
`ol.has.TOUCH = ol.ASSUME_TOUCH || 'ontouchstart' in window;
`
Which looks all right. So, apparently it is an issue of Chromium in Linux and Firefox in Windows not detecting correctly the touch screen. I will close this ticket.
