### ISSUE TITLE
ol.interaction.Translate featuresAtPixel bug

### ISSUE THREAD

**Issue by onack** [openlayers/ol3#6215]
ol.interaction.Translate.prototype.featuresAtPixel_ method does not return any features if this.features_ is null, as stated by the doc the features input option is optional and should return all features if not set.

As an improvement the Translate interaction also should have a way to modify its feature array the same way as the Select interaction has getFeatures()

**Comment by tchandelle** [comment]
Is this related to #5965, if so it will be fixed in next version.

**Comment by onack** [comment]
Yes exactly related, thank you
