### ISSUE TITLE
PinchZoom: allow the view to stay at fractional zoom levels

### ISSUE THREAD

**Issue by aAXEe** [openlayers/ol3#6223]
Currently the `ol.interaction.PinchZoom ` zooms to the next whole-number zoom after the pinch completes.  
This is of course good for classic image tiles but not for vector maps. A concrete user request for this: http://stackoverflow.com/questions/40882212/openlayers3-fractional-zoom-on-touch-device-using-pinch-gesture

I suggest to add a parameter like `keepFractionalZoomLevel` to the `ol.interaction.PinchZoom` constructor so that the user can choose whether to keep the fractional zoom or not.

I already tested this idea: https://github.com/aAXEe/ol3/pull/1
A fiddle with a working example: https://jsfiddle.net/wm78prro/7/

**Comment by ahocevar** [comment]
Since wheel zooming now also does not restrict to integer zoom levels any more, I think such a change would make sense. Would you be able and willing to create a pull request?

**Comment by aAXEe** [comment]
As discussed in #6224 keeping the fractional zoom is now default.

To get the old behavior set the new `constrainResolution` parameter.
