### ISSUE TITLE
Polygon DrawInteraction generating invalid wkt (Missing first co-ordinate).

### ISSUE THREAD

**Issue by theroc** [openlayers/ol3#6225]
This may already be covered by #6063 but just so that I amend our code correctly, the change to the finishDrawing method now does a coordinates.pop[0] to remove the first co-ordinate to close the ring.
The issue this creates for us is that in saving and generating a wkt from the resulting geometry object it is no longer valid. Do we need to manually repush the last coordinate to first position before we store and validate on the server side?

On the client I drew a new polygon then used the writeGeometry method based on the geometry from it,
vm.formatWkt.writeGeometry(g);

Result:
POLYGON(5.242097085813152 54.37664472196721,6.027521079244032 53.982649002529996,4.840884829428547 53.61515629530615)

Then just for good measure, ran it through Postgis and it is now invalid:
select ST_IsValid(ST_GeomFromText('POLYGON(5.242097085813152 54.37664472196721,6.027521079244032 53.982649002529996,4.840884829428547 53.61515629530615)')::geometry)

Any help would be greatly appreciated

**Comment by theroc** [comment]
discovered an issue our side of things. sorry

**Comment by domiSchenk** [comment]
May i know what your issue was? We experience something quite similar.

**Comment by theroc** [comment]
Hi domiSchenk, our issue was we were overriding the geometryFunction, if you have a look in the ol.Interaction.Draw

Have a look here:
https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/draw.js

Line 153-164, specifically dealing with Polygons.

**Comment by icemagno** [comment]
Hi  theroc ! You save me a lot of pain! 
This simple function is causing the Polygon to not close:

```
me.draw = new ol.interaction.Draw({
	source: me.vectorSource,
	type: 'Polygon',
	geometryFunction: function(coords, geom) {
		if (!geom) {
			geom = new ol.geom.Polygon(null);
		}                                
		geom.setCoordinates(coords);
		return geom;
	}
});
```

I removed the function because I don't need the geometry function by now but this function is making a invalid polygon.

I'm using the last OL-Cesium lib version.
