### ISSUE TITLE
Consider leaving layer canvas composition up to the browser

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#6231]
Since we now have a single canvas element per layer, I'm curious if we could see better performance by leaving composition up to the browser (instead of drawing all to a single map canvas).

**Comment by ahocevar** [comment]
My experiments in #6182 showed that css rotation (even if hardware accelerated) is quite slow. And then there's vector layers which are directly rendered to the map canvas. But if someone wants to work on that and the result is a performance gain, I'd not be opposed.

**Comment by tschaub** [comment]
Right.  That was a hasty suggestion.  Vector layers make this a non-starter.
