### ISSUE TITLE
ol.style.Fill.setColor issue

### ISSUE THREAD

**Issue by drnextgis** [openlayers/ol3#6233]
Hello. I've faced with pretty strange issue (see jsfiddle https://jsfiddle.net/9xnsj270/). Why I have to set radius? It looks like some side effect here.

**Comment by tchandelle** [comment]
`Circle` and `RegularShape` styles are pre-rendered at construction or when you change the radius.

There have been discussion to move the rendering part to the layers, see #5775.

**Comment by drnextgis** [comment]
Thanks for response. Close as duplicate of #5775.
