### ISSUE TITLE
Vector tiles not styling properly beyond the source's maxzoom level ...

### ISSUE THREAD

**Issue by Tom-Cuthill** [openlayers/ol3#6234]
Hi,

I have a cached repository of Open Street Map MBTiles.  The max zoom level is 14.  I want my map to render down to zoom level 19, using the vertices exposed from level 14.  

I was lead to believe from here:  http://gis.stackexchange.com/questions/127137/openlayers-3-scale-past-nativezoom-like-leaflet that if I set the max zoom level in the source Vector tile to 14, and set the maxZoom level in the view to 19, that the tiles would render correctly down to zoom level 19.  What I am seeing is fat dithered lines beyond level 14, even though the stroke width is 1.

Here is my code in typescript:

private getMapOptions(OSMapURL: string): olx.MapOptions {
            var layers: Array<ol.layer.Base> = new Array<ol.layer.Base>();
            var OSMTileURL: string = OSMapURL + "/{z}/{x}/{y}.pbf";
            var osmTileOptions: olx.source.VectorTileOptions = <olx.source.VectorTileOptions> {
                attributions: '© <a href="https://www.openstreetmap.org/copyright"> OpenStreetMap contributors</a>',
                format: = new ol.format.MVT();
                maxZoom: 14,
                tileGrid: ol.tilegrid.createXYZ({ minZoom: 4, maxZoom: 14 }),
                tilePixelRatio: 16,
                url: OSMTileURL
            };
            var OSMsource: ol.source.VectorTile = new ol.source.VectorTile(osmTileOptions);
            var osmVectorLayerOptions: olx.layer.VectorTileOptions = <olx.layer.VectorTileOptions>{
                source: OSMsource,
                style:OperationsControllerModule.createMapboxStreetsV6Style(),
            }
            var OSMLayer: ol.layer.VectorTile = new ol.layer.VectorTile(osmVectorLayerOptions);
            layers.push(OSMLayer);

            var initCenter = ol.proj.transform([133.9, -23.69], 'EPSG:4326', 'EPSG:3857');
            var viewOptions: olx.ViewOptions = <olx.ViewOptions>{
                // projection: ol.proj.get("EPSG:4326"),
                center: initCenter,
                minZoom: 4,
                maxZoom: 19,
                zoom: 12
            };

            var view: ol.View = new ol.View(viewOptions);

            return <olx.MapOptions>{
                layers: layers,
                target: 'map',
                view: view
            }
        }

Any insights into what I may be doing wrong would be greatly appreciated.

Cheers,
Tom

**Comment by ahocevar** [comment]
Configure your ´ol.layer.VectorTile` instance with `renderMode: 'vector'`. The effect of that setting is that no pre-rendered raster tiles will be generated, and you'll get proper rendering according to the style at any resolution.
