### ISSUE TITLE
Polygon CanvasPattern fill issue

### ISSUE THREAD

**Issue by norric** [openlayers/ol3#6240]
Since 3.19, a polygon using a CanvasPattern fill (and no stroke) ignores the first vertex in the geometry:

![3 18](https://cloud.githubusercontent.com/assets/2145089/21142790/1030c458-c144-11e6-99ef-d8a76335c5fc.png)
https://jsfiddle.net/norric/vbLsj0rj/

![3 19](https://cloud.githubusercontent.com/assets/2145089/21142791/1034a618-c144-11e6-8c5c-7929139b73b3.png)
https://jsfiddle.net/norric/ykxaez1o/

Adding a stroke style (even transparent) is a viable workaround. Tested and seen on all subsequent releases.

Might be related to https://github.com/openlayers/ol3/issues/6210 ?

**Comment by ahocevar** [comment]
Your polygon geometry is invalid. The last point needs to equal the first. See this [updated JSFiddle](https://jsfiddle.net/ahocevar/ykxaez1o/3/).

**Comment by norric** [comment]
Thanks. I was not aware of that.
