### ISSUE TITLE
VectorTile.changed() regression in 3.20.0

### ISSUE THREAD

**Issue by achimha** [openlayers/ol3#6241]
Changing some properties affecting how a VectorTile layer is rendered and then calling `ol.layer.VectorTile.changed()` to redraw the layer works in 3.19.1 and earlier but has no effect in 3.20.0. If the layer is redrawn for another reason (panned, etc.), the changes show so it's clearly the `changed()` method not doing anything anymore.

Is this a regression or intended behavior? Note that I do not want it to reload data from the source, just redraw itself.

**Comment by ahocevar** [comment]
Regression confirmed. Fix coming up.

**Comment by achimha** [comment]
Great, thank you. If you got a hint where to find it, I could try a local patch to allow me to make progress. Going to 3.19.1 is difficult to me due to some 3.20.0 fixes I depend on.

**Comment by achimha** [comment]
Thanks, that workaround does the job but it means the whole data is reloaded. If you know where the regression is and can point me towards it, I can try to find a solution myself. At this point I don't know enough about the internal structure to pinpoint the location or changeset that caused the regression.

**Comment by ahocevar** [comment]
Patience achimha - a pull request with the fix will be up in 10 minutes.

**Comment by ahocevar** [comment]
@achimha See #6246.

**Comment by achimha** [comment]
Thank you very much, works great!

**Comment by craigsnyders** [comment]
@ahocevar I'm using 3.20.3 but the original issue still occurs.  Taking a look through changelog for 3.20.1 / 3.20.2 / 3.20.3 but I can't see it... Has the change made it in, or regressed?

**Comment by marcjansen** [comment]
@craigsnyders AFAICT #6246 is not part of 3.20.1, the latest release.

**Comment by ahocevar** [comment]
A version with that change has not been released yet. But it will be in the next release of course.
