### ISSUE TITLE
Image Styles in features with MultiPolygon geometry

### ISSUE THREAD

**Issue by jgalrito-i9** [openlayers/ol3#6249]
Not sure if this is intended behaviour, but in the case mentioned in the title the styles are not rendered. Intuitively I think it should still apply the style to center of the geometry extent (or alternatively to the center of each of the polys)

**Comment by ahocevar** [comment]
By default, image styles get applied to points only. If you want image styles to get applied to multipolygons, you'll need to set a geometry in the style function:
```js
var imageStyle = new ol.style.Style({
  geometry: function(feature) {
    return feature.getGeometry().getInteriorPoints();
  },
  image: new ol.style.Circle({
    radius: 5,
    fill: new ol.style.Fill({ color: 'black' })
  })
});
```
