### ISSUE TITLE
forEachLayerAtPixel does not work when tile or image pixel ratio differs from device pixel ratio

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol3#6250]
It appears that it the event pixel location does not match the canvas pixel value that is assessed.
Visible in the console here: http://jsfiddle.net/1zo8r5Lp/445/

Possibly related to #6245

**Comment by ahocevar** [comment]
@Benjaki2 It is not related to #6245. It happens with all layers whose image or tile pixel ratio is different from the device pixel ratio.
