### ISSUE TITLE
One MVT feature is rendered as two

### ISSUE THREAD

**Issue by drnextgis** [openlayers/ol3#6256]
During making [demo](https://jsfiddle.net/_DR_/32b7b6dv/3/) for another issue I've faced with the following problem - one feature of MVT layer is rendered as two:
![screenshot_2016-12-15 11 50 13](https://cloud.githubusercontent.com/assets/866124/21217614/26e1c546-c2be-11e6-87a1-8ac474a33c70.png)

**Comment by ahocevar** [comment]
That was an issue only before v3.20.0. It's fixed.
