### ISSUE TITLE
ol.layer.VectorTile clips labels on tile boundary?

### ISSUE THREAD

**Issue by aAXEe** [openlayers/ol3#6275]
I'm using [Mapzen vector tiles](https://mapzen.com/documentation/vector-tiles/) for a map.
`ol.layer.VectorTile` clips my labels at the tile boundaries instead of drawing them completely:

![grafik](https://cloud.githubusercontent.com/assets/3298652/21288369/a1a9af18-c481-11e6-8913-42760277b2ac.png)

Full example: https://jsfiddle.net/rn3qc4ca/

As the [mapbox vector example](http://openlayers.org/en/latest/examples/mapbox-vector-tiles.html) is basically the same (and works as expected) I have no idea that the problem is.

Note: I am using the `MVT` format in the example. Using `TopoJSON` or `GeoJSON` results in the same problem.

This question might be about the same problem: http://stackoverflow.com/questions/40234804/ol3-geoserver-vector-tile-labels-gets-cropped/

**Comment by ahocevar** [comment]
The Mapbox tiles in the [`mapbox-vector-tiles.html`](http://openlayers.org/en/latest/examples/mapbox-vector-tiles.html) example repeat label points on neighbouring tiles with a dynamic buffer, depending on the expected label size. Mapzen tiles don't do that.

That said, the problem is with the tiles you are loading, not OpenLayers rendering them.

**Comment by aAXEe** [comment]
Thanks a lot for that description!

**Comment by pksorensen** [comment]
I wrote my own tiling algorithm that creates vector tiles, but I fail to see how I should create the auxiliary label points. 

Lets say I detect if they are close to the border, then i could create a label point in the tile next to it, but I dont see how I will ever get the styles to line up such the text from both tiles are drawn so they look like one label. ? can I read about this somewhere?

**Comment by pksorensen** [comment]
sorry, I understand it now. The buffer of the tiles makes up for this. So the buffer should be large enough such the point is in the same location.
