### ISSUE TITLE
IndexSizeError on IE with SVGs

### ISSUE THREAD

**Issue by bencevans** [openlayers/ol3#6281]
Rendering SVGs on IE for Icons throws IndexSizeErrors.

Example: https://jsfiddle.net/yy12g00g/4/

Tested and failing on IE11.
Working correctly on IE10 & Edge.

**Comment by bartvde** [comment]
did you read #3220 ?

**Comment by bencevans** [comment]
Yes, been through a few #3220 #2861 #4409

**Comment by ahocevar** [comment]
You have to set `imgSize` on the icon style for IE support

**Comment by artnas** [comment]
If some unfortunate soul like me ever encounters this issue and adding 'imgSrc' doesn't help - I fixed it by converting my .svg to .png and then **REMOVING** imgSize.

This crashes on IE11:
![image](https://user-images.githubusercontent.com/14143603/59340032-8a878180-8d05-11e9-8c87-d59036070731.png)

This works:
![image](https://user-images.githubusercontent.com/14143603/59340060-907d6280-8d05-11e9-8f85-195ecc86bf34.png)

**Comment by ben-cloud9** [comment]
getting the same IndexSizeError on IE11, even with `imgSize` set (see code below)
```
iconImage = new _style.Icon({
          src: styles.icon.image.url, // valid svg URI, base 64 encoded and renders in IE11 on it's own
          imgSize: styles.icon.image.size || [32, 32],
          scale: styles.icon.image.scale || 1,
          anchor: styles.icon.image.anchor || [12, 24],
          anchorXUnits: 'pixels',
          anchorYUnits: 'pixels',
          rotation: 0,
          size: styles.icon.image.size || [32, 32],
          opacity: styles.icon.image.opacity || 1
});
```
and these are the values of the arguments given to `context.drawImage`:
![image](https://user-images.githubusercontent.com/37899397/59609975-5bf81500-9110-11e9-8016-e991fe774a0a.png)

![image](https://user-images.githubusercontent.com/37899397/59610159-b72a0780-9110-11e9-8281-abb2ef1ef11c.png)

can anyone help?

ol v5.3.3
IE11 v11.0.9600.19301

**Comment by arekgofi** [comment]
Getting the  same error  IndexSizeError on IE11
` const style = new ol.style.Style({
      image: new ol.style.Icon({
        src: "data:image/svg+xml;charset=utf-8," + encodeURIComponent(svg),
        imgSize: [16, 16]
      })
});`

openlayers | 4.2.0
IE11 v 11.1331.16299.0

**Comment by lennerd** [comment]
Make sure that the SVG image has the same size you specified in `imgSIze` and that nothing in your SVG is overlapping the image boundaries.

**Comment by YuK1Game** [comment]
Is this unresolved?
I have the same problem.
