### ISSUE TITLE
Canvas rendered forEachLayerAtPixel does not work with multiple layers

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol3#6282]
The [Coordinate value](https://github.com/ahocevar/ol3/blob/3e8c8791d08d9a5ffce82453564b4969684dc530/src/ol/renderer/canvas/map.js#L217-L218) is being manipulated inside the [layer loop](https://github.com/ahocevar/ol3/blob/3e8c8791d08d9a5ffce82453564b4969684dc530/src/ol/renderer/canvas/map.js#L221-L232) so that the method only works for the first layer.

**Comment by marcjansen** [comment]
Outch. Do you think you can come up with a PR incl. tests?

**Comment by Benjaki2** [comment]
Thanks for your work on this @tschaub.
