### ISSUE TITLE
Different style/marker for each point on a MultiPoint feature

### ISSUE THREAD

**Issue by bjdash** [openlayers/ol3#6287]
I have a MultiPoint feature with the following geo json.

```
{
    "type": "Feature",
    "geometry": {
        "type": "MultiPoint",
        "coordinates": [
            [
                -123,
                58
            ],
            [
                -152.32,
                17.5
            ],
            [
                52.02,
                42.64
            ]
        ]
    }
}
```
When I draw this on map and apply any icon through a style function, its applied for all points.But I would like to show all 3 coordinates above with different icons on map. Is there any way I can add different markers for each coordinates in a Multipoint feature?

**Comment by bartvde** [comment]
Please don't cross-post http://gis.stackexchange.com/questions/222187/openlayers-3-different-style-marker-for-each-point-on-a-multipoint-feature

**Comment by bjdash** [comment]
I wasn't getting any solution from there so thought adding here might help

**Comment by bartvde** [comment]
you asked it there 1 hour ago, what do you expect?
