### ISSUE TITLE
v3.20.1 publishing issue

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol3#6293]
Appears that something went awry when the publish.sh was run for v3.20.1. The version seems to be  missing some recent commits such as #6251

**Comment by bartvde** [comment]
The 3.20.1 release is not done off master, it only includes actual regressions since 3.20

See the release notes: https://github.com/openlayers/ol3/releases/tag/v3.20.1

**Comment by bartvde** [comment]
But I see @tschaub just found a reason for 3.20.2 (#6290) so it might make sense to include #6251 as well although technically speaking this is not a regression right @Benjaki2 ?

**Comment by Benjaki2** [comment]
Yep, not a regression. Thanks for the feedback @bartvde.
