### ISSUE TITLE
Cluster geometryFunction not triggered

### ISSUE THREAD

**Issue by oufresh** [openlayers/ol3#6298]
Hello, I'm currently using the last release. geometryFunction of ol.source.Cluster is not triggered when the layer change.
I tried both to force the layer redraw with the changed() method of the layer and with map.getView().setZoom(GisMap.map.getView().getZoom()*1.00000000000000001) (which I don't actually like).
This is how the layer is declared

this.clusters = new ol.layer.Vector({
        title: 'ClusterLayer',
        updateWhileAnimating: true,
        updateWhileInteracting: true,
        source: new ol.source.Cluster({
                distance: 40,
                source: vectorSource,
                geometryFunction: that._clusterGeometryFunction
            }),
        style: that._ClusterStyle
    });

Is this behaviour right? I expect that the geometry function to be called if I want to include features in the cluster.

Thank a lot.

**Comment by ahocevar** [comment]
You have to call `changed()` on the source, not the layer.
