### ISSUE TITLE
cannot add "dispose" into custom build

### ISSUE THREAD

**Issue by cs09g** [openlayers/ol3#6299]
Hello, 

I want to use "dispose" with my custom build but "ol.Disposable" is not being added as other method. Where should I put "ol.Disposable" to include into my build?

I tried:
1. as usual methods
```
"exports": [
    ...
    "ol.Disposable"
]
```
result: 
ERR! No matching symbol found: ol.Disposable

2. noticed from "info.json". it is in "base" so,
```
"compile": {
    ...
    "base": [
        "ol.Disposable"
    ],
    ....
}
```
result: 
ERR! compile "--base" is not a valid options 
ERR! compile 
ERR! compile Sample usage: --compilation_level (-O) VAL --externs VAL --js VAL --js_output_file VAL --varning_level (-W) [QUIET | DEFAULT | VERBOSE]
ERR! compile Run with --help for all options and details
...

How can I use "dispose" with my build?

**Comment by ahocevar** [comment]
`dispose` is not part of the public API, and there should be no need to use it.

**Comment by cs09g** [comment]
Is there any way to remove map by API? or I just need to remove it by setting null and deleting map div?

**Comment by bartvde** [comment]
```map.setTarget(null)```
