### ISSUE TITLE
canvas map cannot be export

### ISSUE THREAD

**Issue by jacobking** [openlayers/ol3#6304]
what's the rules of export map to png?I packaged map by wmts,but cannot export!Is there is a right way to export map otherwise right key ?here is the reference [http://openlayers.org/en/latest/examples/export-map.html?q=export](http://openlayers.org/en/latest/examples/export-map.html?q=export),this refrence's vector is build by GeoJSON,I build by wmts,that's the difference, here is my demo [https://jsfiddle.net/56Lc2749/4/](https://jsfiddle.net/56Lc2749/4/),
here is the error
`Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

**Comment by mprins** [comment]
> what's the rules of export map to png?
ultimately it depends on your browser; read https://stackoverflow.com/questions/34743987/canvas-image-crossplatform-insecure-error and related questions

**Comment by jacobking** [comment]
@mprins Thanks for your reply,  I use the chrome of  v55.0.2883.75 m,the official demo can download,but the demo i write canot work,the link is here [https://jsfiddle.net/jacobking/56Lc2749/4/](https://jsfiddle.net/jacobking/56Lc2749/4/)

**Comment by sookoll** [comment]
you have to use tiles/data from same origin as your application or server should allow cross-origin requests.
