### ISSUE TITLE
Esri Map Services

### ISSUE THREAD

**Issue by underbluewaters** [openlayers/ol3#654]
Any plans to add native support in OL3 for Esri-based map services? If not are any plugins available?

**Comment by hammos** [comment]
Have there been any updates to this issue? Is anyone actively looking to add support to OL3?

**Comment by fredj** [comment]
AFAIK nobody is working on this

**Comment by ajturner** [comment]
Curious if [terraformer](https://github.com/Esri/Terraformer) or [GeoServices-JS ](https://github.com/Esri/geoservices-js) could make this easier.

**Comment by bartvde** [comment]
Implemented with #3263 so closing this ticket
