### ISSUE TITLE
Cesium integration

### ISSUE THREAD

**Issue by elemoine** [openlayers/ol3#717]
The Cesium integration work happens in the [cesium branch](https://github.com/openlayers/ol3/tree/cesium) of the main ol3 repository.

I recently reviewed the code of this branch, the goal being reaching a state where the cesium branch can be merged into master.

My review comments are the following:

- We need to sort out the circular dependency problem. Search
"view3d.js" in build.py.
- Set ol.ENABLE_CESIUM to false by default. The ol3/cesium integration
code will add to the size of the build, so I'd suggest that this code
is not included in the default build.
- Make sure the "cesium" example works when hosted. This will require
create an ol-cesium.js build if we ol.ENABLE_CESIUM defaults to false.
- There are exports that we don't want: ellipsoid.export,
projection.exports (project and unproject),
cesiumimageryprovider.exports, view3d.exports.
- At this point I don't think we want to expose/export View3D. I think
I'd even suggest to remove View3D entirely, and just have a
getCameraFromView2D function in the cesium renderer.  The
View2D:createView3D_ function indeed rather Cesium-specific to me (it
assumes a WGS84 ellipsoid).
- ol.Ellipsoid includes new functions like cartesianToCartographic.
I've been wondering if Cesium has the same functions, and if we could
rely on Cesium instead of having our own. It sounds like duplicated
math code to me, but I may be wrong.
- ol.Ellipsoid, ol.View2D:createView3D_, and
ol.vec.Mat3.fromQuaternion depend on goog.vec.Vec3 and goog.vec.Mat3.
Up to now, we've tried to depend on goog.vec.Vec4 and goog.vec.Mat4
only, to avoid pulling in too much code. Do we really need Vec3 and
Mat3, or could we just get by with just Vec4 and Mat4?
- ol.renderer.cesium.ImageryProvider includes TODOs that seem to
deserve attention.
- ol.renderer.cesium.ImageryProvider inherits from
Cesium.ImageryProvider. @twpayne said that it's a problem because we
can't build ol3 if Cesium is not present. It made sense when he said
that to me, but I'm not sure anymore. I think the compiler won't
complain as long as we have the cesium.js externs file. I may be
missing something. This is to be investigated. Also, I've been
wondering if inheriting is at all necessary here, as ImageryProvider
(https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ImageryProvider.js)
seems to just be an interface.
- The current cesium code has limitations: it only supports tile
layers, and the EPSG:3857 projection (ol.projection.EPSG3857 is the
only projection implementing "project" and "unproject"). I think it's
ok to have limitations, but we should correctly handle the cases that
we don't support (e.g. by adding assertions).
- We currently have two rendering loops in ol.renderer.cesium.Map.
Instead we should rely on the global ol3 loop (renderFrame). By
setting animate to true on the frameState we can have a continuous
loop, as the Cesium one.
- There's currently no tests for the Cesium code. We need to figure
out where adding tests would make sense.

**Comment by fredj** [comment]
See https://github.com/openlayers/ol3-cesium
