### ISSUE TITLE
Mobile editing

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#873]
For editing on mobile devices, we will want to offer an editing UI that is optimized for touch interfaces. This could e.g. be editing tools that work by moving the map around an editing cursor, instead of placing vertices on touch.

**Comment by fredj** [comment]
@ahocevar: can we close this issue?

**Comment by ahocevar** [comment]
I still have a branch for that, I just haven't gotten to work much on it yet. So please leave it open.

**Comment by ahocevar** [comment]
Closing this, because I haven't gotten to work on it for such a long time.
