### ISSUE TITLE
ScaleLine control assert fails when using a projection without units defined

### ISSUE THREAD

**Issue by sphvn** [openlayers/ol3#977]
I'm using "EPSG:26782" NAD27 LA South. Which doesn't contain a `units` property. 

Causing this assert to fail:

```javascript
20725: goog.asserts.assert((this.units_ == ol.control.ScaleLineUnits.METRIC || this.units_ == ol.control.ScaleLineUnits.IMPERIAL) && projectionUnits == ol.ProjectionUnits.METERS || this.units_ == ol.control.ScaleLineUnits.DEGREES && projectionUnits == ol.ProjectionUnits.DEGREES);
```

Specifically ```projectionUnits == ol.ProjectionUnits.METERS```.

My ScaleLine control is using imperial units as follows and still works as expected.

```javascript
new ol.control.ScaleLine({
  units: ol.control.ScaleLineUnits.IMPERIAL
})
```

**Comment by ahocevar** [comment]
This issue appears to be fixed. The refactoring mentioned above has been implemented with #4234.
